### ISSUE TITLE
Quotes improperly escaped in description

### ISSUE THREAD

**Issue by silksow** [facebookincubator/facebook-for-woocommerce#10]
Single and double quotes display literal escape slash in Facebook description.

Steps to reproduce:

1. Create WC product
2. Use single or double quotes, apostrophes in FB description box
`It's a new, totally "amazing" product`
3. Update product
4. FB shop displays: 
`It\'s a new, totally \"amazing\" product`

**Comment by dmitridr** [comment]
Thanks for pointing this issue out. Is this related to qTranslate somehow?
I tried the repro steps but cannot get the repro, the description shows up without the backslashes.

**Comment by silksow** [comment]
I am not using qTranslate, but this has been an issue since my initial install, using 1.4.3 and the last version of WooCom, with minimal plugins. It does seem like a simple error in regex, possibility in the shortcode escape function.

**Comment by dmitridr** [comment]
We've fixed this issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
