### ISSUE TITLE
Compatibility Issue: WooCommerce Product Bundles extension

### ISSUE THREAD

**Issue by outerbridge** [facebookincubator/facebook-for-woocommerce#100]
Our client's shop uses the official WooCommerce Product Bundles extension.  We want to use this plugin too, but unfortunately, enabling the FB4WC plugin breaks the ability to add bundles to a product.

Screenshot of a new product's product data with FB4WC disabled:
https://imgur.com/a/pwTC8

Screenshot with FB4WC enabled:
https://imgur.com/a/hey5j

Please can you assist.

Many thanks
Mike

**Comment by sammul** [comment]
Hi

Thanks for letting us know the extension conflict. I'll mark this issue as feature-request and we will try to address in the future versions.

Facebook

**Comment by dmitridr** [comment]
Strange, I wonder what causes the breakage. Are you using 1.6.4? 

We had a bug in 1.6.4 that caused other tabs in that section to break, so upgrading to v1.6.5 could potentially fix the compatibility issue.

**Comment by outerbridge** [comment]
Hi

I'm using v1.6.5 and the products are now available for the bundle but each time one is put in the bundle, it appears 6 times!  Deleting 5 of them and then saving brings all 6 back, which obviously isn't a workable position!!!

Many thanks
Mike

**Comment by superg28** [comment]
Not sure if this is related but we can't get product bundles to display on Facebook with this plugin? Keeps saying the product isn't published so now one can see it, but it is published on the site

**Comment by dmitridr** [comment]
@superg28 We haven't fixed the compatibility issue so I'm not surprised that it's broken. Is there maybe some other setting here, like the bundles are in a different language (non-default language?). 

If you can give us a screenshot of the product settings page for the bundle, and one for the FB side, we can try to reproduce it on our test servers, and maybe fix the longstanding compatibility issue as well.

**Comment by superg28** [comment]
Bundles are in the default language (English)

What settings would you need to see for the product?

**Comment by dmitridr** [comment]
Thanks for confirming that, so it's not hidden due to language then. Any settings specific to the bundled product you are setting up which doesn't work would be helpful so our team can essentially create the same product in our store. Or is it a problem for any product you create regardless of settings?

Also, I'm not sure which version you are using, but I would try on our latest version `1.7.11` and also an older version, this would be helpful to us to understand if there was some change in the behavior of our plugin that caused your problem.

**Comment by mengyingdu** [comment]
Hi @outerbridge and @superg28 ,
We will have basic support for bundle products in next release.
Bundle products can be synced, pixel events can be fired (view content, add to cart, initiate checkout , etc) However, we have issues if you disable 'redirect to cart after successful adding products' in your settings. (only if a bundle product which includes a variable product in this case, we can't get value from cart if we fire addToCart from ajax click, ALL other events work correctly.)

I would suggest you enable to redirect to cart directly in you woo settings to guarantee pixel fire events on correct value.

Thanks.

**Comment by mengyingdu** [comment]
Hi @outerbridge and @superg28 ,

We added support for bundle products extension in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6)

Thanks.

**Comment by wdetcetera** [comment]
@mengyingdu I have got the latest version of the facebook for woocommerce and I have problem with the feed. All the bundle product are not coming up

**Comment by bmzero** [comment]
I'm having this issue on current versions of Woo, WP, and the Woo for Facebook extension. Has anyone figured out how to get bundled products into the Facebook catalog?
