### ISSUE TITLE
Error message and products not syncing 

### ISSUE THREAD

**Issue by TSB2019** [facebookincubator/facebook-for-woocommerce#1002]
I receive the following error message: Facebook extension error: Facebook for WooCommerce
Unsupported post request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

And my products are not syncing properly. Hidden products are also showing on the shop page.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
