### ISSUE TITLE
unable to update facebook api token

### ISSUE THREAD

**Issue by glowskinco** [facebookincubator/facebook-for-woocommerce#1003]
trying to update facebook token however when i click on settings it just opens a new browser and doesnt allow me to update token?

**Comment by jacobabey1** [comment]
Yes , this had been a trending issue , and no one is helping out

**Comment by sushmaad** [comment]
Hi, Can you attach some screenshots what do you mean by new browser? Or is it a window that pops-up, If its a window can you go to Advanced Options > Update Token?

**Comment by Sophiemake** [comment]
I have the same issue, I migrated my site and changed domain name, I have deleted and reinstalled pixel plugin but get the same result. API token n longer valid, when I click 'settings' I get an error message.
![Screenshot (1)](https://user-images.githubusercontent.com/50872548/58096351-caf35400-7bcc-11e9-99a6-7ae35afc3486.png)
![Screenshot (2)](https://user-images.githubusercontent.com/50872548/58096362-d181cb80-7bcc-11e9-9efa-dba7d8f42e74.png)

**Comment by Avakiano** [comment]
hi, 

i solved that, by signin out on all accounts on fb, and signing in the correct one, then it allows. I had that issue because it takes the las sign in account on fb.

i hope it helps guys.

**Comment by beezwings** [comment]
I'm having the exact same issue, and I'm logged into the correct FB account.

**Comment by djwilko12** [comment]
Having same issues! It was working fine before. The same thing happens on all my sites. All say sorry, something went wrong

**Comment by glowskinco** [comment]
Is there another plugin anyone else has looked into that works? 

Thank you 😊 

Amber 
Glow SkinCo ✨✨✨

www.glowskinco.com.au

**Comment by glowskinco** [comment]
Also it is signed into the correct account. I’ll try logging out and back in and see what happens 

Thank you 😊 

Amber 
Glow SkinCo ✨✨✨

www.glowskinco.com.au

**Comment by glowskinco** [comment]
This is what I get even when I log out and log back in 



Thank you 😊 

Amber 
Glow SkinCo ✨✨✨

www.glowskinco.com.au

**Comment by Sophiemake** [comment]
Hi Amber, I seem to have got mine working again, I disabled a few other plugins, and now I can access the settings to reset the API token. Now I need to activate my plugins and see if it keeps working/ which one is causing it.  If this doesn't work, webappick plugin was recommended to me as an alternative product feed, alrhough I haven't tried it myself. Good luck!

**Comment by jacobabey1** [comment]
@Sophiemake  , did  what you suggested , but I  can't delete the settings 
![wwww](https://user-images.githubusercontent.com/18306206/58169652-ca1bfa00-7c80-11e9-929f-7e95b1ea917f.PNG)

**Comment by jacobabey1** [comment]
@Sophiemake  , did  what you suggested , but I  can't delete the settings

**Comment by Avakiano** [comment]
first you must "delete" the shop on FB if you have or the catalog. (I wipe
everything)

but, even resetting everything, it doesn't connect with Instagram. i think
the facebook and instagram have the issue, and they don't care about, with
the other commerce systems works fine, like prestashop or shopify. I have 7
people with the same problem, and they have woocommerce, also i think that
they (Facebook) are promoting to migrate to those commerce systems .

btw, the plugin haven't updated with the with the last version of WP


regards!

**Comment by diwangcmu** [comment]
Hi all, this issue should have been fixed. Can you retry and let us know if the problem persists? Thanks!
