### ISSUE TITLE
Plugin connection error facebook-for-woocommerce Debug Ready

### ISSUE THREAD

**Issue by sanchezpu** [facebookincubator/facebook-for-woocommerce#1009]
Debug Ready  
Multiple Reports

WooCommerce version: 3.3.3
WordPress version: 4.9.10
Plugin version : 1.9.10
![image](https://user-images.githubusercontent.com/843291/58187712-f0d83180-7c7c-11e9-906e-d8323763deea.png)

The URL of your website: https://onboardsk8.com
The URL of your Facebook Page: https://www.facebook.com/onboardshop/
The URL(s) of where you took your screenshot(s): https://www.facebook.com/ads/dia?origin=https%3A%2F%2Fonboardsk8.com+&merchant_settings_id#_=_

I need help with my facebook page is https://business.facebook.com/onboardshop/ 
and my webtiste based on wooocmerce is https://onboardsk8.com

Our woocomerce-based virtual store was connected without any problems and synchronizing products with your platform, but a few weeks ago it stops working, when you try to configure the Facebook for woocoemrce plugin that you download from your platform it indicates that the page has a store connected, which is false since the page is not letting us see any store.

Please see this video where we explain the error : https://www.loom.com/share/089a573b11484603bae3dbfeccea0a2a # @ @

**Comment by sushmaad** [comment]
Can you please retry again. Thanks!

**Comment by sushmaad** [comment]
Closing this issue, reopen if you still have issues
