### ISSUE TITLE
After deleting the facebook page, I cannot reconfigure the plugin

### ISSUE THREAD

**Issue by PSinke** [facebookincubator/facebook-for-woocommerce#1062]
I needed to change my Facebook pagename, but FB didn't let me, so I created a new page with the right name, and deleted the old page. The Facebook for WooCommerce plugin was configured for the old page.
Now when I go to the plugin settings, it shows me the 'Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token".' message. But after clicking the 'settings' button, the popup is showing an error (see screenshot). 

I cannot find a 'reconfigure' button anywhere, even after changing my FB password, like some suggested. 

Where can I find the stored information for the plugin, so i can perhaps manually reset it?

![FBWoo_Error](https://user-images.githubusercontent.com/2011552/60348388-b8d0b680-99bf-11e9-8c02-032d6a6468a6.jpg)

Any help would be greatly appreciated.

**Comment by PSinke** [comment]
After some fiddling around with the Facebook URL in the popup (changing the merchant_id to the new page id) I was finally able to reconfigure the settings. 
Maybe this helps someone in a similar situation.

**Comment by jeffsandoval014** [comment]
How exactly did you do it?
