### ISSUE TITLE
Product Not Sync to Facebook

### ISSUE THREAD

**Issue by jonathanronald** [facebookincubator/facebook-for-woocommerce#1065]
Product not sync to my facebook catalog

**Comment by Mediariser** [comment]
i have used facebook-for-woocommerce plugin to my woocommerce the plugin is showing enable shop, once enabled its not syncing & shows Pending Catalog Approval the product and the catalog created in account is empty 
![image](https://user-images.githubusercontent.com/52456003/60514808-e12a1f00-9cf7-11e9-8444-8bada04f2c08.png)

**Comment by sushmaad** [comment]
Hi, For how long pending approval shown? Sometimes it might take longer for the products to get approved and to show up on page shop.

**Comment by Mediariser** [comment]
> Hi, For how long pending approval shown? Sometimes it might take longer for the products to get approved and to show up on page shop.

ok, but i just deleted and recreated yesterday i thought this is due to plugin, but before this it was under approval for almost 6 days so i think there is some problem with the plugin

even after 6 days it was pending for approval

**Comment by sushmaad** [comment]
Can you provide more details store url, facebook page?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
