### ISSUE TITLE
Prices with discounts are incorrect

### ISSUE THREAD

**Issue by micb11** [facebookincubator/facebook-for-woocommerce#107]
Hi 

When a products is discounted on the website is not showing the correct price on Facebook.

This is the product on the site. It was £231 but it has been reduced to 207.90 including VAT.

https://doorsdirect2u.co.uk/product/jeld-wen-cottage-horizontal-7-panel-white-oak-veneer-fire-door-44mm/?attribute_pa_size=2040-x-726-x-44mm726oakhflf

HOWEVER

On the facebook page it is showing 207.90 crossed out and instead showing the new price excluding VAT at £173.25. It should be £231 crossed out and £207.90 as the new price

https://www.facebook.com/commerce/products/1238789899555059/

**Comment by mengyingdu** [comment]
Hey micb11,

I checked your website product page and your Facebook product page, the price is correct as you describe (See screen shot). If you do see different things, it should be weird. Can you upload what you see on your FB page? 

£231 crossed out and showing the new price 207.90 including VAT.
![price with discount](https://user-images.githubusercontent.com/24535640/31919538-fecf936c-b817-11e7-8f2c-c117c9c19760.jpeg)

**Comment by dmitridr** [comment]
Depending on your plugin version this could potentially be fixed by upgrading to the latest one.
#63 had a similar problem with VAT.

**Comment by micb11** [comment]
I upgraded to the latest plugin and did a force resync now it says it is resyncing 421 products but there are only 4 showing on the facebook site. I t has been doing it for a few hours now?

**Comment by mengyingdu** [comment]
Hi,

I check your Facebook page https://www.intern.facebook.com/doorsdirect2u/ and your catalog. It seems your catalog has been deleted on Nov 8, 2017. It has 421 products group. Can you try delete setting and re-setup? It should help product sync problem.

**Comment by mengyingdu** [comment]
Hi micb11,

Does it work now?

**Comment by mengyingdu** [comment]
Hi,
The new version should work for products with discount. I close this issue for now, let me know if you still have problem about this.

Thanks.
