### ISSUE TITLE
Plain text - email and name from WordPress database to pixel? 

### ISSUE THREAD

**Issue by rafaljosko** [facebookincubator/facebook-for-woocommerce#1073]
Official plugin facebook for woocommerce. Why email and name is send to pixel as plain text?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
