### ISSUE TITLE
Facebook Shopping Feed "Processing" for Weeks

### ISSUE THREAD

**Issue by JimboSEO** [facebookincubator/facebook-for-woocommerce#1075]
Please review the plugin and find out why all of us are having such major issues with the shop being processed by Facebook. It has been weeks since I first set up the shopping feed and have not seen any sort of budge or indication that it will be processed properly.

WooCommerce: 3.6.5
WP: 5.2.2
Plugin: 1.9.15
Screenshot: https://www.screencast.com/t/qUnJIul7S8e
Website: https://store.chineseweightlifting.com/
FB page: https://www.facebook.com/chineseweightlifting/
Page URL of screenshot: https://www.facebook.com/pg/chineseweightlifting/shop

Followed all recommended steps, the plugin is at the latest version, connected was disabled, reenabled etc etc etc

**Comment by opanga328** [comment]
@JimboSEO how did you resolve this issue. Please help

**Comment by opanga328** [comment]
I have the same issue for weeks. Ticket # 1060

https://www.facebook.com/dmdfashionCA/
https://www.facebook.com/pg/dmdfashionCA/shop/
https://dmdfashion.ca/shop/

This is really delaying my product launch and advertising.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
