### ISSUE TITLE
Product description syncs to Shop but no pictures

### ISSUE THREAD

**Issue by SharingSolace** [facebookincubator/facebook-for-woocommerce#1076]
I was able to upload a single image as a cover photo for the product but will not sync any pictures from my store. I've resynced products (several times over several weeks), disabled and reinstalled...done everything suggested. Any help would be greatly appreciated!

Store: https://sharingsolace.com/boutique/
FB Shop: https://www.facebook.com/pg/SharingSolaceLLC/shop/
Exact Product with issue: https://www.facebook.com/commerce/products/2081614241949570/

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
