### ISSUE TITLE
Pixel is firing way more event's then really happened  

### ISSUE THREAD

**Issue by doroness** [facebookincubator/facebook-for-woocommerce#1077]
In the last month, we had about 5 sales. Facebook analytics shows about 10 purchases events. The inconsistency is with other events also.
Where could the extra events come from?

Site: https://normanandbella.com/
https://www.facebook.com/NormanandBella/
Woocommerce 3.5.4
Facebook for WooCommerce 1.9.12
WP 5.2.1

![image](https://user-images.githubusercontent.com/53006624/61378804-e7e79300-a8ae-11e9-8ade-63644f5bdf68.png)
![unnamed](https://user-images.githubusercontent.com/53006624/61378805-e7e79300-a8ae-11e9-89e8-34875f2bb7b4.png)

Thanks

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
