### ISSUE TITLE
When I change the color for icon background, no effect takes place

### ISSUE THREAD

**Issue by remymedranda** [facebookincubator/facebook-for-woocommerce#1081]
There is a color option to change the icon color. I've attempted to change that color on multiple sites and have been unable to do so from the plugin setting option that is created for it.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
