### ISSUE TITLE
facebook for woocommerce not syncing

### ISSUE THREAD

**Issue by webteambdc** [facebookincubator/facebook-for-woocommerce#1083]
Hello,

I am facing an issue to sync the products from wordpress woocommerce to facebook.
I was using facebook for woocommerce plugin to do so, but after i clicked the button "Sync Products", it will loading a while, after that just appear the text without loading bar anymore. It seems like the things were not working. After while i go to the facebook catalog and check, it still showing empty, meaning the synchronization failed. 

Please help as i already tried out a lot of solutions but still not able to solve this. Thank you.

![error](https://user-images.githubusercontent.com/48550713/61605061-732da380-ac76-11e9-9e91-2b2acad6de0f.jpg)

#237 
#742 
#769

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
