### ISSUE TITLE
Lead event passed on unvalidated Contact Form 7 submission

### ISSUE THREAD

**Issue by atseira** [facebookincubator/facebook-for-woocommerce#1085]
When user clicks "Submit" button in Contact Form 7, the event `wpcf7submit` will be triggered even when the form is not validated. Then, the Facebook Pixel event `Lead` will be passed even though the form submission is not valid.

I propose to change `wpcf7submit` event listener to `wpcf7mailsent`. Or make the `Lead` tracking optional.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
