### ISSUE TITLE
Instagram show old catalog

### ISSUE THREAD

**Issue by wildatease** [facebookincubator/facebook-for-woocommerce#1086]
Hi, 
I don't know how can i stop showing old catalog on instagram shop. The catalog does not exist anymore (already deleted) but it keeps showing old products on instagram. I need to take them out of there and i have no clue how can i do it.
Can you guys help me please?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
