### ISSUE TITLE
Maxed Out Resources When Force Sync

### ISSUE THREAD

**Issue by creativeapparelstore** [facebookincubator/facebook-for-woocommerce#109]
Facebook for woocommerce: 1.6.4
Woocommerce version: 3.1.2
Products: 100
Type of products: variable products (8 colours per product)
No duplicate SKUs
Customization plugins: Using Printify (not sure if its customisation at all)

When I do a force-resync to sync my products, it seems to max out the resources on my webhost server.

I am using SiteGround on their GroBig account (which is more than enough for WooCommerce) however, whenever I try to run the plugin it maxes out the resources on the server.

It reaches the daily quota of 20000 program and script executions, almost instantly. I had them increase my limit to 70000 and it reached it within an hour. I received a limit and a warning that my account would be cancelled. Is there some type of bug making this happen?

Happy to give you access to my account.

**Comment by mengyingdu** [comment]
Hello,

It's weird since 100 products shouldn't raise that traffic. And we have a lot of users have more than 10k products. If you'd like to share your access, can you send it to ads_extension_woocommerce <ads_extension_woocommerce@fb.com> ? Thanks.

**Comment by mengyingdu** [comment]
Hi,

I think you could just tell us your fb page here.

**Comment by dmitridr** [comment]
Thanks for sharing more details with us, looks like this is a continuation of #98 ?

Can you go into more details about this quota? The plugin makes a heartbeat AJAX call every 5 seconds to make sure there are no products to sync when syncing. If every call is taken against your quota that could be why.

Try changing this value in the plugin via the wordpress plugin editor :
https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/assets/js/facebook-settings.js#L441

It's in milliseconds, so change it from 5000 to 60000? Then there should only be a heartbeat ping every minute. This should hopefully reduce the # of ajax calls, though it will slow down sync.

**Comment by dmitridr** [comment]
Good news. It took a while but we vastly improved the performance of product sync and Force Resync. They are up to 60x faster now. To get the full benefits, reset your configuration via `Reconfigure > Advanced Options > Delete` then set up again. The reason for the speedup : Force Resync uses a feed file to upload products now.

https://github.com/facebookincubator/facebook-for-woocommerce/releases

We've also greatly reduced the # of ajax calls.
