### ISSUE TITLE
FB Retail price set to sale price

### ISSUE THREAD

**Issue by silksow** [facebookincubator/facebook-for-woocommerce#11]
FB sets the retail price to the sale price and does not display as a sale product.

Steps to reproduce:

1. Create and sync variable product
2. Set sale price for variations and update product
3. WooCom displays retail price with line-through style, sale price and sale icon. Facebook displays unstyled sale price only and sets retail price to sale price in catalog

**WooCom product**
![woocom variation](https://user-images.githubusercontent.com/30702576/29007327-66633a24-7ab5-11e7-8b54-46759d102611.JPG)

**WooCom store**
![woocom sale](https://user-images.githubusercontent.com/30702576/29007329-70649694-7ab5-11e7-99be-ad42a8e8665a.JPG)

**Facebook catalog**
![facebook variation price sale price](https://user-images.githubusercontent.com/30702576/29007339-ac8e8b2a-7ab5-11e7-8fb4-015862f498f1.JPG)

**Facebook shop**
![fb shop price](https://user-images.githubusercontent.com/30702576/29007340-b7581472-7ab5-11e7-9221-40222ed47ef9.JPG)

**Comment by mengyingdu** [comment]
We've fixed this issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
