### ISSUE TITLE
No Woo Default : But FB Default is set to scary (expensive) product.

### ISSUE THREAD

**Issue by gchterry** [facebookincubator/facebook-for-woocommerce#110]
I want leave no default UOM on my woocommerce.
Now facebook store auto pick UOM based on alphabet is expensive one, so i don't want scare my Facebook customer.
In this case, I want default UOM in facebook store.

Please check & add on this function^^

![image](https://user-images.githubusercontent.com/31883268/31982977-cd72c934-b98d-11e7-880d-49830c6dbc69.png)

![image](https://user-images.githubusercontent.com/31883268/31982989-e009d39e-b98d-11e7-9791-074055f6df10.png)

PCS is RM298
PACK is RM1999

**Comment by AndreasMe** [comment]
Same problem to me. See #114

**Comment by mengyingdu** [comment]
Hi,

Can you try to set 'default form value' as the one you want with the newest version of plugins?

We support default variation from v 1.6.4. 

Let me know whether it works.

Thanks.

**Comment by dmitridr** [comment]
Hi @gchterry 

There should be a workaround : FB defaults to the last variation in the list as default if no default is set. So if you can make it the last one in the list of variations, it should default to that one on FB. 

In the meantime, we will consider adding some sort of 'FB Default' checkbox on the variants. Or allow for no-default on FB shops. Not sure which would be more ideal here.

**Comment by mengyingdu** [comment]
Hi @gchterry ,

We support default variant from [v1.8.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.3) . If you set the one you prefer to show up as representative as 'default' on Woo product editor, you should get what you want. If this problem still exists, this could be a bug. 

Can you try to upgrade ? After upgrade you do need to click 'update' to sync your default setting. Close this issue for now given the new version has a fix. Feel free to open a new one if you need more help.

Thanks.
