### ISSUE TITLE
Facebook Pixel not getting the store purchase data

### ISSUE THREAD

**Issue by myildir2** [facebookincubator/facebook-for-woocommerce#1104]
My pixel on my woocommerce store is working properly except it does not get any of the purchase data or show it in my AD results. How to fix this? Help please!

**Comment by myildir2** [comment]
https://cadimoda.com/

**Comment by myildir2** [comment]
I also get the "Catalog can not be synced" error!

**Comment by LordGoran** [comment]
I'm seeing the same issue. No sales data, values, or anything.

**Comment by myildir2** [comment]
Will anybody help???

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
