### ISSUE TITLE
Pixel from wrong business/ad account

### ISSUE THREAD

**Issue by andy10676** [facebookincubator/facebook-for-woocommerce#1105]
I had set up a business account when I finished building pages for my site, then I set up all my social including my FB business account. I then went back to my site and started populating with products.  When I came back to my business account my ad accounts were disabled, so I created a new business account and started adding my pages to the new account.  When I went to set up facebook for woocommerce on my site it will give options for what page I want to add...I can select the correct page (I cross checked the ID # on the page itself) BUT when I try to choose the pixel id it only gives me the choice of a pixel that is associated with another page and that pixel is ONLY associated with the OLD business account. 

In simpleist terms I have 2 business accounts.  One is associated with 2 pages (not the page I am trying to connect to), 3 ad accounts (2 disabled and 1 active but not for the page in question), and 5 pixels (1 being the old pixel for the page in question I am trying to replace, another being the only pixel I get as an option to choose from).  The other business account has all the pages I have started (including the one I am trying to connect), 2 ad accounts (one being the one I am trying to set up for this page), and 2 pixels (the pixel I am trying to connect with but DO NOT get as an option)

I fully admit I turned myself around in circles creating business and ad accounts and that I am probably not explaining this issue as best as it can but I can supply any info and screenshots anyone needs to help me with this issue.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
