### ISSUE TITLE
Can't Connect & Sync FB Page & Woocommerce

### ISSUE THREAD

**Issue by gpclarke** [facebookincubator/facebook-for-woocommerce#1106]
I'm still having this problem with one of my FB pages.  The products are active, but the IG Connect Your Instagram Business Profiles connect options on the associated business IG account is shade and I cannot select the "Not Connected" option is not available to select.  The support people only reply after 11pm PT or later...so frustrating to get this setup all week

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
