### ISSUE TITLE
Access token expires & unfamiliar access blocking account

### ISSUE THREAD

**Issue by adriannees** [facebookincubator/facebook-for-woocommerce#1107]
My access token expires frequently and when I attempt to reconnect it alerts me that someone from Clifton NJ is attempting to access my account. When I say yes this was me it tells me that FB has detected suspicious activity on my account, forces me to reset my password and review my activity. 

I can see there are MULTIPLE requests to have this fixed that seem to be getting ignored. At this point the connection is useless to me because I cannot connect my account without it getting flagged.

**Comment by markovanderpuil** [comment]
+1

**Comment by aftianap** [comment]
Hi, I had the same problem, I tried to follow the guide from another forum and it's worked for me!. Let's try to open 
1. Facebook Business Extension on your web page dashboard
2. Klik on n the panel view> Developer > Javascripts console
3. paste this window.facebookAdsToolboxConfig.tokenExpired = 'true'     click enter.
4. Klik "manage setting" and you will see click update toke like the image below:

<img width="948" alt="Screen Shot 2019-08-29 at 11 13 43" src="https://user-images.githubusercontent.com/28257868/63909768-2f387600-ca4e-11e9-83e8-a732ea630d7d.png">

Hope that help! thanks

**Comment by Protohominid** [comment]
+1

**Comment by mkubdev** [comment]
+1

**Comment by jlan155** [comment]
+1

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
