### ISSUE TITLE
Settings access

### ISSUE THREAD

**Issue by hectorpeynado** [facebookincubator/facebook-for-woocommerce#1108]
Hello,

I can't access the plugin settings.

Attached is the error displayed.
![Error](https://user-images.githubusercontent.com/12670829/63850806-3b143180-c995-11e9-9d2f-5e6871b7651f.JPG)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
