### ISSUE TITLE
Your API key is no longer valid. Other page Facebook

### ISSUE THREAD

**Issue by TheShaady** [facebookincubator/facebook-for-woocommerce#1109]
Hello,

I delete my FB account (get banned no reason lol) so my page disapeared. I create a new account and page but got the message : 

Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token".

And when I click setting -> Something went wrong lol

Any ideas how to configure another page (reset API key) ?

Thanks

**Comment by karbaapinfinityhub** [comment]
is there any solution to this? i have the same problem!

**Comment by jeffsandoval014** [comment]
Same here

**Comment by ajahuanex** [comment]
Same problem. 
<img width="1117" alt="Screenshot_2" src="https://user-images.githubusercontent.com/2767765/70961465-dec24400-204f-11ea-8668-3d471d979883.png">

**Comment by jeffsandoval014** [comment]
See my post if you can.
