### ISSUE TITLE
Product description not syncing 

### ISSUE THREAD

**Issue by javismiles** [facebookincubator/facebook-for-woocommerce#111]
Good day,
when  products sync, in the area "Product Details" the name of the product appears, but the full description of the product does not appear. 
In  my Woo I have a long product description with very important explanations that customers  need  to read. This does not appear in the facebook store at all which is a huge problem because then people won't  understand the product. We need the full product descriptions to sync and appear in FB Store please

thank you

**Comment by mengyingdu** [comment]
Hi ,

I just check current we will display product description which has been set in product description. As I understand, you want to show description for each variant, and set it under 'variation' panel. We don't support it on current version but we will add this new feature in later release. 
Thanks.

**Comment by javismiles** [comment]
No problem friends, I have added manually all the descriptions in the facebook tab of the product pages so that should help for now, thank u ;)

**Comment by javismiles** [comment]
But I have a different  issue friends, I set the setting to go to product page, not to cart. I know you told me that you tested on mobile and it works for you, but not for me :)
On desktop it goes to product page, good. But on my android Nexus 5x, i tested again now, and it keeps going to cart, it doesnt go to product page my friends.
Could you please test this again. It only goes to product page on desktop, not on mobile, thank u ;)

**Comment by mengyingdu** [comment]
Hi,

I test that on my iphone -> Facebook App -> enter page shop --> click on one product to checkout.
Can you tell me detailed steps in order to repro your problem?

Thanks.

**Comment by javismiles** [comment]
Good day, so:

- I do exactly what you do but on an Android Nexus 5X instead of an iphone: I delete cache, I go to my store on facebook, open any product, click on button to go to store, and the cart  opens. If you can test it on an android nexus phone and you will see.

- Sync finished incomplete  again friends. 61 of the 80 products in sync, the rest didn't transfer. 

- Another question, my products are in 4  categories, look the same but 4 categories, how can I show to people my 4 categories, women, men, kids and home, without categories people won't understand which garments are women, which men, etc

thank you and have a nice day

**Comment by mengyingdu** [comment]
Hello again, 

We received report that Android shop (including other functionality) is broken now so it currently doesn't work for Android.  

I will update ASAP once it was fixed.

Thanks for your patience.

**Comment by mengyingdu** [comment]
Hello again,

We support that plugin user user variant description in next new release. 
Thanks for your patience. I'm working on your issues and need time to solve it one by one.

Best,

**Comment by javismiles** [comment]
Good day, thank you for the update and I understand, no problem and no rush, with the current status it is enough for it to work quite well, and little by little step by step the issues will be fixed i know, thank you for your support

**Comment by mengyingdu** [comment]
Hi @javismiles 

Some good news to update: our shop team just fixed the shop bug!
To be clear,
if we enter from shop->a variable product group, in the popup window->change variant value, variant description WILL update now. (if you put different description under variation section, 1 to 1 mapping)
