### ISSUE TITLE
FB Pixel not triggering

### ISSUE THREAD

**Issue by moburkhardt** [facebookincubator/facebook-for-woocommerce#1110]
Initially we saw 404 when trying to GET the File "wp-content/cache/busting/facebook-tracking/fbpix-plugin-inferredEvents-2.9.4.js" because the file in the Plugin had a lower case e for Events 🤦🏻‍♂️

Now we fixed the File name but the Pixel is still not triggering:
![Screenshot 2019-09-04 at 10 11 51](https://user-images.githubusercontent.com/169051/64237464-b2e5dd00-cefc-11e9-824a-e79690723061.png)

There was activity on the pixel in today but not since have been investigating the issue.

Plugin Version
Version 1.9.15
WP-Version
Version 5.2.2
WooCommerce
Version 3.6.5

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
