### ISSUE TITLE
Can't add to cart from Instagram in-app browser using Facebook for Woocommerce

### ISSUE THREAD

**Issue by fordmillinery** [facebookincubator/facebook-for-woocommerce#1111]
I haven't been able to add any products to my cart from any page while in the in-app browser in Instagram. Whenever I add to cart, it comes up with a successful "added to cart" message, but then once I go into the cart, the cart is empty. Problem does not happen with any other browser (mobile or desktop)

**Comment by HeatherActon** [comment]
Having the same issue on https://glutenfreebakingacademy.com. No solution yet but will loop back if we find one.

**Comment by Mojowire** [comment]
Having exactly the same issue here - Works everywhere else, but not in the browser in the instagram-app on iOS. @fordmillinery @HeatherActon Which hosting are you using? We are using WP Engine and Flatsome Theme, they shouldn't cache the default Woo-pages like cart and checkout, and I've added text to the cart and checkout-page that show up, so the page itself is not cached.

I did however discover that the shopping basket in the right hand corner, when expanded, you get 2 buttons, one for cart, and one for checkout - but whatever I click I get sent to the cart page - even when clicking the Checkout-button, I checked this by adding the text "cart" to the cart-page and "Checkout" to the Checkout-page, and only the page saying "Cart" shows up - I've even hardcoded in a link to the url/checkout-page in the menu, and clicked that, but it still sends me to the page that says "Cart" on the top - do you experience the same behaviour, ie both buttons pointing to the Cart?

**Comment by HeatherActon** [comment]
I found the issue for us. We are hosted with WP Engine, that by default turns on "redirect bots". Here's there explanation for why - "Essentially, this setting redirects well known crawler user agents (bots) crawling the site to the parent page when they request a page ending in a number or in a query argument." More at https://wpengine.com/support/redirecting-bots-how-this-benefits-you/

When we disabled this setting, all works as intended. I may go back to WPE and ask them to make an exception for just Instagram, so that we can leave Redirect Bots ON, but at this point I'm just happy it works for us. Hopefully it helps you too!

**Comment by Mojowire** [comment]
> 
> 
> I found the issue for us. We are hosted with WP Engine, that by default turns on "redirect bots". Here's there explanation for why - "Essentially, this setting redirects well known crawler user agents (bots) crawling the site to the parent page when they request a page ending in a number or in a query argument." More at https://wpengine.com/support/redirecting-bots-how-this-benefits-you/
> 
> When we disabled this setting, all works as intended. I may go back to WPE and ask them to make an exception for just Instagram, so that we can leave Redirect Bots ON, but at this point I'm just happy it works for us. Hopefully it helps you too!

Hmmm - only problem for us is: This setting is already set to "off" - so it doesn't seem to be the reason for the weird "your cart is empty" behaviour :/ You didn't do anything else at the same time did you? Like disable a plugin or something?

**Comment by HeatherActon** [comment]
Oh bummer... No, we didn't change anything else. We do use custom add to cart URLs but nothing else special happening there. With that, we have redirect to cart turned OFF and Ajax buttons on archives turned ON in Woocommerce-->Settings, Products tab.

At one point, even with the blocked bots, I did have this working when I moved to purely Ajax buttons. I used Enhanced Ajax Add to Cart and replaced our custom add to cart URLs with the shortcode offered by that. But, I undid that after the redirect bots was turned off.

One more thing to check with WP Engine - ensure all the Woo stuff is excluded from cache - it's worth the double-check. It's more than just the cart page itself - it's also anything beyond that along with some cookies, I believe. If this weren't the case, you'd likely have issues in other browsers too, but it's worth a check with them.

Regarding your checkout redirecting to cart, that's an odd one. It sounds like there's a redirect in somewhere - either in WPE interface, .htaccess, or maybe a plugin is doing it. Possibly even the theme if they have a custom cart/checkout area... Or, maybe your checkout page isn't set in WooCommerce->Settings? Hard to say, but not typical. Is that in all browsers or just Insta?

If you'd like to share your site, I'd be happy to take a look and see if I notice anything else. This is tough to troubleshoot...

**Comment by viniciusnz** [comment]
> > I found the issue for us. We are hosted with WP Engine, that by default turns on "redirect bots". Here's there explanation for why - "Essentially, this setting redirects well known crawler user agents (bots) crawling the site to the parent page when they request a page ending in a number or in a query argument." More at https://wpengine.com/support/redirecting-bots-how-this-benefits-you/
> > When we disabled this setting, all works as intended. I may go back to WPE and ask them to make an exception for just Instagram, so that we can leave Redirect Bots ON, but at this point I'm just happy it works for us. Hopefully it helps you too!
> 
> Hmmm - only problem for us is: This setting is already set to "off" - so it doesn't seem to be the reason for the weird "your cart is empty" behaviour :/ You didn't do anything else at the same time did you? Like disable a plugin or something?

Same problem here, setting is already off and still with the same issue...

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
