### ISSUE TITLE
Issue with Pixel

### ISSUE THREAD

**Issue by carcarefreaks** [facebookincubator/facebook-for-woocommerce#1113]
Hi,
I have been in contact with facebook support, but since the error seems to be in your plugin they have redirected me to you.

![69592729_509946956239149_765746364834381824_n](https://user-images.githubusercontent.com/33432065/64450174-d6b64800-d0e1-11e9-9d4a-e6fc3716f705.jpg)

My pixel is reporting items as product group.

Here is what facebook support said:
You will need to change ‘content_type’ => ‘product_group’ to ‘content_type’ => ‘product’

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
