### ISSUE TITLE
Private/Unpublished drafts showing up on Facebook

### ISSUE THREAD

**Issue by tamarw** [facebookincubator/facebook-for-woocommerce#1114]
Noticed this issue was fixed (in #228) but I'm experiencing it on 1.9.15. The only solution I think I can find is to delete everything that's a draft, and I really really do not want to do that. Help?

**Comment by tamarw** [comment]
This is a major issue, so I really hope someone is here who can help with this.

**Comment by tamarw** [comment]
Ummm, is anyone still supporting this plugin or am I in the wrong place???

**Comment by robertstaddon** [comment]
@tamarw, I am having the exact same issue! This plugin is syncing "Draft" and "Private" products and making them publicly viewable on Facebook.

**Comment by tamarw** [comment]
Unfortunately no one seems to be working on this issue at all, and I
haven't figured out a way around this yet.

**Comment by gpclarke** [comment]
I don't seem to see anyone from FB responding within here.  WooCommerce support responded to my support request with: 
"hanks for contacting WooCommerce.com support.

We have a really great relationship with Facebook, and, as part of that, they’ve developed the extension you are using themselves. They’re also supporting the extension, providing help with getting it up and working the best way possible on your store.

You can get help with Facebook by using their support page on GitHub"

**Comment by tamarw** [comment]
Guys, doesn't seem that Facebook is invested in fixing this, so I found a workaround. Make sure all products are both in DRAFT mode and also PRIVATE. That should do the trick.

It shouldn't be necessary to do both, but it seems as if it is. If anyone happens to see this and wants to confirm my issue solves it for them, I'd be much appreciative.

**Comment by Appsman20** [comment]
Setting visibility as hidden works fine.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
