### ISSUE TITLE
Major syncing issues between WC and FB/IG

### ISSUE THREAD

**Issue by delariva805** [facebookincubator/facebook-for-woocommerce#1115]
Good morning! I have a Printful shop through WooCommerce and have it connected to both my FB and Instagram pages, but am having major syncing issues with no consistency as to what's syncing or how it's displaying.

From within my Business Manager, only 9 Printful-created products are showing as synced to my FB/IG store, but every size and color variant of those 9 are listed, so FB Business Manager is saying that I have 255 products. These same 9 are showing as synced in the 'Products' area of my WP admin; all others are showing as 'Not Synced'.

On the 'Shop' section of the front-end of my FB page, however, only 4 products are showing in the catalog, and when you click on one you access variants for that product.

Then over on 'Shop' section of my Instagram page, only 4 products are showing—and 3 of those are different from the ones that are showing on my FB page. (Like the FB page, however, clicking on one product can access all variants for that product.)

From within the WooCommerce dashboard, if I go to WC > Settings > Integration > FB and click 'Manage Settings', and click on 'Your Products' in the dialogue, it says I have 52 products synced, which would be all the products in my Printful (not counting all variants, of course).

I have everything set up properly; business page, users, everything's connected, have hit 'sync products' multiple times, have re-activated my token, etc. I've contacted Printful and they're saying the issue is on FB's end, so I'm reaching out to you guys here. Let me know what you need from me so we can get this resolved.

Thanks in advance!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
