### ISSUE TITLE
API Token Bug After Facebook Pages Were Merged

### ISSUE THREAD

**Issue by FlatRateContent** [facebookincubator/facebook-for-woocommerce#1116]
Hey there, I set up the Facebook shop for a client who had two Facebook pages for the same location.

The facebook pages got merged, and the API key for the facebook plugin is lost with the page that got merged. 

When I go to the  Plugin Settings it doesn't give me the option to manage the settings: 
https://cl.ly/4a9dbbf9c488

When I click the button to follow the instructions for a new API, it leads me to this page:
https://cl.ly/178b50b504bb

I've tried deleting and re-installing the plugin. I've tried completely erasing the plugin from the backend and the problem persists. 

At this point I'm not sure what to do. I don't want to rebuild the shop but I've debated completely starting from scratch. Is there anyway to override this?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
