### ISSUE TITLE
Unauthorised Access 

### ISSUE THREAD

**Issue by DJSavill** [facebookincubator/facebook-for-woocommerce#1117]
Hello,

Whenever I sign in with the Facebook WooCommerce Plugin, Facebook keeps blocking my account telling me I'm having unauthorised login from (Maidenhead?) somewhere in the UK and asking if it's me.

When I click yes, because it is me, Facebook still makes me change my password every time, even though I just click yes, because it's me! - Why am I changing my password to protect me from myself?!

This keeps happening over and over until (something happens, some kind of corruption I assume) the plugin simply stops listing my Facebook page as a page that can be linked to. No matter how many times I uninstall the plugin, clear anything in the database, or whatever, the page doesn't come back in the list to select.

I need my products to sync with Facebook. All I could do, because nobody in Facebook would come back to me and Forums are saying people have been having this issue since April at least, I've had to create a whole new name and branding and roll with a different identity and new Facebook page.

Now, it's also beginning to do it with the new brand!

I think there is a huge issue with the plugin, which needs to be fixed. Whats the point in me having a Facebook page if I cant sync my products with the Facebook shop. It's September, I need AD campaigns ready for the Christmas run up.

With such an important plugin, as so many people use WooCommerce, which syncs businesses products with Facebook pages, I just don't understand why Facebook aren't hot at keeping it perfect.

Please help.

<img width="1880" alt="Screenshot 2019-09-12 at 20 12 26" src="https://user-images.githubusercontent.com/54852121/64813728-efb77100-d599-11e9-88ea-810f2e47aeb8.png">

**Comment by DJSavill** [comment]
No answer? No Comment? No Nothing?!

How is anyone who is relying on this plugin supposed to utilise it for business on Facebook if it isn't working properly?!

Are we to assume Facebook's silence is that they're re-building the plugin from the ground up, and are going to surprise us with a new plugin that works? 

Or, is Facebook just so sure of themselves that they feel they don't need business from WooCommerce users?

Either way, an answer would be nice.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
