### ISSUE TITLE
Retargeting Specific Variants of a Product

### ISSUE THREAD

**Issue by willi409** [facebookincubator/facebook-for-woocommerce#1118]
Hello,

We have a client that has one product, with the option to select 5 different variants of the product:

![STAMINAPRO   Buy – STAMINAPRO](https://user-images.githubusercontent.com/55258871/64820118-9bde6500-d564-11e9-963c-db7cbba7738a.png)

At the moment, the Facebook "View Content" event is only passing "content_type: product_group" and the product_group ID, no ID's that are specific to the variant selected.

Unfortunately the product_group ID is the same for all 5 variants, so there is not information being fed to the Facebook pixel regarding which specific variant the user viewed.

Is there a way for us to pass in the specific variant ID (content ID) to the retargeting pixel for the variant that is currently selected, rather than the whole group ID? I realize that the pixel would need to fire with each variant selection, is there a way to accomplish this as well?

Any input would be greatly appreciated.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
