### ISSUE TITLE
Facebook for Woocommerce plugin error 

### ISSUE THREAD

**Issue by wordpressuser5** [facebookincubator/facebook-for-woocommerce#1119]
Hello, I'm having issues updating the plug-in for FB for WC - please see attached screenshots. Can anyone assist? Thanks! 
[Facebook for Woocommerce plug-in issue.docx](https://github.com/facebookincubator/facebook-for-woocommerce/files/3608276/Facebook.for.Woocommerce.plug-in.issue.docx)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
