### ISSUE TITLE
implement prepare_product filter

### ISSUE THREAD

**Issue by cyptus** [facebookincubator/facebook-for-woocommerce#112]
please implement a filter before the return in the WC_Facebookcommerce_Integration->prepare_product method.
some product details need manual improvments, for example the product image is not always the best image for the facebook shop page (requires square images for better view).
The filter should pass product id and the generated product_data:

Example:
`return apply_filters('facebook_woocommerce_productdata', $id, $product_data);`

**Comment by dmitridr** [comment]
@cyptus 
Great idea. Would you be willing to send us a pull request so we can give you credit for it? As you said it's only one line, we can review and test it.

**Comment by cyptus** [comment]
@mengyingdu thank you - but there is no option for setting different images for the product on the website and the facebook image. The filter will give us this and many more opportunities.

@dmitridr do you have naming convensions for filter names or is "facebook_woocommerce_productdata" just fine?

**Comment by Mapteg34** [comment]
@cyptus, thank, but we need this func too.
we have problem with uploaded images (it must be 600x600px), we add_image_size, add custom crop script, but nothing mechanism in this plugin to set our new image instead of defaut.
This filter resolve our problem, and lot of another.

**Comment by dmitridr** [comment]
Thanks @cyptus and @Mapteg34 for the pull request! This change is live in [v1.6.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases). WooCommerce should have the version on their site in around a week's time.
