### ISSUE TITLE
Products not showing on Facebook Store

### ISSUE THREAD

**Issue by RRS-Development** [facebookincubator/facebook-for-woocommerce#1120]
Had tons of problems with this and by the sounds of things I'm not alone. I followed many tutorials to the T and this still does not work. I now have tons of pixels dotted around, some on my personal account because it keeps defaulting to that, some on the page etc and everything is going back to creating ads. I do not want to create ads, I do not care for creating ads. All I am trying to do is take all the products I have on my Woocommerce Store website www.capturingthemoment.co.uk and get them to come across onto my Facebook store sow hen somebody clicks on a product to buy it takes them to my website.

Can somebody help? 

I go to my website and it's saying I have got a pixel there, it has a number 2 in the green box but on the facebook page it says there is no pixel. Looking in the event data sources there are 2 pixels in there, one says "all good" but the one that I believe it is using saying 100% of views can't be retargeted but doesn't any any help what that means or how to change it....

**Comment by LeopoldKing** [comment]
Hi RRS,

did you try to remover your store and to remove all synced products from Facebook? It happened to me that I could add products to the right catalogue... 

Cheers

**Comment by RRS-Development** [comment]
Hi there,

Apologies for not posting a reply, I had posted in so many places looking for a solution I forgot where I'd posted. I found the issue and the issue for me was with the Woocommerce to facebook Plugin itself. I ended up using a plugin called Feed Manager and it all worked 100% first time. Not 100% sure what the original problem was but after about 2-3 months of trying to get it to work I was happy to change plugins.

Thanks

**Comment by gpclarke** [comment]
I'm going to try the Feed Manager option, as I'm so frustrated with FB Support and getting NO responses on here.
Here's the product for others: https://rextheme.com/best-woocommerce-product-feed

**Comment by RRS-Development** [comment]
> 
> 
> I'm going to try the Feed Manager option, as I'm so frustrated with FB Support and getting NO responses on here.
> Here's the product for others: https://rextheme.com/best-woocommerce-product-feed

I would highly reccomend using the Feed Manager. I was also extremely frustrated at the lack of support for the plugin and when I found the Feed Manager, I did have to do a bit of Googleing to making sure I was setting it up right but it seemed a lot easier than the other plugin to the point where I thought I'd set it up wrong. It searches through all your products for any settings errors within the products and simply tells you wha tyour current setting is when you're trying to post to Facebook and tells you what it needs to be, otherwise you can just skip changing the settings, it's very straight forward to use.
