### ISSUE TITLE
Your API key is no longer valid.

### ISSUE THREAD

**Issue by jeffsandoval014** [facebookincubator/facebook-for-woocommerce#1122]
Kinda same with other issues:

Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token".

But when I click settings:

Sorry, something went wrong.
We're working on getting this fixed as soon as we can.

Go Back

This happened because I deleted the page that was linked before. I created a new one and I can't use the plugin anymore.

**Comment by jeffsandoval014** [comment]
Fixed https://github.com/facebookincubator/facebook-for-woocommerce/issues/708#issuecomment-429088516

**Comment by ALi12301** [comment]
I've read through all the other issues, but none of the proposed solutions helped. I've installed the plugin and gone through the setup after which none of my products get synced with the facebook shop.

 I've looked at the settings and see the following message at the settings page: "Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token"."

 I've tried updating the token, however it does not help and the same message reimains to be there. I've also tried deleting the settings in the Advanced Settings page of the plugin and repeating the set up, however it also did not help.
Plizz tell me how to possible setting ?
