### ISSUE TITLE
Duplicated Products on Facebook Shop

### ISSUE THREAD

**Issue by kaylapham** [facebookincubator/facebook-for-woocommerce#1124]
Hi Support Team,

I've got 7 duplicated products on my Facebook Shop. Could you please advise how can I remove these 7 duplicates? 

Here is the information:
Facebook for WooCommerce: 1.9.15
Woocommerce plugin: 3.7.0
Wordpress: 5.2.3
My Fb shop: https://www.facebook.com/pg/LUKirigamiCards/shop/

I look forward to your response soon.

Thanks,
Kay

**Comment by kaylapham** [comment]
Hi Support Team,

I just updated our Fb shop. Please see it here: https://www.facebook.com/pg/LovedUpCards/shop/

I'm looking forward to your response.

Thanks,
Kay

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
