### ISSUE TITLE
Facebook Pixels Issue

### ISSUE THREAD

**Issue by UnicornATA** [facebookincubator/facebook-for-woocommerce#1125]
I have to online stores: pbsboutique.com and starsandstripesdesign.com. I also have to Facebook pages: https://business.facebook.com/starsandstripesdesign/ and https://business.facebook.com/PBS-Boutique-108370463868391/.
On PBS the pixel is working now, but on the Stars and Stripes. I see the notice: "The pixel installed on this WooCommerce site belongs to another ad account. Contact the person with admin privileges for the currently installed pixel to change it." How is it possible? What can I do? 
And one more question, how can I remove the numbers in the address: https://business.facebook.com/PBS-Boutique-108370463868391/.
Thank you for your help in advance :)

**Comment by Helen-Creative** [comment]
I have the same issue with my FB pixel, but I can help you solve the numbers issue.  Go to the PBS Boutique Page in Facebook (not in business manager) and if you have more than 25 page likes you can change the page name in the page settings. 0

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by Helen-Creative** [comment]
Thanks for getting in touch. At this stage we have gone with an alternative plug in so I won’t be updating this one.

Cheers!


Helen Sampson
The Creative Femme
www.jaggedcrowcreative.com.au
websites | blogging | email marketing| social media strategies
p: 0407 807 187
