### ISSUE TITLE
Please Help! Facebook extension error: Facebook for WooCommerce

### ISSUE THREAD

**Issue by atlasdigitalagency** [facebookincubator/facebook-for-woocommerce#1126]
Facebook extension error: Facebook for WooCommerce
Unsupported post request. Object with ID '3077512242273883' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

My catalog stopped syncing with facebook automatically. Please I really appreciate your help. Thank you!

Facebook for WooCommerce Version 1.9.15
WordPress.Version 5.2.3

I tried removing the plugin and disconnecting the account. Reinstall. Clear cache And nothing worked. :(

**Comment by fury3d** [comment]
Same issue here.. I dont know what do. I have deleted my product catalog of facebook, but it didn resync anything.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
