### ISSUE TITLE
Failing to fetch products to my facebook page from the website

### ISSUE THREAD

**Issue by refataitta** [facebookincubator/facebook-for-woocommerce#1129]
I can't synch products from my website to the page, this was done successfully in the past but I changed the page and I also switched the facebook pixel from one account to another and then switched back again, and now I can't fetch the products on the page.

I am using facebook for woocommerce Version 1.9.15
woocommerce version 3.6.5
wordpress version 5.2.0 (although need to make sure)
website url   aiething.co.uk
facebook page url   https://www.facebook.com/aiethinguk/?modal=admin_todo_tour

The latest steps that I made:
I cleared the plugin and then deactivated and deleted it
I then redowloaded and installed the plugin
Now I get the following error: 
![synch](https://user-images.githubusercontent.com/55796102/65609648-6a2bbc00-dfb0-11e9-8ab8-39846172e3b9.png)
![synch](https://user-images.githubusercontent.com/55796102/65609678-7879d800-dfb0-11e9-9656-37c3b9b6dcd9.png)

So how can I fetch the products to my page?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
