### ISSUE TITLE
Product variation with no default value selected

### ISSUE THREAD

**Issue by dommolo** [facebookincubator/facebook-for-woocommerce#1131]
When I set "Any" in Default Form Value under product variation on wordpress, it doesn't reflect on the related facebook product page, selecting by default one of the values.

WordPress settings (no default value selected):
![Screenshot 2019-09-26 17 37 55](https://user-images.githubusercontent.com/5628139/65703387-f7d8db80-e084-11e9-8ec4-a1ef8e648e66.png)

How it actually appears on facebook (some values automatically selected):
![Screenshot 2019-09-26 17 38 42](https://user-images.githubusercontent.com/5628139/65703476-1f2fa880-e085-11e9-985a-88c8fef5d708.png)

How it should appear (no value selected by default):
![Screenshot 2019-09-26 17 38 50](https://user-images.githubusercontent.com/5628139/65703497-2656b680-e085-11e9-8749-8dce368695fc.png)

Is there a way to get that?

Thanks for help!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
