### ISSUE TITLE
Wrong syncing

### ISSUE THREAD

**Issue by cristhiansrisso** [facebookincubator/facebook-for-woocommerce#1132]
By synchronizing my store on Facebook, retrieve items that no longer exist in woocommerce.
How can I avoid that problem?
Also take some wrong photos or prices. Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
