### ISSUE TITLE
Add to Cart not firing pixel

### ISSUE THREAD

**Issue by luxurybusiness** [facebookincubator/facebook-for-woocommerce#1133]
Add to cart pixel is not firing i install a plugin called Direct to checkout now its not reading the Add to Cart button, when i stop the plugin it works but i want to sent the clients direct to checkout page not in cart page when they will press the button Purchase(Add to cart).
![download](https://user-images.githubusercontent.com/56026848/65957070-3804d900-e44c-11e9-87de-e02877662264.png)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
