### ISSUE TITLE
Wrong syncing, few issues

### ISSUE THREAD

**Issue by dubhumans** [facebookincubator/facebook-for-woocommerce#1134]
Hello, I have few issues and haven't any idea how to fix it, check below please.
If needed I can do access to WP admin & FB accout.
Here is page on FB https://www.facebook.com/pg/DubhumansUA/shop/
Website https://dubhumans.com

1. Wrong Description
[https://www.dropbox.com/s/a7e3kzxxr7z6cdh/1_wrong_description.png?dl=0](url)

2. Weird Attribute
[https://www.dropbox.com/s/75ee64dabh3av6x/2_weird_attribute.png?dl=0](url)

3. Wrong default variation
https://www.dropbox.com/s/yb6rg66rt06euni/1_wrong_def_var.png?dl=0

4. Missed: Age group, Gender, Material. How I can add that?
I already have it in attributes, or I should use some another solution?
[https://www.dropbox.com/s/rjusnj0b61knogs/4_missed_gender.png?dl=0](url)

5. When I clicking on button “Checkput on website” it’s opening “Cart” on website.
How to do Product Page instead cart?
[https://www.dropbox.com/s/q6msl23fvh5cpid/5_Button_checout.png?dl=0](url)

6. How to add extra images to gallery? For example, for FB I want to show Grid of sizes, so it could be like extra image or perhaps I can do it like table in description?

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
