### ISSUE TITLE
Facebook product link not working on home page

### ISSUE THREAD

**Issue by t21store** [facebookincubator/facebook-for-woocommerce#1136]
Hi there,

I connected my woo commerce site to my facebook shop and have encounted the following problem. If i click on a product from the home page it comes up as "this listing no longer exists"
But if i click on the same product in the shop link it comes up fine? 
![IMG_3985](https://user-images.githubusercontent.com/56178690/66249998-90efac80-e77f-11e9-9a31-9a86fcec3123.JPG)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by KMH2017** [comment]
Hello I am having this same issue, and I have already tried updating to the latest version of Woocommerce for Facebook. Was there a fix for this?
