### ISSUE TITLE
Polylang issue: translation overwrites the default language product

### ISSUE THREAD

**Issue by mMoovs** [facebookincubator/facebook-for-woocommerce#1137]
WooCommerce version: 3.4.7
WordPress version: 4.9.8.
Plugin version: 1.9.5

Our shop had first only one language and everything was working. Now we added a second and when the translated product is synced from Woocommerce to Facebook it overwrites the default language information. 

Is this pluging Polylang compatible at all? I noticed you had fixed almost similar issue with WPML but this doesn't seem to fix the problem with Polylang.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
