### ISSUE TITLE
Fatal error on Products Listing page

### ISSUE THREAD

**Issue by codegeek1001** [facebookincubator/facebook-for-woocommerce#1138]
I am getting this fatal error below when I try to see products page in admin dashboard or try to save a product. Seems like it cannot find the is_wc_booking_product() function anywhere. I updated the version to latest 1.9.15. Current woocommerce version is 3.7.0

Fatal error: Uncaught Error: Call to undefined function is_wc_booking_product() in /wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php:143 Stack trace: #0 /wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php(359): WC_Facebook_Product->get_fb_price() #1 /wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(2427): WC_Facebook_Product->is_hidden() #2 /wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(586): WC_Facebookcommerce_Integration->get_product_fbid('fb_product_grou...', 9555, Object(WC_Facebook_Product)) #3 /wp-admin/includes/template.php(1306): WC_Facebookcommerce_Integration->fb_product_meta_box_html(Object(WP_Post), Array) #4 /wp-admin/edit-form-advanced.php(631 in /wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php on line 143

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
