### ISSUE TITLE
Facebook Page not Syncing With Site & Catalog

### ISSUE THREAD

**Issue by theadteam** [facebookincubator/facebook-for-woocommerce#1139]
Hello there, I hope that you are well. We have a wordpress/woocommerce site that has been working great with Facebook page for a long time until a few weeks when the products stopped syncing.

We tried everything from deleting/reinstalling the plugin, removing and relinking, etc, however, nothing seems to be working. Products are showing in the business catalog for the page but are not syncing into the facebook shop section at all.

Wordpress: 5.2.4
Woocommerce: 3.7.1
Facebook for Woocommerce plugin: 1.9.15

Please, could you assist with this asap as it is affecting our business quite a bit.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
