### ISSUE TITLE
FB Product sync fails

### ISSUE THREAD

**Issue by Aitzipez** [facebookincubator/facebook-for-woocommerce#1140]
Hi,
my FB product catalogue sync via FB for Woocommerce is not working. It only works if you do it manually from the admin site. Does anyone have any idea of how to solve this?
Attached the screenshot. It says that HTML format isn't supported but the sync comes directly from the plugin, I wonder where does this HTML format come from if the communication between the platform and Facebook is direct.

![image](https://user-images.githubusercontent.com/56652093/66948817-42a59d80-f00a-11e9-871f-7d4ed78b534b.png)

Some of my products are also rejected for dynamic ads and I was wondering if these two issues could be related.
![image](https://user-images.githubusercontent.com/56652093/66948780-302b6400-f00a-11e9-83b6-5f60c19cf8c4.png)

#237 #969 #advertiser  #goodfirstissue

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
