### ISSUE TITLE
Connection failed. Check that you're logged into your store

### ISSUE THREAD

**Issue by STRONG-Web** [facebookincubator/facebook-for-woocommerce#1141]
Hello.
I have read all other posts however none of the resolutions are working. I have uninstalled, reinstalled, checked CPanel - My PHPAdmin, checked file manager. 
I am an Admin of the FB page and website.
<img width="1149" alt="Screen Shot 2019-10-19 at 3 09 50 pm" src="https://user-images.githubusercontent.com/56749522/67137581-88b96600-f283-11e9-8291-23a25eb69d84.png">

WordPress 5.2.4 running Newspaper theme.
Latest facebook for woocommerce 1.9.15

**Comment by avikatzav** [comment]
Hey
Did you solve it? 
Because I have the same problem...
I Need some help with that...
