### ISSUE TITLE
Facebook - Woocommerce connection catalog

### ISSUE THREAD

**Issue by hegeca** [facebookincubator/facebook-for-woocommerce#1142]
I am using "Official Facebook Piksels" and "Facebook for Woocommerce (by Facebook).

The issue I am having is that the products wont sync from woo to FB. It says that I should not have to make any changes in woo when I am using this plugin. When I try to update it just show the number of products that I have but no transfer link.

Thanks,
Hege

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
