### ISSUE TITLE
Sync doesn't work anymore

### ISSUE THREAD

**Issue by geranoir** [facebookincubator/facebook-for-woocommerce#1143]
Hello!
The plugin was working great! But since 6 days it doesn't sync anymore?
I haven't change anything! All settings are "green"....

It only says "Wird hochgeladen..." --> "Uploading" since the 15th...

Even if I press the "Sync Products" Button - the "loader" is spinning vor 10 min. - but nothing happends?
Can you please help!"

WooCommerce version: 3.7.1
WordPress version: 5.2.4
Plugin version: 1.9.15
The URL of your website: https://www.wonderland13-store.de/
The URL of your Facebook Page: https://www.facebook.com/official.wonderland13/

Thanks,
Gerald

![fb-1](https://user-images.githubusercontent.com/56820802/67202301-951afb80-f408-11e9-9915-a43237fb0c60.jpg)
![fb-2](https://user-images.githubusercontent.com/56820802/67202302-951afb80-f408-11e9-90e2-9b9aa1506615.jpg)
![fb-3](https://user-images.githubusercontent.com/56820802/67202303-951afb80-f408-11e9-8904-9fc5496ef655.jpg)
![fb-4](https://user-images.githubusercontent.com/56820802/67202304-95b39200-f408-11e9-9d8c-d7d44786624d.jpg)

**Comment by giuliapellegrini** [comment]
Yeah, same problem here for a couple of months.
Please anybody answer, our clients are driving crazy

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
