### ISSUE TITLE
Facebook account has been disabled! Please help ASAP!

### ISSUE THREAD

**Issue by kristofffff** [facebookincubator/facebook-for-woocommerce#1144]
- I have no problem using facebook until I used facebook for woocommerce, I have 2 pages on my account each have dedicated wordpress site. I tried syncing my products on my facebook pages and it wen't well the first time, Then yesterday, I tried turning on the "Automatically Force Resync of Products At" setting feature, so that my website's new products can be seen and sync on my facebook shop on the given time I set. Earlier today I receive notification on my facebook account telling me that it detects unusual activities. I'm the only one using my facebook account, So I just go on with my usual actives until this afternoon facebook locks me out of my account saying "You Can't Use Facebook Right Now". I have no problem using facebook for how many years now, until I tick that "automatic force resync" on setting  menu. I suspected that it might be the facebook woocommerce that caused this as it is the only one that have automatic activities that feeds products to my facebook pages. Please help me reach out on facebook to have my facebook account reviewed as soon as possible.

![bug](https://user-images.githubusercontent.com/56828633/67204651-949e5700-f440-11e9-9cf9-db215ae38a96.png)
![bug2png](https://user-images.githubusercontent.com/56828633/67204662-98ca7480-f440-11e9-8b3b-914e39efcb80.png)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by carolina744** [comment]
To regain access to your account, i wll suggest you contact Alexander_mitnick1 on Instagram make sure you follow instructions provided by him. Fill in any required information, such as your email address,full name, and ID. I reached out to him today and i followed every steps and i got my business page back.
