### ISSUE TITLE
Facebook shop has inventory but no products 

### ISSUE THREAD

**Issue by zoaymalaysia** [facebookincubator/facebook-for-woocommerce#1145]
I have tried to sync my products.  It kept syncing but no progress.  On the other hand, under "Your Products", it states that there are products in my inventory but none of them are shown.  Is there way to sync my products onto Facebook still?  Thanks.

**Comment by aluxh** [comment]
I'm facing the same issues. But, what I did beforehand was deleting the data source in Facebook Manager. Then, I wanted to resync after creating a new catalog, it says not ready.

![image](https://user-images.githubusercontent.com/1736667/67615859-ed387000-f803-11e9-9dc9-26f105742ce8.png)

Then, when I went to my woocommerce site, I see what @zoaymalaysia has described, there are products in my inventory, but can't be found in woocommerce site. And when I try to sync, it never completes..

![image](https://user-images.githubusercontent.com/1736667/67615869-07724e00-f804-11e9-9c05-f4edb73fba30.png)

![image](https://user-images.githubusercontent.com/1736667/67615876-1a851e00-f804-11e9-892d-0e2adede6389.png)

**Comment by zoaymalaysia** [comment]
We are facing exactly the same issue

**Comment by alibasheer** [comment]
We are facing same issue. 

It is working for some of the shops I did where they are using personal ad account for the pixel. However it is not working when creating the pixel with Facebook Business Manager due to the pixel 'not ready' issue.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
