### ISSUE TITLE
WooCommerce Products says not published on Facebook Shop

### ISSUE THREAD

**Issue by SOOS-OIO** [facebookincubator/facebook-for-woocommerce#1146]
Hi, the sync of the products are ok and the status for the products are set as visible. Yet it shows as "Not Published" and not visible to visitors. How to publish the products on Facebook page? 

Facebook Shop: https://www.facebook.com/comeback.world/
WooCommerce Shop: https://comeback.world/shop/

Thank you!

**Comment by yukinoba** [comment]
Do you have a 'virtual' product? Currently products with 'virtual' property can not be sold on facebook after synced.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
