### ISSUE TITLE
Woocommerce products not appearing in shop although synced

### ISSUE THREAD

**Issue by AnneOrch** [facebookincubator/facebook-for-woocommerce#1147]
Hi,

I have got the facebook for woocommerce plugin active on this site: https://www.livingstonetextiles.com. it has been set up and products have been synced. However, the products are not pulling through to the facebook shop.
Please can you advise what the issue may be.

Many thanks,
Anne

Facebook Page URL : https://www.facebook.com/livingstonetextiles.com/
WordPress and WooCommerce version number: WP 5.2.4 Woo 3.7.1
Facebook Plugin version number: Version 1.9.15
How many products you have 196
Types of products (i.e. anything besides simple/variable products won’t work): Simple & Variable products only
Do you have Duplicate SKUs in your system? No
What kind of customization plugins you're using (if any)? Plugin list below
Akismet Anti-Spam |   | by Automattic – 4.1.2
All In One SEO Pack Pro |   | by Michael Torbert  – 2.13.1
Block Bad Queries (BBQ) |   | by Jeff Starr  – 20190902
Broken Link Checker |   | by ManageWP – 1.11.8
Contact Form 7 |   | by Takayuki Miyoshi – 5.1.4
Facebook for WooCommerce |   | by Facebook – 1.9.15
Google Analytics for WordPress by MonsterInsights |   | by MonsterInsights – 7.9.0
Google XML Sitemaps |   | by Arne Brachhold – 4.1.0
Image Rotation Fixer |   | by Mert Yazicioglu – 1.0
jQuery Pin It Button for Images |   | by Marcin Skrzypiec – 3.0.5
Limit Login Attempts |   | by Johan Eenfeldt  – 1.7.1
Mailchimp for WooCommerce|   | by Mailchimp  – 2.2.4
Maintenance Mode |   | by Michael Wöhrer – 5.4
MotoPress Slider Lite |   | by MotoPress – 2.1.0
Pinterest Site Verification plugin using Meta Tag |   | by Himanshu Parashar  – 1.2
Print, PDF & Email by PrintFriendly |   | by Print, PDF, & Email by PrintFriendly – 3.14.7
Really Simple SSL |   | by Rogier Lankhorst, Mark Wolters | – 3.2.6
Social Sharing Toolkit |   | by linksalpha – 2.6
UpdraftPlus - Backup/Restore |   | by UpdraftPlus.Com, DavidAnderson – 1.16.17
WooCommerce Admin |   | by WooCommerce  – 0.20.1
WooCommerce PayPal Checkout Gateway |   | by WooCommerce  – 1.16.17
WooCommerce PDF Invoices & Packing Slips |   | by Ewout Fernhout   – 2.3.5
WooCommerce Services |   | by Automattic   – 1.21.1
Wordfence Security |   | by Wordfence   – 7.4.0
WP Missed Schedule |   | by sLaNGjI's Team   – 2014.1231.2016.0
WP-Optimize - Clean, Compress, Cache |   | by David Anderson, Ruhani Rabin, Team Updraft   – 3.0.13

I have tried using the Remove option and setting up again but the result is the same

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
