### ISSUE TITLE
Inventory showing 0 in Facebook

### ISSUE THREAD

**Issue by hypesites** [facebookincubator/facebook-for-woocommerce#1148]
https://www.facebook.com/pg/lifestylesgiftware/shop/?ref=page_internal

Items originally were setup without inventory management and in stock in woocommerce. After they showed issues after synching - Inventory level of 0 - I went back and changed all inventory in woocommerce to be managed at the product level and to have an inventory of 1000.

I tried resynching and fetching but inventory levels don't change in facebook.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
