### ISSUE TITLE
Reset the plugin

### ISSUE THREAD

**Issue by jmassaro87** [facebookincubator/facebook-for-woocommerce#1149]
I am trying to get the "Get Started" button back. We created a new page through the plugin, then realized that we had the wrong facebook account logged in and deleted the page to start over. Now, i have the API key error, and when i click on settings, it give me an error screen. "Sorry something went wrong". I need to reset the plugin to allow my to reset it up. I have tried deleting the plugin and reinstalling but that didn't work.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
