### ISSUE TITLE
Is there possible to make product description (main product information text) include line-breaking after sync?

### ISSUE THREAD

**Issue by zeals75** [facebookincubator/facebook-for-woocommerce#115]
Hi, here's my WooCommerce's product main information (not short description):

> Feature A : XXXXX
> Feature B : XXXXX
> Feature C : XXXXX

After sync, the product information on the Facebook shop become:

> Feature A : XXXXX Feature B : XXXXX Feature C : XXXXX

I'm wondering is there possible to make it include line-breaking (like <br> tag) after sync?

Much appreciated!

**Comment by mengyingdu** [comment]
We will keep line break as you type in description in new release. Thanks.

**Comment by zeals75** [comment]
Many thanks!

**Comment by mengyingdu** [comment]
[v1.6.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.6) is out and supports line breaks. Can you upgrade?

**Comment by zeals75** [comment]
v1.6.6 works fine! Many thanks :)
