### ISSUE TITLE
facebook-for-woocommerce Sale price problem

### ISSUE THREAD

**Issue by gudge25** [facebookincubator/facebook-for-woocommerce#1150]
There is a problem with  facebook-for-woocommerce
addon.
 If i use special price  (right corner on the picture)
on the picture add-on still  listing a product with  a  regular  prise (left corner on the picture) 
![image](https://user-images.githubusercontent.com/2346208/67566272-0b34a080-f730-11e9-8f1d-077d8f8867f9.png)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
