### ISSUE TITLE
Add to Cart firing twice

### ISSUE THREAD

**Issue by na-v** [facebookincubator/facebook-for-woocommerce#1152]
My client has e-commerce store (aida-style.com) and uses Facebook for WooCommerce to send pixel events to FB. I've noticed an issue with Facebook for WooCommerce - it seems that it fires Add to Cart event twice each time a product is added to the cart. I saw notification about this in Facebook Pixel Helper, as well as when I checked with Facebook event testing tool. Please see attached screenshot from testing tool.

I've already tried resynching products with Facebook for WooCommerce, as well as switched plugin off and switched it on and set it up again. There seems to be no issues anywhere else except this double Add to Cart firing.
  
Could you please advise how to fix this issue?

Thanks in advance, 
Natalie

![Screenshot_8](https://user-images.githubusercontent.com/57008626/67581303-755d3d80-f750-11e9-823e-4bd8819dddbb.png)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
