### ISSUE TITLE
Inventory Field and Value Missing in Custom Parameters Sent

### ISSUE THREAD

**Issue by shaktics** [facebookincubator/facebook-for-woocommerce#1153]
Hello Development Team,

The Schema.org doesn't contain the inventory field and value. Please help me how to fix this asap.

Please see the Schema.org sent from Wordpress Woocommerce website to Facebook:

[{"dimensions":{"h":22,"w":1125},"properties":{},"subscopes":[{"dimensions":{"h":22,"w":67},"properties":{"item":"https://www.moniqueleshman.com","name":"HOME","position":"1"},"subscopes":[],"type":"http://schema.org/ListItem"},{"dimensions":{"h":22,"w":63},"properties":{"item":"https://www.moniqueleshman.com/shop/","name":"SHOP","position":"2"},"subscopes":[],"type":"http://schema.org/ListItem"},{"dimensions":{"h":22,"w":100},"properties":{"item":"https://www.moniqueleshman.com/product-category/necklaces/","name":"NECKLACES","position":"3"},"subscopes":[],"type":"http://schema.org/ListItem"}],"type":"http://schema.org/BreadcrumbList"},{"dimensions":{"h":946,"w":880},"properties":{"image":"https://www.moniqueleshman.com/wp-content/uploads/2019/09/1677389_16fa0ab8-183a-42ca-84cc-aa2af2d429af.jpe","name":"Tassel","sku":"Tassel Gold","url":"https://www.moniqueleshman.com/product/tassel/"},"subscopes":[],"type":"http://schema.org/Product"}]

Similarly, OpenGraph and JSON-LD also don't contain the Inventory field and value.

The product is getting added to the Facebook catalog, however, with error.

This is stopping the product from getting listed in Facebook Shop.

All the products in website are having the same issue.

Please help asap how to fix this.

Thank You,
Shakti
#Advertiser

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
