### ISSUE TITLE
Connection failed. Unable to connect my Woocommerce store and install Pixel

### ISSUE THREAD

**Issue by naser-baig-au4** [facebookincubator/facebook-for-woocommerce#1154]
Hi,

My store URL is https://theidealshopper.com

I am using latest WP and WooCommerce version. Trying to connect my store using this plugin but it always says that connection is failed. I am logged into my store and even on facebook.

I tried logging out and logging in to store, as well as facebook. Used different browsers and still unable to finish the integration.

I'd really appreciate any help in this regard. Attached is a screenshot for the integration popup.

https://www.dropbox.com/s/4891hnhuv0sib7j/Screenshot%202019-11-03%2016.34.09.png?dl=0

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
