### ISSUE TITLE
Facebook Pixel doesn't track events properly 

### ISSUE THREAD

**Issue by ColinvG** [facebookincubator/facebook-for-woocommerce#1155]
I have installed my Facebook Pixel on Woocommerce with the Integration Manager and when I just installed it, it worked fine. Unfortunately, after 2 weeks I just looked at my Pixel and the events are not working anymore. Only the Pageview event is firing, but other than that, no events worked. I've checked the plugin, but it seems to be all fine. Can someone help me, as I really need clean data at this point...

I also think that the Pageview event fires more then it should do. So maybe 2 times instead of 1, which creates false data. Can someone please have a look at my pixel as I am really struggling installing it right again. I've already tried to delete and reinstall the plugin but this doesn't help.

Facebook Page URL - https://www.facebook.com/TWIS-Clothing-304282490271718/
WordPress and WooCommerce version number - 3.7.1
Facebook Plugin version number - 1.9.11 
How many products you have - around 100
Types of products (i.e. anything besides simple/variable products won’t work) - clothing
Do you have Duplicate SKUs in your system? - no
What kind of customization plugins you’re using (if any)? - Not sure

**Comment by itrendstore** [comment]
Hello Colin!

I am struggling with the same problem. Could you find any solution for it since then?

Thanks,
Mihály

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by ColinvG** [comment]
Yeah I found a solution: I've changed to Shopify and things have been
working awesome over there :)
