### ISSUE TITLE
PHP Fatal error - get_id() - fbutils.php:90

### ISSUE THREAD

**Issue by kesz1tech** [facebookincubator/facebook-for-woocommerce#1156]
Had to disable the plugin as it was causing an error on checkout not redirecting the user after a credit card transaction but it was changing the card causing much confusion and refunds b/c the user kept clicking the submit button:

[06-Nov-2019 19:06:15 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_id() on boolean in /public_html/wp-content/plugins/facebook-for-woocommerce/includes/fbutils.php:90

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
