### ISSUE TITLE
Malformed JSON-LD

### ISSUE THREAD

**Issue by kooksystem** [facebookincubator/facebook-for-woocommerce#1157]
Facebook Pixel is not liking my JSON-LD schema, image of the error below:

![How To Error](https://user-images.githubusercontent.com/42525418/68374019-b3912e80-014c-11ea-97f4-f485fe790506.png)

![Console Error](https://user-images.githubusercontent.com/42525418/68374320-59dd3400-014d-11ea-8468-3eb6712f5a1d.png)

The JSON-LD schema used can be found here https://pastebin.com/embed_js/zxDnnjMw

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
