### ISSUE TITLE
Using "Default variable product" for the Content IDs of Variable products

### ISSUE THREAD

**Issue by alexhenniffent** [facebookincubator/facebook-for-woocommerce#1159]
Hi there,

So I'm using a plugin called "Product Feed Pro" (https://wordpress.org/plugins/woo-product-feed-pro/) for creating a product feed for my facebook shop. I'm then using the "Facebook for WooCommerce" plugin to place our pixel throughout our site.

For the most part, everything seems to be working except for how the FB extension is looking for the content ids of variable products. The FB catalog that was created using Product Feed Pro uses the "Default Product Variable" as the content ID for variable products, which is fine. But the FB extension by default looks for the product ID of the parent variable product, which is where a misalignment in content ids has started to occur.

I need to somehow adjust the plugins code so that it uses the "Default Product Variable" product ID instead of the product ID of the parent variable product. I'm assuming I will find this string of code in the "facebook-commerce-events-tracker.php" file?

If so, can someone assist me with telling me what I would need to alter in order to achieve the above? Is there some sort of dynamic parameter that refers to the "Default Product Variable"?

If unsure what I'm referring to, see here: https://i.ibb.co/hCWY3HR/Screen-Shot-2019-11-09-at-4-41-21-PM.png

In the image, you can see I have "Large" selected as the default variable product, so the product id that I'd like the FB extension to use should be #5903 (e.g. wc_content_id_5903).

Thanks,

Alex

**Comment by alexhenniffent** [comment]
advertiser

**Comment by alexhenniffent** [comment]
debug ready

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
