### ISSUE TITLE
Product Sync Minus

### ISSUE THREAD

**Issue by edm0d0n** [facebookincubator/facebook-for-woocommerce#116]
I added some products on my woocommerce store i forced sync and the progress shows -142 items remaining and goes more minus. I tried remove the product catalog and ad again also the same issue.  After forcing again after removing product catalog it just adds 30 products i left it open for 2 hours to sync.

**Comment by edm0d0n** [comment]
![image](https://user-images.githubusercontent.com/33116650/32041861-607e3816-ba3e-11e7-82ed-7965302bc3fa.png)

**Comment by edm0d0n** [comment]
It seems like the syncing lasts forever and i got a notice that cpu usage reached some limit on siteground hosting. When i go to watch the feed not all products are synced  only 140 varations and 30 products. Please find me a way to completely remove the plugin and reinstall. i need to remove some databases so the plugin syncs all products.

**Comment by mengyingdu** [comment]
Hi,

I can help you delete your setting ent in backend. Let's try it and let us know whether it works for sync later.

Just want to confirm: is this one (shown in your screen shot) your site? https://techkiddo.com/

**Comment by edm0d0n** [comment]
Yes sir this is the website. I want to completely remove the backend settings. What you need?

**Comment by edm0d0n** [comment]
You need access to my wordpress or something or i cann do it by myself?

**Comment by mengyingdu** [comment]
Hi,

I delete your setting (as latest record) in backend. Can you  try set-up again? 

Thanks.

**Comment by edm0d0n** [comment]
i am just trying it now. I will update when it finishes.

**Comment by mengyingdu** [comment]
Please keep admin page open when syncing.

**Comment by edm0d0n** [comment]
yes i know that sir. i think now everything is synced fine . You know what was causing this annoying problem? the - product sync?

**Comment by mengyingdu** [comment]
Hi,

Thanks for you confirm that. And I also check log for your site that everything works fine now. 
As for the reason of minus value, we put all your new products which are expected in queue to sync, however, for some reason, your woo post return 0, so counting keeps --, the weird minus number show.

Can you try to remember what have you done recently? It may help understand better what kind of manipulation may cause this weird issue.

Thanks.

**Comment by mengyingdu** [comment]
Which version of Woocommerce are you using now?

**Comment by edm0d0n** [comment]
I am using 3.1.1 . Do i need to update?

**Comment by mengyingdu** [comment]
3.1.1 should be fine.
I found that there are 69 products you want to post on 26th but today you post 68. Is that you intentionally delete one?

**Comment by edm0d0n** [comment]
Yes i deleted one

**Comment by dmitridr** [comment]
Hi,

Product sync is unfortunately pretty slow on shared hosting (Mentioned in #98 #83 others). This is gonna take a while to fix, we're gonna need to do a massive perf improvement.

The negative products remaining obviously shouldn't happen, looks like a display error. I think we can fix that based on @mengyingdu 's findings. 

I see you're on the plugin v1.6.0, is that right? Consider upgrading to 1.6.5. We did do a couple perf improvements for variable product sync in the past few versions, though I'm not sure how much it will speed it up for you.

**Comment by edm0d0n** [comment]
i just updated the plugin. i thought when a new version is out wordpress detects and notifies for the update. I was not notified idk why.

**Comment by mengyingdu** [comment]
Hi,

v1.6.6[https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.6]     is out, and fixes the minus remaining counting issue. As explained by @dmitridr , it's caused by race condition. Can you try upgrade to new version?

As for your question:
Facebook-for-Woocommerce is built on Woo, so currently Wordpress won't directly detect new version. We are consider other approach for better user experience.

**Comment by mengyingdu** [comment]
Hi,

[v1.6.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.6) is out, and fixes the minus remaining counting issue. As explained by @dmitridr , it's caused by race condition. Can you try upgrade to new version?

As for your question:
Facebook-for-Woocommerce is built on Woo, so currently Wordpress won't directly detect new version. We are consider other approach for better user experience.
