### ISSUE TITLE
Extension Setup Pixel Error

### ISSUE THREAD

**Issue by DBarwig** [facebookincubator/facebook-for-woocommerce#1160]
We will be launching advertising for an ecommerce client.

When trying to finish setting up the extension in a Wordpress Site, we are receiving the following error, even though the only FB pixel present, is the one which is auto-generated by the extension itself.  We confirmed this with the web developers.

<img width="1237" alt="Screen Shot 2019-11-11 at 11 58 54 AM" src="https://user-images.githubusercontent.com/57629631/68606591-c40f1500-047c-11ea-901e-36b7e1b88208.png">

We are also unable to find in the dropdown for the manual override with a pre-made pixel that we had setup with the advertiser account.

**Comment by gregmarzio** [comment]
I can confirm this issue.

I can only assign a Pixel from my personal account. This plugin does not detect any Pixels from my Business Manager account.

We need the ability to assign a Pixel from our Business Manager/Ad account please.

**Comment by klapperkopp** [comment]
Same issue here, no solution yet. I tried downloading the generated extension via the facebook setup tool, which provides a zip in the end, but that also didn't work.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
