### ISSUE TITLE
Database size

### ISSUE THREAD

**Issue by MrSidz** [facebookincubator/facebook-for-woocommerce#1161]
Hey,
Great plugin, working with him from day one.
I have noted that my Database wp_postmeta table have 12K rows and over 40MB in size.
disconnecting from Facebook, deleting the plugin etc, dos"t work.
do you have a simply way to clean it?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
