### ISSUE TITLE
No ViewContent tracking on product pages.

### ISSUE THREAD

**Issue by itrendstore** [facebookincubator/facebook-for-woocommerce#1162]
Hello!

I have my e-comm store: www.itrend.store

Installed the facebook for woocomerce plugin, but the viewcontent tracking code is not working. I mean If I check a product page and try to check the installed pixels there, there is no ViewContent pixel.

To solve the problem, I tried to install 'Pixel your site' plugin as well. If I do this, There is ViewContent pixel on the product page, but it cannot match the products, so the retargeting ads cannot work.

Facebook Page URL - https://www.facebook.com/itrendstore/
WordPress and WooCommerce version number - 3.8.0
Facebook Plugin version number - 1.9.15
How many products you have - around 1.500
Types of products (i.e. anything besides simple/variable products won’t work) - phonecasese
Do you have Duplicate SKUs in your system? - no
What kind of customization plugins you’re using (if any)? - Not sure

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
