### ISSUE TITLE
Displayed all variants in catalog (Dynamic Ads and Instagram)

### ISSUE THREAD

**Issue by marcogravina** [facebookincubator/facebook-for-woocommerce#1163]
Hello,

i have this problem, when I synchronize the catalog in the business manager every variation is shown to me as a single product (everything is ok from the Facebook showcase).

On WooCommerce I have 13 products (with their size and color variations), but on business managers it synchronizes them 68 products.

This creates problems for me to create Dynamic Ads with "Promote a product catalog" goal, as I would like to advertise the single generic product without having to choose the product with a specific variation.

Thank you
Marco

![img](https://user-images.githubusercontent.com/57671895/68683531-38be7e00-0567-11ea-968e-d57cd8e6ec7b.jpeg)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
