### ISSUE TITLE
Woocommerce for Facebook product variables and prices not showing up

### ISSUE THREAD

**Issue by kmasters79** [facebookincubator/facebook-for-woocommerce#1164]
Hi,

I have set up the woocommerce for facebook plugin, all seems to be looking good! Only there's one thing, the products are not showing variables (different prices and sizes). The 'sold individually' box in WP - variable products is not ticked. Can anyone enlighten me on what I am doing wrong? Site and facebook page:

www.lxck.pt
https://www.facebook.com/pg/LXeeseCake/shop/?ref=page_internal

Thanks so much!

K

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
