### ISSUE TITLE
FB Woo not sync'ing with FB Page Shop

### ISSUE THREAD

**Issue by gpclarke** [facebookincubator/facebook-for-woocommerce#1165]
My FB to Woo plugin is not sync'ing properly.  The FB SHOP Page shows "OUT of STOCK".  The FB Catalog shows products correctly except that one of the products on the Wordpress website side shows just fine.  

I have tied to get support via FB VIP Support and from Woocomerce but this their response:
"Thanks for contacting WooCommerce.com support.

We have a really great relationship with Facebook, and, as part of that, they’ve developed the extension you are using themselves. They’re also supporting the extension, providing help with getting it up and working the best way possible on your store.

You can get help with Facebook by using their support page on GitHub"

I don't seem to see anyone from FB responding within GitHub.

**Comment by pastbobg** [comment]
I too am having problems syncing from woo plugin to Facebook.  I can get it into the new event and catalogue on the business page but it will not sync to my site.  I am at a loss of what to do.  Woo only responds the same way as they did above, I can't get anyone from facebook to respond.

**Comment by calco2020** [comment]
I have the same issue. It suddenly our product catalog did not synchronize to the Fb shop. Using Facebook for woocommerce plugin which seems to be fine. 
The solution that Facebook support team has given me is to ask woocommerce, and then to come to Github to look for solutions....

Please, do you know if there is another way to connect or synch a FB catalog with woocommerce or wordpress it self?

**Comment by pastbobg** [comment]
Woocommerce sent me to get hub and Facebook and I have not found an answer on either platform.  Please give me a link if you think you found an answer.  All fixes I am finding are for the old way of doing the Facebook products

**Comment by gpclarke** [comment]
I'm still getting bouced around with FB support and have not gotten any solutions :(

**Comment by gpclarke** [comment]
I'm going to try the Feed Manager option, as I'm so frustrated with FB Support and getting NO responses on here.
Here's the product for others: https://rextheme.com/best-woocommerce-product-feed

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by gpclarke** [comment]
> Hey there! 👋
> 
> Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.
> 
> In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?
> 
> If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.
> 
> Thank you!

Thanks, but I've moved on from this tool since it took so long to get any support.  I might look at it again in the future.

**Comment by lgfogle** [comment]
Hey @gpclarke! Thanks for your response. I completely understanding needing to move on - if you ever decide to give Facebook for WooCommerce, please don't hesitate to reach out if there's anything we can do to help out!
