### ISSUE TITLE
connect catalog to FB shop  

### ISSUE THREAD

**Issue by Soheilr** [facebookincubator/facebook-for-woocommerce#1167]
plugin is working and create a catalog with all WC products but we cannon connect the catalog 
to our page :O 
there is no "connect to fb shop" in "use Cases" . 
it was just an announcement i know nobody will answer/help here :)

**Comment by calco2020** [comment]
It also happens to me... I ask for a solution too.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by Soheilr** [comment]
hey
thank you
i read some websites shutting down because of the last update and as we
need to work these days i didnt update your plugin .
what do you think is it safe to proceed ?
thanks again
