### ISSUE TITLE
Facebook for woocommerce

### ISSUE THREAD

**Issue by Pedro-calvo-lopez** [facebookincubator/facebook-for-woocommerce#1168]
I am trying to connect the plugins facebook for woocommerce in a woocommerce instance and there is no way to do it. Following the very simple explanatory steps in the adjustment section, when I select the specific page to synchronize, I am left blank not proceeding to select the corresponding pixel. By hand, I put the typical code with its pixel and nothing, the same. Once in a while as if by magic, if you strain, I select the pixel and perfectly makes and uploads the catalog, but does not visualize the wall of the store on facebook, which I have to proceed again to delete the catalog and start over again. Would there be someone who has happened the same thing, how could I fix it, may be that the plugins in the story has bugs for the latest version of wordpress 5.3 or woocommerce Version 3.8.0, please please some light clarifier because it is like going crazy. Greetings

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
