### ISSUE TITLE
URL encode/decode problem of product variation tag name

### ISSUE THREAD

**Issue by yukinoba** [facebookincubator/facebook-for-woocommerce#1169]
there is an issue when you using some non-AlphabeticNumeric name for your product's variation tag name. It will be shown as URL encoded form on the facebook product data like:

[https://i.imgur.com/oM63OM5.png](https://i.imgur.com/oM63OM5.png)

environment information:

version: 1.9.15
wordpress: 5.3
php: 7.3.12
woocommerce: 3.6.4

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
