### ISSUE TITLE
Two PageView Pixels tracked after installing Pixel plugin

### ISSUE THREAD

**Issue by senryxie** [facebookincubator/facebook-for-woocommerce#117]
After install with woocommerce, I used Facebook Pixel Helper to check my Pixel status.
I see two PageView Pixels are tracked. The one from woocommerce is ok, the other one from page itself failed. Any idea why there are two PageView trackings?
![image](https://user-images.githubusercontent.com/1171418/32064372-f0954756-ba79-11e7-904e-3783327b2f93.png)

**Comment by mengyingdu** [comment]
Hi,

That is a known pixel issue with the **pixel helper tool**, our pixel helper team is working on fixing it. You don't have to worry about that because the PageView is firing correctly.
