### ISSUE TITLE
When i use this plugin facebook sees it as spam

### ISSUE THREAD

**Issue by djohanarch** [facebookincubator/facebook-for-woocommerce#1171]
i had problem this messaged from facebook debbug "We can't review this website because the content doesn't meet our Community Standards"

WordPress Version 5.3 
WooCommerce Version 3.8.0
PHP Version 7.3.11
Facebook for WooCommerce Version:1.9.15

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
