### ISSUE TITLE
Problem showing products on Shop-page Facebook

### ISSUE THREAD

**Issue by webprepare-jordy** [facebookincubator/facebook-for-woocommerce#1174]
Hello,

My client is using your plug-in for showing their products on their Facebook page. In the plug-in everything is connected properly. Also the products are exported, as we may believe your plug-in. The problem is, there are no products shown:

See for instance: https://www.facebook.com/pg/byjensen.nl/shop/?rid=1250520584959583&rt=6&referral_code=page_shop_card

Woth mentioning is the fact that this Facebook-page is managed by another page. Is there any chance the issue occured due to this?

Regards,
Jordy

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
