### ISSUE TITLE
"Your API key is no longer valid" Keeps Recurring

### ISSUE THREAD

**Issue by algis100** [facebookincubator/facebook-for-woocommerce#1176]
Hi - quite often if I look in "WooCommerce" -> "Settings" -> "Integration" in the Wordpress backend for either of our two websites I see the following message in the Facebook section: Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token"
I go through the process of updating the Token and all looks good for a while, but soon enough when I check it again I get the same error message.
Any ideas why this happens so regularly?

**Comment by nnasnas1313** [comment]
Hi, the same issue happened to my Facebook for WooCommerce did you get any solution to guide me pls?

**Comment by algis100** [comment]
Hi - I'm afraid not, no one got back to me with a solution for this.
    On Monday, 27 January 2020, 16:31:50 GMT, nnasnas1313 <notifications@github.com> wrote:  
 
 
Hi, the same issue happened to my Facebook for WooCommerce did you get any solution to guide me pls?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
