### ISSUE TITLE
Facebook for WooCommerce

### ISSUE THREAD

**Issue by roandiazruiz** [facebookincubator/facebook-for-woocommerce#1178]
Hola buenas tardes, quería saber si me pueden ayudar, instale el complemento Facebook for WooCommerce en mi woocommerce 3.8.1 en wordpress-5.3, pero no es posible habilitar los productos que varios de ellos son rechazados, no publicados y / o con el siguiente mensaje, "La gente no puede ver este producto porque no lo seleccionó para venderlo en Facebook" que desmanteló el complemento y lo reinstalé, pero el problema continúa, por favor, ¿pueden ayudarme con estos inconvenientes ...

saludos 
rodrigo diaz

![falla plugin](https://user-images.githubusercontent.com/58581174/70294929-f5e97200-17c3-11ea-8f73-c52cc050e7cc.jpg)
![falla plugin-1](https://user-images.githubusercontent.com/58581174/70294930-f5e97200-17c3-11ea-9699-6a1d9b342179.jpg)
![falla plugin-2](https://user-images.githubusercontent.com/58581174/70294931-f6820880-17c3-11ea-9999-eb05e5796a2f.jpg)

**Comment by giuliapellegrini** [comment]
Same problem here. 
Some products are marked with exclamation icon in fb panel and sync from website appears to be disabled. 
Forcing sync doesn't work, as it respond as "sync complete" (from website) or freeze on loading as Rodrigo show in its second screen.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
