### ISSUE TITLE
Products continually processing after 3 days

### ISSUE THREAD

**Issue by Candyskullsandfishbones** [facebookincubator/facebook-for-woocommerce#1179]
I haven't found a recent thread on this unless I am being blind (am new to github) so sorry if this has been gone over a lot.

I have synced and resynced multiple times to attempt to fix this, but the only 3 products that have successfully synced are the ones that I had issue with saying they had rejected, and I manually requested a review on. I am assuming it is a facebook side issue however I can't find contact to go to them to get it fixed.

![image](https://user-images.githubusercontent.com/58521147/70315305-328f8a80-1811-11ea-8cc6-3fbf95eb707a.png)

Any advice or help please let me know!
Thanks in advance
~ Lexi

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
