### ISSUE TITLE
Facebook app Bug in Shops (Android)

### ISSUE THREAD

**Issue by nikidani86** [facebookincubator/facebook-for-woocommerce#118]
Hello, There is a problem with the update of the Facebook app for mobile.  The conection between the Facebook shop and the website is not stable.  Instead of transfering me in the website when i press the Buy button or Shop Now button, facebook crashed or it is displayed "An unexpected error occured".

**Comment by mengyingdu** [comment]
Hi,

We have noticed this issue now which should be a problem for Android app. I have filed a task internally to fix. Thank you so much. (It still works for IOS)

**Comment by dmitridr** [comment]
Seems like the shops team fixed the issue for on the latest version of the app, I tested a random woo shop and it works for me now. @nikidani86 can you confirm that the problem has gone away?

**Comment by mengyingdu** [comment]
Hi,

I close this task now since it should be fixed. If you still have this problem, let me know.
