### ISSUE TITLE
Not published products on facebook

### ISSUE THREAD

**Issue by askzipy** [facebookincubator/facebook-for-woocommerce#1182]
Hello, few of my products are showing not published and showing not published on facebook shop page https://snipboard.io/TpgNio.jpg, can someone help me please?

getting this error message "People cannot currently see this product because you haven't selected it for sale on Facebook."

**Comment by mdroca** [comment]
Same here. Any help??

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
