### ISSUE TITLE
Wrong Facebook pixel installed

### ISSUE THREAD

**Issue by lvsysop53** [facebookincubator/facebook-for-woocommerce#1183]
Debug Ready
Morning,   I Have two website on facebook.
https://pictureperfectfind.com &
https://handpaintedcrossbadybags.com

Using the Facebook Pixel on both pages the one on Pictureperfectfinds.com worked as expected and imported all the products from the website onto the facebook page.  

in the pictures below you see the exact steps.  It starts out using the correct Facebook Pixel but then it says I have the one for the wrong website and it will not let me change it to the correct one as it does not show up in the list to choose. 

On the handpaintedcrossbodybags setup it seems to want to grab the Facebook Pixel for the Pictureperfectfind.com website.  I have captured the screens.  It start out right when setting it up and then it switches.  Look:
![image](https://user-images.githubusercontent.com/58883286/70850149-dd203280-1e3b-11ea-9607-3511367c4c31.png)
![image](https://user-images.githubusercontent.com/58883286/70850151-e4dfd700-1e3b-11ea-8371-d247f26f794c.png)
![image](https://user-images.githubusercontent.com/58883286/70850153-ea3d2180-1e3b-11ea-9ee0-159a0f89f5e2.png)

I contacted Woocomerce and said to contact you and give you this information:

Facbook page url: Hand Painted Cross Body Bags- this is what it shows in the search bar on facebook which is weird as pictureperfectfinds shows: pictureperfectfind.com

Wordpress and Woocommerce version number:  WP: 5.3.1  WC:3.8.1

Facebook plugin for WC: 1.9.15

Currently there are 80 pictures (40 with front and back)   The products are pictures of cross body bags.

No SKU's are being used, just the image # from the camera and there are no duplicates.

No customized plugins that I know of.  I build a pretty simple website.

Appreciate any help you can offer

thank you, 

Charles

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
