### ISSUE TITLE
The plugin can't be set up because your currency ( Pakistan rupee ) is not supported. Learn more about supported currencies.

### ISSUE THREAD

**Issue by muddy-28** [facebookincubator/facebook-for-woocommerce#1185]
I have been trying to connect our woo-commerce store with our facebook shop using "Facebook for woo-commerce" plug-in. But it keeps giving an error when it tries to import the products, The error says; "The plugin can't be set up because your currency ( Pakistan rupee ) is not supported. Learn more about supported currencies." Although Pakistan Rupee is in the list of supported currencies provided by Facebook.

This issue is affecting our daily operations and our marketing activities on Facebook as well. 

A prompt response will be highly appreciated.

Best Regards.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
