### ISSUE TITLE
all 3 step for FB for WooCoom setting is in-complete! but no way to Edit it? now is sucked right there!

### ISSUE THREAD

**Issue by 4RCC** [facebookincubator/facebook-for-woocommerce#1186]
My problems are:-

Step -1  it ends up with no Fan Page name ? no idea which if my Website's FP been recorded or not?  but there no path to allow re-editing or correcting it?
Step- 2 pixel nbr quoted is different from what my Site been given but can't find a way to re-view or re-edit it?
Step-3 found Products pending to edit been uploaded into a separate FB page!  and the selling price is not Updated? 

The problems is there is no path to Allows/Edit them .  So All could be done to hold it up ..till  hear some solution to allow  to Edit/Correct again ...and now things been sucked.

Hope to get some advice here?

P.S.
Facebook Page URL (Be provided on request)
WordPress 5.3 and WooCommerce 3.8 version number
Facebook Plugin version number 1.9.15

**Comment by 4RCC** [comment]
Hi again,
I really hope someone could help to direct me how to re-set the FB for Woocommerce because it looks obviously the set up is not correct e.g. Pixel has not been built into any of the pages of my Website nor in any FB pages of my store...etc

So the fast way that believes that can get my Setting out of stagnant is re-setting up again, or 
provide Way/Path how to edit all the 3 steps all over again?

my website's FB fan page# Number:105127611004309

Any advice offered will be most appreciated.

**Comment by seuaCoder** [comment]
You need to delete the option directly in your database wp_options table

**Comment by seuaCoder** [comment]
Backup your site
Open myPHPadmin
Select the database you WordPress site uses
navigate to wp_options and click it.
Select the number of rows: and set to 500.
Search (ctrl-f) for "woocommerce_facebookcommerce_settings" You may have to to try more than one page to find it.
Click edit.
Clear the textarea called option_value
Save your work
In WooCommerce Setting navigate to the Facebook integration settings page and click "Get Started"

**Comment by 4RCC** [comment]
Thank You, Thank You SeuaCoder!   Though I might not manage to handle those coding work the solution so clear.......Honestly, dun thinks such plungin is mature enough to launch and  did see many issues here and there in each forum.

It is indeed very kind of you ....May You Have The Best Of The Best 2020 To Come!

**Comment by seuaCoder** [comment]
i can help you. Skype: tiger.marketer

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by 4RCC** [comment]
Hi  Igfogle,

Thanks for the update regarding 1.10 releases even 4RCC has given up using the FB for WooCommerce given all the obstacle we have been encountering, but connect our store with FB using separate way successfully.

But will re-try  when we have time later.


Thanks /4RCC
