### ISSUE TITLE
Cannot delete old/non-existing products from FB shop

### ISSUE THREAD

**Issue by iinobe** [facebookincubator/facebook-for-woocommerce#1188]
Hello Ive read past threads and I still can't seem to find a solution to deleting these products from my FB shop. Ive deleted all products from my WC site and yet they still show up in FB shop. I don't even have options to delete manually in FB.

- When I click "Shop" I see old products that don't exist on my WC back-end. (screenshot attached) 
- When I click "Manage catalog", I'm redirected to my FB homepage.
- When I click "Publishing Tools/Shop/Products", the Actions tab is grey (screenshot attached) 
- When I click "Setings/Shop", I don't see any options to manage the shop (screenshot attached) 

My goal is to remove all products from FB and start from scratch with synching products. 
Can these files be removed from the FB back-end?

Any help would be appreciated.
Thanks
-iinobe

DETAILS:

WP: Version 5.3.2
WC: Version 3.8.1
FB: https://facebook.com/iinobe/
FB Shop: https://web.facebook.com/pg/iinobe/shop/?ref=page_internal
Website: https://iinobe.com

SCREENSHOTS:

<img width="1176" alt="Screen Shot 2019-12-30 at 1 40 32 PM" src="https://user-images.githubusercontent.com/59364812/71584373-2cd44e80-2b0a-11ea-8faa-8c52079b4d2e.png">
<img width="1174" alt="Screen Shot 2019-12-30 at 1 36 26 PM" src="https://user-images.githubusercontent.com/59364812/71584374-2d6ce500-2b0a-11ea-88d2-f01f39ebefc8.png">
![Screen Shot 2019-12-30 at 3 17 20 AM](https://user-images.githubusercontent.com/59364812/71584376-2e057b80-2b0a-11ea-8bf3-96b530a24914.png)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
