### ISSUE TITLE
FB messed up my personal FB to  Fan Page plus Entreprise Management Platform a/c I created for my website??

### ISSUE THREAD

**Issue by 4RCC** [facebookincubator/facebook-for-woocommerce#1189]

**Comment by 4RCC** [comment]
Since FB has messed the 2 and now I can place Ads to my website at the business level?  I also  lost the path to enter the "Enterprise Management Platform Account" which built for my website!   

All the products from my Website been uploading into an FB page under my Personal FB account??  Pls help to stop this and must have the 2 things separated. !!

it might cause to facts that when my 1st attempt to activate "FB for WooCommerce" fail  stop it to link with my personal data because I am the operator and so everything link to my personal FB automatically i.e.  FAn page, STore create..etc  all not connect to my website but my personal FB!!!

 I try and try and try to un-plunge it and re-plunging then link everything to my website's email and contacts instead!!  but not allowed .....What can I do now?

BTW - how come all Enterprise Management Platform that already built under my website's name and having myself be the administrator can completely vanish?  i.e. I can not enter into it even thru the same URL?

Data:-
Facebook Plugin version number 1.9.15
WordPress 5.3 and WooCommerce 3.8 version number

URL here to show how my 1st attempt to use the Plugin i.e. everything is incomplete ****
https://www.facebook.com/ads/dia?origin=https%3A%2F%2Ffourrcc.com%20&merchant_settings_id=594873591271807#_=_  ****

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
