### ISSUE TITLE
Slows Down Site : Perf Needs Improvement & Async API Call on Update?

### ISSUE THREAD

**Issue by shreyans94** [facebookincubator/facebook-for-woocommerce#119]
Brings down the complete site for a minute if you try to save a product with lots of variations.

The plugin should push data to facebook asynchronously without impacting the site performance.

https://www.useloom.com/share/ff557d5b04c04b828193edcf519131e0

**Comment by javismiles** [comment]
I agree, it drives crazy slow my updating process on  wordpress site, totally unusable, this has to be asynchronous

**Comment by mengyingdu** [comment]
Hi @shreyans94 ,

Thanks for your video record. @dmitridr Since we add more support and features for variants, do you think we should improve a product with lots of variations? Or maybe there is some other problem for this site?

Thanks for your patience. Our current support rotation @dmitridr will work on this.

**Comment by dmitridr** [comment]
Thanks for flagging this. There's definitely more that we can do perf-wise for the sync to FB.

Can you share with us a screenshot of the product and variant configurations you have set up for this product? or at least tell us the # of variants you're dealing with here? It'll help to be able to set up a perf test on our own test servers.

If you don't have the latest version, I do recommend upgrading. There were a couple perf improvements in 1.6.x that should make variant uploads slightly faster.

**Comment by shreyans94** [comment]
@dmitridr There are about 45 variations in the product. 

This one 

https://nutrabay.com/product/optimum-nutrition-on-100-whey-gold-standard-2/

**Comment by tobiasfeistmantl** [comment]
Have the very same problem. I have variable products with 100s of variations. The complete site is unreachable for a few minutes. And without a swapfile it even fills up the complete RAM und then everything crashes. This is a big problem!

**Comment by kashalo** [comment]
Hello, i have also almost same issue, i have site contain more 10K product and with variation total 34K every time i try to sync with Facebook my site going so slow, i have to deactivate the plugin till this issue solved.

**Comment by tobiasfeistmantl** [comment]
Is there any progress on this issue? It's nearly impossible to publish products with a lot of variants since the website goes down for several minutes for everybody!

**Comment by bebemarketplace** [comment]
i have the same issue 1000 products with 10 variations each. site crashes, deactivate plugin. recently i cant event activate this plugin without crashing my site. please help. this has so much potential!

**Comment by bobteree** [comment]
This is not only about variations. It's about updating in general. When you have 2000 products this plugin brings your site to a crawl. Not exactly sure what is going on, but the plugin code is somehow consuming serious resources when being used with many products and WooCommerce. It is  functionally good, but performance is terrible with a large # of products. Lots of unnecessary updates going on in background I believe.

**Comment by bobteree** [comment]
Do those with many variants ALSO have many products?

**Comment by chillpilllike** [comment]
simply give an option to generate the feed for facebook catalogue and leave an option to not sync the products for site with many variations, this will stop the site hangs.

**Comment by mengyingdu** [comment]
Hi @chillpilllike, @bobteree, @bebemarketplace , @tobiasfeistmantl, @kashalo, @shreyans94 and @javismiles,
 
I'm excited to want to give you the update: In v1.8.1, we replaced the API approach with feed uploading for initial sync all products which improved the performance ~15X.

If you are still interested in our plugin, it's [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.1). 

Thanks.

**Comment by bobteree** [comment]
Thanks! Updating!

**Comment by wethreebears** [comment]
This is still an issue.  I have plugin verson 1.9.11 and it is making my site go so slow.
