### ISSUE TITLE
Filter/Hook to dynamically change SALE price

### ISSUE THREAD

**Issue by Jany-M** [facebookincubator/facebook-for-woocommerce#1191]
I use a custom solution to calculate Sale prices (setting a `n%` in a tax term and associating it with a product, which will cause the base price to be discounted in frontend and backend dynamically based on the `n%` of that term).

Since the **sale price is never saved to db** or to a product custom field, I need a filter/hook/way to manipulate the Sale price when the product syncs to FB.

Also, is there any **documentation** for this plugin??

**Comment by Jany-M** [comment]
Good thing I could answer my own question.
Dont'see any support from Faceboob or WooCommerce devs in here.

```
// Generating dynamically the product "sale price"
function custom_dynamic_sale_price( $sale_price, $product ) {
    $id = $product->get_id();
    $tax = get_the_terms($id,'product_cat');
    $regular_price = wc_format_decimal( $product->get_price() );
    $discount_total = 0;
    foreach ($tax as $term){
        $disc_single = get_field('sale_value', $term->taxonomy . '_' . $term->term_id);
        $discount_total += $disc_single;
    }

    if($discount_total !== 0 || $discount_total !== '')
        return wc_format_decimal($regular_price - ($regular_price / 100 * $discount_total));
    elseif($discount_total == 0 || $discount_total == '')
        return '';
    else
        return $sale_price;
};
if(is_admin()) {
    add_filter( 'woocommerce_product_get_sale_price', 'custom_dynamic_sale_price', 10, 2 );
    add_filter( 'woocommerce_product_variation_get_sale_price', 'custom_dynamic_sale_price', 10, 2 );
}
function custom_dynamic_sale_price_html( $price_html, $product ) {
    if( $product->is_type('variable') ) return $price_html;

    $price_html = wc_format_sale_price( wc_get_price_to_display( $product, array( 'price' => $product->get_regular_price() ) ), wc_get_price_to_display(  $product, array( 'price' => $product->get_sale_price() ) ) ) . $product->get_price_suffix();

    return $price_html;
}
if(is_admin()) {
    add_filter( 'woocommerce_get_price_html', 'custom_dynamic_sale_price_html', 20, 2 );
}
```

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
