### ISSUE TITLE
Unable to disable messanger chat option

### ISSUE THREAD

**Issue by guidigianmarco** [facebookincubator/facebook-for-woocommerce#1193]
Hi,
I’ve integrated Facebook for Woocommerce on mywebsite and I've activated the messenger add-on.
I’m now unable to disable it, if i click on “disable” it will reload the page but add-on is still present.

Website: [https://www.bibimima.com/](url)

Thanks for your help

**Comment by meek2100** [comment]
I'm seeing this as well.  It also won't let me change from the default icon theme to a custom one.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
