### ISSUE TITLE
Problem with selecting pixel

### ISSUE THREAD

**Issue by Dvalken** [facebookincubator/facebook-for-woocommerce#1194]
At this moment i am at the 3th step of the Facebok woocommerce, I need do make a pixel. the only problem is that its not showing the correct page in the drop down menu, what am i doing wrong? busy with this issue for two days now, hope someone can give me reasons why it is not showing so i can check if my settings are correct

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
