### ISSUE TITLE
Facebook only shows a few products.

### ISSUE THREAD

**Issue by ChilliForce** [facebookincubator/facebook-for-woocommerce#1195]
I am using the Facebook for woocommerce plugin, and it is the latest version, and i have set it up a couple of times and got the products to sync to my facebook shop from my woocomerce store, however if i am logged in as admin to the facebook page, i see all the products are there on facebook, but as a normal user, who hasnt even liked the page, they only see around 1/10th of the products that are there, alot of the products are hidden from what appears to be the public, or their is restrictions on them., The only thing thats confusing, is i see all the products on facebook as the admin... please let me know what may be the issue? What i can try?

**Comment by vijaykumarim** [comment]
Same problem here. I have 1500 products on my store but only 86 products showing ok ok in FB shop page. 

I waited till all products are synced but even after completing all the products the shop still shows 86 products. Now whenever I open the WooCommerce FB settings page it started syncing negative number of products.

Please help me. The plugin is always killing my site.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
