### ISSUE TITLE
Very slow loadning product table in admin

### ISSUE THREAD

**Issue by metuza** [facebookincubator/facebook-for-woocommerce#1198]
I have some products set as hidden for facebook and after that the product listings in admin loads very slow. After further investigation i found that all the hidden products generates these failed api calls.

400 Bad requests:
https://graph.facebook.com/v2.9/catalog:2403247003323XXX:XXXCLUZGMDA2XzI0ODk=/
?fields=id,product_group{id}
Redirected to:
https://graph.facebook.com/v2.9/catalog:2403247003323XXX:XXXCLUZGMDA2XzI0ODk=/
?fields=id,product_group%7Bid%7D

Actually i also get these errors when i update/save any of the hidden products. Which alos fill up my debug-logs.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
