### ISSUE TITLE
Facebook for Woocommerce reset

### ISSUE THREAD

**Issue by Iplaygamesnow** [facebookincubator/facebook-for-woocommerce#1199]
Hello
I have a problem when i click on "Get Token" i become this message "Sorry, this content isn't available right now" i deleted my Page in Facebook and opend a nother one, but FforW maybe use the old page settings  (Homepage: Https://www.i-playgames.de)  (Facebook side: https://www.facebook.com/I-Playgames-108924723994292)

**Comment by indesignegypt** [comment]
i have the same problem hope someone help us , as soon as possible

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
