### ISSUE TITLE
Support External/Affiliate Product Purchases + shop UI feature request

### ISSUE THREAD

**Issue by lauragobrightly** [facebookincubator/facebook-for-woocommerce#120]
When a customer tries to "buy" an external/affiliate Woocommerce product via Facebook buy button, they get redirected to my website's shopping cart with an error "You cannot add this product to cart." 

That's more or less working as functionally intended (since you shouldn't be able to add an external/affiliate product to cart)... but as a feature request, I'd love it if the Facebook Shop tab could add support for external/affiliate products (both on WooCommerce + other sources). A lot of brands/influencers/bloggers rely on affiliate links to generate income from their content, and I bet this feature would be pretty widely used.

**WooCommerce Plugin Implementation**
- MVP (basic) support: detect when a product is classified as an external/affiliate product, send the Call-to-Action blue button link to the product's detail page on the Woocommerce website vs. the add-to-cart direct approach
-- Cons to this approach: requires an extra step for customer to buy product, but is clear on why they've landed there

**General External/Affiliate Product Support**
UI updates needed (see attached image)
![affiliateproduct](https://user-images.githubusercontent.com/18519921/32147646-ea7a3bc6-bca7-11e7-8cf8-b483187fdc83.png)
- Marked as A on image: change grey text to say "Recommended by _Facebook Page Name_"
- Marked as B on image: change call-to-action on affiliate product button to say "Check Out on _Partner Website_" On clicking the button, the user would be brought to the affiliate website (most likely the product detail page). Page Admins would need to manually enter these URLs, or utilize integrations like WooCommerce
-- WooCommerce specific: automatically pull the external URL that's tagged to the product and place on this button
- Marked as C on image: grey text would specify where the link is going (ex: _This will take you to affiliatewebsite.com_). I would also think there needs to be legal text mentioning that the Facebook Page will receive a commission from the sale. 

I have no idea where this falls on your roadmap, but it could be a powerhouse feature to introduce before the holiday season. I'm a PM (could you tell?) at another Bay Area tech company and am setting up a new Woocommerce powered marketplace as a side-hustle (which does utilize some affiliate links, but not all.) Happy to chat through this if you are interested.

PS -- overall, the Woocommerce + Facebook integration is amazing. Good job FB team, reinventing e-commerce purchase funnels FTW!

**Comment by dmitridr** [comment]
Hello,

There's a workaround that you can use to avoid the error when adding to cart. It's outlined in #29. Basically there's already a setting (very hard to find unfortunately) that will allow you to change the behavior of the button. Can you try that and see that works for your case?

That said, your MVP implementation suggestion is good, I think we can implement that pretty easily. I don't think that the external/affiliate product should ever be added to cart ... unless there is a case I'm not seeing.

Appreciate the design suggestions for the general support, but we are not the team that controls that design though we'll pass it along to our shops team to see what they think!

**Comment by mengyingdu** [comment]
Hi,

Version [1.7.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.0) is ready now and we add more support for external product
if they click on check-out, we will redirect them to the product url which you put in product editor.
Can you try to upgrade?

Thanks.

**Comment by mengyingdu** [comment]
Given we haven't received update for 6 months and it should be fixed 1.7.0, close it now. Feel free to reopen it if you other problems. Thanks.
