### ISSUE TITLE
URL is set in content_id value in Catalogue Manager

### ISSUE THREAD

**Issue by shabbir-bharmal** [facebookincubator/facebook-for-woocommerce#1200]
Content_id is saved as the URL of the product. For testing purposes, I have also changed the code of get_fb_retailer_id() but no change has affected. I have removed all products from the "Catalogue Manager" and your plugin sync button but newly entered products have URL instead of product id. Please check the attachment for more clearance.  

![77260077-7f4c-431f-a85e-6e20986d492e](https://user-images.githubusercontent.com/29979167/73247146-44b8f400-41d6-11ea-969b-e17cde76b130.png)

Please check this issue why it is happening ASAP I need this to fix it ASAP.

Thank you in advance.

**Comment by shabbir-bharmal** [comment]
Hello, I am waiting for you to return, about the problem that still persists

**Comment by shabbir-bharmal** [comment]
Hi is there any updates?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
