### ISSUE TITLE
Publish repo tag up to date

### ISSUE THREAD

**Issue by cfaria** [facebookincubator/facebook-for-woocommerce#1201]
Hi, I'm using composer to install this plugin with bedrock. Is it possible to have the version tag updated to version 1.9.15. 

Last tagged version is 1.9.10 and we are a bit behind ;D

Thank you!!

**Comment by cfaria** [comment]
Hi, can you please tag the current release?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by cfaria** [comment]
It's still untagged. Last tag is 1.9.10.

Anyway I'll use wpackagist to install it right away from wordpress.org. Thank you.
