### ISSUE TITLE
Facebook for WooCommerce PlugIn Not Syncing

### ISSUE THREAD

**Issue by 1982-sophie** [facebookincubator/facebook-for-woocommerce#1203]
I’m having real trouble trying to connect my clients website/shop section to Facebook - I did it fine last week but then had to delete the whole thing and start again as I’d selected ‘Message to Buy’ when setting up the shop, and should have selected ’Sale through external website’ or however it’s worded in order to set up Instagram shopping via her Facebook page too. I’ve added the Facebook pixel and Woocommerce plugin to the website, this all looks like it’s in and installed but then the pixel is showing as greyed out and ’not ready’ when I try to use this to import the products into the catalogue. It won't verify in Facebook. I've uninstalled, and reinstalled many times, can anyone help please?

**Comment by michaelcsso** [comment]
I have the same problem.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
