### ISSUE TITLE
Products without "Published" status upload to Shop and Publish, Why ???

### ISSUE THREAD

**Issue by hungdangdt** [facebookincubator/facebook-for-woocommerce#1204]
Hi,

I have 133 products in store, 21 in published, 112 in Draft. But this plugin upload all them to facebook and PUBLISH all on facebook shop. on my site will return 404 when click product from facebook.

How to fix it ? or I had wrong config ?

Thank you!

**Comment by fxaviers** [comment]
+1 same issue

**Comment by aether-user** [comment]
Same here.. Workaround: mark the products Private in woocommerce..

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
