### ISSUE TITLE
Bug in facebook-commerce-events-tracker.php

### ISSUE THREAD

**Issue by huntersbest** [facebookincubator/facebook-for-woocommerce#1205]
Mix up of Parent Product and Variations in Lines 228 and 235 (bold is corrected)

         * Triggers ViewContent product pages
         */
        public function inject_view_content_event() {
            if ( ! self::$isEnabled ) {
                return;
            }
            global $post;
            $product      = wc_get_product( $post->ID );
            **$content_type = 'product';**
            if ( ! $product ) {
                return;
            }

            // if product is a variant, fire the pixel with content_type: product_group
            if ( WC_Facebookcommerce_Utils::is_variation_type( $product->get_type() ) ) {
                **$content_type = 'product_group';**
            }

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
