### ISSUE TITLE
Storefront theme menu button on mobile doesn't work

### ISSUE THREAD

**Issue by jmslcs** [facebookincubator/facebook-for-woocommerce#1207]
Hi,

There seems to be a couple of issues with my of Facebook for Woocommerce, not sure if this is the cause, but I've disabled the plug in and it seems to resolve the issue. When viewing my site dontduckitup.co.uk on a mobile, such as an iPhone the menu button doesn't work. It should expand the menu I've got set up, but it doesn't when this plugin is enabled. 

I can't see where this has already been reported?

many thanks :)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
