### ISSUE TITLE
Unable to select pixel

### ISSUE THREAD

**Issue by MarkRabey** [facebookincubator/facebook-for-woocommerce#1209]
When attempting to setup in WooCommerce, on the 3rd step "Facebook Pixel", the drop down only has one pixel available and it is not the one created for the page I selected. It doesn't seem to patter what page I select on step 2, I am only given the same single option for the pixel.

**Comment by freshsheep** [comment]
Same here

**Comment by mixpack** [comment]
I have the same problem

**Comment by MarkRabey** [comment]
@freshsheep @mixpack Make sure your pixel is connected to an Ads Account. After doing that it worked. There were some other issues around the account the ads account was on, but that's not an issue with the plugin at all.
