### ISSUE TITLE
Updating  product slows down website a lot

### ISSUE THREAD

**Issue by javismiles** [facebookincubator/facebook-for-woocommerce#121]
Updating any product with your plugin active makes it go so so so so slow, 
but so slow that often it crashes with a 500 timeout error,
folks, these tasks should be asynchronous or in any case its crazy that your plugin slows down product updating so so so much

**Comment by mengyingdu** [comment]
Hey @dmitridr, can you take a look at javismiles's issue ? I forward his detailed site information to you.

**Comment by dmitridr** [comment]
Agree. Seems like a duplicate of #119. We'll see what we can do about the perf.

**Comment by mengyingdu** [comment]
duplicate of #119

**Comment by kkeennaa** [comment]
Horrible plugin. My site loads so much slower because of it.
