### ISSUE TITLE
FB Woo Problems with product Sync to product catalog

### ISSUE THREAD

**Issue by Jakoshi** [facebookincubator/facebook-for-woocommerce#1210]
When trying to synch our products to our Facebook catalog there is no error visible for the whole catalog. However, looking at a single product we get the „Missing or Incorrect Data“ error. All of our WooCommerce products are affected by this error. We tried to create a new product in Facebook manually, which worked without an error. We then compared the product data and found out two differences. 

#### Capabilities

The error free product has the following values for the capabilities field: 

> ["B2C_MARKETPLACE","DA","SHOPS"]

All products with an error have the following values: 

> ["DA"]

#### Has Main Image Fetched

The error free product has 
> true

as a value, whereas all other products with an error have 
> false

as a value

**Here is an overview the product data for a non working product**

<img width="518" alt="error_prod" src="https://user-images.githubusercontent.com/60102683/75360248-d3905d80-58b5-11ea-9147-2a4ceed916f6.png">

**And here is the data for the manually created product that works.** 

<img width="528" alt="succ_prod" src="https://user-images.githubusercontent.com/60102683/75360379-ffabde80-58b5-11ea-8898-7d50408cd6e3.png">

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
