### ISSUE TITLE
Products not showing up on Facebook shop page

### ISSUE THREAD

**Issue by awoodfinz** [facebookincubator/facebook-for-woocommerce#1211]
I went through the setup process but products are not showing up on the Facebook shop page after about 30 hours

Here is the Facebook page

https://www.facebook.com/pg/ASL-Industries-Ltd-641019692701962/shop/?ref=page_internal

Here is the wordPress shop

https://www.aslindustries.co.nz/shop-categories/

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
