### ISSUE TITLE
AddToCart has wrong value

### ISSUE THREAD

**Issue by fdmsaraiva** [facebookincubator/facebook-for-woocommerce#1212]
The wrong woocommerce variable is being used in the `value` property of the `AddToCart` event.

The variable currently being used produces the cart total at the time the event is triggered. This variable would make sense for an `InitiateCheckout` or `Purchase` event, however, in an `AddToCart` event, I'd expect the value to be the price of the product added to the cart.

**Comment by lgfogle** [comment]
Hey @fdmsaraiva, 

Thanks for reaching out! In the Facebook for WooCommerce 2.0.0 release, we made significant updates to the Facebook pixel to improve accuracy and security. Could you please upgrade and open a new issue if this problem is still occurring on that version?

Thank you!
