### ISSUE TITLE
Tax not added to variable product prices

### ISSUE THREAD

**Issue by V8gremlin** [facebookincubator/facebook-for-woocommerce#1213]
My Woocommerce shop is set to enter prices excluding tax (VAT) on products.  In that configuration, for variable products which are taxable, the tax is not added to the ex tax price when loaded into the FB shop catalogue.  This works correctly for simple products.  There is a temporary workaround if the product variants all have the same price to write that into the Facebook price to override it.  However that is not workable for variable products that have different prices for the variants so needs a code fix, please

**Comment by lgfogle** [comment]
Hey @V8gremlin,

Could you please confirm if you're still experiencing this issue in the latest version of the plugin, Facebook for WooCommerce 2.0.0? We made many improvements to product syncing in that update, and I wonder if it addressed this issue as well.

If not, could you please open a new issue with steps to replicate this problem?

Thank you!
Lindsey

**Comment by V8gremlin** [comment]
Hi,

I have checked the V2 plugin and as far as I can see the variant product VAT problem seems to have been resolved.

If it arises again in further use will report again

Thanks

A
