### ISSUE TITLE
Getting Fetal Error PHP 7.3

### ISSUE THREAD

**Issue by suneth2** [facebookincubator/facebook-for-woocommerce#1214]
I'm getting this after add new plugin version, the previous versions never had this kind of issue, is there have any quick fix for this

WooCommerce version: 3.6.5
WordPress version:  5.2.5
Server info: Apache
PHP version: 7.3.15

`Fatal error: Uncaught Error: Call to a member function getTimestamp() on bool in /home/ccc/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php:93 Stack trace: #0 /home/ccc/public_html/wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/Lifecycle.php(284): SkyVerge\WooCommerce\Facebook\Lifecycle->upgrade_to_1_10_0('1.9.15') #1 /home/oxy7000/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php(57): SkyVerge\WooCommerce\PluginFramework\v5_5_4\Plugin\Lifecycle->upgrade('1.9.15') #2 /home/ccc/public_html/wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/Lifecycle.php(115): SkyVerge\WooCommerce\Facebook\Lifecycle->install() #3 /home/oxy7000/public_html/wp-includes/class-wp-hook.php(286): SkyVerge\WooCommerce\PluginFramework\v5_5_4\Plugin\Lifecycle->init('') #4 /home/oxy7000/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #5 /home/oxy7000/public_htm in /home/ccc/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php on line 93`

**Comment by simonporter007** [comment]
Hey @suneth2!

Thanks for reaching out with this issue! It looks like our upgrade routine, in order to migrate the legacy settings to our new format, is failing when parsing your `pixel_install_time`. The new plugin will try and convert this timestamp to UTC format, and judging by the stack trace, this is returning false.

Would it be possible to let me know what the current value for `pixel_install_time` is inside the `woocommerce_facebookcommerce_settings` WordPress option stored in your database?

Cheers!

**Comment by suneth2** [comment]
actually there were no pixel value becoz run a db cleanup after duplicate site, i manually set value instead of getTimestamp(); then it works and after i revert the above manual value, everything is fine now,  i think it's better to add some validation for it if there haven't any time don't call for timestamp something. or may be my case is a specific one :) anyway we can close the issue

**Comment by simonporter007** [comment]
Hey @suneth2, thanks so much for letting me know! That sounds like a fine workaround in the meantime. I'll relay your information to our development team regarding the validation, as that does make a lot of sense.

Sorry for the interruption caused, and thanks for bearing with us!
