### ISSUE TITLE
Backend Issue on Plugin update

### ISSUE THREAD

**Issue by restre** [facebookincubator/facebook-for-woocommerce#1215]
I just updated my facebook-for-woocommerce plugin and now I can't access the admin backend of WordPress with the following error message

https://prnt.sc/rbpido

I had to uninstall the plugin directly from the server side to be hable to acceso the admin login page.

Any advice?

**Comment by adamburke210890** [comment]
I get a 

'There has been a critical error on your website. Please check your site admin email inbox for instructions.

Learn more about debugging in WordPress.'

and can't access the admin area of wordpress. Same solution of deleting from server side.

**Comment by simonporter007** [comment]
Hi @restre / @adamburke210890 !

Thanks so much for reporting this issue, and apologies for the delay in responding to you so far. Our developers have recently been made aware of this issue since our latest update, and have patched the issue already. They're looking to deploy a new version today hopefully with a few more fixes.

In the meantime, if you'd like to verify the fix, you can find a pre-release version here: <a href="https://cloud.skyver.ge/KouW4dBE">https://cloud.skyver.ge/KouW4dBE</a>

To use the pre-release, please deactivate and delete the plugin, then upload and activate this version from the Plugins page. Don’t worry, you won’t lose any settings or data! :)

Please note that you may see a notice prompting you to update the plugin; if so, you can safely ignore this until version 1.10.1. 

Would you please upload the pre-release version of the plugin and let me know if it resolves the issue for you?

Cheers!

**Comment by adamburke210890** [comment]
Hi,

The plugin now installs without messing my website up but the products dont seem to be syncing. That could be something to do with the laptop i am using so will try again tomorrow at work.

Thanks for your response.

Adam
________________________________

**Comment by restre** [comment]
Same for me, it didn't seem to be making the sync right, si I took it off again y installed version 1.9.11, which works perfect for me as of now...

**Comment by adamburke210890** [comment]
Where can I get the 1.9.11 download? Can't find it anywhere?

**Comment by restre** [comment]
I downloaded it form the WordPress repository, after installing I got the 1.10 updated promt, don't update it...

**Comment by simonporter007** [comment]
Hey @adamburke210890 / @restre , thanks so much for keeping me updated! It sounds like there is something not quite right with the syncing, though I'll need a bit more information to investigate further for you. It would also be helpful to gain access to the store so that we can check over the product data and compare that with the Facebook shop to see exactly what isn't being synced, and see why.

GitHub isn't the best way forward to begin troubleshooting issues like these, especially if we need sensitive data such as a temporary login or site information. If you'd like us to take a further look at these sync issues, would you please raise a request through [our support form](https://www.skyverge.com/contact/?form_type=general) so we can speak with you directly?

Cheers!

**Comment by adamburke210890** [comment]
#outlook a { padding:0; }
          body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
          table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
          img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
          p { display:block;margin:13px 0; ***@***.*** only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
.mj-column-per-33-333333333333336 { width:33.333333333333336% !important; max-width: 33.333333333333336%; }
.mj-column-per-90 { width:90% !important; max-width: 90%; }
.mj-column-per-70 { width:70% !important; max-width: 70%; }
.mj-column-per-15 { width:15% !important; max-width: 15%; }
.mj-column-per-20 { width:20% !important; max-width: 20%; }
      ***@***.*** only screen and (max-width:480px) {
      table.mj-full-width-mobile { width: 100% !important; }
      td.mj-full-width-mobile { width: auto !important; }
    }a:not(.plain-blue-link) {
        color: inherit;
        text-decoration: none;
      }
      a:not(.plain-blue-link):visited {
        color: inherit;
      }

      body {
        padding: 0;
      }

      /* Hack to override blue links
       * https://litmus.com/blog/how-to-remove-blue-links-in-html-emails */

      a {
          color: inherit !important;
          text-decoration: none;
          font-size: inherit;
          font-family: inherit;
          font-weight: inherit;
          line-height: inherit;
      }

      .secondary-button a {
        color: #333333 !important;
      }

      .primary-button a {
        color: white !important;
      }

      .grey-button a {
        color: white !important;
      ***@***.*** (min-width: 600px) {
        .desktop-only {
          display: block !important;
        }

        .desktop-only-column {
          display: table !important;
        }

        .mobile-only {
          display: none !important;
        }
      ***@***.*** (max-width: 480px) {
        .large-button table {
          width: 200px !important;
        }

        .large-button td {
          height: 50px !important;
        }

        .large-button a {
          width: 200px !important;

          padding-top: 18px !important;
          padding-bottom: 18px !important;
        }
      }

      @media (min-width: 600px) {
        .large-button table {
          width: 348px !important;
        }

        .large-button td {
          height: 50px !important;
        }

        .large-button a {
          width: 250px !important;

          padding-top: 18px !important;
          padding-bottom: 18px !important;
        }
      }a{
        text-underline-position: under;
      }
      .email-content{
        white-space: pre-line;
      ***@***.*** (max-width: 480px) { 
        .text-count div {
          display: none !important;
        }
      } Hi there,

I’d love to order your products for my store! I do my wholesale buying on Faire, the online marketplace, and I think your brand would be a great fit. Find more information about Faire below.

Adam from Adam's bargains Sell on Faire This message was sent by Adam's bargains through Faire Why sell on Faire?01Reach 200,000+ retailers onlinethrough Faire’s marketplaceGive your brand effortless exposure to local retailers across the U.S. and Canada.02Offer your buyers net 60 terms,covered by FaireAll brick-and-mortar stores get net 60 terms on Faire, to help you get more sales.03Get 0% commissionWhen you invite your existing buyers to buy your products on Faire, we’ll never charge you commission on their orders. Ever.Ready to grow your wholesale business?Get Started TodayFAIRE 2021Help CenterUnsubscribe

**Comment by adamburke210890** [comment]
Apply to sell on Faire, the leading online wholesale platform and marketplace that 200,000 independent retailers use to stock their stores.

VariantA_LongCopy_Slice1 (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkfJ41W4MqlB_8KQnq-W4QxXl85k_0PhW8JCvtg5JvwMgf1KTlgd03 )

VariantA_LongCopy_Slice2 (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkfJ41W4MqlB_8KQnq-W4QxXl85k_0PhW8JCvtg5JvwMgf1KTlgd13 )

VariantA_LongCopy_Slice3 (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkfJ41W4MqlB_8KQnq-W4QxXl85k_0PhW8JCvtg5JvwMgf1KTlgd23 )

Faire, 100 Potrero Ave, San Francisco, CA 94103, United States

Manage preferences (https://hs-6171711.s.hubspotemail.net/hs/manage-preferences/unsubscribe?d=VnBg0B7Y5dD-W2p76LK3-1rCSW43Z92c47RZWtW4tynYk3M64BQW1SCh6p3M2gmJW3W42ZN3KbsvFW3R0grZ4pxxZlW4rdYl145RlhdW3P28X24hCPvhW43T2ND7DNj_RW17f7hv6-0R3VW8YX8s65LPcZ_W51S94f8YzScsV28TTh7VS-Q5MGKd_P20N58W3YrFCg47BW9qW1ZgNKG4Pq7Sh5115rZ1&amp%3Bv=3&_hsenc=p2ANqtz-828EtqBF-2poIBQ95dceCxLF7_jV_RGEaUZw2n7QZ-vsQLytDEoeOMvZu4Jfk4PrUxIGaxjsD9oiJ8x1cHgVruhtrQqseakRdsysO88nOfiAiHxkxVKV5VBAeUQLLKsOO2lRUMCQSEW6sM24rtKgUSv8zQXQ&_hsmi=140575664 )

**Comment by adamburke210890** [comment]
Apply to Faire, the online platform and marketplace where you can sell wholesale and run your business, all in one place.

NurtureEmail2_Slice1 (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkDhCNW7fMJbh8vQNXgW8PBgd05fJm4ZW6tf8M67QrDtbf1KTlgd03 )

NurtureEmail2_Slice3 (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkDhCNW7fMJbh8vQNXgW8PBgd05fJm4ZW6tf8M67QrDtbf1KTlgd13 )

Faire, 100 Potrero Ave, San Francisco, CA 94103, United States

Manage preferences (https://hs-6171711.s.hubspotemail.net/hs/manage-preferences/unsubscribe?d=VnBg0B7Y5dD-W2p76LK3-1rCSW43Z92c47RZWtW4tynYk3M64BQW1SCh6p3M2gmJW3W42ZN3KbsvFW3R0grZ4pxxZlW4rdYl145RlhdW3P28X24hCPvhW43T2ND7DNj_RW17f7hv8HZ2lPW57nq-M50khYjW4Y74dV7jymZQV28PSh5yRMqwMGKd_P20N8FMMJ000bsLZ3W6FJ69W2KdNBn51568c1&amp%3Bv=3&_hsenc=p2ANqtz-_v-6N5er_lKuQ6hSHd05PodQ-JUk6batyw3K95V6NsyOl-NaGjZohfUdjXJhff-VdsSGYBTVBTKqVqyKaXEMHd6m03D-ec63f5CTzQsiMJTEJ3TsWNi6HCbt85NtFnDHmXijGtefAiPyE6Twpe0colXryXGg&_hsmi=142564439 )

**Comment by adamburke210890** [comment]
Brands like yours use Faire to learn, grow, and succeed in their businesses.

NurtureEmail3_Slice1fromtoday (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbk3lyWW5ZsJgN5kgWKdW8HHNVz98lfg2W8JCvv16-vDwNf1KTlgd03 )

Slice 14-4 (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbk3lyWW5ZsJgN5kgWKdW8HHNVz98lfg2W8JCvv16-vDwNf1KTlgd13 )

NurtureEmail3_Slice4 (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbk3lyWW5ZsJgN5kgWKdW8HHNVz98lfg2W8JCvv16-vDwNf1KTlgd23 )

Faire, 100 Potrero Ave, San Francisco, CA 94103, United States

Manage preferences (https://hs-6171711.s.hubspotemail.net/hs/manage-preferences/unsubscribe?d=VnBg0B7Y5dD-W2p76LK3-1rCSW43Z92c47RZWtW4tynYk3M64BQW1SCh6p3M2gmJW3W42ZN3KbsvFW3R0grZ4pxxZlW4rdYl145RlhdW3P28X24hCPvhW43T2ND7DNj_RW17f7hv62_0LjW8Ds3Q35BW1_cW51BQtj53kS82V28Ytj7DyYQSMGKd_P20N5TN6lX0MfwBM4cW75ZF1S4G3HtH4W5Kp1&amp%3Bv=3&_hsenc=p2ANqtz-9a6Y--U7rGii_9pJlpzf5Z8ILNvYgfdIDdoViMj5JZFT-5D_X20CNq_3cc3lLc6onnCJAi0L1RZ69v5T98VEIfgdMggbU7eYPYBoH0TrMtpsz7a4No0ao9lIj2d2dXx11ljlLchObDj2ofCZBoKMrNeuqkFg&_hsmi=144582307 )

**Comment by adamburke210890** [comment]
Faire handles the messy parts of selling wholesale, like payment terms and verifications—and you only pay commission when retailers discover you on Faire.

NurtureEmail4_Slice1 (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8ykGsx_W6YMHkt8YzX9qW6dCY199bhy9BVXwTLL8YRYj7dBzP8M04 )

NurtureEmail4_Slice2 (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8ykGsx_W6YMHkt8YzX9qW6dCY199bhy9BVXwTLL8YRYj7dBzP8N04 )

NurtureEmail4_Slice3 (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8ykGsx_W6YMHkt8YzX9qW6dCY199bhy9BVXwTLL8YRYj7dBzP8P04 )

Faire, 100 Potrero Ave, San Francisco, CA 94103, United States

Manage preferences (https://hs-6171711.s.hubspotemail.net/hs/manage-preferences/unsubscribe?d=VnzSxZ7Y5dD-W2p76LK3-1rCSW43Z92c47RZWtW4tynYk3M64BQW1SCh6p3M2gmJW3W42ZN3KbsvFW3R0grZ4pxxZlW4rdYl145RlhdW3P28X24hCPvhW43T2ND7DNj_RW15gBJz8VcnrwW8Lh6Z25q1js2W5DDzn34Zpr29VWnTsd6FvFg6MXk_7Qbw9pkW83J0jB2z068TW2wCLw-7MDh0n3bZQ2&amp%3Bv=3&_hsenc=p2ANqtz-84wYRwJhWg5J3mkWtn-1xwIaKIoevpvHz2YoRHdSlU-j3FBmrDO_q63qfDCOVgoEL-iojzxA8ek6b12GW4Cv2_vwhS2HoZC8ggqXY8EcRqSX9-ZiJUFxywA4S2vWSt17JC_N5Bd1fN4s5Ue2KIR5FniIQjzg&_hsmi=146628944 )

**Comment by adamburke210890** [comment]
We built Faire to empower independent brands like yours to sell wholesale online and be successful in an ever-evolving industry.

Slice 22-Jul-22-2021-12-19-18-60-AM (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkgcFsW9gfz2d55HxpFW8dZQcr4Kk6DlW65wJLr7nbLN1f1KTlgd03 )

Slice 23-Jul-22-2021-12-19-48-09-AM (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkgcFsW9gfz2d55HxpFW8dZQcr4Kk6DlW65wJLr7nbLN1f1KTlgd13 )

Slice 24-Jul-22-2021-12-20-33-95-AM (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkgcFsW9gfz2d55HxpFW8dZQcr4Kk6DlW65wJLr7nbLN1f1KTlgd23 )

Faire, 100 Potrero Ave, San Francisco, CA 94103, United States

Manage preferences (https://hs-6171711.s.hubspotemail.net/hs/manage-preferences/unsubscribe?d=VnBg0B7Y5dD-W2p76LK3-1rCSW43Z92c47RZWtW4tynYk3M64BQW1SCh6p3M2gmJW3W42ZN3KbsvFW3R0grZ4pxxZlW4rdYl145RlhdW3P28X24hCPvhW43T2ND7DNj_RW17f7hv70xdmcW51NPtp6L2-BLW4R6xHM8mgfKhV28WmL7F300LMGKd_P20N5BW1cQjXN3hL3HWW8H1tsq5mSp9R4v_mJ1&amp%3Bv=3&_hsenc=p2ANqtz-9tIi2EyRYY0WBDRBANoAyEPjQNpZkt66zEqGe4OoYy0hdsPdYgJK7nBGn5Pviyx8Ns1QqfuvQHpguVDsaThSihH567leAWbA-wuVr_oMwInUHgzhNBvl6mR8h-gH3DO3z1F_6QC1KaQZcmQbE1vjIpiUtyQw&_hsmi=148703175 )
