### ISSUE TITLE
Este produto ainda não está sincronizado com o Facebook - Gostaria que resolvessem

### ISSUE THREAD

**Issue by Afonso-Silva-com** [facebookincubator/facebook-for-woocommerce#1216]
Eu fiz o cadastro pq fui obrigado para conseguir ver respostas ou comentar. Ao fazer o cadastro aqui neste forum, onde pensei que fossem soluções de problemas na verdade é só um agragador dos problemas existentes. 

Não vi nenhum usuário aqui com a sua pergunta respondida. Sendo assim, eu acredito que não terei respostas, por isso, estou desinstalando aqui...

**Comment by lgfogle** [comment]
Hey there,

Thanks for reaching out! 

For plugin support, could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
