### ISSUE TITLE
My Manage Connection Button is Not Working Properly 

### ISSUE THREAD

**Issue by Greenisland** [facebookincubator/facebook-for-woocommerce#1218]
I deactivated the Facebook plugin for a couple hours. When I checked back I saw this message "Your connection has expired. Please click Manage connection > Advanced Options > Update Token to refresh your connection to Facebook." However, when I click the Manage Connection button it takes me to a page that says "Sorry, this content isn't available right now." 
Please see the video link below:

https://www.loom.com/share/a1fd2ff2a5044f4ea4351d7709af8d03

**Comment by simonporter007** [comment]
Hey @Greenisland!

Thanks for reaching out about our latest update, I'm sorry the connection isn't able to get established at the moment, I'd be happy to look into this further.

In order to do so, I'd like to request temporary access to your site so that we can take a closer look. It sounds like the "_Sorry, this content isn't available right now_" message appeared in a pop-up, though I couldn't see this in the video. It would be great to confirm this first! If that is the case, it sounds like there may be some clash with the settings and the Facebook wizard, which we don't have too much control over.

Perhaps it would be possible to reset the settings in your WooCommerce store directly so we could try again.

If you'd like us to go ahead and investigate this further, could you please raise a support request [via our support form](https://www.skyverge.com/contact/?form_type=general) so we can speak with you directly regarding site details and credentials?

Cheers,

**Comment by Greenisland** [comment]
Simon, thanks for your speedy response. Yes, you are correct, the message did appear in a pop-up. As you've requested, I'm giving you temporary access to the site as shown below:
login URL: https://usaforall.net/auqiran/
username: overdrivepaul@yahoo.com
Password:  Auqiran+1988

Thank you again,
Paul
Discipline Determines Your Destiny 



CONFIDENTIALITY NOTICE: This E-Mail is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you have received this communication in error, please do not distribute and delete the original message. Please notify the sender by E-Mail at the address shown. Thank you for your compliance. 

    On Thursday, March 12, 2020, 08:33:52 AM EDT, Simon Porter <notifications@github.com> wrote:  
 
 


Hey @Greenisland!

Thanks for reaching out about our latest update, I'm sorry the connection isn't able to get established at the moment, I'd be happy to look into this further.

In order to do so, I'd like to request temporary access to your site so that we can take a closer look. It sounds like the "Sorry, this content isn't available right now" message appeared in a pop-up, though I couldn't see this in the video. It would be great to confirm this first! If that is the case, it sounds like there may be some clash with the settings and the Facebook wizard, which we don't have too much control over.

Perhaps it would be possible to reset the settings in your WooCommerce store directly so we could try again.

If you'd like us to go ahead and investigate this further, could you please raise a support request via our support form so we can speak with you directly regarding site details and credentials?

Cheers,

**Comment by simonporter007** [comment]
Hey @Greenisland,

Thanks so much for that. You may wish to edit your comment though, to prevent unwanted access to your store!

It looks as though there has been some corruption between the associated account and the store. I think the best way forward would be to remove the current settings the plugin has stored, to let you re-login and link it with the current Facebook shop and pixel.

To do so, I'd need to delete a few options the plugin stores from the database. I notice that you have Updraft Plus installed, would it please be possible for you to take a database backup for good housekeeping, and let me know when that has been done?

Cheers!

**Comment by Greenisland** [comment]
Simon, my database is updated daily and this site is not yet fully up and running so please feel free to do what you need to do.
Thanks,
Paul
Discipline Determines Your Destiny 



CONFIDENTIALITY NOTICE: This E-Mail is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you have received this communication in error, please do not distribute and delete the original message. Please notify the sender by E-Mail at the address shown. Thank you for your compliance. 

    On Thursday, March 12, 2020, 01:16:07 PM EDT, Simon Porter <notifications@github.com> wrote:  
 
 


Hey @Greenisland,

Thanks so much for that. You may wish to edit your comment though, to prevent unwanted access to your store!

It looks as though there has been some corruption between the associated account and the store. I think the best way forward would be to remove the current settings the plugin has stored, to let you re-login and link it with the current Facebook shop and pixel.

To do so, I'd need to delete a few options the plugin stores from the database. I notice that you have Updraft Plus installed, would it please be possible for you to take a database backup for good housekeeping, and let me know when that has been done?

Cheers!

**Comment by simonporter007** [comment]
Hey @Greenisland,

Thanks for letting me know! I've removed the settings from the database, and can now see that the "_Get Started_" button is showing which will launch the wizard. I can also see that this now loads the wizard instead of the error message we were seeing previously.

I've deleted the database plugin I had installed and logged out of admin. If we need to do further troubleshooting, I'll need a password reset as it was not stored.

That said, please could you run through this setup again and let me know if it now connects?

Cheers!

**Comment by Greenisland** [comment]
Thanks for all your help Simon. Unfortunately, I have an emergency in my home so I won't be able to set up until about 24 hours. I will definitely let you know my results.
Again, thank you. 
Paul
Discipline Determines Your Destiny 



CONFIDENTIALITY NOTICE: This E-Mail is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you have received this communication in error, please do not distribute and delete the original message. Please notify the sender by E-Mail at the address shown. Thank you for your compliance. 

    On Thursday, March 12, 2020, 07:28:59 PM EDT, Simon Porter <notifications@github.com> wrote:  
 
 


Hey @Greenisland,

Thanks for letting me know! I've removed the settings from the database, and can now see that the "Get Started" button is showing which will launch the wizard. I can also see that this now loads the wizard instead of the error message we were seeing previously.

I've deleted the database plugin I had installed and logged out of admin. If we need to do further troubleshooting, I'll need a password reset as it was not stored.

That said, please could you run through this setup again and let me know if it now connects?

Cheers!

**Comment by Greenisland** [comment]
Thanks for your great help Simon.
However, I'm still having an issue that is described in the screenshots attached.
Paul
Discipline Determines Your Destiny 



CONFIDENTIALITY NOTICE: This E-Mail is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you have received this communication in error, please do not distribute and delete the original message. Please notify the sender by E-Mail at the address shown. Thank you for your compliance. 

    On Thursday, March 12, 2020, 07:28:59 PM EDT, Simon Porter <notifications@github.com> wrote:  
 
 


Hey @Greenisland,

Thanks for letting me know! I've removed the settings from the database, and can now see that the "Get Started" button is showing which will launch the wizard. I can also see that this now loads the wizard instead of the error message we were seeing previously.

I've deleted the database plugin I had installed and logged out of admin. If we need to do further troubleshooting, I'll need a password reset as it was not stored.

That said, please could you run through this setup again and let me know if it now connects?

Cheers!

**Comment by Greenisland** [comment]
Thanks for your great help Simon. However, I'm still having an issue as described in the screenshots attached.

![Facebook_Connect](https://user-images.githubusercontent.com/47468527/76719371-00df6700-6710-11ea-9e78-645a16561dc6.png)
![Step_2_Facebook_Connect](https://user-images.githubusercontent.com/47468527/76719391-0dfc5600-6710-11ea-8ffc-f20e162fc250.png)

**Comment by simonporter007** [comment]
Hi @Greenisland.

Strange! When deleting the settings locally, and re-running the setup wizard, I am able to select the existing page from the drop-down list instead:

![image](https://user-images.githubusercontent.com/2094229/76741855-2304d380-6768-11ea-88c7-a904d36d0add.png)

It looks like there is a message behind the "create page". would it be possible to let me know what that says?

Cheers,

**Comment by Greenisland** [comment]
Thanks for your speedy response Simon. The attached screenshot is what's behind the "create page."
Paul
Discipline Determines Your Destiny 



CONFIDENTIALITY NOTICE: This E-Mail is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you have received this communication in error, please do not distribute and delete the original message. Please notify the sender by E-Mail at the address shown. Thank you for your compliance. 

    On Monday, March 16, 2020, 05:26:57 AM EDT, Simon Porter <notifications@github.com> wrote:  
 
 


Hi @Greenisland.

Strange! When deleting the settings locally, and re-running the setup wizard, I am able to select the existing page from the drop-down list instead:



It looks like there is a message behind the "create page". would it be possible to let me know what that says?

Cheers,

**Comment by Greenisland** [comment]
![Facebook_connect_3](https://user-images.githubusercontent.com/47468527/76759249-abcc4100-6761-11ea-8689-240bd7626ffa.png)

**Comment by Greenisland** [comment]
That's what's behind the "create page Simon. Thanks for your speedy response.

**Comment by simonporter007** [comment]
Hi @Greenisland, sorry for the delay today! Thanks for passing over those screenshots. That is super strange indeed then! In one instance, it mentions that there is no Facebook page created, and then when trying to create a page, it mentions you already manage a page with the same name!

Could it be that your account you used to login with is only allowed to manage the Facebook shop page, but it isn't the owner of the same page? Could you confirm that the account you're using through the plugin set up wizard is marked as the owner of the shop page as described here: https://www.businessinsider.com/how-to-add-admin-to-facebook-page?r=US&IR=T

Cheers!

**Comment by Shentia** [comment]
Hi 
I have this problem but I can solve it after a long time searching ... 
So I open option from PHPMYADMIN 
And change pixel Ad 




UPDATE `wp_options` SET `option_value` = 'a:29:{s:17:\"facebook_pixel_id\";s:16:\"YOUR CODE \";s:24:\"enable_advanced_matching\";s:2:\"no\";s:16:\"facebook_page_id\";s:15:\"YOUR CODE\";s:19:\"enable_product_sync\";s:3:\"yes\";s:17:\"enable_debug_mode\";s:2:\"no\";s:24:\"product_description_mode\";s:5:\"short\";s:29:\"excluded_product_category_ids\";s:0:\"\";s:24:\"excluded_product_tag_ids\";s:0:\"\";s:12:\"fb_upload_id\";s:15:\"497782587567620\";s:15:\"upload_end_time\";s:24:\"2020-03-21T02:44:11+0000\";i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";s:23:\"scheduled_resync_offset\";s:0:\"\";s:16:\"enable_messenger\";s:3:\"yes\";s:18:\"messenger_greeting\";s:24:\"Hi! How can we help you?\";s:16:\"messenger_locale\";s:5:\"en_US\";s:19:\"messenger_color_hex\";s:7:\"#c2af79\";s:18:\"pixel_install_time\";s:19:\"2020-03-21 02:39:35\";s:10:\"fb_api_key\";s:175:\"EAAVmx1AUlYwBAN01dW1dXCgpP12ZA7ipzeu9DiXF7IKhuxhjSlMn2GsAhfwxi1KpPtR9qpjz8wf4A4tuEOn4TEkIrGZC5Rqq2hYCJ4UAZA1ADgq6seV7XID7ohHxEWia[...]

**Comment by Greenisland** [comment]
Thanks. I will try your suggestion.
Paul
Discipline Determines Your Destiny 



CONFIDENTIALITY NOTICE: This E-Mail is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you have received this communication in error, please do not distribute and delete the original message. Please notify the sender by E-Mail at the address shown. Thank you for your compliance. 

    On Friday, March 20, 2020, 11:38:57 PM EDT, Ahmadreza Shamimi <notifications@github.com> wrote:  
 
 


Hi
I have this problem but I can solve it after a long time searching ...
So I open option from PHPMYADMIN
And change pixel Ad

UPDATE wp_options SET option_value = 'a:29:{s:17:"facebook_pixel_id";s:16:"YOUR CODE ";s:24:"enable_advanced_matching";s:2:"no";s:16:"facebook_page_id";s:15:"YOUR CODE";s:19:"enable_product_sync";s:3:"yes";s:17:"enable_debug_mode";s:2:"no";s:24:"product_description_mode";s:5:"short";s:29:"excluded_product_category_ids";s:0:"";s:24:"excluded_product_tag_ids";s:0:"";s:12:"fb_upload_id";s:15:"497782587567620";s:15:"upload_end_time";s:24:"2020-03-21T02:44:11+0000";i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";s:23:"scheduled_resync_offset";s:0:"";s:16:"enable_messenger";s:3:"yes";s:18:"messenger_greeting";s:24:"Hi! How can we help you?";s:16:"messenger_locale";s:5:"en_US";s:19:"messenger_color_hex";s:7:"#c2af79";s:18:"pixel_install_time";s:19:"2020-03-21 02:39:35";s:10:"fb_api_key";s:175:"EAAVmx1AUlYwBAN01dW1dXCgpP12ZA7ipzeu9DiXF7IKhuxhjSlMn2GsAhfwxi1KpPtR9qpjz8wf4A4tuEOn4TEkIrGZC5Rqq2hYCJ4UAZA1ADgq6seV7XID7ohHxEWia[...]

**Comment by Greenisland** [comment]
I checked in phpmyadmin but I don't see anything for facebook there. If you see this and respond, please be a little more detailed in your description of what you did and how exactly you did it. The Facebook plugin was working excellently until I deactivated it for a few hours. When I went back into my admin I saw the message mentioned at the top of this page and my problems began.

**Comment by hlzma** [comment]
I am having the exact same problem. I was able to get it to work last week and then all of a sudden the integration disconnected and now my products are no longer syncing to the shop on my facebook page.

**Comment by Greenisland** [comment]
When the Facebook plugin is working properly it works like a charm. However, the support for the plugin is sorely lacking and this is why it only has a 2-star rating. Yes, I know it's a free plugin but Facebook makes so much money from ad revenue that they could easily provide much better support for this plugin. Shame on them!

**Comment by hlzma** [comment]
> When the Facebook plugin is working properly it works like a charm. However, the support for the plugin is sorely lacking and this is why it only has a 2-star rating. Yes, I know it's a free plugin but Facebook makes so much money from ad revenue that they could easily provide much better support for this plugin. Shame on them!

I agree! I would understand the lack of support if Woocommerce is less used than other e-commerce CMSs. But it's one of the most used CMS out there. It's pretty disappointing.

**Comment by AmoG876mp** [comment]
Hi, 
@simonporter007 can you please contact me as i am experincing the same issue and would like you to reset the plugin.
i.amojee@gmail.com
0789547266

**Comment by simonporter007** [comment]
Hey @AmoG876mp!

For support related issues, it's best to raise a support request on the support forum: https://wordpress.org/support/plugin/facebook-for-woocommerce/ as the support team is not monitoring the development repository.

As for your question though, we now have a small little plugin you can install to help reset the plugin settings without the need for DB access that we had above.

Would you please download and install the [following plugin](https://cloud.skyver.ge/X6uOEyG9)? This will add a new tool available at **WooCommerce** > **Status** > **Tools** called "_Reset Facebook for WooCommerce settings_". Please click the **Reset Settings** button here, and then navigate back to the Facebook for WooCommerce plugin settings screen to try again!

If there are any further issues with that, please do raise a support forum request, and we can make sure it gets looked at further!

Cheers,
