### ISSUE TITLE
Display issue in Products page column

### ISSUE THREAD

**Issue by nabeel-s** [facebookincubator/facebook-for-woocommerce#1219]
Hi, in Products page, there is a strange display issue in a column, please see this screenshot: https://nimb.ws/3MyqOV

Please fix this urgently and release an update.

**Comment by simonporter007** [comment]
Hey @nabeel-s !

We did tweak the column names of these columns slightly in the new version, and it sounds like the size of the data may be causing a few display issues with your existing set of columns! 

It should be possible to adjust the available columns to either remove the Facebook ones, or remove some of the other columns to ensure it can be displayed correctly. You can do this from the top of the screen by clicking the Screen Options tab, which will then allow you to select which columns should appear in the list.

![image](https://user-images.githubusercontent.com/2094229/76545606-0031a100-6482-11ea-896c-92f835cba87a.png)

Here I've removed the Featured, and Tags columns, which has resolved the display issue. Another option might be to look into [Admin Columns plugin](https://www.admincolumns.com/), which looks to [allow for Horizontal Scrolling](https://www.admincolumns.com/columns-sets-horizontal-scrolling/) too!

Could you try either of these suggestions and let me know if that works for you? :)

Cheers!

**Comment by nabeel-s** [comment]
Thanks, that does help. Please check this error in the column, which is occurring a lot: https://nimb.ws/FGLIJ9

**Comment by simonporter007** [comment]
Hey @nabeel-s, thanks for letting me know! Can I confirm that you're running the latest version of the plugin at the moment, v1.10.1?

**Comment by nabeel-s** [comment]
Yes, recently installed. WooCommerce version is 4.0.0.

**Comment by simonporter007** [comment]
Hey @nabeel-s, thanks so much!

I've raised this for our developers to take a look at for a future release. At this moment, we haven't been able to replicate the same issue, though it should be possible to add additional safety checks to avoid it.

Thanks so much for letting us know about this! Is there anything else I can help out with today?

Cheers,

**Comment by nabeel-s** [comment]
That's all for now, I will let you know if I come across other issues. Thanks.

**Comment by simonporter007** [comment]
Excellent, thanks so much for confirming this for me! I'm going to mark this thread as "closed" now, but if you run into any other questions or issues, please feel free to reply again to re-open it or create a follow up -- we're happy to help out. :)
