### ISSUE TITLE
Sync problem : Caused by Product Duplication

### ISSUE THREAD

**Issue by Agiplan** [facebookincubator/facebook-for-woocommerce#122]
Dear All,

I would like to get help with the program. I use the latest version of everything (wordpress, woocommerce and of course facebook for woocommerce plugin too), but the sync does not work correctly.
New products will not appear on my Facebook Shop site, but will display some of them, say archived products, even though the admin interface does not allow the look.
What could be the problem?

Thank you for your kindly help!

**Comment by dmitridr** [comment]
Hello, 

It could depend on how you are adding the new products, if you are adding them through bulk editor, or WP All Import, then these products will not show up unless you do a 'Force Resync'. Could you describe how you add a new product and what kind of product it is? (We do not support some kinds) 

As for archived and other supposedly invisible products appearing in the shop, the current workaround would be to manually hide them using the visibility toggle on the product edit page. It's our current top priority to fix this issue (See #75) in the meantime.

**Comment by Agiplan** [comment]
Dear Dmitri,

Thank you for your answers. I do not use any bulk uploaders. If I already have a product (such as a headphone) I simply duplicate it and edit it all over (name, url, short and long description etc.stb.stb)
My products are simple, everything about mobile music. Headphones, earphones, portable speakers, portable players, DAC, AMP, car hi-fi, earplugs, earmuffs, etc.etc.etc. No extra. Look at my site at the link below
I tried the ’force resync’ several times but nothing happened. So far, the program worked well, but once there were no new products. There are a couple of products that appear on the newly uploaded, but there are more that do not show up.

Waiting for your kindly answer!
Best regards

Zoltan Balogh

Company: The Art Galery Kft.
Phone: +36-70/384-9002
E-mail: info@artgalery.hu
Web: https://mobilzene.hu, 

Feladó: Dmitri Dranishnikov
Elküldve: 2017. november 1., szerda 2:33
Címzett: facebookincubator/facebook-for-woocommerce
Másolatot kap: Agiplan; Author
Tárgy: Re: [facebookincubator/facebook-for-woocommerce] Sync problem (#122)

Hello,
It could depend on how you are adding the new products, if you are adding them through bulk editor, or WP All Import, then these products will not show up unless you do a 'Force Resync'. Could you describe how you add a new product and what kind of product it is? (We do not support some kinds)
As for archived and other supposedly invisible products appearing in the shop, the current workaround would be to manually hide them using the visibility toggle on the product edit page. It's our current top priority to fix this issue (See #75) in the meantime.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Ezt az e-mailt az Avast víruskereső szoftver átvizsgálta.
https://www.avast.com/antivirus

**Comment by Agiplan** [comment]
Hi Dmitri,

I think my proplem solved. The source of the error is duplicated by the product. If I cliclk a 'Reset Facebook metadata' the product will appear in the Facebook Shop.
But, some of the products still under processing are already ready. What do you think this?

Reagrds
Zoltan

Feladó: Dmitri Dranishnikov
Elküldve: 2017. november 1., szerda 2:33
Címzett: facebookincubator/facebook-for-woocommerce
Másolatot kap: Agiplan; Author
Tárgy: Re: [facebookincubator/facebook-for-woocommerce] Sync problem (#122)

Hello,
It could depend on how you are adding the new products, if you are adding them through bulk editor, or WP All Import, then these products will not show up unless you do a 'Force Resync'. Could you describe how you add a new product and what kind of product it is? (We do not support some kinds)
As for archived and other supposedly invisible products appearing in the shop, the current workaround would be to manually hide them using the visibility toggle on the product edit page. It's our current top priority to fix this issue (See #75) in the meantime.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Ezt az e-mailt az Avast víruskereső szoftver átvizsgálta.
https://www.avast.com/antivirus

**Comment by dmitridr** [comment]
Hi Zoltan,

Glad your problem is solved. Looks like this was related to #101 with the duplication problem you mentioned. I'm not sure what you mean about the products under processing. If you could send us a screenshot (or post it in the GitHub issue) of the weird behavior you are seeing perhaps we can explain what's going on.

**Comment by Agiplan** [comment]
Dear dmitridr,

Look at some pictures:
1. [apparently everything is fine](https://user-images.githubusercontent.com/10388693/32532069-e78c235a-c447-11e7-9f0e-c917fb108914.jpg)
2. [but, the product is being processed](https://user-images.githubusercontent.com/10388693/32532095-22b297b6-c448-11e7-943f-cc37a59de469.jpg)
3. [while the product works on my site](https://user-images.githubusercontent.com/10388693/32532162-a37b1fa8-c448-11e7-890a-61528b00eae2.jpg)

And this "mistake" happens randomly for a few product. What could be the problem?

**Comment by mengyingdu** [comment]
Hi,

When you update your product, normally there will be a short time range for processing. Can you wait for a couple of minutes and then check? I do see 'processing' status right after update in testing your problem and it changed to complete status afterwards.
Let me know whether it works.

Thanks.

**Comment by dmitridr** [comment]
Going to close this as there has not been a response for a while. 

- We fixed the 'Duplication' problem in the original issue in the new version v1.7.3
- I think Mengying's comment explains the 'mistake' you saw. There's a temporary time during which the product is processing after update, this has to do with our system reviewing your product for policy compliance.

Feel free to open a new issue and reference this one if you have another similar problem!
