### ISSUE TITLE
Shortcodes in Facebook for WooCommerce

### ISSUE THREAD

**Issue by Aleyclori** [facebookincubator/facebook-for-woocommerce#1223]
Hello,

i also have problems with the showing shortcodes in Facebook for WooCommerce. How can i get this thing done?
![FIle](https://user-images.githubusercontent.com/62370035/77034079-51252600-69a9-11ea-9fb9-a11e08bdad9b.PNG)

I updated all versions to the latest ones.

Thanks and best regards,

Alex

**Comment by simonporter007** [comment]
Hey @Aleyclori,

Thanks for your question. To clarify, are you looking to remove the shortcodes from the description in Facebook, or were you looking for them to behave as they would do on your WordPress site?

I'm afraid shortcodes are pieces of code that can only run inside a WordPress environment and the Facebook page would not understand what these were supposed to do. It will be output as plain text instead.

That said, the latest version of the plugin has an option for adjusting which product description is sync'd to the store. You can find this from the plugin settings available at **WooCommerce** > **Settings** > **Integration** > **Facebook for WooCommerce** and switching the _Product description sync_ option.

This way it might be possible to keep the shortcodes for WooCommerce, and use the other description for Facebook! Would this help with your request here do you think?

Cheers!

**Comment by Aleyclori** [comment]
Hello, thanks for the answer

I want to remove the shortcodes from fb. In the settings of the Plug in i just can ad a short description, but that doesn’t  change much...

Mhmm, so are there no alternatives?

Thanks and best regards,

Alex

Von meinem iPhone gesendet

**Comment by simonporter007** [comment]
Hi Alex,

If you add a short description without shortcodes, and then sync the short description in the plugin settings, is this not removing the description on the Facebook page? Or is it still syncing the full description instead?

Cheers!

**Comment by lgfogle** [comment]
Hey @Aleyclori,

If this issue still persists, could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
