### ISSUE TITLE
Asset cache busting is using time.

### ISSUE THREAD

**Issue by matt-h** [facebookincubator/facebook-for-woocommerce#1224]
Currently the asset cache busting is using time like this:
```
'/assets/js/facebook-infobanner.min.js?ts=' . time()
```

This makes it so the javascript files will never be cached.

Can this be updated to use the normal include way which includes the plugin version number with `wp_enqueue_script`?

**Comment by lgfogle** [comment]
Hey @matt-h,

We'll be including this fix in our next release, which is currently in testing with Facebook. Could you please reach out after that release to us know if there are any other concerns related to this issue?

Cheers!
Lindsey
