### ISSUE TITLE
Products not showing up in Facebook shop

### ISSUE THREAD

**Issue by gasket1988** [facebookincubator/facebook-for-woocommerce#1225]
Hello,

I've set up facebook for woocommerce on my wordpress website. (www.volkltenniscanada.ca)

Seems like the set up is done well, and seems like the products have been pushed (synced) with the facebook page (volkltenniscanada) but nothing appears on the shop page on facebook.

Please help out. I have facebook for woocommerce 1.10.2 on wordpress 5.3.2

**Comment by lgfogle** [comment]
Hey there,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
