### ISSUE TITLE
Issues Connecting Pixel to Catalog ADVERTISER

### ISSUE THREAD

**Issue by crpmarketing** [facebookincubator/facebook-for-woocommerce#1227]
Hey guys,

I've been having some issues trying to connect my Facebook Pixel with a Catalog. I've been using the plugin Facebook for Woocommerce, and most of the features are working fine. However, it looked like the plugin is not generating any metadata for "Brand" or "Availability". I'm not super familiar with coding, but I have been in contact with the developer of the site, and even he is having issues with it. I would do it manually, but our product catalog consists of over 5000 SKUs and are updated frequently. Any help would be much appreciated!

**Comment by lgfogle** [comment]
Hey @crpmarketing,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
