### ISSUE TITLE
Variant vs Short Description

### ISSUE THREAD

**Issue by cr8tiff** [facebookincubator/facebook-for-woocommerce#1229]
Hi 
90% of my products on woo commerce have variants and when I use the plugin to place the products on my Facebook shop I selected short description thinking that would bring up the products' short description, however when its a variant it doesn't work as expected (works perfectly when not a variant product tho). 
If the product is a variant it brings across the description of that variant, which makes sense, however its the short description from the main product page I was expecting to see.

For example:
https://flipster.com.au/shop/shampoo_bars/midnight_rosemary_vegan_shampoo_bar/

On the page above the "short description" is the paragraph under the title explaining the product and this is what I expected to come through to FB Shop. 
But if you select one of the product options (shampoo bar or Shampoo Bar & Tin) you will notice another shorter description show up underneath which is set in the variant e.g. Shampoo Bar – Packaged in recyclable brown paper bag. - or - Travel Tin – Ideal for storing your Shampoo Bar while traveling. Perfect for carry-on luggage. These are the descriptions I am getting in the FB shop which isn't very helpful.

IS there anyway to sync the "main" short description instead of the variant's short description??
Any help would be appreciated.

Thanks

**Comment by cr8tiff** [comment]
Don't worry, figured out that there is now an extra field where you can input a special description.

**Comment by Iamrahi** [comment]
Hi can you let me know what was the issue. in my case the product description is not coming through to the Facebook shop. And the variant details are shown in product details. Original product description also contains size charts how can I show them in facebook description as an image??

**Comment by lgfogle** [comment]
Hey @cr8tiff,

Happy to hear that you were able to find that special Facebook description field and that it's working out for you!

@Iamrahi, if you're still having problems with how your products are presented in Facebook, could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
