### ISSUE TITLE
Products not showing up properly on Products page

### ISSUE THREAD

**Issue by Yunislav** [facebookincubator/facebook-for-woocommerce#1232]
<img width="1037" alt="Screenshot 2020-04-03 at 19 24 42" src="https://user-images.githubusercontent.com/12301590/78388184-dc74fd00-75e0-11ea-956c-ba46b63d5b7d.png">

**Comment by lgfogle** [comment]
Hey @Yunislav ,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
