### ISSUE TITLE
deleted the Initial product sync from WooCommerce

### ISSUE THREAD

**Issue by fashakra** [facebookincubator/facebook-for-woocommerce#1234]
I deleted the "Initial product sync from WooCommerce. DO NOT DELETE." 
It did not delete all the products from my Catalog and now i cannot resync my products from my woocommerce store.
receiving the following error:
_There was an error trying to sync the products to Facebook. We couldn't create the feed or upload the product information._

**Comment by lgfogle** [comment]
Hey @fashakra,

We'll be including this fix in our next release, which is currently in testing with Facebook. Could you please reach out after that release to us know if there are any other concerns related to this issue?

Cheers!
Lindsey
