### ISSUE TITLE
Product variations are not displayed correctly in the new Facebook interface

### ISSUE THREAD

**Issue by carlosmdh** [facebookincubator/facebook-for-woocommerce#1236]
Hi guys

I am trying to import a store made with WooCommerce to Facebook. For this I am using the Facebook for WooCommerce plugin and I have encountered the following problem.

If the store has variations, for example sizes and colors of a garment. When going to make the purchase from the new Facebook interface, you cannot choose the size or color of the product. In addition, the button below takes you directly to the checkout with which you take the customer to buy without having been able to choose.

I don't know if the problem is that the new Facebook update is incomplete or if it is Facebook WooCommerce plugin is outdated for this new Facebook Interface.

Store, is a test are in: https://plataformamultiatlas.com/
Facebook Store are in https://www.facebook.com/pg/carl0smdh/shop/
Variable product is Producto 1
WordPress: version is: 5.4
WooCommerce Version is: 4.0.1
Facebook for WooCommerce version is: 1.10.2

Do you know of any solution so that, for example, the customer can be taken to the product page instead of the checkout page?

![NEW Facebook interface](https://user-images.githubusercontent.com/23706281/79140456-4f882b80-7db8-11ea-95ea-f43d261e8d8c.png)
![OLD Facebook interface](https://user-images.githubusercontent.com/23706281/79140448-4c8d3b00-7db8-11ea-82fe-007c566f674f.png)

Thank you
Happy Monday.

**Comment by lgfogle** [comment]
Hey @carlosmdh,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
