### ISSUE TITLE
Products are synced and visible in inventory but do not appear in shop, I can't create product manually because it's in inventory already, but doesn't show in shop

### ISSUE THREAD

**Issue by simonpskovgaard** [facebookincubator/facebook-for-woocommerce#1239]
Hi
My shop is https://www.facebook.com/youdloveit/
My woocommerce site has 7 products, which have gone to a catalog on facebook. But I don't have the option to connect to shop, so it won't show on my shop, and it doesn't allow me to manually create products either, because the products are already in inventory. Please help.

**Comment by lgfogle** [comment]
Hey @simonpskovgaard,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey
