### ISSUE TITLE
Facebook for woocommerce

### ISSUE THREAD

**Issue by AndyDeschamps** [facebookincubator/facebook-for-woocommerce#1240]
I have a woocommerce shop in wordpress, with more than 500 item. I setup facebook for woocommerce, and from wordpress, all seemed good with all item synced.

On my facebook shop page, nothing shows up.

1. I've resynced, delete facebook for woocommerce data, et setup again, and still nothing.

I was hoping you could guide me?

Thanks

Andy

**Comment by lgfogle** [comment]
Hey @AndyDeschamps,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
