### ISSUE TITLE
Tax not added

### ISSUE THREAD

**Issue by Eproksw** [facebookincubator/facebook-for-woocommerce#1241]
Hi

I have facebook pixel with woocommerce, and with advertising.

Problem: Price with out tax :(
My Woocommerce shop is set to enter prices excluding tax (VAT) on all products. Now all thing in my shop in facebook show to costumer without Vat.

We needs a fix, please.

Thanks

**Comment by lgfogle** [comment]
Hey @Eproksw,

I'm afraid that if the prices entered in WooCommerce do not include tax, the prices will be reflected without tax in Facebook. The prices in Facebook represent the prices entered at the product-level - Facebook does not calculate the taxes on top of the entered price. To sync taxes to Facebook, you must enter taxes inclusive of price in WooCommerce.

If you need further assistance or have other questions about this, could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Lindsey

**Comment by homanp** [comment]
@lgfogle other plugins that handle advertising have options for appending VAT to the products. Are there any plans to support this?
