### ISSUE TITLE
Product not showing on facebook shop

### ISSUE THREAD

**Issue by Kashifkhan75** [facebookincubator/facebook-for-woocommerce#1243]
Hi I have plugged 
in facebook with my woo commerce site. but the product are not showing on facebook shop.  Although the product in woocommerce showing connected to facebook. but my shop ate facebook have no product. My facebook page ishttps://business.facebook.com/LOOJIISHOP/ and my webpage is www.loojii.com
I have attached some pictures for your review. kindly solve the issue . I am just sick of trying it several times.
<img width="1310" alt="Screenshot 2020-04-20 at 11 52 09 PM" src="https://user-images.githubusercontent.com/64038247/79790194-cf883580-8364-11ea-8d7b-5c4f256b97da.png">
<img width="1217" alt="Screenshot 2020-04-20 at 11 53 10 PM" src="https://user-images.githubusercontent.com/64038247/79790214-d7e07080-8364-11ea-8ece-4f21619fa407.png">

**Comment by marcfielding1** [comment]
Hey mate this a stupid documentation bit SO go into plugins in woo, click the facebook plugin, go to manage connection, click Ad Setup on the left, scroll down on the right you'll see a box that says facebook shop, click that to activate the feed in your shop! I fiddled with this for a couple of days before noticing that.

**Comment by lgfogle** [comment]
Hey @Kashifkhan75,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
