### ISSUE TITLE
How do I get my Facebook shop back to normal? Prior to ever using plug-in

### ISSUE THREAD

**Issue by hanjinyo** [facebookincubator/facebook-for-woocommerce#1244]
I realized that by using the facebook-for-woocommerce plug-in I'm not able to organize my products into collections on FB.  I really wanted to have this feature, so I deactivated the plug-in in hopes to restore my FB shop to its original setting capabilities.  However, I'm still not able to edit, add, delete my products in any way from the FB page.  

How do I reverse linking my FB page with my WooCommerce page?  I'd like it to be back to how it was before I ever downloaded the plug-in.  I'd appreciate any help.  Thank you!

**Comment by lgfogle** [comment]
Hey @hanjinyo,

Thanks for reaching out!

I think this would be a good question for the [Facebook support team](https://www.facebook.com/business/help), since once the plugin is removed we don't have any impact over the presentation of the shop. 

Thank you!
Lindsey
