### ISSUE TITLE
Allowing custom product type of 

### ISSUE THREAD

**Issue by ajayghaghretiya-multidots** [facebookincubator/facebook-for-woocommerce#1245]

**Comment by lgfogle** [comment]
Hey @ajayghaghretiya-multidots,

Thanks for reaching out! 

Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) to discuss this request in greater detail? We'd be happy to help!

Cheers,
Lindsey

**Comment by lgfogle** [comment]
Closing for #1246
