### ISSUE TITLE
Allowing custom product type of WooCommerce?

### ISSUE THREAD

**Issue by ajayghaghretiya-multidots** [facebookincubator/facebook-for-woocommerce#1246]
We are using the premium version of this plugin. Curious to know if you are allowing the woocommerce custom product types.

We added new product type and loaded the products into that but that new product type products are not syncing to Facebook.

What do we need to accomplish this task?

Please do let me know is there any way to allow additional product type, Currently, it allowing the simple, variable and other woocommerce default product type.

Thanks

**Comment by lgfogle** [comment]
Hey @ajayghaghretiya-multidots,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
