### ISSUE TITLE
Facebook sync is blocking product updates

### ISSUE THREAD

**Issue by PerunNL** [facebookincubator/facebook-for-woocommerce#1247]
In Woocommerce the Facebook plugin is blocking updates on product which are excluded from sync. It is impossible to update the product after an edit. After removing the exclusion (Exclude categories from sync) the edit of the product can be saved.

**Comment by ronnahmias** [comment]
same issue as well

**Comment by ronnahmias** [comment]
the update doesnt fix this issue

**Comment by lgfogle** [comment]
Hey @PerunNL and @ronnahmias,

My apologies for the delayed response. I believe we resolved this issue in a subsequent release, but could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this issue persists for you? We'd be happy to help!

Cheers,
Lindsey

**Comment by PerunNL** [comment]
Unfortunately the issue reappeared. I have to disable the plug-in to be able to update an product of the excluded category.
