### ISSUE TITLE
Ajax add to cart event not working

### ISSUE THREAD

**Issue by engineerized** [facebookincubator/facebook-for-woocommerce#1248]
Using Woocommerce theme SAVOY with Ajax add to cart function is not working with plugin version 1.10.2. It worked with version 1.9.15.

When switching of Ajax add to cart function the "Add to Cart" event is triggered.

Hope you guys fix this issue on the next update if someone else doesn't have other solution for it how to solve this?

**Comment by lgfogle** [comment]
Hey @engineerized,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this persists? We'd be happy to help!

Cheers,
Lindsey
