### ISSUE TITLE
I have problem with connection

### ISSUE THREAD

**Issue by periklej** [facebookincubator/facebook-for-woocommerce#1249]
Your connection has expired. Please click Manage connection > Advanced Options > Update Token to refresh your connection to Facebook. 
When i click on "Manage connection" it displays an error: "Sorry, this content isn't available right now"
https://www.angelshop.si/
https://www.facebook.com/angelshopmoda/

**Comment by lgfogle** [comment]
Hey @periklej,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this persists? We'd be happy to help!

Cheers,
Lindsey
