### ISSUE TITLE
Partial Sync Problem & Buttons Do Nothing after Install: website slows down - v1.8.0 Followup

### ISSUE THREAD

**Issue by sean3650** [facebookincubator/facebook-for-woocommerce#125]
hi,
i have around 100 products on my woocommerce website but only 7 products are synced. for fist 4days only 1 product was synced and after like 3 days 6 more products were synced.

if i have to re-sync everything how do i do it? for some reason, Force Product Resync and Re-configure Facebook Settings does not seem clickable on my wordpress backend.

is there a way to disconnected everything and start everything all over again?
what is the best solution for this?

Thank you so much

**Comment by dmitridr** [comment]
Hello,

Thanks for writing in, it seems like you have multiple problems, we'll try to help you out.
First off, I recommend upgrading to v1.6.5, then trying the steps below:

- Deactivate all extensions except FB for Woo and Woo. (Temporarily!)
- Try the Force Resync button again, hopefully it works this time. If it doesn't...
- Try the reconfigure buttons again. Does it work? If so, 'Reconfigure' has a way to reset everything under 'Advanced Options'.
- Reactivate all extensions.

If that still doesn't work, could you send us a screenshot or a video of what you are seeing. If the buttons still do not work after upgrading and disabling the other extensions, could you try opening the console (Ctrl + Shift + J) and if there are any errors there sending a screenshot of those?

**Comment by sean3650** [comment]
Hi 

I am using v1.6.5 at the moment.

i found the problem actually. when i update the products the website slows down too much where sometimes it crashes my server.

is there a fix to this as well?

> Try the reconfigure buttons again. Does it work? If so, 'Reconfigure' has a way to reset everything under 'Advanced Options’. - how do i go to advanced options? where do i need to go?

Thank you so much for your reply

best regards

**Comment by dmitridr** [comment]
Hello,

Thanks for your patience. We identified a similar issue in #173 where product sync was taking a very long time, and we sent out a performance fix in the latest version [v1.7.2](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.2) you may see a performance increase when installing this version.

To answer your question about advanced options, you should click the button 'Reconfigure Facebook Settings', which will launch a popup. In the popup on the left hand column there should be an 'Advanced Options' line, if you click that, you will see an option to delete your settings. <- These are the steps for how to disconnect everything and set up again from the start.

Hope that helps.

**Comment by chillpilllike** [comment]
needs to improve syn of products with big variations. the sync is painfully slow for products with large variations

**Comment by dmitridr** [comment]
Thanks for your feedback. We are definitely thinking of an overhaul focusing on performance.

**Comment by truchosky** [comment]
do you use nginx or apache?,

**Comment by chillpilllike** [comment]
Nginx with Php-fpm

Sent from my iPhone

On 06-Jan-2018, at 6:14 AM, truchosky <notifications@github.com<mailto:notifications@github.com>> wrote:


do you use nginx or apache?,

**Comment by truchosky** [comment]
I have the same configuration and the same problem, did you try apache ?

I am having another [problem ](https://github.com/facebookincubator/facebook-for-woocommerce/issues/199)too with this configuration (nginx + php7-fpm), do you have that problem too ?

**Comment by chillpilllike** [comment]
I tried apache too but same issue there too. Not sure what other issue you are facing there as i only have issue of products sync.

On 06-Jan-2018, at 12:12 PM, truchosky <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the same configuration and the same problem, did you try apache ?

I am having another problem <https://github.com/facebookincubator/facebook-for-woocommerce/issues/199> too with this configuration (nginx + php7-fpm), do you have that problem too ?

**Comment by dmitridr** [comment]
Thanks for your patience, all. We're working on a product sync overhaul with performance in mind, it's our top priority right now.

**Comment by vernardo** [comment]
hi guys. Any news on the performance upgrade?

**Comment by dmitridr** [comment]
@vernardo yes, in fact. Just yesterday @mengyingdu released `v1.8.0` which is available as a beta release [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases), would love it if you or some of the others in this thread could try it out and see if it works for you! 

This new version uploads all the products through just 1 API call to FB using a feed (The older version did multiple API calls per product).

**Comment by mengyingdu** [comment]
Hi @vernardo ,

Did you try v1.8.0 or v1.8.1? We officially released v1.8.1 on WooCommerce.

**Comment by dmitridr** [comment]
As Mengying said, definitely encourage you all to try v1.8.1 as it improves the speed of product sync by up to **60x**. Closing this out, if there's an issue with the new way product sync works, please open a new issue!
