### ISSUE TITLE
Plugin not working normally anymore

### ISSUE THREAD

**Issue by Marameyeh** [facebookincubator/facebook-for-woocommerce#1250]
Hello,
I have several issues with the plugin:
1- Product sync doesn't work anymore: 
**There was an error trying to sync the products to Facebook. We couldn't create the feed or upload the product information.**
2- Catalogue has many rejected products with errors suddenly. although the products haven't been changed
3- It says Last successful update: Sun Mar 29, 2020 2:11pm which means the product sync hasn't happened in a month
Appreciate your help

**Comment by Marameyeh** [comment]
There seem to be more problems with the plugin
1- On Facebook, I can't delete or edit rejected products
2-The products are rejected for a very weird reason, the products on the website are identical in structure to the approved products, but the rejected ones are missing the title, sale price, etc ( even though all the data is there on the product itself) and instead of the product title, the plugin is pulling the SEO title:
<img width="785" alt="Screen Shot 2020-04-24 at 3 53 52 AM" src="https://user-images.githubusercontent.com/64233521/80161104-5d238980-85e0-11ea-94b3-5d639edb6b08.png">

**This item can't be used for Page Shop because it has missing or incorrectly formatted data for name, image, description, price, website link, availability and item condition. Re-upload this item to your catalogue with all required data.**

**Comment by Marameyeh** [comment]
<img width="906" alt="Screen Shot 2020-04-24 at 4 02 42 AM" src="https://user-images.githubusercontent.com/64233521/80161144-775d6780-85e0-11ea-91a7-422ffefc5f1c.png">
<img width="402" alt="Screen Shot 2020-04-24 at 4 03 03 AM" src="https://user-images.githubusercontent.com/64233521/80161159-83492980-85e0-11ea-8bb1-73f161de2eb3.png">

**Comment by lgfogle** [comment]
Hey @Marameyeh,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this persists? We'd be happy to help!

Cheers,
Lindsey
