### ISSUE TITLE
shop page not working

### ISSUE THREAD

**Issue by dipkastel** [facebookincubator/facebook-for-woocommerce#1251]
hi guys 
i have an error on my new page after create it
shop page has an 500 internal server error :

Sorry, something went wrong.
We're working on getting this fixed as soon as we can.
Go Back 

in inspector : Failed to load resource: the server responded with a status of 500 ()

address is :
https://www.facebook.com/Kalamis-106730364354205/shop/

can you help me to resolve it?

**Comment by lgfogle** [comment]
Hey @dipkastel,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this persists? We'd be happy to help!

Cheers,
Lindsey
