### ISSUE TITLE
Pre-existing pixel not allowed to be used

### ISSUE THREAD

**Issue by detra** [facebookincubator/facebook-for-woocommerce#1252]
Have a pre-existing fb pixel, why do I have to create another one after using the offical
facebook-for-wordpress plugin?

Can I re-initialise it to use the pre-existing one

**Comment by lgfogle** [comment]
Hey @detra,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
