### ISSUE TITLE
Currency on FB feed is wrong (USD instead of EUR, which is the set currency for the store)

### ISSUE THREAD

**Issue by Jany-M** [facebookincubator/facebook-for-woocommerce#1255]
All products' currencies in the feed have been changed to USD.
USD isn't used anywhere in the site.
Currency is EUR.

**Comment by Jany-M** [comment]
When forcing re-sync through the Manage Connection option in the Facebook popup, the issue gets solved, but we can't keep doing this every day manually.

There's a bug in the way the plugin syncs on its own, it keeps getting the wrong currency.

**Comment by Jany-M** [comment]
@wvega this is still a major issue!
When forcing sync the currency is correct (€) but when we leave the plugin sync on its own, it keeps reverting to $.
This is damaging our campaigns and needs to be addressed asap!

**Comment by lgfogle** [comment]
Hey @Jany-M,

This sounds like an issue that our support team would be best suited to help troubleshoot. Could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Lindsey

**Comment by Jany-M** [comment]
@lgfogle so are we supposed to use Github or just the Forum for issues?

**Comment by lgfogle** [comment]
@Jany-M In this case, since this isn't something we've been able to replicate,  I think we'll need to do some in-depth troubleshooting into your WordPress environment to identify the cause of this issue. I wanted our support team to take a look on the forums since they are well-versed in investigating these types of issues.
