### ISSUE TITLE
Plugin ignores WPML language to sync to FB catalog

### ISSUE THREAD

**Issue by Jany-M** [facebookincubator/facebook-for-woocommerce#1256]
We have 2 langs, only one lang must be synced to FB products.
It used to work fine, not anymore.
Now only main language is synced to FB and the WPML setting is completely ignored.

**Comment by wvega** [comment]
@Jany-M thank you for reporting this problem. I'm sorry that the WPML integration is no longer working as expected.

We introduced a bug in version 1.11.0 that caused the setting to be ignored. To fix this, we released a new version today with a fix that should allow the plugin and WPML to work together again.

May I ask you to try Facebook for WooCommerce 1.11.1 and let us know if it successfully fixes the problem on your site?

**Comment by Jany-M** [comment]
@wvega don't see any update for the plugin (it's still on 1.11.0 on WP and Github too).

**Comment by wvega** [comment]
@Jany-M I'm sorry for that. You should be able to see version 1.11.1 now. I made a mistake updating the stable tag for the plugin, so even though I uploaded the changes yesterday, the new version was not available for download until a moment ago.

Would you please check again?

Thank you for letting me know.

**Comment by Jany-M** [comment]
It seems to work, thank you.

I can see the option again now, in WPML -> Languages.
However I don't see a Force Re-Sync button anymore in Woo `/wp-admin/admin.php?page=wc-settings&tab=integration&section=facebookcommerce`.
The only way to force re-sync, currently, is by opening the popup, through Manage Connections.

Please DO add, in Products Bulk Edit mode, the option to disable FB sync. They were all set back to sync... and there's 100s of them... the only way to hide them now is one by one, by hand.

And please check out the [wrong currency issue](https://github.com/facebookincubator/facebook-for-woocommerce/issues/1255) too. Hundreds of stores need this plugin to work like it used to and fast, considering the current world situation.

Thank you.

**Comment by wvega** [comment]
Hey @Jany-M,

Thank you for confirming the update is working for you. I appreciate it.

>However I don't see a Force Re-Sync button anymore in Woo /wp-admin/admin.php?page=wc-settings&tab=integration&section=facebookcommerce.
The only way to force re-sync, currently, is by opening the popup, through Manage Connections.
Also, the option to force re-sync at x time every day (or not), is gone.

Unfortunately we [temporarily removed some features](https://docs.woocommerce.com/document/facebook-for-woocommerce/#faq-security) to avoid a security vulnerability with the Facebook connection. We plan to bring all those back within a few weeks once we create a more secure connection.

As a result, right we can't update products immediately after you make changes. However, the latest version of the plugin will regenerate the feed file every 15 minutes and Facebook is going to check that file every hour. You should expect any modifications to be synced to Facebook in the following 15-60 minutes.

>Please DO add, in Products Bulk Edit mode, the option to disable FB sync. They were all set back to sync... and there's 100s of them... the only way to hide them now is one by one, by hand.

I believe you can use the **Exclude from Facebook sync** bulk action. Would you please give that one a try and let me know if helps you update the products more quickly?

<img width="862" alt="Screen Shot 2020-04-28 at 5 11 40 PM" src="https://user-images.githubusercontent.com/45068/80542814-56e03500-8973-11ea-9132-9a6696fdaeac.png">

>And please check out the wrong currency issue too. Hundreds of stores need this plugin to work like it used to and fast, considering the current world situation.

Thank you for reporting that problem as well. You're right. We also understand the impact this plugin has, specially right now, and we will continue checking these reports and adding a solution as soon as possible.

Thank you so much for your patience as we look into this!

Please let me know the bulk action works for you as an alternative to disable FB sync.

**Comment by Jany-M** [comment]
> we can't update products immediately after you make changes. However, the latest version of the plugin will regenerate the feed file every 15 minutes and Facebook is going to check that file every hour. You should expect any modifications to be synced to Facebook in the following 15-60 minutes.

Hopefully a fix will be implemented soon, I'm sure you are working hard on it... but please always keep in mind that many have customized sites and if devs can't have immediate feedback it can be quite dramatic for some clients (eg. especially if they are tagged on IG and/or there's an active campaign going on).

Maybe add a debugging section, where we can at least see how products would be parsed - so we know we haven't made some huge mistake in our code - even if it doesn't sync straight away?
That would help a lot, regardless!

> I believe you can use the Exclude from Facebook sync bulk action. Would you please give that one a try and let me know if helps you update the products more quickly?

Perfect! Just now where I would expect to find it, but does the job!

Thank you for your support, it's very much appreciated!
