### ISSUE TITLE
the latest version (1.11.0) cancels functions in order tabs

### ISSUE THREAD

**Issue by cbacigalupoAR** [facebookincubator/facebook-for-woocommerce#1257]
Hi, this is the first time I've reported something, so I apologize if I don't meet the requirements.

In my online store I use a set of plugins necessary to send collections and invoices that are specifically designed for my country (Argentina), previously I had to suspend a payment platform todopago.com.ar since its plugin became unstable in conjunction with the one on facebook for woocomerce. In this last update, this plugin started to work properly, but two more important ones stopped working, such as electronic invoicing against AFIP, which is the regulatory entity in my country and sent through OCA, which is one of the most important emails in my country.

Specifically, the failure is that it cancels functions in tabs within orders, I attach video of the failure and in turn code of the failure.

Video problem  https://youtu.be/XTXmoORN_Wo

![WhatsApp Image 2020-04-27 at 3 20 06 PM](https://user-images.githubusercontent.com/64477075/80489683-963c6080-8936-11ea-9253-ea9a581e459e.jpeg)

**Comment by lgfogle** [comment]
Hey @cbacigalupoAR,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this persists? We'd be happy to help!

Cheers,
Lindsey

**Comment by cbacigalupoAR** [comment]
> Hey @cbacigalupoAR,
> 
> Thanks for reaching out!
> 
> Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this persists? We'd be happy to help!
> 
> Cheers,
> Lindsey

Hello how are you, I tell you we have updated to the latest version Version 1.11.4, in which the problem persists, I attach the error in the code that occurs

`JQMIGRATE: Migrate is installed, version 1.4.1
post.php?post=17147&action=edit:1 A cookie associated with a cross-site resource at http://wp.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
afip-admin.js?ver=0.0.1:2 afip loaded
post.php?post=17147&action=edit:3933 Uncaught ReferenceError: fbq is not defined
    at HTMLDocument.<anonymous> (post.php?post=17147&action=edit:3933)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
    at HTMLDocument.J (jquery.js:2)
post.php?post=17147&action=edit:1 [DOM] Found 2 elements with non-unique id #_ajax_nonce: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"49076eee50">​ <input type=​"hidden" id=​"_ajax_nonce" name=​"_ajax_nonce" value=​"49076eee50">​
The resource https://www.mundogeek.com.ar/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/style.css?ver=1.3.0 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.mundogeek.com.ar/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.min.js?ver=1.3.0 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.mundogeek.com.ar/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/style.css?ver=1.3.0 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.mundogeek.com.ar/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.min.js?ver=1.3.0 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
wp-auth-check.min.js:2 Uncaught TypeError: Cannot read property 'hasClass' of undefined
    at HTMLDocument.<anonymous> (wp-auth-check.min.js:2)
    at HTMLDocument.dispatch (jquery.js:3)
    at HTMLDocument.r.handle (jquery.js:3)
    at Object.trigger (jquery.js:3)
    at Object.a.event.trigger (jquery-migrate.min.js:2)
    at HTMLDocument.<anonymous> (jquery.js:3)
    at Function.each (jquery.js:2)
    at a.fn.init.each (jquery.js:2)
    at a.fn.init.trigger (jquery.js:3)
    at Object.<anonymous> (heartbeat.min.js:2)
(anonymous) @ wp-auth-check.min.js:2
dispatch @ jquery.js:3
r.handle @ jquery.js:3
trigger @ jquery.js:3
a.event.trigger @ jquery-migrate.min.js:2
(anonymous) @ jquery.js:3
each @ jquery.js:2
each @ jquery.js:2
trigger @ jquery.js:3
(anonymous) @ heartbeat.min.js:2
i @ jquery.js:2
fireWith @ jquery.js:2
x @ jquery.js:4
c @ jquery.js:4
XMLHttpRequest.send (async)
send @ jquery.js:4
ajax @ jquery.js:4
l @ heartbeat.min.js:2
d @ heartbeat.min.js:2
v @ heartbeat.min.js:2
h @ heartbeat.min.js:2
(anonymous) @ heartbeat.min.js:2
dispatch @ jquery.js:3
r.handle @ jquery.js:3`
