### ISSUE TITLE
Latest version Failed

### ISSUE THREAD

**Issue by snowloversglobal** [facebookincubator/facebook-for-woocommerce#1258]
When updating the latest version it says "Update Failed: Update package not available."

**Comment by lgfogle** [comment]
Hey @snowloversglobal,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this issue persists? We'd be happy to help!

Cheers,
Lindsey
