### ISSUE TITLE
Facebook for WooCommerce update 1.11.1 is getting an error

### ISSUE THREAD

**Issue by LittleWingConnections** [facebookincubator/facebook-for-woocommerce#1259]
I am getting this error when I try to do the update. My products are also not syncing to Facebook

**Comment by GlennMartin1** [comment]
I get this error when trying to update to 1.11.1:

**An error occurred while updating Facebook for WooCommerce: Update package not available.**

**Comment by LittleWingConnections** [comment]
I got the same error. Does anyone know the fix? My products are not syncing from my website to Facebook and Instagram.

**Comment by GlennMartin1** [comment]
Ok - I figured it out. You need to "buy" (for free) this plugin to get this plugin in your WooCommerce account. See https://woocommerce.com/products/facebook/

After that, in your site go to WooCommerce > Extensions > Subscriptions.

Make sure your WooCommerce store is connected to WooCommerce.com. 

To be sure the list of extensions is synced, click Update.

After it updates, find Facebook for WooCommerce in the list, and make sure is Activated.

Then this plugin will update after that.

Summary:
- it's got to be in your WooCommerce account. 
- you've got to have your site linked to WooCommerce.com. 
- the extension has to be activated.

**Comment by lgfogle** [comment]
Hey @LittleWingConnections and @GlennMartin1,

My apologies for the delay in my response! Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this issue persists? We'd be happy to help!

Cheers,
Lindsey
