### ISSUE TITLE
Facebook for Woocommerce not reconnecting

### ISSUE THREAD

**Issue by cperry60** [facebookincubator/facebook-for-woocommerce#1261]
I'm getting a message at the top in my WordPress dashboard to reconnect but when I click on reconnect nothing happens.
![FB-for-Woo](https://user-images.githubusercontent.com/50596450/80822570-fcc8b500-8ba8-11ea-8cfa-d8a010a96436.jpg)

**Comment by colinrobinson** [comment]
Hi,

I'm seeing the exact same behaviour.

|     |  Version    |
| ---- | ---- |
|   WordPress version   |   5.4.1   |
|   WooCommerce version   |   4.0.1   |
|   PHP version   |   7.2.24   |
|   Facebook for WooCommerce   |   1.11.2   |

Message in WordPress

> Heads up! Facebook for WooCommerce is migrating to a more secure connection experience. Please click here and go to Manage Connection > Advanced Options > Reconnect Catalogue to securely reconnect. Learn more.

Then following the directions, clicking on the "Manage connection" button and then "Reconnect Catalog" ends with the above screen.

Although nothing is surfaced to the user, the XHR to https://www.facebook.com/ads/dia/setup/ results in the message

> Sorry, something went wrong.
We're working on getting this fixed as soon as we can.

Please let me know if there is any further information I can supply

**Comment by lgfogle** [comment]
Hey @cperry60 and @colinrobinson,

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this issue persists? We'd be happy to help!

Cheers,
Lindsey
