### ISSUE TITLE
Add to cart ajax filter event not working

### ISSUE THREAD

**Issue by engineerized** [facebookincubator/facebook-for-woocommerce#1263]
Add to cart ajax filter event not working. Using latest plugin version 1.11.1

We are using ajax for add to cart.

Our add to cart button html looks like this:
`<button type="submit" name="add-to-cart" value="123" class="nm-simple-add-to-cart-button single_add_to_cart_button button alt">Add to bag</button>`

Hope you guys fix this issue on the next update if someone else doesn't have any other solution for it how to solve this?

**Comment by engineerized** [comment]
When switching off ajax add to cart it is working but now with ajax enabled.

It was working on plugin version 1.9.15

**Comment by lgfogle** [comment]
Hey @engineerized,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this issue persists? We'd be happy to help!

Cheers,
Lindsey
