### ISSUE TITLE
After update new products doesn't sync to facebook catalog

### ISSUE THREAD

**Issue by ronnahmias** [facebookincubator/facebook-for-woocommerce#1264]
I have problem that when I add new product in wordpress the sync don't do to facebook.

Even if I hit sync now the products not sync.

Can someone can help me please?

**Comment by lgfogle** [comment]
Hey @ronnahmias,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this issue persists? We'd be happy to help!

Cheers,
Lindsey
