### ISSUE TITLE
trying to integrate facebook with woocommerce

### ISSUE THREAD

**Issue by Petrathorn** [facebookincubator/facebook-for-woocommerce#1265]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

##🚶‍♀️ Steps to reproduce

1. The first step
1. The next step…

**Comment by Petrathorn** [comment]
I keep getting the message "sorry, this content is not available right now" when i try to integrate. What am I doing wrongP
<img width="1120" alt="Bildschirmfoto 2020-05-02 um 16 26 32" src="https://user-images.githubusercontent.com/64695473/80867136-bd769300-8c92-11ea-9011-1f1fd38e8647.png">

**Comment by engineerized** [comment]
Did you try to switch browser from Safari to Chrome?

**Comment by lgfogle** [comment]
Hey @Petrathorn,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this issue persists? We'd be happy to help!

Cheers,
Lindsey
