### ISSUE TITLE
Facebook Chat Icon not showing up on Site

### ISSUE THREAD

**Issue by CameronBennett** [facebookincubator/facebook-for-woocommerce#1266]
Facebook chat icon not showing up in site. https://georgiawillow.com.

Integration is fully synced and working as products are syncing to facebook, but the icon wont appear. It has been enabled and customized. I reached out to our theme provider for support, but since it is not an "officially support" plug-in, they will not provide support on the issue.
![activation1](https://user-images.githubusercontent.com/16341553/80933848-5db3e100-8d93-11ea-8964-8a399f61afac.PNG)
![activation2](https://user-images.githubusercontent.com/16341553/80933861-6b696680-8d93-11ea-95f7-ba1a0fb7a700.PNG)

Both areas show that the extension is active, but will not appear on shop or homepage. If i need to get logs i can enable logging to see what exactly is going on.

**Comment by lgfogle** [comment]
Hey @CameronBennett,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this issue persists? We'd be happy to help!

Cheers,
Lindsey
