### ISSUE TITLE
Currency in Facebook catalog is wrong

### ISSUE THREAD

**Issue by scoobynko** [facebookincubator/facebook-for-woocommerce#1267]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Hi, I'm using you new plugin for synch my products to Facebook catalog. There is a problem with currency - my currency is by default CZK (Czech Crown) but in catalog its showing in EUR:
![image](https://user-images.githubusercontent.com/40393245/81048474-b501a080-8ebc-11ea-9a9f-f3d3030e6400.png)

I'm using Currency Switcher for Woocomerce but only for one country and it's making no difference when I disabled this plugin. Still EUR in catalog (and in feed and basically everywhere).

Could you please help me? I will provide you any information you need.

##🚶‍♀️ Steps to reproduce

I don't have any I'm affraid.

## ✔️ Expected behavior

Should show only default CZK currency.

**Comment by lgfogle** [comment]
Hey @scoobynko,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this issue persists? We'd be happy to help!

Cheers,
Lindsey
