### ISSUE TITLE
Sale prices not reflecting on Facebook shop.

### ISSUE THREAD

**Issue by sharrday** [facebookincubator/facebook-for-woocommerce#1269]
I have checked and not been able to find a solution anywhere.

I have deleted and reinstalled but still have same issue. When I'm on sale on the website,Facebook still shows the full price and nothing to do with the sale until they click to the website itself. 

Please help

**Comment by lgfogle** [comment]
Hey @sharrday,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if this issue persists? We'd be happy to help!

Cheers,
Lindsey
