### ISSUE TITLE
Fatal error:  Maximum execution time of 120 seconds exceeded wc_facebook_regenerate_feed

### ISSUE THREAD

**Issue by maxisosa** [facebookincubator/facebook-for-woocommerce#1270]
## 🔎 Isolate the bug

- [x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

05-06-2020 @ 11:21:11 - Request
Request
uri: https://graph.facebook.com/v2.9/407706085944848/?fields=name
headers: Array
(
    [Authorization] => ******************************************************************************************************************************************************************************************
)
timeout: 500

**Comment by lgfogle** [comment]
Hey @maxisosa,

My apologies for the delayed response! Could you please try updating to the latest Facebook for WooCommerce version and let me know if you're still experiencing this issue?

Thank you,
Lindsey

**Comment by lgfogle** [comment]
@maxisosa I'm going to close this issue, but please don't hesitate to reach out if you're still encountering this problem!

**Comment by altunakif** [comment]
Although I have max_execution_time = 30000 in my php.ini file, I also get this error. How can I solve this problem
