### ISSUE TITLE
Problem with seeing correct amount of purchases in facebook manager

### ISSUE THREAD

**Issue by Adriana428** [facebookincubator/facebook-for-woocommerce#1271]
Hi guys, 
recently i've had few purchases and tried to build up my data in facebook however the facebook pixel is not showing the correct data whenever im creating a lookalike audience. It only shows the right data when i enter the pixel myself and see the correct events (please see picture with both screenshots attached). Any ideas how to fix this? P.S. -they all were unique customers
<img width="904" alt="problem1" src="https://user-images.githubusercontent.com/64923904/81216015-1ff0cb80-8fd2-11ea-96ce-dc863ce6ecb2.png">

**Comment by lgfogle** [comment]
Hey @Adriana428, 

This sounds like an issue that our support team would be best suited to help troubleshoot. Could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Lindsey
