### ISSUE TITLE
Products not synchronizing with facebook page

### ISSUE THREAD

**Issue by miguelgisbert** [facebookincubator/facebook-for-woocommerce#1276]
Hello, 
After installing and activating the plugin I have tried to sync products automatically and manually but I have no one synchronized and shown on my facebook page. Could you please help me with that? Find here the information needed: 

WooCommerce version: 4.1.0
WordPress version: 5.4.1
Plugin version (please note: we only support up-to-date versions of the plugin): 1.11.2
A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.) No needed, it's already explained and you can see it at the URLs.
The URL of your website: www.miguelgisbert.com
The URL of your page: https://www.facebook.com/miguelgisbert-106987494160935/
The URL(s) of where you took your screenshot(s)
(If applicable) Detailed steps you took in order to see the problem

Thank you very much, 
Miguel Gisbert

**Comment by BlueSpiritbox** [comment]
@miguelgisbert  are you using SG Optimizer by any chance? I had the same problem and it looks like SG Optimizer's HTML Minification was preventing the product synchronization. The synchronization worked after I added this function. 

```
add_filter( 'sgo_html_minify_exclude_params', 'html_minify_exclude_params' );
function html_minify_exclude_params( $exclude_params ) {
    // Add the query params that you want to exclude.
    $exclude_params[] = 'wc-api';
    return $exclude_params;
}
```
 You can force FB to resync by going to your Catalog Manager > Product Data Sources.

Source: https://wordpress.org/support/topic/facebook-product-feed-fails/

**Comment by miguelgisbert** [comment]
Hi! thank you very much for the answer. I don't think I'm using SG optimizer and I have already force FB to resync. The products are on the catalogue but not on the FB shop. There's a red point on the products saying: 

> Missing or Incorrect Data
> This error may still be visible up to 30 minutes after re-uploading your inventory
> El producto no es visible: visibility
> El producto debe ser visible para que Facebook pueda mostrarlo a los usuarios

But all the products are marked as visible on wordpress and with a SKU.

What else could be the problem? 

Thank you very much, 
Miguel Gisbert

**Comment by VectorLC** [comment]
I am also getting the "Missing or Incorrect Data" error for Instagram Shopping: http://prntscr.com/skjkv6

I spent a good hour with facebook support chat and they ruled it to being a woocommerce issue.

My site is using composite product plugin to combine two sku's together and then I have a sku for  that group. I have 177 active products.

I put in a support ticket with woo but they take forever to respond.

I set up all this so I good get my clients products to be sold through the instagram shop. The product catalog shows up on the instagram account but they are greyed out and I can not tag a product to a post. Instagram gives me a notice that I need to "Set it to Activate Delivery"

My plugins:
Facebook for woocommerce: Version 1.11.1
Woocommerce: Version 3.9.2

Any help or suggestions would be appreciated

**Comment by lgfogle** [comment]
Hey @miguelgisbert and @VectorLC,

Thanks for reaching out! 

Based on the description here, these look like issues our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still experiencing this problem? We'd be happy to help!

Cheers,
Lindsey
