### ISSUE TITLE
Wrong Facebook account : How to Remove the existing settings data (page, etc.) from the DB?

### ISSUE THREAD

**Issue by HaardengMarketing** [facebookincubator/facebook-for-woocommerce#128]
Hi,

I would like to use Facebook for Woocommerce for a Facebook Store. I have an old installation that is linked to a wrong Facebook account. How do I change this, when I do not have access to the account associated with the installation? I have tried to delete the plugin and install again, but it did not help.

Hope you can help.

**Comment by dmitridr** [comment]
Hello,

Thanks for writing in. I think we have a resolution for you, though it's a bit hacky. 
You basically need to wipe the info from the current installation from the Wordpress DB, this can be done manually by accessing the DB, but we have luckily built a JS function that you should be able to call from the JS console to do it. Here are the steps:

1. Navigate to the Facebook for WooCommerce settings page.
2. Open the Javascript console (Typically Shift + Ctrl + J on Chrome)
3. Type this command `delete_all_settings();` and hit Enter.

If you have the most recent version, this should reset all the info from the DB and you can set up again using whatever account you like. Let us know if that works.

**Comment by HaardengMarketing** [comment]
Hi Dmitri,

 

Thank you very much! It worked perfectly

 

 

 

Mvh.

 

Mathias Larsen

Telefon: 26700377

 

 

Arnold Nielsens Boulevard 72

2650 Hvidovre

www.online-marketing.dk

 

Fra: Dmitri Dranishnikov <notifications@github.com>
Svar til: facebookincubator/facebook-for-woocommerce <reply@reply.github.com>
Dato: fredag den 3. november 2017 kl. 00.20
Til: facebookincubator/facebook-for-woocommerce <facebook-for-woocommerce@noreply.github.com>
Cc: HaardengMarketing <mathias@haardeng-marketing.dk>, Author <author@noreply.github.com>
Emne: Re: [facebookincubator/facebook-for-woocommerce] Wrong Facebook account (#128)

 

delete_all_settings();

**Comment by ashraffarag** [comment]
Is there a script for deleting only Facebook Pixel assignment ?
