### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by troygolden** [facebookincubator/facebook-for-woocommerce#129]
I can not get the extension to work. I've tried on several installations and configurations. Nothing works. I can not get to the process where I see the "getting started" button. I get the error message "You must be logged in as an Administrator of a Facebook page to use Facebook for WooCommerce." I am currently logged in to my woocommerce back-end and a Facebook Page that I administer.   There was a previous install of the plug-in that worked fine.  We are looking to install it a second time.  Please advise.

Thanks in advance.

Troy

**Comment by dmitridr** [comment]
Hi Troy,

Could you please upgrade to the latest version v1.6.5, if you have not already? We had a similar problem in older versions that occurred if you reset your FB password (bizzare, I know).

If the problem persists after upgrading, could you also share with us a screenshot of what you are seeing and where you are seeing it?

**Comment by troygolden** [comment]
Ok. Will give it a try.  Thanks!

**Comment by tahoff** [comment]
@troygolden, are you still experiencing this issue?

**Comment by troygolden** [comment]
oh. im sorry. we decided to manually upload the feed.   We did not try the
fix.

**Comment by dmitridr** [comment]
Closing the issue. Feel free to re-open if you try the fix and are still having the problem.
