### ISSUE TITLE
Facebook doesn't show images from catalog

### ISSUE THREAD

**Issue by Hatredkeys** [facebookincubator/facebook-for-woocommerce#1297]
Hey there,

Today I have installed this plugin. And it all went perfect but it doesn't show the images on the Facebook page of my products.

It does show the images in the catalog manager and on my website.

My website: www.omegawear.nl
Facebook: https://www.facebook.com/omegawearnl/
I also use the most recent plugin version.
And some people said in this forum to use Yoast SEO but I'm already using it.
I can't see if the link to the images are correct since well they don't show them.

Thank you in advance.

Cheers,
Dennis

**Comment by tim1mw** [comment]
I have this exact same problem, currently running on a freshly installed Wordpress with all plugins up to date and no other content to speak of. Right now this is just a test set up for evaluation, however not having the FaceBook integration working properly is a show-stopper for using WooCommerce, so it would be great to see a resolution for this.

Shop display with images missing:

![shop-display](https://user-images.githubusercontent.com/11174402/82148536-8b496180-984c-11ea-86af-aa026ae2231e.png)

Catalog display proving the images exist:

![manage-products](https://user-images.githubusercontent.com/11174402/82148537-8dabbb80-984c-11ea-853a-438f0583b9c8.png)

**Comment by tim1mw** [comment]
Every single product image on the Facebook shop is linking to the same single pixel gif file. Odd.

**Comment by tim1mw** [comment]
One work-around is to edit the product in the FaceBook catalogue manager and re-upload the image there. That seems to fix it and the sync didn't wipe out the fix. Very laborious if you have a lot of images though.

**Comment by Hatredkeys** [comment]
Hey Tim,

Seems that it's working for me now. Just went to bed and the next day they were showing.
maybe it's a caching thing?

**Comment by tim1mw** [comment]
Hopefully the same will happen for me! It's not browser side caching (I just tried clearing mine), must be something internal to FaceBook.

**Comment by tim1mw** [comment]
Well my product images are now showing up as well. There seems to be a time delay between the product being synced and the image associated with it being fetched. Not managed to establish what that delay is yet though.

**Comment by lgfogle** [comment]
Hey @Hatredkeys and @tim1mw,

Thanks for reaching out! My apologies for the delay in my response.

I believe this issue may be due to the delay on Facebook's end between posting the images for new products, while they are reviewed to ensure they are appropriate and don't violate their policies. However, if you notice a similar issue going forward, could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)? We'd be happy to help!

Cheers,
Lindsey
