### ISSUE TITLE
Connection Failed Error Message

### ISSUE THREAD

**Issue by Slvxna** [facebookincubator/facebook-for-woocommerce#1299]
## 🔎 Isolate the bug

I am having trouble with syncing my Woo commerce products to Facebook. I had previously installed the plugin and synced the products, later I edited them and that did not sync. I managed to delete the whole catalog via "Manage Connections". When I try to sync the products again, I am not able to do so because the popup page appears blank. I managed to access the link using Incognito and head to Advanced Options and Remove/Delete. The Manage Connections Page provides me with "Connection Failed". I am not able to Access anything through that menu. I am also not able to use Instagram Shopping as well because my account was not accepted because I had no products or catalogs synced. I would like to completely delete the Facebook for WooCommerce plugin and start over. I have contacted Facebook regarding this issue and they were no help, because I am outside the US. I don't see why that could be a problem. 

Site: https://ghcases.com/
WordPress version: Version 5.4.1
WooCommerce version: Version 4.1.0
Facebook for WooCommerce version: Version 1.11.2

**Comment by lgfogle** [comment]
Hey there,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey
