### ISSUE TITLE
Plugin doesn't work on WC 2.5.5 / Store crashes

### ISSUE THREAD

**Issue by pvlvsk** [facebookincubator/facebook-for-woocommerce#13]
Hello,

when I try to activate your plugin, my complete store crashes and I have to delete the plugin from the plugins directory to be able access wp-admin again. 

Here is the error:

```
ErrorException: Class 'WP_REST_Controller' not found
#1 wp-content/plugins/facebook-for-woocommerce/includes/fbcustomapi.php(15): handleFatalError
#0 [Anonymous function](0): null
```

I'm using WooCommerce 2.5.5

Thank you!

**Comment by dmitridr** [comment]
Hello, 

As stated in our README file we only officially support WooCommerce 3.0.0 and above, and the plugin itself will only work on WooCommerce 2.7.0 or higher, albeit with some limited functionality. Below that the plugin will not work at all.

If you wish to use our plugin, please consider upgrading WooCommerce.
