### ISSUE TITLE
Accounts keep unlinking

### ISSUE THREAD

**Issue by shelleyphant** [facebookincubator/facebook-for-woocommerce#130]
Hi,

The plugin keeps repeatedly asking me to complete my configuration. After following all the steps and syncing my products, the next time I log in it again asks me to complete my configuration and the syncing options are removed until I follow the steps again. Any help is appreciated.

Thanks

**Comment by dmitridr** [comment]
Hello,

Please upgrade to the latest version v1.6.5, which is available either in the official WooCommerce site or on our releases page. This was a problem that we fixed in v1.6.1. ( See #43 )

**Comment by carcarefreaks** [comment]
Is there any way to reconnect without doing a resetup/resync? Doing so will remove all product links on facebook.

**Comment by dmitridr** [comment]
Unfortunately not, because the API key is gone from your woo DB, and we don't store that on our side for security reasons, you'll need to resync in order to regenerate that. Once the solution mentioned in #96 is implemented, it may become possible to reconnect without doing a resetup, but that won't be for some time.

**Comment by shelleyphant** [comment]
I've upgraded and it's all working again. Why doesn't this plugin auto-update? I had no way of knowing there was a serious issue until I stumbled on it by accident.

**Comment by dmitridr** [comment]
Glad you got it working. We're not sure how to enable that for our plugin, if you have any suggestions on how best to do that we're all ears, if not we'll look into that in the future!
