### ISSUE TITLE
many of my products are flagged like they are about weapons or esplicit sexual things, but in fact they're simple belts or neckpieces. I tried to appeal but everytime it says there is an error and to try again later.. anyone has the same issues? 

### ISSUE THREAD

**Issue by mirirart** [facebookincubator/facebook-for-woocommerce#1300]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

##🚶‍♀️ Steps to reproduce

1. The first step
1. The next step…

**Comment by lgfogle** [comment]
Hey @mirirart,

Thanks for reaching out! My apologies for the delay in my response.

While we don't have direct control over which products Facebook accepts or rejects, we'd be happy to help if this issue persists. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey
