### ISSUE TITLE
Products sync but images not showing

### ISSUE THREAD

**Issue by shadowsand** [facebookincubator/facebook-for-woocommerce#131]
The images on the facebook store is not showing up despite a force resync on my wordpress store. Only the description and titles are correctly sync. However, no images were push to my facebook page shop. I am on facebook for woocommerce v1.6.5 and woocommerce v3.1.2

<img width="1118" alt="screen shot 2017-11-02 at 6 40 25 am" src="https://user-images.githubusercontent.com/33298458/32301525-3960fed4-bf99-11e7-9d6d-a7205326d398.png">

**Comment by dmitridr** [comment]
Hello,

Thank you for reporting this and telling us your version. I checked some sample products, it seems the image urls we upload to FB are linking to a 404 page.

Here's a sample image url I pulled:
https://www.trendtycoon.com/wp-content/uploads/2017/10/magic-toy-crane.png

Could you tell us the correct image URL that this should be?
Also, do you have an extension that you are using that affects the image url behavior for where these images are being stored? 

We are using [standard functions](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproduct.php#L105) to pull the image url, but it seems that does not work for your case... so my guess is a custom extension is changing this behavior somehow. If we know what that extension is, maybe we can fix it for you or give you a code snippet to fix it.

**Comment by shadowsand** [comment]
Thanks for responding, it seems like the cause of the image unavailability is due to cpanel hotlink protection which I have installed. 

That said I tried to disable hotlink protection and resync the shop but the images are still not showing up. Any suggestions why this is happening? 

I am using any ezusy.com chrome extension to fetch some images, but all these were pulled and uploaded to my wordpress site and images are sitting on my server. Even then, those images which were uploaded manually onto my wordpress site is also not showing the images

**Comment by tahoff** [comment]
Hey @shadowsand, it looks like the images on your shop are appearing now. It looks like the usage of cPanel hotlink protection does have a conflict with usage in Facebook ads/shops. If you're looking to reenable the hotlink protection for your site, it looks like you can selectively allow access to our crawler. For more info about Facebook's crawler, you can go here: https://developers.facebook.com/docs/sharing/webmasters/crawler 

I'll close this issue for now, unless the images in your shop become an issue again.

**Comment by ingegnocreativo** [comment]
Hello everyone, sorry if I reopen this post, but I have the same problem, the synchronization of products is done correctly, but you can not see the images on facebook.

WooCommerce: Version 3.2.6
Facebook for WooCommerce: Version 1.7.3

You can help me?

Thank you

**Comment by ingegnocreativo** [comment]
Hi, I remembered that all product images have an external URL from Amazon. Can this help you?

Thank you

**Comment by PowerhouseGroup** [comment]
Hi, I am using this plugin for the first time and the issue I have is that on the "shop" page in FB only about 4 images show up out of over 1000 products. However if you click any product, the image of every product I have checked shows up in the popup, so the images are being pulled. Any thoughts on how to fix?

**Comment by mccait** [comment]
I'm having the same problem as the OP - about four out of 1200 products are showing the images

www.facebook.com/moxieandoliver 

Any thoughts? I used the facebook plugin for woocommerce

**Comment by ezataltahan** [comment]
Hi all
i have the same problem
only the photo i relink can appear other photos or image library is blank
Woocommerece 3.5.4
facebook for woocommerce 1.9.8 
anyone can help

www.facebook.com/damassweets 
www.damassweets.com/shop

**Comment by adriannees** [comment]
I am also having this issue. The products exist and have photos on my site but are showing blank boxes on Facebook. Some photos import and others do not.
