### ISSUE TITLE
Multisite setup looking for wp_2_actionscheduler_actions creates fatal error

### ISSUE THREAD

**Issue by anderslundyo** [facebookincubator/facebook-for-woocommerce#1318]
##🚶‍♀️ Steps to reproduce
After multisite network setup. Looking for a table that doesnt exist, and creates fatal error.

## 🗃 Logs
Fatal error: Uncaught RuntimeException: Error saving action: Table 'lovechild1979_com_db.wp_2_actionscheduler_actions' doesn't exist in /var/www/www.lovechild1979.com/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:75 Stack trace: #0 /var/www/www.lovechild1979.com/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action)) #1 /var/www/www.lovechild1979.com/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(105): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #2 /var/www/www.lovechild1979.com/www/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(45): ActionScheduler_ActionFactory->recurring('wc_facebook_reg...', Array, 1589976335, 900, 'facebook-for-wo...') #3 /var/www/www.lovechild1979.com/www/wp-content/plugins/facebook-for-woocommerce/includes/Product in /var/www/www.lovechild1979.com/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 75

**Comment by anderslundyo** [comment]
Hi. I found out that the tables **needs** to be created, and while this plugin creates a fatal error, the error just comes elsewhere when deactivating..
Although this fatal error should be fixed, if you're in the same situtation as me, you can go ahead to your database, and export the structure of the missing tables. Before exporting, you can rename the tables so that they fit the missing tables.

Hope this could help someone else.

**Comment by lgfogle** [comment]
Hey @anderslundyo,

Thanks for sharing what worked for you! I'm going to close this issue, since it looks like you've solved it, but please feel free to reach out again if you run into other issues, or contact our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance.

Thank you!
Lindsey
