### ISSUE TITLE
plugin upload only 3 products

### ISSUE THREAD

**Issue by designsi** [facebookincubator/facebook-for-woocommerce#1319]
1. Facebook Page URL https://www.facebook.com/design.si.it/
2. WordPress and WooCommerce version number WordPress 5.4.1 WooCommerce version: |   | 4.1.0
3. Facebook Plugin version number Version 1.11.2
4. How many products you have about 15.000
5. Types of products (i.e. anything besides simple/variable products won’t work) simple and variable
6. Do you have Duplicate SKUs in your system? only for multilanguage translation
7. What kind of customization plugins you’re using (if any)? none
On the first days of April we where able to upload products on facebook throughout the plugin on the facebook page of the physical shop held by my sister  https://scontent.fcia1-1.fna.fbcdn.net/v/t1.15752-9/91910816_539291000106273_3068191805808836608_n.jpg?_nc_cat=106&_nc_sid=b96e70&_nc_ohc=gzabi0yV_gsAX8iTVAR&_nc_ht=scontent.fcia1-1.fna&oh=3a40b440890e165b03b0fc769f274269&oe=5EEA29D5 . From the end of April I have unsuccessfully tried to upload products to my facebook page design.si.it  for the onlinestore, but just 3 products have been uploaded

**Comment by designsi** [comment]
@mengyingdu I have seen you gave suggestion for a similar issue, thanks

**Comment by lgfogle** [comment]
Hey @designsi,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey
