### ISSUE TITLE
Compatibility Issue : Support Bundles Extension

### ISSUE THREAD

**Issue by bstrokevin** [facebookincubator/facebook-for-woocommerce#132]
Product Facebook Description is blank after saving product bundles.

<img width="812" alt="screen shot 2017-11-02 at 7 30 56 am" src="https://user-images.githubusercontent.com/13989077/32303183-fa00efac-bfa1-11e7-8ec0-18b02150a471.png">

**Comment by dmitridr** [comment]
Hello,

Thanks for flagging this.
I couldn't find the option to do this on our test servers. Is this an extension?

This one? 
https://woocommerce.com/products/product-bundles/

Could you also confirm you are using one of the latest versions v1.6.5?
I'll mark this as a feature request to support this extension if that is the case.

**Comment by bstrokevin** [comment]
Yes, we are using https://woocommerce.com/products/product-bundles/ <https://woocommerce.com/products/product-bundles/>
and 1.6.4
kevin

**Comment by dmitridr** [comment]
Related to #100

**Comment by mengyingdu** [comment]
Hi @bstrokevin ,

We will have basic support for bundle products in next release.
Bundle products can be synced, pixel events can be fired (view content, add to cart, initiate checkout , etc) However, we have issues if you disable 'redirect to cart after successful adding products' in your settings. (only if a bundle product which includes a variable product in this case, we can't get value from cart if we fire addToCart from ajax click, ALL other events work correctly.)

I would suggest you enable to redirect to cart directly in you woo settings.

Thanks.

**Comment by mengyingdu** [comment]
Hi @bstrokevin,

We added support for bundle products extension in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6)

Thanks.

**Comment by divedesigns** [comment]
I'm currently usind v1.9.11 of Facebook for WooCommerce with v5.7.11 of [WooCommerce Product Bundles by SomewhereWarm](https://woocommerce.com/products/product-bundles/) and I experience the following issue:

I have connected my WooCommerce store with Mailchimp and Facebook. When we look at bundles which were created with the Product Bundles plugin and are based on individually priced items, we see a price of 0.00€. How can we achieve the correct price to be displayed there. I guess this is an issue based on the bundled item not having a price in the usual price field.

Do you have any suggestion on how to resolve the issue of the price being 0.00€?
