### ISSUE TITLE
Facebook ads redirects to 404

### ISSUE THREAD

**Issue by metuza** [facebookincubator/facebook-for-woocommerce#133]
Hello..

I just found that all my facebook ads setup using the product catalog redirects to 404. When i check the product url in the ads all url has this ending after the orginal url: /commerce/products/1596694877021707/

Any idea?

Thanks

**Comment by dmitridr** [comment]
Hello, 

That's not good, can you give us an id of the ad campaign/ad set/ad that you are running? 
I checked your product catalog and the url is correct, so it must be an issue with our ads system.

**Comment by metuza** [comment]
Thats for sure. just added som info to the 404 page as i see many visitors gets there at the moment. Here is from my 2 ads campaigns. Both of them have the ending added to url.

1. selected_campaign_ids=6081411132883&selected_adset_ids=6081411134083
2. selected_campaign_ids=6074385035083

I hope you find a solution :)

Thanks

**Comment by dmitridr** [comment]
Confirmed : It's a problem within our ads system. We are fixing this ASAP, expect the behavior to be fixed within 48 hours.

**Comment by dmitridr** [comment]
A new version of Facebook was just pushed with the fix. I verified on the ads you gave that the behavior is fine now.

Impact:
The issue happened from Nov 1st, 1:30am PST to the present time, so about 1.5 days. It seems only simple products were affected. Pretty huge issue however, thanks @metuza, if not for your quick report it would have taken us much longer to notice the problem.
