### ISSUE TITLE
Event code detected, but the pixel has not activated for this event

### ISSUE THREAD

**Issue by hohohupi** [facebookincubator/facebook-for-woocommerce#1336]
Hi, 

I have a shop based on Wordpress (v5.4.1) + StoreFront + WooCommerce (v4.1.1) and I am using Facebook for WooCommerce plugin version 1.11.3 to integrate with Facebook. 

The problem is that Facebook Pixel is not sending proper information to Facebook about the Events like: Add to Cart, Initiate Checkout, Purchase. It is only reporting Page View. And when testing in Events Manager/Diagnostic, no issues are reported.

The only hint I could find is testing using Facebook Pixel Helper. This Tool is reporting something like this for the Event marked as Add to Cart:

"We detected event code but the pixel has not activated for this event, so no information was sent to Facebook. This could be due to an error in the code, but could also occur if the pixel fires on a dynamic event such as a button click"

https://prnt.sc/sl0otx

If you need any more information, I'm happy to deliver what is needed.

**Comment by lgfogle** [comment]
Hey @hohohupi,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey
