### ISSUE TITLE
Out of memory errors since 1.11.0

### ISSUE THREAD

**Issue by galapogos01** [facebookincubator/facebook-for-woocommerce#1344]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Since installing 1.11.0 my web server error log is seeing out of memory errors approx. every 15 mins. This only started happening after installing 1.11.0 and is still present in 1.11.3.

It appears the new feed generating action scheduler job is causing this issue. It fails every time it executes.

I have bumped the php memory_limit to 300mb per process (previously 192mb) and am still encountering this issue.

My site has approx 3600 products.

## 🚶‍♀️ Steps to reproduce

1. Install 1.11.3
2. Wait

## ✔️ Expected behavior
Feed is created without error.

## 🗃 Logs
Let me know what logs are required and I will provide them securely.

**Comment by lgfogle** [comment]
Hey @galapogos01,

Thanks for reaching out! We added many performance improvements to the plugin in general and product syncing specifically in the latest version (2.0.1). Could you please upgrade to that version and let me know if the problem persists?

Thank you!
Lindsey

**Comment by lgfogle** [comment]
Oops, closed accidentally!

**Comment by lgfogle** [comment]
Closing due to no response. @galapogos01, if you're still encountering this issue in the latest version, could you please let me know? Thank you!
