### ISSUE TITLE
Products not all exporting/syncing and quantity incorrect when products added to basket via facebook

### ISSUE THREAD

**Issue by philspoors** [facebookincubator/facebook-for-woocommerce#1354]
## 🔎 Isolate the bug

- [ X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [(scared to changed theme in case it ruins site) ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

##🚶‍♀️ Steps to reproduce

1. Always happens
1. Always happens

**Comment by lgfogle** [comment]
Hey @philspoors,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey
