### ISSUE TITLE
FB button to go to product page?

### ISSUE THREAD

**Issue by justinrains** [facebookincubator/facebook-for-woocommerce#137]
Is it possible for the button on facebook to go to the product page instead of add to cart page? I'm running an affiliate store.

Thanks,
Justin

**Comment by metuza** [comment]
Hi there... Yes, i just figured it out :) Just go to your FB site settings then click the shop menu down to the left and you will see an option "Use Checkout Urls", then just disable this and button will go to single product page.

**Comment by tahoff** [comment]
@metuza is correct, that's the way to change the urls.

**Comment by sayed786github** [comment]
@metuza Thanks very much for solution
