### ISSUE TITLE
Diagnose issues - "activate delivery" - products are not active

### ISSUE THREAD

**Issue by csertaalexandra** [facebookincubator/facebook-for-woocommerce#1371]
Hi everyone!
I have a woocommerce shop, selling organizing products.
I uploaded the plugin, so WOO, FB and Insta is shared, I can see my products, but it detect a diagnosed issue, and says I sould activate my products to be able to see it on Facebook.
I have absolutely no idea where I can do that I have been doing troubleshooting for the past couple of hrs, been on every damn site, but no idea.
Attached some pictures, please help me :)

Thank you!
![Képernyőfotó 2020-05-27 - 10 18 42](https://user-images.githubusercontent.com/29069010/83005239-d879c000-a010-11ea-9911-0d9e393d5e42.png)
![Képernyőfotó 2020-05-27 - 10 18 48](https://user-images.githubusercontent.com/29069010/83005248-dadc1a00-a010-11ea-99b6-e2ce8395561d.png)
![Képernyőfotó 2020-05-27 - 10 23 58](https://user-images.githubusercontent.com/29069010/83005250-dadc1a00-a010-11ea-9456-009a8525df52.png)
![Képernyőfotó 2020-05-27 - 10 24 01](https://user-images.githubusercontent.com/29069010/83005251-db74b080-a010-11ea-8a89-da2f0b6cbfdc.png)

![Képernyőfotó 2020-05-27 - 11 20 05](https://user-images.githubusercontent.com/29069010/83005254-dc0d4700-a010-11ea-9f60-2c9c229b42c2.png)
![Képernyőfotó 2020-05-27 - 11 20 34](https://user-images.githubusercontent.com/29069010/83005255-dc0d4700-a010-11ea-8020-b353e09d4f68.png)
![Képernyőfotó 2020-05-27 - 11 37 04](https://user-images.githubusercontent.com/29069010/83005258-dca5dd80-a010-11ea-86f2-1ee675cb0fef.png)
![Képernyőfotó 2020-05-27 - 11 37 15](https://user-images.githubusercontent.com/29069010/83005260-dca5dd80-a010-11ea-9314-320531bc552f.png)
![Képernyőfotó 2020-05-27 - 11 41 35](https://user-images.githubusercontent.com/29069010/83005261-dd3e7400-a010-11ea-836e-959f5a53ef59.png)
![Képernyőfotó 2020-05-27 - 11 43 48](https://user-images.githubusercontent.com/29069010/83005262-dd3e7400-a010-11ea-8333-1752f14786a6.png)

**Comment by csertaalexandra** [comment]
![Képernyőfotó 2020-05-27 - 14 07 19](https://user-images.githubusercontent.com/29069010/83017162-737b9580-a023-11ea-9422-46425ef90915.png)

**Comment by lgfogle** [comment]
Hey @csertaalexandra,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey
