### ISSUE TITLE
Unresponsive and timeouts when updating products with many variations

### ISSUE THREAD

**Issue by mtg169** [facebookincubator/facebook-for-woocommerce#1377]
## 🔎 Isolate the bug

- [X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

On a client site with products that have an average of 70+ variations, updating the product takes an average of 1 minute or longer, often becomes unresponsive and/or times out. Hangs on POST request to wp-admin/post.php

##🚶‍♀️ Steps to reproduce

1. Edit a product with many variations (70+)
2. Edit a specific variation option such as stock quantity
3. Click Update

## ✔️ Expected behavior

Product should save immediately or much quicker than it is currently. With plugin deactivated, the product saves within 5 seconds. With plugin activated, it regularly times out due to Cloudflare's 120 second timeout limit. 

## 🗃 Logs

[wordpress-enviro.txt](https://github.com/facebookincubator/facebook-for-woocommerce/files/4691972/wordpress-enviro.txt)

**Comment by lgfogle** [comment]
Hey @mtg169,

Thanks for reaching out! We've added many improvements to the product sync performance in Facebook for WooCommerce version 2.0.1 - could you please update to that version and let us know if you're still encountering this issue?

Thank you,
Lindsey

**Comment by lgfogle** [comment]
Closing due to no response.

**Comment by mtg169** [comment]
This did appear to be resolved, but we are now seeing maximum execution time reached like the following from an apparent background process that may have replaced it. 

2020-10-26T01:45:46+00:00 CRITICAL Maximum execution time of 30 seconds exceeded in /wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 565

Does the plugin specifically set the maximum execution time somewhere? The server this is happening on shows max execution time set to 600 seconds when checking phpinfo(), yet we repeatedly get these errors multiple times daily showing a 30 second limit.

**Comment by simonporter007** [comment]
Hi @mtg169,

The plugin doesn't set the maximum execution time, as this is normally set in your servers PHP configuration. Some hosts have a hardcoded set limit, while others do allow this to be increased. If you have a substantial number of products and not enough server resources, then you may see the error you've mentioned.

Can I check if you are using the latest version of the plugin? Our developers have released some improvements to the feed generation logic in the most recent versions that might help!

Cheers,

**Comment by mtg169** [comment]
Yes, on latest version 2.1.2. We are logging fatal errors like this daily:
2020-10-28T08:25:53+00:00 CRITICAL Maximum execution time of 30 seconds exceeded in /html/wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php on line 81

Client is on a pretty large dedicated server and load is fine. Data center has also confirmed maximum execution time is set to 600 seconds. A script that the plugin relies on must be setting it within PHP somewhere.

**Comment by mtg169** [comment]
The max execution time of 30 seconds is being set by Action Scheduler as a default instead of using the server's setting: https://github.com/woocommerce/action-scheduler/blob/master/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L130

When monitoring wp-cron, we see an infinite execution time that changes to 30 seconds by the action_scheduler_run_queue. The only pending action that ever seems to exist is wc_facebook_regenerate_feed and runs every 15 minutes. It fails multiple times a day due to the max execution time. 

I am not seeing action_scheduler_queue_runner_time_limit being used anywhere in the plugin. This should probably be an added feature for sites with many products/variations due avoid the sync from timing out. For now I will just set it myself.
