### ISSUE TITLE
rearranging the product position based on categories

### ISSUE THREAD

**Issue by sean3650** [facebookincubator/facebook-for-woocommerce#139]
hi 
is there a way to rearrange products and acutally put them in a category on facebook shop?

**Comment by tahoff** [comment]
Unfortunately this isn't done automatically. But you can manually create Collections in the FB shop or product sets for your catalog if you want to use the set in ads. @dmitridr specified the help articles to do those things in #34.

**Comment by dmitridr** [comment]
I'm going around following up on old issues, looks like this one can be closed. As @tahoff said, this can be manually done through collections, those can be created in the shops interface.
