### ISSUE TITLE
Products not Properly Syncing

### ISSUE THREAD

**Issue by kmb0413** [facebookincubator/facebook-for-woocommerce#1400]
## 🔎 Isolate the bug

- [/ ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

##🚶‍♀️ Steps to reproduce

1. The plugin was installed by my client and it won't import products at first, but we were able to fix it. It was facebook pixel issue.
2. I reconnected the facebook page and  the website and I was able to sync, but it only uploaded 27 products although we have 100+ products in the website. I tried to reconnect again but it's still importing 27 products.

## ✔️ Expected behavior

It's suppose to import all of the products in the woocommerce instead of importing only 27 products.

**Comment by acharmat** [comment]
Same problem !

**Comment by lgfogle** [comment]
Hey @kmb0413 and @acharmat,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? Problems where only _some_ products sync are often related to configuration issues with the products themselves, or limitations of the plugin based on the plugin type (e.g. Virtual products). We'd be happy to help investigate this more closely! 

Cheers,
Lindsey
