### ISSUE TITLE
Products description in facebook store are included in [vc_row] tags

### ISSUE THREAD

**Issue by HairProducts** [facebookincubator/facebook-for-woocommerce#1405]
## 🔎 Isolate the bug

- [X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Products description in facebook store are included in [vc_row] tags

##🚶‍♀️ Steps to reproduce

Products description in facebook store are included in [vc_row] tags

## ✔️ Expected behavior

The tags [vc_rows] must not be shown

## 🗃 Logs

last upadated versions of Wordpress/Woocommerce/Facebook-for-woocommerce as in 4th June 2020

**Comment by lgfogle** [comment]
Hey @HairProducts,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey
