### ISSUE TITLE
Facebook for WooCommerce - Failing to sync updated products to Facebook

### ISSUE THREAD

**Issue by samcaz** [facebookincubator/facebook-for-woocommerce#1411]
## 🔎 Isolate the bug

- [X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
We've had just updated the Facebook for WooCommerce plugin, directly via the WooCommerce website. The client has logged in and reconnected the plugin to:

- Facebook Page
- Instagram Page
- Pixel
- Ad Account
- Product / Merchandise Catalogue

It is all connected properly, however it is still pulling in previous the previous sale price of products from a month ago. They have been updated with the new price in the backend of the website, yet are still pulling through the WRONG prices in Facebook.

How can this be resolved? I can't work out where it's gone wrong. None of their products are virtual either.

##🚶‍♀️ Steps to reproduce

1. The first step
1. The next step…

**Comment by Beau515** [comment]
I don't know if I can get help from here. For the past few weeks I've been battling with a clients website. I installed the facebook for woocommerce plugin and the first time everything synced correctly but she alone as admin could see the products, her page visitors don't get to see the product. When I tried to set it up again the products were no longer visible on the shop tab but only visible in a catalog and the shop tab isn't visible to her page visitors any more.  When she tried to add products directly to the shop from facebook it worked so well, the shop tab and the products were visible to her page followers. Please I need help. I have tried all I can to no avail. Here's the URL of her website https://www.glitax.com/,  the url of her facebook page https://www.facebook.com/Glitax-Hair-201035423974956/

**Comment by savlajubin** [comment]
I have the same issue... Even manual sync doesn't sync the products

**Comment by lgfogle** [comment]
Hey @samcaz, @Beau515, and @savlajubin,

Thanks for reaching out!

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey
