### ISSUE TITLE
Unable to login to Facebook page

### ISSUE THREAD

**Issue by Parkesbu** [facebookincubator/facebook-for-woocommerce#1413]
Facebook page was created using Facebook for Woocommerce, it created page and synced all products set website address and appears to be working as, when changes are made to product or product added it syncs. 

Issue is we cannot login to Facebook to manage the page, remove pixel or any Facebook actions

Facebook can't find any of the email address we have can't find fb page by name or mobile (which was not used when setting up from the plugin) so can't find any method to change password. This means we can't contact fb because they need the account

Yes it's syncing with site can add new products delete products etc. But can't do any advertising, change logo add contact details because we can't login.

## 📖 Read documentation

The [Facebook for WooCommerce documentation](https://docs.woocommerce.com/document/facebook-for-woocommerce/) will help you set up the extension, use its features, and answer frequently asked questions. 

## 👩‍💻 Check forums

The [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) let you review other user questions and issues and learn what worked for them. 

## 🗣 Contact support

Our support team would be happy to help answer your questions! [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)

**Comment by lgfogle** [comment]
Hey @Parkesbu,

Thanks for reaching out! 

Based on the description here, this looks like something our support team can help out with. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey
