### ISSUE TITLE
Changed business account password make the plugin needs configuration from the beginning

### ISSUE THREAD

**Issue by edm0d0n** [facebookincubator/facebook-for-woocommerce#142]
Hello. I changed the business account password on fb because facebook security told someone login using my old password. Then there was a plugin error and i configured from the beggining. The problem is now that it made a need product catalog and when i tried to make two new dynamic caroussel product ads one for add to cart and one for view content then it shows me that the audience is low. Before the last 30 days audience for view content was 2k audience. when i configure the plugin from the begin all the previous data is lost?

**Comment by tahoff** [comment]
Hello @edm0d0n, unless you selected a different pixel during setup, the pixel data should be the same even after reinstalling.

Did you try creating a dynamic product ad before the password change? If so, did you see the limited audience issue at that time? What is your website's URL?

**Comment by edm0d0n** [comment]
I am sure i selected the same pixel. The site is techkiddo.com . I had dynamic products ads running before the password change and after i reset the plugin it showed some error product catalog not found. after i made a new catalog the estimated audience from 2k went to estimated audience unavailable.

**Comment by tahoff** [comment]
It looks like the pixel on your site is from Pixel Your Site, rather than our extension. Did you uninstall ours? Your pixel does have View Content events, but they're not associated with your catalog because a pixel from our extension isn't currently on your site.

**Comment by edm0d0n** [comment]
I have them both facebook for woocommerce and pixelyoursite pro. There is an option in pixelyoursite that says Use Facebook for WooCommerce extension content_id logic i have this checked and used to work fine. Are you sure the catalog is not associated with the pixel? I use pixelyoursite as i use an option to woocommerce that when someone adds product to the cart it autodirects to the cart page and your plugin i think does not trigger add to cart events.

**Comment by tahoff** [comment]
The catalog was associated, but for some reason the pixel fires weren't matching initially. It looks like the events (View Content, Add to Cart, and Purchase) are now attributed to your catalog. It's possible there was a delay on our end, unless you made an update on your website. Closing the issue for now.
