### ISSUE TITLE
Facebook Pixel not showing 

### ISSUE THREAD

**Issue by JoeySaps** [facebookincubator/facebook-for-woocommerce#1427]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

I have tried completing the steps to start however after I select my store I have to select my pixel but it shows pixels from a different facebook page to the one I am connecting. I cant move forward.

##🚶‍♀️ Steps to reproduce

1. The first step
1. The next step…

**Comment by lgfogle** [comment]
Hey @JoeySaps,

Thanks for reaching out! 

We'll need some more information from you about this issue before we can troubleshoot further. Could you please contact our team on the [WordPress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you're still encountering this problem? We'd be happy to help!

Cheers,
Lindsey

**Comment by JoeySaps** [comment]
Hi,

Why is this closed?

Can someone please let me know what information you need instead of just you need more information?

________________________________
