### ISSUE TITLE
Product images sizes in iPad app

### ISSUE THREAD

**Issue by whatevs-already** [facebookincubator/facebook-for-woocommerce#143]
I'm having an issue with product image sizes on iPad, they are huge and don't fill the screen. 

Images are properly resized on desktop, huge on iPad, and the entire shop won't even load on iPhone 7. 

I'm using an older iPad on iOS 10.3.3 but successfully running the latest version of Facebook app. 

Screenshot: https://snag.gy/0hFndM.jpg -- that's actually a square image of a pillow, but this is what it shows in the shop, for every pillow... about 1/4 of the actual product image.

My website is woocommerce, latest versions of WP and WC. I'm using "Smart Variations Images Pro" plugin so my customer can choose from two custom attributes I create within each product page (design and color) and I then make the variations from those attributes. 

But the image the FB shop is pulling is the main product image for the page, which is the correct image... it's just huge.

**Comment by tahoff** [comment]
@whatevs-already thanks for flagging this issue. Are you using the latest version of Facebook for WooCommerce (1.6.5)? If not, please try updating because the product image should be variation specific. Additionally, can you send the url of the product from the attached screenshot?

**Comment by dmitridr** [comment]
Hi @whatevs-already I'm following up on older issues in this repository. Are you still having this problem? 
This seems like a bug with shops, but I'm not sure if it has been fixed by that team (if so, we can close this), or still is a problem (if so, we can hand this off to that team).

**Comment by whatevs-already** [comment]
Hi, please give me a couple of days to test this again, and I’ll let you know early next week if the problem still persists.

**Comment by whatevs-already** [comment]
Hi @dmitridr – the problem is now fixed, thank you. Apologies I didn't reply to your message back on Nov 7th I didn't receive notification on that one.
