### ISSUE TITLE
Hide prices from Facebook shop page

### ISSUE THREAD

**Issue by francesca-silvi** [facebookincubator/facebook-for-woocommerce#1435]
We’re happy to help with this question! Our support team works in our help desk rather than GitHub, though, so please use one of the following tools instead:

## 📖 Read documentation

The [Facebook for WooCommerce documentation](https://docs.woocommerce.com/document/facebook-for-woocommerce/) will help you set up the extension, use its features, and answer frequently asked questions. 

## 👩‍💻 Check forums

The [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) let you review other user questions and issues and learn what worked for them. 

## 🗣 Contact support

Our support team would be happy to help answer your questions! [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)

**Comment by francesca-silvi** [comment]
Hi, I would like to set up a facebook shop linked to a woocommerce website but I don't want to show prices directly. I would like to direct customers to sales through a request a quote process. I have already done this on my website but facebook is currently showing prices. Can you please help me on how to hide prices from facebook? Thank you!

**Comment by lgfogle** [comment]
Hey @francesca-silvi,

I'm afraid Facebook requires that we sync a price for products in the catalog, but this may be possible on the Facebook side based on your page configuration. I'd recommend reaching out to the [Facebook support team](https://www.facebook.com/business/help) to see if it's possible to hide prices in the page shop.

Thank you!
Lindsey
