### ISSUE TITLE
One or more of your products is using a checkout URL that may be different than your shop checkout URL

### ISSUE THREAD

**Issue by SynthiaT** [facebookincubator/facebook-for-woocommerce#1436]
![Screenshot 2020-07-21 at 15 25 43](https://user-images.githubusercontent.com/68601557/88067117-7ba90a80-cb66-11ea-8428-f5963a53b1f4.png)
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

I just installed a Pixel on my website and synchronised my catalogue with Facebook and when I go to my website-Dashboard-Products I see this: One or more of your products is using a checkout URL that may be different than your shop checkout URL. I did the re-sync but I still keep seeing the message. I read from an old post that this was supposed to be removed. What am I doing wrong?

**Comment by francescosche** [comment]
Hi @SynthiaT !
Same problem here....
I'm using the Divi Theme, and I customized the "Single Product" page, can I know if you've found any solution on this?

**Comment by SynthiaT** [comment]
Yes, I deleted the Pixel and everything that is connected to it and I went back to my previous set up and there is a reason to it. I contacted Facebook and asked for their help and they couldn't help me at that moment. But this Pixel disrupted my campaigns and everything that I was doing. So since they couldn't help me and they asked me to wait 2-3 days, I had to delete everything. I am not a developer but If they people who have created the Pixel do not have the knowledge in resolving the problem then there is nothing for me to do. I hope that someone will hear about your issue and help out.

**Comment by lgfogle** [comment]
Hey @francescosche and @SynthiaT,

Thanks for reaching out, and I'm sorry about the delay in my response!

Could you please confirm whether you're still encountering this issue in the latest version of Facebook for WooCommerce (2.0.0)? We made some significant improvements to product syncing in this update that may have resolved this problem, so I want to be sure you're using that version first before we troubleshoot further!

Thank you,
Lindsey

**Comment by francescosche** [comment]
Not seeing the error anymore, thanks! <3

**Comment by lgfogle** [comment]
Glad to hear it, @francescosche! Thanks for letting me know. 

@SynthiaT, I'm going to close this issue, but could you please let me know if you're still seeing that error in Facebook for WooCommerce 2.0.0? If so, I'll reopen and we can continue to investigate.
