### ISSUE TITLE
Facebook for woocommerce not working

### ISSUE THREAD

**Issue by khairen728** [facebookincubator/facebook-for-woocommerce#1437]
Hello all, I have some trouble integrating my Wordpress (woocommerce) website to facebook shop. Everytime I'm prompt to select a pixel, the pixel that I'm supposed to use for my website doesn't appear in the list. Any ideas on how to resolve this?

![image](https://user-images.githubusercontent.com/68644265/88170563-7d4efd00-cc50-11ea-8a52-3975069aff97.png)

By the way, I have already integrated facebook pixel into my Wordpress website.

**Comment by lgfogle** [comment]
Hey @khairen728,

Thanks for reaching out! We recently released a major upgrade to Facebook for WooCommerce, which should make connecting easier. Could you please upgrade and let me know if this issue persists?

Thank you!
Lindsey

**Comment by lgfogle** [comment]
Closing due to no response.
