### ISSUE TITLE
Composite products cannot be enables for sync to facebook page

### ISSUE THREAD

**Issue by heisenberg617** [facebookincubator/facebook-for-woocommerce#1442]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When attempting to enable facebook sync'ing for a composite product the checkbox does not store as enabled and the product does not sync or get added to the csv export.

## 🚶‍♀️ Steps to reproduce

1. Check the box to enable syncing on a composite product
1. Upon save you will find the checkbox is again disabled
1. The product is not added to the facebook csv file nor the product catalog at facebook page

The same results occur when doing this from the Bulk operations at the products list

## ✔️ Expected behavior

Products should be added to the csv and the facebook page catalog and the checkbox should enable correctly.

## 🗃 Logs

WordPress version 5.4.2
Current theme: Storefront (version 2.5.8)
Current plugin: Facebook for WooCommerce (version 1.11.4)
PHP version 7.3.19-1~deb10u1

**Comment by heisenberg617** [comment]
The new 2.0.0 version seems to have solved the issue and allowed me to mark the products at "Sync but Hide" or however it reads. They were however not "hidden" and show in my shop as I would expect. Not sure what the assumption that composite products are virtual is. Mine certainly aren't. I use composite products because I want to allow greater flexibility for my customers to customize their purchase. Just like the skateboard example in woocommerce composite product demo. Choose board, choose trucks, choose wheels, choose bearings, etc.

**Comment by heisenberg617** [comment]
In reviewing further I found that my composite products must be considered virtual but they most certainly are not. That said they are hidden on facebook as this plugin sort of indicated in my last message. On the facebook side I see the products as an administrator but my end users do not. Looking at the shop catalog I think the products in question say:
"People cannot currently see this product because you haven't selected it for sale on Facebook."

With no option to select them as for sale.

**Comment by heisenberg617** [comment]
I ended up deactivating and reactivating my integration trying to troublshoot some things. Upon re-enabling my facebook account connection it simply errors. Now I am stuck with no working integration...

<img width="566" alt="Screen Shot 2020-07-31 at 3 21 21 PM" src="https://user-images.githubusercontent.com/40622298/89082030-bcacd600-d341-11ea-9535-fdcb310184f1.png">

**Comment by heisenberg617** [comment]
Found a workaround. I deactivated, uninstalled, then added 1.11.4, activated, ran through the setup process, clicked on manage connection again and it warned me the site was already setup and I would need to deactivate the connection to continue, I did that and everything was working correctly again, removed 1.11.4 from server, added 2.0.0, setup the connection again, and all is good...

Issue still remains with composite products being set as hidden in my facebook store.

**Comment by heisenberg617** [comment]
Reading through the generated csv I found that composite products are coming through with visibility = staging. In Facebook Commerce Manger -> Catalog -> Data Sources -> [My woocommerce feed] -> Settings -> Data Feed Rules I clicked on "Add rule" then "Use Replace" and set the Visibility column to replace "staging" with "published". Now my products show on updates but it is a bad solution IMO. At least my Facebook business can resume as desired...

**Comment by heisenberg617** [comment]
Turns out my hack above still didn't solve it after a second update, no idea why. I ended up just hacking the constant `FB_SHOP_PRODUCT_HIDDEN` to set it to `published`. That could have unintended consequences I know but I need working products...

NOTE: may need to bump PHP to have the new constant take effect.

One additional issue, one of my composite products will not sync no matter how I set it's values, I can't for the life of me determine why. It actually allowed me to set "Sync and show in Catalog" and then the status in the sidebar always says, "This product is not yet synced to Facebook." yet no matter how much I attempt to force a sync it never shows up nor does it get put into my generated csv. I am giving up on that one product for now and will likely create it manually on the facebook side just so I can stopped spinning my wheels on this.

**Comment by heisenberg617** [comment]
Got lucky and noticed that one that wasn't showing had a variable price. I set a price in the facebook price field and it started sync'ing. That said I have this solved for me but I certainly don't like having to hack the constant inside the plugin. Updates will be fun having to remember to keep that hack in place assuming you guys don't resolve the problem here.

**Comment by lgfogle** [comment]
Hey @heisenberg617,

Thanks for reaching out, and I'm sorry for the delay in my response!

This sounds like an issue that our support team would be best suited to help troubleshoot. While non-standard products (such as composite products) don't always sync perfectly to Facebook, what you're seeing isn't expected and we should be able to get to the bottom of it so you don't need to use any workarounds. Could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Lindsey
