### ISSUE TITLE
There was an error trying to sync the products to Facebook.

### ISSUE THREAD

**Issue by patelharshish** [facebookincubator/facebook-for-woocommerce#1444]
Hi,

I just installed this plugin and when trying to sync its keeps giving following error. Seems that ajax is taking too long to load and script it getting timed out. 

There was an error trying to sync the products to Facebook.

Please help so i can connect the store to Facebook. Thank you.

**Comment by lgfogle** [comment]
Hey @patelharshish,

Thanks for reaching out!

This sounds like an issue that our support team would be best suited to help troubleshoot. Could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Lindsey
