### ISSUE TITLE
CSV missing some columns

### ISSUE THREAD

**Issue by heisenberg617** [facebookincubator/facebook-for-woocommerce#1445]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Some data columns are missing and facebook reports them as an issue. Missing columns are:

 * google_product_category
 * variant_value
 * variant_label

## 🚶‍♀️ Steps to reproduce

1. Look at your report details for any of the csv imports in facebook.

## ✔️ Expected behavior

All required columns should be represented.

## 🗃 Logs

none

**Comment by lgfogle** [comment]
Hey @heisenberg617,

Thanks for reaching out! This issue appears quite similar to #1434, so I'm going to close this conversation to avoid duplicate issues. Feel free to follow that issue for updates!

Thank you!
Lindsey
