### ISSUE TITLE
Facebook shop status changed to share after V2 upgrade

### ISSUE THREAD

**Issue by stevejones13** [facebookincubator/facebook-for-woocommerce#1449]
Since updating to V2 - all of the items in my Facebook shop now have "Share" status instead of taking me to the Woocommerce shop item to purchase
https://www.facebook.com/pg/HungryBuddhaMeals/shop/
https://hungrybuddhameals.co.uk/

Please advise urgently as I have just done a mailshot to all customers!

**Comment by stevejones13** [comment]
![image](https://user-images.githubusercontent.com/69237106/89385934-4836b600-d6f8-11ea-9976-d5baea3eb838.png)

**Comment by stevejones13** [comment]
I tried re-linking - it failed

**Comment by doug3d** [comment]
same here

**Comment by growdev** [comment]
We experienced the same thing - unable to link after the 2.0.0 update.

**Comment by lgfogle** [comment]
Hey @stevejones13, @doug3d , and @growdev,

I'm so sorry about this connection problem!

The Facebook team has released a few fixes on their end that may resolve this issue - could you please try again and let me know if that works? There are a few pending problems that they are still working hard to address, but wanted to see if the work they've already done has fixed the particular problem that was blocking your connection.

Thank you!
Lindsey

**Comment by lgfogle** [comment]
Closing due to no response. @stevejones13, @doug3d, and @growdev - please let us know if you're still encountering any connection issues on the latest version!

**Comment by stevejones13** [comment]
I have not had the opportunity to test it - will need to create a new site and Facebook page becuase it has messed up my existing pages

**Comment by growdev** [comment]
We tested with FB for WC 2.0.1, and got the same error when trying to connect. 

@lgfogle I have an open ticket with SkyVerge on this.
