### ISSUE TITLE
Duplicate purchase events in facebook ads manager

### ISSUE THREAD

**Issue by visheshnayyar** [facebookincubator/facebook-for-woocommerce#1454]
Hello,
I've been using facebook for woocommerce plugin for syncing products to facebook and also running ads in the facebook ads manager. All the e-commerce basic events are pre configured in the plugin. However ads manager is showing multiple purchases which are not reflecting in woocommerce orders dashboard. I've also tested other events in the events manager where they are firing correctly. Any help towards this issue is appreciated.  Thanks

**Comment by lgfogle** [comment]
Hey @visheshnayyar,

Thanks for reaching out!

This sounds like an issue that our support team would be best suited to help troubleshoot. Could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Lindsey
