### ISSUE TITLE
Page seller has not been enabled to sell on facebook

### ISSUE THREAD

**Issue by jonathan814** [facebookincubator/facebook-for-woocommerce#1457]
My product is already integrated in my facebook catalouge but it doesnt showing in my facebook shop page it says . The sellers page has not been enabled to sell on facebook. 
Any help please.
here my facebook lpage link: https://www.facebook.com/jonathanstore814
![issue](https://user-images.githubusercontent.com/69410050/89745540-08e8da80-dae7-11ea-80fe-469457dd1015.jpg)
![isuue](https://user-images.githubusercontent.com/69410050/89745542-12724280-dae7-11ea-8516-e84e1e309223.jpg)

**Comment by lgfogle** [comment]
Hey @jonathan814,

Thanks for reaching out! 

This appears to be a problem related to the Facebook Page or other Facebook assets. I'd recommend reaching out to Facebook support directly for assistance by following these steps:

1. Go to **WooCommerce > Facebook**.
2. Click **Manage Connection**.
3. Click **Help** in the popup window.

Their team should be able to address why you received this message and how to fix it!

Thank you,
Lindsey
