### ISSUE TITLE
I have several issues in syncing the Woocommerce product to facebook

### ISSUE THREAD

**Issue by vipsouq** [facebookincubator/facebook-for-woocommerce#1461]
1. Some content_ids sent from pixel fires by this pixel do not match any catalog associated to the pixel, This could be because your catalogs aren't up to date, or because the item IDs in your catalogs don't match the content_ids in your pixel

2. Your data feed file can't be empty:
Add products to your data feed file and then upload it again. Uploading an empty file will delete all products in your feed. If you want to do this, please delete the feed that they were uploaded from.

**Comment by vipsouq** [comment]
Your data feed file can't be empty:
Add products to your data feed file and then upload it again. Uploading an empty file will delete all products in your feed. If you want to do this, please delete the feed that they were uploaded from.

**Comment by lgfogle** [comment]
Hey @vipsouq,

Thanks for reaching out!

This sounds like an issue that our support team would be best suited to help troubleshoot. Could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Lindsey
