### ISSUE TITLE
Variations set to "Any" not showing in Facebook Shop

### ISSUE THREAD

**Issue by 517Design** [facebookincubator/facebook-for-woocommerce#147]
Hi,
I have a product with 5 attributes. I have 3 variations for this product. In woocommerce the values of variations 1,2,3 & 5  are set to "Any..." and the 4th value is set to a specific value. (see screenshot)

<img width="1525" alt="screen shot 2017-11-10 at 11 34 30 am" src="https://user-images.githubusercontent.com/898599/32668708-53611bb0-c60c-11e7-9dab-7d940c8fc1ba.png">

The product is synced to Facebook and appears in our shop. However all 5 attribute dropdowns are there but dropdowns 1,2,3 & 5 are blank.  These are the values set to "Any..." in woocommerce. The 4th dropdown works correctly and is the one set to a specific value in woocommerce. (see screenshot)

<img width="440" alt="screen shot 2017-11-10 at 11 42 25 am" src="https://user-images.githubusercontent.com/898599/32668709-5372b528-c60c-11e7-8f12-bd308e86a384.png">
 
I can not "Create variations from all attributes" in woocommerce because there would be 1008 variations. 

How can i get my products in Facebook to display correctly? Thanks for your help

**Comment by tahoff** [comment]
Hey @517Design, thanks for reporting this issue. Can you confirm that you're using the latest version of Facebook for WooCommerce (1.6.6)? If you're using the latest version, and you've resynced your products after upgrading, can you send us your website URL, and any specific plugins to support your product variations?

**Comment by tahoff** [comment]
Closing this issue, please reopen if this continues to be an issue for you on version 1.6.6.

**Comment by 517Design** [comment]
Hi Sorry for the late response. I was just in the process of updating when you closed the thread. 

I have updated to 1.6.6 and I am still getting an issue but it is a little different. Now Facebook is showing the products like this:
<img width="438" alt="screen shot 2017-11-14 at 12 20 04 pm" src="https://user-images.githubusercontent.com/898599/32794253-4e6d08b2-c936-11e7-9a68-7fac21d0ded9.png">

In the example above the choices should be "Right" or "Left" not "any hand". "Any hand" is how the variation is created in woocommerce. See screenshot: 
<img width="1527" alt="screen shot 2017-11-14 at 12 25 24 pm" src="https://user-images.githubusercontent.com/898599/32794490-05b75e32-c937-11e7-9723-b94bf1093ab5.png">

Here is the website link to that product: https://krankgolf.com/shop/formula-7-driver/

There are no plugins to support my variations. However I am using infusedwoo to connect our products to infusionsoft. 

There are 38 Active plugins. Here is the list:

Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.19
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.15
Dynamic Featured Image: by Ankit Pokhrel – 3.6.1
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.2.0.1 – Not tested with the active version of WooCommerce
Envato WordPress Toolkit: by Envato – 1.7.3
Facebook for WooCommerce: by Facebook – 1.6.6 – Not tested with the active version of WooCommerce
InfusedWoo Pro: by Mark Joseph – 3.8 – Not tested with the active version of WooCommerce
Interactive World Maps: by Carlos Moreira – 2.0.1
Jetpack by WordPress.com: by Automattic – 5.5
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.2
Ninja Forms - Conditional Logic: by The WP Ninjas – 3.0.17
Ninja Forms - Multi-Part Forms: by The WP Ninjas – 3.0.22
Ninja Forms - Layout & Styles: by The WP Ninjas – 3.0.25
Ninja Forms - User Management: by WP Ninjas – 3.0.3
Ninja Forms - Zapier: by Fatcat Apps – 3.0.6
Ninja Forms: by The WP Ninjas – 3.2.4
Popup Maker: by WP Popup Maker – 1.6.6
Porto Theme - Functionality: by SW-THEMES – 1.0.0
WordPress Post Type Archive Links: by Stephen Harris – 1.3.1
Redirection: by John Godley – 2.9.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
Reveal IDs: by Oliver Schlöbe – 1.5.2
Slider Revolution: by ThemePunch – 5.4.6.2
Visual Composer Clipboard: by bitorbit – 3.25
Waiting: by Plugin Builders – 0.5
WooCommerce AdWords Conversion Tracking: by Wolf+Bär Agency – 1.4.7
WooCommerce Product Add-ons: by WooCommerce – 2.8.1 – 2.9.0 is available – Not tested with the active version of WooCommerce
WooCommerce FedEx Shipping: by WooCommerce – 3.4.5 – 3.4.9 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 5.7.1
WP Dashboard Notes: by Jeroen Sormani – 1.0.8.2
WP Rocket: by WP Media – 2.10.11.1
WP Sitemap Page: by Tony Archambeau – 1.6
WP Smush Pro: by WPMU DEV – 2.7.6
WP User Avatar: by flippercode – 2.0.8
WPMU DEV Dashboard: by WPMU DEV – 4.4
YouTube Pro: by EmbedPlus Team – 11.8.3.2

Thank you, Greg

**Comment by 517Design** [comment]
Hi Sorry for the late response. I was just in the process of updating when you closed the thread.

I have updated to 1.6.6 and I am still getting an issue but it is a little different. Now Facebook is showing the products like this:
[screen shot 2017-11-14 at 12 20 04 pm]<https://user-images.githubusercontent.com/898599/32794253-4e6d08b2-c936-11e7-9a68-7fac21d0ded9.png>

In the example above the choices should be "Right" or "Left" not "any hand". "Any hand" is how the variation is created in woocommerce. See screenshot:
[screen shot 2017-11-14 at 12 25 24 pm]<https://user-images.githubusercontent.com/898599/32794490-05b75e32-c937-11e7-9723-b94bf1093ab5.png>

Here is the website link to that product: https://krankgolf.com/shop/formula-7-driver/

There are no plugins to support my variations. However I am using infusedwoo to connect our products to infusionsoft.

There are 38 Active plugins. Here is the list:

Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.19
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.15
Dynamic Featured Image: by Ankit Pokhrel – 3.6.1
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.2.0.1 – Not tested with the active version of WooCommerce
Envato WordPress Toolkit: by Envato – 1.7.3
Facebook for WooCommerce: by Facebook – 1.6.6 – Not tested with the active version of WooCommerce
InfusedWoo Pro: by Mark Joseph – 3.8 – Not tested with the active version of WooCommerce
Interactive World Maps: by Carlos Moreira – 2.0.1
Jetpack by WordPress.com: by Automattic – 5.5
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.2
Ninja Forms - Conditional Logic: by The WP Ninjas – 3.0.17
Ninja Forms - Multi-Part Forms: by The WP Ninjas – 3.0.22
Ninja Forms - Layout & Styles: by The WP Ninjas – 3.0.25
Ninja Forms - User Management: by WP Ninjas – 3.0.3
Ninja Forms - Zapier: by Fatcat Apps – 3.0.6
Ninja Forms: by The WP Ninjas – 3.2.4
Popup Maker: by WP Popup Maker – 1.6.6
Porto Theme - Functionality: by SW-THEMES – 1.0.0
WordPress Post Type Archive Links: by Stephen Harris – 1.3.1
Redirection: by John Godley – 2.9.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
Reveal IDs: by Oliver Schlöbe – 1.5.2
Slider Revolution: by ThemePunch – 5.4.6.2
Visual Composer Clipboard: by bitorbit – 3.25
Waiting: by Plugin Builders – 0.5
WooCommerce AdWords Conversion Tracking: by Wolf+Bär Agency – 1.4.7
WooCommerce Product Add-ons: by WooCommerce – 2.8.1 – 2.9.0 is available – Not tested with the active version of WooCommerce
WooCommerce FedEx Shipping: by WooCommerce – 3.4.5 – 3.4.9 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 5.7.1
WP Dashboard Notes: by Jeroen Sormani – 1.0.8.2
WP Rocket: by WP Media – 2.10.11.1
WP Sitemap Page: by Tony Archambeau – 1.6
WP Smush Pro: by WPMU DEV – 2.7.6
WP User Avatar: by flippercode – 2.0.8
WPMU DEV Dashboard: by WPMU DEV – 4.4
YouTube Pro: by EmbedPlus Team – 11.8.3.2

Thank you, Greg



Thank You,

Greg Robertson

Owner 517 Design

321.243.2152

greg@517design.com

http://517design.com


[1467456149333_517designlogo-160x160.jpg]

________________________________
