### ISSUE TITLE
Clicking on Page During Initial Setup Results in Error

### ISSUE THREAD

**Issue by TravelingAdMan** [facebookincubator/facebook-for-woocommerce#1472]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
On initial setup when coming to "Confirm settings" in the modal if I try to change "Facebook Page" an error occurs: "Oops, something went wrong."

I have tried multiple browsers and the same results.

##🚶‍♀️ Steps to reproduce

1. The first step
1. The next step… 

## ✔️ Expected behavior
Be able to change to other than first resulting Facebook Page that it defaults to.

**Comment by lgfogle** [comment]
Hey @TravelingAdMan,

Thanks for reaching out! The Facebook team recently made some updates on their end that may have resolved this issue - could you please try connecting again and let me know if you're still encountering this issue?

Thank you!
Lindsey

**Comment by TravelingAdMan** [comment]
Hi Lindsey,

Just tried again and still have the same issue.  I had also turned off all
plugins except woocommerce and the Facebook plugin.

Screenshot attached.

Tried from my phone but guessing result will be the same as on Desktop.

Thanks,

Jon

**Comment by lgfogle** [comment]
Hey @TravelingAdMan,

Thanks for following up! The Facebook team is continuing to work to resolve these issues - to help with their research, would you be willing to share the email address associated with your Facebook account? You can use a [QuickForget](https://quickforget.com/) link to share your address. This will let the Facebook team look at the logs from your specific connection attempt.

Thank you!
Lindsey

**Comment by TravelingAdMan** [comment]
https://quickforget.com/s/729a9823c700e592e1bf2b53163534bc02217b9c793bf9c5

**Comment by lgfogle** [comment]
Got it! My apologies for not following up sooner. Thank you so much, @TravelingAdMan.

I will pass this information along to Facebook and follow up once I know more! Please don't hesitate to reach out with other questions in the meantime, and thank you for your patience.

**Comment by lgfogle** [comment]
Hey @TravelingAdMan,

The Facebook team recently made some updates that they believe may have fixed this issue. Could you please try connecting again and let me know how it goes?

Thank you,
Lindsey

**Comment by TravelingAdMan** [comment]
Hi Lindsey,

Yes! The application now works as expected. Thank you for your help.

Jon

**Comment by lgfogle** [comment]
Hey @TravelingAdMan,

Excellent! I'm going to close this out. Please don't hesitate to reach out again if you need anything else.

Cheers,
Lindsey
