### ISSUE TITLE
Using Custom Prices

### ISSUE THREAD

**Issue by serhatcolak** [facebookincubator/facebook-for-woocommerce#1473]
We’re happy to help with this question! Our support team works in our help desk rather than GitHub, though, so please use one of the following tools instead:

## 📖 Read documentation

The [Facebook for WooCommerce documentation](https://docs.woocommerce.com/document/facebook-for-woocommerce/) will help you set up the extension, use its features, and answer frequently asked questions. 

## 👩‍💻 Check forums

The [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) let you review other user questions and issues and learn what worked for them. 

## 🗣 Contact support

Our support team would be happy to help answer your questions! [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)

**Comment by lgfogle** [comment]
Hey @serhatcolak,

Thanks for reaching out! I see that you've also gotten in touch with our team via support (HS #141492, for internal reference), so I'm going to close this issue so they can assist further.

Thank you!
Lindsey

**Comment by helgatheviking** [comment]
@serhatcolak Did you find a solution to that? I have a custom product type that probably needs a custom price sent to FB.
