### ISSUE TITLE
Product images and variations not correctly imported for variable products

### ISSUE THREAD

**Issue by lourenco-cunha** [facebookincubator/facebook-for-woocommerce#15]
i'm having issues importing variable products.
 
For any variable product with variation attribute (type Select) set to "any" its values are not imported. On fb store the attribute does not display any values.

Attributes and values are all defined globally, at attributes management page.

Gallery images aren't imported too

WC version v3.1.1
WP version v4.8
FB for WooCommerce v1.4.3
 
# Products 50
Types: simple and variable (simple products are ok)

**Comment by mengyingdu** [comment]
Hi, I have set up global attributes, type 'select' and set variable product. Everything works correct on fb. Have you update your product ? And select 'visible on facebook' button? (under product attribute step) 

Upload screen shot. Let me know if this still can't work for you.[
![attributes](https://user-images.githubusercontent.com/24535640/30358118-66322614-97f7-11e7-888c-f84bbc2d9a18.jpeg)
![fb page](https://user-images.githubusercontent.com/24535640/30358117-66320026-97f7-11e7-88fb-14f312035e7e.jpeg)
![product attribute set up](https://user-images.githubusercontent.com/24535640/30358119-6633113c-97f7-11e7-92e4-ff5510630a41.jpeg)
![product setting](https://user-images.githubusercontent.com/24535640/30358120-66333dce-97f7-11e7-8c96-6f462ab06806.jpeg)



](url)

**Comment by mengyingdu** [comment]
We've fixed this issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.

**Comment by lourenco-cunha** [comment]
Hi, the issue happens when attribute value is "Any". I'll chek the new version.
