### ISSUE TITLE
Compatibility Issue : Problem with Flex Slider

### ISSUE THREAD

**Issue by rirgang** [facebookincubator/facebook-for-woocommerce#150]
When update to latest version 1.6.6 it causes conflict with the flex slider plugin. Only the second image is uploaded into the store's products at woocommerce.

Disabling the facebbok plugin is back to normal.

This problem did not occur in the previous version.

**Comment by rirgang** [comment]
One suggestion, I do not know if this is the place but it would be interesting to let you choose the images that you want to synchronize during the setup, since facebook leaves everything square it does not make sense to load 4 images.

**Comment by sammul** [comment]
Hi, thanks for reporting the issue, can you tell us what version were you on previously so that we can check what have been changed?
Thanks

**Comment by rirgang** [comment]
Hi
Thanks for response.
On version 1.6.5 the conflict not appears.

**Comment by dmitridr** [comment]
Thanks for confirming the issue. I guess I would recommend sticking with 1.6.5 for now until the compatibility issue can be resolved.
