### ISSUE TITLE
Same Description for all Variations + Bulk Edit Plugin

### ISSUE THREAD

**Issue by rirgang** [facebookincubator/facebook-for-woocommerce#151]
Other Problem

All variations are displaying the same product description. In my case I inform the size in the description and when selecting any of the variations the size is always the same.

He seems to pick up and fix the first variation processed.

Att
Rudimar

**Comment by sammul** [comment]
Hi Rudimar, are you talking about the products imported to Facebook side? 
I assume you are already on the latest version of the plugin as you said in other issue reporting. 
Can you share us your Facebook page url or pixel id so that we can look at your product catalog?
Can you also share with us a screenshot on your side so that we can try to repro this?
Thanks

**Comment by rirgang** [comment]
Thanks sammul
The page is https://www.facebook.com/santhatela/shop/
the product has 4 size variations. the description in the store is different for each one, but on facebook only one.
I deactivated the plugin momentarily because it is causing problems with the galleries and sliders, the theme uses the flex slider, but this I already commented on another issue

**Comment by mengyingdu** [comment]
Hi rirgang,

This is a bug for Facebook page shop and I have already flagged this to our shop team. 

If you go the product item from your Woo panel, click on each product item id on the right side, you can see the correct variation description. However, if you go through your Facebook shop->click on a product group -> change variation selection, the product url doesn't update. We will try our best to collaborate with shop team to fix this, unfortunately I don't have the estimated time for now.

At the meanwhile, I would suggestion that you could use the 'Facebook Description' to set up a general description in you Facebook Shop, and if the shopper click on the checkout, they will go to either the product page on your website (which has detailed description) or your add_to_cart (depending on your shop setting).

Thanks.

**Comment by mengyingdu** [comment]
Upload the screenshot if it helps you find it:
![facebook description](https://user-images.githubusercontent.com/24535640/33353542-3259739e-d463-11e7-827f-010772c6a256.jpeg)

**Comment by rirgang** [comment]
Thanks for the tip @mengyingdu , we have more problems here. I used a bulk editor to have a generic description for all products.

When doing the sync continues taking the description of the variation. If you have already done the sync and go modify the facebook description in the product, it updates on facebook

Another very annoying problem is that when doing the sync everything gets very slow at its beginning and my server is good ... (server 8 core + 16GB + HD SSD, WP 2GB Limit). So if you realize that you have to change something (or like in my case that did not change the description) and want to stop the process can not do anything.

I do not know if it would be a big problem to have a stop button or abort sync.

Well, I gave up momentarily, I'll wait for the anger to pass and try again another day.

**Comment by mengyingdu** [comment]
Hi @rirgang ,

It seems you mentioned 2 problems here, let's divide them:
1. When saying 'bulk editor', is that a WooCommerce plugin? Or the built-in WooCommerce Bulk Edit in 'all product' page?
2. sync slow down: Did it happen when you sync all products or just one product?

Thanks.

**Comment by rirgang** [comment]
Hi @mengyingdu 

The bulk editor is a premium plugin. I've edited all the descriptions, I have left the same for all products ... check out the store details bla bla bla ... hehehe

The description appeared correctly on the products, I was careful to make sure everything was correct.

Then delete the settings and start a new feed for facebook. But it still shows the description of the variation and not the text that I put in the parent product ....

The slowness is always in the initial part of the batch, the server hangs (or almost) and is in the initial synchronization (it happens also if it forces new synchronization).

As I saw it did not work, I edited a product and changed the description. Then appeared the message new product created ... and the number. I checked and it was correct.

I sent him to make a new feed now, complettly new, but I still continue with the description of the variation, unique for all variations .... funny that it randomly picks up, I believe it is in the order of the first variation.

Sorry for the long text and my bad english

Regards

**Comment by mengyingdu** [comment]
Hi @rirgang ,

Currently, there is incompatibility issue with bulk editor plugin (similar #95 #70 #141 ) before.
My [commit](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L204) last week should support Woo builtin bulk edit, however, we may release new version 2 weeks later (due to internal policy).

Can you try to download plugin from github (not release page), or change the code manually if you can? Then force resync? Let me whether it fixed your problem.

Thanks.

**Comment by mengyingdu** [comment]
Hi, 
We included all fixes and updates in [v1.7.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.4). Can you upgrade and try it?

**Comment by mengyingdu** [comment]
Hi @rirgang ,

Update for some good news: Facebook shop team has fixed the variant update bugs now. So if you change your choice for variant value, the description will update as you set in Woo Product page. (If you use different description under different variation)

**Comment by dmitridr** [comment]
Closing this out. If this issue re-occurs, please open a new issue and reference this one!
