### ISSUE TITLE
Why does Facebook for WooCommerce not like WP_DEBUG?

### ISSUE THREAD

**Issue by lvl99** [facebookincubator/facebook-for-woocommerce#152]
I'm developing my site on localhost and require the usage of WP_DEBUG to ensure no errors are present (or to track down what errors are) and Facebook for WooCommerce is [ucking with my shi](https://www.youtube.com/watch?v=Bqxnm6t3QMw).

Namely, I'm trying to create a filter to prevent translated products with WPML syncing with FB. In order to test my filter I'm attempting to debug the sync process, but because I have the debug on the FB for WC plugin doesn't run or is not accessible to start the sync to test with.

**Comment by lvl99** [comment]
Is there any way to debug what information gets set to Facebook without actually sending information?

**Comment by dmitridr** [comment]
Hi,

Sorry for the delay in replying. You should be able to use WP_DEBUG as long as WP_DEBUG_DISPLAY is disabled. In fact, this is the setting we use on our test servers to test the plugin before releasing it.

We'd be happy to review your pull request for such a filter.

To answer your other comment : you can comment out [the _get and _post methods here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbgraph.php#L36) and replace it with a log to a local PHP file.
