### ISSUE TITLE
Connection Issue - Oops something went wrong

### ISSUE THREAD

**Issue by ksimms77** [facebookincubator/facebook-for-woocommerce#1521]
## 🔎 Isolate the bug

- [X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

I follow all of the steps and check all the required boxes and it doesn't want to connect. I've deleted the plugin and reinstalled, updated all plugins.....doesn't work. 

##🚶‍♀️ Steps to reproduce

1. The first step...simply just go through all of the prompts on setting up plugin to reproduce...nothing customized. 
1. The next step… 

## ✔️ Expected behavior

Should connect
![-26-Log-in-With-Facebook (1)](https://user-images.githubusercontent.com/70476466/91660702-58e30d80-eaa5-11ea-9bb3-416f62d4f299.png)
![-26-Log-in-With-Facebook (2)](https://user-images.githubusercontent.com/70476466/91660704-58e30d80-eaa5-11ea-872e-eca246b793e0.png)
![-26-Log-in-With-Facebook (3)](https://user-images.githubusercontent.com/70476466/91660705-597ba400-eaa5-11ea-9931-c48851c8037a.png)
![-26-Log-in-With-Facebook](https://user-images.githubusercontent.com/70476466/91660706-597ba400-eaa5-11ea-9f9d-63d467604359.png)

**Comment by lgfogle** [comment]
Hey @ksimms77,

Thanks for reaching out! I'm very sorry about this connection issue. The Facebook team is working to resolve these issues - to help with their research, would you be willing to share the email address associated with your Facebook account? You can use a [QuickForget](https://quickforget.com/) link to share your address. This will let the Facebook team look at the logs from your specific connection attempt.

Thank you!
Lindsey

**Comment by ksimms77** [comment]
Sure, here’s a quick forget link: 
https://quickforget.com/s/657820966df9d77598e1cef5c726a15a8b098bd5f73b87c8

**Comment by lgfogle** [comment]
Got it! Thank you so much, @ksimms77 . I've gone ahead and viewed the secret enough times that it's been forgotten.

I will pass this information along to Facebook and follow up once I know more! Please don't hesitate to reach out with other questions in the meantime, and thank you for your patience.

**Comment by sandrodz** [comment]
I cannot connect my store also, I get same error.
#1529 seems to be related.

**Comment by lgfogle** [comment]
Hey @sandrodz,

Thanks for reaching out! Would you also be willing to share the **email address used for your Facebook account** and your **Business Manager ID**? You can find the Business Manager ID by going to the [Business Manager](https://business.facebook.com/), selecting the business you want to connect to, and checking the URL for the `business_id=` value.

You can use a [QuickForget](www.quickforget.com) link to share this information. This will let the Facebook team look at the logs from your specific connection attempt.

@ksimms77, would you also mind sharing your **Business Manager ID** as well? Facebook mentioned that might help speed up their troubleshooting.

Thank you!
Lindsey

**Comment by sandrodz** [comment]
> Hey @sandrodz,
> 
> Thanks for reaching out! Would you also be willing to share the **email address used for your Facebook account** and your **Business Manager ID**? You can find the Business Manager ID by going to the [Business Manager](https://business.facebook.com/), selecting the business you want to connect to, and checking the URL for the `business_id=` value.
> 
> You can use a [QuickForget](www.quickforget.com) link to share this information. This will let the Facebook team look at the logs from your specific connection attempt.
> 
> @ksimms77, would you also mind sharing your **Business Manager ID** as well? Facebook mentioned that might help speed up their troubleshooting.
> 
> Thank you!
> Lindsey

https://quickforget.com/s/27823772cb6ed4fc776e060c0aaf3b3b152a5d87b07d3854

I was hoping 2.0.1 would resolve it, but no, it is still not connecting.

**Comment by lgfogle** [comment]
Hey @sandrodz and @ksimms77,

The Facebook team recently made some updates that they believe may have fixed this issue. Could you please try connecting again and let me know how it goes?

Thank you,
Lindsey

**Comment by sandrodz** [comment]
> Hey @sandrodz and @ksimms77,
> 
> The Facebook team recently made some updates that they believe may have fixed this issue. Could you please try connecting again and let me know how it goes?
> 
> Thank you,
> Lindsey

Hi, it still doesn't connect. 2.0.2 did not fix my issue :(

**Comment by auludag** [comment]
I have still the same issue.

**Comment by ksimms77** [comment]
Didn’t work me me either. Had to rollback to a previous version which works

**Comment by ahmadssb** [comment]
I had multiple update for the plugin since this issue occurs , no updates has solved this issue yet  

![image](https://user-images.githubusercontent.com/4236683/94994094-2180e880-059e-11eb-9510-914433939717.png)


currently I had to update the category using Product Feed plugin

**Comment by ahmadssb** [comment]
For those who has this issue , I found this solution and it worked with me :
https://wordpress.org/support/topic/error-connect-to-facebool/#post-13439968

in case it tooks so long to update the date on the link , make the change from database directly 

![image](https://user-images.githubusercontent.com/4236683/95012274-ffd83d80-063f-11eb-86d6-779308952e33.png)


![image](https://user-images.githubusercontent.com/4236683/95012297-29916480-0640-11eb-90c7-9b9db13a5ff2.png)

**Comment by ksimms77** [comment]
Updated plugin, it’s now connected successfully to site. Thank you.

**Comment by simonporter007** [comment]
Hi all!

There has been quite a few changes Facebook has made to the connection process that should have solved the majority of errors we've seen reported to our support team. Most of these connection issues aren't something that we can resolve in the plugin itself, though thanks so much for contacting us so we could report these to the Facebook team and help get them solved!

I'll close this reported issue now as there aren't any required changes to the plugin. However, if you are still encountering connection problems, please do reach out to our [support team on the forums](https://wordpress.org/plugins/facebook-for-woocommerce/) so they can assist further!

Cheers,

**Comment by tim1mw** [comment]
I've been having this problem as well and have now given up on the new plugin and re-installed the old one which "just worked".

**Comment by josespinal** [comment]
Having this issue right now. All is updated.

**Comment by omahlegend0111** [comment]
Utterly frustrated and upset as my business account remains inaccessible. All Thanks to, Chloe _ consultant on I. G. for her invaluable techniques and procedures, and wholeheartedly assisting me with my account recovery. her quick actions and meticulous attention to detail were exemplary. Having someone as capable and supportive as Chloe, guiding me through the whole process was truly appreciated. I highly recommend Chloe , for professional service. 
Email- Chloe.consultant1@Gmail . com 
Insta-Chloe _ consultant
