### ISSUE TITLE
Facebook for Woocommerce error?

### ISSUE THREAD

**Issue by Titosmucki** [facebookincubator/facebook-for-woocommerce#1536]
Hi guys,

I recently got my new woocommerce webshop online. Trying to get my products back on facebook, I get the following error message:

Facebook for WooCommerce error:
Unsupported post request. Object with ID '709051843270010' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

Doing some research and contacting Facebook Support, they told me I would need a GTIN Number or a brand for my products. But, I don't know. Buying GTIN number for each product seems to be far too complicated and expensive. I cant imagine all people are doing it. Other solution would be to add a brand-field. I still don't really get it.

Im sure I'm not the first one with this issue. 

Can you tell me how to solve it?

Thank you very much

**Comment by Titosmucki** [comment]
Hey guys,
anyone able to help or at least point me in the right direction?

**Comment by simonporter007** [comment]
Hey @Titosmucki,

Thanks for reaching out!

This sounds like an issue that our support team would be best suited to help troubleshoot. Could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Simon
