### ISSUE TITLE
Ability to customise product attribute fields

### ISSUE THREAD

**Issue by lvl99** [facebookincubator/facebook-for-woocommerce#154]
I have the "gender" of products available in a differently named attribute field. Rather than having to rename my product attribute taxonomy across all products, would it be possible to put in a filter to change the name of the attribute that the `WC_Facebookcommerce_Integration` looks for?

**Comment by sammul** [comment]
Hey, I'll mark this as a feature request and to see if this is a common case for a lot of users. Thanks for reporting.

**Comment by dmitridr** [comment]
Hey,

There's already a filter you can try using on all the product data. You would have to hook into this filter and set the gender param according to your custom configuration.

It was added #135 

Hope that helps!
If it doesn't, please consider sending us a pull request to add a filter for the gender attribute. We are more than happy to review.

**Comment by lvl99** [comment]
Thanks @sammul and @dmitridr 

I have been using the filter in #135 for setting the gender and hiding non-EN versions of the products (setting the visibility to "staging"). Now I'm trying to see if there's a way to add some custom information like setting the language for a product.

**Comment by mengyingdu** [comment]
Thanks for your update! Please create a new issue and reference this one if the problem persists.
