### ISSUE TITLE
Variable products

### ISSUE THREAD

**Issue by moduca** [facebookincubator/facebook-for-woocommerce#155]
When I synchronized all my products, not all pictures from variable products were uploaded to Facebook, and I am pretty sure I have set a a custom picture to each variation in woocommerce.

**Comment by mengyingdu** [comment]
Hi,

Which version are you currently using? 
There's a checkbox after v1.6.4 to choose whether using parent image on Facebook when you edit the published product. Please note this checkbox only appears in case of variable product when you edit a 'published' product. I have attached the screen shot to make it more clear.
![use parent image](https://user-images.githubusercontent.com/24535640/33046382-8f5d063c-ce05-11e7-9d37-4642934df620.jpeg)

**Comment by mengyingdu** [comment]
On the other hand, for variable product, if you set customized image in variation, we will use it by default when you publish the first time. (the checkbox not shown for the first time draft -> publish).
I confirmed with testing variable product in latest version. Can you try upgrade plugin ?

Let me know whether it works.

Thanks.

**Comment by mengyingdu** [comment]
Hi, 
The new version should support customized image for variable products. I close this issue for now, let me know if you still have problem about this.

**Comment by mengyingdu** [comment]
related to #151 
This is a shop bug, if go through FB shop->change variation value selection->pop up window not update picture/price/variant description
