### ISSUE TITLE
Feature Request: Use Facebook Checkout

### ISSUE THREAD

**Issue by perrochon** [facebookincubator/facebook-for-woocommerce#156]
Feature Requests (this may just be documentation requests)
1) Use Facebook Checkout. Right now it sends me back to WC, but I'd like to check out on Facebook
2) Edit on Facebook. 
Both of these are tricky, because of inventory management/sync, but simple solutions may enable some use cases.

**Comment by mengyingdu** [comment]
Hi,

Thanks for your creative suggestion.
1. Facebook checkout: It's an interesting idea which may need more support from our payment team and we will consider it based on requests priority. Actually, there are some Woo site owners have already felt current checkout redirect to add_to_cart kind of crazy since they believed that shoppers need more time to decide whether to buy and pay. Would you mind tell what kind of products are you selling?
2. edit on Facebook: It's also a novel idea. Currently, we sync products from Woo to Facebook, rather than Facebook to Woo.  We will consider it on our roadmap based on feature request priority.

Again, thanks.

**Comment by perrochon** [comment]
On 1. My wife is selling textile art, bags, quilts, textile jewelry, etc.
Everything handmade and uniquely made in the US. The desire to get them to
the merchant site, with up- and cross-sell is of course in conflict with
avoiding shopping cart abandonment and getting a sale done with minimal
friction. If a Facebook user trusts Facebook, and especially if they
already have a payment instrument in Facebook, then "Buy" right there would
be a nice option (in addition to "Check out on Website"). Maybe that action
could be configurable, with the default as it is right now.

On 2. Inventory control/adding orders back into WC is needed if it can sell
on Facebook. That is tricky enough. Editing anything in the listing on
either WC or FB and syncing back and forth will be significantly more
complex.

**Comment by mengyingdu** [comment]
Thanks for your feedback and suggestion.

**Comment by mengyingdu** [comment]
Hi @perrochon ,

I have some update from shop team. 
1. They used to test onsite checkout on page shop, however, they found the feature didn't bring persuasive business outcome for the business. 
2. They are testing on onsite checkout on marketplace checkout now where is the focus of Facebook as next ecomm online transaction place.

Asks from some feedback:
1. Did you try to run business on marketplace?
2. What's your thoughts in terms of business outcome from 2 places? preference?

Thanks.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
