### ISSUE TITLE
Facebook connection problem

### ISSUE THREAD

**Issue by rcoronado** [facebookincubator/facebook-for-woocommerce#1561]
Hi, i can not connect to Facebook through woocommerce plugins.

I am getting below error:

“Missing Required Information From Developer
There are missing information required to setup the connection correctly. Please reach out to the developer for more information.”

Can anyone help me to resolve the issue?

**Comment by hetulk** [comment]
I am having a similar issue and not matter what I try its stuck there..

I have removed the app and the catalog from Facebook Business... I have also truncated 4 actionscheduler tables nothing seem to work.

**Comment by connectbesocial** [comment]
I am also having this issue and haven't been able to find help anywhere. It's so frustrating.

**Comment by simonporter007** [comment]
Hi @rcoronado, @hetulk , and @connectbesocial!

Thanks for reporting this issue. The Facebook team has investigated the error and added a fix to their connection process last week that should resolve the problem. I would recommend trying to reconnect now as that should hopefully allow you to get past this error message!

If you're still encountering trouble connecting, this sounds like an issue that our support team would be best suited to help troubleshoot. Could you please reach out to [our team on the Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Cheers!

Simon
