### ISSUE TITLE
Force Product Resync with External/Affiliate product

### ISSUE THREAD

**Issue by trungpc** [facebookincubator/facebook-for-woocommerce#157]
Hi,

I want to Product Resync with External/Affiliate product and facebook checkout to referal link like this https://prnt.sc/hcoo0u

<img src="https://image.prntscr.com/image/8YbXQj5xSyWMMW26pELPPg.jpg">
How I can get that?

Thanks, plz!

**Comment by mengyingdu** [comment]
Hi,

I sent a fix to enable external product and it will be added in the new release (after 28th Nov). You can also update product individually in product editor rather than sync all products after that.

Thanks.

**Comment by trungpc** [comment]
thanks you very much!

**Comment by mengyingdu** [comment]
Hi,

Version [1.7.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.0) is released which added a lot of features/fixes, can you upgrade?
