### ISSUE TITLE
No add - to - cart event triggered.

### ISSUE THREAD

**Issue by sionking** [facebookincubator/facebook-for-woocommerce#1578]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Once any product is added to cart it does not show any event site is www.drywild.co.il

##🚶‍♀️ Steps to reproduce
add to cart, check with pixel helper, all other events triggered .

## ✔️ Expected behavior
Trigger add to cart event

Please check www.drywild.co.il
NOTE: Check redirect to cart in WOOCOMMERCE will trigger the add-to-cart.

**Comment by simonporter007** [comment]
Hi @sionking!

Thanks for writing in with your issue. We're not aware of any current reported problem with AddToCart with the default theme Storefront, or TwentyTwenty, for our plugin. Can you confirm you have seen the issue with either of these themes active and only WooCommerce and Facebook for WooCommerce active too?

If you are only seeing this issue when your custom theme is active, this sounds like an issue that our support team would be best suited to help troubleshoot. Could you please reach out to [our team on the Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Cheers!

Simon
