### ISSUE TITLE
Product Catalog Missing

### ISSUE THREAD

**Issue by Elena88BG** [facebookincubator/facebook-for-woocommerce#158]
Hi there!

We're trying to create a set of dynamic ads for remarketing on Facebook. The store is successfully connected via the Facebook for Woocommerce plugin app and the products show up on the Facebook page, but when we try to create a Product Catalogue Sales campaign it says "Your business needs to create a product catalog or connect to the catalog of another business."

Could you please let us know if there is anything else we need to do to use dynamic ads? We were advised by WooCommerce to reach out here, providing the following info:

Facebook Page URL: https://business.facebook.com/shaveclubfinland
WordPress and WooCommerce version number: Version 4.9 and Version 3.2.4
Facebook Plugin version number: Version 1.6.4
How many products you have: 608 
What kind of customization plugins you're using (if any)? None

Thanks in advance, please let me know if there's something else I can provide you with!

Elena

**Comment by mengyingdu** [comment]
Hi,

I check remote log and database for you. It seems you have 2 catalog (one maybe created before setting up our plugin).
Can you try this catalog id (replace the catalog id with this one in your url)? 148351665684781 
Let me know whether it works. I can delete this comments later if you feel it's confidential.

Thanks.

**Comment by Elena88BG** [comment]
It worked, thank you!
