### ISSUE TITLE
Plugin is not working anymore

### ISSUE THREAD

**Issue by BBarbadoSS** [facebookincubator/facebook-for-woocommerce#16]
Hi there,

The plugin is not working anymore. It's all configured but my products are gone at my Facebook page, tried to reconnect and deleted it all but none of it worked.

**Comment by tahoff** [comment]
This was resolved in v1.4.5

**Comment by BBarbadoSS** [comment]
Please fix this asap since my business from Facebook is zero  now!

**Comment by tahoff** [comment]
Can you provide more information and/or send screenshots? Specifically, can you send a screenshot of the extension page and send us your store's URL?

**Comment by BBarbadoSS** [comment]
I installed the plugin, did the installation and the products are showing up in my Business Manager at Facebook but not at my Facebook page shop.

Facebook page: http://facebook.com/marcshopnl/shop
Settings in Wordpress: [http://imgur.com/a/sQmJP](http://imgur.com/a/sQmJP)
Facebook pixel in the Business Manager: [http://imgur.com/t1wUuh7](http://imgur.com/t1wUuh7)
Business Manager: [http://imgur.com/jz4GYpe](http://imgur.com/jz4GYpe)
Source of my website showing the right pixel [http://imgur.com/p3V7OG6](http://imgur.com/p3V7OG6)

**Comment by tahoff** [comment]
When you go through the setup, you need to ensure that the option to create a shop is selected on the final step of the setup flow. The last time you completed the flow, it was not selected.

**Comment by BBarbadoSS** [comment]
Where is that option?
[](http://imgur.com/n0PV2iC)

**Comment by dmitridr** [comment]
The option only appears during setup. You will have to reset (via Advanced Options) and go through setup again to see it. It will appear on the last page 'Your Products'.

**Comment by dmitridr** [comment]
I'm closing this issue since we seem to have resolved the problem. Please re-open this if I am mistaken.
