### ISSUE TITLE
Connect to multiple facebook pages

### ISSUE THREAD

**Issue by emmieanna** [facebookincubator/facebook-for-woocommerce#160]
Wondering how I can connect the WooCommerce Facebook extension to more than one facebook page please. My WooCommerce store covers quite a few facebook pages and need to propogate my products (the same or possibly different) on multiple facebook pages. 
I hope that makes sense.
Thank you!
Emmie

**Comment by mengyingdu** [comment]
Hi,

Currently, one store can only connect to one Facebook page. It's consistent with our product sync progress. It seems you have customized request for your store. Will your multiple Facebook pages sell different product?

**Comment by emmieanna** [comment]
Mostly the same products actually. But really what ever is easiest to be able to have on multiple facebook pages for now.

**Comment by mengyingdu** [comment]
Hi,

Thanks for your explanation. Unfortunately, with current backend design one store can only connect to one Facebook page. The original idea for this set-up is: it's reasonable to own and manage one Facebook official page to represent their business.

**Comment by emmieanna** [comment]
is there any kind of code that can allow for multiple pages?

**Comment by mengyingdu** [comment]
Yeah there's a trick, but no way to update or change those products after doing the trick.

**Comment by PatilPrathamesh** [comment]
@mengyingdu can you share this trick

**Comment by emmieanna** [comment]
@mengyingdu Is there any way to connect to multiple pages yet?

**Comment by AndresBillini** [comment]
Hello can I connect multiple WooCommerce Stores to a same Facebook Fan Page?

**Comment by jeffceriello** [comment]
I also need to connect one store to multiple Facebook pages. Same products. Is this still not available?

**Comment by emmieanna** [comment]
I really wish someone would respond to this... 
It seems like there's a need.
However even though Facebook is the developer of this plugin, they don't support it or respond or take any sort of responsibility.

**Comment by thadeu220** [comment]
me and my business model require the same... we also need to sync new products, to the pages
