### ISSUE TITLE
AddToCart Event is being triggered twice

### ISSUE THREAD

**Issue by flymke** [facebookincubator/facebook-for-woocommerce#1614]
## 🔎 Isolate the bug

- [ x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ x ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
When you have activated the option "woocommerce_cart_redirect_after_add" the AddToCart Event is being triggered twice: 1. on the product page and 2. on the cart page

##🚶‍♀️ Steps to reproduce
When you turn on the log you can see the AddToCart events and the event_source_url. The event is triggered twice.

## ✔️ Expected behavior
It should only be triggered once.

## Solution
As a quick solution I have updated the file **/facebook-commerce-events-tracker.php** in **line 62** and commented out the first AddToCart event since it will be called again in **line 69** where it says **add_action ( 'woocommerce_after_cart ...**: 
```// AddToCart events
// add_action( 'woocommerce_add_to_cart', [ $this, 'inject_add_to_cart_event' ], 40, 4 ); // commented out since it will be called again in line 69
// AddToCart while AJAX is enabled
add_action( 'woocommerce_ajax_added_to_cart', [ $this, 'add_filter_for_add_to_cart_fragments' ] );
// AddToCart while using redirect to cart page
if ( 'yes' === get_option( 'woocommerce_cart_redirect_after_add' ) ) {
	add_filter( 'woocommerce_add_to_cart_redirect', [ $this, 'set_last_product_added_to_cart_upon_redirect' ], 10, 2 );
	add_action( 'woocommerce_ajax_added_to_cart',   [ $this, 'set_last_product_added_to_cart_upon_ajax_redirect' ] );
	add_action( 'woocommerce_after_cart',           [ $this, 'inject_add_to_cart_redirect_event' ], 10, 2 ); // here the event will be triggered again
}
```

**In my eyes it should be like this:**

```// AddToCart events
add_action( 'woocommerce_ajax_added_to_cart', [ $this, 'add_filter_for_add_to_cart_fragments' ] );
if ( 'yes' === get_option( 'woocommerce_cart_redirect_after_add' ) ) {
	// AddToCart while using redirect to cart page
	add_filter( 'woocommerce_add_to_cart_redirect', [ $this, 'set_last_product_added_to_cart_upon_redirect' ], 10, 2 );
	add_action( 'woocommerce_ajax_added_to_cart',   [ $this, 'set_last_product_added_to_cart_upon_ajax_redirect' ] );
	add_action( 'woocommerce_after_cart',           [ $this, 'inject_add_to_cart_redirect_event' ], 10, 2 );
}
else {
	// AddToCart while AJAX is enabled
	add_action( 'woocommerce_add_to_cart', [ $this, 'inject_add_to_cart_event' ], 40, 4 );
}
```

**Comment by simonporter007** [comment]
Hi @flymke,

Thanks for reporting this issue! Can you please share a screenshot of your **WooCommerce** > **Settings** > **Products** screen and confirm you were testing this with a default theme in place such as Storefront or TwentyTwenty? I am not seeing the behavior you describe after enabling redirect to cart and using the Facebook Events Manager Test Tool, so I would like to make sure I am following the same steps you are taking.

My understanding is the first pixel shouldn't be triggered due to the redirect, and wouldn't be recorded until the second redirect_event. This is what I'm seeing in my test store when running Storefront with only WooCommerce and Facebook for WooCommerce active.

Cheers,

Simon.

**Comment by simonporter007** [comment]
Hey @flymke,

We haven't heard from you in a while, so let me close this issue. I hope that you were able to get this issue solved, however, if you're running into any further trouble when using the latest version of the plugin, our support team are always available to help! You can reach them on the forums here: https://wordpress.org/support/plugin/facebook-for-woocommerce/

Cheers,
