### ISSUE TITLE
Connection inactive

### ISSUE THREAD

**Issue by HugoGit39** [facebookincubator/facebook-for-woocommerce#1616]
Hi so this fb pixel is rather new to me. I downloaded the FB Woocommerce plugin and as far as I see did the settings correctly. However when I want to verify the connection it remains inactive. What do I wrong?
![image](https://user-images.githubusercontent.com/60048570/94605781-dfa02b80-0299-11eb-9607-36441b7bf11d.png)
![image](https://user-images.githubusercontent.com/60048570/94605840-f050a180-0299-11eb-9928-3bb91cb3e64f.png)

**Comment by simonporter007** [comment]
Hey @HugoGit39!

Thanks for writing in with your question!

This sounds like an issue that our support team would be best suited to help troubleshoot. Could you please reach out to [our team on the Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Cheers!

Simon
