### ISSUE TITLE
Unsupported post request. Object with ID ‘3372****8619****’ does not exist

### ISSUE THREAD

**Issue by cheapious** [facebookincubator/facebook-for-woocommerce#1619]
Hi,

I'm getting below error after updating products:

Unsupported post request. Object with ID ‘3372****8619****’ does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

Regards

**Comment by simonporter007** [comment]
Hey @cheapious,

Thanks for writing in with your question!

We've sometimes seen this occur when a product is deleted from the Facebook catalog after it was previously synced from your WooCommerce store. As the sync is only one way, and the plugin isn't aware of any manual modifications to the products once in the catalog, the request to get the current product with the API can fail. There are other scenarios when the plugin attempts to delete the product that this error might show too.

I would recommend using the meta box on the right-hand side of the screen to "_Reset Facebook metadata_" for your product, and then try to update again.

If you are still seeing the error notice appear after this, our support team would be best suited to help troubleshoot further. Could you please reach out to [our team on the Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Cheers!

Simon
