### ISSUE TITLE
Facebook created each variation of my products in a separate way. 

### ISSUE THREAD

**Issue by bledfort** [facebookincubator/facebook-for-woocommerce#162]
Hi,
After installing woocommerce plugin with facebook and syncing my products to facebook, it appears that facebook made each variation separatedly which make it look like the product is repeated so it will be hard create facebook ads. Even choosing products based on id won't work since variable product have still same ID. So what can I do?

**Comment by mengyingdu** [comment]
Hi,

Can you explain more details? Yes, each variation will be sync separately as a child of the group. So why would you think they repeated? 

Thanks

**Comment by dmitridr** [comment]
Hello,

I understand your concern but you need not worry, the way Dynamic Ads work no product within the same `product group` will appear in the same ad. Therefore only one variant of each product will appear in any ad to any user at any one time.

If you have a screenshot, that would help us understand what the specific problem is.

**Comment by mengyingdu** [comment]
Hi @bledfort ,

I think your concern about variable product has been resolved? I will close this issue now, if you have any other questions or need help for our plugin, feel free to open a new issue.

Thanks.
