### ISSUE TITLE
 Fatal error: Uncaught Error: Cannot unset string offsets

### ISSUE THREAD

**Issue by camiloq28** [facebookincubator/facebook-for-woocommerce#1621]
i get this error when installing the plugin 

SkyVerge\W\F\Lifecycle::migrate_1_9_settings()
wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php:73
SkyVerge\W\F\Lifecycle::upgrade_to_1_10_0()
wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/Lifecycle.php:284
SkyVerge\W\P\v\P\Lifecycle::upgrade()
wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php:61
SkyVerge\W\F\Lifecycle::install()
wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/Lifecycle.php:115
SkyVerge\W\P\v\P\Lifecycle::init()
wp-includes/class-wp-hook.php:287
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:311
WP_Hook::do_action()
wp-includes/plugin.php:478
do_action()
wp-settings.php:568
require_once()
wp-config.php:84
require_once()
wp-load.php:37
require_once()
wp-admin/admin.php:34
require_once()
wp-admin/plugins.php:10

**Comment by simonporter007** [comment]
Hi @camiloq28,

Thanks for writing in with your issue! Could you clarify if that was the whole of the error message you were given? When a stacktrace is printed, I would normally expect a description of the error to be printed beforehand, to say why the error has occurred, before the stack trace is then printed to show where the code was being run from that caused it.

It looks like the plugin was running through the upgrade routines when the error was caused. If you can share what that error was exactly, I'd be happy to take another look.

Cheers,

Simon.

**Comment by camiloq28** [comment]
hi simon thanks for the reply,  this is the full error, when this happens, i cant access the wordpress admin 

 Fatal error: Uncaught Error: Cannot unset string offsets
in /sites/fast.carts-19.com/files/wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php on line 179

Pila de llamadas:

SkyVerge\W\F\Lifecycle::migrate_1_9_settings()
wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php:74
SkyVerge\W\F\Lifecycle::upgrade_to_1_10_0()
wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/Lifecycle.php:284
SkyVerge\W\P\v\P\Lifecycle::upgrade()
wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php:62
SkyVerge\W\F\Lifecycle::install()
wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/Lifecycle.php:115
SkyVerge\W\P\v\P\Lifecycle::init()
wp-includes/class-wp-hook.php:287
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:311
WP_Hook::do_action()
wp-includes/plugin.php:478
do_action()
wp-settings.php:568
require_once()
wp-config.php:84
require_once()
wp-load.php:37
require_once()
wp-admin/admin.php:34
require_once()
wp-admin/plugins.php:10

**Comment by simonporter007** [comment]
Hi @camiloq28 Thanks for sharing that!

There seems to be some corruption to your existing settings, as when the plugin is attempting to migrate the data, it's not able to unset the option from the array.

As a workaround, would it be possible to show me what the value of the following options are in your database?

'fb_api_key'
'fb_product_catalog_id'
'fb_external_merchant_settings_id'
'fb_feed_id'
'facebook_jssdk_version'
'pixel_install_time'

Alternatively, if you'd like to try deleting these existing options and updating the plugin again, that may skip the migration logic and allow you to re-run through the connection process.

Could you let me know how you get on?

Cheers!

**Comment by simonporter007** [comment]
Hey @camiloq28,

We haven't heard from you in a while, so let me close this issue. I hope that you were able to get this issue solved, however, if you're running into any further trouble when using the latest version of the plugin, our support team are always available to help! You can reach them on the forums here: https://wordpress.org/support/plugin/facebook-for-woocommerce/

Cheers,

**Comment by rubenp152** [comment]
Hi @camiloq28. 
I have this error related to the above, could you help me?

Fatal error: Uncaught Error: Cannot unset string offsets in /home/dinebijo/liliumecosox.com/wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php:179 Stack trace: #0 /home/dinebijo/liliumecosox.com/wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php(74): SkyVerge\WooCommerce\Facebook\Lifecycle->migrate_1_9_settings() #1 /home/dinebijo/liliumecosox.com/wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/Lifecycle.php(301): SkyVerge\WooCommerce\Facebook\Lifecycle->upgrade_to_1_10_0('1.9.15') #2 /home/dinebijo/liliumecosox.com/wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php(62): SkyVerge\WooCommerce\PluginFramework\v5_10_0\Plugin\Lifecycle->upgrade('1.9.15') #3 /home/dinebijo/liliumecosox.com/wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/Lifecycle.php(118): SkyVerge\WooCommerce\Facebook\Lifecycle->install() #4 /home/dinebijo/liliumecosox.com/wp-includes/class-wp-hook.php(287): SkyVerge\WooComme in /home/dinebijo/liliumecosox.com/wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php on line 179
