### ISSUE TITLE
Can't connect page to woocommerce

### ISSUE THREAD

**Issue by ravenkwill** [facebookincubator/facebook-for-woocommerce#1629]
I'm trying to connect our biz page (https://www.facebook.com/flamebilyue) to our woocommerce on our new webpage. We're using Woocommerce 4.5.2 on Wordpress 5.5.1. 

We get the error message: 
Page is already associated with a Commerce Account and cannot be moved to a different Business Manager

I can't figure out what commerce account it's associated with, and how to shift this. What do I need to do to connect this facebook page with this website?

Thank you

**Comment by simonporter007** [comment]
Hi @ravenkwill,

When connecting the latest version of the plugin, we are using Facebook's latest connection application that relies on Business Manager to allow the plugin to manage the assets on your behalf. This requires the assets (page, catalog, pixel) and business, to be managed by your Facebook profile as well as all assets being owned by the same business.

It sounds like you have a page that is owned by a separate business than the one you're looking to connect to. I'm afraid I don't have any way to help you find the correct business that might own the page. I would recommend checking all possible Facebook accounts, and then navigating to Business Settings once logged into Business Manager. Here you can click the **Accounts** > **Pages** item which should show the list of Pages the business has access to. If you can find the page within the list here, clicking it should also show you who the owner is beneath the page name at the top: https://cloud.skyver.ge/ApuLAmp7

As we're not best placed to assist with business manager configuration, I would recommend reaching out to Facebook directly if you're still having problems tracking this down. You can reach them here: https://www.facebook.com/help/contact/552096935652452

Should you have issues connecting the plugin once the page is managed by the correct business, our support team would be more than happy to assist further on the [WordPress.org support forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/)!

Cheers,

Simon.
