### ISSUE TITLE
The page cannot be changed.

### ISSUE THREAD

**Issue by DamianMog** [facebookincubator/facebook-for-woocommerce#1634]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

I just can’t click on a page that was linked to before.
https://i.imgur.com/HXE6dkK.png
Before that, everything was connected properly.
##🚶‍♀️ Steps to reproduce
All steps shown at the attached link:
https://imgur.com/a/XNudf7L

## 🗃 Logs
https://pastebin.com/raw/chx7fJBZ

**Comment by simonporter007** [comment]
Hi @DamianMog!

Thanks for reaching out with your question! This part of the connection process is using Facebook's latest Facebook Business Extension API. As such, it isn't something that we can control from the plugin side. I would recommend reaching out to our support team on the forums so they can take a closer look for you, and to see if they can offer any suggestions to get connected based on other merchant's experiences so far.

You can reach the support team here: https://wordpress.org/support/plugin/facebook-for-woocommerce/

Thanks again for the question!

Cheers,
