### ISSUE TITLE
Uninstall unsuccessful because Facebook Page has been deleted

### ISSUE THREAD

**Issue by rekor-dev** [facebookincubator/facebook-for-woocommerce#1635]
Hi,

How to uninstall Facebook for Woocommerce but my Facebook Page has already been deleted ?

Thank you

**Comment by simonporter007** [comment]
Hi @rekor-dev,

Thanks for getting in touch! This sounds like an issue that our support team would be best suited to help troubleshoot. Could you please reach out to [our team on the Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Cheers!

Simon
