### ISSUE TITLE
It is not possible to exclude products, or tags to sync to facebook cataglog.

### ISSUE THREAD

**Issue by gervet** [facebookincubator/facebook-for-woocommerce#1637]
The tags and products selected to be excluded in the facebook catalog continue to appear day after day even when they have been removed from the Facebook catalog.

The exclusion of categories from the Facebook catalog works properly.

Could you check this out?

thanks

**Comment by simonporter007** [comment]
Hey @gervet,

Thanks for getting in touch about this issue! That's certainly not the default behavior we see during testing, so it would be good to dig in further to see what sync messages the plugin is generating, and if you have any other data feeds syncing product data. For instance, is there a feed file sync that might be using old data instead?

As this forum is for developers to report coding issues, our support team would be best placed to help here! You can contact them at: https://wordpress.org/support/plugin/facebook-for-woocommerce/

Cheers,
