### ISSUE TITLE
Unsupported post request. Object with ID

### ISSUE THREAD

**Issue by gerlandog** [facebookincubator/facebook-for-woocommerce#1640]
Every time I update a product in woocommerce i get this message:

Facebook for WooCommerce error:
Unsupported post request. Object with ID '3585928761435792' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

what am I doing wrong?

![image](https://user-images.githubusercontent.com/21976353/97045001-5bb12a80-154b-11eb-9e5d-3537b9814732.png)

**Comment by simonporter007** [comment]
Hi @gerlandog!

Thanks for reaching out with your question. We typically see that error message when the current product ID cannot be retrieved from your Facebook catalog. The message itself is the response that Facebook has sent back when we attempt to read in the latest values.

This can sometimes be when the product was synced previously and then deleted manually from the Facebook catalog. As the sync is only one way, the plugin and WooCommerce is not alerted to the product being deleted in Facebook. It doesn't sound like this is the case from your description, but a quick test to rule it out would be to use the "_Reset Facebook metadata_" link from the Facebook metabox on the right-hand side of the edit product screen.

If you're still seeing issues with this message appearing, our support team would be best placed to investigate this for you, as the plugin appears to be working okay if it's sending and receiving the API messages.

You can reach our support team here: https://wordpress.org/support/plugin/facebook-for-woocommerce/

Cheers!
