### ISSUE TITLE
information show on shop variations

### ISSUE THREAD

**Issue by elboy84** [facebookincubator/facebook-for-woocommerce#1648]
## Feature requests
There is a standard information in every product. However I added some extra information in some variants to complete what only related to those variants. On the facebook shop those variants in the other hand only shows the additional information without the default one. Can it be show both?

**Comment by simonporter007** [comment]
Hi @elboy84,

Thanks for the request. To make sure I understand correctly, would it be possible to share some screenshots that show the additional information, where it was added, and where it is missing from the Facebook shop page?

Cheers!

**Comment by elboy84** [comment]
here you can see that there is the general information that is shown on IMG_6187 without any additional info in that variation. 
on the other hand I added some extra info to the other variation because I need 1 or 2 days to produce that see IMG_6188. Here you can't see the general information what is the same as the other one. just this variation needed this extra info.

![IMG_6188](https://user-images.githubusercontent.com/73459928/97547554-3a7a8f00-19ce-11eb-84a0-1ead3163ba93.JPG)
![IMG_6187](https://user-images.githubusercontent.com/73459928/97547506-2d5da000-19ce-11eb-8049-162497fbd468.JPG)

**Comment by elboy84** [comment]
I noticed an other thing with the variations.. they are not the same as on my WP shop. for example here is my list of variations on my site on IMG_6190.JPG and look what shows on facebook shop. You can't even pick the parent version what is Blackberry pearl. see IMG_6186.JPG
![IMG_6186](https://user-images.githubusercontent.com/73459928/97548386-5c284600-19cf-11eb-8199-ee0a7c95fb92.JPG)

![IMG_6190](https://user-images.githubusercontent.com/73459928/97548277-356a0f80-19cf-11eb-9775-7a202f7d142f.JPG)

**Comment by elboy84** [comment]
![IMG_6189](https://user-images.githubusercontent.com/73459928/97548501-7f52f580-19cf-11eb-9884-0b7dc88e4760.JPG)
sorry you can see the facebook variations on this one. and there is not blackberry pearl

**Comment by elboy84** [comment]
here is a link to see on webshop:
https://crysteelgyor.hu/product/10-mm-es-lapos-gyongy-beszuros-fulbevalo/
facebook:
facebook.com/commerce/product/2965793073525143/

**Comment by simonporter007** [comment]
Hey @elboy84,

Thanks for sharing those details. It looks to me like you are adding to the product description which can then be synced across to Facebook. Though from your last update, I couldn't see the "made to order" text there on the WooCommerce store either.

If it is part of the product description, then that should be possible by choosing the right description being used from settings: https://cloud.skyver.ge/bLuwLBzd

There is also a Facebook product description text input field if you wanted a specific description for Facebook only. If the text is added elsewhere, either through another plugin or customization, then I'm afraid it would require additional custom code to include this in the Facebook product description before we sync the product. I'd be happy to offer some pointers for your developer resource in that case though!

Would it be possible to give the description sync a try or let me know if you'll like to pursue the custom code route further?

Cheers,

**Comment by elboy84** [comment]
I tried it, and that doesn't seem to solve the problem. :s 

![problem1 1](https://user-images.githubusercontent.com/73459928/98433775-87471f80-20ca-11eb-82c2-020181c197bc.jpg)
![problem1](https://user-images.githubusercontent.com/73459928/98433778-8ca46a00-20ca-11eb-88d5-7827cf88c258.jpg)
![problem2 1](https://user-images.githubusercontent.com/73459928/98433780-8f06c400-20ca-11eb-94d8-d65e6b83de11.jpg)
![problem2](https://user-images.githubusercontent.com/73459928/98433783-91691e00-20ca-11eb-95b0-8c87c10b463e.jpg)

**Comment by elboy84** [comment]
@simonporter007 ,
and it appears like this..
![Screenshot 2020-11-07 at 7 12 17](https://user-images.githubusercontent.com/73459928/98433809-dbea9a80-20ca-11eb-88be-08e8369bba70.jpg)

**Comment by simonporter007** [comment]
Hi @elboy84,

Thanks for sharing the screenshots! To look into this further and get a better idea of which settings are currently set for the products, and the messages the plugin is generating to sync the data, it would be great if our support team could look at your site. We've not had any other reports of the description not syncing correctly at the moment and so I think this may be related to the product settings for these products.

Please could you raise a support request <a href="https://www.skyverge.com/contact/?form_type=general" rel="noopener" target="_blank">via our support form</a>, so that the support team could reach out directly and walk through this with you? Please also feel free to link to this thread so that you don't have to re-send the screenshots here!

Cheers,
