### ISSUE TITLE
non visualizzo i prodotti inseriti su woocommerce nella mia pagina facebook

### ISSUE THREAD

**Issue by andrewr1996** [facebookincubator/facebook-for-woocommerce#1649]
una volta inseriti i prodotti nella mia pagina e-commerce mi andavano automaticamente sulla mia vetrina facebook oppure facevo una sincronizzazione manuale e me li ritrovavo.
Da un paio di giorni queste due funzioni non funzionano più e sul prodotto mi esce scritto "Questo prodotto non è ancora sincronizzato con Facebook." come faccio a risolvere questo problema?
<img width="281" alt="Schermata 2020-10-26 alle 11 00 42" src="https://user-images.githubusercontent.com/73469593/97159042-9056f900-177a-11eb-8bba-535302f6f153.png">

**Comment by simonporter007** [comment]
Hi @andrewr1996,

Thanks for getting in touch! I hope you don't mind if I reply in English, not being an Italian speaker! I can use Google Translate if you wish.

It sounds like you are having some issues syncing your products to your catalog. We don't have any outstanding issues for this at the moment, and it's working okay in our local testing. To look into this further, it would be great if you could contact our support team so they could help troubleshoot!

You can reach them here: https://wordpress.org/support/plugin/facebook-for-woocommerce/

Cheers,
