### ISSUE TITLE
Support 'no default' variant value, default show 'select XXX' in dropdown

### ISSUE THREAD

**Issue by crobertwatson** [facebookincubator/facebook-for-woocommerce#165]
I'm trying to add a WooCommerce product to Facebook using the Facebook for WooCommerce extension. When I have a product that has multi-combo variations (flavor 1 + flavor 2), the Facebook version of the product comes out looking like you see in this screenshot.

https://www.awesomescreenshot.com/image/2986991/76387913f305bf33452bdc709b83e1c4

Why aren't the flavor variations appearing in the dropdowns and how do I fix this?

Facebook Page URL: https://www.facebook.com/allisonsapiaries
WordPress and WooCommerce version number: WP 4.9, WC 3.2.5
Facebook Plugin version number: 1.6.4
Number of products: 14 
Types of products: Simple and variable
Duplicate SKUs: None
Customization plugins: None

**Comment by alexanderdejong** [comment]
Hi, I'm having the same problem as @crobertwatson. Please suggest what we can do to fix this issue on our website. Thanks.

**Comment by mengyingdu** [comment]
Hi,

This is because when you set up variable products in product editor, 'variations' tab, you select 'any' + attribute. If you select the detailed attribute value, it should appear correctly.
Let me know whether it works.

Thanks.

**Comment by crobertwatson** [comment]
I'm not sure I understand. In my case, I have a set of five different flavors for the product. The customer can choose one or both of any two flavors in that set of five. If I were to pre-select the detailed attribute value, that would mean I'd have to have a different dropdown set for each possible combination of the two flavors, including the same for each flavor. So...

Orange Blossom + Orange Blossom
Orange Blossom + Palmetto
Orange Blossom + Wild Flower
Orange Blossom + Summer Wild Flower
Orange Blossom + Holly
Palmetto + Palmetto
.
.
.
Wild Flower + Wild Flower
.
.
.
Summer Wild Flower + Summer Wild Flower
.
.
.
Holly + Holly

**Comment by mengyingdu** [comment]
Hi @crobertwatson,

Sorry for the delay response. I understand your case now and thanks for your explanation with examples. Basically, you want multiple variant **value** (combination), however, we only single value for one attribute in one variant. 

I have some workround for you: 
1. add attribute 'flavor 1' 'flavor 2' (under 'attributes' tab in woo product editor) -> add all of the flavors to each attribute
2. select 'create variants from all attribute' in 'variations' tab of Woo
3. set default value if you want

In this manner, Facebook will import each combo as you want. It looks your case is very customize, hope my suggestion can help you. 
cc @alexanderdejong 

Thanks.

**Comment by crobertwatson** [comment]
That fixed it. But it sure creates a lot of variations. 20 more than WooCommerce needed to be able to offer the combination of selections. Also, even though the default selection in WooCommerce is set to "any", the product selection dropdowns on Facebook's version of the product isn't. It has selected one each of a random different variety for each dropdown. Not the end of the world, but it would be nice to prompt the buyer to select with "Any" as the default selection. That way they don't think it's just the two pre-selected flavors.

**Comment by mengyingdu** [comment]
Hi @crobertwatson ,

Thanks for your feedback. I understand it's better have have 'no default' dropdown for your customized case. However, currently this is limited by our backend API. We will put it on our to-do-list and collaborate with other teams to enable this. Unfortunately, since we are encountering other bugs and performance enhancement request, we don't have the expected timing for this feature now.  Hope you understand.

Thanks.

**Comment by crobertwatson** [comment]
Yup. Thanks for putting that on the to-do list.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
