### ISSUE TITLE
 Error message: syntax error, unexpected ')' error line 1811

### ISSUE THREAD

**Issue by sam240** [facebookincubator/facebook-for-woocommerce#1652]
## 🔎 Isolate the bug

- [x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

An error of type E_PARSE was caused in line 1181 of the file /home/storename/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Products.php. Error message: syntax error, unexpected ')'

##🚶‍♀️ Steps to reproduce

1. The first step
1. The next step…

**Comment by telng** [comment]
It's caused by a trailing comma at the end of the line before; there's another at line 1184 and a third in ../facebook-for-woocommerce/includes/Admin/Enhanced_Catalog_Attribute_Fields.php at line 85.

**Comment by dalhoss** [comment]
Thanks i will Try , i will let you know.

**Comment by yourwebpa** [comment]
Thanks. The above fix was an error but did not fix the bug.

**Comment by sam240** [comment]
I couldn't fix the bug. I ended rolling back to the previous version. It completely broke my store. I was able to restore.

**Comment by simonporter007** [comment]
Hi all!

Thanks so much for reporting this issue. This has been fixed from release v2.1.1. If you are still seeing this issue after updating to the latest release, please do let us know!

Cheers,

**Comment by bridgetkenn** [comment]
Hi, I am getting this error message too  - E_PARSE was caused in line 1181 of the file  with facebook for woocommerce. How can I resolve this. My online shop on facebook is no longer linked. I am just a beginner programmer so any help would be appreciated. thank you.

**Comment by yourwebpa** [comment]
The plugin update solved my issue, so I cant offer any help im afraid. Good luck

**Comment by bizysoftindia** [comment]
> Hi, I am getting this error message too - E_PARSE was caused in line 1181 of the file with facebook for woocommerce. How can I resolve this. My online shop on facebook is no longer linked. I am just a beginner programmer so any help would be appreciated. thank you.

Hi bridgetkenn

I am a beginner and also getting the same error

Following steps will resolve the issue.

Step 1 => Login your hosting cpanel and find the folder "facebook-for-woocommerce"

http://prntscr.com/vmpdmn

Step 2 => find the page "Products.php" and open in inbuild editor in cpanel => go to line number 1162

http://prntscr.com/vmpkfz

after the login uninstall the plugin its worked for me.
