### ISSUE TITLE
Syntax Errors in new facebook-for-woocommerce plugin update

### ISSUE THREAD

**Issue by ChandreTeclogix** [facebookincubator/facebook-for-woocommerce#1654]
The following Syntax Errors were noted:

**When trying to access the website**
..wp-content/plugins/facebook-for-woocommerce/includes/Products.php
Line 1181 & 1184 - syntax error, unexpected ')'

**When trying to access wp-admin**
..wp-content/plugins/facebook-for-woocommerce/includes/Admin/Enhanced_Catalog_Attribute_Fields.php
Line 85 - syntax error, unexpected ')'

**Comment by mateusz-szafraniec** [comment]
Duplicate of #1652
