### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by StratHost3ss** [facebookincubator/facebook-for-woocommerce#1657]
The error received is:

An error of type E_PARSE was caused in line 1181 of the file /home/showtime/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Products.php. Error message: syntax error, unexpected ')'

please comment

**Comment by sam240** [comment]
Duplicate of [#1652](https://github.com/facebookincubator/facebook-for-woocommerce/issues/1652)
