### ISSUE TITLE
Remaining products count goes negative and drops database

### ISSUE THREAD

**Issue by sillyonthestreet** [facebookincubator/facebook-for-woocommerce#166]
I have the latest version of WordPress with the latest version of WooCommerce and the latest (1.6.6) version of the Facebook for WooCommerce plugin. 

I have 197 published products in my store. I tried syncing them, and part of them did get synced, but the count of remaining products goes negative (-xx). Then it drops my MySQL server as I guess it overloads it. I need to restart my MySQL server after that and it goes back to normal until I force a re-sync and the issue appears again.

So how do I fix or bypass this? Not all of my products got synced after 2 attempts that resulted in a database crash. 

I already checked the similar issue where you say this is fixed, but it's not. At least not for me.
https://github.com/facebookincubator/facebook-for-woocommerce/issues/116

My issue is related to an overloaded database, not overloaded CPU. I'm using a KVM VPS, not shared hosting.

When starting the sync process, I get this error in my server logs:

> The WC_Product::get_variation_description function is deprecated since version 3.0

I also noticed descriptions don't get scraped into my Facebook shop. And you use that function here https://github.com/facebookincubator/facebook-for-woocommerce/blob/03b14741214c486d60d580de4022dd4ac3ddd240/includes/fbproduct.php which is apparently deprecated.

**Comment by mengyingdu** [comment]
Hi,

Thanks for your self-investigation and sorry to hear about that. I will look into your issue now.
1. I will solve the deprecated function issue.
2. Can you tell me you store url or Facebook page ?I want to confirm whether your site has some other reason to cause this minus problem.

Thanks.

**Comment by sillyonthestreet** [comment]
Store URL: https://www.facebook.com/MariaPinoWorld/shop/
While I'm at it, I also don't get the option to invite people that liked/reacted to my posts. Only an "Add friend" option. It happens on that page only.

**Comment by mengyingdu** [comment]
Hi,

1. As for your problem about description, if it is a variable product, it should be related to issue #151 
2. I didn't find other problems from remote log.

**Comment by mengyingdu** [comment]
Hi,

1. We fix the deprecated function call in new release (should be this week) . If your store is treating warnings like errors, that could be why it's not syncing and DB too many reads.
2. As for your page 'invite' option, it's an issue with pages, and we can't really help much because it's not an issue with the woo plugin. I will flag this problem to page team, and just to confirm that the option you mentioned this one? If not, can you upload a screenshot from your other page for this option?
![invite people to liek](https://user-images.githubusercontent.com/24535640/33394132-3dc57d0c-d4f6-11e7-8d26-6092a3fb85a3.jpeg)


Thanks.

**Comment by sillyonthestreet** [comment]
1. I just noticed the error somewhere in the logs, it's not related to the DB overload.
2. The invite people option is not the one from your screenshot. It's the option when you click on the reactions for any post
So I get this:
https://imgur.com/a/mhGQM
And I should be getting this:
https://imgur.com/a/RodA4

**Comment by mengyingdu** [comment]
Thanks for your screen shot.
How many fans does the page have? This feature gets removed once a page surpasses a certain fan count.

Thanks.

**Comment by mengyingdu** [comment]
Update:

I have checked our policy that: there is both a page level and user level limit on number of invites sent per day which prevents spam and abuse. So I think this is the reason you can't see this option on this page.

Thanks.

**Comment by mengyingdu** [comment]
Hi,

Version [1.7.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.0) is released which added a lot of features/fixes, can you upgrade?

I will close this issue for now, if you still have the problem, feel free to re-open it and let me know.
