### ISSUE TITLE
Form error after last update on 28-10-2020

### ISSUE THREAD

**Issue by MRTRALHA** [facebookincubator/facebook-for-woocommerce#1662]
Hello,

After the last update to the facebook for woocommerce plug-in, the Auctions plug-in we have from wpinstitut.com and other forms we have when adding a product stopped showing calendar icons and the buttons stopped working. After disabling the facebook plug in everything was ok again.

The only way to get it working with the plug-in is copy an already made product that was working and the form is ok.

I am attaching a file with both examples.

[New product.pdf](https://github.com/facebookincubator/facebook-for-woocommerce/files/5448777/New.product.pdf)

**Comment by simonporter007** [comment]
Hi @MRTRALHA,

We've recently fixed an issue that involved images on the edit product screen being broken due to a JavaScript error. This sounds like it could be related.

Could you please try uploading to the latest version 2.1.2 and let me know if you are still seeing the issue?

Cheers,

**Comment by MRTRALHA** [comment]
Hi, problem solved! Version 2.1.2 solves the issue no more errors. File in attach with complete form and working.

[FB ok.docx](https://github.com/facebookincubator/facebook-for-woocommerce/files/5454987/FB.ok.docx)
