### ISSUE TITLE
Versions >2.1.0 break refunding orders in Woocommerce

### ISSUE THREAD

**Issue by tatusah** [facebookincubator/facebook-for-woocommerce#1664]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Trying to refund orders in Woocommerce gives error notice "Remote ID for parent order not found." and refund for the order fails.

##🚶‍♀️ Steps to reproduce
Try to create a refund for an order (order that's not created through Instagram or Facebook) in the Woocommerce backend.

## ✔️ Expected behavior
This Facebook plugin should not break the Woocommerce core functionality of refunding orders.

**Comment by ashucg** [comment]
In my case the refund went through but my client got confused because of the error message and issued the refund 3 times, I have explained it [in the support forum](https://wordpress.org/support/topic/could-not-refund-checkout-order-remote-id-for-parent-order-not-found-2/).

**Comment by heavestudio** [comment]
same here...

**Comment by tatusah** [comment]
Version 2.1.3 gives a temporary fix by not loading the offending methods.
