### ISSUE TITLE
How to check catalog product match rate in Facebook?

### ISSUE THREAD

**Issue by jigneshdp1493** [facebookincubator/facebook-for-woocommerce#167]
Hello There,

I want to know the step by step for checking catalog product match rate in Facebook.

Thank in Advance :)

**Comment by jieminz22** [comment]
Hi,

You should be able to find it on your Product Catalog page Event tab: https://www.facebook.com/products/catalogs/<catalog-id>/events

**Comment by dmitridr** [comment]
Closing this since it seems the question was answered? Feel free to open a new issue and reference this one if there is a follow up question!
