### ISSUE TITLE
STUCK ON SYNC

### ISSUE THREAD

**Issue by alexiskrauss** [facebookincubator/facebook-for-woocommerce#1678]
## 🔎 Isolate the bug

- [yes ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ yes] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

I've been trying to connect my Woocommerce products to Facebook for HOURS now. It's stuck on sync - nothing is happening. This app is atrociously bad. 

![FB not importing](https://user-images.githubusercontent.com/73724770/97765675-0479ff80-1ae1-11eb-8787-83af6b1bd1ba.jpg)

##🚶‍♀️ Steps to reproduce

1. The first step
1. The next step…

**Comment by simonporter007** [comment]
Hi @alexiskrauss,

Thanks for getting in touch, and I'm sorry to hear that the plugin isn't correctly syncing your products! We're using the API sync for your products in the latest version, though your screenshot looks to be of the catalog using a feed file sync. Our support team would be best placed to assist you with checking why this might be!

You can reach out to our support team in the forums for general support: https://wordpress.org/support/plugin/facebook-for-woocommerce/

To kick start their investigation, I'd also recommend letting them know what version of the plugin you have installed, and if you encountered any issues during the connection process.

Thanks again for your question, and I hope they can take a closer look for you soon!

Cheers,
