### ISSUE TITLE
Span tag not stripped from title

### ISSUE THREAD

**Issue by popforce** [facebookincubator/facebook-for-woocommerce#168]
A span tag used in the title of a product in woocommerce shows as plain text in the facebook shop and does not get stripped as intended.

**Comment by jieminz22** [comment]
Hi,

We've noticed this and will fix the issue in the next version. Meanwhile you can take a look at this similar one https://github.com/facebookincubator/facebook-for-woocommerce/issues/161. 

Thanks.

**Comment by popforce** [comment]
Thank you.
