### ISSUE TITLE
Facebook Tracking Pixel

### ISSUE THREAD

**Issue by activate2020** [facebookincubator/facebook-for-woocommerce#1684]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Receiving this error when the FB pixel plug in is installed on the site! 
![image](https://user-images.githubusercontent.com/74022286/98294333-691bdb00-1f75-11eb-96c3-39a8d0bb0e77.png)

##🚶‍♀️ Steps to reproduce

## ✔️ Expected behavior
Should be able to load the site with the pixel placed.

**Comment by simonporter007** [comment]
Hey @activate2020,

Thanks so much for writing in! We're not seeing any common reports for this error when the plugin is activated, and I'm not able to reproduce this issue locally with a fresh install on a new up to date site. The HTTP 500 error would seem like there is an error being thrown when the plugin is active, and so it could be a conflict with another plugin or custom theme code.

To look into this further, please reach out to our support team who would be best placed to assist: https://wordpress.org/support/plugin/facebook-for-woocommerce/ as they can then walk through the steps to gather the fatal error logs and offer suggestions for further troubleshooting and suggestions.

Cheers!
