### ISSUE TITLE
WooCommerce not syncing to FB shop

### ISSUE THREAD

**Issue by bwohn65** [facebookincubator/facebook-for-woocommerce#170]
This was just working, but now when I enter a new product (or pull up one that worked previously), the FaceBook "SHOP" isn't posting (or even on the page anymore). When I publish a new product it does post it to my FB PAGE, but not to the FB SHOP - and that worked fine yesterday. The FaceBook ID on the right side-bar isn't there either.

I'm now getting the message: "Facebook for WooCommerce is almost ready. To complete your configuration, complete the setup steps"

When I click on it, it takes me to the STEPS, but, says: "A Facebook Page can only be connected to one store at a time. Hammerhead Woodworks is already in use by another WooCommerce store. You can remove the existing connection to use the Page for this store, or you can select a different Page."

Any ideas whats wrong?

Also, I just added the WooCommerce Subscriptions and all are up to date.

Info:
http://facebook.com/hammerheadwoodworks
WooCommerce v 3.2.5
WordPress v 4.9
I have 30-40 products, all Simple or Variable
No Dupe Sku's
And using YOU Theme - no customization

Again, its been working fine, and I didn't add any plugins, just stopped working.

Thank you!!

**Comment by jieminz22** [comment]
Hi,

Have you ever completed the setup steps? This message means that we detect Hammerhead Woodworks is connected to a WooCommerce store already. Have you been through the setup steps already?

**Comment by bwohn65** [comment]
Hi, yes, I went through all the steps months ago and been working fine. Now I get this message and if I try to walk-thru again, it says its already connected. Do I un-connect it and re-connect it? Didn't want to break anything.

**Comment by jieminz22** [comment]
Hi,

Did you recently update your DB on Woo? It seems the system can't detect the settings for Facebook shop on Woo anymore. To fix the issue, you can go ahead un-connect and re-connect it. If you have existing ads running against the catalog it has created, pause it before you re-setup.

**Comment by bwohn65** [comment]
That worked! I just didn’t want to unlink until I knew it was ok… thanks SO much, working again :)

Brian




-----
