### ISSUE TITLE
Variable subscription product not displaying

### ISSUE THREAD

**Issue by Runstat** [facebookincubator/facebook-for-woocommerce#172]
Hi 

I have installed the FB pixel and setup the plugin as per instructions. The WooCommerce product syncs correctly and the pixel is activated etc. However, the products do not show up in the Facebook shop. 

For the time being, I have switched off the shop as part of the set-up/ manually uploaded the products to the page, otherwise I will be without a shop while it's resolved.

It's mentioned in a separate issue that you will support variable subscriptions for general use #73 - is this the case? 

Thanks

**Details**
Facebook Page URL: https://business.facebook.com/shedotspace/?business_id=526543891039000
WordPress and WooCommerce version number: 4.9 & 3.2.5
Facebook Plugin version number: 1.6.6
How many products you have: 1
Types of products (i.e. anything besides simple/variable products won’t work): variable subscription
Do you have Duplicate SKUs in your system?: No
What kind of customization plugins you're using (if any)? None

**Comment by jieminz22** [comment]
Hi,

Sorry we don't support variable subscription product at this moment. We will prioritize it based on user demands.

**Comment by mengyingdu** [comment]
Hi @Runstat ,

We have basic support for variable subscription products in latest [commit](https://github.com/facebookincubator/facebook-for-woocommerce/commit/2a12f7d6d8bac86421879166fb87fb451fbe07c4) which will be included in the next release. If you are eager to try, you can just download from clone zip file.

Thanks.

**Comment by mengyingdu** [comment]
Hi, 
We included all fixes and updates in [v1.7.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.4). Can you upgrade and try it?

**Comment by tahoff** [comment]
Closing, please reopen if this issue comes up again.

**Comment by t22james** [comment]
Hey there,
Am on v1.7.5 (with WP 4.9.1, WC 3.2.6) and am still experiencing issues with variable subscriptions...

We have 4 subscription products- 2 are simple subscriptions, and these are loading fine. 2 others are variable, and are not displaying in FB, and the links provided in woocommerce do not resolve. for example, as at time of writing, the following IDs/links are not resolving to FB, and just resolve to a page saying "Sorry, this content isn't available at the moment":

```
Facebook ID: 1722016611194194
Variant IDs:
39632 : 1820427154657711
7399 : 1816294565110737
7398 : 2249647065061304
9070 : 1384083325036954
```

I've tried resetting metadata on the products, and have also run a full force re-sync, with no luck.

facebook store link:
https://www.facebook.com/pg/Wildernessmag/shop/?cid=1956667264582764&ref=page_internal

**Comment by t22james** [comment]
ok, so after an hour of waiting, the IDs/links finally did start resolving to actual facebook links in the FB shop. This would be good to document perhaps inside Woocommerce, in the links panel, advising users that just because the links are displaying in WC doesnt mean they are active yet on FB, and to please wait an hour or two.

However, there is a new problem where the two variable subscriptions are not displaying in the "subscriptions" area of the FB shop:
https://www.facebook.com/pg/Wildernessmag/shop/?cid=1956667264582764&ref=page_internal

and they also arn't showing that they have variations...
