### ISSUE TITLE
Something went wrong when connecting to Facebook!

### ISSUE THREAD

**Issue by NovelTeaKelsea** [facebookincubator/facebook-for-woocommerce#1731]
When trying to set up Facebook for Woocommerce I keep getting an error page "Something went wrong when connecting to Facebook." I dont know why this keeps happening. I have tried many things already. Ma you please help?

**Comment by jconroy** [comment]
Check out our docs https://docs.woocommerce.com/document/facebook-for-woocommerce/#faq-oops-something-went-wrong

For general help and support going forward please check out
* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)
