### ISSUE TITLE
Option to disable messenger chat to be automatically open when a user enters the website

### ISSUE THREAD

**Issue by studiojpeg** [facebookincubator/facebook-for-woocommerce#1739]
## Feature requests

If you have an idea for how we could improve Facebook for WooCommerce, please let us know by [contacting our support team](https://woocommerce.com/my-account/create-a-ticket/)! We'd love to learn more about the problem you're facing and how Facebook for WooCommerce could help solve it.

## Developers

We welcome your contributions. 🙌 Here are a few tips to help us work together:

- If you submit a new PR, please ensure the description explains why the change is needed, follows WordPress coding standards, is compatible with PHP 5.6, and contains a small changeset — PRs with massive changesets are likely to be rejected or asked for revisions, as they’re much harder to review for potential issues.
- If you’d like to propose a more substantial changeset, feel free to start a discussion of why and the proposed implementation in this issue! Giving our team a heads up increases the likelihood of changes being accepted quickly.
- Internet points are available for PRs that include test coverage! 🏆 💯 Especially failing + passing tests for bug fixes.

**Comment by jconroy** [comment]
Feature requests can be added to the ideas board here https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=398356
