### ISSUE TITLE
Facebook URL Invalid

### ISSUE THREAD

**Issue by Daniel22092000** [facebookincubator/facebook-for-woocommerce#1744]
Hello guys, is it possible if somebody of you could help me? My facebook ad account says that my URL is invalid. I havent done something wrong, the problem just started right away. I cant be running ads or promoting them. Some of my store posts on facebook got deleted to. Its impossible to find my site through facebook, cause my URL is invalid, and i dont know why? Can someone please help me. i really need help, its impossible to contact facebook to. 

BTW: my store name is: Alltimeshomes.com

**Comment by jconroy** [comment]
Hi @Daniel22092000 

Sorry to hear of your difficulties. Unfortunately this isn't a facebook ads support channel.

I'd recommend contacting facebook ads support direct https://www.facebook.com/business/help

For WooCommerce / Facebook for WooCommerce specific help the best places to get general support are
* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)
