### ISSUE TITLE
Readme.txt is out of date. 

### ISSUE THREAD

**Issue by automattic-ian** [facebookincubator/facebook-for-woocommerce#1747]
## 🔎 Isolate the bug

- [ x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Readme.txt mentions only Tested up to: 5.5.3 which results in the following warning when attempting to install Facebook for WooCommerce on WordPress 5.6: 

This plugin has not been tested with your current version of WordPress.

It also shows a flag in the Repository: 
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/33329175/103917319-69eafd80-50db-11eb-8586-b39fc6bed615.png">

##🚶‍♀️ Steps to reproduce

1. Attempt to install Facebook for WooCommerce while using WordPress 5.6
2 see warning about `This plugin has not been tested with your current version of WordPress.
`

## ✔️ Expected behavior
As presumably this is tested the latest version of WordPress with releases, steps should be taken to ensure the public knows that. 

Suggested fix: update readme.txt: https://github.com/facebookincubator/facebook-for-woocommerce/blob/1bde61409078a9da73ebc072479b3e3fa01644a8/readme.txt#L5 

to read Tested up to: 5.6

**Comment by jconroy** [comment]
Fixed with latest version I believe

**Comment by automattic-ian** [comment]
Thanks @jconroy!
