### ISSUE TITLE
Unsupported post request. Object with ID xxxxxx etc etc

### ISSUE THREAD

**Issue by richard-osborne** [facebookincubator/facebook-for-woocommerce#1748]
Hi,
I've tried Googling this error and it's led me here. I'm unable to find which product is the one causing this issue as searching fo the ID xxxxxx in Woocommerce doesn't return any results, and trying to search for it in the Facebook catalog doesn't either. Also contemplated deleting everything from Facebook and starting but really really want to avoid that. Ff could trace the product effected and just delete or resync that one would be fine, but don't know what happened or what product.

All was working fine and no errors, and I know not very helpful but then this error appeared to randomly pop up in the Wordpress/Woocommerce admin area for no specific reason, could be adding a product or editing a page, or just loading into the admin area. My wife and I, as it's her site, don't recall making any changes to anything before this started happening.

A post on Wordpress forums suggest I format the post here as follows;

1. Facebook Page URL
https://www.facebook.com/TheFairyRetreat

2. WordPress and WooCommerce version number
Wordpress 5.6 / WC 4.8.0

3. Facebook Plugin version number
2.2.0

4. How many products you have
114

5. Types of products (i.e. anything besides simple/variable products won’t work)
Mainly standard products with only a handful of variable products (different colour of same product)

6. Do you have Duplicate SKUs in your system?
Not that we are aware of, no.

7. What kind of customization plugins you’re using (if any)?
Using a Theme purchased from ThemeForest (called Gift Shop). Has been live for about 3 months without any issues, did not install the Dokan plugin that came with it as not needed, but using rest as out the box.

**Comment by jconroy** [comment]
Hi @richard-osborne 

Some recommendations/info on that here https://github.com/facebookincubator/facebook-for-woocommerce/issues/1640#issuecomment-718057002

For additional help the e best places to go are
* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)
