### ISSUE TITLE
Pixel deletion

### ISSUE THREAD

**Issue by ShopNorthTexas** [facebookincubator/facebook-for-woocommerce#175]
My goal in this is to link my WooCommerce with my business account for Shop North Texas rather than my personal. (see screenshot)
<img width="703" alt="screen shot 2017-11-30 at 9 55 31 pm" src="https://user-images.githubusercontent.com/34149771/33467330-61a7ad02-d619-11e7-83fd-332f922fd654.png">

Initially, I set up my business page with a different email from the one associated with my personal Facebook page. This seemed to result in my inability to do so, so I added another Admin in the business page, deleted myself, and sent my original email address an invite and changed myself to Admin. Since this didn't work, I went ahead and added a new user to my website (the person I added as an Admin on the business page) and then I got this message: 
![screen shot 2017-11-30 at 10 00 12 pm](https://user-images.githubusercontent.com/34149771/33467428-02b77416-d61a-11e7-8bda-0bb46392c9e6.png)

So, I'm kinda stuck since there's not a simple drop-down to just delete a pixel. I don't understand why - it seems so logical, but please help. I'd like to avoid deleting the entire page and waiting 14 days to recreate it, as I'm looking to start marketing the page sooner than that. 

Thanks for your help.

**Comment by ShopNorthTexas** [comment]
If the user is an Admin, would they not have complete access?

**Comment by ShopNorthTexas** [comment]
There's also a pixel registered under my personal Ad account, and two pixels created under the business account. I'm also not seeing my page in search results either logged in to personal, another account, or incognito on Google. Really confused by this one...

Please help.

**Comment by dmitridr** [comment]
Hi, 

If you are seeing this message, you are logged in as a user who has multiple ad accounts, and none of those ad accounts have a pixel attached to them. If these are personal (non-business) ad accounts, you could go into the account and create a pixel, that should resolve the issue.

If these are business ad accounts, you can probably resolve this by assigning the pixel to the ad account through Business Manager as described in #164.
