### ISSUE TITLE
Some os cadastro de produto no Woocommerce e imagem no celular fica com problema

### ISSUE THREAD

**Issue by tiagopele** [facebookincubator/facebook-for-woocommerce#1750]
Bom o plugin sincroniza etc tudo tranquilo o problema é:  produtos novos  você não consegui cadastrar, descrição, imagem etc

E via celular as imagens ao entrar no produto fica em branco a mesma.

**Comment by jconroy** [comment]
Hi @tiagopele 

Sorry to hear of your difficulties.

The best places to get support is via

* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)
