### ISSUE TITLE
marketplace sale 

### ISSUE THREAD

**Issue by Chester34** [facebookincubator/facebook-for-woocommerce#1753]
Hello guys…Two questions please – 1) i have an auto dealership business page that doesn’t have the manage inventory function or vehicle listing tab – how can I make that appear? the other two auto dealership pages that I own have it so I’m not sure what the issue is. 2) when I try to list vehicles on the other two auto dealership pages under the vehicles tab, it only lets me list under my personal profile, not the business page – is there a way to change this? … i m need shopify , ecommerce ,woocommerce , API or what? i pay if need . Thanks

**Comment by jconroy** [comment]
Hi @Chester34 

The best places to get general support for this is
* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)
