### ISSUE TITLE
Failed to reconnect

### ISSUE THREAD

**Issue by rafalilloblanco** [facebookincubator/facebook-for-woocommerce#1754]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
I have cloned a website with Duplicator. I have everything configured on my new website with the new data. The problem is that when I try to reconnect the account, it tells me that I have to ask permission from the businner manager assigned to the cloned website.

![image](https://user-images.githubusercontent.com/17000368/105694607-6f30b080-5f01-11eb-9833-d15b3bade382.png)
![image](https://user-images.githubusercontent.com/17000368/105694740-92f3f680-5f01-11eb-8921-6a5fdbf21cb3.png)
![image](https://user-images.githubusercontent.com/17000368/105694875-b9b22d00-5f01-11eb-8f99-fa4c13dfc4d6.png)

##🚶‍♀️ Steps to reproduce
1. Click reconnect
2. Continue as "my facebook username"
3. Error

## ✔️ Expected behavior
It should let me connect to my current business manager account where my new website is assigned.

## 🗃 Logs
`
### WordPress Environment ###

WordPress address (URL): https://kanabhome.es
Site address (URL): https://kanabhome.es
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.25
PHP Post Max Size: 256 MB
PHP Time Limit: 0
PHP Max Input Vars: 10000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 10.2.36-MariaDB-cll-lve
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: mb_
Tamaño total de la base de datos: 16.84MB
Tamaño de los datos de la base de datos: 15.57MB
Tamaño del índice de la base de datos: 1.27MB
mb_woocommerce_sessions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
mb_woocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_order_items: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_order_itemmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_tax_rates: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_actionscheduler_actions: Datos: 0.20MB + Índice: 0.09MB + Motor MyISAM
mb_actionscheduler_claims: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_actionscheduler_groups: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
mb_actionscheduler_logs: Datos: 0.14MB + Índice: 0.10MB + Motor MyISAM
mb_ajaxsearchpro: Datos: 0.03MB + Índice: 0.00MB + Motor MyISAM
mb_ajaxsearchpro_priorities: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_ajaxsearchpro_statistics: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_asp_index: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_asp_synonyms: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_cartflows_ca_cart_abandonment: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
mb_cartflows_ca_email_history: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_cartflows_ca_email_templates: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_cartflows_ca_email_templates_meta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_cli_scripts: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_commentmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_comments: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_duplicator_packages: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_jet_reviews: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_jet_review_comments: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_jet_review_meta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_jet_review_types: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_jet_widgets_styles: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_links: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_options: Datos: 3.35MB + Índice: 0.18MB + Motor MyISAM
mb_pmxe_exports: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_pmxe_google_cats: Datos: 0.26MB + Índice: 0.05MB + Motor MyISAM
mb_pmxe_posts: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_pmxe_templates: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_postmeta: Datos: 8.70MB + Índice: 0.42MB + Motor MyISAM
mb_posts: Datos: 2.47MB + Índice: 0.14MB + Motor MyISAM
mb_shortpixel_folders: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_shortpixel_meta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_smush_dir_images: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_termmeta: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
mb_terms: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
mb_term_relationships: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
mb_term_taxonomy: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
mb_usermeta: Datos: 0.04MB + Índice: 0.01MB + Motor MyISAM
mb_users: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
mb_wcpdf_invoice_number: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_wc_admin_notes: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
mb_wc_admin_note_actions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_wc_category_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_wc_customer_lookup: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
mb_wc_download_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_wc_order_coupon_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_wc_order_product_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_wc_order_stats: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_wc_order_tax_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor MyISAM
mb_wc_reserved_stock: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_wc_tax_rate_classes: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
mb_wc_webhooks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_wpforms_tasks_meta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_yoast_indexable: Datos: 0.32MB + Índice: 0.10MB + Motor MyISAM
mb_yoast_indexable_hierarchy: Datos: 0.00MB + Índice: 0.02MB + Motor MyISAM
mb_yoast_migrations: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
mb_yoast_primary_term: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
mb_yoast_prominent_words: Datos: 0.01MB + Índice: 0.02MB + Motor MyISAM
mb_yoast_seo_links: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM

### Post Type Counts ###

astra-advanced-hook: 1
attachment: 479
cartflows_flow: 2
cartflows_step: 4
custom_css: 4
customize_changeset: 26
elementor_library: 5
elementor-hf: 2
nav_menu_item: 19
oembed_cache: 25
page: 12
product: 40
product_variation: 178
revision: 427
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Akismet Anti-Spam: por Automattic – 4.1.8
Astra Pro: por Brainstorm Force – 2.7.3
Better Search Replace: por Delicious Brains – 1.3.4
Classic Editor: por WordPress Contributors – 1.6
Conditional Payments for WooCommerce: por Lauri Karisola / WooElements.com – 2.2.2
Fuentes personalizadas: por Brainstorm Force – 1.2.6
Duplicate Page: por mndpsingh287 – 4.3
Duplicator: por Snap Creek – 1.3.40.1
Elementor Pro: por Elementor.com – 3.0.9
Elementor: por Elementor.com – 3.0.16
Pixel Cat Lite: por Apps Fatcat – 2.5.5
Facebook for WooCommerce: por Facebook – 2.2.0
Go Live Update Urls: por OnPoint Plugins – 6.3.0
Elementor - Header, Footer & Blocks: por Brainstorm Force
Nikhil Chavan – 1.5.4

JetBlocks For Elementor: por Crocoblock – 1.2.7
JetElements For Elementor: por Crocoblock – 2.5.3
JetMenu: por Crocoblock – 2.0.8
JetReviews For Elementor: por Crocoblock – 2.0.2
JetSearch For Elementor: por Crocoblock – 2.1.9
JetThemeCore: por Crocoblock – 1.2.1
JetWooBuilder For Elementor: por Crocoblock – 1.7.4
JetProductGallery For Elementor: por Crocoblock – 1.1.9
Salert: por WPoperation – 1.1.6 – Versión instalada no está probada con la versión activa de WooCommerce 4.0
ShortPixel Image Optimizer: por ShortPixel – 4.21.1
WooCommerce Dynamic Pricing & Discounts: por RightPress – 2.3.9
WooCommerce Cart Abandonment Recovery: por CartFlows Inc – 1.2.9
Stripe For WooCommerce: por Payment Plugins
support@paymentplugins.com – 3.2.11

WooCommerce Google Analytics Integration: por WooCommerce – 1.5.0
WooCommerce Pay for Payment: por Karolína Vyskočilová – 2.0.17
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 2.7.4
WooCommerce Product Add-ons: por WooCommerce – 3.2.0
Woo Visual Attributes Swatches: por ORION – 1.4.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.0
WooCommerce: por Automattic – 4.9.0 (la actualización a la versión 4.9.1 está disponible)
Yoast SEO Premium: por Equipo Yoast – 15.3
WP All Export: por Soflyy – 1.2.7
WP Rocket: por WP Media – 3.7.5
YITH WooCommerce Order Tracking: por YITH – 1.2.22

### Inactive Plugins (7) ###

Disable Right Click For WP: por Aftab Muni – 1.1.6
Facebook for WooCommerce: por Facebook – 1.11.4
GDPR Cookie Consent: por WebToffee – 1.9.5
JetStyleManager: por Crocoblock – 1.0.0-beta
Poptin: por Poptin – 1.2.1
SEO Optimized Images Business With WooCommerce: por priyanshu.mittal – 1.5.5 – Versión instalada no está probada con la versión activa de WooCommerce 4.0
Slider Revolution: por ThemePunch – 6.3.3

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #38 - /tienda/
Carrito: #39 - /carrito/
Finalizar compra: #40 - /finalizar-compra/
Mi cuenta: #41 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Astra Child
Version: 1.0.0
Author URL: http://wpastra.com/about/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 3.0.1
Parent Theme Author URL: https://wpastra.com/about/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completo: 648
Oldest: 2020-12-26 02:03:54 +0000
Newest: 2021-01-25 09:51:38 +0000

Pendiente: 2
Oldest: 2021-01-25 22:50:52 +0000
Newest: 2021-01-25 23:59:00 +0000

`

**Comment by ariefiantofadli** [comment]
Have you try this step?

https://docs.woocommerce.com/document/facebook-for-woocommerce/facebook-for-woocommerce-uninstall-plugin-and-remove-woocommerce-facebook-app/

I have the same case with you, and tried step above, but still give me same error.

**Comment by rafalilloblanco** [comment]
It worked. Thank you very much.
