### ISSUE TITLE
"Hello" shown in main woocommerce product category

### ISSUE THREAD

**Issue by mircobabini** [facebookincubator/facebook-for-woocommerce#1758]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
A useless "HELLO" string is shown in product category edit page:
<img width="715" alt="Screenshot 2021-01-31 at 16 39 33" src="https://user-images.githubusercontent.com/636911/106389533-f9868200-63e3-11eb-8e21-cd01426d37f2.png">

This is because of: https://github.com/facebookincubator/facebook-for-woocommerce/blob/1bde61409078a9da73ebc072479b3e3fa01644a8/includes/Admin/Product_Categories.php#L287

##🚶‍♀️ Steps to reproduce

1. Install WooCommerce
1. Install Facebook for WooCommerce
1. Check the main product category edit page

## ✔️ Expected behavior
No useless strings around.

**Comment by jconroy** [comment]
Will be fixed in the next release https://github.com/facebookincubator/facebook-for-woocommerce/pull/1719
