### ISSUE TITLE
Missing same variation on facebook catalog after synch

### ISSUE THREAD

**Issue by kampiamodikuesto** [facebookincubator/facebook-for-woocommerce#1759]
is there a way to check/debug this problem?

I have 12 product (type product variation) and each of them have nine variation. In particular this nine variation are the same for each of twelve product. After synchronization from facebook i can see all twelve product but each of them have only seven variation and in all product the two missing variation are the same. I can’t find no special problem on the debug file and in the csv (under wp-content/uploads/facebook_for_woocommerce/product_catalog_00f24c90bd090a79b306b1e4dc4a78fc.csv)

it’s a vary strange thing. are there a limit of 7 variations for a product in facabook?

All product are real product, not virtual.
All have the Facebook Sync setting set to “Sync and show in catalog”.
All products belong to a category and there isn't a tag that’s excluded from sync in the WooCommerce > Facebook > Product Sync settings.

some question posted here: https://wordpress.org/support/topic/missing-same-variation-on-facebook-catalog-after-synch/

**Comment by pixelicous** [comment]
For me none of the variation images are being synced.
I have attribute color and from that attribute variations are created.
The sync and show in catalaog is shown on all of them, i cannot reset facebook data on the right column of the product page because it is not syncing.

THe only items which have no problem syncing are those without variations.
Using latest wordpress/woocommerce/facebook integration

**Comment by jconroy** [comment]
Hi @kampiamodikuesto 

Sorry to hear of your difficulties

> are there a limit of 7 variations for a product in facebook?

Not that I am aware of. I'm only aware of a 100 variant limit when creating products manually https://www.facebook.com/business/help/2256580051262113?id=725943027795860

> debug file

There is a specific FB debug file that can be enabled on the main plugin settings page https://docs.woocommerce.com/document/facebook-for-woocommerce/#debug

![Screen Shot 2021-02-18 at 10 44 22 am](https://user-images.githubusercontent.com/355014/108285104-5a7ccb00-71d6-11eb-87ca-9b0991d71f24.png)

That creates debug files within /wp-content/uploads/wc-logs which are viewable within the WP dashboard page under WooCommerce > Status > Logs

If you haven't done so already I'd recommend enabling that and see if there are any errors when the variations are trying to be synced. I'd also recommend just checking for general PHP errors.

> it’s a vary strange thing.

Indeed. In my experience in most situations, there is almost always something small in the configuration affecting things. I can only suggest checking things like stock levels, product visibility and making sure everything matches as expected with the other variations that are syncing. Is there anything at all different about those variations besides a few tweaked attributes? (are those attributes all correctly set or is there something slightly off with the attribute).

---

The best place for support is definitely the forums https://wordpress.org/support/topic/missing-same-variation-on-facebook-catalog-after-synch/  or contacting Woo support directly if you are a paid customer https://woocommerce.com/my-account/create-a-ticket/
