### ISSUE TITLE
Feature request: play nice with WPML

### ISSUE THREAD

**Issue by lvl99** [facebookincubator/facebook-for-woocommerce#176]
WPML has a [wpml-config.xml](https://wpml.org/documentation/support/language-configuration-files/) format which might be a good idea to support.

The other thing is because I use WPML to manage products in two languages (EN and FR) that the FB for WC plugin tries to synchronise all products, not just of one language. I've made a quickfix where I've forced non-EN products' visibility to `staging`:

```php
/**
 * Prepare the product data for FB WC integration
 *
 * @param array $product_data
 * @param int $product_id
 * @return array
 */
function mytheme_fb_for_wc_integration_prepare_product ( $product_data, $product_id )
{
  $wc_product = wc_get_product( $product_id );

  // Only if WPML is installed...
  if ( defined( 'ICL_LANGUAGE_CODE' ) )
  {
    // Set the visibility to false if not in the default lang
    $default_lang = apply_filters( 'wpml_default_language', ICL_LANGUAGE_CODE );
    $default_lang_object_id = icl_object_id( $wc_product->get_id(), 'product', TRUE, $default_lang );

    // If not default language product, set visibility to 'staging'
    if ( $product_id !== $default_lang_object_id )
    {
      $product_data['visibility'] = 'staging';
    }
  }

  return $product_data;
}
add_filter( 'facebook_for_woocommerce_integration_prepare_product', 'mytheme_fb_for_wc_integration_prepare_product', 10, 2 );

/**
 * Define this function only if the FB for WC and WPML is active
 */
if ( class_exists( 'WC_Facebook_Product' ) && defined( 'ICL_LANGUAGE_CODE' ) )
{
  /**
   * Ensure when using Facebook for WooCommerce that it syncs only products in default language (EN)
   *
   * @param null $value
   * @param $object_id
   * @param $meta_key
   * @returns mixed
   */
  function mytheme_fb_for_wc_product_visible_only_for_default_lang ( $value = null, $object_id, $meta_key )
  {
    // Fire only if getting custom Facebook for WooCommerce metadata
    if ( $meta_key === WC_Facebook_Product::FB_VISIBILITY )
    {
      $product = wc_get_product( $object_id );
      $default_lang = apply_filters( 'wpml_default_language', ICL_LANGUAGE_CODE );
      $default_lang_object_id = icl_object_id( $object_id, 'product', TRUE, $default_lang );

      if ( $default_lang_object_id !== $object_id )
      {
        return FALSE;
      }
    }

    // Return the given metadata value
    return $value;
  }
  add_filter( 'get_post_metadata', 'mytheme_fb_for_wc_product_visible_only_for_default_lang', 10, 3 );
  add_filter( 'update_post_metadata', 'mytheme_fb_for_wc_product_visible_only_for_default_lang', 10, 3 );
}
```

I had a look at the Graph API and noticed that there is is an `og:locale` value to set a Graph object's locale, however I'm unsure how to attribute that within the product's data before sending via the REST API.

Ideally it would be great to have this so that we can advertise our products to the different language markets.

**Comment by jieminz22** [comment]
Hello,

Given that we're dealing with a high volume of bugs, we unfortunately won't get to these feature requests for a long time to come, even though we'd like to. However, we'd be happy to review any pull request to add this functionality, please consider sending us one!

**Comment by dmitridr** [comment]
Hello, thanks for writing in. We're aware of existing compatibility issues with WPML (#20 #144 #79). 
But as Jiemin said, we're prioritizing bugs for now. However, we will be happy to review any pull requests. 

Looks like you spent some time developing a fix, unfortunately not every shop will want only the English products to sync, but with some work maybe we can turn your fix into a fix for everyone.... and in fact your code looks like it supports the default language (not always english). Feel free to send us the fix as a pull request!!

**Comment by dmitridr** [comment]
We should have some minimal support for WPML v3.2 and above starting from our next release, based loosely on your fix here.

**Comment by mengyingdu** [comment]
Hi, 
We included all fixes and updates in [v1.7.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.4). Can you upgrade and try it?

**Comment by dmitridr** [comment]
Going to close this, as I assume you already have a good stable solution that you are using, but we do have preliminary WPML support now as Mengying said, in v1.7.4. Thanks for the code snippets, they really helped!!

**Comment by Jany-M** [comment]
Sorry what's the fix in the plugin though? I don't see any change from the previous state.
Am I missing something?
@mengyingdu @dmitridr
