### ISSUE TITLE
Woocommerce facebook account 

### ISSUE THREAD

**Issue by otinaztepe** [facebookincubator/facebook-for-woocommerce#1760]
Step 1: Uninstall Accont  https://prnt.sc/y4x3y7
Step 2: Uninstall Accont (Uninstall unsuccessful. Please try again)

Plugggin Delete / Re İnstall / DeActived / actived 

I deleted the facebook page but I cannot remove the account from the woocommerce page

**Comment by otinaztepe** [comment]
Heads up! Your connection to Facebook is no longer valid. Please click here to securely reconnect your account and continue syncing products.

 Step 1 : https://prnt.sc/y4xeld

Step 2 : https://prnt.sc/y4xf87 

Not Resolved :(

**Comment by jconroy** [comment]
Hi @otinaztepe 

Sorry to hear about your difficulties. 

The best places to get general support for this sort of issue is
* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)
