### ISSUE TITLE
Variation products do not sync

### ISSUE THREAD

**Issue by pixelicous** [facebookincubator/facebook-for-woocommerce#1763]
## 🔎 Isolate the bug
- [x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
I use attributes on products, such as color or size, and generate variations from that.
None of those products get synced to facebook.
Only simple products with no variations get synced without any problems
I have tried reinstalling the plugin, click product sync manually, check variations and they do have the option to get synced to facebook turned on. 
I tried finding a way to delete configuration or metadata but i haven't found such, on the product pages to the right side facebook plugin doesnt show any data as its not synced.

##🚶‍♀️ Steps to reproduce
Using latest wordpress/woocommerce/facebook plugin, variations dont get synced 

## ✔️ Expected behavior
See my products

**Comment by jconroy** [comment]
Hi @pixelicous 

Sorry to hear of your difficulties. I've tested and variable products / variations do sync so I'd suggest we'd need to look into a specific issue you experiencing in your setup/configuration.

The best way we can help with that is through our general support channels.
* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)
