### ISSUE TITLE
Facebook Pixel is executed twice

### ISSUE THREAD

**Issue by MedjahdiKaram** [facebookincubator/facebook-for-woocommerce#1765]
## 🔎 Isolate the bug

- [X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

When we connect the facebook for woocommerce pixel is executed twice 

##🚶‍♀️ Steps to reproduce

1. Install facebook for woocommerce
1. Connect it with pixel

## ✔️ Expected behavior
Facebook pixel code should be inserted only one time

## 🗃 Logs
When we expect the code we find this :
fbq('track','PageView',{"source":"woocommerce","version":"4.9.2","pluginVersion":"2.2.0"});
and this:
				<img height="1" width="1" style="display:none" alt="fbpx" src="https://www.facebook.com/tr?id=702792223972698&ev=PageView&noscript=1" data-pagespeed-url-hash="3299276444"/>

**Comment by budzanowski** [comment]
I was not able to reproduce the problem. 

PageView is used only once in the plugin. Data collected using Chrome Pixel Helper plugin:

Searching on forums suggests that there may be plugins that inject a secondary Pixel to the page. The report is incomplete so I have no way to check any further.

**Comment by felipeladislau** [comment]
I had the same problem @MedjahdiKaram, I just commented lines 201 to 209 on "facebook-for-woocommerce/facebook-commerce-pixel-event.php".
I`m still testing, but when I go to the source code on the home page the pixel is showing only once.
