### ISSUE TITLE
Products are taking forever to update

### ISSUE THREAD

**Issue by caninecandycart** [facebookincubator/facebook-for-woocommerce#1767]
I have installed the plugin Facebook for woo-commerce and trying to sync my woo-commerce products to my Facebook page. I click on product sync and it says you may safely leave this page - 38 items remaining.

It has been 4 hours and it seems as if it is stuck on trying to upload the 38 items.

I am not too sure what to do.

**Comment by jconroy** [comment]
Hi @caninecandycart 

Sorry to hear of your difficulties. It certainly sounds strange.

I'd recommend enabling debugging and see if you get any errors and also checking to make sure your wp-cron is working correctly.

The best places to get general support and help with this would be
* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)
