### ISSUE TITLE
Disable facebook messenger from website

### ISSUE THREAD

**Issue by Ruud0511** [facebookincubator/facebook-for-woocommerce#1770]
In my Woocommerce environment I'm not able to manage the messenger connection. I want to disable the facebook messenger from my site, but when I'm diverted to facebook help I get a 404-message that the page does not exist. How do I disable messenger from my website?

![Schermafbeelding 2021-02-15 112806](https://user-images.githubusercontent.com/79085364/107934884-e695b500-6f80-11eb-816b-7e34522faf62.png)
![Schermafbeelding 2021-02-15 112933](https://user-images.githubusercontent.com/79085364/107935029-1e9cf800-6f81-11eb-9f64-e8a357d7235e.png)

**Comment by Ruud0511** [comment]
Ok, I reinstalled the plugin, that helped with the error. But then I disabled facebook messenger from the plugin and it is STILL visible! How can I delete it / make it invisible?

**Comment by jconroy** [comment]
Hi @Ruud0511 

That is strange - all it should take to disable the messenger is to uncheck the "Enable and customize Facebook Messenger on your store" option

<img width="705" alt="Screen Shot 2021-02-18 at 9 51 29 am" src="https://user-images.githubusercontent.com/355014/108281063-fdc9e200-71ce-11eb-8452-8b9b3c567c61.png">

I've tested and am not seeing any issues on my end.

I'd recommend reaching out to support to get help with problem solving.
* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)
