### ISSUE TITLE
3 Warnings in Pixel

### ISSUE THREAD

**Issue by LisanneKuilman** [facebookincubator/facebook-for-woocommerce#1771]
Hello, 

I was looking into my statistics in Facebook and see that a lot of events are count double. Also I've 3 warnings in my account. Can you help me solving them?

1. Server Sending Invalid Match Key Parameters for AddToCart Event
2. Server Sending Invalid Match Key Parameters for ViewContent Event
3. Dezelfde event_id ontvangen voor vele gebeurtenissen (translate: receiving the same event_id for a lot of events.

Thanks a lot.

Lisanne

**Comment by jconroy** [comment]
Hi @LisanneKuilman 

Thanks for taking the time to send a message.

For the Invalid Match Key Parameters error - these typically haven't been widespread errors we can fix and the advice we have is 
* check your pixel is connected
* its likely related to browser extensions blocking user agent and IP address
* enable debug logging and see if you are getting any obviously errors

Related: https://wordpress.org/support/topic/server-sending-invalid-match-key-parameters-for-viewcategory-event/#post-13433313

I've just created a [catch-all issue](https://github.com/facebookincubator/facebook-for-woocommerce/issues/1777) I'll funnel all the similar reports to for the invalid match key parameter.

[We'll track the same event id issue you meant here](https://github.com/facebookincubator/facebook-for-woocommerce/issues/1722)

For support, the best places to go and get help are:
* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)



https://wordpress.org/support/topic/server-sending-invalid-match-key-parameters-for-viewcategory-event/#post-13433313
