### ISSUE TITLE
can't select my choice of page even with admin account why?

### ISSUE THREAD

**Issue by supersystemis** [facebookincubator/facebook-for-woocommerce#1774]
We’re happy to help with this question! Our support team works in our help desk rather than GitHub, though, so please use one of the following tools instead:

## 📖 Read documentation

The [Facebook for WooCommerce documentation](https://docs.woocommerce.com/document/facebook-for-woocommerce/) will help you set up the extension, use its features, and answer frequently asked questions. 

## 👩‍💻 Check forums

The [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) let you review other user questions and issues and learn what worked for them. 

## 🗣 Contact support

Our support team would be happy to help answer your questions! [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)

**Comment by jconroy** [comment]
Hi @supersystemis best bet for support is to post to [the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) or [contact support direct](https://woocommerce.com/my-account/create-a-ticket/), they'll be able to more efficiently step through any problem solving with you.
