### ISSUE TITLE
Server Sending Invalid Match Key Parameters for AddToCart Event

### ISSUE THREAD

**Issue by antocisale** [facebookincubator/facebook-for-woocommerce#1782]
## 🔎 Isolate the bug

- [ X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

![image](https://user-images.githubusercontent.com/49070899/108600136-1e7f6c80-7374-11eb-80e9-f7ab273146d1.png)

##🚶‍♀️ Steps to reproduce

1. Create an Add to Cart event on Facebook Pixel
1. Add products to the cart and checkout... both events start duplicating

## ✔️ Expected behavior

It only should send one event on each situation

## 🗃 Logs

Versión de WooCommerce: |   | 4.9.0 (didn't update to 5 beacuse Facebook for WooCommerce is not compatible yet)
Wordpress Version: 5.6.1
Facebook for WooCommerce plugin: 2.3.0
-- | -- | --

I don't have any other program rather than this one for the Facebook Pixel, so I don't know how to fix this.

Thank you!

**Comment by jconroy** [comment]
Duplicate https://github.com/facebookincubator/facebook-for-woocommerce/issues/1777
