### ISSUE TITLE
How to remove variant_label and variant_value fields from duplicated product?

### ISSUE THREAD

**Issue by BrianMisko** [facebookincubator/facebook-for-woocommerce#1785]
We’re happy to help with this question! Our support team works in our help desk rather than GitHub, though, so please use one of the following tools instead:

## 📖 Read documentation

The [Facebook for WooCommerce documentation](https://docs.woocommerce.com/document/facebook-for-woocommerce/) will help you set up the extension, use its features, and answer frequently asked questions. 

## 👩‍💻 Check forums

The [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) let you review other user questions and issues and learn what worked for them. 

## 🗣 Contact support

Our support team would be happy to help answer your questions! [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)

**Comment by BrianMisko** [comment]
Hello,

I am working on cleaning up the synchronization of my store data with Facebook.  There are errors noted for variant_label and variant_value fields for non-variable products.  Upon reviewing the items noted, they are products that when the item was created by duplicating an existing product.  It appears that this also duplicated these two fields.  Upon changing the product to a simple product (new item) the variant_label and variant_value persist.  Upon synchronizing to Facebook, it expects these fields even though the product does not use "variant" fields (it's a simple product).  

How do you "clean" the data for products and either populate these fields, make them not required (for simple products) or delete these fields for these products?

Thanks

Brian

**Comment by budzanowski** [comment]
Hi Brian,

On the right hand of the product page, you have the Facebook meta box:
![image](https://user-images.githubusercontent.com/17271089/110895121-71a46980-82f9-11eb-8b85-e874015c1002.png)
Resetting the Facebook metadata should trigger product re-synchronization and clear the errors. Try on one product and check that everything works correctly after the reset.

If this would not help then please contact us again with detailed information on how to reproduce your issue. How is the original variable product set. How is the second product copied? What are the changes that you make to that product?
Where are you observing the errors?

I am closing this, for now, resetting the metadata should help.
