### ISSUE TITLE
Website breaks when trying to edit product

### ISSUE THREAD

**Issue by audrey-colette** [facebookincubator/facebook-for-woocommerce#1786]
## 🔎 Isolate the bug

- [ ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce. [X]
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme. [X]

## ✍️ Describe the bug
This has happened for the last three versions of the plugin and just updated it to see if fixed. If I try to open a productpage to edit it I am sent to an empty page and I receive an email from wordpress that this plugin is causing a fatal error. [https://jewelrybycolette.com/shop/][X]

##🚶‍♀️ Steps to reproduce
I wouldn't know if others can reproduce but the maker of my theme Notio says it has nothing to do with the theme.[X]

1. The first step
1. In the dashboard go to products and click on a product to open product page [X]

## ✔️ Expected behavior
Instead of linking to a page that lets me edit the product information I get an empty page. 

I just updated to version 2.3.1 AND Notio to 5.5.2 but have not received warning from Wordpress yet. So I'm sending the last warning I received about the problem.

![fatal-error](https://user-images.githubusercontent.com/40599089/109170295-eff0ff80-7780-11eb-8d4a-898ecd34d186.png)

Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Facebook for WooCommerce.

First, visit your website (https://jewelrybycolette.com/) and check for any visible issues. Next, visit the page where the error was caught (https://jewelrybycolette.com/jewelry/wp-admin/post.php?post=4348&action=edit) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://jewelrybycolette.com/jewelry/wp-login.php?action=enter_recovery_mode&rm_token=SLdPoLh3f0ZLBwLMVj3tpA&rm_key=WZSTZaiQ5fyHz1SfbVrAhK

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.6.1
Current theme: Notio (version 5.5.1)
Current plugin: Facebook for WooCommerce (version 2.3.0)
PHP version 7.3.27

Error Details
=============
An error of type E_ERROR was caused in line 47 of the file /mnt/web503/b3/89/51588589/htdocs/jewelry/wp-content/plugins/facebook-for-woocommerce/includes/Products/FBCategories.php. Error message: Out of memory (allocated 214925312) (tried to allocate 20480 bytes)

## 🗃 Logs

I cant even upload an image because this website generates an error too! so I pasted the text.

**Comment by stanislauskostka** [comment]
Am experiencing same issue with the plugin.

**Comment by audrey-colette** [comment]
> Am experiencing same issue with the plugin.

Which theme are you using? I hope they don't pin the error on the theme and fix the plugin or I will have to stop using the plugin...

**Comment by Aston701** [comment]
I'm having the same issue, if I disable Facebook for woo plugin it works or if I uninstall the connection to my Facebook page it also starts working again.

**Comment by audrey-colette** [comment]
Me too, I hope they do something about it!



Jewelrybycolette.com <https://jewelrybycolette.com>

+31 (0)6 28640024

\ (゜o゜) /


Op zo 28 feb. 2021 om 20:09 schreef Aston701 <notifications@github.com>:

**Comment by jconroy** [comment]
Hi @audrey-colette , thanks for the message and sorry for your difficulties.

> An error of type E_ERROR was caused in line 47 of the file /mnt/web503/b3/89/51588589/htdocs/jewelry/wp-content/plugins/facebook-for-woocommerce/includes/Products/FBCategories.php. Error message: Out of memory (allocated 214925312) (tried to allocate 20480 bytes)

We're aware of the issue and it is being looked at. The Google Product Categories implementation uses a not-insignificant amount of memory (when trying to load ALL the categories) and on some merchant's hosts (also dependent on their configuration) it can cause issues. The best workaround for now is to try increasing your PHP memory limit (looks like you have it currently set to something around 200MB).

We have some other issues open for this so I'm going to close this or now to avoid duplication.
