### ISSUE TITLE
Select Category to include instead of exclude in Facebook Shop

### ISSUE THREAD

**Issue by ikonstantakis** [facebookincubator/facebook-for-woocommerce#1789]
Hello,

I just started using Facebook for Woocommerce and it would be mush easier if I could select which Category to include for sync instead of which categories to exclude.

I have many product categories but do not want all products to appear on the Facebook Shop page.
It would be much easier for me to create a category "For Facebook Shop" (which does not appear on my actuall eshop) and products I wanted on Facebook I would just asign to this category also.

Thank you.

Ioannis. 
## Feature requests

If you have an idea for how we could improve Facebook for WooCommerce, please let us know by [contacting our support team](https://woocommerce.com/my-account/create-a-ticket/)! We'd love to learn more about the problem you're facing and how Facebook for WooCommerce could help solve it.

## Developers

We welcome your contributions. 🙌 Here are a few tips to help us work together:

- If you submit a new PR, please ensure the description explains why the change is needed, follows WordPress coding standards, is compatible with PHP 5.6, and contains a small changeset — PRs with massive changesets are likely to be rejected or asked for revisions, as they’re much harder to review for potential issues.
- If you’d like to propose a more substantial changeset, feel free to start a discussion of why and the proposed implementation in this issue! Giving our team a heads up increases the likelihood of changes being accepted quickly.
- Internet points are available for PRs that include test coverage! 🏆 💯 Especially failing + passing tests for bug fixes.

**Comment by jconroy** [comment]
Hi @ikonstantakis thanks so much for taking the time to post your idea/feature request. If you don't mind could you please [add it to our ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=398356) so that we can track the popularity - I definitely see merit in your suggestion. The ideas board just helps us prioritize requests better.

**Comment by ikonstantakis** [comment]
Hi @jconroy
I have added it to the ideas board as requested.
