### ISSUE TITLE
Is it possible to single or multi select products to be synced to Facebook?

### ISSUE THREAD

**Issue by adolfusadams** [facebookincubator/facebook-for-woocommerce#179]
Is it possible to single or multi select products to be synced to Facebook?

**Comment by dmitridr** [comment]
Hello,

By default, the plugin will sync all visible published products, so selection of products to sync is not currently possible. Though if you'd like to request this as a feature to add, I can mark this as such.

Here is what is currently possible:

- You can 'Hide' products from FB using the 'Hide' button on the all products page.
- You can 'Hide' products from FB using the visibility toggle on the right side of the product edit page.
- You can Delete products from FB by using the delete link on the right side of the products page, but the product may be re-created if you update it again.
