### ISSUE TITLE
F-commerce doesn't work properly

### ISSUE THREAD

**Issue by saidmsaif** [facebookincubator/facebook-for-woocommerce#1792]
Hi, 

I'm developing a website in wordpress woocommerce and I use the Facebook for WooCommerce plugin to sell my product on Facebook.

**The issue is when I'm setting up automatic synchronization options then it's showing synchronization completed but can not synchronize properly on Facebook.**

**I want the functionality that when any product is getting out of stock then it'll not show on Facebook. When I'll add the product and stock available then It'll show on Facebook automatically.  But it's not working as well. Please quote me how we can setting up this functionality ???**

Regards.

**Comment by jconroy** [comment]
Hi @saidmsaif sorry to hear of your difficulties and thanks for opening an issue, I think the best option at the moment for you to get support is to post to [the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) or [contact support direct](https://woocommerce.com/my-account/create-a-ticket/), they'll be able to more efficiently step through any problem solving with you and help answer set up questions.

**Comment by saidmsaif** [comment]
Okay. Thank you.
