### ISSUE TITLE
Products display in FaceBook oldest to newest

### ISSUE THREAD

**Issue by thesilverforge** [facebookincubator/facebook-for-woocommerce#180]
Hi, apologies if this has been addressed elsewhere - I have read all the documentation and both open and closed issues and can't see an answer. Is there a way to change the display order of the products? Currently they are displayed oldest to newest. Thanks!

**Comment by dmitridr** [comment]
Hello,

Unfortunately there's no way to do that within the shop, if you are talking about the shop. 

If you run Dynamic Ads, the products are typically displayed in order of relevance to the user (starting with the products they looked at directly).

**Comment by thesilverforge** [comment]
Hi Dmitridr, 

Thanks for your reply. I did mean the ordering in the shop. I wonder if there is a setting somewhere in Woocommerce that causes them to be displayed oldest to newest - or is that the default and only setting of Facebook for Woocommerce?

Cheers, Ruthie

**Comment by dmitridr** [comment]
Hi Ruthie,

It's the default and only setting, right now. When uploading products we iterate through all posts from oldest to newest, which would be why the ordering looks that way on the FB shop.

If you'd like to list the products newest to oldest instead (backwards) we can probably come up with a quick fix for you, you would have to add this fix yourself within the WP plugin editor.

You may also want to try creating and using collections in the meantime, there may be a way to change the display ordering of collections within the shop, though I am not too familiar with those.

**Comment by thesilverforge** [comment]
Hi Dimitri, 

A quick fix would be awesome if you could! Newest to oldest makes more sense for me.

I have created collections, however this doesn't change the default display in the main FaceBook page.

Thanks for your help!

Ruthie

**Comment by djheatley** [comment]
can you also please provide me with the quick fix?

**Comment by dmitridr** [comment]
Not so quick I'm afraid. Sorry this fell under the radar for us. Here's my suggestion for the fix. Install v1.8.1, and find the file fbproductfeed.php using the editor, and replace the line [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.8.1/includes/fbproductfeed.php#L84):

Which looks like

```
$product_ids = array_diff($post_ids, $all_parent_product);
```

With

```
$product_ids = array_reverse(array_diff($post_ids, $all_parent_product));
```

Then reset the plugin using `Reconfigure > Advanced Settings > Delete` and set up again.
Unfortunately, I worry this may not fix the problem, when I tested this on my test server it did seem to change the ordering to roughly oldest to newest, but it is not exactly correct either.

#256 is a related issue to this where the shops team may add ordering as a feature in all shops. Please comment in that one as well if you have interest in this feature. The shops team told us they don't think there is demand for this feature so they're not prioritizing very highly right now, we are trying to change their mind.

**Comment by thesilverforge** [comment]
Thanks, Dmitridr!

**Comment by rossmeyerza** [comment]
Thanks guys, was looking for this!

**Comment by mengyingdu** [comment]
Just FYI, you may be able to control the ordering better by creating a Collection. Check out issue #401 for details.

**Comment by dmitridr** [comment]
Since there is a working fix for this using an edit, I will close this issue as it has been 6 months since there has been any activity. Hopefully people will still be able to find this resolution via google and etc.
