### ISSUE TITLE
Implement system that will allow automatic re-sync on plugin update.

### ISSUE THREAD

**Issue by budzanowski** [facebookincubator/facebook-for-woocommerce#1807]
## Feature requests

For some of the releases, an update procedure is required. This procedure would consist of various actions like for example re-sync the products to the FB database.

## Developers

We welcome your contributions. 🙌 Here are a few tips to help us work together:

- If you submit a new PR, please ensure the description explains why the change is needed, follows WordPress coding standards, is compatible with PHP 5.6, and contains a small changeset — PRs with massive changesets are likely to be rejected or asked for revisions, as they’re much harder to review for potential issues.
- If you’d like to propose a more substantial changeset, feel free to start a discussion of why and the proposed implementation in this issue! Giving our team a heads up increases the likelihood of changes being accepted quickly.
- Internet points are available for PRs that include test coverage! 🏆 💯 Especially failing + passing tests for bug fixes.

**Comment by haszari** [comment]
I think we can close this now #1808 is merged and shipped in v2.3.3.
