### ISSUE TITLE
AddToCart and Purchase not working with Pixel + WooCommerce Subscription Issues

### ISSUE THREAD

**Issue by EmmanouilPerdikis** [facebookincubator/facebook-for-woocommerce#181]
After updating to version 1.6.6 , my pixel stoped working properly. 
Only ViewPage is alive. AddtoCart or Purchase stoped working , although i have a lot of daily traffic and some purchases. The Pixel shows zero .
 And also i have two active subscriptions Facebook For WooCommerce ??? Which one is the correct ?

I am attaching you screenshots.

Thanks,
Emmanouil Perdikis
<img width="680" alt="screen shot 2017-12-04 at 23 25 58" src="https://user-images.githubusercontent.com/34255540/33583282-469dfd8a-d962-11e7-9a3c-f7c2527e86cf.png">
<img width="1298" alt="screen shot 2017-12-04 at 23 21 52" src="https://user-images.githubusercontent.com/34255540/33583283-46c26724-d962-11e7-90a6-c6917d76de55.png">

**Comment by dmitridr** [comment]
Hello,

Please try our latest version, v1.7.2 available [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.2).

Does the problem persist in the latest version?

For the subscriptions, I suggest contacting WooCommerce support to resolve the issue. This may be why the pixel won't work. You may be able to fix it by uninstalling/reinstalling the plugin.

**Comment by EmmanouilPerdikis** [comment]
Thanks ! But i am still getting the same errors.

Is there any way to remove all pixel code from the site and Re-Install it.
Like a clean install .

**Comment by EmmanouilPerdikis** [comment]
Also in WooCommerce Subscription i have two FacebookForWoocommerce but i
have only one plugin installed .

**Comment by dmitridr** [comment]
Hello,

Our team is not familiar with the WooCommerce subscription mechanisms or how to resolve issue with those, the WooCommerce support team would probably be the experts on that. 

There is a way to reset the plugin, you can do so by clicking the 'Reconfigure' button in settings, then in the popup clicking on 'Advanced Options / Advanced Settings' in the left. And hitting the button that says 'Delete' and confirming. This should reset your installation to the state it was at the very beginning (no pixel, nothing).

**Comment by EmmanouilPerdikis** [comment]
Thanks for your help and your advices .
I will try to reset and install again.

Do you have any email to contact WooCommerce support team ?


Thanks,
Manolis Perdikis
