### ISSUE TITLE
PROBLEMS WITH PIXEL ON PURCHASE ACTION: Catalog Report Event Match Rate

### ISSUE THREAD

**Issue by pomochoko** [facebookincubator/facebook-for-woocommerce#183]
hello 
I have some issue with the pixel report 
the pixel not report at all the purchases event in power editor and in the pixel part in face book I have people purchase but not report at all so for me it's impossible to track from where the purchases comes
I use WOOCOMMERCE last version the dynamic catalogue is upload 
if someone have a clue about this it will be welcome

**Comment by mengyingdu** [comment]
Hi @pomochoko ,

Can you tell me your page or store url? I need more information to investigate your problem.
Also, if you can upload a screen shot for your view at you power editor pixel part, it's best.

Thanks.

**Comment by pomochoko** [comment]
hello there thank you for reply my questions
It seems FB took more than 12 hours for report the purchases in the pixel part in bisness manager 
but I have only 50 p cent of my purchase report in power editor 
when Im looking in catalogue report all looking fine except this why i they report UNMATCH EVENTS 
![capture d ecran 2017-12-08 a 09 10 23](https://user-images.githubusercontent.com/34292066/33746363-ab0de644-dbf7-11e7-8ac6-3d4240f55402.png)

![capture d ecran 2017-12-08 a 09 08 55](https://user-images.githubusercontent.com/34292066/33746335-7a5da886-dbf7-11e7-9875-1eeb1d3a8fce.png)
I'm still investigate from my part I have some hypothese the one is when the people finish the purchase they turn off to quick the site and not waiting the thank you page all the payement are done with paypal I read some staff about it but not sure at all 

all the indicator are in GREEN with pixel helper I just want to know which campaign perform purchase so I can decide and optimize my facebook add 

Hope you have a clue, idea 
looking forward

**Comment by mengyingdu** [comment]
It seems duplicated with #113

**Comment by mengyingdu** [comment]
Hi @pomochoko ,

We fixed unmatched event issue in v1.7.0. I checked your website and it is using v1.6.0 of our plugin. Can you try to upgrade and check your pixel event later once have another activity?

Thanks.

**Comment by pomochoko** [comment]
hello mengyingdu yes i have version v1.6.0  but why nothing appears like i should update this on my back office wordpress do you have the link where i can dowload the update or the new version the update will be better i'm little bit "worried" dowload something and break my website so many times i did wrong manipulation 
thank you very very much for your help hope it's that the solution

**Comment by mengyingdu** [comment]
Hi @pomochoko ,

Sure, you can download here [v1.7.2](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.2) 
On another note, we enable auto-upgrade after 1.7.0, so you should see that notice in your admin panel if we release new version next time.

Thanks.

**Comment by pomochoko** [comment]
for install new one i should desinstall old one or just install the the 1.7.2

**Comment by mengyingdu** [comment]
You should go to 'plugins' tab -> installed plugins -> deactivate 'Facebook for WooCommerce' -> delete
Then install new plugins: upload the zip file and then install. I think it's not complicated to go through if you try the flow. 

Thanks.

**Comment by pomochoko** [comment]
yes is not looking complicated but i'm "scare" lose something I will do it and keep you update at the nex event on the pixel.
Because again the last 24h 3 purchases only one report in power editor so can not decide wich campaign working good no worries if the new update work fine that like make my christmass gift :-)

**Comment by mengyingdu** [comment]
Hi,

On another side, after upgrading, it should fix the unmatched event for your business in the future purchase. It may not retrieve sth happened before.

Thanks.

**Comment by pomochoko** [comment]
ok understand and make sense :-) i will do it in next couple hours and waiting the next event(s) and thell you if it's all is fine 
this pixel make me crazy ....

**Comment by pomochoko** [comment]
Hello the problems continue I had some purchase coming from my advertisement on fb and the result no show up in POWER EDITOR.
I have 2 questions about that maybe one is the more rational reason
1) problems about the thank you page 
2) problem with my SKU reference
or both 
waiting and litsening all advices for fix that

**Comment by pomochoko** [comment]
my sku generator for now not provide for variable the sku is for that i open the idea about this reason do you recomend one in particular dome of my product have 5 or more variation (color/size etc)

**Comment by pomochoko** [comment]
I more and more sure the problem come from something beetween the iniatiate check out and the purchase action because the total of my initiate cek out is very close from the real PURCHASE

**Comment by mengyingdu** [comment]
Hi @pomochoko,

I don't think sku is the cause of your problem if you checked https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbutils.php#L73.
For variable product, if no sku, we will use variant_id to set up pixel fire event.

After upgrading and having traffic, what did you see in business manager? Any change comparing to previous plugin version?

**Comment by pomochoko** [comment]
hello mengyingdu  since I Update with the new version some of the PURCHASE EVENT appear in the the right place but till more than 50% NOPE they are report in INITIATE CHECK OUT with the exact amount. Maybe fb register this action first because the moment betwwen the SUBMIT for pay and the validation of the payement is to long or the customer close the page payement page to quick or a problem with the thank you page 
All my payement are done with paypal and I use HITSTEP so I can see exactly what happen on my site 

The probleme is between INITIATE CHECK OUT and PURCHASE the result of the pixel fire report in initiate should be in PURCHASE

**Comment by pomochoko** [comment]
{"source":"woocommerce","version":"3.2.5","pluginVersion":"1.7.2","content_ids":"[\"tk6768_6768\"]","content_type":"product_group","value":"35.99","currency":"EUR"} |  
-- | --

for exemple this is report in the PIXEL part in bisness manager in purchase ==>> this purchase happens more than one week ago but the customer came back to check is order so is report in purchase ????

**Comment by pomochoko** [comment]
the same result report in INITIATE CHECK OUT AND PURCHASE
12 décembre 2017 05:30 | InitiateCheckout | Bureau | {"source":"woocommerce","version":"3.2.5","pluginVersion":"1.7.2","num_items":"1","content_ids":"[\"tk4237_8900\"]","content_type":"product","value":"7.49","currency":"EUR"} | https://truktil.com/commande/
-- | -- | -- | -- | --


12 décembre 2017 05:35 | Purchase | Bureau | {"source":"woocommerce","version":"3.2.5","pluginVersion":"1.7.2","content_ids":"[\"tk4237_4237\"]","content_type":"product_group","value":"7.49","currency":"EUR"} | https://truktil.com/commande/order-received/9478/?key=wc_
-- | -- | -- | -- | --

**Comment by pomochoko** [comment]
1 décembre 2017 21:08 | InitiateCheckout | Bureau | {"source":"woocommerce","version":"3.2.5","pluginVersion":"1.7.2","num_items":"6","content_ids":"[\"tk4187_6138\",\"tk4187_6136\",\"tk7171_7171\",\"tk5467_5467\",\"tk6833_6833\",\"tk9450_9456\"]","content_type":"product","value":"37.51","currency":"EUR"} | https://truktil.com/commande/
-- | -- | -- | -- | --
this one report in initiate check out 


11 décembre 2017 21:32 | Purchase | Bureau | {"source":"woocommerce","version":"3.2.5","pluginVersion":"1.7.2","content_ids":"[\"tk4187_4187\",\"tk4187_4187\",\"tk7171_7171\",\"tk5467_5467\",\"tk6833_6833\",\"tk9450_9450\"]","content_type":"product_group","value":"35.63","currency":"EUR"} | https://truktil.com/commande/order-received/9476/?key=wc_
-- | -- | -- | -- | --

this one still in initiate check out for a total a 37,51 and the real purchase is 35,63 the difference is normal because the customer use a reduction coupon

**Comment by mengyingdu** [comment]
Hi @pomochoko,

Thanks for your detailed information and I'm working on a fix now.
Will update here once it's ready on Github.

Thanks.

**Comment by mengyingdu** [comment]
Hi @pomochoko ,

As a quick solution, you can replace ['woocommerce_thankyou'](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L263) with woocommerce_payment_complete. Keep in mind, this doesn't work for cash on delivery  as its name.

Thanks.

**Comment by pomochoko** [comment]
hello there is no link for woocommerce_payment_complete.  and i'm not sure how to do it 
all customers pay by card never cash :-)

**Comment by mengyingdu** [comment]
Hi @pomochoko ,

I mean literally replace 'woocommerce_thankyou' with 'woocommerce_payment_complete' in that line. 

Thanks.

**Comment by pomochoko** [comment]
I'm sorry i'm to much "beginner" for understand and do it this kind of modification with out a full tuto or more explicitationif I use a plug in for that should be for me "simple" if you understand my position :-)

**Comment by mengyingdu** [comment]
Understand that, I will update here later.

**Comment by pomochoko** [comment]
ok i just did update Version 1.7.3  I think I'm not the only ONE people with this problem ??? or people not track their advertisement on FB ??

**Comment by pomochoko** [comment]
because again yesterday people add to cart ==>>> initiate check out ==> purchase and I have 1/1/1 in each column if the people going till purchase should be 1 in purchase the final fire event right??

**Comment by mengyingdu** [comment]
Hi @pomochoko ,

I have a fix for this issue, however, since purchase event is 'REALLY' important for pixel tracking, we hold on it to release and plan to set up more exhausting testing with more payment way. It means v1.7.3 doesn't include my fix for this. We need to set up more bank/paypal 3rd party payment processor to do this testing. But we will definitely include in next release v1.7.4.

If you are urgent to fix this and interested in trying it out, I can offer you a pre-release version. Let me know.

Thanks.

**Comment by pomochoko** [comment]
why not if your pre release not making more trouble in my web site and can help 

**====>>of course PURCHASE EVENT is the most important <<======**

**Comment by mengyingdu** [comment]
Hello again,

If you are interested, can you send an email to ads_extension_woocommerce@fb.com so we can know your email address?

Thanks.

**Comment by pomochoko** [comment]
i sent you email this is automatic answer i get 

Thanks for your message. We're no longer responding to emails that are sent to this address, but we have 2 new ways to get help:

 

Facebook Help Center: We answered frequently asked questions about using WooCommerce on Facebook in this article.

 

Our GitHub repository: If you think you've found a bug, please file it in this repository so it's visible to others and we can take action on it.

When filing a bug on GitHub, please look at the previously closed issues first because you may find a resolution to your issue. If you need assistance in filing an issue, please contact WooCommerce.

 

If you're a developer, you can submit a pull request to the repository for our team to review.


Thanks,

The Facebook Ads Team

**Comment by mengyingdu** [comment]
Hi @pomochoko ,

I received your email and yes,that is our auto reply. I will reply to your email with detailed instruction after meeting. Thanks.

**Comment by mengyingdu** [comment]
Hi @pomochoko ,

I just replied to you.
As for the auto reply, we stop email channel support for a long while. So if you have further questions, feel free to ask on github. 

Thanks.

**Comment by mengyingdu** [comment]
Hi @pomochoko ,

Did that fix your problem? Can you confirm your purchase now?

Thanks.

**Comment by pomochoko** [comment]
Nothing change you told me you will give me a release for testing you not sent the pre release so nothing change
1 addto cart = 1 initiatecheckout = 1 purchase 
OR the information stay in initiatecheckout and the customer purchase so can not adjuste my campaigns and not doing any retargeting because how come i retarget initiatecheck if they bought ???

Waiting your light for clear that

**Comment by mengyingdu** [comment]
I sent instructions and pre-release zip by email on Thursday. Can you check your gmail? (maybe Junk as well since the attachment is very large)

I'm pretty sure I sent it and I can check it in my emailbox record..

**Comment by pomochoko** [comment]
yes i have a mail from you in JUNK box but is mail FAILL the gmail not dowload at all maybe better to put the file on drop box or I give you other email NOT GMAIL let me know the best for transfert big files

**Comment by pomochoko** [comment]
sorry for give you more jobs

**Comment by mengyingdu** [comment]
Sorry, we are not allowed to share file via dropbox externally..

Are you using IE browser? I found some resource may help you: https://productforums.google.com/forum/#!msg/gmail/LOhKkssPdSo/DV6d4RSFKgQJ

Also, I just sent it again and separate it into 2 emails, can you try:
1. follow the suggestion in google forum to set up your browser
2. download.
Let me know whether it works.

Thanks

**Comment by pomochoko** [comment]
receive the video but not yet the new release i will update you when it's done thank

**Comment by pomochoko** [comment]
not yet receive zip file just video

**Comment by mengyingdu** [comment]
resent.

**Comment by pomochoko** [comment]
1.7.3 is install since more than 4 days and still the problem
I don't understand I'm the only one have this problem no body had report this except me

**Comment by mengyingdu** [comment]
Hi, 
If you read through my email, the link is your concern about how to roll back.
There should be a zip file as attachment in that email as well. Did you find it?

**Comment by pomochoko** [comment]
![capture d ecran 2017-12-18 a 11 57 30](https://user-images.githubusercontent.com/34292066/34089414-ca557f3a-e3ea-11e7-898e-56ca4f020bd1.png)
you can see 9H21 one attachement the video all other mail no attachement

**Comment by mengyingdu** [comment]
I see, it seems it was blocked due to security issue.
Actually, you can download zip file from github directly (but not the release page). Since you told me you are absolutely beginner, I didn't propose this approach, sorry for the back and forth!

Step to download:
1. go to 'code' tab (if you go the the head of this page, you are on 'issue' tab now, and code tag is left aside it)
2. click on the **green** 'clone or download' button
3. in the button drop-down, click on download zip

Then you are good to go with the instructions you received.
Hope it helps.

Thanks.

**Comment by pomochoko** [comment]
the name of the file is facebook-for-woocommerce-master.zip

**Comment by mengyingdu** [comment]
yes

**Comment by pomochoko** [comment]
ok i will try it and report after the next purchase event on my site

**Comment by mengyingdu** [comment]
Hi @pomochoko,

Just want to check: do you still have this problem? Does the pre-release version work for you?

Let me know if you need more help.

**Comment by mengyingdu** [comment]
Hi @pomochoko ,

Hope it works for you? You can also go to your catalog manager to check pixel event. Let me know if you need more help.

Happy New Year.

**Comment by mengyingdu** [comment]
Hi @pomochoko 

We have tested and included all fixes and updates in [v1.7.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.4). Can you upgrade and try it?

**Comment by mengyingdu** [comment]
Close this issue now since we fixed in v1.7.4
