### ISSUE TITLE
All variants displayed in catalog

### ISSUE THREAD

**Issue by nejccesar** [facebookincubator/facebook-for-woocommerce#184]
Hi,
I am using your plugin and its awesome the only thing that bothers me is when i sync products to facebook all product sync ok and it says its syncing 650 products but when I try to create a product set all variants are displayed as seperate products. Can i make it work so in the product set there is only one product per variant? I will attach a print screen so you will understand it better. 
THANK YOU for your help. 
![screen shot 2017-12-08 at 12 17 08](https://user-images.githubusercontent.com/17556881/33763699-bf45f006-dc11-11e7-8ba6-11f619c90a7c.png)

**Comment by mengyingdu** [comment]
Hi @nejccesar ,

If you check your Facebook page, it should show correctly: variable product as a one product, and there is drop-down to select variant value. 
Your screen shot is the view of your catalog manager 'products' session, so it will show all 'actual' products. It may help understand that each variant of variable product is a 'real' product so it is here individually.

On other notes, you can create product set in your catalog manager if it helps you manage your business. There is the help doc about catalog manager: https://www.facebook.com/business/help/1659534074121655

This is out of scope of your plugin so I would recommend you reach out to catalog team of help center if you need more help.
Thanks.

**Comment by mengyingdu** [comment]
related to #162

**Comment by mengyingdu** [comment]
Hi @nejccesar ,

I understand your concern (I guess you saw this in Catalog Manager?) but you need not worry, the way Dynamic Ads work no product within the same product group will appear in the same ad. Therefore only one variant of each product will appear in any ad to any user at any one time.
