### ISSUE TITLE
How to disable the export of product variations: only sync main product to FB

### ISSUE THREAD

**Issue by chillpilllike** [facebookincubator/facebook-for-woocommerce#187]
Hi,

i would like to disable the export of product variations since i have a lot of variations for each product and syncing it takes a big load and slows down the website.

can we just disable the variations so only the main product is exported.

thanks

**Comment by tahoff** [comment]
There currently isn't a way to stop all products of a specific type (ex: variable products) for syncing with Facebook. If you want to delete a specific product from Facebook, you can go to the product page and click "Delete product(s) on Facebook" for each product you no longer want to sync. But you'll have to do this for each variable product.

**Comment by dmitridr** [comment]
Hello @chillpilllike , 

I have a workaround for you if you're still interested, though this will stop the exporting of all variable products, including the main product, so only simple products will be exported. It requires editing the plugin directly using the wordpress plugin editor, however. Here's the workaround, change these lines in `facebook-commerce.php`:

https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.7.5/facebook-commerce.php#L703-L705

To 
```
if (true) {
    return;
}
```

This should cancel the sync of variable products. You should reset the plugin after you make the change (`Reconfigure` > `Advanced Options` > `Delete`).

**Comment by chillpilllike** [comment]
Hi Dimitri,

99% of products are variable so it won't help, instead the useful thing is to export the variable products too but not their variations. Same like the official woocommerce google product feed plugin option to export the variable products but not the variations of the variable products.

Thanks


On 13-Jan-2018, at 5:45 AM, Dmitri Dranishnikov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @chillpilllike<https://github.com/chillpilllike> ,

I have a workaround for you if you're still interested, though this will stop the exporting of all variable products, including the main product, so only simple products will be exported. It requires editing the plugin directly using the wordpress plugin editor, however. Here's the workaround, change these lines in facebook-commerce.php:

https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.7.5/facebook-commerce.php#L703-L705

To

if (true) {
    return;
}


This should cancel the sync of variable products. You should reset the plugin after you make the change (Reconfigure > Advanced Options > Delete).

**Comment by mengyingdu** [comment]
@dmitridr 
1.Do you think add a checkbox inside the facebook tab section of the product editor is a doable approach? AKA, if check, sync as simple product. 
2. What's your thoughts on the benefits? 
In my understanding, speed up syncing, fix some weird problems due to variation problems
3. Any potential problems?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
