### ISSUE TITLE
The plugin is publishing products with HIDDEN property

### ISSUE THREAD

**Issue by gabrielizalo** [facebookincubator/facebook-for-woocommerce#19]
In our **WooCommerce** the products has a property **Visibility** that can have one of these values: 

- Catalog and Search
- Catalog
- Search
- Hidden

If a product is **Hidden** I think is a product to be ignored from the published products in Facebook Shop.
A look of my _Product Quick Edit_ (Oculto = Hidden in Spanish):

![woocommerceproducts](https://user-images.githubusercontent.com/656353/29545043-a3265650-86b1-11e7-970d-38bc20244e38.png)

**Comment by gabrielizalo** [comment]
Lookin in my _NNN_postmeta_ table appears records with: 

    meta_key AS _visibility

and
 
    meta_value AS hidden

![postmeta](https://user-images.githubusercontent.com/656353/29545844-43c8600e-86b6-11e7-8c94-f76cf5bb39aa.png)

**Comment by jlev00** [comment]
I think it's a good assumption that if the product is hidden in the Woocommerce store, it should also be hidden from the Facebook Store

**Comment by tahoff** [comment]
@gabrielizalo Thanks for reporting this issue! We've fixed the issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.0). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
