### ISSUE TITLE
AddToCart event is not tracked

### ISSUE THREAD

**Issue by guzun** [facebookincubator/facebook-for-woocommerce#192]
Hi there.

We are using this plugin on a site which redirects to the cart page after successful addition of a product.
https://i.imgur.com/6mXgn59.jpg
And in this case the 'AddToCart' event is not tracked.
If I uncheck that option, then it works.

Is there a way to make it work with the redirect to checkout ?

Thank you,
Alex

**Comment by mengyingdu** [comment]
Hi,

I can repro your issue on our demo store. However, the way for 'AddToCart' works is hook on Ajax action. So if you set 'redirect to cart page' (whether you checked or unchecked "Enable AJAX add to cart buttons on archives", this event can't be fired.

Thanks.

**Comment by mengyingdu** [comment]
Hello,

Some context: We use 'after cart' hook before (but it raise double fire issue for the user opt-out 'redirect to cart') and then we change to add_to_cart which hook on the button click. However, this will have the issue you have when u opt-in redirect to cart. 

1. We could change back to original code, however, it has problem for more users..
2. Alternatively, we can check your setting and then add tracker to different hook. However, it needs DB call every time to checking your products setting when you load WooCommerce admin. So it hurts performance for loading and syncing.

There are some work around as a quick fix for your issue:

if you change [these lines](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L274-L277) like [this](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.6.5/facebook-commerce.php#L220-L221). It should work for add_to_cart event for your case.

Let me know whether it works for you.

Thanks.

**Comment by guzun** [comment]
Hi, thanks for the explanations.
Yes, indeed, using other hooks creates other issues.
So I ended up disabling the redirect. 
It doesn't change much the user work flow, but instead  'AddToCart' event is firing for all the products now.

Thanks again for the help. Really appreciate it.
Alex.
