### ISSUE TITLE
Price sync issues when scheduling a sale

### ISSUE THREAD

**Issue by jclewell** [facebookincubator/facebook-for-woocommerce#193]
When I schedule a product to be on sale, Facebook updates to the sale price immediately, instead of on the day it's supposed to be marked down. Clearly, that's an issue when FB shop shows discounted price and website doesn't yet.

**Comment by mengyingdu** [comment]
Hi @jclewell ,

Which version are you using? We should support 'sale schedule' from [v1.6.2](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/changelog.txt#L59) if you check the changelog.

I would recommend you to upgrade and then 're-config' --> 'force sync'. All of this should be in your : woocommerce -> settings ->integration page.

Let me know if you need help. If my suggestion above doesn't work, your store url or Facebook page will help us investigate your issue.

Thanks.

**Comment by mengyingdu** [comment]
Hi @jclewell,

Follow up with your issues since last reply 20 days, have you ever tried upgraded the plugin? Is this problem still exist?

Let me know if you need any help. 
Thanks!

**Comment by dmitridr** [comment]
I think it's safe to close this. I really hope we have solved all price issues at this point, we put in a lot of effort on that. If the problem re-occurs, please open a new issue and reference this one.
