### ISSUE TITLE
Exclude variations that are "virtual" products from export to Facebook && No Visibility Option for Variations

### ISSUE THREAD

**Issue by MarcusWernicke** [facebookincubator/facebook-for-woocommerce#194]
I have only 6 products, each of which has 2 variations, "email only" and "printed", whereas "printed" is an actual physical product but "email only" is a digital print-at-home version of the same product. Virtual products are prohibited for shops on Facebook, and as there is no way to exclude specific variations from being exported, I cannot use the plug-in at all (since it exports the virtual product as well as the physical).

Could you please automatically exclude those variations that are set to be "virtual" products so that the exported products are always in compliance with Facebook's terms?

**Comment by sammul** [comment]
@MarcusWernicke Sorry that there currently isn't a way to stop all products of a specific type (ex: variable products) for syncing with Facebook. If you want to advertise only email products, you can create a product set for these products and advertise on it in www.facebook.com/products.

**Comment by sammul** [comment]
#187

**Comment by dmitridr** [comment]
I don't think this would be that difficult, unfortunately we are swamped. Please consider sending us a pull request for this, we would love to review!

@MarcusWernicke one workaround you could try in the meantime, since you have only 6 products is to sync all of them, and mark the ones that are not in strict compliance as invisible (there should be a checkbox on the Woo settings page of the product that controls FB visibility)

**Comment by MarcusWernicke** [comment]
@dmitridr, I don't think there is an option to mark a single variation as "invisible" (each of the 6 products exists in 2 variations, 1 of which does not comply with FB terms). To have that option -- to mark an individual variation as invisible -- that is pretty much the feature I'm requesting :)

**Comment by dmitridr** [comment]
Good point, seems I misunderstood the situation here.

**Comment by mengyingdu** [comment]
I bootcamped this task @dmitridr

**Comment by mengyingdu** [comment]
Closes #194
