### ISSUE TITLE
After sync, product images shown repetatively 

### ISSUE THREAD

**Issue by jmrkela** [facebookincubator/facebook-for-woocommerce#196]
Hi There,

After product sync, images for some of my products are displayed multiple times (up to four times) in the shop section of my page.

Please see attached screenshot.

![17df72ee-6eb8-4d7a-a4e9-2796b28b3928](https://user-images.githubusercontent.com/35010752/34470851-7d76c4e2-ef9f-11e7-9113-c670c3742816.jpeg)

Any way around this?

Best regards,

JM

**Comment by jieminz22** [comment]
Hi,

Did you check your catalog? Are there also duplicate products as well? You can send us your store URL so we can take a look from our end.

**Comment by jmrkela** [comment]
Hi,

Here's my store url:
https://www.facebook.com/pg/JPWallArtStore/shop/?ref=page_internal

This is not about duplicated products but about duplicated product images.
Product list in catalogue matches one on my website so that is fine.
The issue is that on some of the products, product images are duplicated,
some are triplicated and some even quadrupled.

I have attached details about single product:
*website -* This is how the product looks like on my website. Please note
main product image and three additional images below the main one.
*catalog* - This is the same product in the product catalog after sync.
Please note that "additional_image_urls" shows 4 entries which is correct
so it looks fine there.
*FB Store* - This is how the same product looks like in the FB store.
Please note that each product image is shown *three* times there and that
is the problem. Some of my products are fine (showing 4 images), some are
doubled, tripled and even quadrupled.

I hope this helps.

Best regards,

JM






Browse through products and click

**Comment by jieminz22** [comment]
Hi JM,

Thanks for the info. I will forward this issue to shop team and will keep this issue open for any update.

**Comment by dmitridr** [comment]
Just want to give a heads up here, we are still tracking this problem internally and working through it with the shops team. 

Some advice in the meantime:
You may have some luck getting rid of this duplication if you upgrade to our newer versions 1.8.x, and do a full reset via `Reconfigure > Advanced Options > Delete` and set up again. We changed the way product sync works in these new versions.

**Comment by leahkatrina** [comment]
Hi. I'm having similar issues. following this thread for updates. Meantime, below are the bugs/issues i want to fix with my shop.

1.) Duplicate Photos
ACTION: In Wordpress Woocommerce, I duplicated a product (page) -> edited content and changed product images -> published.
PROBLEM: product photos of duplicated product appears on the product photos of the edited product on FB shop. Need to delete the photos from the duplicated product and retain the photos of the edited product.

examples:
https://www.facebook.com/commerce/products/1617730018280830/
*Only need the 1st photo. The succeeding 2 photos are from the duplicated product. Need to delete those 2.

https://business.facebook.com/commerce/products/1752217351465224/
*need to remove duplicate photo of the necklace, 2 duplicate photos of the model and 2 duplicate photos of the orange tassel necklace

2.) Product that has been deleted from Woocommerce inventory still shows up in FB shop.
I Ran back up and restore for my website. One product didn't make it to the restored back up file, so I created another entry for the same product. The changes didn't sync on my FB shop. Now I have 2 entries of the same product on my FB shop. Need to delete the previous product (see example below).

example: https://business.facebook.com/commerce/products/1882244675184233/
* this doesn't exist in the web products anymore.
-------------
Facebook Page URL : www.facebook.com/samsaramala
Website URL : www.leahkatrina.com/samsaramala
WordPress version number : version 4.9.4
WooCommerce version number : version 3.3.4
Facebook Plugin version number : Facebook for WooCommerce : version 1.8.1 (version 1.8.2 update error - update package not available)
How many products you have : 5
Types of products : simple product
Do you have Duplicate SKUs in your system? None
What kind of customization plugins you're using (if any)? None

Thank you.

Leah

**Comment by mengyingdu** [comment]
@leahkatrina Your shop and products' problems have been fixed.
@jmrkela
I can't repo your issues (I create a product, it won't have duplicate on my FB shop) 
Can you take a screenshot of your product editor for the product data setup? (Take your previous duplicate product as an example)
Since @leahkatrina fixed his problem by resync, would you mind have a try?

Thanks.
