### ISSUE TITLE
Woo store not posting products

### ISSUE THREAD

**Issue by 7thcirclegit** [facebookincubator/facebook-for-woocommerce#198]
I have a store (https://www.saintanthonyscorner.com) with  3755 items linked to my FB store (https://www.facebook.com/pg/Saint-Anthonys-Corner-151195452196232/shop/). Everything appears to be configured correctly but no products sync to my FB store.

`
### WordPress Environment ###

Home URL: https://www.saintanthonyscorner.com
Site URL: https://www.saintanthonyscorner.com
WC Version: 3.2.6
Log Directory Writable: ?
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ?
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.4
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ? 5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 10 MB
Default Timezone is UTC: ?
fsockopen/cURL: ?
SoapClient: ?
DOMDocument: ?
GZip: ?
Multibyte String: ?
Remote Post: ?
Remote Get: ?

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ?
Total Database Size: 729.71MB
Database Data Size: 571.04MB
Database Index Size: 158.67MB
wp_woocommerce_sessions: Data: 0.22MB + Index: 0.01MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
Managed_Client_Reports: Data: 0.02MB + Index: 0.00MB
Managed_Client_Reports_add_emails: Data: 0.00MB + Index: 0.00MB
Managed_Client_Reports_add_emails_templates: Data: 0.00MB + Index: 0.00MB
Managed_Client_Reports_add_notes: Data: 0.00MB + Index: 0.00MB
Managed_Client_Reports_dismissed_messages: Data: 0.00MB + Index: 0.00MB
Managed_Client_Reports_dismissed_notes: Data: 0.00MB + Index: 0.00MB
Managed_Client_Reports_recent_searched: Data: 0.00MB + Index: 0.00MB
Managed_Client_Reports_seen_messages: Data: 0.00MB + Index: 0.00MB
Managed_Client_Reports_seen_notes: Data: 0.00MB + Index: 0.00MB
wp_blc_filters: Data: 0.00MB + Index: 0.00MB
wp_blc_instances: Data: 0.01MB + Index: 0.01MB
wp_blc_links: Data: 0.07MB + Index: 0.02MB
wp_blc_synch: Data: 0.72MB + Index: 0.34MB
wp_cf_forms: Data: 0.01MB + Index: 0.00MB
wp_cf_form_entries: Data: 0.00MB + Index: 0.00MB
wp_cf_form_entry_meta: Data: 0.00MB + Index: 0.00MB
wp_cf_form_entry_values: Data: 0.00MB + Index: 0.00MB
wp_cf_pro_messages: Data: 0.00MB + Index: 0.00MB
wp_cf_tracking: Data: 0.00MB + Index: 0.00MB
wp_cf_tracking_meta: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.01MB + Index: 0.01MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_comment_mail_queue: Data: 0.02MB + Index: 0.02MB
wp_comment_mail_queue_event_log: Data: 0.00MB + Index: 0.00MB
wp_comment_mail_subs: Data: 0.00MB + Index: 0.01MB
wp_comment_mail_sub_event_log: Data: 0.00MB + Index: 0.00MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
wp_mainwp_stream: Data: 87.13MB + Index: 39.36MB
wp_mainwp_stream_context: Data: 23.66MB + Index: 11.11MB
wp_mainwp_stream_meta: Data: 207.77MB + Index: 74.57MB
wp_options: Data: 3.84MB + Index: 0.40MB
wp_pmlc_geoipcountry: Data: 7.83MB + Index: 3.54MB
wp_postmeta: Data: 204.45MB + Index: 19.90MB
wp_posts: Data: 33.36MB + Index: 6.76MB
wp_pros_campaigns: Data: 0.00MB + Index: 0.00MB
wp_pros_prossubscription: Data: 0.29MB + Index: 0.00MB
wp_queue: Data: 0.00MB + Index: 0.00MB
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.21MB + Index: 0.17MB
wp_terms: Data: 0.21MB + Index: 0.38MB
wp_term_relationships: Data: 1.01MB + Index: 1.83MB
wp_term_taxonomy: Data: 0.18MB + Index: 0.16MB
wp_UPCP_Catalogues: Data: 0.00MB + Index: 0.00MB
wp_UPCP_Catalogue_Items: Data: 0.00MB + Index: 0.00MB
wp_UPCP_Categories: Data: 0.00MB + Index: 0.00MB
wp_UPCP_Custom_Fields: Data: 0.00MB + Index: 0.00MB
wp_UPCP_Fields_Meta: Data: 0.00MB + Index: 0.00MB
wp_UPCP_Items: Data: 0.00MB + Index: 0.00MB
wp_UPCP_Item_Images: Data: 0.00MB + Index: 0.00MB
wp_UPCP_SubCategories: Data: 0.00MB + Index: 0.00MB
wp_UPCP_Tagged_Items: Data: 0.00MB + Index: 0.00MB
wp_UPCP_Tags: Data: 0.00MB + Index: 0.00MB
wp_UPCP_Tag_Groups: Data: 0.00MB + Index: 0.00MB
wp_UPCP_Videos: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.02MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 45033
nav_menu_item: 8
page: 8
post: 7
product: 3755
product_variation: 19787
revision: 31
shop_order: 2
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ?
Hide errors from visitors: ?

### Active Plugins (19) ###

AddToAny Share Buttons: by AddToAny – 1.7.23
Akismet Anti-Spam: by Automattic – 4.0.2
All In One SEO Pack: by Michael Torbert – 2.4.3.1
Autoptimize: by Frank Goossens (futtta) – 2.3.1
BackWPup: by Inpsyde GmbH – 3.4.4
Broken Link Checker: by Janis Elsts
Vladimir Prelovac – 1.11.5

Caldera Forms: by Caldera Labs – 1.5.8.2
Facebook for WooCommerce: by Facebook – 1.7.3 – Not tested with the active version of WooCommerce
Google Authenticator: by Henrik Schack – 0.48
MainWP Child Reports: by MainWP – 1.7
MainWP Child: by MainWP – 3.4.4
Prosociate: by Prosociate – 4.3.5
Storefront Sticky Add to Cart: by WooThemes – 1.1.8
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.11
WooCommerce - All in One SEO Pack: by Visser Labs – 1.3.4 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.6
WP Smush: by WPMU DEV – 2.7.6
WP Super Cache: by Automattic – 1.5.9

### Settings ###

API Enabled: ?
Force SSL: ?
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #14 - /
Cart: #15 - /cart/
Checkout: #16 - /checkout/
My account: #17 - /my-account/
Terms and conditions: #36 - /tos/

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ? – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ?

### Templates ###

Overrides: –
`

**Comment by 7thcirclegit** [comment]
I also get the following error sometimes.

Facebook extension error: Facebook for WooCommerce
Unsupported post request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

**Comment by jieminz22** [comment]
Hi,

When did you see this error? Could you share a screenshot? Also, did you delete the settings?

Thanks.

**Comment by 7thcirclegit** [comment]
I will share the screenshot the next time I see it. It shows up as it feels on this site and my other store, but that one does not have any products yet. No settings have been deleted, the plugin was installed and configured within the last 3 days.

**Comment by 7thcirclegit** [comment]
When I force a re-sync of products, it briefly changes to "syncing" and then reverts back to "all synced"

**Comment by jieminz22** [comment]
Hi,

Which version of the extension are you using? Also, do you see exceptions related to FB in the PHP logs?

Thanks.

**Comment by 7thcirclegit** [comment]
WordPress 4.9.1
Woocommerce 3.2.6
Facebook for WooCommerce 1.7.3
[debug.log](https://github.com/facebookincubator/facebook-for-woocommerce/files/1604263/debug.log)

**Comment by mengyingdu** [comment]
Hi,

I looked into our remote log, the error is connection lost. Can you try re-configuration then sync product?
Let me know if you need more help.

**Comment by 7thcirclegit** [comment]
I have reconfigured it, and no change. At this point, I have also removed the plugin from both of my sites due to the slow support, and the inefficient coding. The plugin overloads my sites memory and cpu usage rendering the sites unusable for the end user.

**Comment by weitls** [comment]
I am not able to since my woocommerce facebook products. This is the error I am getting. 
<img width="1181" alt="mailpicture-56" src="https://user-images.githubusercontent.com/35339223/34831151-213f59d4-f6b4-11e7-9a71-d68c4a14088f.png">
My products show in woocommerce that they have synced. 
<img width="1227" alt="mailpicture-57" src="https://user-images.githubusercontent.com/35339223/34831289-8fd9ea94-f6b4-11e7-9813-28b2a65dfee4.png">
<img width="880" alt="mailpicture-58" src="https://user-images.githubusercontent.com/35339223/34831307-9ba6e70a-f6b4-11e7-9748-c5877189f84e.png">

**Comment by dmitridr** [comment]
Hello, @weitls . 
I checked your catalog, it seems you set up on Dec 23rd, and there are around 400 products (including variations) in our system. However this catalog was deleted on Dec 31st, through one of our interfaces by an admin of your page or business. 

Because the catalog was deleted, you would need to set up again from scratch, this can be done by clicking `Reconfigure` > `Advanced Options` > `Delete Settings`, then going through set up again.

**Comment by weitls** [comment]
Thanks,
Do you know why I am getting error for the shop page on my Facebook page?

**Comment by dmitridr** [comment]
@weitls I think the Shop still exists (not deleted) so it expects the catalog to exists (but it is deleted) which generates an error in the system.

**Comment by weitls** [comment]
Ok! Thanks

**Comment by dmitridr** [comment]
@7thcirclegit We've significantly improved the CPU efficiency of product sync (by 60x), so if you're willing to give our plugin another shot, I recommend trying [v1.8.2](https://github.com/facebookincubator/facebook-for-woocommerce/releases) which has lots of performance improvements.

We're working to tackle the memory issues next. cc @mengyingdu
