### ISSUE TITLE
W3 validation error : An img element must have an alt attribute.

### ISSUE THREAD

**Issue by slava1967** [facebookincubator/facebook-for-woocommerce#201]
After validating at w3.org I have the following error: An img element must have an alt attribute

<img height="1" width="1" style="display:none"↩src="https://www.facebook.com/tr?id=569207803288287&ev=PageView&noscript=1"/>

Is there any way to fix it?

**Comment by jieminz22** [comment]
Hi,

Which version of the extension are you using?

**Comment by slava1967** [comment]
1.7.3

**Comment by slava1967** [comment]
[facebook-commerce-pixel-event.zip](https://github.com/facebookincubator/facebook-for-woocommerce/files/1607766/facebook-commerce-pixel-event.zip)

**Comment by slava1967** [comment]
<noscript>
<img height=\"1\" width=\"1\" style=\"display:none\"
src=\"https://www.facebook.com/tr?id=%s&ev=PageView&noscript=1\"/>
</noscript>

**Comment by slava1967** [comment]
#
#<noscript>
#<img height=\"1\" width=\"1\" style=\"display:none\"
#src=\"https://www.facebook.com/tr?id=%s&ev=PageView&noscript=1\"/>
#</noscript>
#
#

**Comment by jieminz22** [comment]
Hi,

Thanks. Can you send us your site url?

**Comment by slava1967** [comment]
Already changed to another plugin. Thanks.

**Comment by dmitridr** [comment]
Let's keep this open so we can fix it.

**Comment by dmitridr** [comment]
The fix for this is on our latest release : https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.7
