### ISSUE TITLE
Issues with products syncing incorrectly

### ISSUE THREAD

**Issue by katecos** [facebookincubator/facebook-for-woocommerce#203]
Hi,

I have the Facebook for woo commerce plugin and products from my store www.kccmdesign.com.au have been synced to my business Facebook page (KCCM Design).

The issue I have is there is a double up of a particular product which is showing the wrong price. I have deleted the product off my website and added a new one. The new one has sucessfully synced however the old one is still showing on my facebook page. I have also uninstalled the facebook plugin and re-installed version 1.7.4 

Any guidance would be greatly appreciated.

Kind Regards
Kate

**Comment by mengyingdu** [comment]
Hi Kate,

Can you tell us more details so we would try to repo? A screen shot would be better.

When you said you 'delete' this product, did you delete it from woocommerce  product editor or your site? If it was the second case, it won't sync to facebook. Can you try to delete in product editor instead?

Generally, if you go to woocommerce settings page -> integration -> facebook for woocommerce->re-config
It should clean up all data (including the incorrect product information)

Let me know if you need more help.

Thanks.

**Comment by katecos** [comment]
Hello,

Thank you for your email. I had done that step before putting up my post.

I have attached screen shots to show you what my pages are looking like.

Please let me know if you have any other suggestions!


Kind regards,
Kate.


KATE COSGRAVE
KCCM DESIGN
Director, Interior Designer
M +61 431 331 720
W www.kccmdesign.com.au E kate@kccmdesign.com.au





This e-mail may contain information which is confidential, subject to legal privilege and /or protected by copyright. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy all copies of this email.

**Comment by dmitridr** [comment]
Hi Kate,

Could you post the screenshots here?
https://github.com/facebookincubator/facebook-for-woocommerce/issues/203

If you attach them via email, we do not see them. Thank you!
A link to the product itself (The good one and bad one) would also help in this case.

P.S. Please keep in mind, any replies you make to GitHub emails will be public and show up in our repository under the issue in question.

**Comment by katecos** [comment]
Hi, screen shots attached. 

![screen shot 2018-01-09 at 12 01 46 pm](https://user-images.githubusercontent.com/35220248/34748057-eaf96e3e-f5ee-11e7-84a7-34a3adcf63cb.jpg)
![screen shot 2018-01-09 at 12 02 37 pm](https://user-images.githubusercontent.com/35220248/34748058-eb2afa8a-f5ee-11e7-94ab-d4353a61e84d.jpg)
![screen shot 2018-01-09 at 12 03 12 pm](https://user-images.githubusercontent.com/35220248/34748059-eb5b8484-f5ee-11e7-9973-6e7f503073f5.jpg)

Link to good product: https://www.facebook.com/commerce/products/1524701480983773/

Link to bad product: https://www.facebook.com/commerce/products/1938469862836999/

I have just noticed that the bad product notes "People cannot currently see this product because it is not marked as published for sale on Facebook." Regardless, there seems to be something wrong at the back end....

Thanks,
Kate.

**Comment by dmitridr** [comment]
Hi Kate,

Thanks for sending over the info! It's very helpful.

I see your catalog was created back in September. The 'bad' product was created in November, and the right version was created in January. There are two options to fix. 

1. I can just delete the 'bad' product for you right now from FB, it shouldn't appear again.
2. If you reset from scratch (*not* a Force Resync), following the exact steps Mengying described, the catalog will be deleted and recreated, and all your products will resync and this product should disappear. This will also fix any other 'bad' products if they exist.

Let me know which you prefer!

As for the original cause : It's possible for this to occur if you hit 'Clear All MetaData' on the product. Then update the product later. It may also be possible this was a bug in an older version of the plugin.

**Comment by katecos** [comment]
Fantastic, re-set worked! Thank you for your all your help and fast responses.

Kate.

**Comment by dmitridr** [comment]
Glad I could help!
