### ISSUE TITLE
Do not sync on test environment

### ISSUE THREAD

**Issue by mmtomm** [facebookincubator/facebook-for-woocommerce#205]
Hi,

I'd like to request a feature, that there is no sync to FB within or out of my testsystem.
Background: For testing, I use to make a copy of my production system on a subdomain starting with TEST.mydomain.com The only difference to the production is, that I restrict public access with modifications of my .htaccess file.
Some plugin authors do realise such feature in a way that they recognize subdomains starting with dev. or test. subdomains or having a admin checkbox where one can set it to testing.

Thank you
Tom

**Comment by dmitridr** [comment]
Hi Tom,

Thanks for your feature request. We're prioritizing bugs and performance issues for now, however. So we will consider it for the future. 

In the meantime, please consider sending us a pull request if you find a good way to implement this yourself! We'd be happy to review it.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
