### ISSUE TITLE
Can't remove product from Facebook for WooCommerce

### ISSUE THREAD

**Issue by crobertwatson** [facebookincubator/facebook-for-woocommerce#209]
We created several products for the holidays and now that the time has passed, we're removing them from Facebook. I've deleted the products from the Facebook Ship using the Facebook for WooCommerce product links in the WooCommerce product itself. But one product refuses to delete itself. Its ID is 1528101777270750 which no longer exists on the WooCommerce side (probably as result of many edits).

So, now that it's been orphaned from WooCommerce, how do I delete it on Facebook?

**Comment by dmitridr** [comment]
Hello,

Thanks for writing in. This is a tough situation, we really should have a better solution here, but right now the only solution is to reset the plugin entirely (namely delete the entire product catalog), which can be done by going to `Reconfigure` > `Advanced Options` > `Delete`. Then setting up again.

Alternatively, I could delete this item for you as a one-off if resetting would cause too many issues for you, but I would need some proof that you are the admin of that page, like a post. You can Email us at ads_extension_woocommerce@fb.com if you'd like to go that route.

**Comment by crobertwatson** [comment]
Thanks. I wrote an email to ads_extension_woocommerce@fb.com but got the following auto-reply:

"Thanks for your message. We're no longer responding to emails that are sent to this address..."

**Comment by dmitridr** [comment]
Thanks for your patience Rob, I got your email and I've deleted the product. 

For others who may read this, this can occur if you hit `Clear Facebook Metadata`. I advise caution when doing this : the product will remain on FB but the link to WooCommerce is severed. The only way to recover is a full reset.

**Comment by crobertwatson** [comment]
Thanks. Maybe I need to wait a bit for it to clear, but I'm still seeing it here at https://business.facebook.com/pg/allisonsapiaries/shop/?ref=page_internal (Honey Gift Set)

**Comment by dmitridr** [comment]
Thanks for flagging that. There were 4 other ids that needed to be cleared because it was a variable product, it should be gone now. If it happens again, I recommend a reset.

**Comment by crobertwatson** [comment]
Thanks! It's gone now.
