### ISSUE TITLE
Sale price being used erroneously 

### ISSUE THREAD

**Issue by erikpena** [facebookincubator/facebook-for-woocommerce#21]
# Summary
When syncing products that have a future sale defined, I've found that the products that are made available on the Facebook page are the sale price that is not in effect yet.  I double confirmed that this is an issue by looking at the same product in the WooCommerce product page and can see that the price is the normal retail price.

# The Proposed Fix
Looking through the code, it seems that the plugin is only checking to see if the sale price is more than 0, which is only half of the checks that need to happen--

https://github.com/facebookincubator/facebook-for-woocommerce/blob/8c068e68beeda66d1f716e93d682762e06b607b0/facebook-commerce.php#L968-L970

WooCommerce has another Product property called `is_on_sale` (https://docs.woocommerce.com/wc-apidocs/source-class-WC_Product.html#1402-1423) which is a boolean that should act as the primary condition for determining if the sale price should be used or not.

**Comment by dmitridr** [comment]
Thanks for flagging this. We're working on a fix around sale prices, #11 is a related problem as well.

**Comment by mengyingdu** [comment]
We've fixed this issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
