### ISSUE TITLE
Reconfigure facebook settings

### ISSUE THREAD

**Issue by terrybakshi** [facebookincubator/facebook-for-woocommerce#211]
I have changed my facebook password. After removing and reinstalling the plugin i was able to get the Reconfigure facebook settings button, upon clicking that button i go to select my facebook page to connect and post to but its not showing my my page, where as in facebook settings i am admin of the page, so its your plugin which is not showing the list of all the pages i am admin inn

**Comment by tahoff** [comment]
Thanks for flagging this issue @terrybakshi. Can you send a screenshot of the selector that isn't showing your page? If you want to use a different page than you used in setup, you'll need to go to Advanced Settings, then delete your settings and re-complete setup.

**Comment by mengyingdu** [comment]
Hi @terrybakshi ,

I wanna follow up with your issue. Did you figure out your settings? Let me know if you need more help.

Thanks.

**Comment by dmitridr** [comment]
I'm closing this as there was no follow up. Please open a new issue on us if you're still having issues.
