### ISSUE TITLE
Compatibility with Products having additional fields (Fields Factory)

### ISSUE THREAD

**Issue by miketurnermk** [facebookincubator/facebook-for-woocommerce#212]
I am trying to integrate my woocommerce store with Facebook Catalog / Pixels and having difficulty with products that have custom fields which I require for product personalisation using the Fields Factory plugin.

Using the default setup this is what happens:

1. Catalog syncs as well as all variations
2. User can choose product in Facebook and select variations but ‘custom fields’ do not show
3. User clicks ‘Checkout’ from Facebook and it takes them to the basket page
4. The basket is empty for products which have personalisation fields

Does anyone have any experience with Facebook Catalog that could provide some help?

2 ideal outcomes:

1. Facebook has the custom fields added somehow, user completes them there and the basket loads correctly. I’m not sure that this is even possible?

2. Facebook doesn’t send the products to the basket, and instead takes them to the product page where they can then view and complete these custom fields. Does anyone know if there is a way to stop the products trying to take them to the basket? - I'm assuming there is some link to the basket being provided in the feed.. can that be edited?

Any help with this would be really appreciated

Example:
Facebook store:
https://www.facebook.com/pg/OddBulls/shop

Website:
https://www.oddbulls.co.uk

**Comment by tahoff** [comment]
Hey @miketurnermk, if you go to your Page, then navigate to the Settings Tab, you can edit the destination of the Product URLs in the shop section by un-toggling the option "Use Checkout Urls".

I'll close this issue for now, if this doesn't full resolve your issue, feel free to re-open the issue.
