### ISSUE TITLE
Facebook does not display the correct price on discounted products.

### ISSUE THREAD

**Issue by CarretPan** [facebookincubator/facebook-for-woocommerce#22]
Hi.

Setting up woocommerce to enter prices without taxes and display prices in the shop with taxes included, 

in products on offer, Facebook shows the discounted price with tax included (sale price + tax) as the normal price (regular price) and the discounted price without taxes (sale price) as the final total price.

Test on Woocommerce v3.1.2, Facebook for Woocommerce v1.4.3.

**Woo product edit**
![woo-product-screenshot](https://user-images.githubusercontent.com/31343879/29709963-c26c0f70-898e-11e7-9688-377f36404fd6.png)

**Woo Shop** (Sale price 46,2809 + 21% tax = 56,00 €.)
![web-shop-screenshot](https://user-images.githubusercontent.com/31343879/29709968-c7b37c16-898e-11e7-9ba7-72d3d5741a88.png)

**Facebook Shop**

![facebook-shop-screenshot-1](https://user-images.githubusercontent.com/31343879/29709992-d858d4e4-898e-11e7-9a38-ca12a6bd1507.png)

![fb-shop-screenshot-2](https://user-images.githubusercontent.com/31343879/29710001-dcd0b03c-898e-11e7-9064-2ec25e2a67b4.png)

**Comment by dmitridr** [comment]
Thanks for writing in. It seems like there are two problems here, one is caused by issue #21 but other is that the sale price is shown without taxes. We're working on a fix.

**Comment by mengyingdu** [comment]
We've fixed this issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
