### ISSUE TITLE
&amp; instead of & displayed from feed

### ISSUE THREAD

**Issue by miketurnermk** [facebookincubator/facebook-for-woocommerce#220]
Hi,

I have setup another shop and feed into Facebook. A lot of the products have & characters in the variations; for example candles with different fragrances. i.e. "English Pear & Freesia"

However, in the drop down Facebook is displaying this as English Pear &amp; Freesia

Example:
https://www.facebook.com/commerce/products/1998445910172263/

Any idea why and how it can be fixed?

Thanks

**Comment by tahoff** [comment]
@miketurnermk, thanks for reporting this issue. This seems to be a bug on our end.

**Comment by jieminz22** [comment]
Hi,

Sorry for the late follow up. I can't repro this on our demo store and your link doesn't work anymore. Closing this issue for now and let us know if the issue still exists.
