### ISSUE TITLE
Facebook for Woocommerce issues on several sites

### ISSUE THREAD

**Issue by afielding1** [facebookincubator/facebook-for-woocommerce#223]
Hi there,

I’m not sure if something has changed on your plugin recently but we’re having a lot of trouble with it over the last two weeks on several sites – nothing has changed on our sites unless an update on theme or something else has thrown things out.

Basically on all our sites we’re getting messages saying

facebook extension error: error validating access token: the session has been invalidated because the user changed their password or facebook has changed the session for security reasons
Or
The integration page says reconfigure Facebook settings.
Or 
they have this when I check if the box is ticked for facebook:
facebook
This product is not yet synced to Facebook.
Could you please advise if something has changed. If it was just one site then I’d focus on that but given it’s happening on pretty much all of them there must be something we’re missing. 
On the most recent I’ve tried to sync up is https://www.wellnessappliances.co.uk/ to https://www.facebook.com/WellnessAppliances/
It runs through the force product resync but still nothing appears under the shop tab on FB. There are 112 products on the website and none are variable.

**Comment by tahoff** [comment]
@afielding1, thanks for noting these issues.

For the message about the access token, you should be able to click the 'Reconfigure Settings' option, go to the 'Advanced Settings' option and then update your access token. As the message says, it can change for a variety of reasons including a password change. 

The content 'Reconfigure Settings' doesn't actually indicate that something is wrong, that's the default text. I'll take a note of this, because I think it's confusing as well.

For the products that aren't yet synced, are they new products? If you click 'Force Resync' on the settings page, does the message go away? If this is the same site with the access token message, that can also prevent products from being uploaded successfully.

**Comment by afielding1** [comment]
That's helpful thank you. We'll try updating the access token. 

On the https://www.facebook.com/WellnessAppliances/ - this one we've tried to force resync, we've reset the token, reconfigured settings and everything we could think of. On the product page it says synced but under the shop tab on Facebook nothing appears other than the products that were manually added to the shop. We've tried all the above several times but no luck getting anything synced.

**Comment by sammul** [comment]
@afielding1 In the log on our side, I saw you just deleted the settings. Have you tried to upgrade the plug-in to latest version and retry everything?

**Comment by ibrahimxx** [comment]
i have a new problem , my old account is blocked from facebook , now when i try to Re-configure Facebook Settings , i get this message from facebook :  To run this plugin with Facebook, you must be an admin or editor of the Page connected to this WooCommerce store.

**Comment by dmitridr** [comment]
@ibrahimxx Assuming you have no access to the page. You can open the Javascript console (Ctrl + Shift + J) on the main page for `Facebook for WooCommerce` where you see the buttons `Reconfigure...` and `Force Resync` and type this into the console and hit enter : `delete_all_settings();`

This will reset all the FB settings inside your DB, allowing you to set up again. You can also edit the `wp_options` DB manually and remove the settings that way. 

This seems unrelated to the original question though?

**Comment by ibrahimxx** [comment]
i dont know actually when i search on google about my prblem its drive me here !

**Comment by dmitridr** [comment]
I see. Please open a new issue if you have some similar problem in the future, it helps us organize discussions about specific things on specific threads. You can go here : 

https://github.com/facebookincubator/facebook-for-woocommerce/issues

And click `New Issue` to do that.

**Comment by dmitridr** [comment]
Closing this as it has been a while since there has been a reply, if the problem persists on v1.8.7 please open a new issue on us and reference this one.
