### ISSUE TITLE
Purchase Pixel Missing

### ISSUE THREAD

**Issue by robbyswitzer** [facebookincubator/facebook-for-woocommerce#225]
Everything appears to be working fine except that there is no Purchase pixel event firing when a purchase is completed. All standard events are working and are associated with the product catalog - just not seeing the Purchase event fire. Can you help me with this? The store is bellamodastudio.com

**Comment by tahoff** [comment]
@robbyswitzer, thanks for reporting this issue. Do you have any specific payment related extensions or perhaps a customized thank you page?

**Comment by robbyswitzer** [comment]
Hey @tahoff, thanks for your quick response. No there is no added extensions for payment or thank you page.

**Comment by FlairTrade** [comment]
I'm seeing the same issue on my account as well. Shared a screenshot, at the very bottom, in a separate bug report #224

**Comment by belladonnaboutique** [comment]
Same thing here! My purchase pixel event is missing from the page. What do I do?

**Comment by sammul** [comment]
Thanks everyone for reporting. Our team is looking into the purchase event issue. This might be an issue started from 1.7.4. You can try older version to see if it can work for you. Sorry for the inconvenience. 

@robbyswitzer @FlairTrade @belladonnaboutique

**Comment by dmitridr** [comment]
We have a new version with the purchase event firing fix (v1.7.7), can you install it from the zip file in our [latest releases section](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.7), or upgrade to it through the wordpress updater?

**Comment by speechbooth** [comment]
That update fixed it for me.  Was pulling my hair out trying to search for the solution for facebook purchase firing but not being seen.

**Comment by dmitridr** [comment]
Nice, I recommend 1.7.11, because there's other bugs in 1.7.8 - 1.7.10 that were resolved, unrelated to the purchase event. Closing this out.
