### ISSUE TITLE
Purchase Pixel also missing from WooCommerce site

### ISSUE THREAD

**Issue by belladonnaboutique** [facebookincubator/facebook-for-woocommerce#227]
Hi there, 
My FB for Woocommerce plugin is not working properly with Purchase event. It stopped working 5 days ago. I am not sure what happened, as the other events seem to be working fine. The Purchase event is gone.

Also, it says Subscribed Button clicked about 5 or 6 times according to my Chrome pixel helper on many of my pages where View Content is. Not sure what is going on with that either? the site is belladonnaboutique.co

**Comment by belladonnaboutique** [comment]
I also went and did a Back Up Restore from when the purchase pixel was still working and it STILL is not showing the Purchase pixel! What can I do??

**Comment by belladonnaboutique** [comment]
UPDATE: I placed a Test order by clicking on my own Ad yesterday, and I made a "purchase" for that product with a coupon code that made it $0. I did this just as a test, to see if the Purchase pixel and Initiate Checkout Pixels were working. I DID see the Initiate Checkout Pixel on the billing page, and I did see the Purchase pixel on the order-received page after I completed the Test purchase.

In my Ads Manager >> Pixels, it did show the Purchase Pixel and Initiate Checkout Pixels as Active and received, HOWEVER, on my Ad Reporting for that particular ad, it has NOT registered ANY initiate checkouts OR purchases. I actually made TWO test purchases to see if it would show up on my ads reporting.

Why is it not showing up? I am confused as to what the heck is going on! If my Pixels are active and working, why aren't the events registering with my ads!??

**Comment by dmitridr** [comment]
Hi, 

This may have been due to a bug in the extension. See #225 . We just sent out a fix for purchase events in v1.7.7. This version is available [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.7). I recommend trying it, and waiting a few days to see if you get purchases.

**Comment by belladonnaboutique** [comment]
Hi,

Thanks for this. However, I am experiencing a very weird issue. I have
tried deactivating and deleting the other Facebook for WooCommerce plugin
so that I can install this new one, and it wont let me!

See the screen shots.

I cannot replace that plugin file with this new one if I can't delete the
original one.

I have tried logging out of my dashboard and logging back in; still doesn't
work.

**Comment by belladonnaboutique** [comment]
**It says it is deactivated but it doesn't actually deactivate!!

**Comment by dmitridr** [comment]
Hello,

That's pretty weird, unfortunately because you're replying via email, we can't see your screenshots, this is a public thread on GitHub here:
https://github.com/facebookincubator/facebook-for-woocommerce/issues/227

Could you add the screenshots there? One option if you can't deactivate is to upgrade the plugin using the WP upgrader. It should pick up the new version and download it automatically.

If deactivation is not working in general, you'd have to ftp into the server and delete the plugin files manually, though I've never heard of this problem before. It sounds like it could be a server configuration issue...

**Comment by belladonnaboutique** [comment]
Ok so I was able to de-activate the old plugin and activate the new one. I did this 2 days ago (Saturday) and NOW my Add to Cart and Purchase pixel are not even showing as active in my Ads Manager at all! 

Please see the screen shot.
![screen shot 2018-01-29 at 2 05 00 pm](https://user-images.githubusercontent.com/35646111/35528966-84084e98-04fd-11e8-96b9-d750a88da53f.png)

**Comment by belladonnaboutique** [comment]
This is very, very strange! In my FB ads manager those 2 pixels are showing as InActive.

However, when I use the Chrome pixel helper and test the Add to Cart and Initiate Checkout pixels, they do show as Active. 

I also did a Test Purchase to verify the Purchase pixel was active on my site, and it is.

Please see the screen shots. I have no idea why the Pixel Helper would show these as active but FB for some reason is showing them as Inactive.
![screen shot 2018-01-29 at 2 09 57 pm](https://user-images.githubusercontent.com/35646111/35529448-1466d940-04ff-11e8-8d24-3e32255f4728.png)
![screen shot 2018-01-29 at 2 10 16 pm](https://user-images.githubusercontent.com/35646111/35529463-1f2fe1fa-04ff-11e8-9a16-d7cd89dbfff4.png)
![screen shot 2018-01-29 at 2 10 45 pm](https://user-images.githubusercontent.com/35646111/35529479-2c18c6de-04ff-11e8-8ee5-7a63952d9787.png)
![screen shot 2018-01-29 at 2 12 06 pm](https://user-images.githubusercontent.com/35646111/35529487-320b6e84-04ff-11e8-8116-c877e3c88daf.png)
![screen shot 2018-01-29 at 2 16 02 pm](https://user-images.githubusercontent.com/35646111/35529498-37be2f9c-04ff-11e8-8625-5dcac6dad322.png)

**Comment by belladonnaboutique** [comment]
UPDATE: I did a RESET of the Power Editor. Now my Pixels are showing Active in my Ads Manager.

Thanks so much for updating the plugin! I appreciate it!

**Comment by dmitridr** [comment]
Glad you were able to resolve it!! Happy we could help. The pixel helper is usually very accurate about active/inactive, I'm not sure why Power Editor/Ads Manager had a problem with inactivity there, maybe there was some delay in the data.
