### ISSUE TITLE
Unavailable/Draft/Unpublished Items Showing Despite Re-syncing

### ISSUE THREAD

**Issue by AndsotoShop** [facebookincubator/facebook-for-woocommerce#228]
Hi, 

We have items that are no longer available in the shop and so are saved as drafts but they are still showing in our Facebook shop despite us re-syncing. Please can you help. 

Our url is www.andsotoshop.com

Many thanks,

Louise

**Comment by sammul** [comment]
@AndsotoShop can you share a specific product that is showing on Facebook but not available on your website? I looked at your facebook that there are a lot of products, it's hard for me to check one by one. Thanks

**Comment by AndsotoShop** [comment]
Hi,I’ve attached an image, none of this suppliers items are live now as she is on maternity leave. Also, we ideally want the most recent items to appear first. Many thanks,LouiseAnd so to Shop Founderlouise@andsotoshop.comwww.andsotoshop.com---- On Sat, 27 Jan 2018 22:04:47 +0000  Xia W<notifications@github.com> wrote ----@AndsotoShop can you share a specific product that is showing on Facebook but not available on your website? I looked at your facebook that there are a lot of products, it's hard for me to check one by one. Thanks  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mengyingdu** [comment]
Hi @AndsotoShop ,

As for your suggestion for the chronological sorting, I will redirect your feedback to our shop team. 
There is no attached image in your reply, can you try to upload again?

Thanks.

**Comment by groovydogs** [comment]
Hi guys, 
Experiencing the same problem: only published items should be synchronised to FB. 
Is there a solution available? 
Kind regards, 
Katrien

**Comment by mengyingdu** [comment]
Hi @groovydogs,

We should fix Draft/Unpublished products issues in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6) We have 10 fixes plus 1 content enhancement. I do recommend you upgrade first and then try to full reset , force-resync.

If you still have this problem, please let us know.

Thanks.

**Comment by mengyingdu** [comment]
Hi @AndsotoShop ,

I have found 2 pixels from your site, are you using other plugins for pixel? If it is, I do recommend not to use them together, they will have conflicts.

Also, your plugin version is 1.5.1 which is very, very old. After upgrading, I recommend you follow these steps:
1. go to 'woocommerce' -> settings  -> integrations -> facebook-for-woocommerce
2. In the blue panel, click on 're-config'
3. In the popup window, 'advance option' -> delete your settings
4. back to the blue panel, click on 'get started' -> finish setup

Can you try to upgrade to [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6) ?
 
Thanks.

**Comment by dmitridr** [comment]
We should have fixed this in 1.8.7. Closing this out. Please re-open (or create a new issue) if the issue still occurs after upgrading and resyncing.
