### ISSUE TITLE
Plugin not updating

### ISSUE THREAD

**Issue by djwilko12** [facebookincubator/facebook-for-woocommerce#23]
On Woocommerce´s site says the plugin´s latest version is version is 1.4.3.
I have already installed the previous version (1.4.2) on my Woocommerce but there is no notification asking me to update to the latest version (same as it happens with all the other plugins in Wordpress).
Then i went to Woocommerce site to download the latest version and upload it manually, but it says that i cannot do that because the folder already exists.... Too bad....
What can i do? Why i dont see an update notification as it usually happens???

**Comment by dmitridr** [comment]
Hi,

I'm not sure why you don't see the update notification, but we do have a resolution for you. 
You should be able to uninstall the plugin you have fully and then try to install the new version. Don't worry, your data and connection with facebook is still saved in the backend. 

You can download the newest version, 1.4.3 from WooCommerce. but we recommend you download the latest version (as of this writing v1.4.5) from our Github directly, there's typically a delay until WooCommerce updates their version from our repository. Here's the link:

https://github.com/facebookincubator/facebook-for-woocommerce/archive/master.zip

**Comment by djwilko12** [comment]
Thanks for your reply.
I checked on another Woocommerce that i manage which has a version 1.4.1 of the plugin installed and the same thing happens: there is not notification of any update... i think you should check that. Its difficult to be checking every time there is a new release and update it manually on each of the sites.

On the other hand, do you say that i can deactivate the plugin, remove it and the information of the Facebook Shop will still be there? Or i need to configure everything from scratch again?

**Comment by Trebacz** [comment]
@djwilko12 I have deactivated the plugin, deleted the folder and replaced it with the Github version. Then just activate the new version. All my settings were retained.

It's a bit of a pain, but it's an okay workaround until the update process gets fixed.

**Comment by djwilko12** [comment]
Yes, thank you! I have deactivated the plugin and remove it from WP backend and i could update the plugin retaining the settings as well. Anyway, please try to fix the way wordpress recognize the plugin´s update, since there should be an easy way to get notified of a new update and be able to update it easily (as it happens with most of the wordpress plugins).
Thanks!

**Comment by dougaitken** [comment]
@djwilko12 @Trebacz 

If you download from WooCommerce.com and connect your account - you will see any updates in your Plugins, and extension management area

https://woocommerce.com/products/facebook/

**Comment by djwilko12** [comment]
Hello @dougaitken
What do you mean with "connect your account "?

What I did was logging in to woocommerce.on and downloaded the plugin. Then I installed it in wordpress as a plugin. Doing that I never received any update notification...
Please explain what am I missing ?

**Comment by Trebacz** [comment]
My account is connected. I can go to WooCommerce>Extensions>WooCommerce.com Subscriptions, but I couldn't see the current update. On this page Facebook for Woocommerce shows as "Active".

That said when I go to Plugins> I don't see an update available. Right now I'm running on Version 1.4.5 and Github appears to be on version 1.5.1. Fortunately, I'm not in need of any of the features at this point...

**Comment by dougaitken** [comment]
The main change is Facebook Pixel for WordPress, @Trebacz - the version on WooCommerce.com is `1.4.5` but it will be updated asap.

> Please explain what am I missing ?

If you're running WooCommerce 3.1, you can manage any WooCommerce.com extension updates from the new [management area](https://docs.woocommerce.com/document/managing-woocommerce-com-subscriptions) @djwilko12 👍

**Comment by dougaitken** [comment]
@Trebacz @djwilko12 `1.5.1` was deployed by WooCommerce.com 7 hours so should be showing updates if you have your WooCommerce.com account connected

**Comment by Trebacz** [comment]
@dougaitken It did appear and updated just fine using the "normal" plugin update method in Wordpress. Thank you...

**Comment by dmitridr** [comment]
Seems like this is resolved. Keep in mind there is typically some delay (~48 hours) between the version being out on GitHub and WooCommerce releasing the update through their page.
