### ISSUE TITLE
Wrong time zone in events

### ISSUE THREAD

**Issue by chalkandmoss** [facebookincubator/facebook-for-woocommerce#232]
I assume events were created automatically for me when I used the facebook for woocommerce extensions, as several events appear in ad manager / pixels. However, the events are showing the wrong times. It's now 1.30pm Wednesday in the UK, and events are showing up until 8pm Wednesday. The time zone both for my facebook and wordpress are listed correctly as London, so I don't know where this error is coming from.

**Comment by sammul** [comment]
@chalkandmoss Can you share a your website url for me verify this? Sometimes it takes some time(not hours though) for Facebook side to process the pixel event. If you can share some screenshots of what you observed, it would helpful. Thanks

**Comment by chalkandmoss** [comment]
Hi, thanks so much for your reply. The URL is www.chalkandmoss.com. I've attached screenshots showing the time on the clock (on my Mac) and the time recorded by the pixels on the graph, which is later than the actual time it is now. You see it's correctly showing London UK as the location. 
I created the pixel yesterday morning. 

![screen shot 2018-01-24 at 21 40 58](https://user-images.githubusercontent.com/35746921/35358714-77fa9220-014f-11e8-973c-4e139883d573.png)

![screen shot 2018-01-24 at 21 43 30](https://user-images.githubusercontent.com/35746921/35358769-ab974826-014f-11e8-9f73-b82ab1b98283.png)

**Comment by sammul** [comment]
@chalkandmoss Seems like a bug in Ads Manager. I checked in other data tools the pixel is firing correctly. So likely it's just a UI issue. Thanks for reporting. I'll let that team know about this

**Comment by sammul** [comment]
@chalkandmoss Hey, just let you know that the team(Ads Manager) is already on this issue and they will fix asap

**Comment by chalkandmoss** [comment]
Great, thanks for the quick action!

**Comment by sammul** [comment]
@chalkandmoss the team worked on Ads Manager said the dotted part is kind of predicting the pixel traffic, which seems very confusing even to me. In the meanwhile, do you mind check in facebook analytics tool https://www.facebook.com/analytics/ to see if your pixel is working fine? Thanks

**Comment by dmitridr** [comment]
No response for a while so closing this out. If the issue persists or occurs again please open a new issue on us and reference this one. Generally if you suspect the bug is in ads manager (if the pixel helper tool says it's working) it's more effective to report this via the ads manager support channel:

https://www.facebook.com/business/help/1577619702492199
