### ISSUE TITLE
'Purchase' tracking event not firing for Payment Gateways that use ajax

### ISSUE THREAD

**Issue by TimBHowe** [facebookincubator/facebook-for-woocommerce#236]
When the plugin was updated to the [1.7.3 version it moved](https://github.com/facebookincubator/facebook-for-woocommerce/compare/v1.7.3...master#diff-1e47101d4ffb440f08405b2a3cfc7d4eR290) the `inject_purchase_event` function to be fired on the `woocommerce_payment_complete` rather then the `woocommerce_thankyou` action. 

This causes an issue with payment gateways that use ajax to fire the `payment_complete` function as it doesn't load the page and inject the purchase events pixel code.

I would suggest you fire both the `inject_purchase_event` and `inject_gateway_purchase_event` on the `woocommerce_thankyou` action and test the order status to determine if the event should be triggered or not. This should be possible as the `woocommerce_thankyou` action passed the `$order_id` to the function and you can use the `wc_get_order()` function to get the order object.

**Comment by sammul** [comment]
Thanks for suggestion. 

cc @mengyingdu @dmitridr

**Comment by dmitridr** [comment]
Hello, we fixed a very related issue with these injections in [v1.7.8](https://github.com/facebookincubator/facebook-for-woocommerce/releases). Could you try upgrading? It may address the issue.

**Comment by TimBHowe** [comment]
@dmitridr That looks like that fixed it. Thanks.
