### ISSUE TITLE
facebook for woocommerce

### ISSUE THREAD

**Issue by VintageHipDecor** [facebookincubator/facebook-for-woocommerce#237]
This plugin has stopped working and is marked as inactive on our website. I've tried downloading it again but had no success in making work again. Items in our facebook shop have not synced for months.

**Comment by sammul** [comment]
@VintageHipDecor Can you share which version are you on? Also please include your website url.

**Comment by VintageHipDecor** [comment]
woocommerce version 3.2.6

https://vintagehipdecor.com

**Comment by sammul** [comment]
@VintageHipDecor I was asking the version of our plug-in you are using. Have you tried deleting everything(the plug-in and settings) and install the newest version 1.7.8?

**Comment by VintageHipDecor** [comment]
On my dashboard, i don't see an installed plugin by this name. I see it under woocommerce>extentions>woocommerce subscriptions. In other words, there is no place for me to see what version it is or to uninstall and install it again. There is an option of downloading it, but the files are not zipped, so I'm having a hard time uploading it to my site.

**Comment by mengyingdu** [comment]
Hi @VintageHipDecor ,

You can easily download the zip file [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases): note only the 'facebook-for-woocommerce' is what you need.

After installation and activation, you can go to 'woocommerce'->settings->integration:
1) if you see 2 blue boxes:
 re-config facebook settings --> advanced option -> delete, close the pop up window.
Then click 'get started' , set up your new settings in the new pop up window.
2) if you see only 1 blue box 'get started', just click it and finish the step for set-up.

Let me know if you need more help.

Thanks.

**Comment by VintageHipDecor** [comment]
Thank you ever so much! That helped me in a few easy clicks to finally have my facebook shop synced with my website again. Yay!
