### ISSUE TITLE
Inexsistent sale price

### ISSUE THREAD

**Issue by djwilko12** [facebookincubator/facebook-for-woocommerce#24]
The Facebook shop is showing some of my products with a sale price, but the original product on Woocommerce has no discount, it just has the original price. Why FB shop adds some discount on it? Its really strange...

**Comment by mengyingdu** [comment]
Hi,
Have you ever previously ran a sale? We won't remove the sale automatically. Can you try force re-sync products? We are working on to fix it.

**Comment by djwilko12** [comment]
Yes, we ran a sale previously, but its been weeks without any discount. I tried yesterday forcing the re-sync, but SALE prices still there... I think is really important you can fix that issue. Clients dont want to get confused with prices.

**Comment by mengyingdu** [comment]
Yes, this is an issue for Facebook for Woocommerce and we have engineers currently working out this. For a temporary solution, can you try remove this product and then add as new product ?

**Comment by djwilko12** [comment]
Thanks @mengyingdu 
I have deleted the product and then updated the woocommerce product page so it can recreates the product on facebook and the price is now shown correctly. Anyway, its great you can fix it because if you have many products, it is too much time consuming to be deleting and updating each product page.
Please let me know once is fixed.
Regards!

**Comment by dmitridr** [comment]
This looks related to #11 or #21. As @mengyingdu said, we are working on a fix for all of these.

**Comment by mengyingdu** [comment]
We've fixed this issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
