### ISSUE TITLE
Product description does not save using Woocommerce Subscriptions 

### ISSUE THREAD

**Issue by StefanVB** [facebookincubator/facebook-for-woocommerce#245]
As per #221 

When placing plain product description text in the "Facebook" tab within the "Facebook Description" box but on saving the text block would go blank again. The "simple product" type works, however the "simple subscription" product ([Woocommerce Subscriptions Extension](https://woocommerce.com/products/woocommerce-subscriptions/)) does not.

This has resulted in Facebook product descriptions which display short code text instead of plain text descriptions (see [link](https://www.facebook.com/commerce/products/1735975699779092/)).

**Comment by mengyingdu** [comment]
Hi @StefanVB ,

Did you see that for subscription product in old version?

Thanks.

**Comment by StefanVB** [comment]
This happened in the old and new version

**Comment by mengyingdu** [comment]
Hi @StefanVB,
When you see it last time, is that happen right after you sync all products? 

I found a fix for subscription product in our changelog, it seems it was broken now.

**Comment by mengyingdu** [comment]
Hi @StefanVB,

From this issue, the WooCommerce Subscription plugin update its API from 2.2. So our original support for subscription product was broken. I did fix it and will add it in next release.
Ref: https://github.com/woocommerce/woocommerce/issues/14810

Thanks.

**Comment by mengyingdu** [comment]
It was fixed in beta v1.8.0 and [v1.8.1](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.1)
