### ISSUE TITLE
Facebook for Woocommerce breaks frontend for admin

### ISSUE THREAD

**Issue by jessdaddy** [facebookincubator/facebook-for-woocommerce#247]
Hi. I have tried a few times to use this plugin. Setup goes fine and products are uploaded to the shop no problem. However, as long as the plugin is enabled, I cannot see the front end of my site while I am logged in. If I view the page as a visitor, everything seems okay. Using Astra Theme if that makes a difference.

Also, since I used the plugin to upload my products, and have since had to disable it, product ids are not matching up with my manually installed pixel. With the plugin enabled, product matching is fine. With it disabled, there are errors. Please advise as to how I might be able to enable the plugin and still see the front end while logged in. Thank you.

**Comment by mengyingdu** [comment]
Hi @jessdaddy ,

Can you explain the detailed scenario 'unable to see the front end of your site'? A screen shot could be better to help understand.

I need more information from you to investigate:
How about your woocommerce version and facebook-for-woocommerce version?
What's your store url and fb page url?

Thanks.

**Comment by jessdaddy** [comment]
cant do a screenshot for a while. site is kind of busy. but it's easy enough to explain. can see the admin bar nothing else beneath it except white. backend is fine. if I go to front end from admin ,though, blank.. nothing except the admin bar at the top.

**Comment by jessdaddy** [comment]
facebook for woocommerce is latest version available here on the site. 1.7.8 woocommerce 3.2.6 thank you

**Comment by mengyingdu** [comment]
Hi   @jessdaddy,

I activate astra theme and I'm on [v1.7.11](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.11).  
I can't reproduce your issues:
log in as admin --> 
under admin bar, click on 'go to store' --> 
This is what I see in my demo store:
![astra theme](https://user-images.githubusercontent.com/24535640/35695672-18515fa2-073a-11e8-9429-ff8199aa11a7.jpeg)

Any other plugins you are using which could probably cause the issue?

I need more information from you in order to help:
Your site url
Your Facebook page url

Thanks.

**Comment by jessdaddy** [comment]
Hi and thanks for your reply. 
site URL: https://stylemonkey.xyz
FB Page: https://www.facebook.com/wearmorebananas/

Thank you

**Comment by mengyingdu** [comment]
Hi @jessdaddy,

I think you deactivate our plugin now. As my reply before, I can't repo your problems with Astra theme (I can see front-end of my site as login admin).  I checked  our log and there is no error on your site.

What other plugins are you using? 
Are you using adblock?

Thanks.

**Comment by jessdaddy** [comment]
yes, i use adblock, but of course it's turned off on my own site. I am running quite a few different plugins. I tried disabling them all but the problem still occurs. are there any plugins with known issues. i can give you temp admin access if you want to take a look. I am not sure how to message directly here on github though or how to make a reply private. please advise. thank you

**Comment by jessdaddy** [comment]
i downloaded and installed the 1.7.11 version. still same thing. and I cant get any other pixel solution to work because content IDs not matching up with the weird suffixes the plug ads when syncs with shop. I have no idea what to do. I have tried deactivating as many plugins as possible without breaking my site completely. still, nothing seems to help. turn it on, site frontend goes off for admin.

**Comment by jessdaddy** [comment]
found it! Clearfy was the culprit. just deactivating and reactivating didnt fix it. had to reset the settings in Clearfy and then re-enable them. After that, plugin seems to be working as it should. :) 🥇
