### ISSUE TITLE
No products in Facebook page shop?

### ISSUE THREAD

**Issue by sm7uge** [facebookincubator/facebook-for-woocommerce#248]
My Woocommerce products once were synced to my FB shop on my FB page. At one time they disappeared, but I didn't notice until recently.

The sync works in a way that the products show up in the product catalog in business manager, but not in the shop.

Just updated to v1.7.10 and resynced, but no change.

Why won't the products show up in my FB shop?  (undless I'm totally mistaken, they should?)

**Comment by mengyingdu** [comment]
Hi @sm7uge,

Yes, they should appear on your facebook page shop. We fixed a bug in 1.7.10 and just released [v1.7.11](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.11). 

Can you upgrade and re-config your fb setting?
steps:
1. deactivate and delete plugin with old version
2. go to 'WooCommerce' -> Settings-> Integration -> facebook for woocommerce -> re-config your facebook settings -> advance options -> delete
3. 'get started' on original 'facebook for woocommerce' window
4. finish set-up

Your products should finished synced and then your shop will finish processing after that. But as page admin, you should be able to see your products under your shop page. 

If it still doesn't work, please tell us your site url and facebook page url for further investigation.

Thanks.

**Comment by sm7uge** [comment]
In your link to 1.7.11 it seems like I get 1.7.10 when downloading?  at least that is 1.7.10 stated after installation, even if the zip-file states 1.7.11.

When the sync was finished I got an error above Facebook window under integration:

Facebook extension error: Facebook for WooCommerce
(#200) Permissions error

One line says "Created product item XXX on Facebook." But that's just one out of 28 products. There is 26 products in business manager product catalog and 26 products in the store.

By the way, what's up with Wordpress plugin updates?  Not just for this plugin. When I went there to delete v1.7.10 there was an automatic update to 1.7.11, but I choose to delete instead of updating. After installation of what I thought was 1.7.11, which shows as 1.7.10, there is no automatic update displayed in wordpress plugins. I've seen this behaviour for several plugins the last week or so...

**Comment by sm7uge** [comment]
I saw another thread about something wrong with 1.7.11, so I now downloaded the version again and installed and now everything seems okay. Products synced to Facebook as they should.

Thanks.

**Comment by wazman21** [comment]
I appear to be having a similar issue on 1.7.11 - what is the delay I should expect between syncing a product feed into Product Manager (done, working well), and the products showing up on the Facebook Page front end?

My Facebook for Woocommerce settings confirm there are 97 products in my feed, and I have even been able to create Ads with the product feed, but nothing shows on Shop tab of Facebook page (https://www.facebook.com/aesthetiqueliftwear/)

**Comment by sm7uge** [comment]
Wazman21, there is no shop on your Facebook page?  Turn it on under the settings.

**Comment by wazman21** [comment]
It's definitely they and on, but is empty without the product feed working

**Comment by sm7uge** [comment]
Hm, i can't see it...?

**Comment by wazman21** [comment]
Yep, because you aren't an admin. It's not visible when empty. Because the feed isn't working.

**Comment by dmitridr** [comment]
Could be the same problem as #281 ? The shop selector is easy to miss during the setup, and can default to off in some cases.

**Comment by wazman21** [comment]
Thank you @dmitridr - can't believe I missed that - legend.

**Comment by dmitridr** [comment]
Nice. Closing this out.

**Comment by dragad** [comment]
Hello ,
I am having the same issue. My products are synced successfully. They don't appear under shop tab.Shop tab is ON. Tried to delete reconfigure again.No success. Cataloge is empty with 0 products.FB support couldn't resolve my issue.Help please! My facebook page is  https://www.facebook.com/pg/draganadujovic%20/shop/?ref=page_internal
Tried to do the same with  test page SHOP products and guess what ? products appear there .

<img width="1280" alt="screen shot 2018-06-25 at 9 11 05 am" src="https://user-images.githubusercontent.com/40546943/42050102-0eef8078-7ad6-11e8-8cb5-063dc8779162.png">

Tried also to delete plugin and install again did not help

**Comment by dragad** [comment]
<img width="1280" alt="screen shot 2018-06-27 at 10 02 46 am" src="https://user-images.githubusercontent.com/40546943/42050249-69b00ffa-7ad6-11e8-9bda-c0b6fbd1029d.png">




<img width="1280" alt="screen shot 2018-06-27 at 10 05 29 am" src="https://user-images.githubusercontent.com/40546943/42050266-6ef28c18-7ad6-11e8-9a56-5b605345f12a.png">

**Comment by walpap** [comment]
I had exactly the same problem. I was using an old version of the plugin. I´ve just updated it to 1.9.1 and reconfigure the plugin, and all my products started to appear in the shop tab. Good luck!

**Comment by dragad** [comment]
Thank you @walpap I am using the same plugin as you 1.9.1 but still doesn’t work. It looks like the page has issue because I was able to sync products by opening new FB page. 
But still mistery why the shop is not working on my primary page :(

**Comment by TavtheDuck** [comment]
Hi 
I followed the steps about deleting the old version, installing the new (1.9.1) one and re-synching. 
The same issue as before is still happening. Some of the item's images do not appear in the FB Shop... 
Thanks in advance
Kris

This is my FB link:

https://www.facebook.com/pg/thetavsterduck/shop/?rid=36053343534&rt=6


![image](https://user-images.githubusercontent.com/41162980/42647198-4063c186-85d1-11e8-9889-09324531c29e.png)

**Comment by TavtheDuck** [comment]
The products images that do not show on the FB Shop also do not show in the backend of the Shop/Catalog.

![image](https://user-images.githubusercontent.com/41162980/42647486-27f3bace-85d2-11e8-85d2-f987cf067e29.png)

**Comment by pps559** [comment]
ive done everythgin recommended.  i have the most current versions of everything.  ive synched, resynched, same result.  I can see the products on the back end, but when i go to my business page and click shop, it tells me I have no products.

**Comment by dragad** [comment]
I had the same problem, but after I deleted the page from business manager, and I have synced products again, my shop with products appears fine.

**Comment by dragad** [comment]
Yes correct, go to business settings, click “Pages”.Select Facebook page that you want to delete from business manager and click remove.Confirm remove again, and try to sync products again. And check the shop tab after products are synced.

**Comment by pps559** [comment]
i just looked it up, and i dont thik i have a facebook business manager account.  But i still dont see my products on "shop" on my business page.  They are there when i verify through woocommerce and pixel, but when im on the actual facebook business page, nothing. PLEASE HELP!

**Comment by dragad** [comment]
I had exactly the same problem. I think you do have page connected with bus. manager because I see your screenshot with catalogue from bus.manager.Go to YouTube “how to remove Facebook page from business manager follow the steps

**Comment by pps559** [comment]
nope.  i dont have those options.  when i click the drop down on facebook, there is no business manager setting

**Comment by pps559** [comment]
im looking at everything. my pixel is firing, i have pixel helper, but when i try to connect to my woo db facebook says the pixel is not ready

**Comment by pps559** [comment]
totally lost.  ive done and redone everythgin and nothing is working.  to the piont that im angry.  is there an easier way?

**Comment by pps559** [comment]
HELP

**Comment by dragad** [comment]
I know it gets frustrated. I have products synced but still 6 products are under processing. Not yet processed :( It is always something. I would try to remove that page first from bussines  manager.They were saying here, that they had issues with shop when is connected to bus. Manager

**Comment by pps559** [comment]
I dont think you are understandig me.  I dont have the business manager.

**Comment by pps559** [comment]
ok, just ceated a business manager page - still the same result.  I need like a phonecall or screenshare or something

**Comment by firo100** [comment]
Platform shop settings
Use Checkout Urls

I have another products on my shop tab and can't add any photos and price or anything I need help please

**Comment by firo100** [comment]
![untitled](https://user-images.githubusercontent.com/45554224/49377439-daf8a380-f712-11e8-8c22-c92975aec5cc.jpg)
![untitled123](https://user-images.githubusercontent.com/45554224/49377446-dd5afd80-f712-11e8-9bd0-a5f52d4b9285.png)

the first one when I go to shop settings 
the second one when I go to shop tab I find these products that need to be deleted

**Comment by sm7uge** [comment]
firo100,

In woocommerce:

- Delete the demo products, or
- Unpublish the products, or
- Edit the products and untick the box "Visible" on Facebook

**Comment by baratoini** [comment]
Im also having the same. It says pixel has been created and syncing but it does not show on my page
![image](https://user-images.githubusercontent.com/65301684/81837908-07575700-9578-11ea-98e1-c85e3350a107.png)

**Comment by baratoini** [comment]
i still dont see the products in my fb page shop. :(

![image](https://user-images.githubusercontent.com/65301684/81838362-982e3280-9578-11ea-8946-a1e479e68b72.png)
