### ISSUE TITLE
Variation attributes uses the slug name instead of the attribute name

### ISSUE THREAD

**Issue by mmtomm** [facebookincubator/facebook-for-woocommerce#25]
when I follow the link in backend 'Created product item 1234567890 on Facebook.' then I see, that the plugin submitted the attribute slug instead of the attribute name.
For example:
I have a T-Shirt from a certain brand in 3 sizes. I have size attributes setup for that specific brand. The names of the attributes is Small (S), Medium (M), Large (L) the slugs for those are brandX-small, brandX-medium, brandX-large.
When I view this product on www.facebook.com/commerce/products/1234567890/ it displays e.g. 'brandX-small' in the variations drop down instead of 'Small (S)'
In the Productdetails area below the dropdown it displays the product title and the selected variation and here it is correctly displayed using the attribute name as e.g. 'Small (S)'

**Comment by samnazarko** [comment]
Does adding your variation to cart actually work for you?

Adding a product with a variation doesn't work properly: the cart remains empty. See https://www.facebook.com/commerce/products/1623697274370340/ for an example

I have contacted Automattic and they sent me an @fb.com email to get in touch with; but they recommended I comment here.

**Comment by mmtomm** [comment]
yes, adding the right variation to the cart actually works on my site!
[example](https://www.facebook.com/commerce/products/1345711468879890/)

**Comment by tahoff** [comment]
@mmtomm Thanks for reporting this issue! We've fixed the issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.0). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
