### ISSUE TITLE
Facebook shop says no products are shown 

### ISSUE THREAD

**Issue by chloeisaac1997** [facebookincubator/facebook-for-woocommerce#250]
When I go into my shop on FB it says there are no products shown, but I have linked all products from my website and has been working fine until this morning. Having the same issue with Instagram saying the link may be malicious.

**Comment by mengyingdu** [comment]
Hi @chloeisaac1997,

Sorry to hear your problems.

What's  your woocommerce version?
What's your plugin version?
Can you tell us your site url or Facebook page url so I can have more information to help investigate your issues?

Thanks.

**Comment by mengyingdu** [comment]
Also, can you share a screen shot for the malicious link error?

**Comment by chloeisaac1997** [comment]
Facebook sorted it for me. Thanks for your help anyway!
