### ISSUE TITLE
New "facebook_for_woocommerce_integration_pixel_enabled" filter applied to early

### ISSUE THREAD

**Issue by mister** [facebookincubator/facebook-for-woocommerce#251]
Hello,
I'm PixelYourSite developer and trying to integrate `facebook_for_woocommerce_integration_pixel_enabled` filter. The filter is great itself, but it is applied too early, when other plugins, like ours, can be not ready yet. I'm going to make pull request which fixes the issue.

**Comment by mengyingdu** [comment]
Thanks for reaching out.
We will review it!

**Comment by dmitridr** [comment]
Hey @mister thanks for the contribution!! I'm closing this out since it seems the fix is committed.
