### ISSUE TITLE
Variant Price Not Working properly

### ISSUE THREAD

**Issue by Ampmedia-DEV** [facebookincubator/facebook-for-woocommerce#253]
Hi,

After yesterdays issue with V.10 and the permissions, we reverted to 1.7.9 and it worked OK.

Today we tried to update to 1.7.11 using the source code from this site, but the plugin version is still saying V1.7.10 and that we should update.  Plus the permission error is back again and our product variants in Facebook are showing the wrong pricing again.

Sorry guys, but we are reverting to 1.7.9 which seems to be stable and will wait until all of the above issues are resolved.

Cheers

**Comment by Ampmedia-DEV** [comment]
Ok so 1.7.9 also has the permission error so we are going back to 1.7.8 which seems stable

**Comment by mengyingdu** [comment]
Hi @Ampmedia-DEV ,

I'm really sorry that there is sth wrong when I created the release. (It didn't sync correctly between internal change and github.)
I just updated the zip file and i double checked it as 1.7.11.

Again sorry and thanks for your timely report that helps us such quickly.

 Facebook Ads Team

**Comment by Ampmedia-DEV** [comment]
Hi,


Is there a new version of the pixel plugin as well?


Cheers

 


Simon Hay

Media Amplify

M +61 473 064 946

E simonhay@ampmedia.com.au

**Comment by Ampmedia-DEV** [comment]
Hi,


Also just to let you know that in the source package for 1.7.8 the pixel plugin comes up saying that it is version 1.7.7.


Cheers


Simon

 


Simon Hay

Media Amplify

M +61 473 064 946

E simonhay@ampmedia.com.au

**Comment by Ampmedia-DEV** [comment]
UPDATE

Have now successfully installed V1.7.11 and no permission errors, but the variant pricing is still not working correctly in the Facebook shop... have raised a seperate issue for that.

We love this plugin!  So really want to help to get the bugs resolved.

**Comment by mengyingdu** [comment]
Hi @Ampmedia-DEV ,

Thanks for your feedback! To clarify, ALL you need is only the facebook-for-woocommerce.vXXX.zip file. This repo host 2 plugins, another one is in pre-launch status (not fully launched yet). If you use two together, you may have some problems.

**Comment by mengyingdu** [comment]
As for the price issues, I'm working on a fix now. I would suggest you just use v1.7.8 before new release. T
Thanks.

**Comment by mengyingdu** [comment]
Hi @Ampmedia-DEV ,

I can't repo your problem for variant price:
step:
1.  create a variable product with blue ($80) and green ($60).
2. go the fb, show correct price (with tax)
Screen shot:
![screen shot 2018-02-02 at 8 52 06 am](https://user-images.githubusercontent.com/24535640/35745011-b48e8702-07f6-11e8-8d6f-91e1bb4172c3.png)
![screen shot 2018-02-02 at 8 52 27 am](https://user-images.githubusercontent.com/24535640/35745023-b9ea2882-07f6-11e8-965d-e777036eaa34.png)
![screen shot 2018-02-02 at 8 52 37 am](https://user-images.githubusercontent.com/24535640/35745025-bda53912-07f6-11e8-9e30-c1f771845c58.png)

**Comment by mengyingdu** [comment]
Let's keep discussion  in #254
