### ISSUE TITLE
Product Variant pricing Issue: feature request for Variant Price Range

### ISSUE THREAD

**Issue by Ampmedia-DEV** [facebookincubator/facebook-for-woocommerce#254]
Hi,

We have updated to V1.711 this morning an have no permission errors which is great.

**BUT**

The product pricing in Facebook shop is not correct for our variable products.  We sell a range of canopies for 4WD vehicles and the variants range in price from $3,800 to $6,050 depending on the colour/spray options that the client selects.  For all of the variants we have set the Default Form Value to the option 'Powder Coated White' which should have a price of $3,800 or $4300 depending on whether the vehicle is 2 door or 4 door.

However, in Facebook the pricing is behaving very strangely.  As you can see from the attached snippets, on the front page of our facebook page the pricing is showing the correct price as per the default variant we have selected in the website.  

![fb snipet on main page](https://user-images.githubusercontent.com/36017780/35713170-970f29be-0811-11e8-8292-9d354aae0194.jpeg)

**BUT** in the shop itself and also inside the category view in the shop for this product group,the price is defaulting to a variant called Colour Coded - Solid Colour - Outside Only which is significantly more expensive.  This option is the 4 variant option for all of the products.

_View in the shop_
![fb snippet from inside shop](https://user-images.githubusercontent.com/36017780/35713172-97ae3efa-0811-11e8-9767-01f059bd8f4b.jpeg)

_View in the category_
![fb snippet from full category viiew inside shop](https://user-images.githubusercontent.com/36017780/35713171-977147e8-0811-11e8-92ea-ae0c61d07020.jpeg)

This is a serious issue for us as the price difference is so substantial between the product variants - it is not like a T-shirt where the size cost variant may be only a few dollars.

Can someone please take a look at this for us.  Our Facebook page is https://www.facebook.com/TheBushCompany/

**Comment by Ampmedia-DEV** [comment]
Update - in Woocommerce the variant products pricing is shown in a range.  For us the best option is to have the Default Variant Value displayed in Facebook rather than the Price Range, but this may be different for other users.

The best fix would be for there to be an option added to the plugin specifically for variant products so that users can select either the Default Form value or Variant Price Range.  Not sure if this is achievable?

**Comment by mengyingdu** [comment]
Hi @Ampmedia-DEV ,

Thanks for your feedback and suggestion about the price range. It's a good idea! To clarify, this is not a bug in v1.7.11, instead, this shop feature is not supported by our shop team. (Basically, they will show the last (chronologically) created children in your woo product editor. I will redirect this feedback to our shop team!

This is a temporary workaround for you to achieve the appearance you want:
In Woo product editor, delete the product you want to show as default price.
Then add it as a new one, then update product.

I will keep this issue open and update it once this feature is supported!

Thanks.

**Comment by Ampmedia-DEV** [comment]
Hi,

 

Thanks for the update.

 

So as it stands the plugin is not able to support variable products effectively.  It is not realistic to expect a user to have to delete are recreate products or variants just to accommodate the deficiency of the plugin.  In our case there are 16 products each of which has 6 variants with a lot of information to be entered for each one.  Or maybe I have misunderstood you workaround?

 

Also your explanation does not explain why the pricing is correct of the Facebook Homepage but not inside the shop itself – this seems very strange.

 

Anyway, would be great if the dev team can bump this us the list of changes.


Thanks for all your advice and support.

 

Best regards

 


Simon Hay

Media Amplify

M +61 473 064 946

E simonhay@ampmedia.com.au

**Comment by Ampmedia-DEV** [comment]
Hi,

 

We have tried the workaround you suggested on several of the variable products and it does not work.

 

What we did is:
Delete the product variant that we want to be shown in the shop
Update the product
Force Sync with Facebook
Re-edit product adding in the product variant again that we want to have shown in Facebook
Update the product
Force sync with Facebook
 

We still have the wrong product variant pricing showing inside the shop.  On the home page of Facebook page, the pricing is correct, but when we go inside the shop it is showing the wrong variant.

 

Any more suggestions would be much appreciated at this stage.


Cheers


Simon


Simon Hay

Media Amplify

M +61 473 064 946

E simonhay@ampmedia.com.au

**Comment by mengyingdu** [comment]
Hi @Ampmedia-DEV ,

Sorry for the inconvenience to your business. I think I misunderstood your problems in the beginning. I got update with our shop team and would like to explain more:

1. As you observed, in your fb page, price will show as your default variant value. (It confirmed our plugin support variant product effectively.) If you click on a product, it will directly select your default option.

2. In your shop and category view: what's being talked here is that the product collection doesn't point to the ideal product item variant inside each product group. I will follow up with shop team to see whether we could support this feature or whether we can have some workaround to customized this.

Thanks for your patience and try.

**Comment by Ampmedia-DEV** [comment]
Hi,

 

No worries, thanks for the update and we look forward to the fix.

 

Have a great day.


Cheers


Simon

 


Simon Hay

Media Amplify

M +61 473 064 946

E simonhay@ampmedia.com.au

**Comment by mengyingdu** [comment]
Hi @Ampmedia-DEV ,

I have more update :our self-serve UI doesn't support choosing one particular variant inside product group for collection inclusion, this is only supported via API.

However, our plugin doesn't support the API for now. I will mark it as feature request instead of bug. Since we prioritize bug fixes more than new feature, we may not add it soon. But I will keep this issue open and update if we add it. 

Thanks.

**Comment by Ampmedia-DEV** [comment]
Thanks for the update.

 

Would be good to get this sorted as it makes the use of variants a mess.

 

Cheers

 

Simon

 


Simon Hay

Media Amplify

M +61 473 064 946

E simonhay@ampmedia.com.au

**Comment by mengyingdu** [comment]
Unfortunately we don't provide explicit control over ordering, the Facebook infrastructure does not support it right now. I flag this feature to their team, but they aren't actively building it now.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
