### ISSUE TITLE
FB Shop : Sort products newest to oldest

### ISSUE THREAD

**Issue by artdesignstudio** [facebookincubator/facebook-for-woocommerce#256]
Hello, how do I sort products in facebook shop page newest to oldest? by default is oldest to newest

**Comment by jieminz22** [comment]
Hi,

I don't think we have this feature. I'll pass this request to the Shops team. Thanks.

**Comment by djheatley** [comment]
Hi, has this been solved please as it is an issue for my facebook shop as well.  I would prefer to have my latest products showing first.

**Comment by artdesignstudio** [comment]
No, I'm still waiting for that option..

**Comment by dmitridr** [comment]
Small Update : We've passed this feature request to the shops team, but they are prioritizing other features for now. If anyone else reading this would like this feature, please comment here, knowing the approximate demand for this feature helps our teams prioritize. Thanks!

**Comment by thesilverforge** [comment]
It would be great if the sort could be newest to oldest, that makes good sense for display purposes.

**Comment by djheatley** [comment]
yes definitely get this sorted as it is a HUGE problem for business selling new stock.

**Comment by rrowan** [comment]
Yes, I would like this feature as well! Makes so much more sense to display newest items first.

**Comment by shallz19** [comment]
yes, it should be there its a basic feature

**Comment by dmitridr** [comment]
Just FYI, you may be able to control the ordering better by creating a `Collection`. Check out issue #401 for details.

**Comment by philthebass** [comment]
Hi,

Is the default ordering by date added? I've just installed and synced and it seems to be random.

+1 for sort order feature - new to old

Thanks

**Comment by JapeNZ** [comment]
Hi,
This would a great feature!
+1 for sort order feature - new to old

**Comment by ody911** [comment]
Yes it should be there :)

**Comment by badsayer** [comment]
+1 for sort order feature - new to old

**Comment by hemicharger69** [comment]
+1M sort newest to oldest

**Comment by davidsbaldwin** [comment]
+1M Ditto, please add this feature (have ability to sort newest to oldest)!

**Comment by ARuzek** [comment]
I need this feature ASAP, preferably not only sort by new, but custom rearrange of items!

**Comment by djamesdesigns** [comment]
Very Important feature,, preferably not only sort by new, **but*** the ability to custom rearrange of items even better!!

**Comment by Bloudewedd** [comment]
Changing the sort order to different options would be awesome, like allowing us to CHOOSE if we want oldest first, newest first, order by name asc and desc, and (my personal fav) random. I know I'm late to the game here but it would be very helpful!

**Comment by lgfogle** [comment]
Hey all,

Since this is a feature request for Facebook, but not the Facebook for WooCommerce plugin, I'm going to close this issue. I'd recommend reaching out to the Facebook team directly to let them know this issue is important to you! In Facebook for WooCommerce 2.0, you can do that by following these steps:

1. Go to **WooCommerce > Facebook**.
2. Click **Manage Connection**.
3. Click **Help**.

Thank you!
Lindsey
