### ISSUE TITLE
------custom audience can t create-----

### ISSUE THREAD

**Issue by jerome2612** [facebookincubator/facebook-for-woocommerce#257]
hello there I can not create any custome audience since the new uptade 
![capture d ecran 2018-02-03 a 18 02 50](https://user-images.githubusercontent.com/33776849/35766294-80d60ce4-0910-11e8-9ee0-2e244332ee8f.png)
i can create audience who people visited my fb page but can not create audience from people visited pages on my web site??
the result said audience ready but i numbers of people inside this audience is not available
looking forward

**Comment by jieminz22** [comment]
Hi,

If you just installed your pixel not long ago, it takes a while for the audience to be generated. If you prefer you can share your website url with us so that we can double check to see if the pixel is firing correctly.

**Comment by jerome2612** [comment]
did you read ALL my explanation ??? 
I already gave all informations .... 
I explained already everything ....
since more than 8 months I use the pixel I did many custom audiences 
all my old customs audiences vanish and when I create new one NO audiences
if I create audience with informations from my pages it works (like people answers my posts, people like a post...) BUT no works for RETARGETING people who visited specifics pages, categories ....
so this is my web site link https://truktil.com/
before this issue we already manage the purchase bug now just after the update can not making custom audience
looking forward

**Comment by jerome2612** [comment]
someone also in  ticket  #242 have the same  issues
