### ISSUE TITLE
Facebook plugin brought my website down

### ISSUE THREAD

**Issue by domGaultonRR** [facebookincubator/facebook-for-woocommerce#258]
My website is https://oldschoolski.co.uk

I had the Facebook Plugin installed for a few weeks, but on 01/02/18 I noticed that my website would not load. I managed to find the error was due to the facebook for woocommerce plugin (see below)

Fatal error: Call to a member function get_sku() on boolean in /public_html/wp-content/plugins/facebook-for-woocommerce/includes/fbutils.php on line 94

I have no deactivated the plugin but would like to use it again. 

Please could you help

**Comment by jieminz22** [comment]
Sorry for the inconvenience. Please try our latest version to see if the problem persists. Thanks.

**Comment by domGaultonRR** [comment]
Version 1.4.1

**Comment by jieminz22** [comment]
Could you please try our latest version 1.7.11 to see if it fixes the issue? Thanks!

**Comment by domGaultonRR** [comment]
This looks like it has fixed the problem - thanks

**Comment by akspablo** [comment]
My website went down as well..
