### ISSUE TITLE
The Catalog Errors I Reported Definitely Are Causing Problems, No Price or Description Shown in Dynamic ads. No response to my last ticket

### ISSUE THREAD

**Issue by DaveNoakes** [facebookincubator/facebook-for-woocommerce#261]
Hi,

I opened a ticket a week ago, got one response assuring me that everything was fine despite the error messages I was receiving on the catalog manager page and then no response once I'd added the screenshots of the errors.

There definitely IS a problem. I am running dynamic ads using this plugin's setup and have just seen it on Instagram with no price or description (or indeed, the text that should appear above the ad), only the photos and the book now button. In preview mode it works and I have seen it in the Facebook feed working fine. But clearly it's not working every time.

Please, could you look at my case again and respond to it.

**Comment by mengyingdu** [comment]
I apologize for your inconvenience. I'm working remotely in UK now and I will look into your problems after meetings in daytime.

**Comment by mengyingdu** [comment]
related to #239

**Comment by DaveNoakes** [comment]
Thanks Mengyingdu! Much appreciated! Sorry for being a pain!

**Comment by dmitridr** [comment]
Let's keep discussing in the other issue. 

The issue you describe here seems like a bug in how the ad is displayed in Instagram? Unfortunately, we cannot help much with issues beyond the plugin itself. We can however make the instagram team aware of the issue, if you provide a screenshot of the incorrect behavior with an ad id.
