### ISSUE TITLE
Compatibility Issue : FB for Woo breaks Divi Builder

### ISSUE THREAD

**Issue by maltam** [facebookincubator/facebook-for-woocommerce#262]
Elegant Themes was debugging as the Divi Builder was not loading while editing some pages. This is what they found:

A plugin name "Facebook for WooCommerce" produces some JS errors on the page thus breaking the whole layout. I have disabled the plugin and it is working fine now. Please contact the plugin author regarding the error produced by it.

**Comment by jieminz22** [comment]
Hi,

Thanks for reporting this. I'm marking this as a feature request to support compatibility with Divi Builder.

**Comment by melerman** [comment]
Has there been any update on this? Products built with divi end up showing their markup. 
![screen shot 2018-02-28 at 12 44 21 pm](https://user-images.githubusercontent.com/23385418/36803321-3b18148a-1c85-11e8-974b-96c05ff971f9.png)

**Comment by mengyingdu** [comment]
Hi @melerman,

Unfortunately, we haven't fix this incompatibility for now. There are some workaround for you:
Can you put your preferred description here:
![screen shot 2018-02-28 at 11 12 08 am](https://user-images.githubusercontent.com/24535640/36808248-6b240d7a-1c79-11e8-99f3-1228ea5bbf36.png)


Thanks.

**Comment by mengyingdu** [comment]
Hi @melerman ,

Given we have swamped and prioritize bugs, we aren't actively building this now. But like said in #285 have a filter available [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.7.11/includes/fbproduct.php#L467)  which you can use to override the fields sent to FB with short description if it can solve your situation. It has the wp_id of the product as one of the fields, so you should be able to override the description with the short description.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
