### ISSUE TITLE
Multiple Sites with Different Pixels

### ISSUE THREAD

**Issue by onewithpez** [facebookincubator/facebook-for-woocommerce#263]
I set up my FB page and pixel on my site with no issues. I am trying to help a friend out and set up theirs. My friend made me an admin on their FB page and their website. When I try to install and set up the plugin, it does not give me an option to set up a new pixel. 

If my friend creates a pixel on his Ads account, will I be able to select the pixel when setting it up? If not, how can I accomplish this?

**Comment by jieminz22** [comment]
Hi,

Try the steps in this guide to share your friend's pixel with you. Starting from 'Share the facebook pixel' step.
https://www.jonloomer.com/2017/03/17/share-facebook-audience-pixel/
Let me know if it doesn't work.
