### ISSUE TITLE
Pixel counts my IP & shows my test purchase associated with a facebook ad

### ISSUE THREAD

**Issue by chalkandmoss** [facebookincubator/facebook-for-woocommerce#264]
I can't find a way to exclude my IP from Facebook pixel/ad results. I made a test purchase just now when I added Stripe as a gateway. This purchase now shows up as a purchase in one of my active ad campaigns. So my query is twofold:
1. How can I exclude my IP from these results (and delete the result shown, as having my test purchase in there skewed my results and thus Facebook's algorithm of what works). 
2. Why is a purchase by me being associated with one of my two active ad campaigns? I didn't click on my own ad. Or is it just because I was showed me ad? This begs the question why am I being shown my own (and paying to be shown) my ad?

Oddly, the purchase is only showing up in my facebook ad, not in the pixel view for purchases. There's only been that one purchase today and I can see that in my woocommerce order, so I know that the one showing in the Ads Manager is the test purchase I made. 

Let me know if this query should be directed elsewhere. I've seen others raise the issue of excluding one's own IP and Facebook have said that this functionality doesn't exist (the latest thread I saw was 3 months ago - https://www.facebook.com/business/help/community/question/?id=792529413362). 

Thanks so much!

**Comment by jieminz22** [comment]
Hi, 

I don't think we have this feature to exclude your IP. 
If you've seen your ad it will be counted as an impression and will be associated with the ad. Since we don't exclude you from the audience it's possible that you will see your own ad.
