### ISSUE TITLE
Undefined index notices thrown by facebook-commerce-pixel-event.php

### ISSUE THREAD

**Issue by glagonikas** [facebookincubator/facebook-for-woocommerce#265]
The changes made to support reverse proxy, are throwing the following notices
```
PHP Notice:  Undefined index: pixel_render in /home/XXXXXX/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-pixel-event.php on line 85
PHP Notice:  Undefined index: proxy_basecode in /home/XXXXXX/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-pixel-event.php on line 225
PHP Notice:  Undefined index: no_script_render in /home/XXXXXX/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-pixel-event.php on line 158
```

**Comment by mengyingdu** [comment]
Hi @glagonikas,

Thanks for your development on our plugin! I would reviewed and get back to you earlier, however, I am beyond swamped right now. Most of our team are traveling in UK for full-day meetings now, except one engineer on-call in office.  I will get back to you next week. Thanks for your time and patience!
