### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by glagonikas** [facebookincubator/facebook-for-woocommerce#267]
When jQuery is not included before this plugin, a JavaScript error is thrown on the console.

This could happen for a number of reasons, especially if you're using a plugin that moves JS code to the bottom, use defer or simply have a custom theme.

The plugin should ideally ensure jQuery is loaded before using it.

**Comment by mengyingdu** [comment]
Hi @glagonikas,

Thanks for your development on our plugin! I would reviewed and get back to you earlier, however, I am beyond swamped right now. Most of our team are traveling in UK for full-day meetings now, except one engineer on-call in office.  I will get back to you next week. Thanks for your time and patience!
