### ISSUE TITLE
Plugin Error - "You are sending a non-standard event 'ViewCategory'."

### ISSUE THREAD

**Issue by boxtreeclinic** [facebookincubator/facebook-for-woocommerce#27]
The Facebook plugin is generating the following error:

"fbevents.js:24 Facebook Pixel Warning: You are sending a non-standard event 'ViewCategory'. The preferred way to send events is using trackCustom. See https://www.facebookmarketingdevelopers.com/pixels/up#sec-custom for more information
nc @ fbevents.js:24"

Can you issue a fix for this please?

Richard

**Comment by dmitridr** [comment]
Hi,

We can't reproduce this issue on our end. Could you share a screenshot with us or a website url for which this is happening? Thanks.

**Comment by boxtreeclinic** [comment]
Thank you for your email. Here is a url where the error is happening and a screen shot.

Many thanks,

Richard

https://boxtreeclinic.com/blog/practitioner/tom-sobel/ <https://boxtreeclinic.com/blog/practitioner/tom-sobel/>

**Comment by dmitridr** [comment]
Thanks for the email. I confirmed the repro using your link and I'm working on a fix. We should have it in the next version.

**Comment by boxtreeclinic** [comment]
Thank you. Richard

**Comment by dmitridr** [comment]
We've fixed this issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
