### ISSUE TITLE
---about ticket #257 IMPOSSIBLE CREATE CUSTOM AUDIENCE ---

### ISSUE THREAD

**Issue by jerome2612** [facebookincubator/facebook-for-woocommerce#270]
Hello there I RE-POST my request about the impossibility to create a custom audience and that is a basic tools for people use pixel with advertisements how come is possible before was fine and perfect and suddenly all my customs audiences vanish and impossible create new one 
looking forward

**Comment by jieminz22** [comment]
Please see my comments in #257.
