### ISSUE TITLE
Products does not appear.

### ISSUE THREAD

**Issue by cmertkan** [facebookincubator/facebook-for-woocommerce#272]
Hello, I have integrated Woocommerce Facebook to my dodoBees.com woocommerce web site. However, I cannot see the products in Facebook.com/cdodobees page.

Could you help?

**Comment by jieminz22** [comment]
Hi, 
I open your Facebook page and I do see products up there. Are those the ones you are expecting?

**Comment by cmertkan** [comment]
Yes, I have fixed it. I erased the store and go over again..

jieminz22 <notifications@github.com> şunları yazdı (7 Şub 2018 21:49):
