### ISSUE TITLE
wp-admin stopped working after I activated this plugin

### ISSUE THREAD

**Issue by camilosw** [facebookincubator/facebook-for-woocommerce#275]
Plugin Version: 1.7.6
Wordpress version: 4.9.4
WooCommerce version:  3.3.1

[09-Feb-2018 15:56:26 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WC_Facebookcommerce_EventsTracker::__construct(), 1 passed in /home/sushimarket/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 290 and exactly 2 expected in /home/sushimarket/public_html/wp-content/plugins/facebook-pixel/facebook-commerce-events-tracker.php:19
Stack trace:
#0 /home/sushimarket/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(290): WC_Facebookcommerce_EventsTracker->__construct(Array)
#1 /home/sushimarket/public_html/wp-content/plugins/woocommerce/includes/class-wc-integrations.php(39): WC_Facebookcommerce_Integration->__construct()
#2 /home/sushimarket/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(464): WC_Integrations->__construct()
#3 /home/sushimarket/public_html/wp-includes/class-wp-hook.php(286): WooCommerce->init('')
#4 /home/sushimarket/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /home/sushi in /home/sushimarket/public_html/wp-content/plugins/facebook-pixel/facebook-commerce-events-tracker.php on line 19

**Comment by dmitridr** [comment]
Yeah, sorry about this, we're aware of this problem, it's caused by a compatibility issue with `PixelYourSite` and some other plugins. Please upgrade to 1.7.11, it should fix the issue!

The latest version is available here : 
https://github.com/facebookincubator/facebook-for-woocommerce/releases

**Comment by camilosw** [comment]
1.7.11 work fine. Thanks
