### ISSUE TITLE
Purchase Pixel stopped firing

### ISSUE THREAD

**Issue by CTCOC** [facebookincubator/facebook-for-woocommerce#276]
Not sure if anybody else is having this issue but our purchase pixel stopped firing. All our other events are firing properly except for the purchase one, which had been working fine for some time.
![screen shot 2018-02-09 at 3 27 20 pm](https://user-images.githubusercontent.com/36316310/36055279-36ceebda-0db0-11e8-9fca-3c319dc7a27e.png)
![screen shot 2018-02-09 at 3 27 44 pm](https://user-images.githubusercontent.com/36316310/36055280-36e695f0-0db0-11e8-812b-40e5e048e12a.png)

**Comment by jieminz22** [comment]
Hi,

Which version of the extension are you using?

Also, in order for us to confirm the problem, I would recommend you install the Pixel Helper extension for chrome, and try doing a test purchase on your own site (maybe with a hidden product) and observe to see if the Purchase event fires. If that's true, it's probably an issue with our plugin. And we can dig in further.

Thanks.

**Comment by aquezada** [comment]
Hi, Nor is it giving me "purchase" results since the last update, I have reviewed from "Pixel Helper extension"

**Comment by jieminz22** [comment]
Hi,

Are you using the latest version of our extension? If not please try the latest one. We've seen this issue before with earlier versions but have fixed it (#227).

**Comment by dmitridr** [comment]
@aquezada you are using v1.7.11? Could you go into details about the configuration of your purchase flow so we can test it on our own test servers? (Stripe? Paypal? etc.)

As Jiemin said, we had big problems with purchase not appearing before v1.7.8 but those should be fixed.

**Comment by aquezada** [comment]
Infinites thanks!! I work with 1.7.11 :)

I was testing with 1.7.5! sorry!

**Comment by dmitridr** [comment]
Great, thanks for confirming! Really glad we don't have another bug here.

@CTCOC upgrading to 1.7.11 should fix your issue as well. If you can confirm, I'll close the issue.
