### ISSUE TITLE
W3 Validation Error: Inserting <img> tag into document <head>

### ISSUE THREAD

**Issue by APlusDesign** [facebookincubator/facebook-for-woocommerce#28]
Regarding the Facebook for WooCommerce WordPress plugin, it is causing a W3 validation error because it is inserting an `<img>` element into the head of the document.

Site Details.

https://beardifulman.com
https://www.facebook.com/abeardifulman/

Error Replication

https://validator.w3.org/nu/?doc=https%3A%2F%2Fbeardifulman.com

More Info
--------------
WordPress 4.8.1 and WooCommerce 3.1.2
Facebook Plugin version 1.4.5 
20 Products
Products are beard oils, balms, etc
No duplicate SKU's we are not using any currently

The code can be found on line 34 of 'facebook-commerce-pixel-event.php' in the root folder of the plugin facebook-for-woocommerce.

`<noscript><img height=\"1\" width=\"1\" style=\"display:none\"
src=\"https://www.facebook.com/tr?id=%s&ev=PageView&noscript=1\"
/></noscript>`

Img tags are not allowed in the head of a document, not even if they are wrapped in a no script tag. You can see from this link

https://validator.w3.org/nu/?doc=https%3A%2F%2Fbeardifulman.com

That the plugin is clearly causing a validation error because of this.

**Comment by APlusDesign** [comment]
Anyone going to pick this one up or even just comment that it' has been noted. Seems fairly serious to me.

**Comment by mengyingdu** [comment]
We've fixed this issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
