### ISSUE TITLE
Shop is not created : selector is easy to miss.

### ISSUE THREAD

**Issue by Sicura** [facebookincubator/facebook-for-woocommerce#281]
Hi there,
I made all the step mentioned in here: https://www.facebook.com/business/help/900699293402826
But it doesn't work. My shop is always empty and I also can't anymore add product manually?
my web site: sicuracasseforti.it
My Fb page: www.facebook.com/sicuracasseforti/
Could you help me?
Thank's in advance

**Comment by dmitridr** [comment]
Hello,

I checked your page, seems like you have a Self-Serve shop that you have created. When you create such a shop, we avoid overwriting it with our plugin unless you explicitly select this option in our setup steps.

It's easy to miss, but right before you click `Finish` in Setup, there is a selector asking you if you would like to set up a shop. We default this to off if we detect that you already have a shop, so you have to set this to `On`. 

Here's a screenshot of what I am talking about :
![shop1](https://user-images.githubusercontent.com/29133800/36177789-ae2b3684-10cb-11e8-8c20-f11cac83cdd1.png)
![shop2](https://user-images.githubusercontent.com/29133800/36177794-b134beb8-10cb-11e8-8196-75ad6c6ba497.png)

**Comment by wazman21** [comment]
THANK YOU - this helped greatly - I was starting to pull my hair out!

**Comment by dmitridr** [comment]
Closing. This seems to be a common issue, maybe we can fix it with a design revamp.

**Comment by rikinhim** [comment]
I face the same issue as well, i tried 3-4 times and waited around 24 hrs each time, still no clue, any suggestions for other better plugins?
