### ISSUE TITLE
Store page broken since WC update

### ISSUE THREAD

**Issue by Diedericht** [facebookincubator/facebook-for-woocommerce#283]
After updating woocommerce to 3.3.1 our store page broke.
After disabling facebook for woocommerce the store works again.

**Comment by dmitridr** [comment]
Hey,

That's not good, thanks for reporting it. 
We use 3.3.1 on our test servers and don't see the same problem, so unfortunately we can't replicate the problem and need more information from you.

- Could you go into detail on how it broke? Was it the frontend that broke? How did it look like when it broke (Do you have a screenshot?)?
- Which version of Facebook For WooCommerce do you have? We have some known instability in versions before 1.7.11, I recommend upgrading to see if that fixes the problem.

**Comment by Diedericht** [comment]
Thank you!
Just updating worked.

We were on version 1.4.0 but never got any notification that newer versions are available.

Attached a screenshot in case it helps someone.

![purpleonline co za_shop_ laptop with hidpi screen](https://user-images.githubusercontent.com/36063211/36296271-342ccbd2-12f5-11e8-94ad-370df7df407d.png)
