### ISSUE TITLE
Contact Us Link Within Plugin & Blank SKUs

### ISSUE THREAD

**Issue by bighippo999** [facebookincubator/facebook-for-woocommerce#284]
The email address in:

> If this error persists, or you have a use-case for duplicated SKUs, [please contact us](mailto:ads_extension_woocommerce@fb.com).

Is now just an auto-responder:

> Thanks for your message. We're no longer responding to emails that are sent to this address, but we have 2 new ways to get help:
> 
> Facebook Help Center: We answered frequently asked questions about using WooCommerce on Facebook in this article.
> 
> Our GitHub repository: If you think you've found a bug, please file it in this repository so it's visible to others and we can take action on it.
> 
> When filing a bug on GitHub, please look at the previously closed issues first because you may find a resolution to your issue. If you need assistance in filing an issue, please contact WooCommerce.
> 
> If you're a developer, you can submit a pull request to the repository for our team to review.
> 
> Thanks,
> The Facebook Ads Team

Seems a bit pointless :)

**Comment by dmitridr** [comment]
Agreed. Where do you see the first bit? Is that on the WooCommerce page?

**Comment by bighippo999** [comment]
Hi,
It's an error notice that gets displayed in WooCommerce (definitely the orders page and the integration>woocommerce, I didn't look at other pages but suspect it's across everything until dismissed).
I looked at the code, it's on lines 1231 & 1232, but the entire error message starts 1225 of facebook-commerce.php

If it helps the error was moaning about duplicate SKU's when syncing. I checked via the database for duplicate SKU's (easier than checking each item) and the only products showing duplicate sku is where there's no SKU (the guide says it will only sync if there's valid sku, image, title) it should be skipping these. I mailed to find out if blank SKU is likely to be classed as duplicate :)

**Comment by dmitridr** [comment]
Got it. Thanks for reporting that! I think we can easily fix this by not syncing blank SKUs and remove the message as well.

**Comment by mengyingdu** [comment]
Hi @bighippo999 ,

This should be fixed in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6) We have 10 fixes plus 1 content enhancement. I do recommend you upgrade. Feel free to open a new issue if you have other question.

If you like **Facebook-for-WooCommerce**  please leave us a [*****](https://woocommerce.com/products/facebook/) rating. A huge thanks in advance!
