### ISSUE TITLE
Use short description by default for all products

### ISSUE THREAD

**Issue by mmtomm** [facebookincubator/facebook-for-woocommerce#285]
Hi,

I guess, the custom meta fb_product_description is the place to override the product description which is synced to fb and is taken from the (long) description of the product. Is there a function available to use the short description by default for all products?

The reason I want to use this one is because in short description I only use plain text, whereas in description there are formattings like lists or theme specific designs which makes the product decription on facebook looks a bit scrambbled sometimes ([example product in my catalogue](https://business.facebook.com/commerce/products/1750698514981733/))

Thank you
Tom

**Comment by dmitridr** [comment]
Hi Tom,

Thanks for writing in. There's no way to do this in the UI right now short of manually copying the short description into the fb_product_description field per product, but we have some programmatic ways to do what you ask:

- We have a filter available [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.7.11/includes/fbproduct.php#L467) which you can use to override the fields sent to FB with your own function. It has the wp_id of the product as one of the fields, so you should be able to override the short description.
- Another potentially easier workaround is just switching these two `if` statements [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.7.11/includes/fbproduct.php#L217-L222) which should prioritize the short description over the long one during sync.

After applying any of these methods, a `Force Resync` should provide the desired result.
Hope that helps!

**Comment by mengyingdu** [comment]
Hi Tom,
I think you should replace this code block:
    if ($post_content) {
      $description = $post_content;
    }
    if ($description == '' && $post_excerpt) {
      $description = $post_excerpt;
    }

into 
 
    if ($description == '' && $post_excerpt) {
      $description = $post_excerpt;
    }

rather than switching, if you want to override all products.  (post_content is original post description, post_excerpt is short description. @dmitridr 

Thanks

**Comment by dmitridr** [comment]
We added an option in the UI under `Advanced Settings` in the config page of the plugin in version v1.9.8 to sync short description instead of description. Check it out!

**Comment by jedgueruela** [comment]
I'm getting this issue. I have "sync short description instead of description" already checked under advanced settings and re-synced all the products but still no luck. It appears that it is only using the product title and variation name as the description. If I clicked a product from the facebook catalog, the description shows something like this: **Product Name - Brown** and that's about it.

**Comment by donaldking** [comment]
Has this been fixed yet? I'm experiencing the same issue @jedgueruela reported above
