### ISSUE TITLE
Forced to use plugin

### ISSUE THREAD

**Issue by CoolKay** [facebookincubator/facebook-for-woocommerce#286]
From what I see, WooCommerce let us use this plugin for free for awhile - and Countyfairgrounds, USA has items on the shop tab on Countyfairgrounds, USA  - Facebook page. Then they apparently fixed the plugin and sent me an update - that I have not configured  because 1) it is forcing me to buy ads  and 2) it says I can no longer post anything to my Facebook Shop page because I have to pick a NEW shop  url instead of the current one.  3) they give me no way to update the shop I already have  4) I do NOT appreciate this thing locking u[p my back end on woocommerce either

**Comment by sammul** [comment]
@CoolKay I'm not sure I follow: 1) our plug-in doesn't force you to buy ads; 2) this seems a problem on the shop side, but I've never seen this. 3) do you mean you our plug-in will erase your current shop and create a new one?

**Comment by CoolKay** [comment]
Hi, yes plugin erased current. Shop and i had to start over from scratch
nwith each item in the store. As far as the ad thing goes .. twas my
mis-understanding

**Comment by sammul** [comment]
@CoolKay Yeah, our plug-in has to overwrite your shop. Thanks for the feedback though. Is there any reason that you want to keep the shop you manually created rather than our plug-in updates all for you?

**Comment by CoolKay** [comment]
I did not manually create it - WooCommerce  had a Facebook plugin - And I
went through and had to update each listing to get it to show on my
Facebook store. THEN when your plugin in came around - it deleted
everything in the shop and I had to go back and manually re- input  - each
item back in - I still have not finished that yet - I just have not gotten
back to it.

*Karen Riedl,  Webmaster*
*Countyfairgrounds.net *
    *(866) 572-6324*

**Comment by dmitridr** [comment]
Hello,

That's a bit confusing, the plugin that WooCommerce has *is* the same as our plugin, unless you mean a different one that they have? They literally take our plugin here and put it on their website.

I took a look at your shop and it seems the products have synced to it through the plugin, so it seems it's working. If you have further problems, feel free to open a new issue on us, closing this one out.
