### ISSUE TITLE
Variations cannot be added to cart

### ISSUE THREAD

**Issue by samnazarko** [facebookincubator/facebook-for-woocommerce#29]
Adding a product with a variation doesn't work properly: the cart remains empty. See https://www.facebook.com/commerce/products/1623697274370340/ for an example

Possibly related to #25

**Comment by dmitridr** [comment]
Hi,

We have a known issue with variations causing strange add-to-cart behavior, thankfully there is a workaround you can do by sending users to the product page instead of the add to cart page. It's described in #4

**Comment by samnazarko** [comment]
Thank you for the workaround and prompt reply

I actually prefer to take the user to the product page instead of the checkout.
I'll dig in to this and see if I can identify the issue, but I suspect you may beat me to it. 

Sam

**Comment by dmitridr** [comment]
We'll go ahead and close this issue, we weren't able to fix this, but the existing workaround for the products page instead of the checkout seems to work for everyone.

@samnazarko If you do figure out the problem, we'd be happy to look at your pull request!
