### ISSUE TITLE
Error when visiting shop page with capital SHOP in the URL 

### ISSUE THREAD

**Issue by konmavrakis** [facebookincubator/facebook-for-woocommerce#291]
There seems to be an issue when visiting the shop page when the permalink in the URL is capitalised. For example, https://exampleshop.com/shop displays everything properly; if you visit https://exampleshop.com/SHOP we get the fllowing error: 

`Fatal error: Uncaught Error: Call to a member function get_sku() on boolean in /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/fbutils.php:111 Stack trace: #0 /var/www/html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-events-tracker.php(50): WC_Facebookcommerce_Utils::get_fb_content_ids(false) #1 /var/www/html/wp-includes/class-wp-hook.php(286): WC_Facebookcommerce_EventsTracker->inject_view_category_event('') #2 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /var/www/html/wp-content/themes/flatsome-child/woocommerce/layouts/category.php(102): do_action('woocommerce_aft...') #5 /var/www/html/wp-includes/template.php(690): require('/var/www/html/w...') #6 /var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(180): load_template('/var/www/html/w...', false) #7 /var/www/html/wp-content/themes/flatsome/woocommerce/archive-product.php(21): wc_get_template_pa in /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/fbutils.php on line 111`

**Comment by jieminz22** [comment]
Hi @konmavrakis,

I tested on our demo store confirmed the issue does exist, however it persists even I deleted this plugin. I think it's a Woo bug, rather than a bug introduced by this plugin. I'll close the issue.
