### ISSUE TITLE
Is this now compatible with WooCommerce 3.3.1?

### ISSUE THREAD

**Issue by jessdaddy** [facebookincubator/facebook-for-woocommerce#292]
Hi I have been putting off updating WC to the latest version because of a fear of incompatibility with the FBfWC. Is the latest version stable enough to update to and use WC 3.3.1? I am still using FBfWC 1.7.11 it seems to be okay for now with WC 3.2.6. Please advise. thanks.

**Comment by sammul** [comment]
Yes, we have a lot of users using W 3.3.1 with plug-in 1.7.11
