### ISSUE TITLE
No updates available after v1.6.1

### ISSUE THREAD

**Issue by thamarakandabada** [facebookincubator/facebook-for-woocommerce#293]
I'm running a store on WooCommerce 3.3.1. In the plugins section, I cannot see any updates available for the Facebook for WooCommerce plugin after v1.6.1. In the plugin changelog [here](https://dzv365zjfbd8v.cloudfront.net/changelogs/facebook-for-woocommerce/changelog.txt) I can see that the latest version available is 1.7.11 What can be the reason?

The reason I'm keen is because right now when my products are synced to the Facebook shop, unpublished and trashed products are also synced. I saw in an issue thread somewhere that this has been fixed in v1.6.4, so I'd like to get the updated version as soon as possible.

Thanks in advance for your help.

**Comment by sammul** [comment]
You can download the latest version in https://github.com/facebookincubator/facebook-for-woocommerce/releases and upload the package to woocommerce

**Comment by thamarakandabada** [comment]
Thank you @sammul. This did occur to me.

Perhaps I should have phrased the first part of the question better. I'm interested in knowing why the latest update is not shown to me in the WooCommerce plugins section. Can there be something wrong that I need to fix?

**Comment by sammul** [comment]
@thamarakandabada  I don't think it's a problem on your side. I'll ask the person who works on pushing the new versions to verify. Thanks for flagging this.

**Comment by thamarakandabada** [comment]
Thanks a lot, @sammul.

**Comment by izricketts** [comment]
Can I check how I update plugin to most recent version? Do I deactivate it then delete it then reinstall version 1.7.11, thanks

**Comment by sammul** [comment]
@izricketts Yes

**Comment by sammul** [comment]
@thamarakandabada This has been identified an issue from our side. We will fix it asap

**Comment by izricketts** [comment]
great, thanks

**Comment by mengyingdu** [comment]
Hi @izricketts ,

It should be fixed in [v1.8.1](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.1).
