### ISSUE TITLE
Website Conversion Value and Event Tracking

### ISSUE THREAD

**Issue by chvillanuevap** [facebookincubator/facebook-for-woocommerce#294]
Hi there!

I've been using this Pixel plugin to track the ROI of my Facebook ads. For example, I have an ad inside a Traffic campaign that has resulted in two Custom Conversions. The Custom Conversion gets activated when the user reaches the Thank You page URL after purchasing a paid product. By these 2 conversions, my conversion value on my ad should be low, under $50. However, my Website Conversion Value displayed for my ad says $188. I'm wondering if Facebook is duplicating the value of events from the plugin. For example, the 'ViewContent', 'AddToCart', 'InitiateCheckout', and 'Purchase' events all have a value that is more or less the cost of the product. This would more or less increase the conversion value of an ad 4 times.

Does Facebook count each event and adds their value to the Total Conversion Value for an ad? And if so, is assigning these events a value equal to the product cost the right way to do it?

Thank you!

Hernán

**Comment by sammul** [comment]
@chvillanuevap The purchase amount metric in your campaign insights only counts the purchase event value.

**Comment by sammul** [comment]
@chvillanuevap I actually saw the pixel is sending 0.00 value for the purchase events, if you look at the event manger for the pixel. I also noticed you are using an old version of the plug-in, which might be broken. Can you update to the latest version, and use pixel helper(available in chrome extension) to do a test order to make sure pixel is firing correctly?

**Comment by chvillanuevap** [comment]
I offer lots of free products on my site, but still make customers go through the checkout process to get their email addresses and their consent to receive info from us. That could be why some Purchase events send a value of 0.00.

By the way, I downloaded the plugin from here: 

https://www.facebook.com/events_manager/partner-integration?act=18291140

It seems their version of the plugin is 1.7.3.

I'll perform the steps you suggested.

**Comment by sammul** [comment]
@chvillanuevap We have newer version in https://github.com/facebookincubator/facebook-for-woocommerce/releases
Or on woocommerce, if you have auto-upgrade, you will be able to directly upgrade there. You can use 1.7.11 or try 1.8.0(it's in beta but has perf improvement)

Back to your question of conversion value, I can see the avg purchase value is around $3-$5, which seems correct from your describing

**Comment by chvillanuevap** [comment]
Ok, I upgraded the plugin. As I navigate through the checkout process, I see the following events:
```
ViewContent
content_type: product
content_ids: ["wc_post_id_343776"]
value: 15
source: woocommerce
pluginVersion: 1.7.11
content_name: Show
currency: USD
version: 3.2.5
```
```
InitiateCheckout
content_type: product
content_ids: ["wc_post_id_343776"]
value: 15
source: woocommerce
num_items: 1
pluginVersion: 1.7.11
currency: USD
version: 3.2.5
```
etc.

So I guess the value of each event adds up for the Total Conversion Value metric, but Website Purchase Conversion only tracks Purchase events?

**Comment by sammul** [comment]
@chvillanuevap I think you are right, the Total Conversion Value counts everything has a value(AddToCart, InitiateCheckout etc), which is confusing. I learned this today as well. Thanks for flagging. For you, you should look at purchase value, which is used to calculate the ROAS/ROI

**Comment by chvillanuevap** [comment]
Thank you for clarifying! I appreciate your help with this issue!
