### ISSUE TITLE
Half of Half goods only, shows when using WPML

### ISSUE THREAD

**Issue by aavvaavv** [facebookincubator/facebook-for-woocommerce#295]
I'm not spamming. Just what to say that half products on original language can't be displayed on FB shop. 25% of 100% only showing. Only 62 goods from 248.

Hello. I found the same problem. But also, I think that additional but. Now I will describe and show

WPML
2 languages.
304 goods; http://prntscr.com/iie768 - 331 main language and 158 on additional language. 173 of 331 on original language is private goods.
So, when I start to sync, I see next message from plugin: http://prntscr.com/iie8gi (We have 158 goods)
158 on main language and 158 on additional. = 316 goods.
When I make re sync, it shows 304 - http://prntscr.com/iie90f m I thin few goods are private.

So, after sync, with variations, I see next: http://prntscr.com/iie9ss - 2800 products, => http://prntscr.com/iiea1a - 2752 variations.
And, on the FB show I see next - http://prntscr.com/iieai4 - 124 items when logged, and 124\2=62 from other account - without duplicates - http://prntscr.com/iiecw9

The main idea, to which we will return - I synced 124 goods * = 248(2 langs)(2800 with variations), but on FB I see only 62.
If I syncing 98 goods * 2 = 196 on 2 languages, I see only 196 \ 2 \ 2 = 49 goods on FB.
I think that there is a limit on the display of goods. How many downloaded, so many can be displayed. But because of takes in the second language, I can not show the remaining half of the second goods.

I try to mark of next point on the second language: http://prntscr.com/iiefw6

As for me, there is no problem that the goods are unloaded in the second language. But I can not show all 100% of the goods. For some reason, it displays exactly 50% of all goods.

I can provide all accesses and passwords so that you can get acquainted with the situation.
Thank you so much.

p.s. FB page: https://www.facebook.com/pg/annaskoblikovabridal
site: annaskoblikova.com

Andrey

**Comment by aavvaavv** [comment]
Also I have next errors - Facebook extension error: We've detected duplicate SKUs in your shop. This can happen for a few reasons, including the effects of other plugins. 
Some of your products may not have been synced to Facebook. Please delete your settings via the "Advanced" tab and try setup again.
If this error persists, or you have a use-case for duplicated SKUs, please contact us.

**Comment by mengyingdu** [comment]
Hi @aavvaavv ,

We don't have full support for WPML, and you can check the description and functionality [here](https://github.com/facebookincubator/facebook-for-woocommerce/commit/c7f1393e1584219e6e387d26f4dae2c9eb6e4967)

I got confused by your number, there're too many... Can you try to understand the level of support we had for WPML first and then count/check your site?
Sorry about the delayed reply. We have historical issues with multi-language site for long while.

Thanks.

**Comment by aavvaavv** [comment]
Dear @mengyingdu 

Thank you for the answer.
I studied next link - https://github.com/facebookincubator/facebook-for-woocommerce/commit/c7f1393e1584219e6e387d26f4dae2c9eb6e4967 

Yes, all items in "Staging" mode - it is ok. But many items - 50% - half in original language - is active but they are not displayed. - https://www.facebook.com/pg/annaskoblikovabridal/shop/?ref=page_internal
Only half :)

Thank you, I'm in touch.

Andrew

**Comment by dmitridr** [comment]
Hello @aavvaavv 

Thanks for your patience and taking the time to gather so many screenshots for us.
I checked our logging, some products did indeed fail to upload, the error I'm seeing is "Duplicate retailer_id when attempting to create a product"

Do you have some different products with the same SKU? Perhaps exactly half? This could be causing the problem. If that's not it, could you provide us with a link to one of the products (on your site) that failed to upload into the shop, and a screenshot of the settings of that product? That will help us figure out why it did not upload correctly.

**Comment by mengyingdu** [comment]
Hi @aavvaavv ,

We supported WPML in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6) by adding a language selector. To take advantage of this feature you need to upgrade to the latest version and do a full reset or Force Resync as it seems you have done. Please clear your browser cache after upgrade.

If your still have problems for your products, please let me know.


Thanks.

**Comment by dmitridr** [comment]
It's been a while since there has been a reply here, if your problem has not been addressed by the recent update, please open a new issue on us and reference this issue. As @mengyingdu mentioned, our WPML support has gotten much better as of v1.8.6. Now you can select which language to show on the shop inside the WPML settings.
