### ISSUE TITLE
ViewContent, AddToCard pixel not fired

### ISSUE THREAD

**Issue by al6ert** [facebookincubator/facebook-for-woocommerce#296]
Hi!,

The installation has generated the product catalog and the pixel is installed in wordpress but It doesn't fire the standard events.

I've installed the plugin and configured with the same pixel ID is used in other website (same company). I've never had a catalogue so may be this could generate some conflicts

I've seen here some people having troubles with the AddToCard and Purchase events but not with ViewContent event. In my case it doesn't fire any standard event. May be the woocommerce version (3.2.4) is not compatible with the plugin (1.7.11) ?

![captura de pantalla 2018-02-23 a las 13 41 32](https://user-images.githubusercontent.com/1695042/36594898-598f313e-18a0-11e8-94b5-5f05557e4d99.png)

**Comment by sammul** [comment]
@al6ert Can you go to Ads Manager pixel events to see if they are firing correctly? This might be pixel helper issue

**Comment by al6ert** [comment]
No, I only receive pageview events

**Comment by mengyingdu** [comment]
Hi @al6ert ,

Did you check 'redirect to cart after addition' ?  If so, the add to card event which is hooked on the button click won't be fired.
![screen shot 2018-03-02 at 7 06 45 pm](https://user-images.githubusercontent.com/24535640/36929952-0acf033c-1e4d-11e8-8f69-ef5f88a0f7ed.png)


Let me know if you need more help.

Thanks.

**Comment by al6ert** [comment]
hi @mengyingdu @sammul 

Yes! that solves the addToCard issue... but I liked the redirection feature.

We have solved the issue with "viewContent". The designer theme removed the hook woocommerce_after_single_product from the woocommerce template, this hook fires the event.

Thanks

**Comment by dmitridr** [comment]
There's more discussion and a potential workaround for AddToCart in #219. We may implement some fix for it soon as well based on the discussion in that thread.

Glad you solved the "viewContent" issue. It looks like all issues have been resolved so I will close this, if I am wrong please open a new issue and reference this one!
