### ISSUE TITLE
Fatal error at thank you page

### ISSUE THREAD

**Issue by Momotica** [facebookincubator/facebook-for-woocommerce#297]
Customers are getting this fatal error after the ordered.
I'm using 1.8.0

Thanks in advance for the help.

`Fatal error: Uncaught Error: Call to undefined method WC_Order::get_payment_method() in /home/deb91934/domains/momotica.nl/public_html/wp-content/plugins/facebook-for-woocommerce-master/facebook-commerce-events-tracker.php:315 Stack trace: #0 /home/deb91934/domains/momotica.nl/public_html/wp-includes/class-wp-hook.php(298): WC_Facebookcommerce_EventsTracker->inject_gateway_purchase_event(20681) #1 /home/deb91934/domains/momotica.nl/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #2 /home/deb91934/domains/momotica.nl/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/deb91934/domains/momotica.nl/public_html/wp-content/themes/flatsome-child/woocommerce/checkout/thankyou.php(80): do_action('woocommerce_tha...', 20681) #4 /home/deb91934/domains/momotica.nl/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(203): include('/home/deb91934/...') #5 /home/deb91934/domains/momotica.nl/public_html/wp-content/plugins/woocommerce/includes/shortcodes/cl in /home/deb91934/domains/momotica.nl/public_html/wp-content/plugins/facebook-for-woocommerce-master/facebook-commerce-events-tracker.php on line 315`

**Comment by sammul** [comment]
@Momotica Thanks for reporting. Have you tried 1.7.11? Is 1.7.11 working fine for you?

**Comment by Momotica** [comment]
I update from 1.7.11 because of the error.
I'm going to try an older version, since I needed to update.
The plugin keeps saying that I needed to finish the setup, has been finished for monthes.

Will let you know.

**Comment by Momotica** [comment]
@sammul I just tested with 1.4.2 and no problem.
This is the first one I used at the beginning.

**Comment by sammul** [comment]
@Momotica Are you using any other plug-in for payment? Might be because of some conflict with other plug-in.

**Comment by mengyingdu** [comment]
Hi @Momotica ,

How about your WooCommerce version? I found many issues about this: https://wordpress.org/support/topic/fatal-error-call-to-undefined-method-wc_orderget_id/

Can you try to upgrade WooCommerce? The reason why you don't see that error in 1.4.2 is because we added this function change after 1.7.0.

Let me know if you need more help.

Thanks.

**Comment by mengyingdu** [comment]
Hi @Momotica ,

Have you fixed you problems?
Let me know if you need more help.


Thanks.

**Comment by Momotica** [comment]
Hi, sorry for the late reply.
Updating woocommerce is on my to do list, I guess thats the problem.
I'm not using the latest version yet.

**Comment by dmitridr** [comment]
Hi, 

Any update here? If you like, we can provide a quick workaround involving you adding some lines to the plugin to tide you over until you can upgrade. Essentially those lines would check to see if the method exists or not before calling it.

**Comment by mengyingdu** [comment]
It should be solved by upgrading WooCommerce.
