### ISSUE TITLE
View Content Pixel not working properly

### ISSUE THREAD

**Issue by belladonnaboutique** [facebookincubator/facebook-for-woocommerce#299]
Hi there,

The View Content pixel is not working properly for one of my products. It says that additional characters are in the url, but this is not correct. The url hasnt changed, and the View Content pixel was working fine previously and now all of a sudden it is not. I have attached a screen shot. 
![screen shot 2018-02-24 at 9 51 07 am](https://user-images.githubusercontent.com/35646111/36631565-7d846b6a-1948-11e8-9ee5-bacd4e88ace2.png)
![screen shot 2018-02-24 at 9 51 16 am](https://user-images.githubusercontent.com/35646111/36631569-83e8d2e8-1948-11e8-96ed-338a76611179.png)

**Comment by sammul** [comment]
@belladonnaboutique It looks working for me 
![screen shot 2018-03-02 at 10 16 13 am](https://user-images.githubusercontent.com/4251631/36914633-c8b57c14-1e02-11e8-8416-e95bbc134e1f.png)

Is it an issue with Woo 3.3.1 only? I noticed you upgraded to 3.3.3

**Comment by belladonnaboutique** [comment]
Ok that is strange. it seems to be working now!
