### ISSUE TITLE
Add to cart pixel not fired when item is added to cart from product page

### ISSUE THREAD

**Issue by helgatheviking** [facebookincubator/facebook-for-woocommerce#3]
The add to cart pixel is only fired when a user visits the cart page and `woocommerce_after_cart` is triggered. This misses the event on the single product page. It's also possible that a user might go straight to checkout (or be redirected straight to checkout) and so you'd miss the add to cart action all together.

**Comment by dmitridr** [comment]
Yes, by design the event won't be fired unless the user views the cart. However as with #2 we are open to supporting this feature, based on user demand.

**Comment by helgatheviking** [comment]
View cart doesn't seem the same as add to cart to me, but it's obviously up to you.

**Comment by dmitridr** [comment]
I agree, it's not the same. We would definitely like to address this...

But, given that we're dealing with a high volume of bugs, we unfortunately won't get to this feature request for a long time to come, even though we'd like to. However, we'd be happy to review any pull request to add this functionality, please consider sending us one!

**Comment by helgatheviking** [comment]
I feel your pain. I just sent a PR with the best I can do right now. Good luck with it!
