### ISSUE TITLE
Opt-out of facebook pixel

### ISSUE THREAD

**Issue by crudolf** [facebookincubator/facebook-for-woocommerce#304]
In some countries like Germany, a user needs to be able to opt-out to the facebook pixel. So he has to actively click a button "stop using facebook pixel". 

Do you see a way to extend the plugin in some way? The implementation will be cookie based and is ok to be client-side.

**Comment by mengyingdu** [comment]
Hi @crudolf ,

Facebook-for-WooCommerce is deployed to onboard E-commerce to utilize the pixel off-hand (since all are integrated). I don't think it's possible to opt-out the pixel.

Thanks.

**Comment by scrobbleme** [comment]
Would like to have an configuration option to disable the pixel at all.

**Comment by mengyingdu** [comment]
Hi @crudolf and @scrobbleme ,

Thanks for your input and feedback! In the future we will enlarge the scope of our plugin to business focused level. When we get there, pixel may not a mandatory required.

**Comment by dmitridr** [comment]
Related to #301

**Comment by dmitridr** [comment]
Let's keep all GDPR discussion in one place for clarity (#301).
