### ISSUE TITLE
Problem in connecting the our store to Facebook Shop.

### ISSUE THREAD

**Issue by hasanhalabi** [facebookincubator/facebook-for-woocommerce#305]
We have a site hosted on WordPress.com (https://alsndoos.com). Every time we try to connect Facebook WooCommerce plugin to our Page we got the following message:

> Check that you're logged into your store. You can close this window and reopen the plugin from inside your store's admin panel.

Step 1 (Choose the Page): Done with no problems.
Step 2 (Connect to Pixel): Done with no Problems.
Step 3: the plugin asked me if I want to sync the products and I said (Yes!). I have about 370+ products in the store.

When I click finish, the plugin start processing for a while then shows me the mentioned error message. Please note that I logged in as the Admin for the WordPress Store, Page, and Pixel Accounts.

What shall we do?

Thanks

**Comment by mengyingdu** [comment]
Hi @hasanhalabi,

I checked your site, it seems your pixel is alive, however, your plugin is disabled.
I found something interesting from our log:
There different users trying to set up from US and GB. Is your site dual language? dual currency?

Will all the owners (tried to set up) have the admin access in your woocommerce?

Thanks.

**Comment by pixelmorph** [comment]
I have the exact same  issue...
