### ISSUE TITLE
shop is not created

### ISSUE THREAD

**Issue by bahoffman** [facebookincubator/facebook-for-woocommerce#311]
9 products.
plugin appears to work.
![admin php](https://user-images.githubusercontent.com/8589242/37007364-cc3ec510-2141-11e8-9cb2-c4db85ffb188.jpg)
but no products appear in the FB store - 
https://www.facebook.com/pg/WayOfTheDojo/shop/?ref=page_internal
However, they do appear in my FB product catalog for creating FB ads -
![products](https://user-images.githubusercontent.com/8589242/37007506-6e5d1cc0-2142-11e8-8c18-32c92984b3a0.jpg)

I've tried to re-sync, etc. but no success.
thank you.

**Comment by jieminz22** [comment]
Hi,

Could be the same problem as #281 ? The shop selector is easy to miss during the setup, and can default to off in some cases.

**Comment by dmitridr** [comment]
I'm going to assume it's the same issue and close this up. Generally there are two possible causes for this problem, 1 is outlined in #281, the other is that your page is blacklisted. 

Please open a new issue and reference this one if I am mistaken about this being resolved!

**Comment by bahoffman** [comment]
Thank you so much.
#281 was it. DUH.
