### ISSUE TITLE
Can't edit tracking pixel or delete settings

### ISSUE THREAD

**Issue by awolffmills** [facebookincubator/facebook-for-woocommerce#314]
Hi there,

I am unable to change the tracking pixel that is in use on our site (when I hit the edit button I can select the pixel I'd like to use and hit save, but the "updating" loading graphic appears and never goes away). I confirmed that the account I'm using to connect has ad account admin rights. Also, similarly to a report in another closed thread, I am unable to delete the settings to attempt to reconnect our site and get the message "Sorry, something went wrong. This might be a temporary issue and we're working to get it fixed as soon as we can. Please try again later."

Our site is: https://tattooschool.com and the ad account I'm trying to connect to is: Ad Account ID
10154117686774448 Owned By Academy of Responsible Tattooing (10153761427539448)
It is currently linking to the page https://www.facebook.com/322489314447
The pixel I am attempting to select is: Pixel ID: 531610970333959 (ART ADS)

Thanks!

**Comment by PeterHygge** [comment]
I have a similar problem.

Woocommerce can only see my old pixel. I needed to create a new pixel and have set it up in FB Business Manager but cannot delete the first pixel and replace with the new one. As a result my shop is not displayed in FB.

**Comment by jieminz22** [comment]
Hi,

Looks like there is some permission issue that you don't have access to the catalog anymore. Did someone recently change your catalog permission? Meanwhile if you want, we can reset it from our end for you.

**Comment by awolffmills** [comment]
Not that I know of -- so yes, please reset it.

Thanks!

**Comment by awolffmills** [comment]
My role on the page had been changed without my knowledge, so getting back 'admin' role fixed the issue, no need to take further action. Thank you!
