### ISSUE TITLE
Products Not Syncing to Catalog

### ISSUE THREAD

**Issue by belladonnaboutique** [facebookincubator/facebook-for-woocommerce#315]
I went to go set up dynamic product ads today and it was showing many duplicates of my products in the catalogs on FB. Rather than deleting so many duplicate products, I deleted the catalog.

Then, I clicked Force Products to ReSynce under WooCommerce>>Settings>>Integrations>>FB for WooCommerce.

It showed that it was successful and products reysnced, and that there are 36 products in my inventory which is correct.

But then, on FB, that catalog is not there. My Shop shows 0 products. The product tags in all my posts have disappeared, and there are Sample products that are not mine under the Shop section.

In Ads Manager, under Catalogs, it showed the BellaDonna catalog - but shows 0 products.

However in the FB for Woo plugin, it shows that my products are synced. I have tried Force Resync many times and the same result.

So the plugin shows 36 products, but then FB ads manager shows 0.
![screen shot 2018-03-06 at 10 07 04 pm](https://user-images.githubusercontent.com/35646111/37071519-ddc3d2fa-218a-11e8-858d-f77fdf21d8d3.png)

I have attached screen shots.
![screen shot 2018-03-06 at 9 55 46 pm](https://user-images.githubusercontent.com/35646111/37071421-730876fa-218a-11e8-940b-173fae76b7a7.png)

**Comment by jieminz22** [comment]
Hi,

Directly deleting the catalog from Facebook won't work with our plugin. If you need to reset, you need to do it within the plugin. Try to go do the Advanced Option and choose Delete Settings from there. Let me know if that works.

**Comment by jieminz22** [comment]
Hi,

Regarding to the overwhelming catalog, I understand your concern, but you need not worry, the way Dynamic Ads work no product within the same product group will appear in the same ad. Therefore only one variant of each product will appear in any ad to any user at any one time.

Regarding to the sale prices, can you confirm you are using the latest version of the plugin?

**Comment by belladonnaboutique** [comment]
Where is the latest version? I believe I am
Using the latest one

**Comment by jieminz22** [comment]
The latest version is v1.8.1.

**Comment by belladonnaboutique** [comment]
Yes I have that version.

**Comment by belladonnaboutique** [comment]
Also, the products have disappeared from my FB shop and I cannot tag
products. They used to be tagged in my posts - now that is all gone.
All the products that were tagged in my posts have disappeared and are not
in my shop despite them being in the catalog.

**Comment by belladonnaboutique** [comment]
Well the products are showing in my Shop now but the tags have all
disappeared and I cant seem to re-tag them :-/ Is there a way to fix that?

**Comment by dmitridr** [comment]
Seems like this is mostly resolved except for the product tagging? I believe if you tag the product then delete the product catalog, the product tags will unfortunately disappear. 

I'm not sure why you can't re-tag them, if you could provide us with some screenshots of where you could normally re-tag and a general visualization of the problem maybe we can help figure out what's going on. Though maybe you got it to work since your last post?

**Comment by andrea2803** [comment]
Hello,

I have a problem with the product catalog and I really hope you can help me out.

I succesfully connected woocomerce products with the business manager, but with the wrong page. So the first reaction that I had was deleting the catalog. But now, when I am connecting it to the right page woocommerce detects there are products in my facebook inventory already. 

![screen shot 2018-05-06 at 6 55 16 pm](https://user-images.githubusercontent.com/39031755/39675689-0fa578f6-515f-11e8-8ac3-ec042d074ddf.png)

I tried resyncing products, reconfiguring settings, deleting plugins and then installing it again, different pixels and making new catalogs. I didn't find a sollution.

There are no products in my bussines manager and woocomerce does not give me the option to sync products all over again.

Do you have any additional idea of what can I do to solve the problem?

Best regards!

**Comment by dmitridr** [comment]
Hello @andrea2803 

In the future please open a new issue on us, as it helps us keep track of separate questions and answer them in a timely manner. The display of products in your inventory is just a count of products in WooCommerce itself. 

If you go to `Reconfigure > Advanced Options > Delete` you should be given the option to sync products all over again and indeed set up again. Hope that helps.
