### ISSUE TITLE
Facebook Shop and Catalog not working products are not getting synced

### ISSUE THREAD

**Issue by annsali** [facebookincubator/facebook-for-woocommerce#316]
i cannot see the products in my shop neither can i make dynamic ads or product catalog ads.
my website is fasterpakistan.com and my facebook page is https://www.facebook.com/FasterPakistani/

**Comment by annsali** [comment]
![image](https://user-images.githubusercontent.com/10221271/37079004-e1f5a754-2202-11e8-8c26-44077d686c73.png)
It shows product inventory and all products that have synced fine
![image](https://user-images.githubusercontent.com/10221271/37079084-26c70c60-2203-11e8-900b-c1b5893b1b05.png)
but my catalog shows 0 products and my shop is empty
![image](https://user-images.githubusercontent.com/10221271/37079717-658cbbc8-2205-11e8-80e1-4fc91c113fc5.png)

ive already tried this

Delete all settings in woo plugin
Use delete_all_settings(); on js console
Uninstall plugin
Download latest version
Upload and activate plugin
Initiate the setup

**Comment by jieminz22** [comment]
Hi,

Sorry for the issue. I think your product weren't uploaded because their description are all uppercase. We are actually working on a fix to support all caps description so they won't fail on uploading. The fix will be included in our next version.

**Comment by dmitridr** [comment]
The fix is out in v1.8.2 and can be found [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases)
