### ISSUE TITLE
Variable Products

### ISSUE THREAD

**Issue by PeterHygge** [facebookincubator/facebook-for-woocommerce#317]
Hi
All my products are variables (based on size) and in my woocommerce store the default value is 'null' so the customer must select a size. In my FB shop the products are defaulting to the biggest size and highest price, which I feel may put people off the product. Can you advise? Thanks!

**Comment by jieminz22** [comment]
Hi,

Could you take a look at #171 see if the solution works for you? Basically you need to set the default with the price you'd like to show.

**Comment by dmitridr** [comment]
Closing this up. Please open a new issue on us if the advice in #171 did not solve your problem.
