### ISSUE TITLE
Lost connection between woo and FB: upgraded plugin to latest but still no joy

### ISSUE THREAD

**Issue by kevinw199** [facebookincubator/facebook-for-woocommerce#320]
A few days ago I installed Google Analytics for Ecommerce and that broke the connection between Woocommerce and Facebook on my site. I dug around here and found that the problem was an outdated plugin version.

So I installed the newest version (1.81) from Github and tried to reconnect, but the plugin is acting as if I have to start again from scratch to connect to FB.  When I try to do that, I get this message:

"A Facebook Page can only be connected to one store at a time. Lions Gate Models: building instructions to use with your LEGO bricks is already in use by another WooCommerce store. "

It's hard to tell whether the message is coming from the FB end or the plugin. Of course, this is the page I had connected to this site (lionsgatemodels.com) via this plugin, before.

What do I need to do to re-establish the connection?

**Comment by jieminz22** [comment]
Hi,

That message is coming from FB side. What screen do you first see when you open this plugin again? If you see a Advanced Settings option on the left hand side, you can use that to delete your current settings and restart setup. Let me know if that helps.

**Comment by kevinw199** [comment]
Thanks for responding.

No advanced settings show up.
![image](https://user-images.githubusercontent.com/37189581/37174360-1b6095bc-22cb-11e8-80a7-e8001cdb2bbc.png)

Since I've never made a sale through my FB shop, I'm not too worried about losing that, but I do want to be able to use my FB pixel with a different plugin. Any advice on convincing FB that I am no longer connected to that page?

I am comfortable working in the WP database via phpadmin if that's needed to get rid of the connection.

**Comment by jieminz22** [comment]
Please click Get Started. Looks like you haven't finished setup yet. Then you will have the option to disconnect a page from a shop during the page step.

**Comment by kevinw199** [comment]
Finally found the "disconnect a page" button, did so, and got things hooked up again like they were before.
Thanks for the help!

Does this plugin now notify us when it needs updating, like most plugins do?  That would be very helpful.

**Comment by dmitridr** [comment]
@kevinw199 Glad we could help. Our plugin support auto-update, but if you don't have that enabled you'll have to go to the plugins page to see the notification that the plugin needs updating, @mengyingdu added this feature in 1.7.0 I believe. Hope that helps!
