### ISSUE TITLE
Can't setup the plugin manually

### ISSUE THREAD

**Issue by edirpedro** [facebookincubator/facebook-for-woocommerce#321]
I'm just reporting a bad concept with the setup form.

There is a problem with this plugin, I have to be the owner of the facebook accounts to make the setup. My client has another company doing the marketing and I can't share administration access to the store just to setup this plugin. So how can i ask them to all of those data to setup? Even I couldn't find all the informations to register that form manually.

Facebook Page ID: Easy to find
Product Catalog ID: Where do i find it?
Pixel ID: Easy to find, there is a button to send this data to developer
External Merchant Settings ID: Where do i find it?
API Key: Where do i find it?

There is a button on facebook documentation that sends information to developer, but it can send only the Pixel ID and not all the other data. And there is no information on the setup page to indicate where to find those IDs.

**Comment by jieminz22** [comment]
Hi,

You have to be the admin of their page in order to install this plugin. You will also need to have access to their pixel.

**Comment by dmitridr** [comment]
Hello,

You shouldn't need any IDs in order to set up, the page and pixel can be selected from the popup screen, and the catalog will be created for you.

If you are seeing a form, this may be because you have debug mode enabled in wordpress. Could you paste a screenshot of what you are seeing so that we can confirm?

**Comment by edirpedro** [comment]
Yes, debug mode was enabled when I was testing the plugin. In the production there is no form to fill, just the popup. I thought I could fill that form manually, but this is not possible.

My problem was with the setup using that popup, because I need to be the owner of the facebook accounts to setup, or I need to have administrator roles at least. But I'm not, the facebook  account is managed by another company and the only way to setup the plugin was giving temporary administrator access to the store for that company, so they can login and use that popup.

Usually to setup an API i can just ask the company for some data like token and secret key, when they don't want to give me administrator access to create that token. So I'm just giving here a feedback about the way the plugin is setting up.

**Comment by dmitridr** [comment]
Fair enough, thank you for the feedback. 

It seems that our plugin does not work well in the case where this data needs to be manually set by someone without access to the company's assets. We built the plugin primarily with the use case of self-install in mind, which requires permission on all the assets in FB.

I will think about how we can accommodate this use case better, but I don't see a very easy way that is also privacy-safe.

**Comment by edirpedro** [comment]
I see an option. Currently the setup panel is inside the Woocommerce Integration tab and there you can't provide access only to that tab and page. A workaround could be using a separated page to setup the plugin, inside the Wordpress Settings menu for example, with a exclusive capability. With that capability I could use any role manager plugin, like members plugin, to set an exclusive access to this settings page only for an specific user.
