### ISSUE TITLE
No settings saved after update to 1.3.2

### ISSUE THREAD

**Issue by Demuri** [facebookincubator/facebook-for-woocommerce#322]
Again "Facebook for WooCommerce is almost ready. To complete your configuration, complete the setup steps." This error repeats for some time.
How should I add settings without loosing my catalogue on FB? Any fix?

**Comment by jieminz22** [comment]
Hi,

Have you tried to launch the plugin and finish setup?

**Comment by Demuri** [comment]
Yes. “Your page is already connected to one shop”. Last time I disconnected it I lost my catalogue.

**Comment by dmitridr** [comment]
Hey, we had a bug like this long ago, pre 1.5, 1.3.2 is an ancient version could you upgrade? The problem should definitely go away. We are up to v1.8 now, check out our [releases page](https://github.com/facebookincubator/facebook-for-woocommerce/releases).

**Comment by dmitridr** [comment]
For the problem of disconnecting and losing your catalog, unfortunately there is no solution, you will have to reset the catalog one last time. Rest assured, this problem will not happen again though. 

Issue #43 covers this in greater detail.
