### ISSUE TITLE
Error on Product Sync

### ISSUE THREAD

**Issue by HW-Siew** [facebookincubator/facebook-for-woocommerce#328]
Hi, when i update a product, it shows an error below. Any idea what caused this? thank you

```
> Facebook extension error: Facebook for WooCommerce
> (#100) Invalid parameter
```

**Comment by dmitridr** [comment]
Hello, 

It sounds like maybe it's a bug? Could you give us a link to your page or your page id? We have logging about failed product uploads that we could check to identify the problem.

**Comment by HW-Siew** [comment]
Hi, here you go for my facebook page https://www.facebook.com/actiweb.co/.

**Comment by HW-Siew** [comment]
Another error showed today !

Facebook extension error: Facebook for WooCommerce
Unsupported post request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

**Comment by dmitridr** [comment]
Hey,

I checked our logs, and it seems like you upgraded from 1.7.x to our latest version 1.8.1, which is great. I see the same errors you see in our logs also, and it seems there are some items left over in your DB from the old installation that are causing you to see some errors in the new one. It seems like you re-set the plugin around the time you made this post, did that help? 

I don't see the first kind of error anymore, only the second one. 
My recommendation:
- Try Force Resync. Perhaps FB went out of sync?
- Try another reset.

It may be some conflict with another plugin. The API requests I see coming from your server in our logs are very strange and contain only a visibility parameter and no other information.

**Comment by HW-Siew** [comment]
Thanks. it works !
