### ISSUE TITLE
Purchase Pixel not firing AGAIN!! : Google Enhanced E-Commerce Plugin Compatibility

### ISSUE THREAD

**Issue by belladonnaboutique** [facebookincubator/facebook-for-woocommerce#329]
Hi, I am really getting frustrated with this plugin! How am I supposed to run ads and make sales if this plugin keeps getting messed up with pixel fires?!

The Purchase event is showing as Active, it was last received 6 days ago. However, I started running a Purchase conversion ad this morning and got 1 sale. The Add to Cart and Initiate Checkout pixels were fired, but the Purchase pixel was not! It is still lit up as Green and active, but for some reason it is not actually firing. I checked the order-received page using CHrome pixel helper to see if it was there, and it isn't showing up on that page.

Please see attached screen shots. I am really frustrated! I would appreciate a fast response and fix because every time this happens I have to stop running ads and sometimes it takes a week to get a response. 
![screen shot 2018-03-15 at 10 14 53 am](https://user-images.githubusercontent.com/35646111/37468820-4f1f6f8a-283a-11e8-9edc-00e8ac93f567.png)
![screen shot 2018-03-15 at 10 14 35 am](https://user-images.githubusercontent.com/35646111/37468874-663f707a-283a-11e8-972f-5c1dfccd22b6.png)

**Comment by belladonnaboutique** [comment]
UPDATE:  My Purchase pixel shows as active in ads manager, but in the details it says it hasn’t fired in 6 days, and I had a sale this morning. 

It didn’t register under the actual ad in my Ads account either. 

It is also NOT showing up in my Google Analytics account! Google Analytics has been tracking ALL my sales and traffic, I don’t know why it suddenly didn’t track the sale today! 

I went and did a few test purchases to see if the Purchase event was active on the right page. I did a test purchase for PayPal, Stripe and square, and the chrome pixel helper does show the purchase pixel on the order received page.

I then checked my ads manager and it briefly showed that the purchase pixel fired, but then when I refreshed the ads manager —> Pixels page a few minutes later, it went BACK to saying it fired 6 days ago!! The Purchase Fire completely disappeared! Anyone have an idea what could be going on? 

I DO have the latest updated version from
New plugin release from two weeks ago. I don’t know what else to do since the chrome pixel helper shows it is active and on the right page - so why is that data NOT being transferred to FB and Google analytics? It’s only doing this for Purchase

**Comment by dmitridr** [comment]
Hello,

Thanks for writing in about your issue.
I'm glad If the chrome pixel helper tool shows the pixel is firing when you do a test purchase on your own website, then it should be working and correctly it's not a bug in our plugin. 

I can think of a couple of causes:
(1) There was a site-wide issue yesterday where some purchase data was lost in our system. So this could be a 1 time thing due to this site-wide issue.
(2) The sale came from a user who asked us not to be tracked. So we can't track this user or report the purchase to you, as it would violate our own terms of service.
(3) There is a bug in the interface you are using to track the purchase. I guess your screenshot is from either ads manager or events manager? If you observe the issue happening again, we can pass this as a bug report to that team.

In general, I recommend waiting for some time and confirming that the issue keeps happening. If you observe the issue keeps happening, it will rule out (1) and (2). But I'm not sure about (3) either, because if you saw the problem in Google Analytics, then there's a big chance the problem is unrelated to Facebook.

**Comment by belladonnaboutique** [comment]
I do not have any kind of pop up or form that would allow someone to opt
out of tracking data yet, so that part is not the issue.

What do you mean by “the interface I am using to track my data?”

I am using Ads Manager and Google Analytics. Neither showed the sale.

After I did the test purchase (3 times) it showed up under the Pixels
section of Ads Manager, the Purchase pixel WAS fired. But when I refreshed
the page a few minutes later to ensure that the data still showed, it
reverted back to “6 days ago” instead of “received in the last minute.”

I don’t understand why this would happen both in GA and Ads Manager.

On a side note, when I was trying to set up my dynamic product ads a few
days ago, it was also saying in ads manager that the Purchase pixel wasn’t
firing (This was under Dynamic Product Ad creation, not the main ads
amanger.)

**Comment by belladonnaboutique** [comment]
Per your point 3) it did happen again. It happened with my Test purchases
that I did 3 times! It didn’t relay the Purchase information to FB ... soo
there is something going wrong between the purchase pixel being fired and
the data flow to both FB and GA.

**Comment by dmitridr** [comment]
I think your own purchases (if you were logged in to FB when making the purchase) might not show up in your own reporting, so it's more reliable to wait for another purchase to be sure.

Two more thoughts that may help:

(1) The fact that it's happening for GA too could mean it's some kind of local issue on your site. For example, perhaps the user made a purchase in a way (different checkout method?) that did not fire the FB pixel correctly or register correctly in GA. If you have the data on the purchase method used by the user who made the sale, I'd verify that that specific purchase method is firing the pixel.

(2) Regarding the tracking, we do allow users to opt out in our own interfaces on Facebook. That the user didn't register in GA maybe means they opted out of being tracked by Google as well. 

I'm also at a loss to explain why both GA and Ads Manager didn't pick it up. But at this point I think it's possible it's a one time issue.

**Comment by belladonnaboutique** [comment]
The user Purchase using Square. I tested Square and it does work with the
pixel active, it simply redirects to my order received page where the pixel
is.

As far as users being able to opt out, where and how do they do this? I
have never seen any kind of notification or blurb on my site or in the
check out process in regards to opting out, so I am not sure how they could
do this? Can you show me a screen shot or something of where this opt out
is?

I know there are new laws with the GDPR and was wondering how I am going to
address that on my site, so if the option to opt out  is already there
maybe that’s all I’d need but I’d like to see where it is because I’ve
never seen it or known that was an option.

I did have one person in a WooCommerce help FB group say that if I have
meme cache enabled this could be it. I am going to check to see if it is
enabled; he suggested turning off meme cache and purging the cache so I
will try this if it is turned on.

I am just nervous/reluctant to start running an ad again if it’s not
tracking the purchases. That is the only way I’d know sooner because
without ads it can take several days before I’d see another sale again.

**Comment by dmitridr** [comment]
Here is where users can go https://www.facebook.com/ads/preferences/?entry_product=ad_settings_screen to opt out of seeing ads based on their online behavior. I am not certain whether this means they will not be tracked completely, but it's possible.

Another option is that the user had a do-not-track browser extension installed. With such an extension, ,for example `Ghostery`, data sent to GA and FB and any 3rd party will be blocked completely.

After thinking about it some more, I think the above is most likely what happened, the other explanations are just too unlikely. Though it could be a cache issue you like you say.

Regarding adding an opt-out notice on your site (which is different from the opt-out I was mentioning before), we have an open issue about that here #301. Hope that helps. I understand your reluctance to restart ads, but if the pixel helper tool says it's working, from my experience in dealing with other issues like this one, almost certainly it's working.

**Comment by belladonnaboutique** [comment]
Hi there,

I spoke with Google and they went through my website. THey were able to
tell me that the Ecommerce code was REMOVED from my order-received (order
confirmation) page.

I have not touched any of the coding, except for installing the new updated
plugin of FB for WooCommerce last week.

I am not sure if others are having this trouble, because you mentioned
people were losing purchase data - but I think the plugin might have
removed my Google eccommerce tags.

Also, I had another sale this morning, and the FB purchase pixel did not
fire again.

SO there is something going on with the coding for the purchase data. Can
you please assist?

**Comment by belladonnaboutique** [comment]
Even stranger - FB did NOT register the Purchase data for the 2 sales I had
yesterday and today. It registered the Adds to Cart, and the Initiate Check
Outs, but not their purchases.

However, the test purchase I made yesterday, DID register with FB, but not
with Google because my ecommerce tags were somehow removed.

So it is really weird that FB would track MY test purchases, but not the
actual purchases that others made. I also have no clue how my ecommerce
tags for Google were removed.

**Comment by belladonnaboutique** [comment]
UPDATE: I think I figured out the Google issue. I had an enhanced ecommerce
plugin and under my Ecommerce settings in my GA the "Enable Enhanced
Ecommerce Settings" was turned off. I turned it back on.

So I will see now if the data starts to flow to GA. However, still unsure
of why FB Purchase pixel is not firing. Add to Cart and Initiate Check-Out
update immediately in Ads Manager, but Purchase pixel is still not.

**Comment by belladonnaboutique** [comment]
I went through the Analytics section in my FB ads manager. Please see the attached screen shots.
For some reason, it tracked MY test purchases of $0, .40 and $1. 

It did NOT track the purchase of my website visitors. It DID track their Initiate Check Out though.

It doesnt make sense that the reason for lost purchase data would be because they opted out. If they opted out, I think I would not have been able to track the Adds to Cart and the Initiate Check Outs. 

So, there must be something else going on with the Purchase data tracking for external users. 
![screen shot 2018-03-16 at 11 23 29 am](https://user-images.githubusercontent.com/35646111/37529252-098c3d1c-290d-11e8-9c1d-64b1fe376d6c.png)
![screen shot 2018-03-16 at 11 24 20 am](https://user-images.githubusercontent.com/35646111/37529261-116b4b7c-290d-11e8-994b-b9e5377e5d66.png)
![screen shot 2018-03-16 at 11 24 53 am](https://user-images.githubusercontent.com/35646111/37529276-1aa99cac-290d-11e8-8a29-fbf554a10d31.png)

**Comment by MiladyWanna** [comment]
Hello.
I am experiencing the exact situation that belladonnaboutique has signaled.
Every last detail of the issue is covered, including the reading of my purchase and not the ones coming from campaigns.
I am really hoping for a solution as this has been going on for 5-6 days now.
Thank you.

**Comment by dmitridr** [comment]
The issue appears to be that we have a compatibility problem with `Google Enhanced E-Commerce` as mentioned in issue #319 . Thanks for your work in tracking this down, we'll prioritize fixing that, it seems this is a high priority problem.

**Comment by MiladyWanna** [comment]
thank you for clearing things up, dmitridr. i have disabled the Google plugin and will hope to receive a quick fix.

**Comment by dmitridr** [comment]
I think a workaround you can try in the meantime is to try and use the `PixelYourSite` plugin, which should be compatible with ours and replaces the pixel, it should also not have the compatibility issue with Google according to the reports in #319.

Could either of you share with me your settings for the Enhanced E-commerce plugin you are using? I am unable to reproduce the problem on our test servers, so it will be difficult for us to fix. It could also be that there are multiple problems here (the Purchase problem, and the tags vanishing)...

**Comment by dmitridr** [comment]
Additionally it would be helpful to have the version info for that plugin, and whether or not you have the premium version. Thanks!

**Comment by MiladyWanna** [comment]
i have  2.0.0 version, not the premium version, just the regular.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MiladyWanna** [comment]
also, as settings,

**Comment by belladonnaboutique** [comment]
I am not sure what's changed but all of a sudden NOW my Purchase pixel is
firing and my Google Analytics is working!!

MiladyWanna - make sure when you go to Google Analytics -- Admin
Settings--> Ecommerce Settings, check to see if "Enhance ECommerce
Reporting" is toggled OFF.
I had called Google this afternoon and they informed me the Ecommerce code
was missing from my Purchase page which was strange because I hadn't
touched the code.

I also have the Enhanced Ecommerce plugin, and I went to the plugin website
to check what their instructions were, and in it they said to toggle the
Enhanced Ecommerce Reporting ON in the Ecommerce Settings in GA. I thought
I would check my GA to make sure it was on, and when I looked it was
actually OFF!!

I toggled it on about 6 hours ago, and now it seems to be working. I dont
know how that got turned off - but do check your GA to make sure!

**Comment by MiladyWanna** [comment]
belladonnaboutique thank you so much for sharing, you are a life-saver.
just checked and  Enhance ECommerce Reporting  was actually ON, so I
switched it OFF.
i will check if everything goes back to normal but you've already confirmed
so it should be fine. thank you a lot!

**Comment by belladonnaboutique** [comment]
No no you want it ON!

Mine had been off! I had to turn it on. But maybe if you toggle it off then
back on it could reset it?

**Comment by MiladyWanna** [comment]
yes, i did just that and hopefully will see a difference tomorrow. thank
you.

**Comment by dmitridr** [comment]
We fixed this compatibility in 1.8.7, it's available [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.7). Please open a new issue and reference this one if the problem occurs again.

Details : The issue was one of JS insertion into WooCommerce, both our plugin and Google do this insertion, however because of the way the insertion works our JS is inserted in between the Google tracking code, which appears to be the cause of the problem, we changed the insertion so that ours is inserted above the Google code, which should prevent interference. The problem appears to occur specifically when the user is not logged in.
