### ISSUE TITLE
facebook pixel unable to connect

### ISSUE THREAD

**Issue by flashcrow2000** [facebookincubator/facebook-for-woocommerce#330]
I'm getting the 'Unable to connect' message after completing the setup process. I installed version 1.8.1, after trying to install an older version which was breaking my website.
I appreciate any help or advice you can provide. Thank you!

**Comment by dmitridr** [comment]
Hello,

Can you provide a screenshot of where you see this 'Unable to connect' message?

**Comment by flashcrow2000** [comment]
it's on the facebook pop-up, after setting the Facebook page and the Facebook store.

**Comment by flashcrow2000** [comment]
Just checked with the FB Pixel Header and it finds a pixel on the page, but it's a different id than the one from the ads manager. I guess i need to remove that one first.

**Comment by dmitridr** [comment]
To clarify, do you get this message
(1) when you re-open the popup after setting up?
(2) or after clicking finish during the set up?

Generally, unable to connect happens if you close the parent window, or navigate to another location. This disrupts the communication between the popup and your woo store. If you keep both the configuration window and the popup open, it should generally work unless there's some bug. Let me know if that helps.

**Comment by flashcrow2000** [comment]
I'm getting this message after clicking finish.
Both facebook and wordpress pages are open.

**Comment by dmitridr** [comment]
Can you share your facebook page (via link or name or id) with us? We can check our logs to see what happened. What you describe is possible if there's a critical error in the plugin or in wordpress when the popup window communicates with wordpress. 

Basically we created your catalog and API token and etc, passed that down into the plugin, but the plugin couldn't save it into your DB for some reason, that's what I believe is going on.

**Comment by flashcrow2000** [comment]
the facebook page is: iqbebero

**Comment by flashcrow2000** [comment]
hi .. any luck finding anything? I removed all the inline pixels or tracking modules, i uninstalled the woocommerce plugin too, did a fresh install of 1.8.1 but it still says 'Unable to connect'.
The language in the facebook pop-up is not English, so I'm not sure how what's the error text in english, but roughly it translates to:
"Failed to connect
Check if you are connected to your store. You can close this window and re-open the plugin from your store's control panel."

Are there any modules which might affect this communication? Should I try using a different browser? 
Thank you!

**Comment by flashcrow2000** [comment]
I installed it manually ... unfortunately i wasn't able to get the plugin working. might be an issue with writing into my database, or another setting on my website. This was a multisite, btw .. maybe that's the reason.

**Comment by dmitridr** [comment]
Hey again,

Yeah I checked our logs and I see that your server responded with a 500 error when we tried to save your catalog / API token / other settings into your DB. Do you have any internal logging you can look at for your server to see if there is a stack trace/exception there in the logs (I'd search for `Facebook` in the logs) we can use to identify the problem?

All I can tell from here is that the problem happened in the part that saves settings to your `wp_options` table. It could be a problem with the DB, or in the part that calls the DB.

Can you explain your multisite configuration? It sounds like it could be related.

**Comment by dmitridr** [comment]
Hey, 

I'm closing this out because there hasn't been a response in over 2 months. If you still have this problem, please open a new issue on us and reference this one, and we can follow up.
