### ISSUE TITLE
Facebook purchase pixel not working

### ISSUE THREAD

**Issue by Danielriott** [facebookincubator/facebook-for-woocommerce#331]
Hi.

I just noticed today that for the last 8 days, my purchase pixel has not been working.
We have orders everyday, so that's not the problem.

I tested it today with the pixelhelper, and got this from it (see screenshot).
![image](https://user-images.githubusercontent.com/37449380/37529242-ebabb4c4-2936-11e8-98b7-ef2e53c5625f.png)

It doesn't help me at all as i dont see a problem with the code.
The plugin has been working fine untill now.

What do i do to fix this problem? Right now i cannot make any ads as i cannot track conversions.

Kind regards
Daniel

**Comment by dmitridr** [comment]
Hello,

This is troubling. I verified that the Purchase event does work for our store, so it must be a problem specific to your store or a setting that you have that we don't. I have a couple of questions to try and help us get to the bottom of this problem :

(1) Can you think of anything that you did around the time the purchase stopped firing? For example, was there a new plugin you installed or a configuration you changed?

(2) Can you verify that you had adblock and any adblock-like extensions turned off when testing the pixel using the pixel helper?

(3) Is this problem specific to one purchase method (e.g. PayPal only?) or does it occur for all payment methods in your store? 

(4) Can you email us the source code of the page after you make a purchase on your store.? Our email is ads_extension_woocommerce@fb.com We may be able to identify the problem by looking through that.

Thanks.

**Comment by dmitridr** [comment]
One more thing, do you have the Google Enhanced E-Commerce Plugin? We've had recent reports that this is interfering with Purchase events. 

Related Issue : #329

**Comment by Danielriott** [comment]
Okay thanks.
I will try to remove all plugins one by one and see if i can find one that is a problem.
I have send you an email with the source code on the "thank you" page :)

I will be back asap

**Comment by dmitridr** [comment]
Hey, 

Any luck?
I got your email and looked through the source, it seems there is some suspicious code about `mini_cart_item` and another add to cart extension being injected into Javascript in the same area as the purchase event which are possibly causing confusion in the pixel helper tool or in the code execution itself.

I am not sure if these are the causes but you could try disabling plugins related to add to cart functionality, in order to fix it. We may also be able to fix it by raising the priority of the injection of the purchase event to be above that of whichever plugin ads the `mini_cart_item` stuff.

**Comment by dmitridr** [comment]
Following up on this older issue: We changed the way we inject all pixel events in 1.8.7 which fixed compatibility issues with some plugins, including `Google Enhanced ECommerce` which were causing some problems with these events. Chances are that upgrading will fix this older issue. 

If you are still having this problem with the new version, please open a new issue on us and reference this one. I will close this out.
