### ISSUE TITLE
<!-- End Support AJAX add to cart</script> not correctly closed

### ISSUE THREAD

**Issue by Remcotv** [facebookincubator/facebook-for-woocommerce#336]
Hi,

I get the following tag in my html code: 
</script>

How to ge this fixed?

**Comment by dmitridr** [comment]
Hey,

It seems closed to me : [here's the code in our GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.8.1/facebook-commerce-pixel-event.php#L92)

Could you confirm you have the latest version v1.8.1?
If you do, maybe it's another add-to-cart plugin that's causing some kind of interference. Do you have any custom add to cart plugins?

**Comment by dmitridr** [comment]
If you send us a link to your site, we can also take a look at the source and try to guess what's going on.

**Comment by Remcotv** [comment]
http://www.happy-orange.nl

 

Van: Dmitri Dranishnikov <notifications@github.com> 
Verzonden: maandag 19 maart 2018 20:12
Aan: facebookincubator/facebook-for-woocommerce <facebook-for-woocommerce@noreply.github.com>
CC: Remcotv <remco@dutchfresh.com>; Author <author@noreply.github.com>
Onderwerp: Re: [facebookincubator/facebook-for-woocommerce] <!-- End Support AJAX add to cart</script> not correctly closed (#336)

 

If you send us a link to your site, we can also take a look at the source and try to guess what's going on.

**Comment by Remcotv** [comment]
Thanks, i have the version 1.6.6?

 

Van: Dmitri Dranishnikov <notifications@github.com> 
Verzonden: maandag 19 maart 2018 20:11
Aan: facebookincubator/facebook-for-woocommerce <facebook-for-woocommerce@noreply.github.com>
CC: Remcotv <remco@dutchfresh.com>; Author <author@noreply.github.com>
Onderwerp: Re: [facebookincubator/facebook-for-woocommerce] <!-- End Support AJAX add to cart</script> not correctly closed (#336)

 

Hey,

It seems closed to me : here's the code in our GitHub <https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.8.1/facebook-commerce-pixel-event.php#L92> 

Could you confirm you have the latest version v1.8.1?
If you do, maybe it's another add-to-cart plugin that's causing some kind of interference. Do you have any custom add to cart plugins?

**Comment by Remcotv** [comment]
How to get this plugin updated?

 



 

Van: Dmitri Dranishnikov <notifications@github.com> 
Verzonden: maandag 19 maart 2018 20:11
Aan: facebookincubator/facebook-for-woocommerce <facebook-for-woocommerce@noreply.github.com>
CC: Remcotv <remco@dutchfresh.com>; Author <author@noreply.github.com>
Onderwerp: Re: [facebookincubator/facebook-for-woocommerce] <!-- End Support AJAX add to cart</script> not correctly closed (#336)

 

Hey,

It seems closed to me : here's the code in our GitHub <https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.8.1/facebook-commerce-pixel-event.php#L92> 

Could you confirm you have the latest version v1.8.1?
If you do, maybe it's another add-to-cart plugin that's causing some kind of interference. Do you have any custom add to cart plugins?

**Comment by dmitridr** [comment]
Hey,

You can do that from www.woocommerce.com, or from our releases page directly on [GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/releases).

We added auto-update in 1.7.0, so after you install a new version, you should be able to update it directly in the plugins page of your own admin panel. Let us know how it goes after the update, whether you have the same issue.

**Comment by Remcotv** [comment]
Hi Dmitri,

 

Have updated the plugin. Still face the same issue, tested in different browsers also:

 



if(typeof jQuery != 'undefined') {

  jQuery(document).ready(function($){

    jQuery('body').on('added_to_cart', function(event) {

 

      // Ajax action.

      $.get('?wc-ajax=fb_inject_add_to_cart_event', function(data) {

        $('head').append(data);

      });

 

    });

  });

}

<!-- End Support AJAX add to cart</script>

 

Van: Dmitri Dranishnikov <notifications@github.com> 
Verzonden: maandag 19 maart 2018 20:55
Aan: facebookincubator/facebook-for-woocommerce <facebook-for-woocommerce@noreply.github.com>
CC: Remcotv <remco@dutchfresh.com>; Author <author@noreply.github.com>
Onderwerp: Re: [facebookincubator/facebook-for-woocommerce] <!-- End Support AJAX add to cart</script> not correctly closed (#336)

 

Hey,

You can do that from www.woocommerce.com <http://www.woocommerce.com> , or from our releases page directly on GitHub <https://github.com/facebookincubator/facebook-for-woocommerce/releases> .

We added auto-update in 1.7.0, so after you install a new version, you should be able to update it directly in the plugins page of your own admin panel. Let us know how it goes after the update, whether you have the same issue.

**Comment by dmitridr** [comment]
Hello,

Could you please verify that your version is indeed 1.8.1, and you have cleared the javascript cache of both your website and your browser?

The code you posted is code from our 1.7.x and 1.6.x versions. It can be seen here : https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.7.0/facebook-commerce-pixel-event.php#L39

The code you should see if you have the 1.8.x versions is different, and can be seen here:
https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.8.1/facebook-commerce-pixel-event.php#L83

For example, there is no `if(typeof jQuery != 'undefined')` portion.

**Comment by Remcotv** [comment]
Hi Dmitri,

 

Cleared the browser cache, cleared the server cache.

 

And have the version 1.8.1 installed and activated: still get the following

 

<script>fbq('init', '650231228698532', {}, {
    "agent": "woocommerce-3.3.4-1.8.1"
});
 
fbq('track', 'PageView', {
    "source": "woocommerce",
    "version": "3.3.4",
    "pluginVersion": "1.8.1"
});

document.addEventListener('DOMContentLoaded', function() {
  jQuery && jQuery(function($){
    $('body').on('added_to_cart', function(event) {
      // Ajax action.
      $.get('?wc-ajax=fb_inject_add_to_cart_event', function(data) {
        $('head').append(data);
      });
    });
  });
}, false);
<!-- End Support AJAX add to cart</script> 

 

 

Van: Dmitri Dranishnikov <notifications@github.com> 
Verzonden: Tuesday, March 20, 2018 10:28 PM
Aan: facebookincubator/facebook-for-woocommerce <facebook-for-woocommerce@noreply.github.com>
CC: Remcotv <remco@dutchfresh.com>; Author <author@noreply.github.com>
Onderwerp: Re: [facebookincubator/facebook-for-woocommerce] <!-- End Support AJAX add to cart</script> not correctly closed (#336)

 

Hello,

Could you please verify that your version is indeed 1.8.1, and you have cleared the javascript cache of both your website and your browser?

The code you posted is code from our 1.7.x and 1.6.x versions. It can be seen here : https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.7.0/facebook-commerce-pixel-event.php#L39

The code you should see if you have the 1.8.x versions is different, and can be seen here:
https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.8.1/facebook-commerce-pixel-event.php#L83

For example, there is no if(typeof jQuery != 'undefined') portion.

**Comment by sammul** [comment]
@Remcotv where do you see the error? Can you attach a screenshot? I see your pixel is correct firing 
![screen shot 2018-03-22 at 11 12 32 am](https://user-images.githubusercontent.com/4251631/37789762-f71ac982-2dc1-11e8-8e3b-5bd56dbbd5a4.png)

**Comment by MrBlank** [comment]
For anyone finding this with the same problem, it was a plugin conflict that caused this issue for me.

The HTML compression of the Autoptimize plugin was removing the closing comment tag in `<!-- End Support AJAX add to cart</script>` for me. turning off HTML compression fixed the issue.
