### ISSUE TITLE
Incompatible with Google structured data testing tool

### ISSUE THREAD

**Issue by mawtt** [facebookincubator/facebook-for-woocommerce#338]
Hi 
My theme adds woocommerce product JSON structured markup and for some reason it was not appearing in googles test for structured markup.

I finally managed to nail it down to this plug in by switching all plugs off and slowly bringing them back on.  As soon as this plug in was switched on it stopped all of my themes mark up appearing.

Im on 1.8.2 of this plug, Woocommerce 3.3.4 and wordpress 4.9.4

i have attached screen shots of before and after in the structured test. The image with Product data included is with your plug in switched OFF.
<img width="706" alt="screen shot 2018-03-22 at 12 53 07" src="https://user-images.githubusercontent.com/37661154/37771610-149559ba-2dd0-11e8-9d5c-01a56d9611e2.png">
<img width="716" alt="screen shot 2018-03-22 at 12 51 55" src="https://user-images.githubusercontent.com/37661154/37771639-204645bc-2dd0-11e8-9cb0-d60ce2fbd814.png">

Also, if you check this url please, you'll see the JSON is in the header for the page BUT this plug in seems to stop google from seeing it, when testing for structure data. 

calmhappyhealthy.com/home-garden/natural-dish-washing/dishwasher/bio-d-dishwasher-powder-720g/

Thanks

**Comment by sammul** [comment]
Hi thanks for reporting, have you disabled the plug-in(I don't see it on your website). Which theme are you using?

**Comment by mawtt** [comment]
Hi 

Thanks for getting back.

No the plug in is still activated and on.

I’m using Handy Theme

Thanks

**Comment by sammul** [comment]
@mawtt Are you using some plug-in from google?

**Comment by mawtt** [comment]
only a google tag manager for analytics. And another for Google review stars.

**Comment by mawtt** [comment]
yes if you go to this url....
https://search.google.com/structured-data/testing-tool#

this is googles tool to test if your structured data markup (schema) is showing and working ok.

if you place in any product url from my shop you will see that organisation and website markup load ok. BUT there should be Product too (please look at my two attachments from earlier) and you can see one of the screenshots, has your plug in turned off and it shows the correct markup showing, that includes Product and also WP header, Footer etc.

When you checked my product page url, did you check the header filer in google console, and see the JSON script?  if you click not hat script on google console, you will see the product schema that should show and is being stopped by your plug in.

Thanks

**Comment by mawtt** [comment]
Hi Sammul
Just wondering of you managed to see what was happening with this please?
Thanks!

**Comment by sammul** [comment]
@mawtt I was able to reproduce the issue. Thanks for reporting. 
I'm labeling it as a bug and will look into shortly. Unfortunately there is no workaround in my mind currently.

**Comment by sammul** [comment]
@mawtt However the issue doesn't happen on my test website: http://ec2-54-153-37-179.us-west-1.compute.amazonaws.com/product/hoodie-with-logo/

If you try this product. Wondering why it only happens to you

**Comment by mawtt** [comment]
For that product is the structured data added by the theme in JSON?

And if you were able to reproduce the issue, does that not show, it is probably not just my site is affecting? Maybe others just don't realise it's happening?

What process did you run to test and reproduce the error please? That might help me see a reason

**Comment by sammul** [comment]
@mawtt I was able to reproduce the issue with your product(the link you shared).
However, my test website(the link I sent) doesn't have this issue.
I checked some other woocommerce websites(people shared links in this github), it's working fine for them(e.g. https://fburl.com/694plifj ; https://fburl.com/s0fczn0l)

So it's probably there is incompatibility between our extension with something else on your website

**Comment by mawtt** [comment]
could it be incompatibility with the theme?  therefore its blocking themes structured data?  or do you think its another plug in its clashing with that is then stopping the themes schema showing?

Thanks

**Comment by mawtt** [comment]
I just checked your site, this one...
http://ec2-54-153-37-179.us-west-1.compute.amazonaws.com/product/hoodie-with-logo/

and the structured data is not actually working, just like mine. If you check that url in the structured data test that google offers, and then click preview on the product data, its not working correctly. 

if you turn off your plug in , i have a feeling your structured data would then work.

**Comment by sammul** [comment]
@mawtt but the other 2 links I sent are working right?

**Comment by mawtt** [comment]
i could not tell to be honest as the links just took me to Facebook pages i could not access. 

are you putting this url...
http://ec2-54-153-37-179.us-west-1.compute.amazonaws.com/product/hoodie-with-logo/

into this test tool....

https://search.google.com/structured-data/testing-tool/

if you can try that please, then click on the Product tab, which shows you your products structured JSON markup BUT then if you click the green button that says Preview, it will show you how your structured mark up will look in google search, and yours is not working (which i believe your plug in is breaking)

maybe try switching your plug in off after checking the above, and see if the preview then works?

**Comment by mawtt** [comment]
Hey Sammul, did you manage to see if that was happening on your site please?

**Comment by sammul** [comment]
@mawtt I realized you have LiteSpeed Cache which might cause this issue. Can you disable this and try again? Honestly we are not sure why this is happening, but we suggest you to report this to google if you know how

**Comment by mawtt** [comment]
Ok I'll try without litespeed cache. But when I turn your plug in off it all works fine. Which also means it's not really a google issue.

Plus, as I mentioned, when I checked your demo site, the structured data was not working correctly.

Can you possibly try switching off your plug in for a bit in that demo site so we can see if the structured data then works please?

Thanks

**Comment by mawtt** [comment]
ok let me test the LiteSpeed cache more, as it might be the HTML minification that is breaking it.
Thanks

**Comment by mengyingdu** [comment]
Hi @mawtt ,

I checked your site and you are on the latest 1.9.1 and pixel fires fine.
To be sincerely honest, I doubt this is a compatibility issues or bugs, but i will keep the compatibility tag here.
We have seen some js warning because of the pixel injection (eg. image html... if the warning is from our plugin). The google test tool is to test your site and product display. If you can confirm all works fine manually, that should be fine.

Thanks.

**Comment by Ram-Annamalai** [comment]
Hello Friends,

I ran a structured data test and I get a weird link on @id.....I would like to understand how to remove this and add the right info. I am not an expert so need easy steps for fix please. Any help appreciated.
Thx
Ram
![image](https://user-images.githubusercontent.com/38677325/42795765-7d345ac0-89c9-11e8-8f28-5e43e9f42893.png)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
