### ISSUE TITLE
Reconfigure from beginning

### ISSUE THREAD

**Issue by CS10-85** [facebookincubator/facebook-for-woocommerce#340]
Hi there.
Because I started using this plugin from very early days before the speed improvements were made, I'm struggling with syncing 50000 products to a facebook page.

Therefore, I want to start from scratch with it completely.

I thought I had removed it properly in advanced settings and then removed the plugin and reinstalled the very latest version 1.82, but it seems to be stuck somewhere, as when it is syncing products, the number of products left goes up and down.. which is very confusing.

Can somebody help me start again with this?

My facebook page's shop is now empty (the pixel is still there though - thats ok isn't it).
Facebook page is https://www.facebook.com/MGAutoMotorsport
Store url is https://www.mgautos.uk.com

Thanks!

**Comment by CS10-85** [comment]
I'd really appreciate somebody helping me with this.

I just want to clear completely anything that is set so I can start from scratch with the latest version.

I think it's in a bit of a state of of syncing products as soon as I enable the plug in again but there is no shop on the Facebook page.

Can anyone please help?

**Comment by sammul** [comment]
@CS10-85 from my side, I can see all the settings(setup) have been deleted. However, some product catalogs still exist. How many catalogs do you see if you go to www.facebook.com/products? Can you delete all the ones you don't want?

**Comment by CS10-85** [comment]
There are no products at all.

In fact I think I deleted the whole catalog to try and start again.

The plugin still thinks it is syncing products, but I've no idea where to!

What can I do to really clear everything and start again?

**Comment by sammul** [comment]
@CS10-85 , @dmitridr suggested you to complete the setup one more time to see if the message would disappear

**Comment by CS10-85** [comment]
Hi there.
Thanks for the reply.

I can certainly give that a try.

Do you mean re-do the setup through the plugin?

Last time I tried the other day, it didn't seem to make a difference.....

**Comment by sammul** [comment]
@CS10-85 Yes. Did you try with 1.8.2 at that time? Our previous versions had trouble with large amount of products, like yours. So it stuck somewhere during uploading the products. However, we changed the approach starting from 1.8.

**Comment by CS10-85** [comment]
@sammul 
I upgraded to the latest version yes.

I think its in a bit of a limbo state at the minute. How can it be fully reset?
Ie - no products at all in my store think they have ever been synced etc?

When I went through the setup, it linked to the page and existing pixel, and then started syncing the products, but was failing.

And if I went to alter the setup, nothing was remembered so it wanted me to run the setup again...

**Comment by sammul** [comment]
Adding @dmitridr into the thread to see if he has better suggestions.

**Comment by CS10-85** [comment]
Thank you @sammul

**Comment by CS10-85** [comment]
@dmitridr 
Can you help with this at all please?

Thank you,
Craig

**Comment by dmitridr** [comment]
Hey @CS10-85 , 

Sorry for the delay in getting back to you, we're swamped with issues that affect multiple stores. 
It sounds like the plugin is in a bad state because there's some problems with the intermediate DB state and the older version. 

I'm guessing from #374 that you've already solved this problem though and the products are uploading correctly for you. Let me close this issue then and we can follow up in that one if things are still not working for you.
