### ISSUE TITLE
ViewContent double fired

### ISSUE THREAD

**Issue by gilangramadhan** [facebookincubator/facebook-for-woocommerce#343]
Hello

Anyone have idea why the ViewContent event is double firing on single product page? 

![doubleviewcontent](https://user-images.githubusercontent.com/6247523/37866081-fd7bc69e-2fb7-11e8-9c37-fa8a1d43026e.jpg)

I'm using latest version 1.8.2.

**Comment by gilangramadhan** [comment]
@sammul please check https://hijacket.shop/shop/hj5-basic/

**Comment by sammul** [comment]
@gilangramadhan The other ViewContent is not fired by our extension. I'm not sure if you have another extension doing this though.

This piece of code is not generated by our extension:
![screen shot 2018-03-26 at 9 50 20 am](https://user-images.githubusercontent.com/4251631/37920263-3e0f3a32-30db-11e8-8468-3909855ad557.png)

**Comment by gilangramadhan** [comment]
I spotted that generated script too but can't find any other suspicious plugins. 

I tried to deactivate Facebook for Woocommerce for a moment and the double ViewContent is disappeared.

I'm confused.

**Comment by sammul** [comment]
So only ViewContent is double fired right? I tried AddToCart and it's working correctly.

**Comment by mengyingdu** [comment]
I checked it and confirmed ViewContent only fired one time now.
