### ISSUE TITLE
Pixel already installed. 

### ISSUE THREAD

**Issue by hypermaninc** [facebookincubator/facebook-for-woocommerce#344]
Hi,

The problem is that while configuration in dropdow is offered only Pixel of another Ad account, for another project.
So, at the second step I got a message - "A pixel is already installed on this site. If you continue, you will replace the existing pixel with OTHER PROJECTS NAME's Pixel."
But there is no chance to click something like skip, to not to use this Pixel instead of already installed.
How can I resolve this issue?

Thanks!

**Comment by hypermaninc** [comment]
Unfortunately, the pixel wich offered as new is not the one I need. The thing is, that in dropdown in your extension's step 3 (after choosing the page), there are only one pixel offered. And that only pixel is wrong and connected to another facebook business account.

**Comment by sammul** [comment]
@hypermaninc that happens when you don't have access to the pixel you want. Make sure you have access to the adaccount owns the pixel(if adaccount is personal) or assigned to it(if pixel is owned by business)

**Comment by hypermaninc** [comment]
@sammul Very thank you! You was right, my mistake that i was created the pixel, but didn't assignet myself to it. I fixed this and it works.
Thanks again!
