### ISSUE TITLE
All products have disappeared from Facebook after updating to 1.8.2

### ISSUE THREAD

**Issue by cmacreative** [facebookincubator/facebook-for-woocommerce#345]
How do I get my products back? they have all disappeared since I updated the plugin to 1.8.2.
Please get back to me asap,

**Comment by cmacreative** [comment]
Website url : https://goo.gl/EkHUcG

Facebook url: https://goo.gl/EyBXcT

**Comment by sammul** [comment]
@cmacreative I can see the products are in facebook shop. Seems the issue was resolved on itself?

**Comment by sammul** [comment]
@makiskotselidis please share your url and facebook page

**Comment by makiskotselidis** [comment]
Website url
[](https://mybeautyspot.gr/)
and the facebook page is
[](https://www.facebook.com/pg/mybeautyspot.gr/shop/)

@cmacreative I can not see your products either. Same issue as mine.

**Comment by mengyingdu** [comment]
Hi @makiskotselidis and @cmacreative,

We found the cause now and will fix it ASAP. The fix is only on FB side, so you don't need to upgrade or wait for new version.

Great thanks for your report!

**Comment by mengyingdu** [comment]
Hi @cmacreative and @makiskotselidis,

This has been fixed, and you can check it after a couple of hours or tomorrow. Your products in shop should come back for normal visitors.

Thanks.

**Comment by makiskotselidis** [comment]
Is an update going to be available? What action should I take on my side? Thank you for your help

Λήψη του Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by mengyingdu** [comment]
No actions needed.

**Comment by mengyingdu** [comment]
@makiskotselidis  and @cmacreative I checked that your shop can show all products now when I login as a test user.
