### ISSUE TITLE
Is it possible that plugin killed website?

### ISSUE THREAD

**Issue by hypermaninc** [facebookincubator/facebook-for-woocommerce#346]
5h ago tried to configure plugin. After little help of @sammul successfully done it and products from webstore started synhronisation

**Comment by hypermaninc** [comment]
Sorry...

So after some 10-15 min website was down - Error 500.
The thing is, that there are only 50+ products and all other websites on same server works properly.

Maybe someone had same issue before?

**Comment by sammul** [comment]
hmm, what's your url?

**Comment by hypermaninc** [comment]
amstaffcrew.eu

**Comment by sammul** [comment]
What if you disable the extension? Will the website come back?

**Comment by hypermaninc** [comment]
It’s will sounds strange, but i don’t know how ))i’m very beginner in such things.
Should i backup and just delete plugin directory?

**Comment by sammul** [comment]
Are you on latest version? If you are using an older version, the extension might exhaust memory.
If you can login to your admin panel, just go to extensions management and disable it.

**Comment by hypermaninc** [comment]
Yes, i have downloaded extension just yesterday, so i think it’s the latest one.
No, i can’t login, cause all links showing 500.

**Comment by hypermaninc** [comment]
Hi,
So the problem was in CPU of hosting, not in your extension.
Thanks for your help!
It's weird, cause it's not a cheap hosting.

**Comment by sammul** [comment]
Closing it as seems the issue was resolved itself.
