### ISSUE TITLE
Products not showing in shop

### ISSUE THREAD

**Issue by Chris-HHH** [facebookincubator/facebook-for-woocommerce#347]
Hi,

None of my products are showing in my 2 Shops.  If I look in admin they are there, if I search for a product they are there.
Set up the shops yesterday - although I have tried setting up before. Am I blacklisted or missing something?

https://www.facebook.com/pg/CotswoldGoodies/shop/
https://cotswoldgoodies.com/

https://www.facebook.com/pg/cotswoldgiftware/shop/
https://cotswoldgiftware.com/

Thanks in advance

**Comment by mengyingdu** [comment]
Hi @Chris-HHH ,

Which product you refer as 'None of my products are showing in my 2 Shops.'?
This is my view (log in as a my personal account)
![screen shot 2018-03-26 at 1 33 08 pm](https://user-images.githubusercontent.com/24535640/37931426-69d10870-30fa-11e8-9011-196cfa7ffd51.png)
![screen shot 2018-03-26 at 1 33 14 pm](https://user-images.githubusercontent.com/24535640/37931427-69f9cb20-30fa-11e8-9f00-3723968c9424.png)

**Comment by Chris-HHH** [comment]
This is my views:
What the ?? Nice you can see them, this view is from friends login (My WiFi)
![image](https://user-images.githubusercontent.com/28512934/37934088-115caee2-3145-11e8-998f-592ece2b2f81.png)
![image](https://user-images.githubusercontent.com/28512934/37934287-99da19d0-3145-11e8-8d76-4061e695a8e9.png)

**Comment by Rabiiiiiiii** [comment]
Same problem
