### ISSUE TITLE
Cannot hide product in facebook page's store from Woocommerce Product setting

### ISSUE THREAD

**Issue by gchterry** [facebookincubator/facebook-for-woocommerce#35]
my woocommerce version 3.0.8
using Facebook for WooCommerce 1.5.1
Polylang for WooCommerce 0.8
i already success sync all product with chinese version only
i want to hide product in facebook page's store, so i edit my product, untick visible in facebook menu then click update.
product still show in fb store & inside my product screen the visible still status tick

**Comment by tahoff** [comment]
@gchterry Thanks for reporting this issue! We've fixed the issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.0). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
