### ISSUE TITLE
Google Product Category Errors

### ISSUE THREAD

**Issue by FlairTrade** [facebookincubator/facebook-for-woocommerce#350]
In the past couple weeks I began seeing these Google Product Category errors in the Diagnostics of my WooCommerce catalog feed. I don't know if this is a new field that has been added to recent releases of the facebook-for-woocommerce plugin or if the field is generated by some other plugin. Any thoughts?

![google product category](https://user-images.githubusercontent.com/35601034/37971757-b83fc50a-31a4-11e8-872d-570979448419.jpg)

**Comment by coccoinomane** [comment]
I have the same issue; I have synched my catalog and the `google_product_category` field is empty, thus the warning.

A possible solution would be to code an interface where categories can be mapped, as suggested in https://github.com/facebookincubator/facebook-for-woocommerce/issues/335.

**Comment by mengyingdu** [comment]
Hi @FlairTrade ,

If you are not using google category, we fixed it in [v1.8.2](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.2).

If you are using v1.8.2, it could be related to @coccoinomane mentioned.

Thanks.

**Comment by patiohq** [comment]
I'm using version 1.8.4 and have the same issue.

**Comment by pabowles** [comment]
Having this issue on random products with 1.8.7

**Comment by zwkaarten** [comment]
I'm still facing this issue, anyone solved it?

**Comment by s0a0a0z** [comment]
Hi

I've setup following site with facebook for woocommerce shop
https://eyefashion.pk
some of my products are rejected by facebook because of the problem "google_product_category" mentioned in attachment 

![image1](https://user-images.githubusercontent.com/16450144/52791879-ce39e980-308b-11e9-9463-efb416e06264.png)

**Comment by FlairTrade** [comment]
@s0a0a0z They aren't rejected, this is just a warning or sorts. Everyone of my current 1297 items has this warning, it is very annoying, but I haven't see it impact our Facebook shop. Note the wording next to the caution triangle "Some products or properties have issues that might lower your catalog quality:" Also, notice the product count shows 41 of your products were updated or added and there are none rejected.

![image](https://user-images.githubusercontent.com/35601034/52793700-411b7400-303c-11e9-8d3c-df372d531a48.png)

**Comment by swspcodes** [comment]
Same here.... can´t even map from the data source settings inside Facebook Business Manager. I´m on 1.9.15
