### ISSUE TITLE
Fatal error: Call to undefined method WC_Facebookcommerce_Utils::is_valid_id() in...

### ISSUE THREAD

**Issue by PrestaShark** [facebookincubator/facebook-for-woocommerce#352]
Hi guys,
I have this error Fatal error: Call to undefined method WC_Facebookcommerce_Utils::is_valid_id() in (...) wp-content/plugins/facebook-pixel/facebook-for-wordpress.php on line 30

Any ideas?
Thanks

**Comment by mengyingdu** [comment]
Hi @PrestaShark ,

more context: a long time ago, this repository has two plugins, and we separated them. 

You shouldn't install or use 'facebook-pixel'. Can you install the new version [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.2)?

Thanks.
