### ISSUE TITLE
slow in saving products

### ISSUE THREAD

**Issue by emanuelepinna** [facebookincubator/facebook-for-woocommerce#353]
Hello,
after installing the plugin, every time I edit and save a product, the save takes about 30/40 seconds.
Is there any way to fix this problem?
thank you
best regards

**Comment by mengyingdu** [comment]
Hi @emanuelepinna ,

Can you follow the support section in the readme (front page of this github repository) when you open an issue? We need that information in order to help you .

Thanks.
