### ISSUE TITLE
“Get Started” just takes me straight to Facebook page 

### ISSUE THREAD

**Issue by rebelsalliance** [facebookincubator/facebook-for-woocommerce#355]
Successfully installed and activated but when I hit the “get started” button, I signed in and it took me straight to my store’s Facebook page - no changes made. I don’t get access to the follow up questions and options.

**Comment by rebelsalliance** [comment]
I do not get the option to choose a Facebook page and then the install pixel options - just immediately to the fb page on which nothing ha store happened

**Comment by mengyingdu** [comment]
Hi @rebelsalliance ,

You should set up your settings from your 'woocommerce settings' section. I uploaded the picture to help you find it. (This is what it looks like after you set up, before that, there is a 'get started' blue button)

It's in woocommerce -> settings --> integrations --> facebook for woocommerce
![screen shot 2018-03-28 at 1 42 23 pm](https://user-images.githubusercontent.com/24535640/38055301-28ac0ada-328e-11e8-8349-5b2852ec1a75.png)

Let me know if you need more help.
Thanks.

**Comment by rebelsalliance** [comment]
Hi there,

Yeah that’s exactly where I’ve been trying from, but when I click that blue button it takes me straight to the “Rebels Alliance” Facebook page and not the “choose an account” page that eventually leads to importing all my products.

**Comment by mengyingdu** [comment]
Hi @rebelsalliance,

That's so weird. Can you upload a screen record ?

Thanks.

**Comment by rebelsalliance** [comment]
Yeah I know, I’ve watched a tonne of tutorials and there’s always go straight to the “choose an account” page - mine refuses to every time and just goes straight to my fb home page - very frustrating. I will send you a screen video tomorrow, but as far as I can tell I’m doing it all right.

Thanks

**Comment by rebelsalliance** [comment]
Hi there,

Did you have any luck trying to figure this out? I’ve no idea why I can’t get it to work - very frustrating.

**Comment by mengyingdu** [comment]
Hi @rebelsalliance ,

The problem here is I can't repo or have enough information to help you. 
Can you upload a full screen video record so I can know what happened?

Thanks.

**Comment by rebelsalliance** [comment]
Hi 

Yeah it’s a really annoying situation. How to I upload a screen capture??
Really want to get this working

Thanks

**Comment by rebelsalliance** [comment]
Is there anyone else I can contact to help with this issue?

**Comment by mengyingdu** [comment]
Hi @rebelsalliance ,

You can upload screenshot or video record on github by clicking on 'select them' (blue hyper text).
![screen shot 2018-04-02 at 7 47 58 am](https://user-images.githubusercontent.com/24535640/38200729-4b1b3720-364a-11e8-8941-6226fb900df6.png)

**Comment by rebelsalliance** [comment]
![9affc599-ae4c-4334-81b9-5179b6b7cebe](https://user-images.githubusercontent.com/37865724/38236327-be118e1a-371b-11e8-9785-c5dfded554d0.png)
![19838fcc-3a68-44fe-b882-b5b81058227b](https://user-images.githubusercontent.com/37865724/38236329-be5b9f1e-371b-11e8-8b62-aae60478b760.png)
![4e0c55d8-c1b9-4f16-b0c2-07221f59d19b](https://user-images.githubusercontent.com/37865724/38236330-be93ef0e-371b-11e8-8ad0-6cc2687357bd.png)
![01f5cafc-c360-4553-9a8d-c3b017aae937](https://user-images.githubusercontent.com/37865724/38236331-bed7d0e8-371b-11e8-8d19-c6d693f90266.png)

**Comment by rebelsalliance** [comment]
I couldnt upload the video format but here’s exactly what happens in screenshots

**Comment by dmitridr** [comment]
@rebelsalliance 

Not sure if you are still having this problem but from your screenshots I can tell you it's because you're using an ipad. The problem is we do not support mobile browsers for the WooCommerce plugin at this time. If you have access to a desktop browser, please use one of those, it should work. There are several apps for using a desktop browser on mobile, or using a physical desktop/laptop should also work. Hope that helps.
