### ISSUE TITLE
Deleted products Woocommerce still showing in Facebook shop

### ISSUE THREAD

**Issue by rrowan** [facebookincubator/facebook-for-woocommerce#356]
Hello,

Deleted products (also products that are set as invisible by the way) are still uploaded to Facebook and visible in the shop section on Facebook. Products in trash also show up on Facebook. Also after resync and reset. Even if I permanently delete them and resync they're visible. This product for example has been permanently deleted from our webshop, but still shows up on Facebook: https://www.facebook.com/commerce/products/1825095387521557/

I saw someone else had a similar problem, but in his case the products would eventually disappear from Facebook when he permanently deleted them (https://github.com/facebookincubator/facebook-for-woocommerce/issues/75).

I once dodged the problem by uninstalling the plugin and reintstalling it, but I don't want to do that every time I delete a product from my shop.

I'm using WooCommerce version 3.2.6 and Facebook for WooCommerce version 1.8.1.

Please let me know what other information I need to provide in order for you to see what could be the source of this.

Thank you so much for your help!

Kind regards,
Rowan

**Comment by mengyingdu** [comment]
Hi @rrowan ,

When you delete a product, did you hit the 'update' button on product editor page?
If not, can you try it?

Thanks.

**Comment by MandyvdWalt** [comment]
Hi I am having the same issues. My plugin is 100% up-to-date as well. The products that are featured on my Facebook shop, that I can't get rid of, have been permanently deleted from my Woocommerce shop so when my visitors click to purchase this deleted item it takes them to checkout with nothing in their basket. As they're permanently deleted, I'm not sure how I can go back and do any of the other suggestions that I've read in your issues thread.

Sorry to hijack your post rrowan :) this is just flipping me off

**Comment by MandyvdWalt** [comment]
Thanks rrowan.

@mengyingdu, if the item has been permanently deleted/ removed from the Woocommerce store on your website, it is no longer in your bin so you can't do a thing. You cannot hide the item or anything because it no longer exists. How then is it that Facebook has this product. I personally have tried uninstalling the plugin, reinstalling it, resyncing it etc and am at my wits end here.

I've seen many threads with this issue and I'm pretty sure that @rrowan and I have the most updated version of this plugin.

**Comment by rrowan** [comment]
I personally delete products straight from the product summary page.

**Comment by mengyingdu** [comment]
Hi @rrowan ,

Sorry to hear your problems. We have a fix for deleted/draft products in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6). Can you try to upgrade?

You should be able to get rid of the deleted product doing a full reset of the plugin, which can be done through Reconfigure > Advanced Options > Delete, and then setting up again.

Let me know whether it works for you.

Thanks.

**Comment by mengyingdu** [comment]
Hi @MandyvdWalt ,

same advice here.

**Comment by mengyingdu** [comment]
Since we haven't got update for a long while, close this issue now. Feel free to open a new one if you still have this problem.

**Comment by sotirisa** [comment]
Hi I still have the same problem here.

All the products whisch are in trash they shown up again again. And also the products with no stock.
