### ISSUE TITLE
wp-admin stopped after activating plugin version 1.8.2

### ISSUE THREAD

**Issue by creckinger** [facebookincubator/facebook-for-woocommerce#358]
Hi,

Actually I have the same problem even after installing the latest version as you as instructed in [here](https://github.com/facebookincubator/facebook-for-woocommerce/issues/275) . I also tried with 1.7.11 and it didn't work either.

Thanks!

Plugin version: 1.8.2 and 1.7.11
Wordpress version: 4.9.4
WooCommerce version: 3.3.4
PHP version: 7.2.3

My error logs:

- ERROR | GET /wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s= HTTP/1.0
- ERROR | AH01071: Got error 'PHP message: PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function WC_Facebookcommerce_EventsTracker::__construct(), 1 passed in /var/www/vhosts/reckinger.lu/httpdocs/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 296 and exactly 2 expected in /var/www/vhosts/reckinger.lu/httpdocs/wp-content/plugins/facebook-pixel/facebook-commerce-events-tracker.php:19\nStack trace:\n#0 /var/www/vhosts/reckinger.lu/httpdocs/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(296): WC_Facebookcommerce_EventsTracker->__construct(Array)\n#1 /var/www/vhosts/reckinger.lu/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-integrations.php(39): WC_Facebookcommerce_Integration->__construct()\n#2 /var/www/vhosts/reckinger.lu/httpdocs/wp-content/plugins/woocommerce/includes/class-woocommerce.php(464): WC_Integrations->__construct()\n#3 /var/www/vhosts/reckinger.lu/httpdocs/wp-includes/class-wp-hook.php(286): WooCommerce->init('')\n#4 /var/www/vhosts/reckinger.lu/http...\n', referer: https://www.reckinger.lu/wp-admin/update.php?action=upload-plugin

**Comment by mengyingdu** [comment]
Hi @creckinger ,

You have this problem because you installed facebook-pixel. You should only use facebook-for-woocommerce. Please deactivate and delete that one in your plugin section. Then it should be fixed.

from your error message: 
exactly 2 expected in /var/www/vhosts/reckinger.lu/httpdocs/wp-content/plugins/facebook-pixel/facebook-commerce-events-tracker.php

Thanks.

**Comment by creckinger** [comment]
Perfect! Issue fixed. Thanks!
