### ISSUE TITLE
Not Synced - This product is not yet synced to Facebook.

### ISSUE THREAD

**Issue by personalgifts** [facebookincubator/facebook-for-woocommerce#359]
Hi,
I made few changes to products. I am getting message This product is not yet synced to Facebook.

How do i sync these products?

website is www.thepersonalgifts.co.uk

Thanks

**Comment by mengyingdu** [comment]
Hi @personalgifts ,

I checked our data from your site, it seems  you haven't synced products ever. Did  you follow the steps in pop up window util the last step? 

Also, your plugin version is 1.6.1 which is very old. 

Can you try 

1. delete your settings:
   woocommerce settings -> integration tab -> facebook for woocommerce -> re-config your setting
  --> advance options -> delete
2. deactivate and delete your current plugin
3. download [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.3) , upload, install and activate

Let me know if you need more help.

Thanks.

**Comment by dmitridr** [comment]
I will assume that the above advice helped. If not please open a new issue on us, also the link above is to v1.8.3 but I recommend using v1.8.7 which has even more fixes.

**Comment by webteambdc** [comment]
Hi @dmitridr , 

actually i am also facing this issue as well.
Currently my version for "facebook for woocommerce" is Version 1.9.15.
There's no re-config your setting under advance options. Can you advice me pls? 

Thank you and appreciate.
