### ISSUE TITLE
Error after update 1.8.2

### ISSUE THREAD

**Issue by PEASHasselt** [facebookincubator/facebook-for-woocommerce#360]
I'm getting an error on my website, after I did the update 1.8.2:

**Warning: Missing argument 2 for WC_Facebookcommerce_EventsTracker::__construct(), called in /home/peashass/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 296 and defined in /home/peashass/public_html/wp-content/plugins/facebook-pixel/facebook-commerce-events-tracker.php on line 19**

The error is readable on the backend of Wordpress and on the mobile version. I can't read the message on desktop (but there's a space between the menu and the beginning of the page).

My website is [www.peashasselt.be](url)
I'm using version 4.9.4 of Wordpress with Organic (as a DIVI child theme).

I had this error before, I think that it had something to do with the pixels I installed on my website.
I removed all unnecessary pixels and the error went away.
Just to pop up after I updated WooCommerce.

**Comment by mengyingdu** [comment]
Hi @PEASHasselt ,

What's the previous version you have used ?

You shouldn't use other pixel related plugin, eg facebook-pixel.
You can check this on your wordpress-> plugins page.

Thanks.

**Comment by PEASHasselt** [comment]
Oh, that was it :). Great! Thanks a lot.
