### ISSUE TITLE
"Your Shop Is Being Processed"

### ISSUE THREAD

**Issue by knightofn1** [facebookincubator/facebook-for-woocommerce#361]
hey my shop has been being processed for days now and i wanted to see if anyone here could help me. i had the plugin for a long time and then it somehow became unsynced with my FB business page and i didn't have the option to force a resync, only the option to start all over so i did that the other day and it's still not up

plz halp

web: liveinexcess.com
business page: facebook.com/xsaccessories

**Comment by mengyingdu** [comment]
Hi @knightofn1,

I checked our fb page and store, your shop has some failure after review. I confirmed that your catalog has synced many products. 

I combined your problem with @NicoleParberry in #357 together to shop review group. I will update here once i get back some feedback.

Thanks.

**Comment by knightofn1** [comment]
thanks sooooo much!!

**Comment by jieminz22** [comment]
Hi @knightofn1,

You shop is alive now!
