### ISSUE TITLE
Facebook extension error : Woocommerce #333

### ISSUE THREAD

**Issue by mybluepink** [facebookincubator/facebook-for-woocommerce#362]
Hi **My issue#333 was closed but I need more info. on it. Please help after going through the case as under.**
Hi
I am getting the below-mentioned error and as in screenshot while I try to syn products with my facebook page.
![error](https://user-images.githubusercontent.com/37506089/38145818-d69c943a-3468-11e8-8580-5aaa48e42763.JPG)

 I changed the password a few days back. I tried installing the plugin again by deleting the previous one but it didn't work.
Facebook extension error: Facebook for WooCommerce
Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.

I was given this solution by @dmitridr 
_If you go to the configuration page for the plugin (in the WooCommerce tab under Integration), you should see instructions about how to proceed, there's two ways.

(1) Launch the plugin config via Reconfigure then go to Advanced Options and hit Update Token
(2) Reset the plugin entirely by going to Reconfigure then going to Advanced Options and hit Delete. Then complete set up again.

I recommend doing (1) as it will not affect your existing shop or ads._

Hello,
I tried doing the (1) but I don't see any Update token button in Advanced Options. Please check screenshot and suggest accordingly.
![error1](https://user-images.githubusercontent.com/37506089/38145862-03c03a98-3469-11e8-8497-db851780bade.JPG)

Please help me resolve the issue. 
Thanks in Advance

**Comment by jieminz22** [comment]
Hi @mybluepink,

Can you try option (2) instead?

**Comment by abismonlo1** [comment]
@mybluepink 
put the previous password on my facebook and everything was solved

**Comment by mengyingdu** [comment]
Hi @mybluepink ,

I think option 2 can solve your problem here. Otherwise, you can try the suggestion from @abismonlo1 

Thanks.
