### ISSUE TITLE
Multilingual site problem (WPML) : Wrong URLs

### ISSUE THREAD

**Issue by kalinin1213** [facebookincubator/facebook-for-woocommerce#367]
Hello,
We use WPML to run the site in 3 languages and I'd like to synchronize all products in all languages with FB catalog.

Facebook-for-woocommerce does create all the products in different languages in the catalog, but product details are mixed up

for example here is the same SKU in three languages https://snag.gy/A46XMr.jpg
english is fine
German has wrong link https://snag.gy/8Fpn2o.jpg
Russian has wrong link  https://snag.gy/12bONh.jpg

Seems that plugin generates the link instead of taking it from SKU settings. Otherwise I can't understand why the url is half right, half wrong. http://olga-grinyuk.ch/платья/.....7?attribute_pa_size=44-ru - this part is correct for russian, but the slug is taken from english SKU (geneva-office-dress-knee-length-blue)

correct Russian url should be https://olga-grinyuk.ch/ru/%D0%BF%D0%BB%D0%B0%D1%82%D1%8C%D1%8F/%D0%BF%D0%BB%D0%B0%D1%82%D1%8C%D0%B5-%D0%B6%D0%B5%D0%BD%D0%B5%D0%B2%D0%B0/?attribute_pa_size=42-ru

___________________
other example
 the same SKU in 3 languages https://snag.gy/tEkRAY.jpg

English has wrong url https://snag.gy/BHsPVZ.jpg full url is incorrect, it lead to Russian SKU
German has wrong url https://snag.gy/ZiTcws.jpg . the slug is incorrect
Russian has correct url https://snag.gy/TGOq2p.jpg

________________
separate issue is that Brand is taken in english across all variants so impossible to filter by language...

_____________________
all those issues makes the catalog very difficult to use for DPA :/ 

please help to fix or advise how to clean away all the product from the catalog so I import them via separate manual feeds for each language

thank you!

**Comment by jieminz22** [comment]
Hi @kalinin1213,

Sorry we don't have full support for WPML, and you can check the description and functionality [here](https://github.com/facebookincubator/facebook-for-woocommerce/commit/c7f1393e1584219e6e387d26f4dae2c9eb6e4967).

We had similar issues reported due to WPML before (https://github.com/facebookincubator/facebook-for-woocommerce/issues/295). 

Please take a look and understand our level of support for WPDL first and check with your site. Thanks!

**Comment by kalinin1213** [comment]
Thank you for the explanation 

Is there a way to remove the catalog created by Facebook-for-woocommerce, but keep using the pixel? I'd then create catalog via manual product feed compatible with WPML

**Comment by kalinin1213** [comment]
Hi @jieminz22 ,
is there a plan to solve WPML compatibility issue? 
that would be a huge improvement for numerous miltilingual sites. 

thanks!

**Comment by dmitridr** [comment]
No plan yet, but thank you for flagging this, we do have fairly poor multilingual support at the moment. If you (or anyone reading this) has a WPML fix for the wrong product urls, please feel free to send us a pull request to solve this. We'd be more than happy to review.

**Comment by kalinin1213** [comment]
Hi @mengyingdu ,
thank you for handling this issue

I did the following, but unfortunately it made no difference
1. I upgraded to the new version 
2.  then i cleared website cache and browser cache.
3. chose russian in WMPL settings https://snag.gy/MeqcT7.jpg 
4. then i did forced Resync

Results: 
1. I still see products in all languages in the catalog https://snag.gy/BRHrsj.jpg (which is actually not a problem, but seems WPML language setting made no difference)
2. product details in Russian are not correct. Website links are wrong. Somehow URL has English product slug https://snag.gy/VTsckS.jpg and miss "RU" in the URL

see here the correct URL of that product  https://snag.gy/g5NtP1.jpg

3. I can't use Russian products for Dynamic Products Ads because they lead to non-existing URLs and users see error 404 :(

Could you please help to fix the issue with URLs of the secondary languages? (German products also recorded with a wrong product slug...)

thanks in advance!

**Comment by dmitridr** [comment]
Let's keep this open to fix the URL issue. Will update when we have a chance to fix it. Thanks for your patience!

**Comment by dmitridr** [comment]
Also just a clarification : all languages are still synced to FB, and will show up in the catalog. This provides the added benefit that all users who see your products on all languages of your site may still be added to a custom audience (and used for ads) based on your pixel.

We can add a more advanced feature later to not sync these products at all, but these can still be separated into product sets and advertised separately, so it should not be a significant issue that they are all in the same catalog, unless I'm missing something...?

The added WPML setting controls shops visibility only, for now.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
