### ISSUE TITLE
incompatibility with WPML: Issues using the plugin on my site

### ISSUE THREAD

**Issue by spradooooo** [facebookincubator/facebook-for-woocommerce#368]
Hello,

I am trying to use the plugin with my woocommerce site but I am having a lot of issues hope you can help me with it.

When I installed the plugin and tried to use it for the first time after going through the steps and started to upload the products it gives an error saying something went wrong uploading the products please try again.
So I force resync and it starts to upload the products fine to the shop.
then I tried to hide the default language products on the shop and only use the second language products but it keeps displaying them and never hides them.
So I tried to delete the product on FB from the product editing page but never helps.

I deleted the shop and went through the process again and the same behavior happens.

Also I get this error on the product listing page:

> Facebook for WooCommerce
> One or more of your products is using a checkout URL that may be different than your shop checkout URL. Re-sync your products to update checkout URLs on Facebook.

- and when I visit the product from the shop and click to checkout on website, the product name change to "cart", it really becomes "cart" on the site and I don't know why this is happening.

Last thing is when I click to checkout for one product, it takes me to the default language cart page.

What I would like to do with the plugin is to only display the products in the second language and maybe get the chance to sync what I want before uploading everything in the beginning, because it takes very long time to sync the 2 languages products.

Site details:
Site: https://www.cabreet.com/
FB Page: https://www.facebook.com/cabreet/

My setup is:
Wordpress: 4.9.4
Woocommerce: 3.3.4
FB for woocommerce: 1.8.2
WPML: latest version not sure of the number but I keep it up-to-date

I hope you assist me with these things, and I would like to thank you for giving us this plugin in the first place.

Best regards

![screen shot 2018-04-01 at 10 35 16 pm](https://user-images.githubusercontent.com/16766564/38177194-46108cbe-35fd-11e8-9623-3c7f4a9b9df6.png)
![screen shot 2018-04-01 at 10 35 30 pm](https://user-images.githubusercontent.com/16766564/38177195-462d7f68-35fd-11e8-82a3-8199ecf10b9c.png)
![screen shot 2018-04-01 at 10 35 48 pm](https://user-images.githubusercontent.com/16766564/38177196-46486184-35fd-11e8-9199-cb39d8c2ae97.png)

**Comment by jieminz22** [comment]
Hi @spradooooo,
 
Sorry we don't have full support for WPML, and you can check the description and functionality [here](https://github.com/facebookincubator/facebook-for-woocommerce/commit/c7f1393e1584219e6e387d26f4dae2c9eb6e4967).

We had similar issues reported due to WPML before (#295).

Please take a look and understand our level of support for WPDL first and check with your site. Thanks!

**Comment by dmitridr** [comment]
Hi all,

What sort of WPML features would you like to see? As you saw we did have a recent change to hide products in the non-default language.

Some thoughts about how to fully address this:
(1) We could potentially add an option into WPML settings itself to select language for FB. (Cleaner)
(2) We could add an advanced section in the settings page of this plugin to select language for WPML. (Easier?)

If you want you can also hack the plugin directly and select the desired language by changing the code [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.8.5/includes/fbproduct.php#L468) to set `$this->default_lang` to your desired default language, then `Force Resync` afterwards. That will work in the meantime as a workaround while we work on developing full support.

**Comment by spradooooo** [comment]
Hi dmitridr,

I would prefer the second option to stay clear of WPML settings and control it within the plugin settings.

The features I am looking for are:
1- No products get synced by default.
2- The ability to select the products I want to sync, individually or bulk.

This will save time and effort because the moment you install the plugin it starts to sync everything and you have to wait and then go back to remove all the products one by one.

Can you please tell me what to write instead in the code $this->default_lang because it is not clear what I should do.
for example if I want to choose arabic instead of default english, what should I write?


Thank you very much.

**Comment by mengyingdu** [comment]
Hi @spradooooo ,

We supported WPML in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6) by adding a language selector. To take advantage of this feature you need to upgrade to the latest version and do a full reset or Force Resync as it seems you have done. Please clear your browser cache after upgrade.

If you like **Facebook-for-WooCommerce**  please leave us a [*****](https://woocommerce.com/products/facebook/) rating. A huge thanks in advance!

Thanks.

**Comment by spradooooo** [comment]
Hi mengyingdu,

Thank you very much for this, it works great.

for anyone who gonna use it before force syncing go to the WPML -> language -> Facebook Visibility then choose the desired language then save.

Best regards
