### ISSUE TITLE
Avoid feeding Out of Stock products

### ISSUE THREAD

**Issue by dabodude** [facebookincubator/facebook-for-woocommerce#37]
Hello! Would it be possible to avoid including out of stock products in the sync?

We have seasonal products that once they're out of stock, will never be in stock again but we still need to have them in our catalog for historic data.

**Comment by dmitridr** [comment]
Hi,

If you mark your product as out of stock, it should be marked as out of stock within the shop, and it will not be visible in ads at all. However, it seems the product is still displayed in the shop listing page...

If you have products that you know you will never want to sync to FB again and you don't want them to display in this page, there's a workaround you can do by marking these products as not visible on the products page here:
![visiblesample](https://user-images.githubusercontent.com/29133800/30460718-6cfeff5e-996d-11e7-8797-f59a60633ba2.png)

I don't think we can build a feature where out of stock products are automatically removed from the sync. However, we could potentially auto-mark the product as 'invisible' (won't appear in the shop) if it's out of stock and provide a setting to control this, if that will address your case. In the meantime, you do have the above workaround.

**Comment by dabodude** [comment]
Yep! That will do it :) Thanks!

**Comment by dmitridr** [comment]
@dabodude FYI : There's a known issue with the Visible setting in #35.  We're working on a fix and you may or may not have this issue depending on your version. But you can still use the 'Delete product(s) on Facebook' option if you don't want to wait until the fix is ready.

**Comment by marcelbootin** [comment]
I've just started using Facebook for Woocommerce and have come across the issue with out of stock products being visible in the catalog.  Please add the 'auto-mark' product as invisible feature!

It would also be great if you could include/exclude categories to the feed.

**Comment by dmitridr** [comment]
@marcelbootin Please file a separate issue for that! We can mark it as a feature request and keep track of demand for that feature. I think someone has already requested the 2nd feature (categories) as well and filed an issue.
