### ISSUE TITLE
++++ Message error with pixel can't match Products ++++

### ISSUE THREAD

**Issue by jerome2612** [facebookincubator/facebook-for-woocommerce#371]
Please have a look on the screeshot this problem happens and make all wrong my campaign facebook 
I really no understand from where it comes and is very anoying 
my web site ====> https://astuphone.com/

looking forward

![capture d ecran 2018-04-03 a 11 04 27](https://user-images.githubusercontent.com/33776849/38227071-ffa07626-372e-11e8-9378-e13bed4a5f0b.png)

**Comment by jieminz22** [comment]
Hi,

I checked your catalog it does have your products. Can you please try resync your products to see if it will help? Let us know if the problem persists.

**Comment by jerome2612** [comment]
@jieminz22 hello there it changes nothings absolutly nothing 
looking forward

**Comment by jerome2612** [comment]
@jieminz22 is it possible to get a proper answer and solution this problems happens also and sites from friends so i think is really AGAIN a bug

**Comment by jieminz22** [comment]
Hi @jerome2612,

Did resync your product not solve your problem? You may want to try a full reset, using Reconfigure > advanced options > delete then complete setup with our latest version. Does the problem still occur?

**Comment by jerome2612** [comment]
@jieminz22 yes already install and re install couple of times nothing changes the error appears again and again and specicfly ONLY variable product that is really annoying I have to stop all my FB campaign because all the advertise result are wrong no possible to RE target

**Comment by dmitridr** [comment]
Hi @jerome2612 we should have fixed this in the latest version [v1.8.5](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.5). Installing the new version and doing a force resync should fix the problem. If it doesn't please open a new issue on us!

**Comment by eylulgormus** [comment]
I have tried everything suggested here with no avail. Could you *please* offer a proper support? This is an ongoing bug.
