### ISSUE TITLE
Installing a certain pixel and ending up with another

### ISSUE THREAD

**Issue by MiladyWanna** [facebookincubator/facebook-for-woocommerce#375]
Hello.
I hope you can help me with this one.
So, if I download the plugin for a pixel ending in ...123 and install it to a Wordpress site, it shows me a totally different pixel installed endind in ...456.
The verification is done by Pixel helper.
I must say that i have no other plugin to help with installing the pixel such as Pixelyoursite etc and it is not manually installed either.
Please share some of your insight.
Thank you.

**Comment by MiladyWanna** [comment]
hello and thank you for your prompt response.
i managed to solve that one, but there is another issue i came about.
so i am trying to install the plugin with the same pixel on 2 different
sites.
they are similar as niches so i figured that i can use the info from one to
grow the other.
it seems though that is not something that i can achieve because as i
installed the plugin on the second site, all my running ads that i have for
the first site stopped spending.
i also tried using pixelyoursite for one site and  Facebook for WooCommerce
for the other.
the truth is that as soon as i remove the pixel from the second site it
starts spending again.
have you any insight on the matter?
it would be highly appreciated.
thank you for your time.

**Comment by dmitridr** [comment]
Hi @MiladyWanna 

We landed [a fix](https://github.com/facebookincubator/facebook-for-woocommerce/commit/79c116b0080577b44a544e501a04d9f2d3413112) for the AddToCart issue just the other day, so we should have a new version out soon, v1.8.4, which will fix it. (It's the same problem from #219 probably).

cc @mengyingdu maybe we should we send out a new version ASAP with the fix?

**Comment by MiladyWanna** [comment]
ok, waiting forward to it.
thank you and great job!

**Comment by dmitridr** [comment]
We have the new version ready. 
Please [try upgrading to it](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.4) and see if it solves the issue for you. You may have to clear the browser cache (Shift + F5 on Chrome).

**Comment by MiladyWanna** [comment]
it works perfectly now.
thank you so much!
