### ISSUE TITLE
woocommerce variations not pulling through to facebook

### ISSUE THREAD

**Issue by zanderwk1** [facebookincubator/facebook-for-woocommerce#376]
Hi, I've recently set up the facebook for woocommerce extension on wordpress

And my issue is: 
1. Its pulling all of my products through however its not pulling all of my variations through. 

I've forced a resynced a couple of time (left the window open to finish) and I have also done a complete re-setup of the integrations (did not change it)

You can see the facebook shop items here with no variations:
1.Facebook shop [fb shop product 1](https://www.facebook.com/commerce/products/1965437050146831/) (product is still waiting for verification again)
1.1 woocommerce shop:[shop product 1]( https://momsaidyes.co.za/product/wooden-teethers/)

2. Facebook shop [fb shop product 2](https://www.facebook.com/commerce/products/1811942968873547/) (product is still waiting for verification again)
2.1 woocommerce shop: [shop product 2](https://momsaidyes.co.za/product/bandana-bib/

)

**Comment by jieminz22** [comment]
Hi @zanderwk1,

I can't open your shop link. Which version of the plugin are you using?

**Comment by dmitridr** [comment]
Closing as there hasn't been a reply in a while. 

Please try our latest version, v1.8.7 and do a full reset (`Reconfigure > Advanced Options > Delete`) to enable the new product sync method. Hopefully your variants will all sync correctly. If not, please file a new issue on us.

**Comment by Kae07** [comment]
Im having the same issue as this but I have opened up a new issue, if someone has any advise or can help as soon as possible it would begreatly appreciated!
