### ISSUE TITLE
HTML comment syntax in JS causing issue with code optimizer 

### ISSUE THREAD

**Issue by MrBlank** [facebookincubator/facebook-for-woocommerce#377]
I was having trouble with a comment in the script being added to the <head> of my page: `<!-- End Support AJAX add to cart</script>` not having a closing comment tag. This was causing Google to silently stop reading all my JSON-LD schema after. I isolated the conflict to the Autoptomize plugin's HTML compression. You can see my comment on this issue.

https://github.com/facebookincubator/facebook-for-woocommerce/issues/336#issuecomment-378742141

I reached out to the dev of Autoptimize and he was able to replicate but also mentioned that the Facebook to Woo plugin script was using HTML comment syntax in JS, which is similar to an old practice of hiding JS from older browsers. This seems to be the root of the conflict.

https://wordpress.org/support/topic/html-optimization-removes-closing-comment-tag-in-js/#post-10150226

I wanted to bring this to your attention since it caused me a lot of time debugging a silent scripting error with Structured Data. :-) It might a good idea to change any `<!--` HTML comments to `/*` JS comment syntax. This may also fix problems with other code optimizers. 

Thanks!

**Comment by jieminz22** [comment]
Hi @MrBlank,

Thank you so much for informing us. We will include this fix in our next version.

**Comment by mengyingdu** [comment]
Hi @MrBlank ,

We have a fix for this and will be in next release.

Thank you!
