### ISSUE TITLE
"Check Out on Website" to go to the product page

### ISSUE THREAD

**Issue by PaulLonghurst** [facebookincubator/facebook-for-woocommerce#378]
Hi All,

The "Check Out on Website" button in Facebook adds the product to the cart and shows the cart. We want it to go to the product description page. 

If it can't be changed, We want to change the wording on the button to "Add to Card" or similar.

Are these configurable?

Thank you.

**Comment by PaulLonghurst** [comment]
Found it - D'oH!

**Comment by spradooooo** [comment]
Hi PaulLonghurst,

How did you fix that? can you let me know please

Kind regards

**Comment by PaulLonghurst** [comment]
HI spradooooo,

It was a Facebook setting in the shop. Go to https://www.facebook.com/**YourFBShopNameHere**/settings/?tab=shop and it's the "Use Checkout Urls" option.

**Comment by spradooooo** [comment]
Hi PaulLonghurst,

Thank you very much, that was easy to find.

Best regards
