### ISSUE TITLE
[bug?]v1.8.4 facebook Feed :Goods lack information: google_product_category

### ISSUE THREAD

**Issue by dean224** [facebookincubator/facebook-for-woocommerce#382]
google_product_category is missed!

![11](https://user-images.githubusercontent.com/9065450/38464403-13410c3a-3b40-11e8-9c52-d8452f730536.png)

fb page: https://www.facebook.com/novodress

is it a bug?

**Comment by jerome2612** [comment]
I follow this @dean224 same report

**Comment by sammul** [comment]
The column is optional and woocommerce doesn't have this supported. So that's fine.

**Comment by dean224** [comment]
@sammul  so,Where can I configure these optional options?I can not find it?
