### ISSUE TITLE
Plugin not parsing og:description for descriptions

### ISSUE THREAD

**Issue by aand01** [facebookincubator/facebook-for-woocommerce#385]
I've noticed that the plugin seemingly ignores the og:description metadata, and instead pulls in whatever is present in the full description field. Please read the og:description field instead (or optionally)

**Comment by sammul** [comment]
@aand01 It's my first time hearing about og:description, is it from another plug-in you are using? Can you describe more? We do use full description field.

**Comment by aand01** [comment]
Hi @sammul, thanks for chiming in! I've emailed you a private example, but in general, it seems like you might be scraping the raw data from the description field, rather than parse the "description" or "og:description" metadata fields on publishing?

**Comment by dmitridr** [comment]
Hey,

I'm following up on some older issues. 
Is this still occurring for you in [newer versions](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest)?
