### ISSUE TITLE
Duplicate Cart Content : Astra Theme

### ISSUE THREAD

**Issue by dvrcthewrld** [facebookincubator/facebook-for-woocommerce#387]
With this plugin activated and the Astra theme, the cart area is duplicated on the cart page.

**Comment by sammul** [comment]
Can you share a url?
Do you mean when our plug-in is off, everything is fine; when it's on, the cart page is duplicated?

**Comment by dvrcthewrld** [comment]
That's exactly right.
catholictshirtclub.com/cart/
The staging site has the plugin activated, and you can see the duplicated cart:
https://app-5ab82ae2f911c81630875a6f.closte.com/cart/

**Comment by sammul** [comment]
@dvrcthewrld I don't see duplicate...
![screen shot 2018-04-09 at 11 59 39 am](https://user-images.githubusercontent.com/4251631/38517032-85386394-3bed-11e8-82cf-700b016f0fc2.png)

**Comment by dvrcthewrld** [comment]
Sorry. It's necessary to actually have an item in the cart.

**Comment by dvrcthewrld** [comment]
I'm using the popular Astra theme.

**Comment by mengyingdu** [comment]
I checked your site, it seems fixed. Did you change your theme or figure out it yourself? It's great.
![screen shot 2018-06-30 at 2 54 10 pm](https://user-images.githubusercontent.com/24535640/42129277-7d269ed2-7c75-11e8-97e1-a426b9c94707.png)

**Comment by dvrcthewrld** [comment]
One of your releases a while back resolved it.
