### ISSUE TITLE
Products not syncing - duplicate products showing with incorrect pricing

### ISSUE THREAD

**Issue by MelD78** [facebookincubator/facebook-for-woocommerce#388]
I have some issues with the plugin

It's not syncing properly and it's also creating duplicate products in the shop with incorrect pricing. I have updated to version 1.8.4 this morning as instructed, forced product resync and deleted the settings so restarting the process.  I shall advise if the issue continues once the products are fetched and uploaded to the store.

@dmitridr

**Comment by sammul** [comment]
@dmitridr Seems @MelD78 followed your suggestions but it's still not working. Original discussion here: #380 

Also currently there are couple similar reports: #396 #389

**Comment by dmitridr** [comment]
Hello again,

@MelD78 Thanks for creating a new issue, helps us organize. 

Could you link to a product on your site that has this problem? Linking to it in the shop will also work. Could you also provide a screenshot of the price settings for the product, and if there is anything unique about the product (for example, is it some custom type?) we would like to know that as well. 

@Lovelychoses I'd like to ask you the same request as above as well. It will help us try and get to the bottom of the cause here.

The prices can definitely be off for bookable products, we have had issues like this in the past, because these types have dynamic pricing based on time-ranges (not supported by FB).

Thanks all, for your patience.

**Comment by dmitridr** [comment]
For the issue of 'not syncing properly' could you elaborate more? Is there more problems beyond the price/duplication stuff?

**Comment by MelD78** [comment]
here is the link to the product on my website, it's a regular product, nothing custom, no variants:
https://embalmskincare.com.au/products/uplifting-cleanser

This is the link to the product in my Facebook shop with correct price:
https://www.facebook.com/commerce/products/1674478889279978/

This is the link of the duplicate product with incorrect price
https://www.facebook.com/commerce/products/1704850302927820/

Regarding your question: "For the issue of 'not syncing properly' could you elaborate more? Are there more problems beyond the price/duplication stuff?"

No, that's the only issue at present. Looks like there is only one duplicate product at the moment but the majority of prices of the product in the Facebook shop are incorrect.

Screenshot of price settings attached.
![price settings](https://user-images.githubusercontent.com/38145904/38765094-8a3cf796-3ffe-11e8-81cd-0073fcb6cf89.PNG)

**Comment by MelD78** [comment]
Here is a screenshot of my Facebook shop. The lip balm for example should be $9.95 but shows as $55  

![screenshot](https://user-images.githubusercontent.com/38145904/39110482-a08b9dfa-4714-11e8-8b09-8c1276f1b604.PNG)

**Comment by mengyingdu** [comment]
Hi @MelD78 ,

Sorry for the delay response, I'm looking at this issue now.
Thanks.

**Comment by MelD78** [comment]
Hi @mengyingdu 

Wow, I'm so glad I finally know what's causing the issue. Let me quickly disable the plugin and to a re-sync.

**Comment by MelD78** [comment]
Hi @mengyingdu,

Unfortunately, no luck. At least with the two plugins I thought were related the the multi-currency.

Here is a screenshot of all the plugins I have active. Are you able to take a look at advise which others I could cause the issue?

![plugins 1](https://user-images.githubusercontent.com/38145904/39161214-fc145812-47b2-11e8-91ca-321e9fff9f5e.PNG)
![plugins 2](https://user-images.githubusercontent.com/38145904/39161215-fc6db13c-47b2-11e8-8d74-8af450432d0e.PNG)
![plugins 3](https://user-images.githubusercontent.com/38145904/39161216-fca20d2e-47b2-11e8-9c23-4ddda91eb150.PNG)
![plugins 4](https://user-images.githubusercontent.com/38145904/39161217-fcfbf24e-47b2-11e8-8737-b77c0dc28eae.PNG)
![plugins 5](https://user-images.githubusercontent.com/38145904/39161219-fd5183ee-47b2-11e8-9468-5e0b4aa276c7.PNG)

**Comment by MelD78** [comment]
@mengyingdu 

Just deleted the settings within the facebook for woocommerce plugin again and also re-done the same things over and over again but the prices show still as incorrect.

**Comment by mengyingdu** [comment]
Unfortunately, I can't repo your issue. And I have checked our log but haven't found potential hints for your issues. 
Would you mind find your local log and paste here? @MelD78

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
