### ISSUE TITLE
Synch Issues : Bundled and Composite products

### ISSUE THREAD

**Issue by mkaulback** [facebookincubator/facebook-for-woocommerce#389]
Hi,

I have version 1.8.4 installed. I am having issues getting products to synch. I have deleted, uninstalled/reinstalled plugin, tried force resync and I can only get the same four products to sync - I have 103 total products. I do not need all 103 products to sync, only need about 9. I have tried to simply "update" the products I want to sync but they do not resync to FB. I have verified that I can "update" a simple or variable product and it will sync, but it does not do the same for bundled or composite products.

**Comment by sammul** [comment]
Seems similar issue with #388 

Can you give us your url, facebook page and catalog id? Thanks

**Comment by mkaulback** [comment]
url is thecoloradocookiecompany.com
FB page is https://www.facebook.com/thecoloradocookiecompany/
Catalog #: 204933640103317

**Comment by dmitridr** [comment]
Hey,

I checked our logs, I see 15 Simple + Variants being uploaded with 4 parent products. 
We have known issues for bundled products which are not officially supported, detailed here : #100 #132 
For composite products, I have honestly not heard of those before, is this from a specific extension? Most likely, we do not have correct compatibility with whatever extension is providing these products.

**Comment by mengyingdu** [comment]
Hi @mkaulback ,

We will have basic support for bundle products in next release. 
Bundle products can be synced, pixel events can be fired (view content, add to cart, initiate checkout , etc) However, we have issues if you disable 'redirect to cart after successful adding products' in your settings. (only if a bundle product which includes a variable product in this case, we can't get value from cart if we fire addToCart from ajax click, ALL other events work correctly.)

I would suggest you enable to redirect to cart directly in you woo settings.

Thanks.

**Comment by mengyingdu** [comment]
Hi @mkaulback,

We added basic support for bundle products extension in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6)

Thanks.
