### ISSUE TITLE
My product variation showing the slug (Variation not showed properly)

### ISSUE THREAD

**Issue by ecommerce1st** [facebookincubator/facebook-for-woocommerce#39]
I have a problem, my product variation showing the slug.

Cause I use a multi-language website.

Example Boots pink colour size 9, it showing the size as "9-en"

I just wan to see what i wrote in variation not the slyg.

Somebody can help me on this.

Regards,

Sylvain D. Desjardins

**Comment by dmitridr** [comment]
Hello,

Could you tell us the version you are using?
We should have fixed this issue in the [latest release](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.0) last week of v1.6.0. If you are not using that one, please try upgrading and force resync, it should fix the problem.

**Comment by ecommerce1st** [comment]
Ok I update the plugin, and force resync and the problems is there again.

THe link of the original product: https://pfworkwear.com/product/womens-waterproof-safety-work-boots/

And the facebook shop: https://www.facebook.com/pg/pfworkwear/shop/

**Comment by tahoff** [comment]
@ecommerce1st Are all the products which show the slug instead of the attribute using a radio button selector instead of a drop down? Do you use a specific extension to add this functionality?

**Comment by ecommerce1st** [comment]
Radio button with the plugin "WooCommerce Variation Swatches and Photos" (Buy on Woocommerce website) Developped by Lucas Stark

**Comment by tahoff** [comment]
@ecommerce1st Can you try disabling that other extension and clicking 'Force Resync'. This may resolve the issue in the near-term before we can add support for that extension.

**Comment by tahoff** [comment]
@ecommerce1st After looking at the products in your shop, only the following ones have issues:
- https://www.facebook.com/commerce/products/1555012267890728/
- https://www.facebook.com/commerce/products/1616828408389451/
- https://www.facebook.com/commerce/products/1437238006365118/

Can you go the WooCommerce product page for those products, and try clicking 'Delete product(s) on Facebook' and see if that resolves the issue? Please let us know if that resolves the issue.

**Comment by dmitridr** [comment]
Closing this issue, please re-open if the steps listed by @tahoff didn't work.

**Comment by swagat88** [comment]
Hello,
This issue is happening again after WooCommerce 3.5 update.
I sync my inventory and it is showing Attribute slug on facebook shop, insteal of Attribute Name.
Woo Commerce - 3.5
Wordpress - 4.9.8
facebook-for-woocommerce plugin - 1.9.5
e.g 
https://www.facebook.com/commerce/products/2688987981127096/
