### ISSUE TITLE
<<facebook report catalog  default_product is not valid >>

### ISSUE THREAD

**Issue by jerome2612** [facebookincubator/facebook-for-woocommerce#394]
![capture d ecran 2018-04-10 a 19 04 11](https://user-images.githubusercontent.com/33776849/38553646-74db10f4-3cf2-11e8-836d-be0d6ca5a88d.png)
site : https://astuphone
plus problem with pixel view content with a triangle orange 
![capture d ecran 2018-04-10 a 19 08 45](https://user-images.githubusercontent.com/33776849/38553721-aa5bbe04-3cf2-11e8-95a3-4554258fe68f.png)
this triangle appear ONLY on pages with variable product I have other website with oldest version facebook for woocommerce and all fine
so please give me a link where I can dowload oldest version
Already re sinc re ininstall several time all the plu in nothing change
@mengyingdu 
or other member of the team 
looking forward

**Comment by sammul** [comment]
You can find the older version here: https://github.com/facebookincubator/facebook-for-woocommerce/releases?after=v1.6.3

@mengyingdu Is this product sync issue?

**Comment by dmitridr** [comment]
Hello. A couple of points:

(1) This warning about default product is harmless. But actually it should not even appear. @mengyingdu you added this feature recently, do you think we can remove the warning display from feed enforcement?
(2) The `ViewContent` not matching products is more concerning. 

Please let us know if using an older version helps, particularly with (2), this will help us fix the problem.

**Comment by mengyingdu** [comment]
Hi @jerome2612,

As @dmitridr explained, this warning is harmless. I will remove the warning soon.

More context about this column:
Since we supported variable product in fb side, if you set a default value for variant, the default one will be the representative as this group to display in your fb shop section.

Thanks for flagging this.

**Comment by jerome2612** [comment]
Hello @dmitridr thank you for your quick reply and explanations I think I need more a release beginning of 2018 with the purchase action bug fix I will try with the 1.6.2 but i remember there is a bug about purchase action report 
I will try 1.6.2 if that fix the view content problem
thank you

**Comment by FlairTrade** [comment]
Until I just updated to the latest 1.8.4 release this morning the default product @mengyingdu had added was just constantly showing as a warning but now I'm getting a rejection error and all new items that have been added to my website aren't loading to my catalog.

https://www.flairtradeconsign.com/shop/
https://www.facebook.com/flairtradeconsign/shop/

![rejected](https://user-images.githubusercontent.com/35601034/38731756-a542646a-3ee9-11e8-9e96-6f3f711d536b.png)

**Comment by dmitridr** [comment]
We're aware of this, it's a FB-wide error not related to the plugin itself. #404 tracks the progress.

**Comment by dmitridr** [comment]
Thanks all for your patience. Both the warning and the error for `default_product` should be gone now.
If you encountered this error, please try a `Force Resync` to ensure that it is working.

For the ViewContent event, there are multiple reports on this, and we have debugged it and know the cause, it affects all variable products currently. #405 tracks the issue, you can expect a fix in v1.8.5.

**Comment by dmitridr** [comment]
[v1.8.5](https://github.com/facebookincubator/facebook-for-woocommerce/releases) is out, the ViewContent problem is fixed in that version if you update and do a `Force Resync`.
