### ISSUE TITLE
Purchase Pixel Not Appearing in domain.com/checkout/order-received

### ISSUE THREAD

**Issue by leinadnat** [facebookincubator/facebook-for-woocommerce#395]
How to fixed this? Using the latest Facebook for Woocommerce Plugin 1.8.4
When i manually browse to order-received page, i don't see the purchase pixel fire (using chrome's pixel helper)
My store received a complete order today but i'm not seeing any purchase conversion in my ads manager! Please help? ~ only running fb ads to drive traffic

**Comment by leinadnat** [comment]
Anyone please? I have tried looking for a solution but couldnt find any working.

**Comment by leinadnat** [comment]
Hey man?

**Comment by sammul** [comment]
@leinadnat what's your website url and pixel id?

**Comment by sammul** [comment]
Talked with @leinadnat and his pixel is working fine. Closing the issue
