### ISSUE TITLE
Facebook for WooCommerce: how to delete products on FB shop?

### ISSUE THREAD

**Issue by studiomanusha** [facebookincubator/facebook-for-woocommerce#397]
We had a couple of Simple Products in WooCommerce with incorrect "attributes". It created a couple of incorrect products in our Facebook shop and we can't seem to delete them off Facebook. Even after updating the products in WC and re-syncing, they still show up. 

How can we delete products off the Facebook Shop?

**Comment by sammul** [comment]
Hi @studiomanusha , you can open our plug-in, go to advanced options, delete everything and then re-do the setup. Let me know if it works. Thanks

**Comment by dmitridr** [comment]
@sammul 's suggestion will work. But you can also delete items individually by going to their product page on WooCommerce, and on the right-side panel there is a link `Delete on Facebook` that you can use to remove the product.

Be warned : Next time you update the product, it will auto sync to FB. So a more permanent solution would be to mark it as 'not visible' this will make the product invisible to users who see your shop. The visibility setting can be found in the same place (product edit page) or on the products overview page there's a column for it.

**Comment by studiomanusha** [comment]
Thanks for the info. We had tried the 'delete on Facebook' option for one of the products but it didn't seem to clear the wrong ones. 

We cannot make them 'hidden' as they are some of our major products; it's just that a couple of additional products with the wrong price got added to Facebook because of the colour attributes.

So after removing the attributes and updating the products on WC, we tried the delete on Facebook button and then saved the products again but they didn't all clear...

Will try one more time and if it doesn't do it, suppose we'll have to delete all and start again. 

Is there a place somewhere on Facebook where we can manually delete the products off the shop?

**Comment by dmitridr** [comment]
Hey again, 

The option to delete products via the Shops interface is only available for self-serve shops, unfortunately.
I do think a full reset has a good chance of fixing the issue. I'd also make sure you have our latest version, v1.8.4.

Regarding your earlier comment, are these products with incorrect info variations? I may not have been specific enough earlier, there is an FB-specific visibility setting for products which should be on the product edit page.

Hope that helps.

**Comment by studiomanusha** [comment]
Hi @dmitridr 
Thank you very much for getting back to us. Shame about not having the ability to delete products vua the FB Shop interface. Is it in planning at all? It would be good to be able to re-order them as well.

Re: version, yes we are running the latest one

Re: faulty products on Facebook, they are WooCommerce Simple Products and had incorrect "Attributes". Even after deleting the Attributes off the products, "deleting on Facebook" and re-saving, the faulty ones are still showing in the FB shop. 

Re: visibility, I saw indeed that you were referring to the FB-specific setting but I do want the product to show on Facebook, just not the additional weird/wrong/$5 versions that were created initially.
Anyway, it looks like a full reset is the only solution. 

Thanks for your assistance with this.

**Comment by dmitridr** [comment]
Hey again,

We are not planning to support deletion, unfortunately, but 
you can control the order the products are displayed by creating a Collection, as described in #401. 

Hope the full reset helped. If not feel free to open a new issue on us, referencing this one. I will close this out.

**Comment by ba7ba7** [comment]
> Hi @studiomanusha , you can open our plug-in, go to advanced options, delete everything and then re-do the setup. Let me know if it works. Thanks

these options you refer to do not exist. woocommerce> settings> integration=> facebook. advanced settings. cannot delete, erase, or break pixel connection.
