### ISSUE TITLE
Issues with products sync

### ISSUE THREAD

**Issue by jcastro91** [facebookincubator/facebook-for-woocommerce#40]
Hello!

Not all my products are being sync to the facebook store, I'm not sure why or what's the condition for it, but they aren't, and I can even see the check to publish them, just a Not Sync message. 

Please help! Thanks,

**Comment by jcastro91** [comment]
It just says: This product is not yet synced to Facebook.

**Comment by dmitridr** [comment]
Hello!

The sync should happen in the background, if you remain on the facebook settings page. Is this not happening for you? Screenshots would help us understand the problem. 
Have you tried 'Force resync' on the settings page?

**Comment by jcastro91** [comment]
Hello

I just noticed that if I just update the products, without changing anything, it syncs them. Force Sync wasn't working neither, the only way I manage to do so, is to enter to each product and update it. 

Best, Jorge

**Comment by jcastro91** [comment]
Hello!

I can give you the error logs, but I would prefer doing it privately, is there a way I can send them to you that way?

Best, Jorge

**Comment by dmitridr** [comment]
Hello Jorge,

Yes you can email us at ads_extension_woocommerce@fb.com, we will not be able to respond but we will see your message. Thank you for taking the time to send us the logs so that we can try to debug it!

**Comment by jcastro91** [comment]
Done! 👍

**Comment by dmitridr** [comment]
Thanks, I received your files! I noticed there was some warnings about code that no longer exists in our plugin, so I checked your version.

I see that you are running a really old version of the plugin 1.3.0, is this correct? You may want to upgrade to [1.6.1](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest) it is likely it will fix your problem. Could you try this?

**Comment by dmitridr** [comment]
I'm going to go ahead and close this, please feel free to re-open if you updated to 1.6.x and it's still not working for you!

**Comment by jhbreen** [comment]
Hello,

I am having the exact same problem that jcastro91 described ...

"Not all my products are being synced to the Facebook store, I'm not sure why or what's the condition for it, but they aren't, and I can even see the check to publish them, just a Not Sync message."

Please help! Thanks,
