### ISSUE TITLE
Graph API issue

### ISSUE THREAD

**Issue by Dedagroup** [facebookincubator/facebook-for-woocommerce#400]
Will this be fixed in any update soon?

![udklip](https://user-images.githubusercontent.com/38320880/38678240-c43c94aa-3e60-11e8-9cea-466f1e46dad5.JPG)

and will we be able to update the plugin inside wordpress instead of having to delete the plugin and reupload the newest update? :)

**Comment by dmitridr** [comment]
Hello,

Could you tell us your version? We should have auto-update in wordpress as of 1.8.0, so if you upgrade you should get that functionality.

Also, if you do a reset of the plugin on a newer version (preferrably the latest one, v1.8.4) that error should disappear. It's generally caused by a bug in older versions where Facebook Object IDs are left in the DB when they should have been erased. A reset can be done with `Reconfigure > Advanced Options > Delete` on the plugin's config page. Hope that helps!

**Comment by Dedagroup** [comment]
I am using the version 1.8.4 and it doesnt help.
i see that you came with a new update, but it doesnt update in wordpress automatically? Do i really have to download the new update and delete my old one manually?

And i resynced all products. Still it doesnt work.
Now my viewcontent pixel also stopped working.

**Comment by sammul** [comment]
@Dedagroup I'd like to check your role on the page and business. Can you send me your facebook page url and your first name? Thanks

**Comment by Dedagroup** [comment]
https://www.facebook.com/riott.dk/

My name is Daniel

**Comment by Dedagroup** [comment]
https://business.facebook.com/riott.dk/?business_id=635464806619878

**Comment by Dedagroup** [comment]
Anything new?

**Comment by sammul** [comment]
@Dedagroup from my looking at your website, some products are working(e.g. https://riott.dk/produkt/young-rich-vest-med-aftagelig-pels-haette/?attribute_pa_stoerrelse-1=stoerrelse-xl)
Some are not working (e.g. https://riott.dk/produkt/vest-med-aftagelig-haette/)

There are currently 3095 products uploaded. Is this a partial upload problem(our extension only uploads part of your products)?

**Comment by Dedagroup** [comment]
I'm not sure what you are asking me?
i have no idea why this happens. It should be the same to all products.

**Comment by Dedagroup** [comment]
Nah. We have 556 produkts. I think the number 3.095 must be with variations?

**Comment by Dedagroup** [comment]
It is fixed now. The latest update and a resync did the job.

**Comment by dmitridr** [comment]
Nice. Glad we could fix this with our updates.
