### ISSUE TITLE
order the products are displayed

### ISSUE THREAD

**Issue by patiohq** [facebookincubator/facebook-for-woocommerce#401]
How do we change the order that the products are displayed on the Facebook Shop page? 

Currently, they are in rows with 4 columns but it seems to list the products from our website randomly. I'd much rather display more popular products or products that are on sale in the first say 2 to 3 rows.

**Comment by dmitridr** [comment]
Hey!

I recommend creating a collection, and then featuring that collection at the top of the store. I believe collections allow you to change the ordering. They can be created by going to the settings of the shop (gear icon on the top right of the shop screen), under `Collections`. 

Unfortunately, the products in the default collection (what you see immediately after upload) can't be ordered by themselves. Hope that helps!

**Comment by patiohq** [comment]
that worked, thanks

**Comment by Neokmc** [comment]
I am still having issues with this, I see no way to make collections anymore to fix this on Facebooks side of things.
