### ISSUE TITLE
google product category error issue

### ISSUE THREAD

**Issue by patiohq** [facebookincubator/facebook-for-woocommerce#402]
A product is missing a field: google_product_category Without google_product_category information, your products may not appear the way you want them to in ads.

What does this mean and how do I fix it?

**Comment by dmitridr** [comment]
Hey again! You can ignore this error, it's harmless. 

Here's what it means though:

If you have a per-product attribute called `google_product_category` which correspond's to an entry in google's product taxonomy, we can potentially import that (Google set the standard for this). It helps the accuracy of FB product classification, which in turn helps us recommend correct products in ads when appropriate. (e.g. Someone buys a shoe, we can recommend them a sock, if we have a correct classification.) However, our classification algorithms are already fairly accurate even without this information, so it helps but it's not essential.
