### ISSUE TITLE
++++ Pixel report purchase on Power editor but no purchase at all ++++

### ISSUE THREAD

**Issue by jerome2612** [facebookincubator/facebook-for-woocommerce#403]
i have purchase action reported on my powereditor but no purchase in reality on 
hhtps://truktil.com
this is very annoying so many bugs and problems with this plug in on 6 months I did more than 10 reports there and only for the basic thing FB selling the pixel like the best tools for control our advertisement but all datas I have with my pixel are wrong so I don't know what thinking about this plug in 
looking forward

**Comment by leinadnat** [comment]
It could be organic purchases

**Comment by jerome2612** [comment]
@leinadnat can you develop what is it a n organic purchase that it's the first time I heard or read that ...

**Comment by sammul** [comment]
@jerome2612 can you send me the campaign id, which has a false purchase reported? From my side, i can see your pixel did fire purchase during the last week.

**Comment by dmitridr** [comment]
No follow up here for over a month. I'm closing this out. Please open a new issue and reference this one if you want to follow up.
