### ISSUE TITLE
affiliate links not redirecting to product page of advertiser

### ISSUE THREAD

**Issue by myfrontrend** [facebookincubator/facebook-for-woocommerce#406]
My products are included in the Facebook shop, but on a desktop, my affiliate links don't redirect right. On the Facebook app they do redirect to the right page. Pretty weird.

**Comment by dmitridr** [comment]
Can you link us to an example product? We can take a look at what's going on. Could be a bug in shops.

**Comment by dmitridr** [comment]
Past issues with affiliate products here, for reference : #120 #157

**Comment by mengyingdu** [comment]
Hi @myfrontrend ,

I can't repo your issue and we do have a fix from [v1.7.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.0)

My repo steps:
1. create a 'external/affiliate' product
2. check on my facebook test shop
3. click on checkout
4. it will redirect to the product page (of your shop)

If you are not on the latest version, I recommend you upgrade.

Thanks.
