### ISSUE TITLE
Product images not displaying on Facebook shop

### ISSUE THREAD

**Issue by LouDivine** [facebookincubator/facebook-for-woocommerce#408]
I installed the plugin last week and after trying to use the Parent image after no images were being pulled through, this still isn't displaying any images at all.

I tried creating a new product with a different style of product image and that didn't work either. I know I am using ACF for some images, but I thought it would at least display the default Product Image?

FB Shop link: https://www.facebook.com/pg/ragingbullandcheekycow/shop/?ref=page_internal

**Comment by bianca713** [comment]
i having a problem too, but i manually upload the product images into my shop page. it doesnt show the images. 

please assist on this 

fb shop link: https://www.facebook.com/pg/MEOAirMY/shop/?ref=page_internal
