### ISSUE TITLE
deleting the products in facebook created via WooCommerce plugin

### ISSUE THREAD

**Issue by tomwebmanager** [facebookincubator/facebook-for-woocommerce#409]
hi, 
we have a company page that we manage, and uploaded products from the plugin, 
after a long week that the products where under review, and we tried reching facbook, we decided we want to upload the products manually without the plugin, but how can we remove the products? how do i disable the plugin so the product will not appear in facebook?

**Comment by sammul** [comment]
Please open the extension, go to 'Advanced options' and then delete everything

**Comment by tomwebmanager** [comment]
where? in facebook?

**Comment by dmitridr** [comment]
Apologies for the lack of timely follow up here.

You would go to the main configuration page of the plugin, inside WooCommerce settings, where you first set up the plugin. There's a button to `Reconfigure` settings, you'd click that, then click `Advanced Options` then `Delete`.

You can also delete the facebook catalog directly by going to `www.facebook.com/products`. Hope that helps.
