### ISSUE TITLE
Compatibility : AliDropship

### ISSUE THREAD

**Issue by vallweb** [facebookincubator/facebook-for-woocommerce#410]
Hello,
I have imported my catalog to the facebook shop, but the problem is that it's uploading all products of my woo store... even the products i have in "draft", or "pending of review". I don't want those products to show as they are not complete (no image, not good titles,...).
The strange thing is that in face book woo plugin it says it import only published products (in my case 73 as you can see in the print screen).
![2018-04-16_00h43_33](https://user-images.githubusercontent.com/38409706/38784286-da3466be-410f-11e8-88ee-0a44faf1cbab.png)
But really shows all products not only published, so it uploads around 320 products.
![2018-04-16_00h44_43](https://user-images.githubusercontent.com/38409706/38784299-016e5848-4110-11e8-82fb-f79d2f72ddfb.png)

I have tried to delete plugin, reset all settings, import again products , but still uploading all products.

Any suggestion to face this problem??
Thanks in advance,
David

**Comment by sammul** [comment]
similar report here: #380

We will look into for next update.

Is it possible you unpublish them to see what happens?

**Comment by vallweb** [comment]
I have not unpublished from woocommerce as it's on production webstie and people are woring on. But i moved products status from "pending" to "draft", also to "imported",... and doesn't change. Always showing and importing to the facebook shop!
May be an important information, i use Alidropship plugin and we import products. Maybe the #380 also use this plugin??
When do you think you will check to fix this issue? Just to know if i have to check for another plugin.

Thanks for your answer.
David

**Comment by vallweb** [comment]
I see this morning you an update available, but when i try to install it it gives me an Error.

**Comment by sammul** [comment]
@vallweb what error do you see? Have you tried 1.8.5?

**Comment by vallweb** [comment]
I have tried again and still not working...
Please see prints:
![2018-04-19_10h35_53](https://user-images.githubusercontent.com/38409706/38981444-ba45b800-43bf-11e8-86e4-46624e63995c.png)
![2018-04-19_10h26_57](https://user-images.githubusercontent.com/38409706/38981487-d57873ce-43bf-11e8-988a-8c3344ec8c3c.png)
Good i have only 85 products to upload (but you will see later that it uploads everything, not only those 85).
![2018-04-19_10h35_14](https://user-images.githubusercontent.com/38409706/38981494-d97034a8-43bf-11e8-8135-7f761ea5a7a9.png)
In some of the tests i had this error:
![2018-04-19_10h36_39](https://user-images.githubusercontent.com/38409706/38981576-030e8c74-43c0-11e8-818e-44edea136434.png)
Example of product that should not upload as it's not in "published" but in "pending" status:
![2018-04-19_10h39_17](https://user-images.githubusercontent.com/38409706/38981646-2e25df66-43c0-11e8-9706-023a1d93b5d6.png)
![2018-04-19_10h40_15](https://user-images.githubusercontent.com/38409706/38981656-31ad894a-43c0-11e8-90b6-d704fe03eb06.png)
Maybe 2 solutions to wait you find how to fix the import problem??
![2018-04-19_10h42_51](https://user-images.githubusercontent.com/38409706/38981712-5499e7b4-43c0-11e8-96bc-a8281188f343.png)
![2018-04-19_10h47_00](https://user-images.githubusercontent.com/38409706/38981714-56fd3394-43c0-11e8-9ef2-59f244ae7213.png)

Regards

**Comment by sammul** [comment]
@vallweb  You can see those products because you are admin on the shop/page. Normal user doesn't see the unpublished products. Can you use another account to check your shop to see if a client can see those products? In theory they wouldn't see the draft/unpublished/processing products

**Comment by vallweb** [comment]
Hello.
Theory is not reallity ... Yes they can see all draft/unpublished/processing products, just tried with a normal facebook user...
I even passed product by product in the woocommerce product catalog to set in the "Facebook shop" column on "Hide" on all those unwanted products but still showing... 
REAL problem with this plugin actually...
Please any other plugin working and doing this job ?
Thanks.

**Comment by vallweb** [comment]
Well... No answers, no solution...
For all those who have this issue the best way is to use a this other plugin: WooCommerce Product Feed PRO (free version allow you to export for Facebook shop).

**Comment by mengyingdu** [comment]
Hi @vallweb ,

Apologize to hear your problems and delayed reply!

1. We fix WP import incompatibility in [v1.8.7](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.7), but not Alidropship plugin. Hope you can understand we have limited resource and impossible to support every other plugins. If it's possible, would you mind to use WP import? It works for importing and is a high ranked plugin 

2. We fix draft/pending product published in the latest version too. Would you like try to upgrade and sync from scratch? I understand you feel frustrated, but you want to give it a try, I can give you detailed instructions.

Again, our developers do care our plugins and users. We just host a quality room to fix hi-pri bugs and fix some incompatibility issues. 

Thanks

**Comment by vallweb** [comment]
Hello, 
Features of WP import and Alidropship are not the same. So no, i can't try WP import in order to have Facebook-for-woocommerce plugin working... 
Alidropship is a Premium plugin with also many customers, so may be you should check to fix the incompatibility.
Let me know if one day you fix it.
Best regards.

**Comment by dmitridr** [comment]
Thanks for trying our plugin in any case. The draft/unpublished issue has been fixed as of the latest version.
However, the workaround for `Alidropship` and other import plugins would still be to `Force Resync` after every use. Perhaps we can add a feature to detect many unsynced products and surface a notification suggesting a resync to FB (We do this for `All Import`). I've marked this as a feature request with that in mind.

**Comment by mengyingdu** [comment]
Hi @vallweb ,

Do you still have problems with draft/unpublished issue?
Does 'force resync' work for you?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
