### ISSUE TITLE
Missing purchase event data on iOS-devices

### ISSUE THREAD

**Issue by orjansteffensen** [facebookincubator/facebook-for-woocommerce#414]
Hi guys, we have a peculiar problem on our site (friskforlag.no), and I can honestly not say if it's a bug with iOS, with Facebook pixel in general or with our site.

In short we don't receive any data on conversions (event: Purchase) for our ads on iOS-devices. Android and computers track fine. We've suspected that this has to do with the in-app browsers that open up when clicking an ad in Facebook or Instagram, but it's difficult to verify. We know the numbers are wrong on FB, since we can compare and verify that the numbers between Woocommerce and Google Analytics are correct.

The website uses Divi theme, and we sell our products mostly by using landing pages with integrated checkout using the plugin One Page Checkout available from woocommerce.com. My best guess is that the missing data is either due to some incompatibility with Divi or the plugin, or the combination.

The missing data can be backtracked to March 15th, which is also the date we migrated to Divi from another theme. At the time we used another checkout plugin that loads the checkout fields and cart via iframe, we had to replace this plugin when we discovered that the iframe would not load in the in-app browser on iOS, hence we changed to One Page Checkout which loaded correctly. Upon completion of order user is sent to woocommerde order confirmation which has Purchase-event correctly installed. But no conversions on iOS are registered.

If it can be of interest, I can upload screenshots of Google Analytics vs. Facebook metrics. 

PS! You are welcome to test purchase if you'd like to test the pixel yourself. Just make sure the payment type is "Faktura" and write 5303 in post code (postnummer) and write test on everything else. Tests can be done here: https://friskforlag.no/frisk-graviditet/

**Comment by sammul** [comment]
@orjansteffensen what can I put for Epostadresse? It didn't go through if I put test for it

**Comment by orjansteffensen** [comment]
Ah, sorry. I meant test in a generic way. It'll probably work if you write test@test.test or any gibberish as long as it has @ and .

**Comment by orjansteffensen** [comment]
Update: I've just got a word from Elegant Themes help. They've asked me to comment out a snippet from the core > functions.php file. Didn't get any more info than that, but since it was so specific it might point to the Divi theme. I'll probably see if I get any conversions within tomorrow morning UTC+2.

**Comment by orjansteffensen** [comment]
Can confirm that we receive purchase data after commenting out a line of code in Divi. The developers are aware of the bug, but haven't yet been able to implement a fix.
