### ISSUE TITLE
Sync Problem for old version: partially sync, some product groups doesn't have product Item

### ISSUE THREAD

**Issue by benw-emote** [facebookincubator/facebook-for-woocommerce#415]
I want to set up Facebook shop/catalog/ads but then I've installed the plugin I do not get the prompt necessary int he below steps:

<img width="875" alt="screen shot 2018-04-18 at 4 36 41 pm" src="https://user-images.githubusercontent.com/38487969/38915445-0618bd7a-4327-11e8-80a2-24fe0c6b36d8.png">

**Comment by sammul** [comment]
Do you see the blue button 'Get Started'?

**Comment by benw-emote** [comment]
Hi @sammul no it just displays like this - there doesn't seem to be any links to get started to complete set up

![screen shot 2018-04-19 at 15 09 59](https://user-images.githubusercontent.com/38487969/38972439-d81bf708-43e3-11e8-9b9b-4b89c2e8aec0.png)

**Comment by sammul** [comment]
Please go to 'settings' then 'integrations' to find the dialog

**Comment by sammul** [comment]
First of all, have you found the get started button?

**Comment by benw-emote** [comment]
@sammul yes although because the plugin was there previously it said re-configure facebook settings. I did this and it still didnt work.

**Comment by sammul** [comment]
Please share your catalog id so I can have a quick look into

**Comment by benw-emote** [comment]
@sammul 
Catalog #: 434100270369648

**Comment by benw-emote** [comment]
Hi @mengyingdu thanks a lot for this. I have folowed those steps and the products seem to be syncing up! Waiting for them all to load in!

**Comment by mengyingdu** [comment]
Hi @benw-emote ,

I do recommend that you upgrade your plugin version if you haven't done that. We have supported many new features and performance enhancement in recent release. You can download it [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.5).

Thanks.
