### ISSUE TITLE
Size variations not coming in correct order  

### ISSUE THREAD

**Issue by MRisley84** [facebookincubator/facebook-for-woocommerce#417]
I have a few products that are shoes that have numbered sizes and when I imported them into Facebook using the plugin they are all out of numeric order. How can I get them to show in numerical order?

 Here is a pic of the size chart on Facebook
![image](https://user-images.githubusercontent.com/38531949/38995683-7a9c4d20-43b7-11e8-987f-7edf31f8f052.png)

**Comment by sammul** [comment]
Seems a reasonable feature request. Thanks for reporting. We will discuss about the prioritization of this.

**Comment by mengyingdu** [comment]
@MRisley84 Please refer to the comments in #309

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
