### ISSUE TITLE
Repeated Catalog Integration Failure  

### ISSUE THREAD

**Issue by VeloSocial** [facebookincubator/facebook-for-woocommerce#418]
I have been attempting to import my catalogue to Facebook for the past 48hours without success. The integration summary (see screenshot1) reports 29k products are in my inventory, but no products are visible in my shop tab. After waiting for 24hrs with no change, I have followed the guidelines by deleting my settings and attempting to import again, but still no products visible. The summary shows it as a successful import, but no products are visible. 

On the first import attempt, the products were visible within Facebook > Catalog Manager, but are now no longer. See screenshot2

If I try to delete settings and try again, there is a message in my WP login stating Your API key is no longer valid. Please click "Re-configure Facebook Settings > Advanced Options > Update Token". I have updated the token, but the message is still visible. See screenshot3.

As a final fix, I deleted the Facebook plugin and reinstalled, but the above errors are still visible.

Any help would be much appreciated!

Here is a link to my Facebook page: https://www.facebook.com/velosocial/ 
Website URL: www.velosocial.cc
Facebook plugin version 1.8.5
Woocommerce version 3.3.2

![screenshot1](https://user-images.githubusercontent.com/38535219/39003408-b5e78e2c-43f2-11e8-91e3-091874b6353e.png)

![screenshot2](https://user-images.githubusercontent.com/38535219/39003543-f6a90d14-43f2-11e8-9d3a-14bfe22b8210.png)

![screenshot3](https://user-images.githubusercontent.com/38535219/39003778-7cae17b0-43f3-11e8-849f-1dd8bcc2ee9c.png)

**Comment by VeloSocial** [comment]
![screen shot 2018-04-19 at 17 10 17](https://user-images.githubusercontent.com/38535219/39004177-97792b2e-43f4-11e8-9749-122d937a9422.png)

**Comment by sammul** [comment]
Hi @VeloSocial I just looked at your shop and it's working:  https://www.facebook.com/pg/velosocial/shop/?ref=page_internal

Can you confirm?

**Comment by VeloSocial** [comment]
Hi Sammul,
Yes, all now working, thank you.
