### ISSUE TITLE
Product sync

### ISSUE THREAD

**Issue by Grin0011** [facebookincubator/facebook-for-woocommerce#42]
I have integrated the Facebook for woocommerce plugin in my webshop. So all my products are synced with the Facebookshop, but I want that only the products with the status 'in stock' are synced to the Facebookshop. Is that possible?

**Comment by dmitridr** [comment]
Hi,

There's a workaround in #37 that should solve your issue. Let us know if that works for you or if you are asking for something different.

**Comment by dmitridr** [comment]
Closing this. Please re-open if it's still an issue.
