### ISSUE TITLE
remove some products

### ISSUE THREAD

**Issue by patiohq** [facebookincubator/facebook-for-woocommerce#421]
How do you remove some products but not all of them? I clicked the Hide button next to each product that I want to hide from our Facebook shop and then did a resync but those products still appear. When I try Manage Shop on the Facebook store page there are no choices to delete each individual product.

**Comment by sammul** [comment]
You can hide the product on your website and resync. You cannot delete the individual product on facebook

**Comment by patiohq** [comment]
I've done that already and the products that I've hidden still appear on our Facebook shop page.

**Comment by sammul** [comment]
@patiohq You can see those products because you are admin on the shop/page. Normal user doesn't see the unpublished products

**Comment by patiohq** [comment]
I wish that was the case but I opened this up in a different browser Firefox vs Chrome so that my session isn't logged in and the hidden products still appear. We are trying to hide the blue cushions and the brown images with the raindrops on them which are furniture covers. 

https://www.facebook.com/pg/patiohqfurniture/shop

**Comment by patiohq** [comment]
I'm noticing another problem, when you click on a product to goto our website, any product that has additional attribute options or variations results in the product not being added to the cart.

**Comment by patiohq** [comment]
All we want to do is display our products in the shop, then start to advertise them......This shouldn't be so complicated and convoluted.

**Comment by sammul** [comment]
@patiohq For the checkout issue, you can follow #378

**Comment by sammul** [comment]
@patiohq I tried the hide button, and it works for me. (if you are interested: https://www.facebook.com/commerce/products/1686522174750384/ it will say the page is not available)

**Comment by patiohq** [comment]
It's not working for me so there must be another issue or something is conflicting with the plugin on my website. Thanks for your assistance. I will figure something out.
