### ISSUE TITLE
Products have been processing for over 48 hours

### ISSUE THREAD

**Issue by directrevenues** [facebookincubator/facebook-for-woocommerce#422]
I have been having issues with my Woo Commerce products syncing to my Facebook Shop. My Woo Commerce catalog has synced with my Facebook page and I can see it/products within Business Manager settings. Some of my products/images have uploaded to FB Shop fine, however, most have read "processing" for over 48 hours now. I have forced sync multiple times with no luck. My Instagram Shop settings allow me to select my Woo Commerce catalog with 26 products, but when I go to tag a product in a photo - none of the products appear for me to tag. Please advise.

Facebook Page URL: https://www.facebook.com/McCallFitness/

WordPress and WooCommerce version number: 
Wordpress Version 4.9.5 
Woo Commerce Version 3.3.5

Facebook Plugin version number: Facebook for Woocommerce Version 1.8.3

How many products you have: 26
Types of products: Fitness Supplements
Do you have Duplicate SKUs in your system? No
What kind of customization plugins you're using (if any)? Not sure

**Comment by sammul** [comment]
@directrevenues the shop is approved while some products are under-review. Did you see more products cleared over time? Just let you know that re-do a setup will require product reviews again so you probably don't want to do that.

For instagram shop, please see #332 , we don't support instagram shop yet but it's coming soon.

**Comment by directrevenues** [comment]
Ok - a few products have cleared, but is it normal for products to be "processing" for over 48 hours?

**Comment by mengyingdu** [comment]
Hi @directrevenues ,

We have products review process, and sync with backend data. 
Thanks.

**Comment by directrevenues** [comment]
How long does the review process take? It says "process takes minutes" but it's been almost 72 hours with the same products under review or "processing" and no new products have been approved. 

![screen shot 2018-04-21 at 12 43 08 pm](https://user-images.githubusercontent.com/38571095/39087113-a23b238c-4561-11e8-8903-9e6efd015e3f.png)

**Comment by sammul** [comment]
@directrevenues I shouldn't be that long. However, the review process is handled by other team. I'll help to report for you next Monday. Thanks for your patience

**Comment by directrevenues** [comment]
@sammul Just checking in to see if you have any updates for me on this. Our products are still showing as processing and no new products have been approved or rejected since last week. Thanks

**Comment by sammul** [comment]
@directrevenues Just reported your issue to the Facebook shop team, who handles the product review. Will let you the outcome. Thanks for the patience

**Comment by dmitridr** [comment]
Hello @directrevenues 

I am following up on old issues. I see some of your products have been approved, others are rejected, and one pending (though it says rejected in our system). If you'd like to appeal the rejection I'd encourage you to use the appeals form if it is working for you.

One other thing you can do is to use the `Facebook Description` provided in WooCommerce in order to change the description of the product on Facebook to something that will be less likely to be rejected (it seems we have very strict policies on supplements, here's some more details on policy : https://www.facebook.com/policies/commerce). 

Generally, if the product processing is taking too long, you can resubmit the product for review by making a change in the product description (the `Facebook Description` mentioned above) or similar. 

As @sammul  said, we have limited ability to help you with this, since this is not controlled by the plugin and is owned by another team. Hope that helps.

**Comment by bulbuljessore** [comment]
Hey Guys

Hope everyone doing good without me at this moment. I am having the same problem regarding this post. However, I have checked the link for facebook policy for e-commerce. And I believe that my shop is okay by their policy. 

I import all of my 76 products from WooCommerce to my Facebook Shop page and it's over 48 hours and most of the products are in processing mode and some of those are available for view (only for me). 

I am using all updated version of the theme, WooCommerce, and the plugin but the Facebook Shop page is still unavailable. I was planning for Black Friday's sales but now I do not have I will able to make it. 

Do you have any solution for me? so I can fix this problem and start boosting my products using Facebook ads. 

Looking forward to your reply ASAP.

**Comment by jakestpeter** [comment]
I'm running into all these problems. Products rejected like Purse and Necklace. Items processing for days and weeks ...  Appeal rejections not working. What a MESS!
![PastedGraphic-2](https://user-images.githubusercontent.com/7673228/66142076-d1f68e00-e5d2-11e9-936a-5a148d84c4f6.png)
![PastedGraphic-4](https://user-images.githubusercontent.com/7673228/66142082-d4f17e80-e5d2-11e9-8c80-97fb7cdf0506.png)

**Comment by linkinpark187** [comment]
I'm having issues with items being processed, as well.  I just posted a new item, but I have one that I know I edited more than a month ago, and it's still sitting at "Processing".  This is more than just a tiny issue, and clearly the issue is growing.  What gives?
