### ISSUE TITLE
Product Upload problem

### ISSUE THREAD

**Issue by wkschab** [facebookincubator/facebook-for-woocommerce#423]
Upload is stuck on 90 products. It says Progress: 33 items remaining although i have lots of variable products on my website. Plugin 1.8.3 with up to date version of woocommerce. I tried to delete everything and restart process but first it says something went wrong and when i do force restart it says Products synced with your shop and 33 remaining but in fact I have only 90 in the store. I am not sure if this is a bug or something that I can fix. Thank you.

**Comment by sammul** [comment]
@wkschab sorry for the delay in replying. Can you share your facebook page url?

**Comment by dmitridr** [comment]
Recommend the following steps (if you have not fixed it already) : 

- Upgrade to v1.8.7
- Reset the extension using `Reconfigure > Advanced Options > Delete`
- Sync again.

If it still doesn't work, it is likely your server does not have `curl` support. I would investigate why and try to enable it (we use `curl` for the new product upload method). Hope that helps.
