### ISSUE TITLE
Facebook extension error: Facebook for WooCommerce Invalid parameter

### ISSUE THREAD

**Issue by conjunktionman** [facebookincubator/facebook-for-woocommerce#425]
Hi there,

The plugin keeps displaying the same error when I am attempting to sync a new product to the Facebook shop. 

**Facebook extension error: Facebook for WooCommerce Invalid parameter**

The product URL is https://rockthejumpsuit.com/product/rachel/

Product group number is 1689392551156229

FB page is https://www.facebook.com/rockthejumpsuit/

The product isn't any different from the other outfits on the website so I am a bit stumped.

Any ideas would be greatly appreciated.

Thank you

**Comment by conjunktionman** [comment]
Anyone have any answers for this?

**Comment by conjunktionman** [comment]
I figured this out myself which is fortunate because no one bothered to offer any advice.

So if anyone out there has the same problem here was my issue:

The products on my website had titles in ALL UPPERCASE. I simply added a lower case tag-line to the title and the issue was resolved. Turns out Facebook doesn't like the product titles or descriptions being in ALL CAPS.

I hope someone else finds this useful.

**Comment by amirvenus** [comment]
I have the same problem and I confirm not all of characters in item's title are uppercase.

**Comment by lucatorcivia** [comment]
steso problema! e confermo ho risolto utilizzando la soluzione di @conjunktionman !!!!!

grazie mille!

**Comment by LeeStuttaford** [comment]
This still seems to be an issue:  

Facebook doesn't like the product titles or descriptions being in ALL CAPS - even when creating the product with title in Sentence case and then editing it to UPPERCASE, (as some clients wish to have it), it then fails to keep the product linked correctly in FB view?
