### ISSUE TITLE
Facebook pixel code on this page didn't load

### ISSUE THREAD

**Issue by rocketmanny** [facebookincubator/facebook-for-woocommerce#426]
i uploaded and set up pixel on my website using the plugin, however my facebook pixel helper identifies that the "view category" section of the pixel doesnt load even when i click the button and browse the website. how do i fix this?

**Comment by rocketmanny** [comment]
My site is www.ahima.co.uk and Facebook url is www.facebook.com/ahimajewellery. 

And yes everything is updated. I do not use adblocker.

**Comment by mengyingdu** [comment]
Hi @rocketmanny,

I checked your store and record, it seems your initial version is 1.7.3 and then upgrade to new version. I have more questions:

1. Any other plugins you are using now? Detailed list will help.
2. If you don't have any other plugins, can you try re-setup? 
Instructions:
1. go to 'woocommerce' -> settings  -> integrations -> facebook-for-woocommerce
2. In the blue panel, click on 're-config'
3. In the popup window, 'advance option' -> delete your settings
4. back to the blue panel, click on 'get started' -> finish setup

BTW, we had a quality room first half of this week and just released [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6) We have 10 fixes plus 1 content enhancement. I do recommend you upgrade first and then go through my instructions above.

Thanks.

**Comment by dmitridr** [comment]
I'm following up on older inactive issues and closing them out. 

Regarding this one, I would recommend an upgrade but I would also reassure you that `ViewCategory` is not critical to the plugin or for ads, it will not affect ads at all unless you are specifically creating audiences from this event.

I wouldn't worry too much about this, and we may remove the event in the future anyway, as Facebook has removed this event from it's list of [Standard Events](https://developers.facebook.com/docs/ads-for-websites/pixel-events/v3.0). The most important event is `ViewContent` for Dynamic Ads, (followed by `Purchase` and `Add To Cart`).
