### ISSUE TITLE
How to delete shop on Facebook created by the plugin

### ISSUE THREAD

**Issue by shaky512** [facebookincubator/facebook-for-woocommerce#428]
Hi, im also having trouble to delete products from facebook shop.
have set up the test products in woocommerce, and its appearing in facebook shop.
but can't delete them in facebook.
I've already deleted the website & all its content.
but the products still appearing in facebook.
Do help.

**Comment by shaky512** [comment]
![image](https://user-images.githubusercontent.com/38683729/39172449-5f4c36c2-47d4-11e8-9419-2b504c8e59f4.png)

**Comment by mengyingdu** [comment]
Hi @shaky512,

You can delete your products by the clicking on 'moving to trash'.
![screen shot 2018-05-07 at 9 30 15 am](https://user-images.githubusercontent.com/24535640/39712818-4805f7dc-51d9-11e8-93e0-d9d2801c3d8b.png)

If you delete the product directly from you shop, it won't sync with FB.

Thanks.

**Comment by shaky512** [comment]
HI support,

As mentioned earlier, the whole website has been deleted, due to virus issue.

Now how do I remove the product from FB?

 

 

 

Thank You & Regards

 

Shakirah Abdul Karim, OMCP

Founder/Digital Marketing Strategist of Minda Trafik | Speaker | Coach | Principal Trainer
Online Marketing Certified Professional (OMCP) | Master Certified Online Marketer (United States) 

 

Facebook: www.facebook.com/MindaTrafik <http://www.facebook.com/MindaTrafik> 

Google Plus: https://plus.google.com/+ShakirahKarimCoach
Mobile : +6019 265 7982

Email : shakirah@mindatrafik.com <mailto:shakirah@mindatrafik.com> 

IM(Yahoo)/Skype: shaky1104   Gtalk/Hotmail: shaky512

WEBSITE CONVERSION | WEBSITE TRAFFIC & SALES | SEARCH ENGINE OPTIMIZATION | SOCIAL MEDIA | STATISTICS & TRACKING | WEBSITE AUDIT | EMAIL MARKETING

Certified:

Master Certified Online Marketer (Web Analytics) : Market Motive (US)

OMCP Certified Professionals (Online Marketing Certified Professional) : OMCP International Body

Google Analytics Individuals Qualification : Google

Certified MasterPIES Trainer

**Comment by dmitridr** [comment]
Hello,

Have you resolved this? I checked your page and the shop is gone now, so I will close this out assuming you've fixed it. Feel free to reply as to how you did that, it may help others with the same problems.

If you'd like to remove the products you can do that by deleting the catalog (seen at www.facebook.com/products ). If the original website is gone, you can also delete the existing shop by installing on a new website (which will overwrite all older shops) and then deleting the settings via `Reconfigure > Advanced Options > Delete`. (which will delete the current shop).

**Comment by shaky512** [comment]
Hi Support,

The shop is still here.

I’ve just verified in my FB.

Kindly help 

 

 

Thank You & Regards

 

Shakirah Abdul Karim, OMCP

Founder/Digital Marketing Strategist of Minda Trafik | Speaker | Coach | Principal Trainer
Online Marketing Certified Professional (OMCP) | Master Certified Online Marketer (United States) 

 

Facebook: www.facebook.com/MindaTrafik <http://www.facebook.com/MindaTrafik> 

Google Plus: https://plus.google.com/+ShakirahKarimCoach
Mobile : +6019 265 7982

Email : shakirah@mindatrafik.com <mailto:shakirah@mindatrafik.com> 

IM(Yahoo)/Skype: shaky1104   Gtalk/Hotmail: shaky512

WEBSITE CONVERSION | WEBSITE TRAFFIC & SALES | SEARCH ENGINE OPTIMIZATION | SOCIAL MEDIA | STATISTICS & TRACKING | WEBSITE AUDIT | EMAIL MARKETING

Certified:

Master Certified Online Marketer (Web Analytics) : Market Motive (US)

OMCP Certified Professionals (Online Marketing Certified Professional) : OMCP International Body

Google Analytics Individuals Qualification : Google

Certified MasterPIES Trainer
