### ISSUE TITLE
Facebook for WooCommerce is almost ready. To complete your configuration, complete the setup steps.

### ISSUE THREAD

**Issue by exactsameproblem** [facebookincubator/facebook-for-woocommerce#43]
Hello there,
I was using FB for Woocommerce without any problem until today, I get this error:

> Facebook for WooCommerce is almost ready. To complete your configuration, complete the setup steps.

My catalog is still on FB, but product sync is not working anymore.
I didn't change anything, it came from one day to the other. I installed the latest github release to see if something changed, and it's still the same. Also, the pixel doesn't seem to be installed anymore, I don't see it inside the source code...but somehow Facebook detects some events?
I don't want to remove the connection as FB tells me I will have to do my ads again...Please help!

**Comment by exactsameproblem** [comment]
Quick update: this has do to with another plugin inside the Woocommerce Integration tab...(Woocommerce autoresponder). It looks like saving the settings of this plugin makes FB for Woocommerce loose the connection. It didn't change anything before...just started from one day to another. So any advice is good to take. Thank you.

**Comment by dmitridr** [comment]
Not good. We'll try it out, test and fix. Thanks for flagging and finding the offending plugin!

This is the same issue as #31

**Comment by exactsameproblem** [comment]
Hello @dmitridr and thank you for you support!
In order to help you, I have some more details.
The plugin interferring is a Woocommerce autoresponder paid plugin.
It uses the function "admin_options", it doesn't extend the WC_Integration class but still displays correctly the fields in the Integration tab next to Facebook for Woocommerce (again, everything worked before).
A function is used to process the admin options and save the data using:
`update_option( 'autoresp_options', maybe_serialize($options_array) );`
I have no idea why this would make crash the FB plugin, but it looks like this may have to do with the Integration tab...Hope it helps, feel free to ask for more details. I cannot find any errors in the log file, that's why the error is sneaky.

**Comment by DougChandler** [comment]
The same has happened to me, was all working and sync'ing, then all of a sudden the message and lack of sync. If I try and go through the setup again it says I will need to re-do any adverts I have setup.
I hope a fix is forthcoming. I don't have the other plugin mentioned WooCommerce AuthResponder installed.

**Comment by giwrgosfl** [comment]
Exact same thing just happened to me. I believe it was due to saving the options on another woocommerce integration as mentioned above. Unfortunately, I have no idea how to debug this to be of any help.

**Comment by DougChandler** [comment]
Thanks. I do have Google Analytics as another integration and I think I saved these settings recently. This could be my problem. I hope there is a fix as I'm not sure what re-setting my connection will do to my adverts.

**Comment by dmitridr** [comment]
@DougChandler 
@giwrgosfl 

Just released a new version, [v1.6.1](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest), should fix this issue permanently. Please re-open if it happens to you again on 1.6.1 or above.

Aside : I reproed this with Google Analytics, saving it did indeed erase the FB settings,
