### ISSUE TITLE
No shop on facebook

### ISSUE THREAD

**Issue by WOBusiness** [facebookincubator/facebook-for-woocommerce#433]
Hi
I have deleted the link with facebook and reinstalled it, as it wasn't removing products that I had deleted off facebook. I've gone through the process of resyncing the products. 

The Integration page within Woocommerce shows the error message "something went wrong when uploading, please try again. 

But the circle is still turning indicating it may be still trying to sync. 
The facebook catalogues page - shows 892 products in stock, and 818 products out of stock. But my actual facebook page shows a blank store... https://www.facebook.com/pg/glitterhaven/shop/?rt=28

Please advise how I can fix this. 
Thankyou
Sandra

**Comment by WOBusiness** [comment]
Hi 
Yes, that's exactly what I did. facebook for woocommerce' --> re-config your settings --> advance options --> delete you settings

Should I do it again?
Sandra

**Comment by mengyingdu** [comment]
Hi @WOBusiness ,

Sorry I didn't understand when you said 'delete the link' which I assume you refer to some other places.

I checked your setup history, I think your problem is because hasn't been submitted successfully.  If you go through the steps in the popup window, there should be a toggle for you to decide set up shop or not. Also, in the last step, when you click on submit, there should be a confirmation pop. I upload screen shot to clarify this. 
![shop toggle](https://user-images.githubusercontent.com/24535640/39322472-d64cafac-493e-11e8-8a62-f9b180d7ec7b.png)
![fae submit settings success](https://user-images.githubusercontent.com/24535640/39322478-dcc0d002-493e-11e8-8f02-52451c0e97d2.png)

My questions:
1. Did you check the toggle?
2. Did you see the confirmation window?

Thanks.

**Comment by WOBusiness** [comment]
Hi
There's no toggle nor confirmation popup. 
![facebook shop toggle](https://user-images.githubusercontent.com/38719858/39336215-a62a1a88-49f9-11e8-8261-04a8fa5ca209.PNG)

I've clicked fetch now again, to see if that changes anything.  Please advise should i delete everything and start again?
Sandra

**Comment by WOBusiness** [comment]
FYI: this time I got the confirmation screen, but still no toggle.

**Comment by WOBusiness** [comment]
Any ideas of what I should do to fix this?

**Comment by mengyingdu** [comment]
Hi @WOBusiness ,

Sorry the delayed reply and thanks for flagging this issue!
The screen shot seems very weird to me. Basically, the popup window is a product inside FB (not in plugin). I will discuss this with our engineers. It's possible a bug on FB side.

Thanks.

**Comment by mengyingdu** [comment]
Hi @WOBusiness ,

I found the reason here. There is no shop toggle in that screen. Because that's the control panel. The shop toggle is in the setup screen only, not the control panel. (you need to delete first so you can enter the setup panel.)

Thanks.

**Comment by dmitridr** [comment]
Hello, Please see #281 for instructions on getting the shop to work. The selector only appears during setup, and it's very very easy to miss, and is not automatically enabled for some users. If you do not see the selector during setup, let us know.

**Comment by WOBusiness** [comment]
Hi 
The shop selector button doesn't show. There is no shop selector toggle on the screen. I have deleted it and relinked everything and it still doesn't show. 
Sandra

**Comment by WOBusiness** [comment]
@dmitridr I'm** not sure why this issue was closed. I followed your instructions and the selector does not appear. I have deleted and reinstalled the plugin and still the selector doesn't appear. Please help. 
Thanks
Sandra

**Comment by dmitridr** [comment]
@WOBusiness 

There's no toggle on the screen you listed. The toggle is only on the setup screen, which you can only reach by resetting the plugin  using `Settings > Reconfigure > Advanced Options > Delete`, just a simple uninstall won't help/reinstall will not help. 

Please post a screenshot of the setup page you see here (it should have the buttons on the bottom as in the screenshot below). 

![shopselector](https://user-images.githubusercontent.com/29133800/42537570-22a4a468-844a-11e8-885b-21d7c94bf2d6.png)

If you still don't see it after doing a full reset, please send us your Page ID. It's possible you are in a country blacklisted from Shops, or your page was blacklisted for other reasons by Facebook.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
