### ISSUE TITLE
Guidance for having FB for Woo plugin working (after so many pain)

### ISSUE THREAD

**Issue by milosmili** [facebookincubator/facebook-for-woocommerce#440]
About: Facebook For WooCommerce WordPress plugin. 
Tested with version 1.8.3

Current version: 1.8.6: installed but causing HTPP 500 Error. Removed and re-installed 1.8.3.

URL to download: https://woocommerce.com/products/facebook/

We decided to write this out of frustration due to inconsistent, slow, and inadequate plug-in support.

The plugin is supposed to facilitate and ease transfer of your Woo products to your FB page. It is using FB Pixel technology so that every product and each product’s variation & related image is properly identified and assigned a FB URL.

Prerequisites:
A.	Create a business FB page : https://www.facebook.com/pages/create
B.	You have to create FB Pixel : https://www.facebook.com/business/help/314143995668266
C.	Create a FB business catalog : https://www.facebook.com/business/help/1397294963910848
D.	Check if all your products’ attributes & variations are properly set and assigned.

NOTE# 1: We’d suggest doing a FULL backup of your site that before you start.

1.	Login to FB
2.	In your WP admin area select WooCommerce -> Settings -> Integration
3.	Select Configure (Reconfigure) Facebook Settings
4.	Select Facebook Page you wish your products to show up
5.	Select Facebook Pixel
6.	Once steps 5 & 6 are done your FB will start transferring your FB catalog will start populating with ALL your products

NOTE #2: Depending of the number of products you have it may take anywhere from few hours to several days and perhaps weeks. The plugin does not provide any info or indication about the transfer speed, no indication on transfer progress, no alerts when transfer is done, success or failure.

NOTE #3: Most probably the initial transfer won’t include all of your products and/or all of your products’ variations & images. Also most probably the transfer might got stuck somewhere between FB and your site.

If this happens NEVER EVER select FORCE PRODUCT RESYNC as it will re-sync ALL your products and then you might start living in the Agony City: it might cause MySQL DB errors, http 500 Error, data corruption, and perhaps your ISP might think you’re spamming. The plugin is hard on consumption and sucks a considerable amount of GB for the transfer.

Instead of using Force Product Resync select ADVANCED OPTIONS -> DELETE SETTINGS. This will clear the current plugin settings and you should start from the step #3. Repeat as many times as you need. If after few re-configurations you still not getting all of your products with all variations & images proceed to step 7.

7.	Now there is no other option but to update each of your products. Slightly change a text, or add additional image and click on UPDATE button. This will transfer all of your product’s data again to your FB page. The new transfer might take between few minutes or hours and is often followed by the following:

Is it really is being processed? Well, Yes and No

8.	How To Test If Transfer Is Completed

8.1.	Login to your FB account an hour after completing steps 1. To 6. 
8.2.	Open your FB page where your products are listed
8.3.	Click on any product link
8.4.	Do you see the above product’s info? If you do not, meaning your product is 100% transferred
8.5.	If you DO see it:
8.5.1.	Open another Web browser, like Firefox
8.5.2.	Copy and paste your FB page URL from the other browser (where you’ re currently logged in) but DO NOT login to your FB account
8.5.3.	Click on the same product
8.5.4.	Do you see the above product’s info? Most probably you won’t …so that means your product is being processed 100%.

Finale Note: The plugin requires extensive amount of effort and time in order to have all set and executed. However it facilitates transfer to FB and thus transfer to your Instagram profile as well.

Check it out: https://www.facebook.com/pg/Topphonestuff-479032609180608/shop

Our Web Site: https://TopPhoneStuff.com/

We certainly hope this will help someone!

Milos, Sandra, Gabriel, Alexander and many other hard-working gals & guys @ TopPhoneStuff.Com

**Comment by sammul** [comment]
Thanks for sharing your experience here. Apologize that our plug-in gave you so much baffle. We have been trying as much as we can to make it work for everyone but sometimes it still doesn't work as expected because everyone's website could have different plug-ins and it's own environment.

Per v1.8.6, Yes we introduced fatal error in v1.8.6. The 1.8.5 is available in https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.5

**Comment by dmitridr** [comment]
Thanks for taking the time to write this!

**Comment by shonaqg** [comment]
Hi! I have been trying to integrate the pixel using Facebook for WooCommerce tool but during the setup, I get stuck on the pixel page and it says that "Ad Account Not Allowed to Create Pixels"
My ad account is working and active but it is still not letting me do it.
Can someone please assist me on how I can fix this issue? I have gotten no help from Facebook.
I raised a request 3 times to get my ad account checked and they verified that it is working fine but I am still not able to create a pixel.

**Comment by alvinarichard** [comment]
I am doing integration of my WooCommerce store with Facebook but I am having issue as entering the URL store not redirects to Facebook. I have seen several articles and also following one of the tutorial to implement it proper step by step https://www.cloudways.com/blog/woocommerce-store-with-facebook/ but I don't know why it is not redirecting. Can you help me to resolve this issue?

**Comment by geekmaxsteel** [comment]
Your totally right even now over one year later after your post you the plugin sucks totally we test it on the university on a very strong power server and I crush the server, the coding is very poor and if you ask for support, you can see that Facebook don't care at all on this issue, "just sent us you data and pay for Ads" that's the Facebook policy "Pay to Play" I really hop that one day there will be a good dev who gonna optimise that poor code with some variable that prevents the server to overload directly.. 

So good luck - Cheers Max.

**Comment by briantetrault** [comment]
I very much agree that this plugin is incredibly poorly coded and causes more issues than it helps.

Has anyone found a way to use the FB pixel without having to use this (or any) plugin? Understanding the products and such won't be synced etc. Isn't there a way to manually import products and keep them synced? I know it's more work, but probably still less than this plugin has caused. Any insight would be great, thanks!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
