### ISSUE TITLE
[v1.8.6 Broken] Problem with Facebook For Woocommerce Plugin

### ISSUE THREAD

**Issue by MillenniumJim** [facebookincubator/facebook-for-woocommerce#441]
Out of the blue, I am now getting the following PHP error when I attempt to update a product.  This started happening quite abruptly, all plugins are updated, haven't added ANYTHING, and this started occurring.  Just to make sure, I DISABLED THE PLUGIN and NO PROBLEM NOW.  Obviously, it is a problem with the plugin.  I am using the latest version OF EVERYTHING as of today's date.  pLEASE HELP!

Warning: strpos() expects parameter 1 to be string, object given in /home4/maintreasures/public_html/shop/wp-includes/shortcodes.php on line 205

Warning: preg_match_all() expects parameter 2 to be string, object given in /home4/maintreasures/public_html/shop/wp-includes/shortcodes.php on line 213

Warning: array_intersect(): Argument #2 is not an array in /home4/maintreasures/public_html/shop/wp-includes/shortcodes.php on line 214

Catchable fatal error: Object of class WP_Error could not be converted to string in /home4/maintreasures/public_html/shop/wp-content/plugins/facebook-for-woocommerce/includes/fbutils.php on line 141

**Comment by philartfactory** [comment]
I am also getting a 500 error when updating products when I upgrade to version 1.8.6, if I roll back to 1.8.3 which is the version currently available from woocommer.com then everything works fine, but once I upgrade to 1.8.6 I start getting the error. Everything else on my site is 100% up to date

**Comment by MillenniumJim** [comment]
I'm not getting a 500 error, but I am getting the aforementioned PHP errors.  Started happening all of a sudden.  When I deactivate the facebook for woocommerce plugin, it works fine.

**Comment by philartfactory** [comment]
Mine works fine with version 1.8.3 but as soon as I upgrade to 1.8.6 I am getting the 500 error as such when updating products.

Another odd issue I ran into with 1.8.6 is that it wouldn't let me simply delete the folder from my cpanel file manager, it had to uninstall it through the Wordpress back end which is extremely unusual.

At this point I am just going to chalk it up to a bad version and wait for 1.8.7

**Comment by jack-sindamag** [comment]
I am also getting a 500 error waiting for the new update :)

**Comment by TiagoRodrigues** [comment]
+1

**Comment by marmaro** [comment]
me too same php error

**Comment by abismonlo1** [comment]
I'm having the same error, how can I get a previous version? .... Can somebody help me?

**Comment by abismonlo1** [comment]
@philartfactory 
How did you get the previous version? Can you give it to me?

**Comment by philartfactory** [comment]
Download it from here https://woocommerce.com/products/facebook/ they still have the old version in official woocommerce site, you have to sign up for an account but its a free download for this product

**Comment by philartfactory** [comment]
[facebook-for-woocommerce (1).zip](https://github.com/facebookincubator/facebook-for-woocommerce/files/1958331/facebook-for-woocommerce.1.zip)

**Comment by alien27** [comment]
Same here with current version. 
Anyone else also using PixelYourSite? Maybe an issue in combination?

**Comment by jbsness** [comment]
Same here with 1.8.6 version

**Comment by alvesjc** [comment]
Hello.

I'm having the same issue.

Also, the product list is malformated in the products admin page.

I've downgrade to 1.8.3, it doesn't give error 500, but still malformed.

**Comment by alvesjc** [comment]
Hi have very few products at the moment, all show up.

The page is still in development, not a production site yet.

**Comment by sammul** [comment]
Hi everyone, we seem to introduce an fatal error to v1.8.6. Can you guys try 1.8.5 instead? https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.5

Apologize for the inconvenience. We will try to fix asap.

**Comment by sammul** [comment]
@MillenniumJim @philartfactory @alvesjc @alien27 @abismonlo1 @TiagoRodrigues @jack-sindamag @marmaro @jbsness

**Comment by pasog** [comment]
ok same error now I try the version 1.85 but it is not compatible with wmpl
apsed an updated version thanks

**Comment by bradhawkins85** [comment]
Hi sammul,

I have uninstalled v1.8.6 and installed v1.8.5 and can confirm the issue does not exist on the earlier version.

**Comment by mengyingdu** [comment]
@dmitridr , If you auto-upgrader doesn't work for you, it should be a problem for your demo server set-up.

**Comment by philartfactory** [comment]
Thank you! The update to 1.8.5 is working great for now, will be looking forward to the next update. Thanks again @mengyingdu

**Comment by alvesjc** [comment]
Hi.

Thank you.

It also fixes the formatting issue I pointed in the screenshot?

**Comment by mengyingdu** [comment]
Hi @alvesjc ,

I can't repo the format issues as you mentioned in the screenshot. It seems a different problem or your display settings. Can you open another issue to discuss?

**Comment by alvesjc** [comment]
Ok, I'll.

Thank you.

**Comment by MillenniumJim** [comment]
Version 1.8.5 works updating products with no error now....BUT AS YOU CAN SEE IN THE ATTACHED SCREENSHOT....I have 2784 products in my store (and the product count shows 2784 products) but only 144 of them are showing up in the pagination.  What the heck is going on with that....?  I started seeing that issue the same time I started having problems with the plugin, so I can possibly assume the issues are related.  Is anyone else having that issue?
![144](https://user-images.githubusercontent.com/38790098/39552569-cd483338-4e37-11e8-9092-6a61480aceeb.jpg)

**Comment by philartfactory** [comment]
Are you sure the 144 isn't a page count? If you have it set to display 20 items per page then this page count would be accurate

**Comment by mengyingdu** [comment]
Hi @alvesjc ,

[v1.8.7](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.7) is alive now and fix this issue. 

@MillenniumJim ,

It seems a different issue, would you mind discuss in a separate issue? That helps us prioritize and  track your problems.

Thanks!

**Comment by philartfactory** [comment]
Thank you, I have run the update to 1.8.7 and the products are updating without error

**Comment by pasog** [comment]
![image](https://user-images.githubusercontent.com/20639992/39601726-3c707f72-4f23-11e8-9663-d8c0c28fe54a.png)
error 500 products are not loaded

**Comment by pasog** [comment]
![image](https://user-images.githubusercontent.com/20639992/39602007-34153290-4f24-11e8-8069-1aaf91b7fd38.png)
