### ISSUE TITLE
[v1.8.6 Broken, Please try v1.8.5] Error 500

### ISSUE THREAD

**Issue by kalinin1213** [facebookincubator/facebook-for-woocommerce#442]
Hello,
today i upgraded to v1.8.6 and it causes the following issue

1. when i try to update any product, i see HTML ERROR 500
2. my hosting helpdesk (WPEngine) identified that the issue was due to facebook-for-woocommerce
here is what they said might be helpful to investigate futher "10 PHP Catchable fatal error: Object of class WP_Error could not be converted to string in /nas/content/live/olgagrinyuk/wp-content/plugins/facebook-for-woocommerce/includes/fbutils.php on line 141"
3. When i deactivate the plugin, everything works well

Hope you can fix it. thanks in advance!

**Comment by kalinin1213** [comment]
sorry just noticed that it is related to #441

**Comment by abismonlo1** [comment]
Tengo exactamente el mismo problema, agradezco la ayuda.

**Comment by sammul** [comment]
@kalinin1213 @abismonlo1 we seem to introduce an fatal error to v1.8.6. Can you guys try 1.8.5 instead? https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.5

Apologize for the inconvenience. We will try to fix asap.

**Comment by mengyingdu** [comment]
Hi @kalinin1213 and @abismonlo1 ,

[v1.8.7](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.7) is alive now and fix this issue. 

Thanks!
