### ISSUE TITLE
Partial Sync Woocommerce and FB shop

### ISSUE THREAD

**Issue by Jason611** [facebookincubator/facebook-for-woocommerce#446]
I would like to limit certain categories of my woocommerce product to be sync with the fb online store and not all shown on facebook. Is that possible? Thanks

**Comment by sammul** [comment]
It's not supported currently. You can create collections on facebook shop though

**Comment by dmitridr** [comment]
#92 #34 #364 are related issues to read for this feature. We don't support this right now, but may in the future. Thanks for your interest in our plugin!

**Comment by mengyingdu** [comment]
@Jason611  Please see my comments on #92
