### ISSUE TITLE
[v1.8.6 broken] .186 wont let me update meta description

### ISSUE THREAD

**Issue by whitlockwoodendesigns** [facebookincubator/facebook-for-woocommerce#447]
Hi, I have been trying to update a page, the content updates but the meta description won't with these error codes. The clue is in the last one
Warning: strpos() expects parameter 1 to be string, object given in /home/whitloc3/public_html/wp-includes/shortcodes.php on line 179

Warning: preg_match_all() expects parameter 2 to be string, object given in /home/whitloc3/public_html/wp-includes/shortcodes.php on line 187

Warning: array_intersect(): Argument #2 is not an array in /home/whitloc3/public_html/wp-includes/shortcodes.php on line 188

Catchable fatal error: Object of class WP_Error could not be converted to string in /home/whitloc3/public_html/wp-content/plugins/facebook-for-woocommerce/includes/fbutils.php on line 141

**Comment by sammul** [comment]
Hi @whitlockwoodendesigns , thanks for reporting. This is probably the error we introduced in latest version. Would you mind try https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.5 for now until we have fix for new version?

**Comment by whitlockwoodendesigns** [comment]
Thank you, going back to .185 has fixed the problem

**Comment by mengyingdu** [comment]
Hi @whitlockwoodendesigns @mnording ,

Apologize for the inconvenience. We have fix for the PHP error now and I will update the new version ASAP.

Thanks!

**Comment by mnording** [comment]
thanks you for the quick turnaround  @mengyingdu 
Works great

**Comment by mengyingdu** [comment]
Hi @whitlockwoodendesigns @mnording ,

[v1.8.7](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.7) is alive now and fix this issue. 

Thanks!
