### ISSUE TITLE
Fatal error when update woocommerce products 

### ISSUE THREAD

**Issue by Jason611** [facebookincubator/facebook-for-woocommerce#450]
![capture163](https://user-images.githubusercontent.com/38854071/39479580-42564b06-4d98-11e8-8531-cfdb093c07a0.JPG)

Every time, i update a product, I'll get this fatal error which is due to facebook for woocommerce plugin. Can you fix this bug? Thanks

**Comment by sammul** [comment]
@Jason611 v1.8.6 is a known broken version. Please try out 1.8.5 https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.5 and let us know if it works

**Comment by mouseacookie** [comment]
1.8.5 alleviates this problem, but the page still takes forever to load after clicking update

**Comment by mengyingdu** [comment]
Hi @Jason611 ,

[v1.8.7](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.7) is alive now and fix this issue. 

Thanks!
