### ISSUE TITLE
Sync with multiple variations : way too slow, falls back to slow upload for some reason v1.8.7

### ISSUE THREAD

**Issue by theototo** [facebookincubator/facebook-for-woocommerce#451]
Hi, 
I 'am trying to use  facebook for woocommerce plugin on an eshop containing 167 products. The problem is that almost all products have many variations. Some of them have up to 1000 variations. Because of that my products in facebook shop could reach 35,000 or even more.
During the sync process some products (those with not so many variations) are syncing ok. But when it comes to a product with many variations, sync is not working, many errors in variations appear and finally, only a part of total variations are syncing, and with many errors. Also syncing could take many hours and never completes.  
Apart from that, during the sync process, site becomes unresponsive, giving a lot of 504 errors. 
Hosting environment is typical.
WP memory limit:		256 MB
PHP version:		7.2.4
PHP post max size:		8 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.29.0, NSS/3.28.4

So my question is, is it possible to use this plugin in an installation like the one i describe or not. Will it help if i  upgrade my hosting environment? 
Thanks 
Regards.

**Comment by mengyingdu** [comment]
Hi @theototo ,

Facebook feed only accept 30 options per variant, eg 30 colours, 30 sizes. If your products have more than that, it will raise unexpected sync result. Not sure what's the best way fix your problem. I'd suggest you create products with options less than 30.

Thanks.

**Comment by theototo** [comment]
Hi,
Thanks for the quick response. 
My products don't have more than 30 options per variable. Maximum is 15. But a product could have up to 4 variables. This means for example 6x7x8x5 =1680 variants. 
Is this also not acceptable?
Thanks.

**Comment by pabowles** [comment]
I would also like to know if the limit is 30 options per variant or per product as theototo has asked?
Also, is this a limitation of the facebook feed or just this particular plugin?

**Comment by dmitridr** [comment]
Hi,

From your description of product sync It sounds like you are using an older version. In newer versions errors do not appear like you describe (but appear after sync is finished all in one place).

Could you confirm which version you are using? 
v1.8.0 and above should be using the new product sync for which thousands of products would be uploaded relatively quickly. If you are not using such a version, I recommend upgrading (to v1.8.7) and doing a complete reset to get the best results.

AFAIK the Facebook limit is 30 per variant not per product. Will double-check. It's a limitation of the FB feed.

**Comment by theototo** [comment]
Hello Dmitri, 
If you are referring to me, my first attempt was with v1.8.5. . That attempt synced 90 products with approximately 10 variants each. When it came to the next product which has over 800 variants, it stuck for 2 hours and website became unresponsive. 
I tried again with v1.8.7. . I let it sync for 12 hours. It continued from the last product of the previous attempt. After 12 hours the result was to sync 6 more products with a total of approximately 5000 variants. 3 of 6 products synced ok and the other 3 with errors. I mean in facebook shop those 3 products appear with no variants, no price , no buy button only photos and description. 
During those 12  hours  I had to put an under maintenance message in my frontpage, because website was unresponsive. 
From what i am getting, in my installation the only way to have a full sync is to let it run for 3-4 days with website down. Unfortunately this can't be done in a live eshop. 

I think i would be more functional if the syncing process would not consume all available resources from server. It would be slower but it would not  affect so much website's functionality. 

Best regards.

**Comment by dmitridr** [comment]
Hi @theototo,

It seems you are still syncing using the older, very slow, version of product sync. 
This can happen for one of two reasons:

(1) You have not done a full reset (using `Reconfigure > Advanced Options > Delete`) after installing v1.8.7. If not you should do this, upload should be much faster. The whole reason we released 1.8.x was to prevent the issue you have described and address that feedback, so I hope we can fix this for you.

(2) You do not have curl support on wordpress. We use a curl request to upload the product feed in the new version of product sync, but if curl does not exist we have to fall back to the slow version.

Hope that helps. Thank you for the feedback, I think we will make these two steps more clear for users in future versions.

**Comment by mengyingdu** [comment]
@theototo 
Did you still have this problem? 
If you installed curl on your server, you should enable it in your php.ini file. 
https://www.google.com/search?q=enable+curl+wordpress

**Comment by theototo** [comment]
Hi,
My server has curl installed as php extension from the beginning.  I will test it again in a new installation and I ll come back.
Thanks.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by mitchellkrogza** [comment]
30 variations per product? Are you kidding me? Why put such silly restrictions? I cannot go redesign an entire store with 700+ products each with 70+ variations. Programmers astound me frequently, I would have expected this 20 years ago.
