### ISSUE TITLE
[Column Name Too Long] It Breaks Woocommerce product table when activated.

### ISSUE THREAD

**Issue by Less97** [facebookincubator/facebook-for-woocommerce#454]
When I activate it, it breaks the Products table in the backend. Attach the link here:[https://ibb.co/g2TQDn](https://ibb.co/g2TQDn)

Facebook for Woocommerce version: 1.8.5
Wordpress version: 4.9.5
Woocommerce version:  3.3.5

**Comment by sammul** [comment]
Thanks for sharing the feedback. Same report as #455

**Comment by Less97** [comment]
This happens on my mac. I will try on my desktop, if the behaviour changes. Thanks a lot!

**Comment by dmitridr** [comment]
We'll rename it to FBShop and see if it helps.

**Comment by Less97** [comment]
I'll test it tomorrow with the developer toolbar and I'll let you know the
result. Thanks a lot!

Alessandro

2018-05-07 22:52 GMT+01:00 Dmitri Dranishnikov <notifications@github.com>:
