### ISSUE TITLE
[Column Name Too Long] Formating issue in the product list at admin page -- monitor display issue

### ISSUE THREAD

**Issue by alvesjc** [facebookincubator/facebook-for-woocommerce#455]
Hello,

With 1.8.5, product update works, but I still have the product list malformed.

![image](https://user-images.githubusercontent.com/16749630/39525351-a2f86d88-4e13-11e8-8be3-29a9312a9efc.png)

This problem has been consistent with all versions.

Can someone help pinpointing this issue?

I'm using the latest version, 4.9.5 of wordpress

Regards

**Comment by alvesjc** [comment]
Ok, one update.

The issue is related with the screen resolution.

My monitor uses 1440x900, and with the browser at 100% zoom (no zoom), the "facebook shop" word get in that way.

If I reduce the browser zoom to 80%, the problem disappears, but the text continues to not being centered.

This seems to be some issue related to the column format in the product table.

To reproduce the issue from your side, try to increment your browser zoom.

Thanks

**Comment by mengyingdu** [comment]
Hi @alvesjc ,

My monitor is 2560 x 1440.
I can only repo your problems after I zoom more than 150%. To be sincerely honest, I dont think it's a bug for our plugin. But thanks for flagging this. A quick fix can be renamed the column name as shorter as possible. I will discuss with designer and content strategists.

Thanks.

**Comment by dmitridr** [comment]
We're changing the name to `FB Shop` in the next version, which may fix it.

You can edit the name [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.8.7/facebook-commerce.php#L436) in the meantime.

**Comment by vhernandez24** [comment]
The FB Shop column seems to has no with. I could solve it by adding this custom code in functions.php file: 

```
add_action('admin_head', 'my_custom_fonts');

function my_custom_fonts() {
echo '<style>
.column-fb {
width: 11%;
}
</style>';
}
```

Hope this helps. Regards.

**Comment by dmitridr** [comment]
@vhernandez24 That's great!! Please send us a pull request if you can, would love to give you credit for this.
