### ISSUE TITLE
Product Resync Not Working

### ISSUE THREAD

**Issue by ElleJoe** [facebookincubator/facebook-for-woocommerce#460]
Hi, 

I deleted the settings of my store as it was displaying old products that no longer exist. I have reset but the products aren't pulling through anymore.

I am not the person who set it up originally and I don't have access to the Facebook ads account, it created a new pixel when I reset the plugin. Is this why? How can I get the products to pull through to Facebook again?

Thanks!

**Comment by sammul** [comment]
Your facebook page and url please?

It's important to use the pixel and ad account your company use to run facebook ads. So make sure you have access to that before reset

**Comment by dmitridr** [comment]
Hello,

We had issues with products pulling through around the time you made this post. It should have been resolved by now though, have you had any luck?

Regarding the new pixel, yes if you don't have access to the old pixel you will not be able to select it, the plugin does create a pixel for you if there are no pixels available for you to use.

**Comment by dmitridr** [comment]
Closing as there has not been a reply in a while. Feel free to open a new issue if you have more concerns.
