### ISSUE TITLE
We haven't detected the events AddToCart, Purchase, ViewContent coming from your pixel + Catalog Diagnostics

### ISSUE THREAD

**Issue by giulianorapoz** [facebookincubator/facebook-for-woocommerce#461]
Hi, I am using WooCommerce Facebook Plugin to create a category of products in order to enable Instagram product tagging, however I'm getting this Event error from within my Product Catalog Diagnostics.
![debugerror](https://user-images.githubusercontent.com/30539010/39603747-6ef4e19c-4f21-11e8-9c19-bbd763cdc075.PNG)

I have used the Facebook Pixel debugger, however everything seems to be firing correctly, so not sure why the error is triggering. Any Ideas?
I am using version 1.8.7 which I understand has the AJAX add to cart fix.
![pixel](https://user-images.githubusercontent.com/30539010/39604420-01c97508-4f24-11e8-9de1-c003d6c2c643.PNG)

I've had a look at the two other threads here, uninstalled an re-enabled the Woocommerce plugin and the catalog [369](https://github.com/facebookincubator/facebook-for-woocommerce/issues/369) and [219](https://github.com/facebookincubator/facebook-for-woocommerce/issues/219) however, still can't seem to trigger any events. Any help appreciated!

website url: [proteinandpantryshop.azurewebsites.net/strongshop](proteinandpantryshop.azurewebsites.net/strongshop)

Thanks!
Giuliano

**Comment by sammul** [comment]
@giulianorapoz I checked your website that AddToCart indeed can be fired correctly. Do you see events in pixel event tool? https://www.facebook.com/analytics/384109375423903?section=AppEvents

**Comment by giulianorapoz** [comment]
@sammul I see some events in the tool, however on the main dashboard they are 0...if I go into them in more detail it looks like they are firing correctly...unless I am missing something?
![appevents](https://user-images.githubusercontent.com/30539010/39617191-a4e581a8-4f76-11e8-8844-46b24bcf2511.PNG)

Add to cart Event fired twice yesterday:
![addtocartevent](https://user-images.githubusercontent.com/30539010/39617217-b33c1cd0-4f76-11e8-9023-441589e40b97.PNG)

**Comment by aluxh** [comment]
Hi,

I'm facing the same problem, and not sure what I should do. Could you assist?

https://myredlotus.com is the website

**Comment by dmitridr** [comment]
@aluxh @giulianorapoz 

So to clarify the problem, you both see events in the analytics too, but do not see them on the dashboard, is that correct? Could both of you send me links to the analytics tool for your pixel, and main dashboard for your pixel?

I will file a bug report on the team which owns the main dashboard with these links.

**Comment by MarcoLobo** [comment]
Hi,

I'm also having this same problem. Can this error cause an interference in the activation of the Instagram Shopping feature? I've been trying to enable product tagging in my instagram profile for at least 20 days and I can not.

I've made all the settings recommended by Facebook but my Instagram account does not enable product tagging.

I sell only allowed products and my profile has 4 more years of creation. I do not know what else to do!

https://quenembanana.com is my site

**Comment by pps559** [comment]
fix???

**Comment by mengyingdu** [comment]
Hi @jacobabey1 ,

I think your problem is different from the discussion above:  they are able to fire pixel event but have problems in the event tool. Can you open another issue to separate the discussion?

**Comment by mengyingdu** [comment]
For any of you @pps559 @giulianorapoz @pietbrannas @aluxh , like @dmitridr , could you post links to the analytics tool for your pixel, and main dashboard for your pixel?

**Comment by jacobabey1** [comment]
@pps559  @mengyingdu  , the issued had been fixed and currently working fine .
Thanks

**Comment by dripppple** [comment]
@pps559 @mengyingdu @jacobabey1 Same issue with facebook to instagram. How did you fix this?

**Comment by mengyingdu** [comment]
@dripppple The analysis interface is not owned by our team, and we didn't make any changes.

**Comment by aluxh** [comment]
> For any of you @pps559 @giulianorapoz @pietbrannas @aluxh , like @dmitridr said , could you post links to the analytics tool for your pixel, and main dashboard for your pixel?

How can I do that? I've stopped using facebook advertising because of this. But, recently... I'm looking again. But, the size is still not available.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
