### ISSUE TITLE
Product update not working

### ISSUE THREAD

**Issue by priyankagwl123** [facebookincubator/facebook-for-woocommerce#465]
I am using the latest version of "Facebook for WooCommerce" plugin on my WooCommerce website. With the latest version, I am not able to update the product. Please help.

**Comment by priyankagwl123** [comment]
Any update here?

**Comment by mengyingdu** [comment]
Hi @priyankagwl123 ,

Can you follow the support instruction of this repository main page? we need more information in order to help you.

Thanks.

**Comment by dmitridr** [comment]
Hi @priyankagwl123 

As Mengying said, we need more info. Please ensure you have the version 1.8.7 and have done a `Force Resync` if this does not fix your problem, let us know.

**Comment by mengyingdu** [comment]
Hi @priyankagwl123 ,

Still have problems? Any update?

Thanks.

**Comment by dmitridr** [comment]
Closing this as there hasn't been an update from OP. Please open a new issue if there are further concerns.
