### ISSUE TITLE
Remove out-of-stock items, and show the right price

### ISSUE THREAD

**Issue by JesperH95** [facebookincubator/facebook-for-woocommerce#466]
Hello,

I have a few issues with the plugin, and hope you can help or maybe fix this in an update:

I can't remove out-of-stock or private products from the store? I think it at least should be standard to remove private products from the store?

Besides this, there is also an issue with the price after it has been on sale, and it has returned to the normal price. Then the on-sale price is still shown. 

Is there a way to fix this?

**Comment by devakali** [comment]
I have the same problems.

**Comment by dmitridr** [comment]
Hello,

Please make sure you are on the latest version and have done a `Force Resync` after upgrading.

Could you please link us to one product which has such a problem (with the price)? Out of stock products in the shop should be marked out of stock correctly but still visible to the user. If you'd like it to be invisible, you can use the `FB Visibility` setting in the products edit page to mark it as invisible in the shop.

This is similar to #124 so you can take a look at that issue as well.

**Comment by JesperH95** [comment]
Hello,

Thanks for the answer :)

Regarding the visibility, the "Visible" is checked again after I uncheck it and update the product. However, it is possible for me to use the "Delete product(s) on Facebook" to remove it from the catelogue. So that solves this problem for me :)

Regarding the problem with the price, I have just forced resync again, and the plugin is updated - but the problem is still here. An example is the product: https://backpackerlife.dk/produkt/expedition-65-liter/ which can be found on our facebook catelogue page: https://www.facebook.com/commerce/products/1691293414275684/

**Comment by JesperH95** [comment]
If I click "Delete product(s) on Facebook", and then update the product again, then it shows the right price again. But when I then input a sale price, update, and then remove the sales price again, then the sales price will still be shown.

So, it is possible for me to get around this by clicking "Delete product(s) on Facebook" after I have removed the sales price. And the update again. But it would offcourse by a lot less work, if it could be done easier than this.

**Comment by dmitridr** [comment]
Hey, I checked your shop, it seems you have version 1.4.5 of our plugin, this is a very ancient version! We did indeed have sale price bugs and visibility not working in older versions, we've fixed 100 bugs easily since then.

Most likely this old version is the cause of all the problems you see. I recommend upgrading to 1.8.7 then do a `Force Resync`, which should fix the sale issue at least. 

But there may be other problems, because there have been many breaking changes between 1.4.5 and 1.8.7... if you experience further issues, I recommend doing a full reset of the plugin via `Reconfigure > Advanced Options > Delete` and doing the setup again, there should not be any issues after doing this. 

Hope that helps!

**Comment by dmitridr** [comment]
You can find our latest versions here. 
https://github.com/facebookincubator/facebook-for-woocommerce/releases

We added a wordpress notice in 1.7.x which should be visibile on the plugin page and tell you when a new version is available.

**Comment by JesperH95** [comment]
OK, thanks a lot! I thought it was enough to check the wordpress-update page for updates. But it sounds great that it will be coming soon 👍

**Comment by dmitridr** [comment]
Great. I assume you've upgraded and things work now? If not, please open a new issue on us if you keep encountering this problem (or have some others).

**Comment by JesperH95** [comment]
Yeah it works now, thank you very much for the help! :)
