### ISSUE TITLE
WPML : Issues with images, Hide/Show functionality and URLs

### ISSUE THREAD

**Issue by poxolo** [facebookincubator/facebook-for-woocommerce#467]
- Symptoms of your problem: 
1.- Product images not uploaded properly (on Facebook shop only the main image has been uploaded and on the BM catalog it uploads the same image 3 times, whether it has only 1 image or any amount of different ones). 
2.- Also, we have products in multiple languages through WooCommerce Multilingual and WPML Multilingual CMS plugins and, in the Facebook page the products marked for sale don't match with the ones selected to "Show" in Products.
3.- The URLs of each language of the product are created through the multilingual plugins and, even though each product in each language has the right permalink in the product section, for some reason this facebook plugin doesn't pull the language part of the URL ("/en/" or "/es/"), but it does pull the rest of the URL when it's different between languages (from "/en/product/productname" and "/es/producto/productname" it pulls "product" and "producto" but it doesn't pull "es" or "en").
4.- In the Facebook shop the URLs pulled are for adding to the cart straight away (in the product catalog the URLs are the product pages). I don't know if this is working as intended, but I think the URLs of the shop should lead to the product page, not to the cart with the product added already.
- Screen shot if possible: You can see everything in the facebook page and the website.
- Your Facebook page url: https://www.facebook.com/cocosielife/
- Your website url: https://cocosie.com/
- Current version of Facebook-for-WooCommerce(1.8.7), WooCommerce(3.2.6), Wordpress(4.9.3), PHP (7.1.12).

**Comment by dmitridr** [comment]
Hello.

(1) Are there other images that are not uploading correctly, gallery images? BM should show the same image X times where X is the number of variants, if you do not have variant specific images. This is normal, because each variant maps to 1 product in FB.
(2) Could you give an example of a product marked for sale that doesn't match the one on the site? I'm not sure I completely understand this.
(3) Thanks for reporting this, it appears to be the same issue as in #367 ?
(4) There is a setting to change this in the settings of the shop. Look for the gear icon #378 has details.

We'll keep this open and update about the URL issue if there's a resolution.

**Comment by poxolo** [comment]
Hi,

1.- They are not product variants, but different photos of the same product, and they are not getting uploaded in the Facebook Page Shop (only one uploaded). As for the BM Catalog, it's taking as variants the other languages, but the other languages are also being uploaded as different products. So one product has 3 languages, and in the catalog it's uploaded 3 times (as it should, even while there's still the issue 3) and each of those 3 has 3 identical photos. So total 9 identical photos between 3 products.
2.- Right now every single product is marked for sale (they all show the "Hide" button) and I've resynced and even reinstalled the plugin and resynced again, and the Facebook shop uploads all the products (in all 3 languages), but still only puts for sale the versions in one language. And, even if I hide the versions that currently show up for sale (in an attempt to make the other language ones to change status), and resync, nothing changes, the same language versions show up for sale and the rest don't.
3.- It is.
4.- Thanks, hadn't seen that one.

As for points 1 and 2, it seems there's some incompatibility between the way WPML creates multilingual products and the way the plugin flags a product as a variant.

**Comment by dmitridr** [comment]
Thanks for the response. I have a better idea of the problem. Some more clarifying questions around (1)-(2) :

(1) I get this now. We do upload all the languages, though some are hidden from the shop, the visibility can be controlled in WPML settings. #279 has details. How are you storing these different photos for each product? Is it through another plugin? I am not aware of additional product images aside from the `Primary Image` and `Gallery Images` provided by WooCommerce.
(2) Could you provide links to products of both cases you describe? That will help us understand the problem.
(3) Thanks for confirming.
(4) Glad I could help.

**Comment by poxolo** [comment]
Hi,

1.- Correct. It's the same issue and I see that it's working as intended because other people complained about duplicate products. The thing is that our main language in wordpress and woocommerce products is dutch, since it was our first market, and now we need the English versions to be uploaded to Facebook for a more international approach. Isn't there any way to create a toggle in the settings where we decide which products do we want to sell?
About the images, they are assigned to products through a custom field group with a repeater field type and a child gallery field type for each image.
2.- After reading #279 I understand that both issues 1 and 2 are related to the same thing. The functionality that hides all products not uploaded in the default language is what's overriding the manual Show/Hide settings on my products. 

If there's some way for me to decide if I want only products in the default language or to use the Show/Hide button in the product tab to manually select which products to show would fix both issues 1 and 2, except the part with the photos, which is due to the gallery being linked to each product through custom field groups and not the WooCommerce gallery.

**Comment by mengyingdu** [comment]
Hi @poxolo ,

 Unfortunately, currently we don't  have this toggle now and we may consider it based on user demand. But I could say, English is more internal and also most of browser support instant translation now. So I wouldn't worry it too much.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
