### ISSUE TITLE
[SOLVED] Facebook product synchronisation not working

### ISSUE THREAD

**Issue by devakali** [facebookincubator/facebook-for-woocommerce#468]
**Symptoms of your problem:**
1. Products are not synched properly to my Facebook store.
2. Only about 40% of my products are synched to store and it's not possible to synch the other ones. either through force re-sync or manually updating each product. Somehow one new product was added on my first resynch. I have not been able to replicate this.
   
You can see everything in the facebook page and the website.
FB page url: https://www.facebook.com/yogistylesweden/
Website url: https://www.yogistyle.se/
Current versions: Facebook-for-WooCommerce(1.8.7), WooCommerce(3.2.6), Wordpress(4.9.5), PHP (7.0.30).

**Comment by auludag** [comment]
I have this problem as well. just spinning on the WooCommerce page without no improvement

**Comment by poxolo** [comment]
Have you checked in the wordpress products tab if each product is marked to show? If they are marked to show you'll have a button to "Hide", and viceversa.

**Comment by auludag** [comment]
for my case, i downgraded version to 1.7.3 then synced it. but for first initial sync, it is not syncing.

**Comment by devakali** [comment]
They are all marked as visible except the out of stock items.

**Comment by devakali** [comment]
The solution to this was to select reconfigure settings on the FB integration page in WC settings, going to advanced and selecting remove. Then I redid the setup process and now it syncs and works fine!

I was using an older version before, updated to the new one and still had the same problem, so if you have done the same just redo the FB shop connection setup.

**Comment by dmitridr** [comment]
Glad you were able to solve this!
