### ISSUE TITLE
Problem from the get started

### ISSUE THREAD

**Issue by pacificao** [facebookincubator/facebook-for-woocommerce#47]
When I click on the Get Started button I get routed to Facebook and the page says

“Sorry, something went wrong.
We are working on it and we'll get it fixed as soon as we can.”

It has been the same error for the last two days on a clean install, any ideas?

**Comment by pacificao** [comment]
![659d5741-aaec-4e80-89ac-46bf3e22344d](https://user-images.githubusercontent.com/29243681/30720488-881413e6-9edc-11e7-947c-14ddbd7829ca.png)

**Comment by pacificao** [comment]
Version 1.5.1

Woocommerce and Facebook for WooCommerce are the only two plugins.

**Comment by dmitridr** [comment]
Oh are you trying this on Mobile? We don't support mobile yet, though we have a team working on that. 
It should work on Desktop or Laptop.

**Comment by dmitridr** [comment]
I'm closing this, the recommended resolution here is to do the initial setup of the extension on a Laptop/Desktop. 

Basic management of the shop and the WooCommerce side can still be done on Mobile afterward.
