### ISSUE TITLE
[Shop Bug] The price is 100x on the first page of iOS

### ISSUE THREAD

**Issue by ateliershen** [facebookincubator/facebook-for-woocommerce#470]
Hi,

I found that the price is 100x on the first page of iOS APP.

Please take a look for this:
iOS: 
![s__4784199](https://user-images.githubusercontent.com/30176935/39737065-c4f2a894-52b5-11e8-956f-9fcbb3d1ef90.jpg)

Android:
![60304](https://user-images.githubusercontent.com/30176935/39737078-d268b04a-52b5-11e8-9503-cc82fc0c4685.jpg)

Web:
![2018-05-08 11 50 54](https://user-images.githubusercontent.com/30176935/39737120-162fe50a-52b6-11e8-813a-f91bdcdc74dc.jpg)

ps. 
I have another site encountering the same issue. Resync does not solve this problem. Please help me out of this 🙏

The link of my page is https://www.facebook.com/yaoindia

**Comment by dmitridr** [comment]
That's messed up! Thanks for reporting, I've forwarded this bug to the shops team. Will update when there is resolution.

**Comment by ateliershen** [comment]
@dmitridr 

Thank you! But it's getting even worse... all the products on iOS App is 100x the price now...😭

Is there anything I can do?

**Comment by ateliershen** [comment]
@dmitridr 

The issue seems to be fixed. Thank you.
