### ISSUE TITLE
Can't edit pixel data in Facebook for Woo commerce 

### ISSUE THREAD

**Issue by benjiman04** [facebookincubator/facebook-for-woocommerce#471]
I need to delete the data from our plug in and re set up under a new pixel and ad account, but have been getting this error all day today when clicking on Advanced and delete settings. 

"Sorry, something went wrong. This might be a temporary issue and we're working to get it fixed as soon as we can. Please try again later."
<img width="899" alt="screen shot 2018-05-08 at 4 57 24 pm" src="https://user-images.githubusercontent.com/39080049/39742511-159ebbb8-52e1-11e8-8d89-0776e69dff65.png">

**Comment by dmitridr** [comment]
Hi,

That error should only happen if you don't have permission to delete the settings. 

Are you the same person who set up the plugin? 
In general you must be an administrator on the associated page with at least permissions of level create content. If you are not, you will not be able to change the settings.

If you are, please send us the page id or some other information so we can dig deeper into why you can't delete the settings.

BTW, you can change the pixel using the `Facebook pixel` step. Have you tried that? It may be easier than deleting settings.

**Comment by benjiman04** [comment]
I have tried that but I get a different error. 

I think I see the issue now. 

I’m an admin of the page personally but on Business Manager I’m just an advertiser so have changed that and it’s allowed me to fix. 

Thank you!


Ben Whitmore <mailto:ben@lemontreemarketing.com.au> • Senior Marketing Manager
P: 07 5576 7841 <tel:0755767841>
M: 0468 642 246 <tel:0468642246>
3/37 Connor St, Burleigh Heads 4220 <https://www.google.com.au/maps/dir/''/lemon+tree+marketing/data=!4m5!4m4!1m0!1m2!1m1!1s0x6b910382329ec78f:0x289d7a87fb7039dd?sa=X&ved=0ahUKEwio5LDcqNDUAhVCXrwKHbNtCq0Q9RcIeDAO>
www.lemontreemarketing.com.au <http://lemontreemarketing.com.au/>
  <https://www.facebook.com/Lemontreemarketing>  <http://instagram.com/lemontreemarketing> <https://twitter.com/Lemontreemktg>  <https://www.linkedin.com/company/lemon-tree-marketing>		 <http://lemontreemarketing.com.au/>

**Comment by dmitridr** [comment]
Great, glad it helped!!
