### ISSUE TITLE
[Feature Request] option to not sync variants

### ISSUE THREAD

**Issue by jemmille** [facebookincubator/facebook-for-woocommerce#476]
The short version:

I'd love to just have an option to not sync variants or to select which variants are synced.

The long version:

My products have multiple sizes (and often colors).  The problem I have it not with the sync but rather catalog is builds and how that translates to tagging products on instagram.  

When you use this plugin to build your catalog it adds each variation to the catalog.  If the product has  3 sizes, i end up with 4 "products" in my catalog (all with the same picture because it's the same shirt or dress, just different sizes).  That is all fine and well but if you link that catalog to Instagram then try to tag a product, your list of products shows the same image 4 times per product.  If you have 100 items in your catalog that's up to 400 images to scroll through.  

I'd love to just have an option to not sync variants or to select which variants are synced.

**Comment by sammul** [comment]
Thanks for sharing the feedback. We added the variants because a lot of people requested that feature. I don't have much experience in instagram tagging, but would it help if the tagging allows you to search a product?

**Comment by mengyingdu** [comment]
Thanks for the screenshot to clarify! @jemmille 

It seems to be sth we need to consider after we integrated with IG fully launched? It may raise more concerns at that time. @dmitridr

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
