### ISSUE TITLE
[Product Missing in Shop] Product not appearing on Facebook Shop, but already uploaded to catalog

### ISSUE THREAD

**Issue by amgdre** [facebookincubator/facebook-for-woocommerce#477]
Hello!

I already synced my products and almost all of them is appearing on Facebook Shop. There is just one product synced but not appearing on the shop.
The product: 
https://positiva.eco.br/produto/trio-1l/
Facebbok Shop:
https://www.facebook.com/pg/positivaconsultoriapermacultura/shop/?rid=416385561873029&rt=6

PS. I already force resync with no success with this specific product...

Thank you very much.

**Comment by sammul** [comment]
The product is already uploaded to Facebook catalog: https://www.facebook.com/products/catalogs/205461950263714/products
This is likely a shop issue, we can try to help you report on this to the shop team. We have received similar complaints

**Comment by amgdre** [comment]
Hello Sammul. Thanks!
Is there an action for me to take right now?

**Comment by mengyingdu** [comment]
The shop bug has been fixed and your shop is filled with products now.
