### ISSUE TITLE
Products don't sync at all

### ISSUE THREAD

**Issue by jgomola** [facebookincubator/facebook-for-woocommerce#478]
Hi,

After installing plugin and configuration, catalog appears in catalog manager, but products don't upload. Not even after forced re-sync.  In products, column Facebook shop shows status Not synced, but button is also missing. I could not find an exact issue, so I am creating a new one.

Thank you for help.

Jiri

**Comment by redasaiko** [comment]
Hello,

I am strugglimg with exactly the same issue, nothing helps : resync, deleteing the plugins, deleting settings...

I have the 1.8.7 verison and everything in wp and wc is up to date,

Thanky ou for your help.

**Comment by sammul** [comment]
@jgomola @redasaiko please share the link to your catalog in catalog manager thanks

**Comment by redasaiko** [comment]
Hello,

for me it's solved, I just added my business account on the catalog.

Hope it helps.

**Comment by dmitridr** [comment]
Closing as it has been a while since there has been a reply. @jgomola please open a new issue with the information requested by @sammul if you are still having this problem. We cannot check our own internal logs to see what happened unless we have your shop information.
