### ISSUE TITLE
Taken to blank page when trying to finish configuring the extension 

### ISSUE THREAD

**Issue by natem** [facebookincubator/facebook-for-woocommerce#483]
I've added the plugin and when I click on complete the setup steps link I am taken to a blank page with the url mywebsite.com/wp-admin//admin.php?page=wc-settings&tab=integration&section=facebookcommerce.  Disclaimer I am using an older version of WooCommerce (2.4.7).

**Comment by mengyingdu** [comment]
Did you activate the plugin before redirecting to that page?
