### ISSUE TITLE
[GDPR]Disable Tracking Pixel but leave sync-on

### ISSUE THREAD

**Issue by sanderkie** [facebookincubator/facebook-for-woocommerce#499]
Hello,

with the new GDPR coming into effect I would like to keep the product-sync on; but turn the Facebook Pixel off.
Is there any way to do that with the plugin?
As of now my only solution seems to simply disable the complete plugin.

**Comment by mengyingdu** [comment]
Hi @sanderkie ,

Regarding legal concerns, see the image I posted earlier of the pixel step, which links to this page. I think our GDPR policy, www.facebook.com/business/GDPR, has also been updated.

As discussed in #301 , that filter can be used to build your own opt-in solutions, but we will not be taking action on this to implement opt-in behavior. However, we welcome your pull requests if you need additional filters/features to facilitate building those solutions.

I would also look into using PixelYourSite which is compatible with our plugin, they may have an opt-in solution, and they do use the above filter.

**Comment by sanderkie** [comment]
Hello,

what I would like is to disable the pixel, but leave the sync .
Is this possible with the plugin?

**Comment by dmitridr** [comment]
@sanderkie Yes, but you must modify the plugin code using the WP editor, the modification is simple though. Please see the comment in #301 by @addedlovely about the filter, that line of code can be inserted anywhere within the plugin. If you have further questions, please comment in that issue, we'd like to keep all discussion about GDPR in one place.
