### ISSUE TITLE
Deleted Products Show Up on FB + Product appears on FB Shop without Picture

### ISSUE THREAD

**Issue by ShopVeraVeraCollection** [facebookincubator/facebook-for-woocommerce#509]
Hi!
I made resync of the products.I have another question. I deleted some products from my site, but they are still on my facebook shop. Don't know how to delete them, as there is no option hide, as they are deleted.
and One of my products appears on facebook shop without picture, however I made resync before.

Thank you.

**Comment by mengyingdu** [comment]
@ShopVeraVeraCollection 
1. It depends on how you delete your products.
2. product url? (both fb and your shop)
