### ISSUE TITLE
Issue with all products syncing.

### ISSUE THREAD

**Issue by rburnett3** [facebookincubator/facebook-for-woocommerce#52]
I installed the plugin last week on our ecom store, it managed to pull many of our products and prices.  The products that did get pulled and the price that didn't get pulled are my issue.  
![-ref page_internal 2](https://user-images.githubusercontent.com/32270839/30815441-39303e14-a1e1-11e7-9641-5bb3bf9b379e.jpg)

**Comment by dmitridr** [comment]
Hello,

Could you give us some more details?
- Are all of the products 0.00 or just some?
- Is there anything special about the 0.00 products that we can use to determine the cause?

Also:
- Which version are you using? v1.6.0 should have some price-related fixes.

Seems like this is related to #50

**Comment by rburnett3** [comment]
Just some of the products are 0.00. About half,.
There is nothing specifically different between these listings.
How would I be able to tell which version I'm using?

**Comment by rburnett3** [comment]
I've updated the plugin to v1.6.0 and tried to push the products into the store with no luck getting all of the products synced.

**Comment by dmitridr** [comment]
Hello again,

We still can't reproduce this problem, could you perhaps send us a screenshot of the configuration for one of these products that has price 0.00? In particular, the settings on the price page interest us. Also, could you tell us if you have any price-related extensions that may be conflicting or might cause such behavior?

**Comment by dmitridr** [comment]
Hello,

If you try our new version, [v1.6.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases) and Force Resync, it should mark the existing 0$ products as invisible in the shop, and new products with price $0 will not be uploaded to FB.

**Comment by mengyingdu** [comment]
Hi,
Since we didn't hear back any more update about this and new version should work now. Close issue.
