### ISSUE TITLE
Can't select pixels without attached ad account.

### ISSUE THREAD

**Issue by f3bruary** [facebookincubator/facebook-for-woocommerce#521]
I'm working on a client's site who doesn't have an ad account yet. I created a pixel for him in my business manager account (I have 2). I can select the right page, but then it asks for the pixel and I don't see it.

I got 2 business manager account. One for me and my own business, and another for other people's businesses. The page selection drop-down shows all the pages across the 2 account.

But the pixel selection drop-down only seems to show Pixel's from 1 (my own) business account.

Therefore I cannot seem to select the client's pixel that I've created.

**Comment by f3bruary** [comment]
WordPress: 4.9.6
WooCommerce: 3.4.1
Plugin: 1.8.7

Screenshot:
![image](https://user-images.githubusercontent.com/5641933/40872849-f226c512-6655-11e8-879e-e46e289b40dd.png)

Steps to reproduce:
1. Get Started
2. Next
3: Pick Page (Note: All my pages appears here, from both my Business Manager Accounts)
4. Pick Pixel (Note: Just some of my Pixels appear here. From the looks, just from 1 account)

I'd also like to mention that the Pixel I'm trying to pick doesn't have an ad account yet. But I see no reason why that should matter at this stage (development).

Debug Ready

**Comment by dmitridr** [comment]
Hi,

Thanks for your interest in our plugin! 

As you noticed, our plugin doesn't support pixels that are not attached to an ad account. If you wish to use such a pixel, I recommend attaching it to an ad account (and then de-attaching afterward, if needed), as a workaround.

We plan to support pixels without attached ad-accounts in the future and it is on our roadmap to do before the end of the year, but this will not happen immediately. I am marking this as a feature request.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
