### ISSUE TITLE
Woocommerce unlink facebook page and products

### ISSUE THREAD

**Issue by margar1n** [facebookincubator/facebook-for-woocommerce#522]
Hi! 
I link my Woo and FB Page. All products are automatically exported to facebook page. 
But all products descriptions with WPBakery code or HTML code. Check screenshot pls:
1) http://prntscr.com/jpso8a
2) http://prntscr.com/jpsokw
3 http://prntscr.com/jpsqxp

Please explain how I can unlink FB and Woo ?
Or how I can delete all products from FB page ? I don`t see EDIT button in FB.

**Info:**
1) web site address: http://pickaplace.com.au
2) FBPage URL https://business.facebook.com/pg/Pick-a-place-1677767105670976/shop/?ref=page_internal
3) WordPress version 4.9.6
4)  WooCommerce version number 3.4.1
5) Facebook Plugin version number? I don`t know. Installed and downloaded May 27, 2018.
6) How many products you have? 21 items 
7) Types of products  - No any variations. Simple products. Scratch off maps and posters.
8) Do you have Duplicate SKUs in your system? - I don`t know. I think no!

Thanks! 

<img width="916" alt="2018-06-02 13 04 06" src="https://user-images.githubusercontent.com/39820343/40870035-7dc19ade-6665-11e8-9d84-501a43b567bd.png">
<img width="1271" alt="2018-06-02 13 03 53" src="https://user-images.githubusercontent.com/39820343/40870036-7e1c0622-6665-11e8-8f7b-4bd03477111f.png">
<img width="921" alt="2018-05-30 13 45 41" src="https://user-images.githubusercontent.com/39820343/40870037-7e5ae036-6665-11e8-973e-99700c6114b8.png">
<img width="921" alt="2018-06-02 13 04 16" src="https://user-images.githubusercontent.com/39820343/40870038-7eb4d3a2-6665-11e8-9849-e43d7fdac081.png">

**Comment by margar1n** [comment]
@FlairTrade @mengyingdu, @sammul, @jieminz22, @dmitridr

**Comment by FlairTrade** [comment]
@margar1n I'd help if I could but not sure what is going on here.

**Comment by margar1n** [comment]
@FlairTrade My English is not enough? Need more details or what?

**Comment by FlairTrade** [comment]
@margar1n sorry no help

**Comment by margar1n** [comment]
@FlairTrade WHo can help me?

**Comment by sammul** [comment]
@margar1n If you want to delete, you can launch our extension, and go to settings and delete everything. If you only want to delete the product catalog, you can go to www.facebook.com/products to find the catalog and delete it

**Comment by margar1n** [comment]
Thank you! I solve my problem!
