### ISSUE TITLE
After Sync, Added Products Variation Not Availabe

### ISSUE THREAD

**Issue by bbihun12** [facebookincubator/facebook-for-woocommerce#524]
When using the plugin syncing products from Woocommerce and setting up Collections does the "Add Product" go away on the shop page. 

I don't see how to manually add products or edit products now after syncing from WooCommerce to my shop page

**Comment by margar1n** [comment]
I have the same problem!

**Comment by dmitridr** [comment]
Hi,

Yes the plugin does not support manually adding or editing products without adding them to Woo, and the shops UI does not have any way to do this.

You can however add products manually by uploading another product feed into your WooCommerce product catalog, available at `www.facebook.com/products`. Products added there should appear in the shop.

You can edit existing products in a similar way, but the process is much more difficult, and I don't advise doing this. As soon as you edit the product again on the WooCommerce side, any edits you make will be overwritten by sync into FB...

If there are fields that you wish to change, I advise using our filter to change these fields programatically. #547 has an example of how to do this and remove some junk from the description fields. Hope that helps.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
