### ISSUE TITLE
Products display Error

### ISSUE THREAD

**Issue by Yunislav** [facebookincubator/facebook-for-woocommerce#532]
When the extension is enabled, the products on wooCommerce are not displayed properly.
<img width="1116" alt="screenshot 2018-06-05 19 51 29" src="https://user-images.githubusercontent.com/12301590/41061224-28aeb534-69d2-11e8-9c6d-ef453c777f67.png">

**Comment by mengyingdu** [comment]
Hi @Yunislav ,

We fixed the UI display error in [v1.9.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.9.0)
