### ISSUE TITLE
Can't exclude products from displaying

### ISSUE THREAD

**Issue by Caitlinvdv** [facebookincubator/facebook-for-woocommerce#54]
Hi!

I can't seem to find how to exclude some products from displaying on Facebook. Free products that are created in the shop and are hidden, shouldn't be showed on Facebook neither. How can I fix this?

Thanks in advance!

**Comment by dmitridr** [comment]
Hello,

Thanks for writing in.
To exclude products : If you are using 1.6.0 or above, you should be able to uncheck the 'Visible' option under the 'Facebook' section of the product edit page as described in issue #37.

We should have fixed hidden products not showing in v1.6.0 in #19, If you're still seeing the problem, can you confirm that you are using the new version?

**Comment by dmitridr** [comment]
I'm closing this, please re-open if the suggested fix (upgrading to 1.6.x and using the 'Visible' toggle) does not work for you.

**Comment by jb510** [comment]
I know this is ancient, but it's still a problem.

The "Visible" toggle does not work for me.  There are lots of products that I do not want showing up in my Catalog, but I do need showing up in WooCommerce.
