### ISSUE TITLE
error when changing password facebook page

### ISSUE THREAD

**Issue by jfernando1599** [facebookincubator/facebook-for-woocommerce#55]
![facebookstore](https://user-images.githubusercontent.com/32281573/30835082-b1c3f8b6-a22c-11e7-818c-79bce16d8063.JPG)
I changed the password of my page and the plugin says that I have to change the password of it .Oplkugin does not allow me access to change

I'm logged in as a facebook page administrator. what to do ?

**Comment by dmitridr** [comment]
Hello,

That looks like an older version of our plugin. Could you try upgrading to 1.6.1?

Generally if you reset your password, you will have to reset the FB integration, this is a limitation we're working on addressing in the near future.

**Comment by jfernando1599** [comment]
I am using version 1.4.1 does not appear update to do in the panel of
plugins wordpress.How do I update the plugin?

**Comment by dmitridr** [comment]
Our latest release will always be here available as a zip file :

https://github.com/facebookincubator/facebook-for-woocommerce/releases

Currently it's 1.6.1. You'll have to uninstall your older version and install this new one. Once you do that, you should see a different message about how to resolve your issue...

**Comment by dmitridr** [comment]
I am closing this for now, but please re-open if you have further issues.
As I said above, we are working on a better way for you to reset the token that does not involve resetting everything, but that is not ready yet.
