### ISSUE TITLE
Update product feed automatically

### ISSUE THREAD

**Issue by Dedagroup** [facebookincubator/facebook-for-woocommerce#554]
Hi,

i was trying to see if i could make facebook auto update my product feed, but i can't seem to find out how as I don't know where the feed link is when i'm using this plugin.

How do I do this? :)

**Comment by jieminz22** [comment]
Hi Dedagroup,

This plugin doesn't generate a feed file with link, but we sync your products through API. 

If you update your products through WooCommerce UI, Facebook will get the update automatically. If you update your products through all other ways, you will need to click "Sync Products" button to force a resync. 

Let me know if that helps.

**Comment by dmitridr** [comment]
Hi,

if you merely want functionality to auto resync the products on some set schedule, there is already an open feature request in #542, would encourage you to check out that issue and see if it's what you are requesting as well!

As Jiemin said, we sync products through API, though a feed file is generated to simplify this process (we upload the file to FB via API), it is immediately deleted after creation in [this line of code](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproductfeed.php#L75). If you really want this feed file, you can try removing this line of code, then the file should appear on your server. You can create a symlink in a public directory to make this file externally visible if you need to use it.

**Comment by dmitridr** [comment]
I'm pleased to report that we have built the functionality as of v1.9.8 of the plugin. Please see the releases page and check it out. Issue #542 has more details.

**Comment by Dedagroup** [comment]
Great!
I see that it is an advanced setting, but i can't find the tickbox under advanced settings? how do i enable this new function? :)
