### ISSUE TITLE
Custom Labels sync

### ISSUE THREAD

**Issue by jaykishan-utwani** [facebookincubator/facebook-for-woocommerce#555]
The FB advertising platform provides provision to push custom fields - Check Link (https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog/) like custom_label_0 and so on and so forth? So how can we configure the plugin to push certain other fields like Suburb, Camp Dates, Venue Name etc through to Facebook?

Do you have any idea on that? Is this time taking exercise?

**Comment by mengyingdu** [comment]
Unfortunately, this is not currently supported. But there are some workaround for you if you want to play around and make it yourself.

1. add the column you want by using this [filter](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproduct.php#L498-L501)
2. You need to override the feed format [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproductfeed.php#L138)
3. Add the column [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproductfeed.php#L231-L252)

It can be a lot of work and depends your development experience. My instructions can't cover each line you need to change, but i think it's possible. @jaykishan-utwani

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by Mte90** [comment]
I confirm that that feature is missing is not mentioned in the documentation as example: https://docs.woocommerce.com/document/facebook-for-woocommerce/
