### ISSUE TITLE
These additions would make life much easier : Short Description & Default Variation

### ISSUE THREAD

**Issue by TimeFreezerPhotography** [facebookincubator/facebook-for-woocommerce#56]
I've been running the woocommerce for facebook plugin for a while now and
have noticed a few things that would be handy.  I've noticed you've added
a Facebook tab in the product data field which allows you to add a
separate description for your facebook shop.  That's great! however I have
166 products already on there and they're using the general description
(annoying because I'd rather they used the "short" description) Is there
any snippet that I could add that would prepopulate that facebook
description field with the 'short' description?  I can't face adding a new
description to all my products.

Secondly, is there a snippet that would allow the selected default product
variation to be the default variation on facebook.  I've noticed that at
present it uses the last variation you enter which in my case is often the
most expensive and I think is putting people off clicking.  It would be
much more useful if it used the default
variation.

My website is www.timnefreezer.co.uk and my facebook page is
www.facebook.com/TimeFreezerPhotography I'm running the latest version of
wordpress and the woocommerce for facebook plugin.

**Comment by dmitridr** [comment]
Hello,

Thanks for writing in. These are both excellent suggestions.

For the first suggestion I'm thinking we can export the short description into FB and surface a toggle in the settings to allow you to display the short or long description. Alternatively we could put a toggle on WooCommerce somewhere...

For the second suggestion, that seems like something we might be able to quickly fix by uploading the default variation last.

We like to prioritize additional features based on demand, so the more people want these, the faster we'll get to them, though right now we're working on some bugs.

**Comment by silksow** [comment]
There have been several reports now regarding problems with variable products. Here's a video that demonstrates a few of them. Shown first is what I believe to be the correct/default FB shop behavior, followed by FB for WooCom plugin 1.6.1.

![fb for woocom variable product correct-incorrect](https://user-images.githubusercontent.com/30702576/30944600-dbb70e92-a3ad-11e7-977c-d23644db0660.gif)

**Comment by dmitridr** [comment]
Thanks for the video! That does look pretty bad, we'll be sure to address this, at least the most obvious issue of the thumbnail not being selected & the default variant, I recall you posted about this before.

For the record, the more people that comment here that want this issue addressed, the higher we will prioritize it.

**Comment by silksow** [comment]
More details in issue #8

**Comment by silksow** [comment]
These are very serious issues, @dmitridr - I just discovered that the variant issue is reflected on the FB product catalog level, resulting in the default variant image being used (zoomed and cropped in a couple cases???) in DPAs. Very _expensive_ DPAs. 
**FB Product catalog variations**
![fb to woocom variant image](https://user-images.githubusercontent.com/30702576/30990698-1a8be1c0-a457-11e7-9bb2-d321a23c0abe.jpg)
![fb to woocom variant image 2](https://user-images.githubusercontent.com/30702576/30990532-87aa1cf0-a456-11e7-9191-7aa4cbf0331d.jpg)

**Comment by dmitridr** [comment]
The zoom and crop settings should be controllable via catalog manager in regards to how products appear in ads. 

Regarding the primary image, we've had complaints in the past of the opposite variety : that the variant specific image was being used as the primary image, but the default one was higher quality and better for ads, which is why we switched to using that. It seems your issue is the opposite, so the only solution here that will make everyone happy seems to be a toggle or setting on which image will be used as the primary image.

**Comment by mengyingdu** [comment]
Thanks for your interest and suggestion for our extension. "Default variation" will be supported in our next release.

**Comment by TimeFreezerPhotography** [comment]
That's excellent thanks

What about the description toggle?

**Comment by mengyingdu** [comment]
We will look into it in the future based on priority of new features. Thanks for your suggestion.

**Comment by oococc** [comment]
+1 default variations
"For the second suggestion, that seems like something we might be able to quickly fix by uploading the default variation last."

Please include the fix in the next release, it would be a game changer for our store.

**Comment by dmitridr** [comment]
@mengyingdu added Default Variants into [v1.6.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases) which is now out. Please try it and 'Force Resync' to get the updated default ordering.

I'll work on the 'toggle' to determine which FB image is set to primary within the variants. So keeping this issue open for that.

**Comment by dmitridr** [comment]
@TimeFreezerPhotography we do have a code snippet for you for the automatic use of short description, if you're still interested.

If you can edit the plugin in the editor, look for the file `fbproduct.php` and look for the line

https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproduct.php#L202
  
And delete the 3 lines of code.

```
    if ($post_content) {
      $description = $post_content;
    }
```

Then save and force resync. This should switch all simple products from using the description to using the short description. Unfortunately, it won't work for variable products and variants.

**Comment by dmitridr** [comment]
[v1.6.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases) is out, and fixes the longstanding issue mentioned by @silksow which has been around since 1.5.0. 

The variant-specific image is now the primary image by default, but this behavior can be changed through the use of a new checkbox for specific products. Checking the box will use the parent (variable product) image that is uploaded in the right hand side, as the default image for all variants both in the shop and in ads.

<img width="522" alt="variableproduct_useparentimage" src="https://user-images.githubusercontent.com/29133800/31525570-0a01b102-af76-11e7-98e0-6da6bb5808f6.png">

Please Install the new version and Force Resync to see the effects.
