### ISSUE TITLE
Resync make website down

### ISSUE THREAD

**Issue by gchterry** [facebookincubator/facebook-for-woocommerce#58]
When i do force product resync, my website is not allow access by visitor
How much memory or network usage will be use for resync?
Why so heavy duty?
How can we check & solve this problem?
I'm using Wordpress 4.7.5, Woocommerce 3.0.8, Facebook for Woocommerce 1.6.1, dedicated server

**Comment by dmitridr** [comment]
It depends on how many products you have, but yes the upload is fairly slow, we are aware of the issue but thank you for calling this out.

Force resync should not take down your website though, I am not sure why this occurs, but you should not need to 'force resync' often unless there is some other bug?

**Comment by mengyingdu** [comment]
Hi @gchterry ,

Can you tell me your shop url ?or facebook page id? So we can check your logging.

Thanks!

**Comment by mengyingdu** [comment]
Hi @gchterry I closed it for now since haven't got back any information from you. Let me know if you still have this problem so we can re-open it. Thanks!
