### ISSUE TITLE
Size and color of some products don't show

### ISSUE THREAD

**Issue by bojochris** [facebookincubator/facebook-for-woocommerce#59]
The size and color of some products on FB shop don't show. It just says "Any size/Any color" while the product is ok on woocommerce shop.

Why is that? How can i fix this?
![2017-09-27 14_42_32-bojo boutique - shop](https://user-images.githubusercontent.com/32329780/30911660-2fed0e6a-a392-11e7-92bf-14b58fd6dcca.png)

**Comment by dmitridr** [comment]
Hello,

Could you share with us the configuration of the product (a screenshot of the product in the edit page will do)? I'm guessing the variants are configured to be 'any color' on the woo-commerce side?

**Comment by bojochris** [comment]
Hello,

Thanks for getting back to me. I noticed that the issue concerns variable
products.

See screenshot below:

[image: Inline image 1]

Cheers,

*Chrystalla Zezou*
*Operations Manager*


*www.clickhouse.media <http://www.clickhouse.media>*
Eleftheroupoleos 6, Unit 16, Strovolos, Nicosia, 2001 Cyprus
*Phone*: +357 22 222122
*Skype*: chrystalla.clickhouse
*Email*: c.zezou@clickhouse.media

**Comment by mengyingdu** [comment]
Hi,

The inline image is invisible from your message, you need to click on  'selecting items' at the bottom of text area. Can you upload again?

Thanks.

**Comment by bojochris** [comment]
Hello there,

Please find attached the screenshot. Also, kindly get back to me as soon as
possible regarding the issue.
Thanks a lot.

Cheers,

*Chrystalla Zezou*
*Operations Manager*


*www.clickhouse.media <http://www.clickhouse.media>*
Eleftheroupoleos 6, Unit 16, Strovolos, Nicosia, 2001 Cyprus
*Phone*: +357 22 222122
*Skype*: chrystalla.clickhouse
*Email*: c.zezou@clickhouse.media

**Comment by bojochris** [comment]
Hey again,

I have found the way to solve this.

Thank you anyway!

Cheers,

*Chrystalla Zezou*
*Operations Manager*


*www.clickhouse.media <http://www.clickhouse.media>*
Eleftheroupoleos 6, Unit 16, Strovolos, Nicosia, 2001 Cyprus
*Phone*: +357 22 222122
*Skype*: chrystalla.clickhouse
*Email*: c.zezou@clickhouse.media

**Comment by mengyingdu** [comment]
Glad to hear you figure it out.

**Comment by Jany-M** [comment]
@bojochris how?? Color, Material and Size are still not showing for me.

@mengyingdu How do I tell the plugin the slug of these attributes (Im sure that not everybody write it the same and/or in english!!!)??
