### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by sn00ppy** [facebookincubator/facebook-for-woocommerce#6]
Hello
I installed the facebook plugin for woocommerce.
And I can't get it working: when I go to welcome screen and press "Get Started" button, nothing happens.
When I watch what's happening in console, I can see a javascript error when I click the "Get Started" button. I'm attaching the screenshot with the error.

![facebook-woocommerce](https://user-images.githubusercontent.com/1163343/28860804-486f2cda-775e-11e7-8795-b016f818bafc.png)

Please help me solve this issue,
Thank You,
 
Vig

**Comment by aashay** [comment]
Can you click into the error and show what the JS looks like?  Also can you confirm that you're running the latest version of the plugin?

**Comment by sn00ppy** [comment]
sure

![facebook-woocommerce-jserror](https://user-images.githubusercontent.com/1163343/28905092-4e42b332-780f-11e7-91a3-ce99ebc55513.png)

first two errors happen when the page loads and the third one onclick

**Comment by tahoff** [comment]
Can you try adding
```
ini_set('display_errors','Off');
ini_set('error_reporting', E_ALL );
define('WP_DEBUG', false);
define('WP_DEBUG_DISPLAY', false);
```
to your wp-config.php file?

**Comment by tahoff** [comment]
This was a duplicate issue, and was resolved in v1.4.5

**Comment by majdzik84** [comment]
I probably have a trivial question. I downloaded the plugin from https://woocommerce.com/products/facebook/
Unfortunately, the plugin is version 1.4.3 and I have a problem with the GET STARTED button at the beginning of integration.
How can I upgrade to the latest version 1.4.5?
I like the understanding and simple instructions. The plugin did not update automatically.

**Comment by tahoff** [comment]
There are a few ways of manually updating a plugin, which can be found here: https://kinsta.com/knowledgebase/manually-update-wordpress-plugin/ 

If none of those options work, you can try uninstalling our plugin and reinstalling version 1.4.5

**Comment by dougaitken** [comment]
@majdzik84 if you downloaded from WooCommerce.com, you would connect your site to WooCommerce.com using the [managing subscriptions](https://docs.woocommerce.com/document/managing-woocommerce-com-subscriptions) if you're using WooCommerce `3.1.x`
