### ISSUE TITLE
FB "duplicate" category added on product update in 1.6.1

### ISSUE THREAD

**Issue by silksow** [facebookincubator/facebook-for-woocommerce#60]
Steps to reproduce:

1. Update existing product in any category.
2. FB creates new category (from quoted name to unquoted name), removes product from original category and moves it to the new one.
3. WooCom categories unchanged.

(There are no products in the "hoodies" category in the attached images.)
**FB product catalog**
![fb for woocom categories](https://user-images.githubusercontent.com/30702576/30986927-0435f2a6-a44a-11e7-81d3-5b6d06fa137c.png)
**WooCom categories**
![fb to woocom categories 2](https://user-images.githubusercontent.com/30702576/30987043-73fa6090-a44a-11e7-9662-e036535af3d3.jpg)
**Updated WooCom product**
![fb to woocom categories 3](https://user-images.githubusercontent.com/30702576/30987046-763a0400-a44a-11e7-8cf8-1b0ecbe1a854.jpg)

**Comment by dmitridr** [comment]
We removed the quotes from the category names as part of a fix for #26. If you force resync it should update all the products with the new (quoteless) categories.
