### ISSUE TITLE
Woocommerce products synced but not showing in Facebook Shop

### ISSUE THREAD

**Issue by smwebdesigns** [facebookincubator/facebook-for-woocommerce#604]
Hi,

I have got the facebook for woocommerce plugin active on this site: https://www.lj-natural.com. it has been set up and products have been synced and can be seen in the catalogue. However, the products are not pulling through to the facebook shop.
Please can you advise what the issue may be.

Many thanks,
Sarah

Facebook Page URL : https://www.facebook.com/ljnatural/
WordPress and WooCommerce version number: WP 4.9.7 Woo 3.4.4
Facebook Plugin version number: Version 1.9.2
How many products you have 93 (54 published)
Types of products (i.e. anything besides simple/variable products won’t work): Simple & Variable products only
Do you have Duplicate SKUs in your system? No
What kind of customization plugins you're using (if any)? Plugin list below

Akismet Anti-Spam |   | by Automattic – 4.0.8
-- | -- | --
iThemes Security |   | by iThemes – 7.0.4
Contact Form 7 |   | by Takayuki Miyoshi – 5.0.3
GDPR Cookie Consent |   | by webtoffee – 1.6.2
Easy Testimonials |   | by Gold Plugins – 3.2
Eggplant 301 Redirects |   | by Shawn Wernig http://www.eggplantstudios.ca – 2.3.0
EWWW Image Optimizer |   | by Shane Bishop – 4.2.3
Facebook for WooCommerce |   | by Facebook – 1.9.2 – Not tested with the active version of LJ Natural Shop
Jetpack by WordPress.com |   | by Automattic – 6.3.3
MailChimp for WordPress |   | by ibericode – 4.2.4
MetaSlider |   | by Team Updraft – 3.8.1
PixelYourSite |   | by PixelYourSite – 5.3.1 – Not tested with the active version of LJ Natural Shop
SUMO Reward Points |   | by Fantastic Plugins – 17.6 – Not tested with the active version of LJ Natural Shop
SG Optimiser |   | by SiteGround – 4.0.7
Page Builder by SiteOrigin |   | by SiteOrigin – 2.7.3
Special Recent Posts FREE Edition |   | by Luca Grandicelli – 2.0.4
White Label CMS |   | by www.videousermanuals.com – 1.6.4
WooCommerce Branding |   | by WooCommerce – 1.0.17
LJ Natural Shop Stripe Gateway |   | by LJ Natural Shop – 4.1.8
WooCommerce New Product Badge |   | by jameskoster – 0.3.0 – Not tested with the active version of LJ Natural Shop
LJ Natural Shop |   | by Automattic – 3.4.4
WooSidebars |   | by LJ Natural Shop – 1.4.5
Yoast SEO |   | by Team Yoast – 7.9
WPFront User Role Editor |   | by Syam Mohan – 2.14.1

Automated : Need More Info
<img width="860" alt="screenshot 2018-07-31 22 39 53" src="https://user-images.githubusercontent.com/2286895/43488770-b661ad58-9512-11e8-8351-5eead6ff229e.png">

**Comment by smwebdesigns** [comment]
Hi,

I have gone through the steps above and have supplied this information in my previous post.

Thanks, Sarah

Debug Ready

**Comment by dmitridr** [comment]
Hi Sarah,

Our records show that you do not have a shop because you chose not to create a shop in the final setup step. Please see #281 #557 for a description of the selector in the setup step, and how not to miss it. You will need to reset your existing configuration to go through the setup again to enable the shop. Hope that helps.

**Comment by smwebdesigns** [comment]
Hi,

Ok, thanks.

How do I reset the configuration? I have deleted the plugin and reinstalled
it but it goes to my previous configuration.

I don't know how to reset it to enable the shop?

[image: Screenshot 2018-08-02 22.54.34.png]


Kind regards,

Sarah
sm web designs

*School summer holiday working hours: I shall be away from 9th August and
will be back at my keyboard on 28th August. I will be checking emails but
not actively working other than to provide technical support. *

m: 07515 855 110
e: hello@sm-webdesigns.co.uk
w: www.sm-webdesigns.co.uk

Find me on:
instagram <https://www.instagram.com/smwebdesigns/>, facebook
<https://www.facebook.com/smwebdesigns>, pinterest
<http://www.pinterest.com/smwebdesigns/>, twitter
<https://www.twitter.com/smwebdesigns>, google+
<https://plus.google.com/u/0/b/101430781114797344991/101430781114797344991/posts>
  and linkedin <https://www.linkedin.com/pub/sarah-muirhead/33/704/657>




Note: My general working hours are set around the school day so I work
Monday to Friday 9:00am to 3pm. I check my emails twice a day, aiming to
respond as soon as possible and within 48 hours.

Confidentiality: The contents of this email and its attachment(s) are
confidential and intended solely for the use of the individual(s) to whom
it is addressed. Any views or opinions expressed are solely those of the
author and do not necessarily represent those of sm web designs. The
content of this email may not be disclosed, copied, forwarded, used or
relied upon by any other person other that the intended addressee. If you
are not the intended recipient of this email, you must not take any action
based upon its contents, nor copy or show it to anyone. Please contact the
sender if you believe you have received this email in error.

ᐧ

**Comment by dmitridr** [comment]
You have to go to the plugin configuration page. It's under `WooCommerce > Settings > Integrations`, then click on `Settings` or `Reconfigure` it should launch a popup. From there go to `Advanced Options > Delete` this will reset everything.

**Comment by smwebdesigns** [comment]
Great, thank you!

Kind regards,

Sarah
sm web designs

*School summer holiday working hours: I shall be away from 9th August and
will be back at my keyboard on 28th August. I will be checking emails but
not actively working other than to provide technical support. *

m: 07515 855 110
e: hello@sm-webdesigns.co.uk
w: www.sm-webdesigns.co.uk

Find me on:
instagram <https://www.instagram.com/smwebdesigns/>, facebook
<https://www.facebook.com/smwebdesigns>, pinterest
<http://www.pinterest.com/smwebdesigns/>, twitter
<https://www.twitter.com/smwebdesigns>, google+
<https://plus.google.com/u/0/b/101430781114797344991/101430781114797344991/posts>
  and linkedin <https://www.linkedin.com/pub/sarah-muirhead/33/704/657>




Note: My general working hours are set around the school day so I work
Monday to Friday 9:00am to 3pm. I check my emails twice a day, aiming to
respond as soon as possible and within 48 hours.

Confidentiality: The contents of this email and its attachment(s) are
confidential and intended solely for the use of the individual(s) to whom
it is addressed. Any views or opinions expressed are solely those of the
author and do not necessarily represent those of sm web designs. The
content of this email may not be disclosed, copied, forwarded, used or
relied upon by any other person other that the intended addressee. If you
are not the intended recipient of this email, you must not take any action
based upon its contents, nor copy or show it to anyone. Please contact the
sender if you believe you have received this email in error.

ᐧ

**Comment by dmitridr** [comment]
No problem. Looks like you got it working now, closing this out!
