### ISSUE TITLE
Reconfigure > Advanced Options > Delete

### ISSUE THREAD

**Issue by FoldAccessories** [facebookincubator/facebook-for-woocommerce#612]
Please help - Where do i find where to do this? Facebook business settings? Or on Wordpress back end? i am really unsure..

**Comment by dmitridr** [comment]
Hi,

Thanks for your interest in our plugin. 
I understand your confusion, we recently renamed `Reconfigure` to `Settings`. 
Here's a screenshot showing where the settings are (they're in Wordpress under WooCommerce settings) : 

![where1](https://user-images.githubusercontent.com/29133800/43736129-6414bc44-9971-11e8-9a40-3f8873ad3479.png)

Hope that helps!

**Comment by boutzamat** [comment]
> Hi,
> 
> Thanks for your interest in our plugin.
> I understand your confusion, we recently renamed `Reconfigure` to `Settings`.
> Here's a screenshot showing where the settings are (they're in Wordpress under WooCommerce settings) :
> 
> ![where1](https://user-images.githubusercontent.com/29133800/43736129-6414bc44-9971-11e8-9a40-3f8873ad3479.png)
> 
> Hope that helps!

This only took me 1 hour to find. Please do something about that documentation. 

Thank you for this guide. I was starting to become a bit frustrated.
