### ISSUE TITLE
Warning in checkout page

### ISSUE THREAD

**Issue by mercerialacostura** [facebookincubator/facebook-for-woocommerce#616]
Hi there,

I'm having an issue with Facebook for Woocommerce plugin. Once you paid the order, in the checkout (order-received), it appears this warning:

> Use of undefined constant wcs_get_subscriptions_for_order - assumed 'wcs_get_subscriptions_for_order' (this will throw an Error in a future version of PHP) in 
/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-events-tracker.php on line 329

I'm not sure how to fix it. I hope you could help me with that.

Thank you in advance.

Regards

PS, wp_debug is off.

**Comment by mercerialacostura** [comment]
WooCommerce version: 3.4.4
WordPress version: 4.9.8
Plugin version: 1.9.3
A screenshot of where you see the problem: A screenshot of WooCommerce.
![whatsapp image 2018-08-07 at 16 49 45](https://user-images.githubusercontent.com/42202528/43888329-b5020e3e-9bc1-11e8-8fb6-e0c76639e798.jpeg)

The URL of your website: https://www.mercerialacostura.com/
The URL of your page: https://www.facebook.com/mercerialacostura/
The URL(s) of where you took your screenshot(s): https://www.mercerialacostura.com/finalizar-compra/order-received/ (The warning only applies to a real order)

Debug Ready

**Comment by RamiSadi** [comment]
The same issue with me, and the same environment.

**Comment by ozzysong** [comment]
Can confirm is happening on 1.9.4 version of the plugin.

**Comment by mengyingdu** [comment]
This was fixed in [v1.9.5](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.9.5)
We will push it to woocommerce marketplace next week, and it's ready to download from github now. 

Thanks for the reports and triage!
