### ISSUE TITLE
Some products displaying ex VAT prices / some inc VAT

### ISSUE THREAD

**Issue by jimmyjinkz** [facebookincubator/facebook-for-woocommerce#63]
1 out of 5 products in my facebook shop is displaying prices ex VAT instead of inc VAT.

The price should be £69.99 inc VAT but the ex VAT price of £58.33 is displaying.

The other products are displaying the inc VAT prices.

All products are entered into my store ex VAT.
![screen shot 2017-09-30 at 14 39 41](https://user-images.githubusercontent.com/32415240/31046247-72171292-a5ed-11e7-85b1-612a6170ecad.png)

**Comment by dmitridr** [comment]
Hi,

Could you give us some more details on the ex VAT product? Any specific thing that makes it different from the others (is it on sale? was it on sale in the past?). A screenshot of the config page for the price may be helpful.

**Comment by jimmyjinkz** [comment]
Hi

The £58.33 product was created last week.

The config of the product is exactly the same as the product with the same name priced at £89. This product is displaying correctly with VAT included.

The only differences in the config are: 1. the price; 2. a canonical link reference in the head; and 3. the visibility of this product is set to hidden (although it is still visible for some reason - raised as a separate issue).

Here is a screenshot of the config page:

![product config](https://user-images.githubusercontent.com/32415240/31172179-71e5cbfa-a8fa-11e7-8c6b-2c685dfb6e71.png)

**Comment by dmitridr** [comment]
Hi,

Thanks for taking the time and sending over more details! We still can't reproduce the issue on our end so there's a couple of things we'd like you to try to attempt to determine the cause:

- Have you tried updating the product? (This should resync the price)
- Have you tried updating the other 89 GBP product which is working fine now? (Will this error occur on the other product too? If so, it's a systemic issue in the plugin.)
- Have you tried deleting the product? (Then updating the product should re-create it.)
- Could you try to mark another product as not visible? (I wonder if the Visibility setting is affecting the price somehow.)

And another question:

- We also checked in our backend, apparently the product used to be worth 69.99 GBP when it was first uploaded on Sept 30, but it was updated on Oct 4 and the price changed to 58.33 GBP. Is there a chance you upgraded the plugin version between those times?

**Comment by jimmyjinkz** [comment]
Hi

I deactivated all plugins on my site apart from WooCommerce and Facebook for WooCommerce.

I think ran a few tests:

- show / hide bulk editor didn't change the visibility of the £58 product
- on product page clicked visible and update - confirmed product on facebook updated but no change to price or visibility
- on product page clicked to make not visible and update - got a 502 timeout error, which I got with all plugins enabled too (either the 502 or connection lost or connection lost then 502)
- clicked delete product on facebook - now product states 'this product is not synced to facebook' and the product is not visible on facebook anymore
- updating product post deletion - recreated product on facebook but still at ex VAT price

I haven't tried updating the £89 product that is showing correctly with VAT included. I'd prefer to not test updating this one in case I end up syncing an ex VAT price point that I can't undo.

Now I've deleted the product from facebook are there any records relating to it in your backend? If so, could you delete them and I'll try resycing?

In terms of starting at £69.99 and moving to £58.33, I think the following happened:

1. I installed an older version of plugin - synced to facebook at £58.33
2. I was trying to change the visibility of the product on facebook and somewhere in that process the price started to show ex VAT
3. I tried deleting the product from facebook visibility but it kept showing even when it said it was deleted in Woo
4. I deleted my facebook connection with Woo to delete my shop and get rid of the orphaned product that was showing in Facebook without anyway to update it or turn it off
5. I installed the latest version of the plugin - I can't remember if this synced at £69.99 then went to £58.33, or if it synced at £58.33 straight away

**Comment by mengyingdu** [comment]
Hi jimmyjinkz,

Thanks for your time and detailed information. 
1. We have improved tax support from v 1.6.0. It's possible that when you upgrade the version, not all products have been re-synced. 
2. We can clear up your settings in our backend and let's do this way. Please go to: 'WooCommerce -> Settings -> integration->Facebook for WooCommerce->Re-configure Facebook Settings, then in the popup window 'advanced option' tag, click 'delete settings'
In the meanwhile, I will clear up your data in backend. So we can make sure client and server are completed cleared up.
3. I checked that there is problem with 'visible' setting (I check with my account and also test user not page owner account). I'm working on it to fix now.
4. As for bulk action, currently there are some bulk actions we don't fully support. For best practice, I would recommend either edit on product page and update for single product, or after changes re-sync products.

Please confirm that you want us to clear up all your store setting in our backend. But you will need to set up again in this case.

Thanks.

**Comment by jimmyjinkz** [comment]
Hi - I've deleted my settings, so yes please can you delete on the back end too? Thank you

**Comment by dmitridr** [comment]
Did following the reset steps resolve the problem? The backend should automatically be deleted if you deleted your settings using the interface as @mengyingdu suggested.

**Comment by jimmyjinkz** [comment]
Hi

Issue mostly resolved thanks :-)

I upgraded to 1.6.6 before reconnecting.

After reconnecting, all prices synced inc VAT.

And when changing visibility on the product page, the changes did pass through to my facebook shop. A connection lost message was displayed, but then the page reloaded itself and confirmed the product had been updated.

Thanks for your help on this
