### ISSUE TITLE
Products are imported, prices and images aren't linked properly

### ISSUE THREAD

**Issue by rburnett3** [facebookincubator/facebook-for-woocommerce#66]
I'm trying to sync our product catalog, with no luck getting everything synced properly.  Some products are imported twice under different names 1 with the price, 1 without, 1 with product photo the other without. 
![products](https://user-images.githubusercontent.com/32270839/31096290-9be0ef1a-a789-11e7-94e1-547558ee9408.jpg)
![products 3](https://user-images.githubusercontent.com/32270839/31096293-9e3aa63e-a789-11e7-8504-1c946c2d8f25.jpg)
![products 2](https://user-images.githubusercontent.com/32270839/31096294-9fe578ce-a789-11e7-9fca-96a10d80e3d8.jpg)
![products 1](https://user-images.githubusercontent.com/32270839/31096298-a182b34a-a789-11e7-8c56-ac4822360a46.jpg)

Some variations will show product price.  And the original will have the photo and no pricing.  

Is it possible to edit those products directly? (remove/delete , update photo, add pricing info manually?)

**Comment by dmitridr** [comment]
Hello,

That's really weird. Do you have any other extensions which could be causing this? If you have any ideas you could try disabling those, syncing with fb, then re-enabling. But I don't know what kind of extension would cause something like this...
Can you confirm you're running on a new version of the plugin 1.6.1 or 1.6.2?

**Comment by rburnett3** [comment]
The plugin is updated.  Here's what I've found after digging deeper. 
![products 5](https://user-images.githubusercontent.com/32270839/31129771-8de07bca-a823-11e7-8bb6-510c61aa2ef7.jpg)
These two products are the same from our WooCommerce store. 
The main difference I see in the listings are:
**1.**  
![edit php](https://user-images.githubusercontent.com/32270839/31131169-58c42712-a827-11e7-8108-582a8d79e8d6.jpg)

The products are listed as "In Stock $49.95" and "In Stock **From**: $49.95".
The listing stating **From** is not showing the pricing in the Facebook Store. 
Descriptions are not fully in the **MB1444**
![products 6](https://user-images.githubusercontent.com/32270839/31131312-c0a4891c-a827-11e7-8226-e0c9ed65a7f9.jpg)
![products 7](https://user-images.githubusercontent.com/32270839/31131314-c208162a-a827-11e7-9164-c9e2cec9d710.jpg)

**Comment by dmitridr** [comment]
Hello,

Thanks for the extra detail. Could you elaborate on the product with the "From" listing in the price? What kind of type of product is it? (Variable? Simple?) 

Also a small update from our team, v1.6.4 should prevent products with $0 price from being visible in the store. I don't think this will fully address your problem, however.

**Comment by dmitridr** [comment]
Closing because there hasn't been a response in a while. If you do still have the same problem, consider upgrading to the latest version v1.7.3, and doing a complete reset of the plugin. We have made many changes since and it's possible the problem will no longer occur.

Feel free to open a new issue and reference this one if the problem persists and you'd like to continue discussion.
