### ISSUE TITLE
How to delete shop on Facebook created by the plugin

### ISSUE THREAD

**Issue by lcorsa** [facebookincubator/facebook-for-woocommerce#68]
Hi. Nice plugin, but doesn't work well for my store because I have many "composite products" that show up as $0 cost. I've been trying to figure out how to delete the shop, but there is no "delete shop" option where it should be. Any idea how to delete a shop not created manually in Facebook? Thanks!

**Comment by dmitridr** [comment]
Hi,

You can disable creation of the shop during setup. It's in the last step before setting up and clicking 'Finish'. If you have already set up, you can disable the shop by resetting the integration via:

Re-Configure Facebook Settings > Advanced Options > Delete Settings

Then going through setup again, being sure to un-select the option `Add Products to a Facebook Shop`

**Comment by dmitridr** [comment]
I think we can look into not-syncing or not-showing products with 0$ cost if that will help your case.

**Comment by lcorsa** [comment]
Hi, dmitridr,
Perfect - that removed the shop! Yes, I think it would be helpful if $0 cost items could be excluded from the sync. Even better may be to have the ability to select the products to be included in the shop. Thanks!

**Comment by dmitridr** [comment]
@lcorsa 

There should already be a way to not show items in the shop via the 'Visible' checkbox on the product edit page.  #37  has the workaround. Closing this since I think this solves both issues!

**Comment by shaky512** [comment]
Hi, im also having trouble to delete products from facebook shop.
have set up the test products in woocommerce, and its appearing in facebook shop.
but can't delete them in facebook.
I've already  deleted the website & all its content.
but the products still appearing in facebook.
Do help.

**Comment by alxshell** [comment]
I have the same problem as @shaky512 described. Can not delete the products or the shop.
