### ISSUE TITLE
Issues with variable products syncing incorrectly...

### ISSUE THREAD

**Issue by tombellord** [facebookincubator/facebook-for-woocommerce#69]
Hi 
I have the Facebook for woo commerce plugin and all products form my store www.camillabellordinteriors.com have been synced to my business Facebook page (Camilla Bellord Interiors).

The issue I have is that every single variable product has not synced correctly. Issues include:

1) The full product descriptions are not present
2) The wrong image displays on default
3) Not all image pull through
4) When selecting a new colour, the image disappears
5) Random default sizes are pulled through to the landing page

Any guidance would be greatly appreciated.

Kind Regards
Tom

Supporting info: 

Facebook Page URL: https://www.facebook.com/pg/camillabellordinteriors/
WordPress and WooCommerce version number: 4.7.6
Facebook Plugin version number: 1.6.1
How many products you have: 55 (not including variations)
Types of products (i.e. anything besides simple/variable products won’t work): Simple and variable products
Do you have Duplicate SKUs in your system? No

**Comment by dmitridr** [comment]
Hello,

Could you give us a specific example of one product, a screenshot of the variant configuration and product images, and a link to the product on Facebook, and an explanation of the missing / incorrect information? This will help us solve your problem.

Some of the items you mentioned have already been resolved:

- We added gallery image import in 1.6.2 for variants, so you should be able to get that by upgrading.
- We added default variant selection in 1.6.3, which was just released.

We recommend using the 'Force Resync' option after upgrading.

**Comment by tombellord** [comment]
Dmitri

Many thanks for your mail. Sounds like if I have the right version my issues will be resolved. So before coming back to you with the specific issues, I will upgrade. 

Can you tell me where to download the latest version of the plugin? 

The following link where I got the 1.6.1 version doesn’t seem to have a 1.6.3 version available. 

Many thanks
Tom

Tom Bellord
Co-owner and Director
For and on behalf of Camilla Bellord Interiors
Web: www.camillabellordinteriors.com
Mobile: +44 (0)7867 393 488


 <https://www.instagram.com/camillabellordinteriors/>

This email and any files transmitted with it are only intended for the person(s) to whom this email is addressed and may contain confidential information. If you have received this email in error, please delete this message and do not copy, distribute, take any action in reliance on it or otherwise use it. We will not intentionally introduce viruses or bugs via this email but, unfortunately, we cannot guarantee that our emails will be secure or free from bugs or viruses given the proliferation of them; you are responsible for configuring your computer and should use your own virus protection software. 
 <https://www.instagram.com/camillabellordinteriors/>
On 6 Oct 2017, at 01:45, Dmitri Dranishnikov <notifications@github.com> wrote:

Hello,

Could you give us a specific example of one product, a screenshot of the variant configuration and product images, and a link to the product on Facebook, and an explanation of the missing / incorrect information? This will help us solve your problem.

Some of the items you mentioned have already been resolved:

We added gallery image import in 1.6.2 for variants, so you should be able to get that by upgrading.
We added default variant selection in 1.6.3, which was just released.
We recommend using the 'Force Resync' option after upgrading.

**Comment by dmitridr** [comment]
Hi Tom,

Thanks for your response. The WooCommerce site tends to have a delay of about 1-2 weeks for the versions because of their deployment cycle. You can always find the latest version [on our GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/releases). 

After you upgrade be sure to hit 'Force Resync' to resync all the products and see which issues persist.

**Comment by tombellord** [comment]
Hi Dimitri

I have now updated the plugin to the 1.6.3, so thanks for sharing the link to the latest version on github. We are however still experiencing some problems. 

So here are a couple of examples: 

If you take the "Sama cushion” product as seen on our website: 
https://www.camillabellordinteriors.com/product/sama-linen-cushion/ <https://www.camillabellordinteriors.com/product/sama-linen-cushion/>

When this is synced with Facebook it shows as follows: 

https://www.facebook.com/commerce/products/1877190815639265/ <https://www.facebook.com/commerce/products/1877190815639265/>



Here you will see that he main image is the pink version of the cushion (known as Illet). However the product is described on the right as the Eaux Profondes variant (which is the navy blue coloured cushion). 
If you then try to select another colour option the main image does not change to reflect this. So if you have colour descriptions that are not standard e.g. red, blue, yellow etc the customer could easily end up purchasing a colour they do not actually want. 

The second issue is in regards to how the artwork is pulling through to the Facebook page. 

We have 4 different sizes for every artwork print available framed and unframed (so 8 variants per print). The cheapest format is to the smallest print unframed which costs £793. As you will see from our website all default settings for artwork are from £793.

https://www.camillabellordinteriors.com/product-category/artwork/ <https://www.camillabellordinteriors.com/product-category/artwork/>

However if you look at the Facebook store the artwork is pulling through at various price points - but never at £793 as a default. Below you can see the Aston Martin print coming through at £985 and the Bull print coming in at £2570. We would naturally like all products to feature at their cheapest price as a default. 



I hope that helps to explain the issues we are facing? 

Thanks in advance for any help you can offer to get this remedied. 

Kind Regards
Tom


Tom Bellord
Co-owner and Director
For and on behalf of Camilla Bellord Interiors
Web: www.camillabellordinteriors.com
Mobile: +44 (0)7867 393 488


 <https://www.instagram.com/camillabellordinteriors/>

This email and any files transmitted with it are only intended for the person(s) to whom this email is addressed and may contain confidential information. If you have received this email in error, please delete this message and do not copy, distribute, take any action in reliance on it or otherwise use it. We will not intentionally introduce viruses or bugs via this email but, unfortunately, we cannot guarantee that our emails will be secure or free from bugs or viruses given the proliferation of them; you are responsible for configuring your computer and should use your own virus protection software. 
 <https://www.instagram.com/camillabellordinteriors/>
On 6 Oct 2017, at 01:45, Dmitri Dranishnikov <notifications@github.com> wrote:

Hello,

Could you give us a specific example of one product, a screenshot of the variant configuration and product images, and a link to the product on Facebook, and an explanation of the missing / incorrect information? This will help us solve your problem.

Some of the items you mentioned have already been resolved:

We added gallery image import in 1.6.2 for variants, so you should be able to get that by upgrading.
We added default variant selection in 1.6.3, which was just released.
We recommend using the 'Force Resync' option after upgrading.

**Comment by dmitridr** [comment]
Hello Tom,

Thanks for sending over the issues you're facing with great detail and many supporting links, this certainly helps us address your issues.

- For the first issue, the good news is that we have addressed the problem in [v1.6.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest) which we released today. Updating to this version and doing a 'force resync' should hopefully address the issue you are seeing with the pillow. It will take a few minutes after the resync for the shop to update the order of the images. Let us know if this problem still occurs despite that.

- For the artwork issue, that's strange because we should have supported "Default Variants" in 1.6.3. Could you send over a screenshot of the configuration of the variants of one of those products? Specifically we are interested in what the setting is for the 'Default'. 

For example for this product https://www.facebook.com/commerce/products/1454611591321075/ the default from our perspective appears to be 'Framed' which is why the price is showing as 985. It could be a bug in our default variant selection if we are using the wrong default there.

~Dmitri

**Comment by tombellord** [comment]
Dimitri
Thanks for your mail. I have now updated to version 1.6.4 and now everything works!! Thank you so much for your help with this!! 

Very much appreciated. 

Have a great weekend. 

Kind regards
Tom

Tom Bellord
Co-owner and Director
For and on behalf of Camilla Bellord Interiors
Web: www.camillabellordinteriors.com
Mobile: +44 (0)7867 393 488


 <https://www.instagram.com/camillabellordinteriors/>

This email and any files transmitted with it are only intended for the person(s) to whom this email is addressed and may contain confidential information. If you have received this email in error, please delete this message and do not copy, distribute, take any action in reliance on it or otherwise use it. We will not intentionally introduce viruses or bugs via this email but, unfortunately, we cannot guarantee that our emails will be secure or free from bugs or viruses given the proliferation of them; you are responsible for configuring your computer and should use your own virus protection software. 
 <https://www.instagram.com/camillabellordinteriors/>
On 13 Oct 2017, at 02:36, Dmitri Dranishnikov <notifications@github.com> wrote:

Hello Tom,

Thanks for sending over the issues you're facing with great detail and many supporting links, this certainly helps us address your issues.

For the first issue, the good news is that we have addressed the problem in v1.6.4 <https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest> which we released today. Updating to this version and doing a 'force resync' should hopefully address the issue you are seeing with the pillow. It will take a few minutes after the resync for the shop to update the order of the images. Let us know if this problem still occurs despite that.

For the artwork issue, that's strange because we should have supported "Default Variants" in 1.6.3. Could you send over a screenshot of the configuration of the variants of one of those products? Specifically we are interested in what the setting is for the 'Default'.

For example for this product https://www.facebook.com/commerce/products/1454611591321075/ <https://www.facebook.com/commerce/products/1454611591321075/> the default from our perspective appears to be 'Framed' which is why the price is showing as 985. It could be a bug in our default variant selection if we are using the wrong default there.

~Dmitri

**Comment by dmitridr** [comment]
Wonderful! Glad I could help.

**Comment by tombellord** [comment]
Hi Dimitri

We seem to be having another issue with the product images that are showing in the Facebook page. As you will see from the attached the images for “Stilettos” and the “1958 Lotus” prints are no longer showing as the products primary image and now seem to be taking the secondary images of the respective frames.

Can you advise how to ensure all products show their primary image, in this case the pictures of the prints?

Many thanks in advance.

Tom

Sent from Iphone

On 13 Oct 2017, at 02:36, Dmitri Dranishnikov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Tom,

Thanks for sending over the issues you're facing with great detail and many supporting links, this certainly helps us address your issues.

  *   For the first issue, the good news is that we have addressed the problem in v1.6.4<https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest> which we released today. Updating to this version and doing a 'force resync' should hopefully address the issue you are seeing with the pillow. It will take a few minutes after the resync for the shop to update the order of the images. Let us know if this problem still occurs despite that.

  *   For the artwork issue, that's strange because we should have supported "Default Variants" in 1.6.3. Could you send over a screenshot of the configuration of the variants of one of those products? Specifically we are interested in what the setting is for the 'Default'.

For example for this product https://www.facebook.com/commerce/products/1454611591321075/ the default from our perspective appears to be 'Framed' which is why the price is showing as 985. It could be a bug in our default variant selection if we are using the wrong default there.

~Dmitri

**Comment by tombellord** [comment]
Dmitri

Our Facebook feed from woo commerce is again showing with problems. 

As you will see from the screenshot below our “Stilettos” artwork is showing on our FB page as a frame (which is the supporting image in our store). 



To help clarify I also send you the image of the stilettos product in our store. 

https://www.camillabellordinteriors.com/product/stilettos-limited-edition-print/

Please do come back to me on this as I really do not want this bland “frame” image to be on my FB page. 

Many thanks in advance. 

Best
Tom


On 13 Oct 2017, at 02:36, Dmitri Dranishnikov <notifications@github.com> wrote:

Hello Tom,

Thanks for sending over the issues you're facing with great detail and many supporting links, this certainly helps us address your issues.

For the first issue, the good news is that we have addressed the problem in v1.6.4 <https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest> which we released today. Updating to this version and doing a 'force resync' should hopefully address the issue you are seeing with the pillow. It will take a few minutes after the resync for the shop to update the order of the images. Let us know if this problem still occurs despite that.

For the artwork issue, that's strange because we should have supported "Default Variants" in 1.6.3. Could you send over a screenshot of the configuration of the variants of one of those products? Specifically we are interested in what the setting is for the 'Default'.

For example for this product https://www.facebook.com/commerce/products/1454611591321075/ <https://www.facebook.com/commerce/products/1454611591321075/> the default from our perspective appears to be 'Framed' which is why the price is showing as 985. It could be a bug in our default variant selection if we are using the wrong default there.

~Dmitri
