### ISSUE TITLE
Products Added by Bulk Edit Do Not Sync

### ISSUE THREAD

**Issue by icircletech** [facebookincubator/facebook-for-woocommerce#70]
I have an issue with the products not syncing with Facebook. 

I have attempted to deactivate/uninstall/reinstall/reactivate etc... 
I dumped all caches, killed the options row in the DB.
Unfortunately, none of these have worked.

The Facebook integration starts off saying "syncing products " "386 Products Remaining" (always says 386, no other number) Then eventually it kicks over to say "Products are synced to Facebook", but they never actually sync.  There is not a single product in the Facebook Catalog, and the WooCommerce "All Products" listings shows "Not Synced"

Please Help!

Any help is appreciated, I have been pulling my hair out trying to figure this one out.
Thanks in advance!

![fb-integrator-synced](https://user-images.githubusercontent.com/12781537/31259687-a56524fe-aa16-11e7-9b70-dd2dd4f056c9.png)
![fb-integration-386](https://user-images.githubusercontent.com/12781537/31259690-a91d6976-aa16-11e7-96b6-8042392c1d80.png)
![fb-integration](https://user-images.githubusercontent.com/12781537/31259692-ab651814-aa16-11e7-8b74-4116a4224997.png)
![product](https://user-images.githubusercontent.com/12781537/31259693-adbfa1b0-aa16-11e7-8bee-e03e97f96271.png)
![products](https://user-images.githubusercontent.com/12781537/31259695-afd71bc2-aa16-11e7-93ea-6a6b5f8fe337.png)

**Comment by icircletech** [comment]
I just read Issue #44 (Facebook shop won't update after product price change -> Bulk Edit Doesn't Work) I also use a bulk editor and recently did a massive update to all of my products using that bulk editing tool. I believe that is what caused this issue. I found that if I go into each individual product and click on "update" it creates a new listing on Facebook. If that is this case that's going to be a lot of work. I also noticed, that when I attempt to update a "Bundled Product" it does not create a listing on Facebook or Sync.

**Comment by dmitridr** [comment]
Hello,

Thanks for reporting this. That does look the same as #44. I take it from your first message that 'Force Resync' doesn't work after using bulk-edit?

Could you send us your PHP error logs, preferrably around the time you tried to do a 'Force Resync' or total plugin reset? I'm not sure why that wouldn't sync the products via bulk edit too. 

Could you also confirm you're using the plugin with version v1.6.1 or above?

**Comment by icircletech** [comment]
Confirmed - I am using the latest version off of Github 1.6.3

I checked my logs, I did not see any error logs present in the Facebook Plugin Folder or WP-Admin Folder, The  WP Core Folder folder had a log, but there was no relevant error data regarding this plugin.

Also, I had been working on re-uploading a small product set to facebook, I noticed that the Products would mysteriously overwrite the title (i.e., I would upload a product "iPhone 7 Case Blue", and then "iPhone 6 Case Blue". ) It would only keep one product on Facebooks shop. (I verified on facebook it would show iPhone 7 Case Blue until I synced iPhone 6 Blue.  I believe I narrowed it down to the fact that they were sharing the same image asset resource. (i.e., Both phone cases pointed at iphone-case-blue.jpg)  I created new individual assets and renamed them relative to the product (i.e, iphone-6-case-blue.jpg & iphone-7-case-blue.jpg)  I had to delete the product from Facebook shop catalog than manually resync each one.    

I kind of get the feeling it could be an issue on the Facebook Shop Catalog side of the equation. Maybe it has trouble sharing the same image asset name? 

I haven't had a chance to look at the code, I have been trying desperately to get my ad campaign going :) I will dig a little deeper and report back any findings if I get a chance. 

Thanks for your help!

**Comment by ifede84** [comment]
Dear Ircletech,

Do you use advanced bulk edit to bulk edit your items? I'have the same issue: editing via advanced bulk edit doesn't sync products...

**Comment by javismiles** [comment]
Hi folks,
"Products Remaining", what could I say, in my case Woocommerce + your plugin, "Products Remaining" is a nightmare to say the least, it just never works basically, sometimes it will show negative numbers, other times it will get stuck on whatever number and never move, force resync doesnt solve it, etc, etc, again right now this feels unusable for me, I have the latest versions of everything, I clean cache, deactivate, reactivate, etc, etc, try everything, nothing, this Sync feature is a nightmare

**Comment by dmitridr** [comment]
@mengyingdu added support for Bulk Edit in [v1.7.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). If you update, items edited through bulk edit should now be synced.
