### ISSUE TITLE
Why require WP_DEBUG_DISPLAY to be disabled?

### ISSUE THREAD

**Issue by dominic-p** [facebookincubator/facebook-for-woocommerce#702]
I'm just getting started with this plugin, but when I try to activate it I see a message saying;

> To use Facebook for WooCommerce, please disable WP_DEBUG_DISPLAY in your wp-config.php file. Contact your server administrator for more assistance.

It's considered [best practice](https://codex.wordpress.org/Debugging_in_WordPress) in the WordPress community to develop with WP_DEBUG enabled to catch any errors or bugs before you push your code to your production site. By forcing debug to be disabled you're effectively preventing me from testing the plugin in my development environment.

I'm curious why this decision was made.

**Comment by dominic-p** [comment]
Just following up here. Have you considered using output buffering to check for and remove garbage output? I would be willing to take a look at the code to see if I can come up with a PR if you can point me at the specific area(s) you're seeing this issue.

**Comment by dominic-p** [comment]
I finally got around to playing with the plugin a bit. I took your advice and commented out the check for `WP_DEBUG_DISPLAY`.

Right away I ran into a couple undefined index errors in the plugin code. I'm guessing you guys don't develop with `WP_DEBUG_DISPLAY` enabled? I was thinking the problem had to do with interference from other plugins, but now it looks like there are plenty of debug errors in the plugin code itself.

I really wanted to use this plugin because it seems like it makes life so easy, but I'm definitely concerned about the code quality and lack of adherence to WordPress/PHP best practices (you have to check if an array index exists with `isset()` or `empty()` before you try to access it).

Sorry, I don't mean to rant, but I guess I just expected better from facebook.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
