### ISSUE TITLE
Featured image duplicates

### ISSUE THREAD

**Issue by cesneris** [facebookincubator/facebook-for-woocommerce#71]
Hello,
I have a problem, featured image is shown twice on all products. Any ideas? 
![screenshot_1](https://user-images.githubusercontent.com/31724819/31264554-95ec9cd0-aa72-11e7-9d4b-94c5bbfd5b35.png)

**Comment by dmitridr** [comment]
Hello,

Thanks for reporting this. Could you tell us the plugin version you are using and could you link us to your shop or a sample product? I wasn't able to find these out using the url given in the screenshot.

**Comment by cesneris** [comment]
I am not using the latest one yet, 1.4.5. I will try to update tomorrow to see if something changes. My shop is https://www.mrbeard.lt

**Comment by dmitridr** [comment]
Yes please do update, there were a lot of changes since 1.4.5.

**Comment by dmitridr** [comment]
Please re-open if the update did not fix your issue. Thanks.
