### ISSUE TITLE
Support "Variable Subscription" Products : Prices are currently zero

### ISSUE THREAD

**Issue by nuvoPoint** [facebookincubator/facebook-for-woocommerce#73]
Hey, 
with the version 1.6.3 the variable subscription product prices are set to zero. This worked before so what have changed?

**Comment by dmitridr** [comment]
Hello,

Could you give us an example product and screenshot of the configuration? We changed the default variant selection, but I'm not sure how that is related. Which version did you upgrade from?

**Comment by nuvoPoint** [comment]
Sure!

This is the product in woocommerce: [https://www.cmiile.com/produkt/abonnement-paa-tandblegnings-gel/]
and on the Facebook shop it shows with zero price: [https://www.facebook.com/pg/cmiile/shop/?rid=1616157588646521&rt=6]

The product is setup as a Variable Subscription:
![sample](https://user-images.githubusercontent.com/7877300/31373665-3faf39c8-ad9b-11e7-8159-eada51e8fd9e.png)

**Comment by dmitridr** [comment]
Thanks for sending that over. We don't support variable subscription products, so I'm not surprised we broke it. Still I wonder what happened and why it used to work before... maybe we can fix it.

I will see if we can get a copy of that extension to test the problem.

Meanwhile, it would help us to know which version you were using earlier where the price actually worked for these products. Would you happen to remember that?

**Comment by dmitridr** [comment]
Update : v1.6.4 should have a workaround, the products with price 0$ currently will be marked as invisible in the shop if you do a force resync.

We'll support "Variable Subscription" products in general based on demand from our users. Currently we're prioritizing bugs and high-demand features.

**Comment by mengyingdu** [comment]
HHi, 
We have fixes for "Variable Subscription" products in [v1.7.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.4). Can you upgrade and try it?

**Comment by tahoff** [comment]
Closing unless this issue arises again.

**Comment by tj-i2g** [comment]
mengyingdu - Thank you! v1.7.4 fixed the issue, anyone running into this problem after uploading the latest version, just give it some time on facebook's end to process the variable subscriptions! nice work guys
