### ISSUE TITLE
facebook for woocommerce - stuck at "products still importing"

### ISSUE THREAD

**Issue by DFGFcreator** [facebookincubator/facebook-for-woocommerce#738]
I have the same problem with my FB shop. My woocommerce store is connected to the FB page, it's synced but the products are still importing after 3 days. Can you please help?

My FB page: https://www.facebook.com/thedailyfeelgoodfactor
Shop Page: https://www.facebook.com/thedailyfeelgoodfactor/shop
Website: http://thedailyfeelgoodfactor.com/shop/

Thank you very much for your help in advanced.

**Comment by DFGFcreator** [comment]
Debug Ready
Information as requested:
WooCommerce Version 3.5.0 
WordPress 4.9.8

![fb 5](https://user-images.githubusercontent.com/44540017/47640210-40f38780-dbb7-11e8-86ad-5734cfe6104b.PNG)
![fb 4](https://user-images.githubusercontent.com/44540017/47640211-40f38780-dbb7-11e8-8a6c-4a69451594da.PNG)
![fb 3](https://user-images.githubusercontent.com/44540017/47640212-40f38780-dbb7-11e8-9163-c91b5121af3b.PNG)
![fb 2](https://user-images.githubusercontent.com/44540017/47640214-418c1e00-dbb7-11e8-9089-b3384e70a899.PNG)
![fb 1](https://user-images.githubusercontent.com/44540017/47640215-418c1e00-dbb7-11e8-9b8c-87f16797de57.PNG)





Facebook for WooCommerce Version 1.9.6
My FB page: https://www.facebook.com/thedailyfeelgoodfactor
Shop Page: https://www.facebook.com/thedailyfeelgoodfactor/shop
Website: http://thedailyfeelgoodfactor.com/shop/

I've tried resync-ing the products from the plugin settings page as well as resetting the plugin by selecting Reconfigure > Advanced Options > Delete, and setting up this plugin again as advised on the common resolution methods

**Comment by Luther2010** [comment]
Hey @DFGFcreator! Are you seeing inconsistent information about whether the products are synced at different places? By looking at your page, it looks like the products have been synced and the catalog can be used to create Facebook ads

**Comment by DFGFcreator** [comment]
Yes, at WooCommerce Settings from my website, it states that my products are synced but in FB Business, it keeps looping at "uploading" my products and I can't see anything at my FB page. And I can't create any FB ads. Can you help?
![fb business](https://user-images.githubusercontent.com/44540017/48093064-6c830b80-e262-11e8-8580-63e9bbdadd14.PNG)

**Comment by tuperhero** [comment]
Hi @DFGFcreator  did you ever find the solution to this? I'm having the exact same problem

**Comment by thecryptodrive** [comment]
I'm also having the same problem.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
