### ISSUE TITLE
How to synch to new page

### ISSUE THREAD

**Issue by jasperf** [facebookincubator/facebook-for-woocommerce#76]
Facebook for WooCommerce is now synced to AddProduct demo page. I need it to be disconnected and connected to our page. How do we do that?

**Comment by dmitridr** [comment]
Hello,

You should be able to do this via 
`Reconfigure Facebook Settings > (Popup) Advanced Options > Delete > Confirm`

Then set up again using a different page. This will delete your catalog and (if you elected to set up a shop) your shop as well.

**Comment by jasperf** [comment]
But I do not see advanced options just this:
![screen shot 2017-10-11 at 8 06 54 am](https://user-images.githubusercontent.com/344138/31423152-8e08b944-ae5b-11e7-8fb8-9b5112b8cf44.png)

**Comment by jasperf** [comment]
Never mind. My partner had to disconnect it and now I can add a new one. Only need to figure out some Facebook Pixel things. Thanks for the help @dmitridr !
