### ISSUE TITLE
Hit "Sync Products" button and nothing happens - shop empty, catalog empty 

### ISSUE THREAD

**Issue by the-springer** [facebookincubator/facebook-for-woocommerce#767]
Debug Ready

Hi, the plugin has stopped working for me. Since yesterday when i hit the "sync products" the products got deleted and now the shop and catalog on FB are empty. No error msg - just stuck in "Syncing... Keep this browser open Until sync is complete"
How can i debbug this issue (woocommerce side or facebook side) - ive read in an reply about an log file, where would that be?
Maybe the feed is corrupted or something.

Shop with issue:
https://www.facebook.com/lorientwien/shop

Try'd the follwing steps you recommend
###########################
"Common Resolution Methods
If you are experiencing a problem or bug and have not found any similar issue, please try the following:

    Upgrade to the latest version of the plugin
    Try to Resync products using the button on the plugin config page
    Reset the plugin by selecting Reconfigure > Advanced Options > Delete, and setting up this plugin again
    Try deactivating other plugins that you think may be interfering, then reset and set up again"
###########################

Here are the necessary information

    WooCommerce version: 3.5.1
    WordPress version: 4.9.8
    Plugin version: 1.9.7
    A screenshot of where you see the problem :
![grafik](https://user-images.githubusercontent.com/40660827/48453295-0abb2800-e7b3-11e8-8a5d-b321e083f154.png)

![grafik](https://user-images.githubusercontent.com/40660827/48453315-27eff680-e7b3-11e8-9539-dfe8cda2b6b4.png)
  

    The URL of your website: https://www.lorient.at/
    The URL of your Facebook Page: https://www.facebook.com/lorientwien
    The URL(s) of where you took your screenshot(s): https://www.facebook.com/pg/lorientwien/shop/?ref=page_internal

**Comment by the-springer** [comment]
Here's an important update ... when i hit sync button still nothing happens BUT when i update a product this product will be synct then to FB shop and catalog

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
