### ISSUE TITLE
The software keep duplicating products

### ISSUE THREAD

**Issue by tacticalsurvivaltools** [facebookincubator/facebook-for-woocommerce#77]
the plugin keep syncing the same products over and over again in my facebook shop. I have only a few hundred products but in my facebook page it has thousands. Mostly same products duplicated 5 or 6 times.

**Comment by dmitridr** [comment]
Not good. That should not happen. Could you confirm you are on the latest version 1.6.1 or above?
If you give us the url of your shop or site we can also try to investigate what is happening.

**Comment by dmitridr** [comment]
Closing this, please re-open if you have additional information. We would need additional info to solve this.
