### ISSUE TITLE
Question, how we manage the inventory with bilingual website (Using WPML)

### ISSUE THREAD

**Issue by ecommerce1st** [facebookincubator/facebook-for-woocommerce#79]
Question, how we can manage the inventory with bilingual website (Using WPML)

On some customer bilingual store, we are using WPML (Language management software)

My question is how we can handle or manage the inventory?

I will get all the product in double (1 French and 1 in English?)

And can we use a code to select to use only the english inventor? (dor example)

Just to know...

Best regards,

Sylvain

**Comment by dmitridr** [comment]
Hello,

Thanks for reaching out. This issue has been mentioned before in #20. Does the suggested resolution in that task help your case?

There are also alternative resolutions in this thread:
https://wpml.org/forums/topic/facebook-for-woocommerce-extension-products-displaying-twice/

From that thread, it seems like we can support syncing only the default language with minimal code effort, so I can look into that. Probably for v1.6.5 or later.

**Comment by dmitridr** [comment]
A first pass at WMPL (version >=3.2) support was added in v1.7.4. Thanks for your patience on this.

We still sync all the products, however, those not in the default language are marked as `staging` and become invisible in the shop. So the shop will only show the default language products.

You can modify the code added [here](https://github.com/facebookincubator/facebook-for-woocommerce/commit/c7f1393e1584219e6e387d26f4dae2c9eb6e4967) using the plugin editor, if you'd like to sync products that are not the default language.
