### ISSUE TITLE
1.9.8 upgrade "Broke" site.

### ISSUE THREAD

**Issue by powerlix** [facebookincubator/facebook-for-woocommerce#799]
I updated today to 1.9.8 and now we get two error lines at the top of every page:

Warning: include_once(fbasync.php): failed to open stream: No such file or directory in /homepages/33/d630878307/htdocs/clickandbuilds/MiltonWares/wp-content/plugins/facebook-for-woocommerce/includes/fbgraph.php on line 18

Warning: include_once(): Failed opening 'fbasync.php' for inclusion (include_path='.:/usr/lib/php7.2') in /homepages/33/d630878307/htdocs/clickandbuilds/MiltonWares/wp-content/plugins/facebook-for-woocommerce/includes/fbgraph.php on line 18

**Comment by Mybeverly** [comment]
Yes me too please we need to find solution it's very urgent for me

Warning: include_once(fbasync.php): failed to open stream: No such file or directory in /htdocs/wp-content/plugins/facebook-for-woocommerce/includes/fbgraph.php on line 18

Warning: include_once(): Failed opening 'fbasync.php' for inclusion (include_path='.:/usr/share/php') in /htdocs/wp-content/plugins/facebook-for-woocommerce/includes/fbgraph.php on line 18

**Comment by soulpawa** [comment]
+1

**Comment by Luther2010** [comment]
Hey guys, I just uploaded the updated zip. Let me know if it works :) Sorry for any inconvenience it may cause

**Comment by Luther2010** [comment]
Great, thanks for getting back so quickly. I'm closing this one :)
