### ISSUE TITLE
When we select a specific color variation, the top image should change to show the right colour

### ISSUE THREAD

**Issue by ecommerce1st** [facebookincubator/facebook-for-woocommerce#80]
When we select a specific colour variation, the top image should change to show the right colour.

I have the last version 1.6.7
I already force resync.

My point if when we change the colour choices, the top picture should change to show the new selection, cause actually this is the second one changing.

For the customer, this is not user-friendly, they are not sure to make the right choices.

The store link: https://www.facebook.com/pg/pfworkwear/shop/

Check the boots for example : https://www.facebook.com/commerce/products/2096175410408317/

Best regards,

Sylvain

**Comment by dmitridr** [comment]
Hello,

We haven't released 1.6.7 yet, are you from the future? :)
The good news is that this is what we are currently trying to fix, and we are tracking the issue in #56 
v1.6.4 should have the fix when it is out.

**Comment by ecommerce1st** [comment]
Sorry I travel too much with my DeLorean...lol

I have 1.6.3 ;-)

**Comment by dmitridr** [comment]
Nice. 

We released [v1.6.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases) yesterday. If you force resync the order of the top two images should swap after a few minutes. 

We also added a checkbox on the WooCommerce side which will allow you use the old ordering if you need it back, which may be useful for running ads.

**Comment by dmitridr** [comment]
Please re-open the issue if upgrading and following the suggestion did not fix your problem! 

Also if you really are a time traveler, can we get a copy of our repo from 1 year in the future? I bet we could fix a lot of bugs all at once. :)
