### ISSUE TITLE
SHOPPING ON INSTAGRAM IS NOT WORKING AFTER MONTHS

### ISSUE THREAD

**Issue by Nathalie60** [facebookincubator/facebook-for-woocommerce#804]
Hi,

I have installed facebook for woocommerce and everything was ok, they said my account is ready for ads and I could install fb messenger if I wanted to. I received that my account is being looked at so they can approve it. After weeks, still nothing. I saw that my shop was up on FB but Instagram shopping wasn't working. After this I installed it again and again! After months is still isn't working!

**Comment by dmitridr** [comment]
Hi,

Thanks for writing in. IG Shopping is not officially supported by the plugin yet, please see #798 , so it's no surprise that it does not work. When it is officially supported you will see a button at the end of the plugin in order to apply for the shop. Thanks for your patience.
