### ISSUE TITLE
Showing 1st product gallery image instead of main product image under shop section on Facebook home page

### ISSUE THREAD

**Issue by meck22** [facebookincubator/facebook-for-woocommerce#81]
Hi all! It appears that the products are showing the 1st product gallery image instead of the main product image on the Facebook home page under the shop section but if you click "shop now" or click on the product, the main product image picture will be shown 1st. Any help on this issue would be greatly appreciated.            https://www.facebook.com/TechReUp/

**Comment by dmitridr** [comment]
Hello, 

Thanks for reporting this. I went to your site to try to observe the issue but it seems like the first image is the same as the image shown in the shop main screen, at least that is what I see.

Am I missing something? Could you send us a specific product which has the problem or maybe a screenshot of what you are seeing?

**Comment by meck22** [comment]
Hi there! Thanks for the quick response! If I click on the shop section everything appears to be good but if you go to the Facebook home page and see the shop section that is where I see the issue.

**Comment by meck22** [comment]
![facebook shop error](https://user-images.githubusercontent.com/32717515/31465986-a2a58de4-aea3-11e7-8382-a72da17e6b91.PNG)

**Comment by dmitridr** [comment]
Hello,

Based on Issue #90, could you try upgrading to the absolute latest version [v1.6.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases) and doing a 'Force Resync'? It will most likely address the problem. If not, we can continue to debug this.

**Comment by dmitridr** [comment]
Closing. Please re-open if upgrading did not fix your problem.
