### ISSUE TITLE
Facebook for Woocommerce : Add to Cart doesn't make the job

### ISSUE THREAD

**Issue by Deldum99** [facebookincubator/facebook-for-woocommerce#815]
Hello,

I'm running Facebook ads thanks to facebook for woocommerce, but it doesn't work because of a pixel bug ... Label advertiser 
I have a problem with the Pixel when I use Facebook-for-woocommerce : it doesn't install properly the pixel on my "add to cart" page. But all the other pages are right.
I already met this problem 1 year ago : it was working right but suddenly, the Fb pixel didn't record any Add to cart (but it recorded the right purchases, initiate checkouts).
I couldn't find a solution so I stopped Facebook-for-woocommerce and used Pixel-your-site. This worked perfectly   ;-)   However, I now want to connect my catalog (in order to use "objective : catalog sales" and variables in my ads) ... so I re-installed facebook-for-woocommerce, and once again, add to cart don't work anymore   :-(

Here are usefull infos :  
www.little-oh.be/cart
www.facebook.com/littleoh
WordPress 4.9.9
WooCommerce 3.5.2
Facebook for Woocommerce 1.6.6
Theme : Handystore 5.0.14 by Themes Zone
PHP : 7.0

I found another issu like mine, but it was closed without saying how they resolved it. Just "now it works" ...   :-(   #529 

PS : I can't code ... I just would like to use the plugin correctly and I didn't code in my existing website

In this image, you can easily see since when I changed Pixel-your-site for Fb-for-woocommerce : 
![image](https://user-images.githubusercontent.com/45895357/50042786-a49f1a80-0068-11e9-9e73-67157b0fd1b9.png)

**Comment by Deldum99** [comment]
Advertiser

Yannick 
_____________________________________

L'équipe Little Oh!
Créations originales et pétillantes
e-shop et boutiques : www.little-oh.be
Rejoignez la communauté :
www.facebook.com/littleoh/
www.instagram.com/little_oh.be

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
