### ISSUE TITLE
Messenger Chat

### ISSUE THREAD

**Issue by FlairTrade** [facebookincubator/facebook-for-woocommerce#816]
Would love the ability to designate what pages Messenger Chat feature are loaded on. I've chosen to uninstall the feature because of the site performance impact the script has on site load time. Page performance score on GTmetrix went from an "A" rating to "C" with Messenger Chat enabled. Which could significantly impact SEO scores and thus search rankings. Basically I don't want it on my primary landing page, just store and contact us location on my site.

Additionally, after enabling and then disabling the feature it is leaving remnants that are still negatively impacting site performance
![image](https://user-images.githubusercontent.com/35601034/50043150-08135300-003d-11e9-9beb-547dd3b651f3.png)

**Comment by FlairTrade** [comment]
Feature Request

**Comment by heArt-coder** [comment]
Calling Customer chat SDK after page load and specific time like 4 seconds can hugely benefit page load time and SEO scores.

**Comment by FlairTrade** [comment]
> Calling Customer chat SDK after page load and specific time like 4 seconds can hugely benefit page load time and SEO scores.

@heArt-coder agreed! Was that a developer recommendation or do you know how to make the plugin do that?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
