### ISSUE TITLE
Checkout URL Causes Infinite Redirect and Infinite Length URL

### ISSUE THREAD

**Issue by gjrowe** [facebookincubator/facebook-for-woocommerce#82]
If you go to https://m.facebook.com/pg/riverslicks/shop/?ref=page_internal&mt_nav=1 and try to "Checkout on Website" you won't be able to because it forwards to an incorrect URL

**Comment by dmitridr** [comment]
Hello,

Could you try the resolution in Issue #29 ?
Basically there is a setting in the 'Settings' page of the shop which will allow you to change the behavior of the "Checkout on Website" button in order to work around this issue.

**Comment by gjrowe** [comment]
As a workaround that works!
The other way the path in the URL is repeated over and over thus making the URL not work at all

Glenn Rowe

Message sent from my iPhone

**Comment by dmitridr** [comment]
Great! Glad the workaround works. 

I'm not sure why it's repeating over and over though, that is not something we have seen before. Do you happen to have another extension installed that changes / affects the default behavior of add to cart?

**Comment by gjrowe** [comment]
That is the only plugin I have that connects to the Facebook Shop

**Comment by dmitridr** [comment]
Sorry, I meant do you have a plugin that would affect the the default behavior of 'add to cart' within your WooCommerce store?

**Comment by gjrowe** [comment]
I don’t believe so but don’t quote me on that.

**Comment by dmitridr** [comment]
I'm following up on older issues. Since there's a workaround here I'm closing this one.
