### ISSUE TITLE
Syncing hidden, unpublished and products in trash

### ISSUE THREAD

**Issue by LQuin** [facebookincubator/facebook-for-woocommerce#830]
It syncs absolutely everything even drafts, unpublished items, and trash. I've seen old threads about it and you said it should've been fixed. I'm a new user and forced sync twice already. Not helping :(

**Comment by thisisvisual** [comment]
I have the same issue; Plugin syncs all products to Facebook - even the drafts, unpublished etc.

- WooCommerce version: 3.5.3
- Wordpress version: 
- Facebook for Woocommerce: 1.9.8
- Website URL: www.normode.dk
- Facebook page URL: www.facebook.com/pg/NorWomenMen
- Facebook shop screen print URL: https://www.facebook.com/pg/NorWomenMen/shop/?ref=page_internal 
- Webshop plugin screen shot: https://normode.dk/wp-admin/admin.php?page=wc-settings&tab=integration&section=facebookcommerce# 

![skaermbillede 2019-01-16 kl 13 00 03](https://user-images.githubusercontent.com/46748019/51248046-2f887300-198f-11e9-8dd2-d317f17c924b.png)

![skaermbillede 2019-01-16 kl 12 48 11](https://user-images.githubusercontent.com/46748019/51248059-3c0ccb80-198f-11e9-8273-d94486ea1aca.png)

**Comment by ody911** [comment]
Same issue here
