### ISSUE TITLE
Variable Products don't siynced with sales price [Debug Ready]

### ISSUE THREAD

**Issue by kevingraziani** [facebookincubator/facebook-for-woocommerce#845]
Hello there,
Facebook catalog doesn't show the sales price of my variable products. During this winter sales, I changed all the sales price of my woocommerce variable products, and I thought that Facebook would've changed the price also in my fb catalog. But it didn't happen. So that's why I'm here asking for support.
Let me know if you need further information about catalog ID, website url etc...
Thanks,
Kevin

**Comment by diwangcmu** [comment]
Hi Kevin, sorry that we didn't get to you earlier. Were you able to solve the problem? You are likely to find an answer here https://www.facebook.com/business/help/support. Hope that will help!
