### ISSUE TITLE
value for AddToCart equals 0 when not redirecting to cart

### ISSUE THREAD

**Issue by sunnre3** [facebookincubator/facebook-for-woocommerce#846]
WordPress version: 5.0.3
WooCommerce version: 3.5.3
Facebook for WooCommerce version: 1.9.9
PHP: 7.1

When WooCommerce option `woocommerce_cart_redirect_after_add` is set to `no` the `value` of the `AddToCart` event is always wrong.

In file `facebook-commerce-events-tracker.php` the action `inject_add_to_cart_event` runs at priority 2 but that means that WooCommerce cart hasn't calculated totals yet since `WC_Cart::calculate_totals()` runs at priority 20 on the same action (see `class-wc-cart.php:112`).

Changing priority of `inject_add_to_cart_event` to anything higher than 20 resolves this.

![skarmavbild 2019-01-21 kl 15 29 44](https://user-images.githubusercontent.com/2368812/51481016-e8d1b900-1d92-11e9-91d8-07cd58b08d98.png)
*`inject_add_to_cart_event` running at priority 2 (before `WC_Cart:calculate_totals()`*

![skarmavbild 2019-01-21 kl 15 31 32](https://user-images.githubusercontent.com/2368812/51481047-07d04b00-1d93-11e9-910f-91cdfa85ff0f.png)
*`inject_add_to_cart_event` running at priority 30 (after `WC_Cart:calculate_totals()`*

**Comment by sunnre3** [comment]
Debug Ready

**Comment by liborbitala** [comment]
Debug Ready

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
