### ISSUE TITLE
Get Started button not working

### ISSUE THREAD

**Issue by ophyrion** [facebookincubator/facebook-for-woocommerce#87]
in the debugger says - 
'facebookConfig' is undefined
uninstalled and reinstalled already 
using version 1.63
![fberror](https://user-images.githubusercontent.com/32764111/31538076-1a65649c-afa0-11e7-8c58-7ad8d620dcfd.JPG)

**Comment by dmitridr** [comment]
Hello,

This is strange.
facebookConfig() is defined in a function `facebook-settings.js` right [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/assets/js/facebook-settings.js#L71). It could be something is preventing you from reading this file?

My recommendation:
- Try clearing browser javascript Cache (Typically Shift + F5)
- Try switching browsers.
- Check PHP server error logs for `facebook` related errors.
- Make sure any ad-blockers in your browser are disabled.

Let us know if none of those help.

**Comment by dmitridr** [comment]
I guess one of those helped? Please re-open if that was not the case. Also potentially related to #74.
