### ISSUE TITLE
Brand Problem : WooCommerce Brands Pro Compatibility

### ISSUE THREAD

**Issue by imHakanArslan** [facebookincubator/facebook-for-woocommerce#88]
Woocommerce uses taxonomy for the brands. That plugin (Facebook for Woocommerce) could be ask to brand taxonomy for us.

Because, the brand of products on facebook, is seen as the name of my web site.
![brand-problem](https://user-images.githubusercontent.com/374136/31540136-75bc027e-b013-11e7-8aaf-a9a25945765a.png)

**Comment by dmitridr** [comment]
Hello,

Thanks for bringing this to our attention. I do not think it would be that hard for us to support product brands and export them into FB.

However, I could not find a way to store the product brand on WooCommerce by default.
Are you using some extension to store the brand of the product? `WooCommerce Brands` ?

**Comment by imHakanArslan** [comment]
Yes i am using Woocommerce Brands Pro (http://proword.net/Plugins/Woocommerce_Brands_pro/)

**Comment by imHakanArslan** [comment]
this worked: get_the_term_list( $post->ID, 'product_brand', '', ', ' )

thank you.

**Comment by dmitridr** [comment]
Hello again,

You got it to work? That's great!
We'd love it if you send us a pull request with your fix, if you have figured out a way to fix it.

**Comment by CosminMandricel** [comment]
@imHakanArslan can you explain more exactly how you fix the problem, please?
I using the same plugin, Woocommerce Brands Pro, paid version.

**Comment by imHakanArslan** [comment]
It works but there is a problem.
if you are editing a product, it works correctly.

but when i use Force Product Resync, everything is okay just brand get null. (brand field always empty).
![Image of problem](https://static.doludunya.com/uploads/2017/01/problem.jpg)
Hi, @CosminMandricel, if that info enough for u, u have to edit that code.

open facebook-commerce.php file and find this code 'brand' => $this->get_store_name(), lines 947,1515 

change this : 'brand' => strip_tags(get_the_term_list( $post->ID, 'product_brand', '', ', ' )),

**Comment by scarparoalves** [comment]
what should I do if I use an attribute named 'brand' to save product brand value? Any Idea?

**Comment by dmitridr** [comment]
@scarparoalves 

You should add a `case` statement in this switch [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L994), 

`case 'brand':`

That should be enough, though `Disclaimer` I haven't tested this, so try it at your own risk. I'm pretty sure it will work though, that code takes the attributes for size and color and sets them to the product fields by the same name if they exist.

**Comment by romaniamare** [comment]
I am also interested to rename  taxonomy named “product_brand” in "brand".
who can explain how to do that?
thx

**Comment by mengyingdu** [comment]
@imHakanArslan @scarparoalves 

We will support brand extension in next release which should be next week. Thanks.
