### ISSUE TITLE
Products not syncing

### ISSUE THREAD

**Issue by RuzgarDogu** [facebookincubator/facebook-for-woocommerce#881]
Hi, 

I am using Facebook for Woocommerce Version 1.9.7 and Woocommerce Version 3.5.4. I believe i did everything as instructed. It's been 2 days but my products are not syncing to my Facebook shop.

I deleted the settings and reconfigured everything from scratch. But no luck.
It is giving me the message "Something wrong when uploading, please try again."

My products which are published before i installed this plugin shows "Not synced" and the one that i added after this plugin says it's visible (and synced). But still none of them is showing up on my facebook store. When i try to sync manually, again nothing happens.

How can i overcome this issue? Thank you in advance.

PS: When i tryy to sync products manually by clicking the "Sync Products" button on woocommerce settings, it says "Syncing... Keep this browser open Until sync is complete". But its taking too long, and nothing happens. And i also checked "Automatically Force Resync of Products At  23:00 Every Day." But nothing happened.

There is an error code saying:

`/wp-admin/admin.php?page=wc-settings&tab=integration#:1 Failed to set referrer policy: The value '' is not one of 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-cross-origin', 'same-origin', 'strict-origin', 'strict-origin-when-cross-origin', or 'unsafe-url'. The referrer policy has been left unchanged.`

And: 
`Failed to load resource: the server responded with a status of 500 (Internal Server Error) admin-ajax.php`

**Comment by chrisschwartze** [comment]
Same issue here.

**Comment by RuzgarDogu** [comment]
Can it be something related to secure connection? Because this site is serving over http but requests are made to https. Just a thought.

**Comment by zdytch** [comment]
Same for me, site runs over https

**Comment by RuzgarDogu** [comment]
Finally I've found that there were several issues.

1. My PHP version was 5.4 which was out of date. And it gave me this error message:

`CRITICAL Class 'CurlFile' not found in /var/www/vhosts/hoopoes.co.uk/httpdocs/wp-content/plugins/facebook-for-woocommerce/includes/fbgraph.php on line 191`

I called my hosting provider and updated my PHP version to 5.6, which solved this issue.

I deleted my settings and setup again, but i still couldn't manage to upload products to my Facebook Store.

Then I realized that i already have a shop on facebook that blocked me fro uploading to Facebook.
So i deleted my settings again, and setup for the last time, but this time by checking "Add products to a facebook shop".
And Voila.

You can check the original post from [here](https://github.com/facebookincubator/facebook-for-woocommerce/issues/281)

Hope this helps someone.

**Comment by antareius** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
