### ISSUE TITLE
Products sync but don't show up on Facebook

### ISSUE THREAD

**Issue by CharlotteBr28** [facebookincubator/facebook-for-woocommerce#884]
Hello,

I have got the facebook for woocommerce plugin active on this site: www.fineyellow.com. It has been set-up and products have been synced (screenshot 1) but they can't be seen on the catalogue (screenshot 2) and they are therefore not available in the facebook shot.
In addition, when going to the Sources of Product data on my shop, it says that it was impossible to import the feed.
Can you please advise what the issue is and how it can be resolved?

I have already tried to:
- resync the products using the button on the plugin config page
- reset the plugin and setting up this plugin again

Thanks a lot,
Charlotte

Information you might need:
Website URL: www.fineyellow.com
Facebook Page URL: www.facebook.com/fineyellow/
Wordpress and WooCommerce version number: WP 5.0.3 and WC 3.5.4
Facebook Plugin verison number: version 1.9.7
How many products do we have: 276 published products
Types of products: Simple and Variable (with variations)
We don't have duplicate SKUs in the system

Screenshots:
1. When I go on WordPress and then click WooCommerce > Settings > Integrations > Facebook > Manage Settings > Your Products, then screenshot one shows that it tells me the sync was successful
2. Then I click on "Display your products on Facebook" and I get to screenshot 2, where it says there are 0 products in my facebook catalogue
3. When on the shop, when clicking on Source of product data, it appears that it was impossible to import the feed, but I don't understand why
<img width="936" alt="screenshot 1" src="https://user-images.githubusercontent.com/47816078/53088164-40d21b80-3509-11e9-89aa-c5915ad48c6b.png">
<img width="1195" alt="screenshot 2" src="https://user-images.githubusercontent.com/47816078/53088177-44fe3900-3509-11e9-8f0c-4144f63f6825.png">
<img width="1207" alt="screenshot 3" src="https://user-images.githubusercontent.com/47816078/53088181-46c7fc80-3509-11e9-8435-2c38fee06f53.png">

**Comment by zdytch** [comment]
Same story for me

**Comment by ncpmt** [comment]
Same here. Did you find a solution?

**Comment by CharlotteBr28** [comment]
No not yet - It's still not working and I'm still waiting for an answer on the ticket, so if you find a way to solve this issue I'd be really interested to find out!

**Comment by CharlotteBr28** [comment]
Update on my ticket: 
After installing the plugin, I realized that the products that I put live on my WooCommerce after the installation were shown in my Facebook Catalogue. However, the products that were there before are still not synchronized even though the settings indicate that they should be.

When can I expect to receive some assistance?

**Comment by SilanBekjarov** [comment]
So what was the solution for this? I have the exact same problem. Everything looks fine, just doesnt show up on FB. Even after deleting my product catalogue on FB and resynching from the start with resetted plugin, nothing shows up on FB.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
