### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by thierrymaasdam** [facebookincubator/facebook-for-woocommerce#9]
Hi,

One of my clients recently reported a issue with the prices displayed on their Facebook Page, the prices in particular. Some of them are one (euro)cent off.

Screenshot: http://imgur.com/a/SRtl8

- The URL to the Facebook page is https://www.facebook.com/HipHuis/
- Wordpress version 4.8.1, WooCommerce is running on 3.1.1
- Extension/Plugin version 1.4.2
- There are currently 347 products of which 343 published online, as well as several misc products like gift wrapping used at checkout which aren’t synced to the Facebook Page
- Types of products are mostly ‘simple’
- No duplicate SKU’s in the system
- No customisation plugins directly influencing product types/data

If you could help me out, that'd be great.

Thanks — and have a nice weekend.

Yours,
Thierry

Vallonic on behalf of HipHuis

**Comment by thierrymaasdam** [comment]
Bump.

**Comment by tahoff** [comment]
This issue will be fixed in version 1.4.6. We're still waiting for WooCommerce to push version 1.4.5

**Comment by dmitridr** [comment]
Should be fixed in [v1.5.0,](https://github.com/facebookincubator/facebook-for-woocommerce/releases/download/v1.5.0/facebook-for-woocommerce-v1.5.0.zip) let us know if the problem reoccurs.
