### ISSUE TITLE
Implement Product Category Filters for Shop Sync

### ISSUE THREAD

**Issue by mqfellmeth** [facebookincubator/facebook-for-woocommerce#92]
It would be a great feature addition if you could filter the product sync by product categories. We have, for example, over 5,000 products, all of which are currently synced. However, only one product category that includes about 700 products is appropriate for the FB Shop page.

As it's an unreasonable amount of work to open up 4,300 products one at a time in WooCommerce in order to mark them do not display in the Shop page, we cannot currently use the Shop page. Allowing sync by product category would sync the 700 products only and then we could further individually mark any items within that category "do not display" as needed.

**Comment by dmitridr** [comment]
Hello,

Thanks for the suggestion, we'll prioritize this feature based on demand. 

I can suggest a small workaround in the meantime : You don't have to open up the products one at a time if you use the 'Hide' button on the WooCommerce screen when viewing all products. Still, that's a lot of clicking.

This is also slightly related to #34.

**Comment by mengyingdu** [comment]
@dmitridr Do you think they can use the product_data filter here? If not the expected category, unset the key before syncing? 
If so, you can adopt it [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproduct.php#L498) @mqfellmeth

**Comment by tnchuntic** [comment]
I have achieved it by hooking to the only filter that I can find to override the data.  :) 

```
**
 * -----------------------------------------------------------------------------
 *
 * Woo Product to Facebook filter by category
 * 
 * @since 3.5.2
 * @param int $id Product ID
 * @param array $product_data Product data array
 *
 * -----------------------------------------------------------------------------
 */
function wc_facebook_product_item_filter($product_data, $id) {

        // get terms of product by id
        $terms = get_the_terms($id, 'category');

        // don't sync
        if (!$terms || is_wp_error($terms)):
                return null;
        endif;

        // init flag
        $flag = false;
        
        // loop term and check fb sync
        foreach ($terms as $term):
                // acf field bool switch in category
                if (get_field('id_enable_sync_product', sprintf('category_%d', $term->term_id))):
                        $flag = true;
                        break;
                endif;
        endforeach;

        // return null if false
        if (!$flag):
                return null;
        endif;

        // return data if true
        return $product_data;
}

add_filter('facebook_for_woocommerce_integration_prepare_product', 'wc_facebook_product_item_filter', 10, 2);
```

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
