### ISSUE TITLE
Compatibily Issue with Advanced Bulk Edit Plugin

### ISSUE THREAD

**Issue by ifede84** [facebookincubator/facebook-for-woocommerce#95]
Hi All,

i've found a compatibility issue with Advanced Bulk Edit plugin: 

https://codecanyon.net/item/woocommerce-advanced-bulk-edit/8011417

Simply, editing items via advanced bulk edit doesn't start synchronizations. For example, editing items quantities or prices.

Advanced bulk edit is an inventory management plugin with 6,643 sales, actually.

I'm sorry if this post doesn't respect guidelines.

Thank you!

**Comment by dmitridr** [comment]
Hello,

Thanks for identifying this compatibility issue. In general we are prioritizing compatibility fixes based on user demand, though if you find and fix the issue we are always willing to take your pull request!

This is probably related to #70 , because normal Bulk Edit is not working, so Advanced Bulk Edit probably wouldn't work as well.

**Comment by mengyingdu** [comment]
Hi @ifede84,

Update : Bulk Edit (WooCommerce product editor has been supported and works now). However, the bulk edit plugin is another plugin which is incompatible with our plugin.

My suggestion:
1) If the goal of using bulk edit plugin can be done by the built-in bulk edit in woocommerce, can you use that one instead?
2) If not, we are swapped within bugs fixes based on user demand, and will appreciate your pull request!

Thanks.

**Comment by ifede84** [comment]
Dear mengyingdu,

The plugin i was asking help for actually run with last facebook for woocommerce version: the plugin is this one, https://codecanyon.net/item/woocommerce-advanced-bulk-edit/8011417

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
