### ISSUE TITLE
Getting error as Catalog Can't Be Synced

### ISSUE THREAD

**Issue by nishitmorakhia** [facebookincubator/facebook-for-woocommerce#957]
![Facebook for woocommerce error](https://user-images.githubusercontent.com/49756738/56365821-5fa21500-620f-11e9-90b7-099eef41799f.JPG)
Getting Error 
Catalog Can't Be Synced
A system error is preventing your catalog from syncing. You can still get website visitors and track sales, and we'll notify you when your catalog is ready to sync.

**Comment by nishitmorakhia** [comment]
Duplicate of #947

**Comment by keyurpatel007** [comment]
same issue i face right now. request to say me how to solved it.
![fb error](https://user-images.githubusercontent.com/49774253/56405212-e6df9f00-6288-11e9-9763-62c3019c0aaf.png)
