### ISSUE TITLE
Variant Description for Variable Products Not Update after Changing Variant Option in Facebook Product page

### ISSUE THREAD

**Issue by mediaworksmt** [facebookincubator/facebook-for-woocommerce#97]
I am the web developer for a client who has a WooCommerce shop and a Facebook business page.

Recently we installed the Facebook for WooCommerce plugin, went through the process of setting it up and synchronizing the products to Facebook.

All seems to work well, except for that the products which are "Variable Products" are not carrying the main description through to Facebook. All other "Simple Products", the description carries over to Facebook just fine.

To be clear, this is an issue with all of the "Variable Products", and the only description entered on these is in the main description: The "Variable Products" do not have a short description, nor a per-variation description.

**Steps to Recreate This Issue:**

1. Create one or more "Variable Products" in WooCommerce, with attributes and variations as would typically be done
2. Install the Facebook for WooCommerce plugin
3. Configure the plugin to link to a Facebook page
4. Proceed to synchronize with Facebook, allowing time for processing
5. View the "Variable Products" on the Shop tab of the Facebook page
6. Notice that the text of the main description is missing

**Comment by dmitridr** [comment]
Hello,

Good find. The workaround would be to copy the main description into the 'Facebook Description' field of the variable product, then the main description will sync. 

However, this should be an easy fix to default to the parent description if the children have no description. We'll fix it.

**Comment by mengyingdu** [comment]
Hi @mediaworksmt ,

We support variant description in v1.6.6 in you check our changelog, can you try to upgrade?
However, we have another bug from our shop team: 
1. after changing the variant option value, the description doesn't update.
2. If you check the variant description from the product id link (on your right panel of your Woo product editor), they have been sync correctly.

I have flag this issue to shop team and will keep this issue open for any update.

Thanks.

**Comment by mengyingdu** [comment]
Variable products' description can update now, this is fixed by our shop team.
