### ISSUE TITLE
Server CPU Time Usage Maxes Out

### ISSUE THREAD

**Issue by creativeapparelstore** [facebookincubator/facebook-for-woocommerce#98]
Hi there,

I appear to have an issue where when force-sync'ing my products, the server overloads. I have 140 products.

I am currently with  SiteGround, and when I was not using the plugin, there was no issue of restriction. Upon enable the plugin and force-sync'ing I get CPU Time Usage overload.

How do I go about having this plugin work?

This is from the support desk at SiteGround: "It appears that the admin-ajax.php activity is coming from the multiple request on your plugin".

Thanks,

**Comment by dmitridr** [comment]
Hi, 

Thanks for your patience. I guess this is the same issue you mentioned in #83? If so I'll close that one and we can continue the discussion here.
My recommendation is as follows:

- Try disabling all other plugins, does the cpu time issue persist?
- Try older versions, you were using v1.6.0 before, did it have the same problem?

Unfortunately I don't have any good answer why the CPU time is being taken up without knowing more about what is going on on your side. Perhaps we added too many DB calls in recent versions, we can do an audit and try to consolidate those and increase the perf, but this will take some time.

Looking at our internal logs for your site, the sync eventually finishes (after ~24hrs?) though the server is likely overloaded for some time.

**Comment by dmitridr** [comment]
Update : @mengyingdu is working on a complete overhaul of product sync in 1.8.0 (spoiler: it's much much faster and uses much less CPU!). So we hope to resolve this problem in the near future.

**Comment by dmitridr** [comment]
Hello, please try v1.8.2 https://github.com/facebookincubator/facebook-for-woocommerce/releases
It uses up to 60x less CPU time thanks to the great work by @mengyingdu. The products are uploaded in a feed file now.

We also greatly reduced the admin-ajax activity as described in #334
