### ISSUE TITLE
Bilingual wordpress webshop - bilingual facebook shop

### ISSUE THREAD

**Issue by JN-83** [facebookincubator/facebook-for-woocommerce#996]
We have a Dutch-French wordpress webshop (translation handled by WPML), on which i've installed the facebook for woocommerce plugin. I now see all products listed on the facebook webshop on our page (which is bilingual, which version is shown depends on facebook language user settings.

Is there any way to show Dutch products on the Dutch facebook shop and likewise for French products?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
