### ISSUE TITLE
Not all products visible on Facebook page

### ISSUE THREAD

**Issue by jeffceriello** [facebookincubator/facebook-for-woocommerce#997]
Hi,

My shop has around 12k products and when I sync them it says

12569 products in your inventory

but when I go on Facebook shop it says there are only 7.2k.

I have tried resyncing them but it doesn't update. What could it be?

Thanks

![Screenshot 2019-05-15 at 18 50 12](https://user-images.githubusercontent.com/5859601/57794075-19bf6a80-7743-11e9-8679-bac6e3d4a347.png)

![Screenshot 2019-05-15 at 18 56 24](https://user-images.githubusercontent.com/5859601/57794098-293eb380-7743-11e9-9bb5-dc34b5fe942a.png)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
