### ISSUE TITLE
Problem changing Facebook page

### ISSUE THREAD

**Issue by gavinstockden** [facebookincubator/facebook-for-woocommerce#999]
Hi 

I have recently cloned a Wordpress site for a client. She had an existing shop (Vagabond) and now wants a new shop (Karat). When going into the settings for this plugin on the cloned Karat site I was unable to change the page from the Vagabond page to the Karat page (Edit was greyed out). When I tried to delete the settings, it said there is a temporary problem and I am unable to delete the settings. I tried to delete the plugin entirely, but when I reinstall it is still set to Vagabond.

I even went in through ftp to try and see if the plugin had left any files there but I don't see anything in the plugin folder. Are there some settings left in a table somewhere I need to delete? How can I remove Vagabond from the plugin settings to set it up with Karat?

And another thing, at some point I reset the API on the Karat FB shop settings while trying to get this to work. This imported the Karat products into the Vagabond FB store. I then went into the Vagabond FB store settings and reset the API on that side. I also resynched the products, but now the Karat products are still showing on the Vagabond FB Store. How do I remove those?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
